export const categories = [
  { id: 'crypto', name: 'Crypto & Security', tint: '#6a5a8c' },
  { id: 'converter', name: 'Converters', tint: '#96703f' },
  { id: 'web', name: 'Web', tint: '#3f6b91' },
  { id: 'development', name: 'Development', tint: '#4a7a58' },
  { id: 'network', name: 'Network', tint: '#3f7a75' },
  { id: 'text', name: 'Text', tint: '#875a6b' },
  { id: 'math', name: 'Math & Units', tint: '#847a44' },
  { id: 'media', name: 'Media', tint: '#8a1c3b' },
  { id: 'ai', name: 'Local AI', tint: '#5b5b8a' },
  { id: 'play', name: 'Play', tint: '#9c6440' },
  { id: 'utility', name: 'Utility', tint: '#5b6470' },
  { id: 'system', name: 'System', tint: '#6b7280' },
];

export const catalog = [
  {
    id: 'hash-text',
    name: 'Hash Text',
    tagline: 'MD5, SHA-1, SHA-256, SHA-512 digests',
    category: 'crypto',
    glyph: '#',
    icon: 'hash',
    tint: '#8b5cf6',
    keywords: ['hash', 'md5', 'sha', 'sha256', 'checksum', 'digest'],
    tag: 'jg-app-hash-text',
    widget: true,
    load: () => import('./hash-text.js'),
    settings: [
      { key: 'case', label: 'Output case', type: 'select', default: 'lower', options: [
        { value: 'lower', label: 'lowercase' },
        { value: 'upper', label: 'UPPERCASE' },
      ] },
    ],
  },
  {
    id: 'hmac-generator',
    name: 'HMAC',
    tagline: 'Keyed hash message authentication codes',
    category: 'crypto',
    glyph: 'H',
    icon: 'key',
    tint: '#7c3aed',
    keywords: ['hmac', 'sign', 'secret', 'signature', 'sha'],
    tag: 'jg-app-hmac',
    load: () => import('./hmac-generator.js'),
  },
  {
    id: 'encryption',
    name: 'Encrypt / Decrypt',
    tagline: 'AES-GCM text encryption with a passphrase',
    category: 'crypto',
    glyph: '🔒',
    icon: 'lock',
    tint: '#6d28d9',
    keywords: ['aes', 'encrypt', 'decrypt', 'cipher', 'password', 'gcm'],
    tag: 'jg-app-encryption',
    load: () => import('./encryption.js'),
  },
  {
    id: 'token-generator',
    name: 'Token Generator',
    tagline: 'Strong random passwords and API tokens',
    category: 'crypto',
    glyph: '⁂',
    icon: 'asterisk',
    tint: '#a855f7',
    keywords: ['password', 'token', 'random', 'secret', 'entropy'],
    tag: 'jg-app-token',
    widget: true,
    load: () => import('./token-generator.js'),
    settings: [
      { key: 'length', label: 'Default length', type: 'number', default: 32, min: 4, max: 512 },
      { key: 'symbols', label: 'Include symbols', type: 'switch', default: true },
    ],
  },
  {
    id: 'otp-generator',
    name: 'TOTP',
    tagline: 'Time based one-time passwords from a secret',
    category: 'crypto',
    glyph: '⏲',
    icon: 'timer',
    tint: '#9333ea',
    keywords: ['otp', 'totp', '2fa', 'mfa', 'authenticator'],
    tag: 'jg-app-otp',
    widget: true,
    load: () => import('./otp-generator.js'),
  },
  {
    id: 'basic-auth',
    name: 'Basic Auth',
    tagline: 'Build Authorization headers from credentials',
    category: 'crypto',
    glyph: 'Aa',
    icon: 'user',
    tint: '#7e22ce',
    keywords: ['basic', 'auth', 'header', 'authorization', 'base64'],
    tag: 'jg-app-basic-auth',
    load: () => import('./basic-auth.js'),
  },

  {
    id: 'rsa-keygen',
    name: 'Key Pair',
    tagline: 'Generate RSA and elliptic curve keys as PEM',
    category: 'crypto',
    glyph: 'PEM',
    icon: 'keyPair',
    tint: '#6d28d9',
    keywords: ['rsa', 'key', 'pair', 'pem', 'ecdsa', 'public', 'private', 'ssh'],
    tag: 'jg-app-rsa-keygen',
    load: () => import('./rsa-keygen.js'),
  },
  {
    id: 'password-strength',
    name: 'Password Strength',
    tagline: 'Entropy, weaknesses and time to crack',
    category: 'crypto',
    glyph: '◍',
    icon: 'gauge',
    tint: '#7c3aed',
    keywords: ['password', 'strength', 'entropy', 'crack', 'secure'],
    tag: 'jg-app-password-strength',
    load: () => import('./password-strength.js'),
  },

  {
    id: 'base64-converter',
    name: 'Base64',
    tagline: 'Encode and decode text or files',
    category: 'converter',
    glyph: '64',
    icon: 'swap',
    tint: '#f59e0b',
    keywords: ['base64', 'encode', 'decode', 'atob', 'btoa', 'data uri'],
    tag: 'jg-app-base64',
    load: () => import('./base64-converter.js'),
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    tagline: 'HEX, RGB, HSL, OKLCH and contrast checks',
    category: 'converter',
    glyph: '◐',
    icon: 'palette',
    tint: '#f97316',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'palette', 'contrast', 'wcag'],
    tag: 'jg-app-color',
    widget: true,
    load: () => import('./color-converter.js'),
  },
  {
    id: 'color-palette',
    name: 'Colour Palette',
    tagline: 'Tailwind style scales, a colour wheel and harmonies',
    category: 'converter',
    glyph: '▤',
    icon: 'swatches',
    tint: '#f97316',
    keywords: ['color', 'colour', 'palette', 'tailwind', 'wheel', 'scale', 'shades', 'harmony', 'swatch'],
    tag: 'jg-app-color-palette',
    window: { width: 1040, height: 900 },
    load: () => import('./color-palette.js'),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    tagline: 'camelCase, snake_case, kebab-case and more',
    category: 'converter',
    glyph: 'aA',
    icon: 'type',
    tint: '#d97706',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'title'],
    tag: 'jg-app-case',
    load: () => import('./case-converter.js'),
  },
  {
    id: 'date-converter',
    name: 'Date & Time',
    tagline: 'Unix timestamps, ISO 8601 and relative time',
    category: 'converter',
    glyph: '⌚',
    icon: 'clock',
    tint: '#ea580c',
    keywords: ['date', 'time', 'unix', 'epoch', 'timestamp', 'iso'],
    tag: 'jg-app-date',
    widget: true,
    load: () => import('./date-converter.js'),
  },
  {
    id: 'base-converter',
    name: 'Number Base',
    tagline: 'Binary, octal, decimal, hex and any base',
    category: 'converter',
    glyph: '01',
    icon: 'binary',
    tint: '#b45309',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'radix', 'base'],
    tag: 'jg-app-base-converter',
    load: () => import('./base-converter.js'),
  },
  {
    id: 'json-yaml',
    name: 'JSON ⇄ YAML',
    tagline: 'Convert between JSON and YAML documents',
    category: 'converter',
    glyph: 'Y',
    icon: 'swap',
    tint: '#f59e0b',
    keywords: ['yaml', 'json', 'convert', 'config'],
    tag: 'jg-app-json-yaml',
    load: () => import('./json-yaml.js'),
  },
  {
    id: 'text-encoder',
    name: 'Text Encoder',
    tagline: 'Binary, hex, unicode, NATO, morse and ROT13',
    category: 'converter',
    glyph: '01',
    icon: 'transform',
    tint: '#ea580c',
    keywords: ['binary', 'hex', 'unicode', 'nato', 'morse', 'rot13', 'escape', 'numeronym'],
    tag: 'jg-app-text-encoder',
    load: () => import('./text-encoder.js'),
  },
  {
    id: 'list-converter',
    name: 'List Converter',
    tagline: 'Sort, dedupe, wrap and rejoin lists',
    category: 'converter',
    glyph: '≡',
    icon: 'list',
    tint: '#d97706',
    keywords: ['list', 'sort', 'dedupe', 'join', 'split', 'lines', 'csv'],
    tag: 'jg-app-list-converter',
    load: () => import('./list-converter.js'),
  },
  {
    id: 'roman-numerals',
    name: 'Roman Numerals',
    tagline: 'Convert numbers to and from Roman numerals',
    category: 'converter',
    glyph: 'IV',
    icon: 'landmark',
    tint: '#c2410c',
    keywords: ['roman', 'numeral', 'number'],
    tag: 'jg-app-roman',
    load: () => import('./roman-numerals.js'),
  },

  {
    id: 'url-encoder',
    name: 'URL Encode',
    tagline: 'Percent-encode and decode URL components',
    category: 'web',
    glyph: '%',
    icon: 'percent',
    tint: '#0ea5e9',
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    tag: 'jg-app-url-encoder',
    load: () => import('./url-encoder.js'),
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    tagline: 'Break a URL into its parts and query params',
    category: 'web',
    glyph: '⋔',
    icon: 'link',
    tint: '#0284c7',
    keywords: ['url', 'parse', 'query', 'params', 'host'],
    tag: 'jg-app-url-parser',
    load: () => import('./url-parser.js'),
  },
  {
    id: 'html-entities',
    name: 'HTML Entities',
    tagline: 'Escape and unescape HTML entities',
    category: 'web',
    glyph: '&',
    icon: 'ampersand',
    tint: '#0369a1',
    keywords: ['html', 'entities', 'escape', 'unescape', 'amp'],
    tag: 'jg-app-html-entities',
    load: () => import('./html-entities.js'),
  },
  {
    id: 'jwt-parser',
    name: 'JWT Parser',
    tagline: 'Decode and inspect JSON Web Tokens',
    category: 'web',
    glyph: 'JWT',
    icon: 'badge',
    tint: '#0891b2',
    keywords: ['jwt', 'token', 'jose', 'claims', 'decode'],
    tag: 'jg-app-jwt',
    load: () => import('./jwt-parser.js'),
  },
  {
    id: 'keycode-info',
    name: 'Keycode Info',
    tagline: 'Inspect keyboard events key by key',
    category: 'web',
    glyph: '⌨',
    icon: 'keyboard',
    tint: '#0e7490',
    keywords: ['key', 'keycode', 'keyboard', 'event', 'which'],
    tag: 'jg-app-keycode',
    load: () => import('./keycode-info.js'),
  },
  {
    id: 'slugify',
    name: 'Slugify',
    tagline: 'Turn any string into a clean URL slug',
    category: 'web',
    glyph: '/',
    icon: 'slug',
    tint: '#155e75',
    keywords: ['slug', 'url', 'seo', 'permalink'],
    tag: 'jg-app-slugify',
    load: () => import('./slugify.js'),
  },
  {
    id: 'http-status',
    name: 'HTTP Status',
    tagline: 'Searchable reference of HTTP status codes',
    category: 'web',
    glyph: '200',
    icon: 'activity',
    tint: '#38bdf8',
    keywords: ['http', 'status', 'code', 'reference', '404', '500'],
    tag: 'jg-app-http-status',
    load: () => import('./http-status.js'),
  },

  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    tagline: 'Format, validate, minify and explore JSON',
    category: 'development',
    glyph: '{ }',
    icon: 'braces',
    tint: '#22c55e',
    keywords: ['json', 'format', 'pretty', 'minify', 'validate', 'tree'],
    tag: 'jg-app-json-formatter',
    load: () => import('./json-formatter.js'),
    settings: [
      { key: 'indent', label: 'Indent', type: 'select', default: '2', options: [
        { value: '2', label: '2 spaces' },
        { value: '4', label: '4 spaces' },
        { value: 'tab', label: 'Tab' },
      ] },
      { key: 'sortKeys', label: 'Sort keys', type: 'switch', default: false },
    ],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    tagline: 'Compare two JSON documents key by key',
    category: 'development',
    glyph: 'Δ',
    icon: 'gitCompare',
    tint: '#16a34a',
    keywords: ['json', 'diff', 'compare', 'changes', 'merge'],
    tag: 'jg-app-json-diff',
    load: () => import('./json-diff.js'),
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    tagline: 'Readable formatting for SQL statements',
    category: 'development',
    glyph: 'SQL',
    icon: 'database',
    tint: '#16a34a',
    keywords: ['sql', 'format', 'query', 'pretty', 'database'],
    tag: 'jg-app-sql-formatter',
    load: () => import('./sql-formatter.js'),
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    tagline: 'Indent and minify XML or HTML markup',
    category: 'development',
    glyph: '</>',
    icon: 'code',
    tint: '#15803d',
    keywords: ['xml', 'html', 'format', 'pretty', 'indent'],
    tag: 'jg-app-xml-formatter',
    load: () => import('./xml-formatter.js'),
  },
  {
    id: 'crontab-generator',
    name: 'Crontab',
    tagline: 'Explain cron expressions and preview next runs',
    category: 'development',
    glyph: '✳',
    icon: 'repeat',
    tint: '#4d7c0f',
    keywords: ['cron', 'crontab', 'schedule', 'job', 'timer'],
    tag: 'jg-app-crontab',
    load: () => import('./crontab-generator.js'),
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod',
    tagline: 'Unix permissions in octal and symbolic form',
    category: 'development',
    glyph: '755',
    icon: 'fileLock',
    tint: '#65a30d',
    keywords: ['chmod', 'permission', 'unix', 'octal', 'file'],
    tag: 'jg-app-chmod',
    load: () => import('./chmod-calculator.js'),
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    tagline: 'Test patterns with live matches and groups',
    category: 'development',
    glyph: '.*',
    icon: 'regex',
    tint: '#059669',
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test'],
    tag: 'jg-app-regex',
    load: () => import('./regex-tester.js'),
  },

  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    tagline: 'IPv4 CIDR ranges, masks and host counts',
    category: 'network',
    glyph: '/24',
    icon: 'network',
    tint: '#14b8a6',
    keywords: ['subnet', 'cidr', 'ipv4', 'netmask', 'network'],
    tag: 'jg-app-subnet',
    load: () => import('./subnet-calculator.js'),
  },
  {
    id: 'ip-converter',
    name: 'IP Converter',
    tagline: 'IPv4 in decimal, hex, binary and octal',
    category: 'network',
    glyph: 'IP',
    icon: 'globe',
    tint: '#0d9488',
    keywords: ['ip', 'ipv4', 'convert', 'decimal', 'binary'],
    tag: 'jg-app-ip-converter',
    load: () => import('./ip-converter.js'),
  },
  {
    id: 'mac-generator',
    name: 'MAC Address',
    tagline: 'Generate and reformat MAC addresses',
    category: 'network',
    glyph: 'MAC',
    icon: 'router',
    tint: '#0f766e',
    keywords: ['mac', 'address', 'ethernet', 'hardware', 'generate'],
    tag: 'jg-app-mac',
    load: () => import('./mac-generator.js'),
  },

  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    tagline: 'Placeholder copy in words, sentences or lists',
    category: 'text',
    glyph: 'L',
    icon: 'alignLeft',
    tint: '#ec4899',
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy', 'text'],
    tag: 'jg-app-lorem',
    load: () => import('./lorem-ipsum.js'),
  },
  {
    id: 'text-stats',
    name: 'Text Stats',
    tagline: 'Counts, reading time and character analysis',
    category: 'text',
    glyph: '∑',
    icon: 'chart',
    tint: '#db2777',
    keywords: ['text', 'stats', 'count', 'words', 'characters', 'reading'],
    tag: 'jg-app-text-stats',
    load: () => import('./text-stats.js'),
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    tagline: 'Compare two texts line by line',
    category: 'text',
    glyph: '±',
    icon: 'compare',
    tint: '#be185d',
    keywords: ['diff', 'compare', 'changes', 'merge'],
    tag: 'jg-app-text-diff',
    load: () => import('./text-diff.js'),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown',
    tagline: 'Write markdown and preview the HTML',
    category: 'text',
    glyph: 'M↓',
    icon: 'fileText',
    tint: '#9d174d',
    keywords: ['markdown', 'md', 'preview', 'html', 'render'],
    tag: 'jg-app-markdown',
    load: () => import('./markdown-preview.js'),
  },

  {
    id: 'math-evaluator',
    name: 'Math Evaluator',
    tagline: 'Evaluate expressions with functions and constants',
    category: 'math',
    glyph: '=',
    icon: 'calculator',
    tint: '#eab308',
    keywords: ['math', 'calculator', 'evaluate', 'expression'],
    tag: 'jg-app-math',
    widget: true,
    load: () => import('./math-evaluator.js'),
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    tagline: 'Length, mass, data, temperature and time',
    category: 'math',
    glyph: '⇄',
    icon: 'scale',
    tint: '#ca8a04',
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'bytes'],
    tag: 'jg-app-units',
    load: () => import('./unit-converter.js'),
  },

  {
    id: 'qr-generator',
    name: 'QR Code',
    tagline: 'Generate scannable QR codes offline',
    category: 'media',
    glyph: '▦',
    icon: 'qr',
    tint: '#f43f5e',
    keywords: ['qr', 'code', 'barcode', 'scan', 'link'],
    tag: 'jg-app-qr',
    load: () => import('./qr-generator.js'),
  },

  {
    id: 'uuid-generator',
    name: 'UUID',
    tagline: 'Generate v4 and v7 identifiers in bulk',
    category: 'utility',
    glyph: 'ID',
    icon: 'fingerprint',
    tint: '#64748b',
    keywords: ['uuid', 'guid', 'id', 'random', 'v4', 'v7', 'ulid'],
    tag: 'jg-app-uuid',
    widget: true,
    load: () => import('./uuid-generator.js'),
  },
  {
    id: 'device-info',
    name: 'Device Info',
    tagline: 'Everything the browser knows about this device',
    category: 'utility',
    glyph: 'ⓘ',
    icon: 'monitor',
    tint: '#475569',
    keywords: ['device', 'browser', 'screen', 'agent', 'info'],
    tag: 'jg-app-device-info',
    load: () => import('./device-info.js'),
  },
  {
    id: 'clock',
    name: 'Clock',
    tagline: 'World clocks, stopwatch and countdown timer',
    category: 'utility',
    glyph: '◷',
    icon: 'clock',
    tint: '#0ea5e9',
    keywords: ['clock', 'time', 'timezone', 'stopwatch', 'timer', 'world'],
    tag: 'jg-app-clock',
    widget: true,
    load: () => import('./clock.js'),
    settings: [
      { key: 'hour12', label: '12-hour time', type: 'switch', default: false },
      { key: 'seconds', label: 'Show seconds', type: 'switch', default: true },
    ],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    tagline: 'Month view with events saved per workspace',
    category: 'utility',
    glyph: '▤',
    icon: 'calendar',
    tint: '#ef4444',
    keywords: ['calendar', 'month', 'date', 'events', 'schedule', 'agenda'],
    tag: 'jg-app-calendar',
    widget: true,
    load: () => import('./calendar.js'),
    settings: [
      { key: 'weekStart', label: 'Week starts on', type: 'select', default: 'mon', options: [
        { value: 'mon', label: 'Monday' },
        { value: 'sun', label: 'Sunday' },
      ] },
    ],
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    tagline: 'Track holdings, allocation and profit or loss',
    category: 'utility',
    glyph: '$',
    icon: 'trending',
    tint: '#4a7a58',
    keywords: ['portfolio', 'stocks', 'shares', 'investing', 'profit', 'loss', 'allocation', 'crypto', 'positions'],
    tag: 'jg-app-portfolio',
    widget: true,
    window: { width: 1040, height: 900 },
    load: () => import('./portfolio.js'),
    settings: [
      { key: 'currency', label: 'Currency', type: 'select', default: 'USD', options: [
        { value: 'USD', label: 'USD' }, { value: 'EUR', label: 'EUR' }, { value: 'GBP', label: 'GBP' },
        { value: 'CHF', label: 'CHF' }, { value: 'CAD', label: 'CAD' }, { value: 'AUD', label: 'AUD' },
        { value: 'JPY', label: 'JPY' }, { value: 'AED', label: 'AED' },
      ] },
      { key: 'provider', label: 'Price provider', type: 'select', default: 'manual', options: [
        { value: 'manual', label: 'Manual prices' },
        { value: 'finnhub', label: 'Finnhub' },
        { value: 'twelvedata', label: 'Twelve Data' },
        { value: 'coingecko', label: 'CoinGecko' },
      ] },
    ],
  },
  {
    id: 'notes',
    name: 'Notes',
    tagline: 'Quick scratch notes saved to this workspace',
    category: 'utility',
    glyph: '✎',
    icon: 'pencil',
    tint: '#0891b2',
    keywords: ['notes', 'scratch', 'write', 'memo'],
    tag: 'jg-app-notes',
    widget: true,
    load: () => import('./notes.js'),
  },
  {
    id: 'todo',
    name: 'Tasks',
    tagline: 'A lightweight checklist per workspace',
    category: 'utility',
    glyph: '✓',
    icon: 'checkSquare',
    tint: '#16a34a',
    keywords: ['todo', 'task', 'checklist', 'done'],
    tag: 'jg-app-todo',
    widget: true,
    load: () => import('./todo.js'),
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    tagline: 'Convert, resize and compress images in the browser',
    category: 'media',
    glyph: 'IMG',
    icon: 'image',
    tint: '#e11d48',
    keywords: ['image', 'convert', 'resize', 'compress', 'png', 'jpeg', 'webp'],
    tag: 'jg-app-image-converter',
    load: () => import('./image-converter.js'),
  },
  {
    id: 'media-converter',
    name: 'Video & Audio',
    tagline: 'Transcode video and audio with WebAssembly',
    category: 'media',
    glyph: 'AV',
    icon: 'film',
    tint: '#be123c',
    keywords: ['video', 'audio', 'convert', 'ffmpeg', 'mp4', 'webm', 'mp3', 'gif', 'transcode'],
    tag: 'jg-app-media-converter',
    load: () => import('./media-converter.js'),
  },

  {
    id: 'ai-chat',
    name: 'AI Chat',
    tagline: 'Chat with a model running on this device',
    category: 'ai',
    glyph: 'AI',
    icon: 'sparkles',
    tint: '#a855f7',
    keywords: ['ai', 'chat', 'llm', 'webllm', 'assistant', 'local'],
    tag: 'jg-app-ai-chat',
    widget: true,
    load: () => import('./ai-chat.js'),
    settings: [
      { key: 'system', label: 'System prompt', type: 'text', default: 'You are a concise, accurate assistant for developers.' },
    ],
  },
  {
    id: 'ai-code',
    name: 'AI Code',
    tagline: 'Explain, review, document and convert code',
    category: 'ai',
    glyph: 'AIC',
    icon: 'codeSparkle',
    tint: '#9333ea',
    keywords: ['ai', 'code', 'explain', 'review', 'refactor', 'tests', 'llm'],
    tag: 'jg-app-ai-code',
    load: () => import('./ai-code.js'),
  },
  {
    id: 'ai-writer',
    name: 'AI Writer',
    tagline: 'Summarise, rewrite, translate and proofread',
    category: 'ai',
    glyph: 'AIW',
    icon: 'pencil',
    tint: '#7e22ce',
    keywords: ['ai', 'write', 'summarise', 'translate', 'rewrite', 'commit'],
    tag: 'jg-app-ai-writer',
    load: () => import('./ai-writer.js'),
  },
  {
    id: 'ai-translate',
    name: 'Translate',
    tagline: 'Translate text with a model on this device',
    category: 'ai',
    glyph: '文',
    icon: 'languages',
    tint: '#8b5cf6',
    keywords: ['translate', 'language', 'ai', 'localise', 'localize', 'spanish', 'french', 'japanese'],
    tag: 'jg-app-ai-translate',
    window: { width: 980, height: 760 },
    load: () => import('./ai-translate.js'),
    settings: [
      { key: 'target', label: 'Default target language', type: 'text', default: 'English' },
      { key: 'auto', label: 'Translate as I type', type: 'switch', default: false },
    ],
  },
  {
    id: 'ai-regex',
    name: 'AI Regex',
    tagline: 'Describe a pattern and get a tested regex',
    category: 'ai',
    glyph: 'AIR',
    icon: 'regex',
    tint: '#c026d3',
    keywords: ['ai', 'regex', 'pattern', 'generate', 'explain'],
    tag: 'jg-app-ai-regex',
    load: () => import('./ai-regex.js'),
  },

  {
    id: 'dns-lookup',
    name: 'DNS Lookup',
    tagline: 'Dig style record lookups over DNS-over-HTTPS',
    category: 'network',
    glyph: 'DNS',
    icon: 'server2',
    tint: '#0f766e',
    keywords: ['dns', 'dig', 'nslookup', 'records', 'mx', 'txt', 'ns', 'ptr', 'domain'],
    tag: 'jg-app-dns-lookup',
    window: { width: 820, height: 780 },
    load: () => import('./dns-lookup.js'),
    settings: [
      { key: 'resolver', label: 'Resolver', type: 'select', default: 'cloudflare', options: [
        { value: 'cloudflare', label: 'Cloudflare' },
        { value: 'google', label: 'Google' },
      ] },
    ],
  },

  {
    id: 'speed-test',
    name: 'Speed Test',
    tagline: 'Measure download, upload, latency and jitter',
    category: 'network',
    glyph: 'Mb',
    icon: 'gauge2',
    tint: '#0d9488',
    keywords: ['speed', 'test', 'bandwidth', 'download', 'upload', 'latency', 'ping', 'internet'],
    tag: 'jg-app-speed-test',
    load: () => import('./speed-test.js'),
    settings: [
      { key: 'server', label: 'Test server', type: 'select', default: 'cloudflare', options: [
        { value: 'cloudflare', label: 'Cloudflare' },
        { value: 'origin', label: 'This server' },
      ] },
    ],
  },

  {
    id: 'emoji-picker',
    name: 'Emoji Picker',
    tagline: 'Browse, search and copy emoji with their code points',
    category: 'text',
    glyph: '☺',
    icon: 'emoji',
    keywords: ['emoji', 'unicode', 'smiley', 'symbol', 'picker', 'copy'],
    tag: 'jg-app-emoji-picker',
    window: { width: 880, height: 760 },
    load: () => import('./emoji-picker.js'),
  },
  {
    id: 'unicode-tables',
    name: 'Unicode Tables',
    tagline: 'Browse Unicode blocks and inspect any character',
    category: 'text',
    glyph: 'U+',
    icon: 'glyphs',
    keywords: ['unicode', 'character', 'code point', 'utf-8', 'entity', 'symbol', 'charmap'],
    tag: 'jg-app-unicode-tables',
    window: { width: 920, height: 780 },
    load: () => import('./unicode-tables.js'),
  },
  {
    id: 'drum-kit',
    name: 'Drum Kit',
    tagline: 'Play pads and build a 16 step beat',
    category: 'play',
    glyph: '🥁',
    icon: 'drum',
    keywords: ['drum', 'kit', 'beat', 'sequencer', 'music', 'pads', 'rhythm'],
    tag: 'jg-app-drum-kit',
    window: { width: 900, height: 820 },
    load: () => import('./drum-kit.js'),
  },
  {
    id: 'api-spec',
    name: 'API Spec Editor',
    tagline: 'Edit and check OpenAPI documents',
    category: 'development',
    glyph: 'API',
    icon: 'spec',
    keywords: ['openapi', 'swagger', 'api', 'spec', 'rest', 'yaml', 'schema', 'lint'],
    tag: 'jg-app-api-spec',
    window: { width: 1120, height: 860 },
    load: () => import('./api-spec.js'),
  },
  {
    id: 'exif-editor',
    name: 'Exif Metadata',
    tagline: 'Read and strip metadata from JPEG photos',
    category: 'media',
    glyph: 'EX',
    icon: 'exif',
    keywords: ['exif', 'metadata', 'photo', 'jpeg', 'gps', 'privacy', 'strip'],
    tag: 'jg-app-exif-editor',
    window: { width: 900, height: 800 },
    load: () => import('./exif-editor.js'),
  },
  {
    id: 'mp3-metadata',
    name: 'MP3 Metadata',
    tagline: 'Edit ID3 tags and artwork on MP3 files',
    category: 'media',
    glyph: 'ID3',
    icon: 'music',
    keywords: ['mp3', 'id3', 'tags', 'metadata', 'music', 'artwork', 'album'],
    tag: 'jg-app-mp3-metadata',
    window: { width: 940, height: 820 },
    load: () => import('./mp3-metadata.js'),
  },
  {
    id: 'docker-compose',
    name: 'Docker Compose',
    tagline: 'Convert docker run commands to compose files',
    category: 'development',
    glyph: '🐳',
    icon: 'docker',
    keywords: ['docker', 'compose', 'container', 'run', 'yaml', 'devops'],
    tag: 'jg-app-docker-compose',
    window: { width: 1100, height: 800 },
    load: () => import('./docker-compose.js'),
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    tagline: 'Generate deployment, service and ingress manifests',
    category: 'development',
    glyph: 'K8s',
    icon: 'helm',
    keywords: ['kubernetes', 'k8s', 'manifest', 'deployment', 'service', 'ingress', 'yaml', 'devops'],
    tag: 'jg-app-kubernetes',
    window: { width: 1140, height: 880 },
    load: () => import('./kubernetes.js'),
  },
  {
    id: 'morse-code',
    name: 'Morse Code',
    tagline: 'Translate text to Morse and play it back',
    category: 'converter',
    glyph: '.-',
    icon: 'morse',
    keywords: ['morse', 'code', 'telegraph', 'signal', 'sos', 'decode'],
    tag: 'jg-app-morse-code',
    window: { width: 760, height: 820 },
    load: () => import('./morse-code.js'),
  },
  {
    id: 'iban-validator',
    name: 'IBAN Validator',
    tagline: 'Check bank account numbers and read their parts',
    category: 'utility',
    glyph: 'IB',
    icon: 'bank',
    keywords: ['iban', 'bank', 'account', 'sepa', 'validate', 'check digits', 'bic'],
    tag: 'jg-app-iban-validator',
    window: { width: 720, height: 720 },
    load: () => import('./iban-validator.js'),
  },
  {
    id: 'svg-placeholder',
    name: 'Placeholder SVG',
    tagline: 'Generate placeholder images as inline SVG',
    category: 'media',
    glyph: '▢',
    icon: 'frame',
    keywords: ['placeholder', 'svg', 'image', 'mockup', 'dummy', 'data uri'],
    tag: 'jg-app-svg-placeholder',
    window: { width: 860, height: 900 },
    load: () => import('./svg-placeholder.js'),
  },
  {
    id: 'ascii-art',
    name: 'ASCII Art',
    tagline: 'Text banners and image to ASCII conversion',
    category: 'media',
    glyph: 'A',
    icon: 'ascii',
    keywords: ['ascii', 'art', 'banner', 'figlet', 'text', 'image', 'terminal'],
    tag: 'jg-app-ascii-art',
    window: { width: 900, height: 860 },
    load: () => import('./ascii-art.js'),
  },
  {
    id: 'css-gradient',
    name: 'Gradient Maker',
    tagline: 'Build CSS gradients with draggable colour stops',
    category: 'web',
    glyph: '▞',
    icon: 'gradient',
    keywords: ['css', 'gradient', 'linear', 'radial', 'conic', 'background', 'colour', 'color'],
    tag: 'jg-app-css-gradient',
    window: { width: 780, height: 860 },
    load: () => import('./css-gradient.js'),
  },
  {
    id: 'css-animation',
    name: 'CSS Animation',
    tagline: 'Keyframe presets with a cubic-bezier editor',
    category: 'web',
    glyph: '◠',
    icon: 'motion',
    keywords: ['css', 'animation', 'keyframes', 'easing', 'cubic-bezier', 'transition', 'motion'],
    tag: 'jg-app-css-animation',
    window: { width: 820, height: 900 },
    load: () => import('./css-animation.js'),
  },
  {
    id: 'jsx-svg',
    name: 'JSX to SVG',
    tagline: 'Convert React components to SVG and back',
    category: 'development',
    glyph: '<>',
    icon: 'jsx',
    keywords: ['jsx', 'react', 'svg', 'component', 'icon', 'convert', 'tsx'],
    tag: 'jg-app-jsx-svg',
    window: { width: 980, height: 780 },
    load: () => import('./jsx-svg.js'),
  },
  {
    id: 'svg-editor',
    name: 'SVG Studio',
    tagline: 'View, clean, recolour and export SVG',
    category: 'media',
    glyph: 'SVG',
    icon: 'vector',
    tint: '#e11d48',
    keywords: ['svg', 'vector', 'viewer', 'editor', 'optimise', 'optimize', 'icon', 'minify', 'png'],
    tag: 'jg-app-svg-editor',
    window: { width: 1080, height: 860 },
    load: () => import('./svg-editor.js'),
  },

  {
    id: 'voice-recorder',
    name: 'Voice Recorder',
    tagline: 'Record audio and transcribe it on this device',
    category: 'media',
    glyph: '●',
    icon: 'mic',
    tint: '#be123c',
    keywords: ['voice', 'record', 'audio', 'memo', 'transcribe', 'whisper', 'speech', 'dictate', 'notes'],
    tag: 'jg-app-voice-recorder',
    window: { width: 860, height: 880 },
    load: () => import('./voice-recorder.js'),
    settings: [
      { key: 'live', label: 'Live captions while recording', type: 'switch', default: true },
      { key: 'language', label: 'Transcription language', type: 'select', default: 'auto', options: [
        { value: 'auto', label: 'Detect' },
        { value: 'english', label: 'English' },
        { value: 'spanish', label: 'Spanish' },
        { value: 'french', label: 'French' },
        { value: 'german', label: 'German' },
        { value: 'persian', label: 'Farsi' },
        { value: 'arabic', label: 'Arabic' },
        { value: 'japanese', label: 'Japanese' },
      ] },
    ],
  },

  {
    id: 'mirror',
    name: 'Mirror',
    tagline: 'Camera mirror with an adjustable ring light',
    category: 'media',
    glyph: '◲',
    icon: 'mirror',
    tint: '#f43f5e',
    keywords: ['mirror', 'camera', 'webcam', 'ring light', 'selfie', 'makeup'],
    tag: 'jg-app-mirror',
    window: { width: 760, height: 860 },
    load: () => import('./mirror.js'),
    settings: [
      { key: 'glow', label: 'Ring light level', type: 'number', default: 70, min: 0, max: 100 },
      { key: 'warmth', label: 'Warmth', type: 'number', default: 20, min: 0, max: 100 },
    ],
  },
  {
    id: 'screenshot',
    name: 'Screenshot Studio',
    tagline: 'Capture, annotate, blur and compare screenshots',
    category: 'media',
    glyph: '⌗',
    icon: 'screenshot',
    tint: '#e11d48',
    keywords: ['screenshot', 'capture', 'annotate', 'blur', 'redact', 'crop', 'arrow', 'before after'],
    tag: 'jg-app-screenshot',
    window: { width: 1080, height: 900 },
    load: () => import('./screenshot.js'),
  },

  {
    id: 'tuner',
    name: 'Tuner',
    tagline: 'Tune a guitar, bass or ukulele by ear or mic',
    category: 'play',
    glyph: '♩',
    icon: 'tuning',
    tint: '#d97706',
    keywords: ['tuner', 'guitar', 'bass', 'ukulele', 'pitch', 'tune', 'strings', 'music'],
    tag: 'jg-app-tuner',
    window: { width: 700, height: 780 },
    load: () => import('./tuner.js'),
    settings: [
      { key: 'reference', label: 'Reference pitch (A4)', type: 'number', default: 440, min: 415, max: 466 },
    ],
  },
  {
    id: 'midi-keyboard',
    name: 'MIDI Keyboard',
    tagline: 'Playable synth with computer keyboard and MIDI input',
    category: 'play',
    glyph: '♪',
    icon: 'piano',
    tint: '#f59e0b',
    keywords: ['midi', 'piano', 'keyboard', 'synth', 'music', 'notes', 'audio'],
    tag: 'jg-app-midi-keyboard',
    window: { width: 900, height: 720 },
    load: () => import('./midi-keyboard.js'),
  },
  {
    id: 'game-2048',
    name: '2048',
    tagline: 'Slide and merge tiles to reach 2048',
    category: 'play',
    glyph: '2048',
    icon: 'blocks',
    tint: '#eab308',
    keywords: ['game', '2048', 'puzzle', 'tiles', 'merge'],
    tag: 'jg-app-game-2048',
    window: { width: 660, height: 880 },
    load: () => import('./game-2048.js'),
  },
  {
    id: 'game-minesweeper',
    name: 'Minesweeper',
    tagline: 'Clear the grid without hitting a mine',
    category: 'play',
    glyph: '✱',
    icon: 'bomb',
    tint: '#d97706',
    keywords: ['game', 'minesweeper', 'mines', 'puzzle', 'grid'],
    tag: 'jg-app-game-minesweeper',
    window: { width: 940, height: 840 },
    load: () => import('./game-minesweeper.js'),
  },
  {
    id: 'game-snake',
    name: 'Snake',
    tagline: 'Eat, grow and do not bite yourself',
    category: 'play',
    glyph: '~',
    icon: 'snake',
    tint: '#ca8a04',
    keywords: ['game', 'snake', 'arcade', 'classic'],
    tag: 'jg-app-game-snake',
    window: { width: 700, height: 900 },
    load: () => import('./game-snake.js'),
  },

  {
    id: 'settings',
    name: 'Settings',
    tagline: 'Appearance, home screen, workspaces and data',
    category: 'system',
    glyph: '⚙',
    icon: 'cog',
    tint: '#a1a1aa',
    keywords: ['settings', 'preferences', 'theme', 'workspace', 'config'],
    tag: 'jg-app-settings',
    system: true,
    load: () => import('./settings-app.js'),
  },
];
