export const categories = [
  { id: 'crypto', name: 'Crypto & Security', tint: '#8b5cf6' },
  { id: 'converter', name: 'Converters', tint: '#f59e0b' },
  { id: 'web', name: 'Web', tint: '#0ea5e9' },
  { id: 'development', name: 'Development', tint: '#22c55e' },
  { id: 'network', name: 'Network', tint: '#14b8a6' },
  { id: 'text', name: 'Text', tint: '#ec4899' },
  { id: 'math', name: 'Math & Units', tint: '#eab308' },
  { id: 'media', name: 'Media', tint: '#f43f5e' },
  { id: 'utility', name: 'Utility', tint: '#64748b' },
  { id: 'system', name: 'System', tint: '#a1a1aa' },
];

export const catalog = [
  {
    id: 'hash-text',
    name: 'Hash Text',
    tagline: 'MD5, SHA-1, SHA-256, SHA-512 digests',
    category: 'crypto',
    glyph: '#',
    icon: 'hash',
    tint: '#8b5cf6',
    keywords: ['hash', 'md5', 'sha', 'sha256', 'checksum', 'digest'],
    tag: 'jg-app-hash-text',
    widget: true,
    load: () => import('./hash-text.js'),
    settings: [
      { key: 'case', label: 'Output case', type: 'select', default: 'lower', options: [
        { value: 'lower', label: 'lowercase' },
        { value: 'upper', label: 'UPPERCASE' },
      ] },
    ],
  },
  {
    id: 'hmac-generator',
    name: 'HMAC',
    tagline: 'Keyed hash message authentication codes',
    category: 'crypto',
    glyph: 'H',
    icon: 'key',
    tint: '#7c3aed',
    keywords: ['hmac', 'sign', 'secret', 'signature', 'sha'],
    tag: 'jg-app-hmac',
    load: () => import('./hmac-generator.js'),
  },
  {
    id: 'encryption',
    name: 'Encrypt / Decrypt',
    tagline: 'AES-GCM text encryption with a passphrase',
    category: 'crypto',
    glyph: '🔒',
    icon: 'lock',
    tint: '#6d28d9',
    keywords: ['aes', 'encrypt', 'decrypt', 'cipher', 'password', 'gcm'],
    tag: 'jg-app-encryption',
    load: () => import('./encryption.js'),
  },
  {
    id: 'token-generator',
    name: 'Token Generator',
    tagline: 'Strong random passwords and API tokens',
    category: 'crypto',
    glyph: '⁂',
    icon: 'asterisk',
    tint: '#a855f7',
    keywords: ['password', 'token', 'random', 'secret', 'entropy'],
    tag: 'jg-app-token',
    widget: true,
    load: () => import('./token-generator.js'),
    settings: [
      { key: 'length', label: 'Default length', type: 'number', default: 32, min: 4, max: 512 },
      { key: 'symbols', label: 'Include symbols', type: 'switch', default: true },
    ],
  },
  {
    id: 'otp-generator',
    name: 'TOTP',
    tagline: 'Time based one-time passwords from a secret',
    category: 'crypto',
    glyph: '⏲',
    icon: 'timer',
    tint: '#9333ea',
    keywords: ['otp', 'totp', '2fa', 'mfa', 'authenticator'],
    tag: 'jg-app-otp',
    widget: true,
    load: () => import('./otp-generator.js'),
  },
  {
    id: 'basic-auth',
    name: 'Basic Auth',
    tagline: 'Build Authorization headers from credentials',
    category: 'crypto',
    glyph: 'Aa',
    icon: 'user',
    tint: '#7e22ce',
    keywords: ['basic', 'auth', 'header', 'authorization', 'base64'],
    tag: 'jg-app-basic-auth',
    load: () => import('./basic-auth.js'),
  },

  {
    id: 'base64-converter',
    name: 'Base64',
    tagline: 'Encode and decode text or files',
    category: 'converter',
    glyph: '64',
    icon: 'swap',
    tint: '#f59e0b',
    keywords: ['base64', 'encode', 'decode', 'atob', 'btoa', 'data uri'],
    tag: 'jg-app-base64',
    load: () => import('./base64-converter.js'),
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    tagline: 'HEX, RGB, HSL, OKLCH and contrast checks',
    category: 'converter',
    glyph: '◐',
    icon: 'palette',
    tint: '#f97316',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'palette', 'contrast', 'wcag'],
    tag: 'jg-app-color',
    widget: true,
    load: () => import('./color-converter.js'),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    tagline: 'camelCase, snake_case, kebab-case and more',
    category: 'converter',
    glyph: 'aA',
    icon: 'type',
    tint: '#d97706',
    keywords: ['case', 'camel', 'snake', 'kebab', 'pascal', 'title'],
    tag: 'jg-app-case',
    load: () => import('./case-converter.js'),
  },
  {
    id: 'date-converter',
    name: 'Date & Time',
    tagline: 'Unix timestamps, ISO 8601 and relative time',
    category: 'converter',
    glyph: '⌚',
    icon: 'clock',
    tint: '#ea580c',
    keywords: ['date', 'time', 'unix', 'epoch', 'timestamp', 'iso'],
    tag: 'jg-app-date',
    widget: true,
    load: () => import('./date-converter.js'),
  },
  {
    id: 'base-converter',
    name: 'Number Base',
    tagline: 'Binary, octal, decimal, hex and any base',
    category: 'converter',
    glyph: '01',
    icon: 'binary',
    tint: '#b45309',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'radix', 'base'],
    tag: 'jg-app-base-converter',
    load: () => import('./base-converter.js'),
  },
  {
    id: 'json-yaml',
    name: 'JSON ⇄ YAML',
    tagline: 'Convert between JSON and YAML documents',
    category: 'converter',
    glyph: 'Y',
    icon: 'swap',
    tint: '#f59e0b',
    keywords: ['yaml', 'json', 'convert', 'config'],
    tag: 'jg-app-json-yaml',
    load: () => import('./json-yaml.js'),
  },
  {
    id: 'roman-numerals',
    name: 'Roman Numerals',
    tagline: 'Convert numbers to and from Roman numerals',
    category: 'converter',
    glyph: 'IV',
    icon: 'landmark',
    tint: '#c2410c',
    keywords: ['roman', 'numeral', 'number'],
    tag: 'jg-app-roman',
    load: () => import('./roman-numerals.js'),
  },

  {
    id: 'url-encoder',
    name: 'URL Encode',
    tagline: 'Percent-encode and decode URL components',
    category: 'web',
    glyph: '%',
    icon: 'percent',
    tint: '#0ea5e9',
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    tag: 'jg-app-url-encoder',
    load: () => import('./url-encoder.js'),
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    tagline: 'Break a URL into its parts and query params',
    category: 'web',
    glyph: '⋔',
    icon: 'link',
    tint: '#0284c7',
    keywords: ['url', 'parse', 'query', 'params', 'host'],
    tag: 'jg-app-url-parser',
    load: () => import('./url-parser.js'),
  },
  {
    id: 'html-entities',
    name: 'HTML Entities',
    tagline: 'Escape and unescape HTML entities',
    category: 'web',
    glyph: '&',
    icon: 'ampersand',
    tint: '#0369a1',
    keywords: ['html', 'entities', 'escape', 'unescape', 'amp'],
    tag: 'jg-app-html-entities',
    load: () => import('./html-entities.js'),
  },
  {
    id: 'jwt-parser',
    name: 'JWT Parser',
    tagline: 'Decode and inspect JSON Web Tokens',
    category: 'web',
    glyph: 'JWT',
    icon: 'badge',
    tint: '#0891b2',
    keywords: ['jwt', 'token', 'jose', 'claims', 'decode'],
    tag: 'jg-app-jwt',
    load: () => import('./jwt-parser.js'),
  },
  {
    id: 'keycode-info',
    name: 'Keycode Info',
    tagline: 'Inspect keyboard events key by key',
    category: 'web',
    glyph: '⌨',
    icon: 'keyboard',
    tint: '#0e7490',
    keywords: ['key', 'keycode', 'keyboard', 'event', 'which'],
    tag: 'jg-app-keycode',
    load: () => import('./keycode-info.js'),
  },
  {
    id: 'slugify',
    name: 'Slugify',
    tagline: 'Turn any string into a clean URL slug',
    category: 'web',
    glyph: '/',
    icon: 'slug',
    tint: '#155e75',
    keywords: ['slug', 'url', 'seo', 'permalink'],
    tag: 'jg-app-slugify',
    load: () => import('./slugify.js'),
  },
  {
    id: 'http-status',
    name: 'HTTP Status',
    tagline: 'Searchable reference of HTTP status codes',
    category: 'web',
    glyph: '200',
    icon: 'activity',
    tint: '#38bdf8',
    keywords: ['http', 'status', 'code', 'reference', '404', '500'],
    tag: 'jg-app-http-status',
    load: () => import('./http-status.js'),
  },

  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    tagline: 'Format, validate, minify and explore JSON',
    category: 'development',
    glyph: '{ }',
    icon: 'braces',
    tint: '#22c55e',
    keywords: ['json', 'format', 'pretty', 'minify', 'validate', 'tree'],
    tag: 'jg-app-json-formatter',
    load: () => import('./json-formatter.js'),
    settings: [
      { key: 'indent', label: 'Indent', type: 'select', default: '2', options: [
        { value: '2', label: '2 spaces' },
        { value: '4', label: '4 spaces' },
        { value: 'tab', label: 'Tab' },
      ] },
      { key: 'sortKeys', label: 'Sort keys', type: 'switch', default: false },
    ],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    tagline: 'Readable formatting for SQL statements',
    category: 'development',
    glyph: 'SQL',
    icon: 'database',
    tint: '#16a34a',
    keywords: ['sql', 'format', 'query', 'pretty', 'database'],
    tag: 'jg-app-sql-formatter',
    load: () => import('./sql-formatter.js'),
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    tagline: 'Indent and minify XML or HTML markup',
    category: 'development',
    glyph: '</>',
    icon: 'code',
    tint: '#15803d',
    keywords: ['xml', 'html', 'format', 'pretty', 'indent'],
    tag: 'jg-app-xml-formatter',
    load: () => import('./xml-formatter.js'),
  },
  {
    id: 'crontab-generator',
    name: 'Crontab',
    tagline: 'Explain cron expressions and preview next runs',
    category: 'development',
    glyph: '✳',
    icon: 'repeat',
    tint: '#4d7c0f',
    keywords: ['cron', 'crontab', 'schedule', 'job', 'timer'],
    tag: 'jg-app-crontab',
    load: () => import('./crontab-generator.js'),
  },
  {
    id: 'chmod-calculator',
    name: 'Chmod',
    tagline: 'Unix permissions in octal and symbolic form',
    category: 'development',
    glyph: '755',
    icon: 'fileLock',
    tint: '#65a30d',
    keywords: ['chmod', 'permission', 'unix', 'octal', 'file'],
    tag: 'jg-app-chmod',
    load: () => import('./chmod-calculator.js'),
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    tagline: 'Test patterns with live matches and groups',
    category: 'development',
    glyph: '.*',
    icon: 'regex',
    tint: '#059669',
    keywords: ['regex', 'regexp', 'pattern', 'match', 'test'],
    tag: 'jg-app-regex',
    load: () => import('./regex-tester.js'),
  },

  {
    id: 'subnet-calculator',
    name: 'Subnet Calculator',
    tagline: 'IPv4 CIDR ranges, masks and host counts',
    category: 'network',
    glyph: '/24',
    icon: 'network',
    tint: '#14b8a6',
    keywords: ['subnet', 'cidr', 'ipv4', 'netmask', 'network'],
    tag: 'jg-app-subnet',
    load: () => import('./subnet-calculator.js'),
  },
  {
    id: 'ip-converter',
    name: 'IP Converter',
    tagline: 'IPv4 in decimal, hex, binary and octal',
    category: 'network',
    glyph: 'IP',
    icon: 'globe',
    tint: '#0d9488',
    keywords: ['ip', 'ipv4', 'convert', 'decimal', 'binary'],
    tag: 'jg-app-ip-converter',
    load: () => import('./ip-converter.js'),
  },
  {
    id: 'mac-generator',
    name: 'MAC Address',
    tagline: 'Generate and reformat MAC addresses',
    category: 'network',
    glyph: 'MAC',
    icon: 'router',
    tint: '#0f766e',
    keywords: ['mac', 'address', 'ethernet', 'hardware', 'generate'],
    tag: 'jg-app-mac',
    load: () => import('./mac-generator.js'),
  },

  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    tagline: 'Placeholder copy in words, sentences or lists',
    category: 'text',
    glyph: 'L',
    icon: 'alignLeft',
    tint: '#ec4899',
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy', 'text'],
    tag: 'jg-app-lorem',
    load: () => import('./lorem-ipsum.js'),
  },
  {
    id: 'text-stats',
    name: 'Text Stats',
    tagline: 'Counts, reading time and character analysis',
    category: 'text',
    glyph: '∑',
    icon: 'chart',
    tint: '#db2777',
    keywords: ['text', 'stats', 'count', 'words', 'characters', 'reading'],
    tag: 'jg-app-text-stats',
    load: () => import('./text-stats.js'),
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    tagline: 'Compare two texts line by line',
    category: 'text',
    glyph: '±',
    icon: 'compare',
    tint: '#be185d',
    keywords: ['diff', 'compare', 'changes', 'merge'],
    tag: 'jg-app-text-diff',
    load: () => import('./text-diff.js'),
  },
  {
    id: 'markdown-preview',
    name: 'Markdown',
    tagline: 'Write markdown and preview the HTML',
    category: 'text',
    glyph: 'M↓',
    icon: 'fileText',
    tint: '#9d174d',
    keywords: ['markdown', 'md', 'preview', 'html', 'render'],
    tag: 'jg-app-markdown',
    load: () => import('./markdown-preview.js'),
  },

  {
    id: 'math-evaluator',
    name: 'Math Evaluator',
    tagline: 'Evaluate expressions with functions and constants',
    category: 'math',
    glyph: '=',
    icon: 'calculator',
    tint: '#eab308',
    keywords: ['math', 'calculator', 'evaluate', 'expression'],
    tag: 'jg-app-math',
    widget: true,
    load: () => import('./math-evaluator.js'),
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    tagline: 'Length, mass, data, temperature and time',
    category: 'math',
    glyph: '⇄',
    icon: 'scale',
    tint: '#ca8a04',
    keywords: ['unit', 'convert', 'length', 'weight', 'temperature', 'bytes'],
    tag: 'jg-app-units',
    load: () => import('./unit-converter.js'),
  },

  {
    id: 'qr-generator',
    name: 'QR Code',
    tagline: 'Generate scannable QR codes offline',
    category: 'media',
    glyph: '▦',
    icon: 'qr',
    tint: '#f43f5e',
    keywords: ['qr', 'code', 'barcode', 'scan', 'link'],
    tag: 'jg-app-qr',
    load: () => import('./qr-generator.js'),
  },

  {
    id: 'uuid-generator',
    name: 'UUID',
    tagline: 'Generate v4 and v7 identifiers in bulk',
    category: 'utility',
    glyph: 'ID',
    icon: 'fingerprint',
    tint: '#64748b',
    keywords: ['uuid', 'guid', 'id', 'random', 'v4', 'v7', 'ulid'],
    tag: 'jg-app-uuid',
    widget: true,
    load: () => import('./uuid-generator.js'),
  },
  {
    id: 'device-info',
    name: 'Device Info',
    tagline: 'Everything the browser knows about this device',
    category: 'utility',
    glyph: 'ⓘ',
    icon: 'monitor',
    tint: '#475569',
    keywords: ['device', 'browser', 'screen', 'agent', 'info'],
    tag: 'jg-app-device-info',
    load: () => import('./device-info.js'),
  },
  {
    id: 'clock',
    name: 'Clock',
    tagline: 'World clocks, stopwatch and countdown timer',
    category: 'utility',
    glyph: '◷',
    icon: 'clock',
    tint: '#0ea5e9',
    keywords: ['clock', 'time', 'timezone', 'stopwatch', 'timer', 'world'],
    tag: 'jg-app-clock',
    widget: true,
    load: () => import('./clock.js'),
    settings: [
      { key: 'hour12', label: '12-hour time', type: 'switch', default: false },
      { key: 'seconds', label: 'Show seconds', type: 'switch', default: true },
    ],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    tagline: 'Month view with events saved per workspace',
    category: 'utility',
    glyph: '▤',
    icon: 'calendar',
    tint: '#ef4444',
    keywords: ['calendar', 'month', 'date', 'events', 'schedule', 'agenda'],
    tag: 'jg-app-calendar',
    widget: true,
    load: () => import('./calendar.js'),
    settings: [
      { key: 'weekStart', label: 'Week starts on', type: 'select', default: 'mon', options: [
        { value: 'mon', label: 'Monday' },
        { value: 'sun', label: 'Sunday' },
      ] },
    ],
  },
  {
    id: 'notes',
    name: 'Notes',
    tagline: 'Quick scratch notes saved to this workspace',
    category: 'utility',
    glyph: '✎',
    icon: 'pencil',
    tint: '#0891b2',
    keywords: ['notes', 'scratch', 'write', 'memo'],
    tag: 'jg-app-notes',
    widget: true,
    load: () => import('./notes.js'),
  },
  {
    id: 'todo',
    name: 'Tasks',
    tagline: 'A lightweight checklist per workspace',
    category: 'utility',
    glyph: '✓',
    icon: 'checkSquare',
    tint: '#16a34a',
    keywords: ['todo', 'task', 'checklist', 'done'],
    tag: 'jg-app-todo',
    widget: true,
    load: () => import('./todo.js'),
  },
  {
    id: 'settings',
    name: 'Settings',
    tagline: 'Appearance, home screen, workspaces and data',
    category: 'system',
    glyph: '⚙',
    icon: 'gear',
    tint: '#a1a1aa',
    keywords: ['settings', 'preferences', 'theme', 'workspace', 'config'],
    tag: 'jg-app-settings',
    system: true,
    load: () => import('./settings-app.js'),
  },
];
