import { JGApp, define, html, css } from '../core/app.js';
import { generate, describe, inspect } from '../lib/ssh-keys.js';
import { copyText, download } from '../core/util.js';

const sheet = css`
  .app { container-type: inline-size; }
  .art {
    font: 12px/1.25 var(--font-mono);
    white-space: pre;
    margin: 0;
    padding: 10px 12px;
    border-radius: var(--radius-md);
    background: color-mix(in srgb, var(--muted) 75%, transparent);
    border: 1px solid var(--border);
    overflow-x: auto;
  }
  .marks { display: grid; grid-template-columns: auto 1fr; gap: 6px 12px; font-size: 12.5px; align-items: baseline; }
  .marks dt { color: var(--muted-foreground); }
  .marks dd { margin: 0; font-family: var(--font-mono); overflow-wrap: anywhere; }
  .pair { display: grid; grid-template-columns: minmax(0, 1fr) 128px; gap: 12px; align-items: start; }
  .pair .stack { padding-top: 22px; }
  @container (max-width: 620px) {
    .pair { grid-template-columns: minmax(0, 1fr); }
    .pair .stack { padding-top: 0; flex-direction: row; }
  }
  .warn {
    font-size: 12.5px;
    color: var(--muted-foreground);
    border-left: 2px solid color-mix(in srgb, var(--ring) 60%, transparent);
    padding-left: 10px;
  }
  .opts { display: flex; flex-wrap: wrap; gap: 6px 14px; }
  .opts label { display: inline-flex; align-items: center; gap: 6px; font-size: 12.5px; }
`;

const TYPES = [
  { value: 'ed25519', label: 'Ed25519 (recommended)' },
  { value: 'ecdsa-256', label: 'ECDSA nistp256' },
  { value: 'ecdsa-384', label: 'ECDSA nistp384' },
  { value: 'ecdsa-521', label: 'ECDSA nistp521' },
  { value: 'rsa-2048', label: 'RSA 2048' },
  { value: 'rsa-3072', label: 'RSA 3072' },
  { value: 'rsa-4096', label: 'RSA 4096' },
];

const RESTRICTIONS = [
  { value: 'restrict', label: 'restrict' },
  { value: 'no-pty', label: 'no-pty' },
  { value: 'no-agent-forwarding', label: 'no-agent-forwarding' },
  { value: 'no-port-forwarding', label: 'no-port-forwarding' },
  { value: 'no-X11-forwarding', label: 'no-X11-forwarding' },
];

class SshKeys extends JGApp {
  static appId = 'ssh-keys';
  static settings = [
    { key: 'type', label: 'Default key type', type: 'select', default: 'ed25519', options: TYPES },
  ];
  static styles = [...JGApp.styles, sheet];

  #mode = 'generate';
  #key = null;

  renderWidget() {
    this.paint(html`<div class="app" style="padding:12px">
      <div class="stack tight">
        <div class="label">SSH Keys</div>
        <div class="hint">Generate and inspect OpenSSH keys without leaving the browser.</div>
      </div>
    </div>`);
  }

  renderApp() {
    this.paint(html`<div class="app">
      <jg-tabs id="mode"></jg-tabs>

      <div id="generate">
        <div class="row">
          <jg-field label="Key type">
            <jg-select id="type" size="sm" value="${this.config.get('type', 'ed25519')}" style="width:200px">
              ${TYPES.map((type) => html`<option value="${type.value}">${type.label}</option>`)}
            </jg-select>
          </jg-field>
          <jg-field label="Comment" class="grow">
            <jg-input id="comment" size="sm" placeholder="you@machine"></jg-input>
          </jg-field>
          <jg-button id="make" size="sm">Generate</jg-button>
        </div>

        <div id="result" hidden>
          <div class="pair">
            <jg-field label="Public key" hint="Append this to ~/.ssh/authorized_keys on the server">
              <jg-textarea id="pub" rows="3" mono readonly></jg-textarea>
            </jg-field>
            <div class="stack tight">
              <jg-button size="sm" variant="outline" id="copy-pub">Copy</jg-button>
              <jg-button size="sm" variant="ghost" id="save-pub">Save .pub</jg-button>
            </div>
          </div>

          <div class="pair">
            <jg-field label="Private key" hint="Keep this file at chmod 600 and never share it">
              <jg-textarea id="priv" rows="8" mono readonly></jg-textarea>
            </jg-field>
            <div class="stack tight">
              <jg-button size="sm" variant="outline" id="copy-priv">Copy</jg-button>
              <jg-button size="sm" variant="ghost" id="save-priv">Save key</jg-button>
            </div>
          </div>

          <p class="warn">
            The key is generated by your browser with WebCrypto and never leaves this tab. It is written without a
            passphrase, so add one locally with <code>ssh-keygen -p -f &lt;file&gt;</code> before you store it anywhere.
          </p>

          <div class="cols">
            <div class="stack tight">
              <div class="label">Fingerprints</div>
              <dl class="marks" id="marks"></dl>
            </div>
            <pre class="art" id="art"></pre>
          </div>

          <jg-field label="authorized_keys line" hint="Tick the limits you want in front of the key">
            <div class="opts" id="opts">
              ${RESTRICTIONS.map(
                (item) => html`<label><input type="checkbox" value="${item.value}" /> ${item.label}</label>`,
              )}
              <label>from= <jg-input id="from" size="sm" placeholder="10.0.0.0/8" style="width:150px"></jg-input></label>
              <label>command= <jg-input id="command" size="sm" placeholder="/usr/bin/backup" style="width:170px"></jg-input></label>
            </div>
            <jg-textarea id="authorized" rows="3" mono readonly></jg-textarea>
          </jg-field>
        </div>
      </div>

      <div id="inspect" hidden>
        <jg-field label="Public key line" hint="Paste an authorized_keys or known_hosts entry">
          <jg-textarea id="line" rows="4" mono placeholder="ssh-ed25519 AAAAC3Nza... you@machine"></jg-textarea>
        </jg-field>
        <div class="row">
          <jg-button size="sm" id="check">Inspect</jg-button>
          <span class="error" id="error"></span>
        </div>
        <div class="cols" id="found" hidden>
          <dl class="marks" id="found-marks"></dl>
          <pre class="art" id="found-art"></pre>
        </div>
      </div>
    </div>`);

    this.$('#mode').items = [
      { value: 'generate', label: 'Generate' },
      { value: 'inspect', label: 'Inspect' },
    ];
    this.$('#mode').value = this.#mode;
    this.on(this.$('#mode'), 'change', (event) => {
      this.#mode = event.detail.value;
      this.$('#generate').hidden = this.#mode !== 'generate';
      this.$('#inspect').hidden = this.#mode !== 'inspect';
    });

    this.on(this.$('#type'), 'change', (event) => this.config.set('type', event.detail.value));
    this.on(this.$('#make'), 'click', () => this.#generate());
    this.on(this.$('#check'), 'click', () => this.#inspect());
    this.on(this.$('#copy-pub'), 'click', () => copyText(this.$('#pub').value));
    this.on(this.$('#copy-priv'), 'click', () => copyText(this.$('#priv').value));
    this.on(this.$('#save-pub'), 'click', () => download(`id_${this.#stem()}.pub`, this.$('#pub').value));
    this.on(this.$('#save-priv'), 'click', () => download(`id_${this.#stem()}`, this.$('#priv').value));
    this.bind('#opts input[type="checkbox"]', 'change', () => this.#authorized());
    this.on(this.$('#from'), 'input', () => this.#authorized());
    this.on(this.$('#command'), 'input', () => this.#authorized());
  }

  #stem() {
    const type = this.$('#type').value;
    return type.startsWith('rsa') ? 'rsa' : type.startsWith('ecdsa') ? 'ecdsa' : 'ed25519';
  }

  async #generate() {
    const button = this.$('#make');
    button.setAttribute('loading', '');
    try {
      const jwk = await generate(this.$('#type').value);
      this.#key = await describe(jwk, this.$('#comment').value.trim());
      this.$('#result').hidden = false;
      this.$('#pub').value = this.#key.publicKey;
      this.$('#priv').value = this.#key.privateKey;
      this.$('#art').textContent = this.#key.art;
      this.$('#marks').innerHTML = html`
        <dt>Type</dt><dd>${this.#key.type} · ${this.#key.bits} bit</dd>
        <dt>SHA256</dt><dd>${this.#key.sha256}</dd>
        <dt>MD5</dt><dd>${this.#key.md5}</dd>
      `;
      this.#authorized();
    } finally {
      button.removeAttribute('loading');
    }
  }

  #authorized() {
    if (!this.#key) return;
    const flags = this.$$('#opts input[type="checkbox"]')
      .filter((box) => box.checked)
      .map((box) => box.value);
    const from = this.$('#from').value.trim();
    const command = this.$('#command').value.trim();
    if (from) flags.unshift(`from="${from}"`);
    if (command) flags.unshift(`command="${command}"`);
    this.$('#authorized').value = `${flags.length ? `${flags.join(',')} ` : ''}${this.#key.publicKey}`;
  }

  async #inspect() {
    const error = this.$('#error');
    error.textContent = '';
    try {
      const found = await inspect(this.$('#line').value);
      if (!found) return;
      this.$('#found').hidden = false;
      this.$('#found-art').textContent = found.art;
      this.$('#found-marks').innerHTML = html`
        <dt>Type</dt><dd>${found.type}${found.bits ? ` · ${found.bits} bit` : ''}</dd>
        <dt>SHA256</dt><dd>${found.sha256}</dd>
        <dt>MD5</dt><dd>${found.md5}</dd>
        ${found.comment ? html`<dt>Comment</dt><dd>${found.comment}</dd>` : ''}
        ${found.options ? html`<dt>Options</dt><dd>${found.options}</dd>` : ''}
      `;
    } catch (failure) {
      this.$('#found').hidden = true;
      error.textContent = failure.message;
    }
  }
}

define('jg-app-ssh-keys', SshKeys);
