export default {
  id: "ssh-keys",
  name: "SSH Keys",
  tagline: "Generate and inspect OpenSSH keys offline",
  category: "crypto",
  glyph: "⌁",
  icon: "key",
  tint: "#6a5a8c",
  keywords: ["ssh","key","ed25519","rsa","ecdsa","keygen","fingerprint","authorized_keys","openssh"],
  tag: "jg-app-ssh-keys",
  window: {"width":940,"height":800},
  i18n: {
    de: { name: 'SSH-Schlüssel', tagline: 'OpenSSH-Schlüssel offline erzeugen und prüfen' },
    es: { name: 'Claves SSH', tagline: 'Generar e inspeccionar claves OpenSSH sin conexión' },
    zh: { name: 'SSH 密钥', tagline: '离线生成并查看 OpenSSH 密钥' },
    fr: { name: 'Clés SSH', tagline: 'Générer et inspecter des clés OpenSSH hors ligne' },
    pt: { name: 'Chaves SSH', tagline: 'Gere e inspecione chaves OpenSSH offline' },
    ja: { name: 'SSH 鍵', tagline: 'OpenSSH 鍵をオフラインで生成、検査' },
    ko: { name: 'SSH 키', tagline: 'OpenSSH 키를 오프라인에서 만들고 살펴보기' },
  },
  load: () => import('./index.js'),
};
