export default {
  id: "api-spec",
  name: "API Spec Editor",
  tagline: "Edit and check OpenAPI documents",
  category: "development",
  glyph: "API",
  icon: "spec",
  keywords: ["openapi","swagger","api","spec","rest","yaml","schema","lint"],
  tag: "jg-app-api-spec",
  window: {"width":1120,"height":860},
  i18n: {
    de: { name: 'API-Spec-Editor', tagline: 'OpenAPI-Dokumente bearbeiten und prüfen' },
    es: { name: 'Editor de API', tagline: 'Editar y comprobar documentos OpenAPI' },
    zh: { name: 'API 规范编辑器', tagline: '编辑并校验 OpenAPI 文档' },
    fr: { name: 'Éditeur de spec API', tagline: 'Modifier et vérifier des documents OpenAPI' },
    pt: { name: 'Editor de spec de API', tagline: 'Edite e verifique documentos OpenAPI' },
    ja: { name: 'API 仕様エディタ', tagline: 'OpenAPI 文書の編集と検査' },
    ko: { name: 'API 명세 편집기', tagline: 'OpenAPI 문서를 편집하고 검사하기' },
  },
  load: () => import('./index.js'),
};
