import { appText, language } from '../../core/i18n.js';

const t = appText('tax-calculator');

const FIELD = {
  '401(k) contribution': () => t('tax-calculator.field.401KContribution', '401(k) contribution'),
  'Children': () => t('tax-calculator.field.children', 'Children'),
  'Church member': () => t('tax-calculator.field.churchMember', 'Church member'),
  'Extra health contribution': () => t('tax-calculator.field.extraHealthContribution', 'Extra health contribution'),
  'Federal state': () => t('tax-calculator.field.federalState', 'Federal state'),
  'Filing status': () => t('tax-calculator.field.filingStatus', 'Filing status'),
  'Health insurance': () => t('tax-calculator.field.healthInsurance', 'Health insurance'),
  'Household': () => t('tax-calculator.field.household', 'Household'),
  'Pension contribution': () => t('tax-calculator.field.pensionContribution', 'Pension contribution'),
  'Private premium a month': () => t('tax-calculator.field.privatePremiumAMonth', 'Private premium a month'),
  'Province': () => t('tax-calculator.field.province', 'Province'),
  'RRSP contribution': () => t('tax-calculator.field.rrspContribution', 'RRSP contribution'),
  'State': () => t('tax-calculator.field.state', 'State'),
  'State pension age': () => t('tax-calculator.field.statePensionAge', 'State pension age'),
  'Student loan': () => t('tax-calculator.field.studentLoan', 'Student loan'),
  'Tax class': () => t('tax-calculator.field.taxClass', 'Tax class'),
  'The 30 percent ruling': () => t('tax-calculator.field.the30PercentRuling', 'The 30 percent ruling'),
  'Under 23 and childless': () => t('tax-calculator.field.under23AndChildless', 'Under 23 and childless'),
  'Where you live': () => t('tax-calculator.field.whereYouLive', 'Where you live'),
};

const OPTION = {
  'Alberta': () => t('tax-calculator.option.alberta', 'Alberta'),
  'Applies': () => t('tax-calculator.option.applies', 'Applies'),
  'Arizona': () => t('tax-calculator.option.arizona', 'Arizona'),
  'Baden-Wurttemberg': () => t('tax-calculator.option.badenWurttemberg', 'Baden-Wurttemberg'),
  'Bavaria': () => t('tax-calculator.option.bavaria', 'Bavaria'),
  'Below it': () => t('tax-calculator.option.belowIt', 'Below it'),
  'Berlin': () => t('tax-calculator.option.berlin', 'Berlin'),
  'Brandenburg': () => t('tax-calculator.option.brandenburg', 'Brandenburg'),
  'Bremen': () => t('tax-calculator.option.bremen', 'Bremen'),
  'British Columbia': () => t('tax-calculator.option.britishColumbia', 'British Columbia'),
  'Class 1, on your own': () => t('tax-calculator.option.class1OnYourOwn', 'Class 1, on your own'),
  'Class 2, married': () => t('tax-calculator.option.class2Married', 'Class 2, married'),
  'Colorado': () => t('tax-calculator.option.colorado', 'Colorado'),
  'Does not apply': () => t('tax-calculator.option.doesNotApply', 'Does not apply'),
  'England, Wales or Northern Ireland': () => t('tax-calculator.option.englandWalesOrNorthernIreland', 'England, Wales or Northern Ireland'),
  'Hamburg': () => t('tax-calculator.option.hamburg', 'Hamburg'),
  'Head of household': () => t('tax-calculator.option.headOfHousehold', 'Head of household'),
  'Hesse': () => t('tax-calculator.option.hesse', 'Hesse'),
  'I, on your own': () => t('tax-calculator.option.iOnYourOwn', 'I, on your own'),
  'II, single parent': () => t('tax-calculator.option.iiSingleParent', 'II, single parent'),
  'III, married, the higher earner': () => t('tax-calculator.option.iiiMarriedTheHigherEarner', 'III, married, the higher earner'),
  'IV, married, both earning alike': () => t('tax-calculator.option.ivMarriedBothEarningAlike', 'IV, married, both earning alike'),
  'Illinois': () => t('tax-calculator.option.illinois', 'Illinois'),
  'Indiana': () => t('tax-calculator.option.indiana', 'Indiana'),
  'Kentucky': () => t('tax-calculator.option.kentucky', 'Kentucky'),
  'Lower Saxony': () => t('tax-calculator.option.lowerSaxony', 'Lower Saxony'),
  'Manitoba': () => t('tax-calculator.option.manitoba', 'Manitoba'),
  'Married': () => t('tax-calculator.option.married', 'Married'),
  'Married filing jointly': () => t('tax-calculator.option.marriedFilingJointly', 'Married filing jointly'),
  'Married or cohabiting': () => t('tax-calculator.option.marriedOrCohabiting', 'Married or cohabiting'),
  'Married or in a civil union': () => t('tax-calculator.option.marriedOrInACivilUnion', 'Married or in a civil union'),
  'Married, one income': () => t('tax-calculator.option.marriedOneIncome', 'Married, one income'),
  'Massachusetts': () => t('tax-calculator.option.massachusetts', 'Massachusetts'),
  'Mecklenburg-Vorpommern': () => t('tax-calculator.option.mecklenburgVorpommern', 'Mecklenburg-Vorpommern'),
  'Michigan': () => t('tax-calculator.option.michigan', 'Michigan'),
  'New Brunswick': () => t('tax-calculator.option.newBrunswick', 'New Brunswick'),
  'No': () => t('tax-calculator.option.no', 'No'),
  'No state income tax': () => t('tax-calculator.option.noStateIncomeTax', 'No state income tax'),
  'None': () => t('tax-calculator.option.none', 'None'),
  'North Carolina': () => t('tax-calculator.option.northCarolina', 'North Carolina'),
  'North Rhine-Westphalia': () => t('tax-calculator.option.northRhineWestphalia', 'North Rhine-Westphalia'),
  'Nova Scotia': () => t('tax-calculator.option.novaScotia', 'Nova Scotia'),
  'On your own': () => t('tax-calculator.option.onYourOwn', 'On your own'),
  'Ontario': () => t('tax-calculator.option.ontario', 'Ontario'),
  'Pennsylvania': () => t('tax-calculator.option.pennsylvania', 'Pennsylvania'),
  'Plan 1': () => t('tax-calculator.option.plan1', 'Plan 1'),
  'Plan 2': () => t('tax-calculator.option.plan2', 'Plan 2'),
  'Plan 4 (Scotland)': () => t('tax-calculator.option.plan4Scotland', 'Plan 4 (Scotland)'),
  'Plan 5': () => t('tax-calculator.option.plan5', 'Plan 5'),
  'Postgraduate': () => t('tax-calculator.option.postgraduate', 'Postgraduate'),
  'Private': () => t('tax-calculator.option.private', 'Private'),
  'Quebec': () => t('tax-calculator.option.quebec', 'Quebec'),
  'Reached it': () => t('tax-calculator.option.reachedIt', 'Reached it'),
  'Rhineland-Palatinate': () => t('tax-calculator.option.rhinelandPalatinate', 'Rhineland-Palatinate'),
  'Saarland': () => t('tax-calculator.option.saarland', 'Saarland'),
  'Saskatchewan': () => t('tax-calculator.option.saskatchewan', 'Saskatchewan'),
  'Saxony': () => t('tax-calculator.option.saxony', 'Saxony'),
  'Saxony-Anhalt': () => t('tax-calculator.option.saxonyAnhalt', 'Saxony-Anhalt'),
  'Schleswig-Holstein': () => t('tax-calculator.option.schleswigHolstein', 'Schleswig-Holstein'),
  'Scotland': () => t('tax-calculator.option.scotland', 'Scotland'),
  'Single': () => t('tax-calculator.option.single', 'Single'),
  'Statutory': () => t('tax-calculator.option.statutory', 'Statutory'),
  'Thuringia': () => t('tax-calculator.option.thuringia', 'Thuringia'),
  'Utah': () => t('tax-calculator.option.utah', 'Utah'),
  'V, married, the lower earner': () => t('tax-calculator.option.vMarriedTheLowerEarner', 'V, married, the lower earner'),
  'VI, a second job': () => t('tax-calculator.option.viASecondJob', 'VI, a second job'),
  'Yes': () => t('tax-calculator.option.yes', 'Yes'),
};

const HINT = {
  'Child allowances counted for you': () => t('tax-calculator.hint.childAllowancesCountedForYou', 'Child allowances counted for you'),
  'Percent of gross, taken before tax': () => t('tax-calculator.hint.percentOfGrossTakenBeforeTax', 'Percent of gross, taken before tax'),
  'Percent of pay, before federal tax': () => t('tax-calculator.hint.percentOfPayBeforeFederalTax', 'Percent of pay, before federal tax'),
  'Percent of pay, deducted before tax': () => t('tax-calculator.hint.percentOfPayDeductedBeforeTax', 'Percent of pay, deducted before tax'),
  'Under 23 you are spared the childless surcharge': () => t('tax-calculator.hint.under23YouAreSparedTheChildlessSurcharge', 'Under 23 you are spared the childless surcharge'),
  'Your fund sets this, 2.5 on average': () => t('tax-calculator.hint.yourFundSetsThis25OnAverage', 'Your fund sets this, 2.5 on average'),
  'Your share of health and care cover': () => t('tax-calculator.hint.yourShareOfHealthAndCareCover', 'Your share of health and care cover'),
};

const NOTE = {
  'A flat fifteen percent on employment income.': () => t('tax-calculator.note.aFlatFifteenPercentOnEmploymentIncome', 'A flat fifteen percent on employment income.'),
  'A flat ten percent, charged after the pension and health contributions.': () => t('tax-calculator.note.aFlatTenPercentChargedAfterThePensionAndHe', 'A flat ten percent, charged after the pension and health contributions.'),
  'Box 1 tax on employment income, with the general and labour credits.': () => t('tax-calculator.note.box1TaxOnEmploymentIncomeWithTheGeneralAnd', 'Box 1 tax on employment income, with the general and labour credits.'),
  'CPP and EI are at the employee rate. Quebec uses QPP and its own parental plan.': () => t('tax-calculator.note.cppAndEiAreAtTheEmployeeRateQuebecUsesQppA', 'CPP and EI are at the employee rate. Quebec uses QPP and its own parental plan.'),
  'Cantons differ enormously, so treat the cantonal part as a rough guide.': () => t('tax-calculator.note.cantonsDifferEnormouslySoTreatTheCantonalP', 'Cantons differ enormously, so treat the cantonal part as a rough guide.'),
  'Child allowances lower the solidarity surcharge and church tax, not the income tax itself.': () => t('tax-calculator.note.childAllowancesLowerTheSolidaritySurcharge', 'Child allowances lower the solidarity surcharge and church tax, not the income tax itself.'),
  'Class one and class two of the scale, with the employment fund surcharge.': () => t('tax-calculator.note.classOneAndClassTwoOfTheScaleWithTheEmploy', 'Class one and class two of the scale, with the employment fund surcharge.'),
  'Contributions are taken off before tax through the Vorsorgepauschale.': () => t('tax-calculator.note.contributionsAreTakenOffBeforeTaxThroughTh', 'Contributions are taken off before tax through the Vorsorgepauschale.'),
  'Contributions are twenty five and ten percent of gross.': () => t('tax-calculator.note.contributionsAreTwentyFiveAndTenPercentOfG', 'Contributions are twenty five and ten percent of gross.'),
  'Contributions cover old age and unemployment, plus the occupational pension at a middle rate.': () => t('tax-calculator.note.contributionsCoverOldAgeAndUnemploymentPlu', 'Contributions cover old age and unemployment, plus the occupational pension at a middle rate.'),
  'Employee contributions are taken together at the usual private sector rate.': () => t('tax-calculator.note.employeeContributionsAreTakenTogetherAtThe', 'Employee contributions are taken together at the usual private sector rate.'),
  'Employee pension and unemployment contributions are included.': () => t('tax-calculator.note.employeePensionAndUnemploymentContribution', 'Employee pension and unemployment contributions are included.'),
  'Employment income under PAYE, with the standard personal allowance.': () => t('tax-calculator.note.employmentIncomeUnderPayeWithTheStandardPe', 'Employment income under PAYE, with the standard personal allowance.'),
  'Federal and provincial tax on employment income, with the basic personal amounts.': () => t('tax-calculator.note.federalAndProvincialTaxOnEmploymentIncomeW', 'Federal and provincial tax on employment income, with the basic personal amounts.'),
  'Federal income tax on wages with the standard deduction, plus FICA.': () => t('tax-calculator.note.federalIncomeTaxOnWagesWithTheStandardDedu', 'Federal income tax on wages with the standard deduction, plus FICA.'),
  'Federal tax on employment income after social security and the work allowance.': () => t('tax-calculator.note.federalTaxOnEmploymentIncomeAfterSocialSec', 'Federal tax on employment income after social security and the work allowance.'),
  'Federal tax on the scale, with cantonal and municipal tax at a typical multiple.': () => t('tax-calculator.note.federalTaxOnTheScaleWithCantonalAndMunicip', 'Federal tax on the scale, with cantonal and municipal tax at a typical multiple.'),
  'Flat fifteen percent up to the ceiling, then twenty three percent above it.': () => t('tax-calculator.note.flatFifteenPercentUpToTheCeilingThenTwenty', 'Flat fifteen percent up to the ceiling, then twenty three percent above it.'),
  'Flat tax on ordinary income after the standard deductions, plus the step tax.': () => t('tax-calculator.note.flatTaxOnOrdinaryIncomeAfterTheStandardDed', 'Flat tax on ordinary income after the standard deductions, plus the step tax.'),
  'Income tax on the twelve monthly payments, with the traffic credit.': () => t('tax-calculator.note.incomeTaxOnTheTwelveMonthlyPaymentsWithThe', 'Income tax on the twelve monthly payments, with the traffic credit.'),
  'Income tax with the personal and employee credits, plus PRSI and USC.': () => t('tax-calculator.note.incomeTaxWithThePersonalAndEmployeeCredits', 'Income tax with the personal and employee credits, plus PRSI and USC.'),
  'Labour market contribution first, then bottom and top tax with the personal allowance.': () => t('tax-calculator.note.labourMarketContributionFirstThenBottomAnd', 'Labour market contribution first, then bottom and top tax with the personal allowance.'),
  'Leaves out church tax and the many deductions.': () => t('tax-calculator.note.leavesOutChurchTaxAndTheManyDeductions', 'Leaves out church tax and the many deductions.'),
  'Leaves out credits, itemised deductions, local taxes and pre-tax benefits.': () => t('tax-calculator.note.leavesOutCreditsItemisedDeductionsLocalTax', 'Leaves out credits, itemised deductions, local taxes and pre-tax benefits.'),
  'Leaves out other credits, RRSP room carried forward and the Quebec abatement.': () => t('tax-calculator.note.leavesOutOtherCreditsRrspRoomCarriedForwar', 'Leaves out other credits, RRSP room carried forward and the Quebec abatement.'),
  'Leaves out other reliefs and the home carer credit.': () => t('tax-calculator.note.leavesOutOtherReliefsAndTheHomeCarerCredit', 'Leaves out other reliefs and the home carer credit.'),
  'Leaves out tax credits, benefits, salary sacrifice and the marriage allowance.': () => t('tax-calculator.note.leavesOutTaxCreditsBenefitsSalarySacrifice', 'Leaves out tax credits, benefits, salary sacrifice and the marriage allowance.'),
  'Leaves out the church tax and the earned income deductions.': () => t('tax-calculator.note.leavesOutTheChurchTaxAndTheEarnedIncomeDed', 'Leaves out the church tax and the earned income deductions.'),
  'Leaves out the family allowance, which can be large.': () => t('tax-calculator.note.leavesOutTheFamilyAllowanceWhichCanBeLarge', 'Leaves out the family allowance, which can be large.'),
  'Leaves out the many credits and the dependent child relief.': () => t('tax-calculator.note.leavesOutTheManyCreditsAndTheDependentChil', 'Leaves out the many credits and the dependent child relief.'),
  'Leaves out the many personal and family credits.': () => t('tax-calculator.note.leavesOutTheManyPersonalAndFamilyCredits', 'Leaves out the many personal and family credits.'),
  'Leaves out the many special deductions.': () => t('tax-calculator.note.leavesOutTheManySpecialDeductions', 'Leaves out the many special deductions.'),
  'Leaves out the mortgage deduction and other personal allowances.': () => t('tax-calculator.note.leavesOutTheMortgageDeductionAndOtherPerso', 'Leaves out the mortgage deduction and other personal allowances.'),
  'Leaves out the personal deduction for lower pay.': () => t('tax-calculator.note.leavesOutThePersonalDeductionForLowerPay', 'Leaves out the personal deduction for lower pay.'),
  'Leaves out the relief for the young and joint assessment.': () => t('tax-calculator.note.leavesOutTheReliefForTheYoungAndJointAsses', 'Leaves out the relief for the young and joint assessment.'),
  'Leaves out the solidarity contribution, which is suspended.': () => t('tax-calculator.note.leavesOutTheSolidarityContributionWhichIsS', 'Leaves out the solidarity contribution, which is suspended.'),
  'Madeira and the Azores use lower rates that are not shown here.': () => t('tax-calculator.note.madeiraAndTheAzoresUseLowerRatesThatAreNot', 'Madeira and the Azores use lower rates that are not shown here.'),
  'Mainland rates on employment income, with the standard deduction.': () => t('tax-calculator.note.mainlandRatesOnEmploymentIncomeWithTheStan', 'Mainland rates on employment income, with the standard deduction.'),
  'Municipal surcharge is taken at seven percent, the usual level.': () => t('tax-calculator.note.municipalSurchargeIsTakenAtSevenPercentThe', 'Municipal surcharge is taken at seven percent, the usual level.'),
  'Municipal tax at the average rate, plus national tax above the threshold.': () => t('tax-calculator.note.municipalTaxAtTheAverageRatePlusNationalTa', 'Municipal tax at the average rate, plus national tax above the threshold.'),
  'Municipal tax is at the average rate.': () => t('tax-calculator.note.municipalTaxIsAtTheAverageRate', 'Municipal tax is at the average rate.'),
  'National Insurance is class 1 at the employee rate.': () => t('tax-calculator.note.nationalInsuranceIsClass1AtTheEmployeeRate', 'National Insurance is class 1 at the employee rate.'),
  'National insurance is at the employee rate.': () => t('tax-calculator.note.nationalInsuranceIsAtTheEmployeeRate', 'National insurance is at the employee rate.'),
  'National tax at the three rates, with the employment credit.': () => t('tax-calculator.note.nationalTaxAtTheThreeRatesWithTheEmploymen', 'National tax at the three rates, with the employment credit.'),
  'Regional and municipal surcharges are taken at typical levels.': () => t('tax-calculator.note.regionalAndMunicipalSurchargesAreTakenAtTy', 'Regional and municipal surcharges are taken at typical levels.'),
  'Regions set their own half of the scale, so your bill may differ.': () => t('tax-calculator.note.regionsSetTheirOwnHalfOfTheScaleSoYourBill', 'Regions set their own half of the scale, so your bill may differ.'),
  'Saxony charges the employee half a point more for care insurance.': () => t('tax-calculator.note.saxonyChargesTheEmployeeHalfAPointMoreForC', 'Saxony charges the employee half a point more for care insurance.'),
  'Social and health contributions are at the employee rates.': () => t('tax-calculator.note.socialAndHealthContributionsAreAtTheEmploy', 'Social and health contributions are at the employee rates.'),
  'Social contribution is at the employee rate of eighteen and a half percent.': () => t('tax-calculator.note.socialContributionIsAtTheEmployeeRateOfEig', 'Social contribution is at the employee rate of eighteen and a half percent.'),
  'Social contributions cover pension, health and long term care.': () => t('tax-calculator.note.socialContributionsCoverPensionHealthAndLo', 'Social contributions cover pension, health and long term care.'),
  'Social security is at the employee rate of eleven percent.': () => t('tax-calculator.note.socialSecurityIsAtTheEmployeeRateOfElevenP', 'Social security is at the employee rate of eleven percent.'),
  'Social security is at the employee rate up to the ceiling.': () => t('tax-calculator.note.socialSecurityIsAtTheEmployeeRateUpToTheCe', 'Social security is at the employee rate up to the ceiling.'),
  'Social security is at the employee rate up to the monthly ceiling.': () => t('tax-calculator.note.socialSecurityIsAtTheEmployeeRateUpToTheMo', 'Social security is at the employee rate up to the monthly ceiling.'),
  'Social security is at the usual employee rate.': () => t('tax-calculator.note.socialSecurityIsAtTheUsualEmployeeRate', 'Social security is at the usual employee rate.'),
  'State and regional tax added together at the common rates.': () => t('tax-calculator.note.stateAndRegionalTaxAddedTogetherAtTheCommo', 'State and regional tax added together at the common rates.'),
  'State tax on the scale, plus municipal tax at the average rate.': () => t('tax-calculator.note.stateTaxOnTheScalePlusMunicipalTaxAtTheAve', 'State tax on the scale, plus municipal tax at the average rate.'),
  'States shown are the ones with a single flat rate, or none at all.': () => t('tax-calculator.note.statesShownAreTheOnesWithASingleFlatRateOr', 'States shown are the ones with a single flat rate, or none at all.'),
  'Tax is worked out on pay after contributions, as the barème requires.': () => t('tax-calculator.note.taxIsWorkedOutOnPayAfterContributionsAsThe', 'Tax is worked out on pay after contributions, as the barème requires.'),
  'The barème on employment income after the ten percent allowance for work costs.': () => t('tax-calculator.note.theBarMeOnEmploymentIncomeAfterTheTenPerce', 'The barème on employment income after the ten percent allowance for work costs.'),
  'The basic deduction and the earned income credit are both applied.': () => t('tax-calculator.note.theBasicDeductionAndTheEarnedIncomeCreditA', 'The basic deduction and the earned income credit are both applied.'),
  'The employment scale with the tax credit that falls as income rises.': () => t('tax-calculator.note.theEmploymentScaleWithTheTaxCreditThatFall', 'The employment scale with the tax credit that falls as income rises.'),
  'The family quotient counts a half part for each of the first two children.': () => t('tax-calculator.note.theFamilyQuotientCountsAHalfPartForEachOfT', 'The family quotient counts a half part for each of the first two children.'),
  'The official tarif for the year, with the tax class applied as payroll does it.': () => t('tax-calculator.note.theOfficialTarifForTheYearWithTheTaxClassA', 'The official tarif for the year, with the tax class applied as payroll does it.'),
  'The standard rate band widens for a married couple with one income.': () => t('tax-calculator.note.theStandardRateBandWidensForAMarriedCouple', 'The standard rate band widens for a married couple with one income.'),
  'The taxpayer credit is applied in full.': () => t('tax-calculator.note.theTaxpayerCreditIsAppliedInFull', 'The taxpayer credit is applied in full.'),
  'The thirteenth and fourteenth salaries are taxed more lightly and are not counted here.': () => t('tax-calculator.note.theThirteenthAndFourteenthSalariesAreTaxed', 'The thirteenth and fourteenth salaries are taxed more lightly and are not counted here.'),
  'The thirty percent ruling is applied to the taxable part of your pay.': () => t('tax-calculator.note.theThirtyPercentRulingIsAppliedToTheTaxabl', 'The thirty percent ruling is applied to the taxable part of your pay.'),
  'The two rate scale with the tax reducing amount.': () => t('tax-calculator.note.theTwoRateScaleWithTheTaxReducingAmount', 'The two rate scale with the tax reducing amount.'),
  'Your municipality sets its own rate, so the bill varies by where you live.': () => t('tax-calculator.note.yourMunicipalitySetsItsOwnRateSoTheBillVar', 'Your municipality sets its own rate, so the bill varies by where you live.'),
};

const LINE = {
  'Alberta tax': () => t('tax-calculator.line.albertaTax', 'Alberta tax'),
  'Box 1 tax after credits': () => t('tax-calculator.line.box1TaxAfterCredits', 'Box 1 tax after credits'),
  'British Columbia tax': () => t('tax-calculator.line.britishColumbiaTax', 'British Columbia tax'),
  'CPP': () => t('tax-calculator.line.cpp', 'CPP'),
  'Cantonal and municipal tax': () => t('tax-calculator.line.cantonalAndMunicipalTax', 'Cantonal and municipal tax'),
  'Care insurance': () => t('tax-calculator.line.careInsurance', 'Care insurance'),
  'Church tax': () => t('tax-calculator.line.churchTax', 'Church tax'),
  'Employee contributions': () => t('tax-calculator.line.employeeContributions', 'Employee contributions'),
  'Employment fund surcharge': () => t('tax-calculator.line.employmentFundSurcharge', 'Employment fund surcharge'),
  'Employment insurance': () => t('tax-calculator.line.employmentInsurance', 'Employment insurance'),
  'Federal income tax': () => t('tax-calculator.line.federalIncomeTax', 'Federal income tax'),
  'Federal tax': () => t('tax-calculator.line.federalTax', 'Federal tax'),
  'Health contribution': () => t('tax-calculator.line.healthContribution', 'Health contribution'),
  'Health insurance': () => t('tax-calculator.line.healthInsurance', 'Health insurance'),
  'Income tax': () => t('tax-calculator.line.incomeTax', 'Income tax'),
  'Labour market contribution': () => t('tax-calculator.line.labourMarketContribution', 'Labour market contribution'),
  'Manitoba tax': () => t('tax-calculator.line.manitobaTax', 'Manitoba tax'),
  'Medicare': () => t('tax-calculator.line.medicare', 'Medicare'),
  'Municipal surcharge': () => t('tax-calculator.line.municipalSurcharge', 'Municipal surcharge'),
  'Municipal tax': () => t('tax-calculator.line.municipalTax', 'Municipal tax'),
  'National Insurance': () => t('tax-calculator.line.nationalInsurance', 'National Insurance'),
  'National insurance': () => t('tax-calculator.line.nationalInsurance2', 'National insurance'),
  'National tax': () => t('tax-calculator.line.nationalTax', 'National tax'),
  'New Brunswick tax': () => t('tax-calculator.line.newBrunswickTax', 'New Brunswick tax'),
  'Nova Scotia tax': () => t('tax-calculator.line.novaScotiaTax', 'Nova Scotia tax'),
  'Occupational pension': () => t('tax-calculator.line.occupationalPension', 'Occupational pension'),
  'Old age and unemployment': () => t('tax-calculator.line.oldAgeAndUnemployment', 'Old age and unemployment'),
  'Ontario tax': () => t('tax-calculator.line.ontarioTax', 'Ontario tax'),
  'PRSI': () => t('tax-calculator.line.prsi', 'PRSI'),
  'Parental insurance': () => t('tax-calculator.line.parentalInsurance', 'Parental insurance'),
  'Pension contribution': () => t('tax-calculator.line.pensionContribution', 'Pension contribution'),
  'Pension insurance': () => t('tax-calculator.line.pensionInsurance', 'Pension insurance'),
  'Private health cover': () => t('tax-calculator.line.privateHealthCover', 'Private health cover'),
  'QPP': () => t('tax-calculator.line.qpp', 'QPP'),
  'Quebec tax': () => t('tax-calculator.line.quebecTax', 'Quebec tax'),
  'Regional surcharge': () => t('tax-calculator.line.regionalSurcharge', 'Regional surcharge'),
  'Saskatchewan tax': () => t('tax-calculator.line.saskatchewanTax', 'Saskatchewan tax'),
  'Social Security': () => t('tax-calculator.line.socialSecurity', 'Social Security'),
  'Social contributions': () => t('tax-calculator.line.socialContributions', 'Social contributions'),
  'Social insurance': () => t('tax-calculator.line.socialInsurance', 'Social insurance'),
  'Social security': () => t('tax-calculator.line.socialSecurity2', 'Social security'),
  'State income tax': () => t('tax-calculator.line.stateIncomeTax', 'State income tax'),
  'Student loan': () => t('tax-calculator.line.studentLoan', 'Student loan'),
  'Unemployment contribution': () => t('tax-calculator.line.unemploymentContribution', 'Unemployment contribution'),
  'Unemployment insurance': () => t('tax-calculator.line.unemploymentInsurance', 'Unemployment insurance'),
  'Universal social charge': () => t('tax-calculator.line.universalSocialCharge', 'Universal social charge'),
};

const lookup = (table) => (text) => (table[text] ?? (() => text))();

export const fieldLabel = lookup(FIELD);
export const optionLabel = lookup(OPTION);
export const hintLabel = lookup(HINT);
export const noteLabel = lookup(NOTE);
export const lineLabel = lookup(LINE);

const ISO = {
  uk: 'GB', ie: 'IE', de: 'DE', fr: 'FR', nl: 'NL', be: 'BE', lu: 'LU', ch: 'CH', at: 'AT',
  es: 'ES', pt: 'PT', it: 'IT', gr: 'GR', se: 'SE', dk: 'DK', no: 'NO', fi: 'FI',
  pl: 'PL', cz: 'CZ', hu: 'HU', ro: 'RO', us: 'US', ca: 'CA',
};

export const countryName = (id, fallback) => {
  const code = ISO[id];
  if (!code) return fallback;
  try {
    return new Intl.DisplayNames([language()], { type: 'region' }).of(code) ?? fallback;
  } catch {
    return fallback;
  }
};
