export default {
  id: "optics-lab",
  name: "Optics Lab",
  tagline: "Lenses, mirrors and prisms with real ray tracing",
  category: "science",
  glyph: "◐",
  icon: "prismLight",
  tint: "#3aa6d8",
  keywords: ["optics", "light", "lens", "mirror", "prism", "refraction", "physics", "ray", "rainbow"],
  tag: "jg-app-optics-lab",
  window: { width: 1120, height: 780 },
  i18n: {
    de: { name: 'Optiklabor', tagline: 'Linsen, Spiegel und Prismen mit echter Strahlverfolgung' },
    es: { name: 'Laboratorio de óptica', tagline: 'Lentes, espejos y prismas con trazado de rayos real' },
    zh: { name: '光学实验室', tagline: '透镜、反射镜与棱镜，真实光线追踪' },
    fr: { name: 'Labo optique', tagline: 'Lentilles, miroirs et prismes avec vrai tracé de rayons' },
    pt: { name: 'Laboratório de óptica', tagline: 'Lentes, espelhos e prismas com traçado de raios de verdade' },
    ja: { name: '光学ラボ', tagline: 'レンズ、鏡、プリズムを本物の光線追跡で' },
    ko: { name: '광학 실험실', tagline: '렌즈, 거울, 프리즘을 실제 광선 추적으로' },
  },
  load: () => import('./index.js'),
};
