export default {
  id: "mirror",
  name: "Mirror",
  tagline: "Camera mirror with an adjustable ring light",
  category: "media",
  glyph: "◲",
  icon: "mirror",
  tint: "#f43f5e",
  keywords: ["mirror","camera","webcam","ring light","selfie","makeup"],
  tag: "jg-app-mirror",
  window: { width: 980, height: 860, maximized: true },
  i18n: {
    de: { name: 'Spiegel', tagline: 'Kameraspiegel mit einstellbarem Ringlicht' },
    es: { name: 'Espejo', tagline: 'Espejo de cámara con un aro de luz ajustable' },
    zh: { name: '镜子', tagline: '带可调环形补光的摄像头镜子' },
    fr: { name: 'Miroir', tagline: 'Miroir caméra avec anneau lumineux réglable' },
    pt: { name: 'Espelho', tagline: 'Espelho de câmera com luz de anel ajustável' },
    ja: { name: 'ミラー', tagline: '明るさを調整できるリングライト付きカメラミラー' },
    ko: { name: '거울', tagline: '밝기를 조절하는 링라이트가 있는 카메라 거울' },
  },
  load: () => import('./index.js'),
};
