export default {
  id: "gamepad-tester",
  name: "Gamepad Tester",
  tagline: "Check every stick, trigger and button",
  category: "utility",
  glyph: "⊕",
  icon: "joystick",
  tint: "#9c6440",
  keywords: ["gamepad","joystick","controller","xbox","playstation","test","axes","buttons","rumble"],
  tag: "jg-app-gamepad-tester",
  widget: true,
  window: {"width":900,"height":820},
  i18n: {
    de: { name: 'Gamepad-Tester', tagline: 'Jeden Stick, Trigger und Knopf prüfen' },
    es: { name: 'Probador de mando', tagline: 'Comprobar cada stick, gatillo y botón' },
    zh: { name: '手柄测试', tagline: '检查每个摇杆、扳机与按键' },
    fr: { name: 'Test de manette', tagline: 'Vérifier chaque stick, gâchette et bouton' },
    pt: { name: 'Teste de controle', tagline: 'Verifique cada analógico, gatilho e botão' },
    ja: { name: 'ゲームパッド診断', tagline: 'スティック、トリガー、ボタンをすべて確認' },
    ko: { name: '게임패드 점검', tagline: '스틱, 트리거, 버튼을 전부 확인하기' },
  },
  load: () => import('./index.js'),
};
