// Letters of the writing systems people most often set out to learn, each with
// the name it goes by, how it is written in the latin alphabet and the sound it
// stands for.

const greek = [
  { glyph: 'Α', pair: 'α', name: 'alpha', latin: 'a', sound: 'a in father' },
  { glyph: 'Β', pair: 'β', name: 'beta', latin: 'v', sound: 'v in van, b in ancient Greek' },
  { glyph: 'Γ', pair: 'γ', name: 'gamma', latin: 'g', sound: 'a softer g, close to y before e and i' },
  { glyph: 'Δ', pair: 'δ', name: 'delta', latin: 'd', sound: 'th in this' },
  { glyph: 'Ε', pair: 'ε', name: 'epsilon', latin: 'e', sound: 'e in bed' },
  { glyph: 'Ζ', pair: 'ζ', name: 'zeta', latin: 'z', sound: 'z in zoo' },
  { glyph: 'Η', pair: 'η', name: 'eta', latin: 'i', sound: 'ee in see' },
  { glyph: 'Θ', pair: 'θ', name: 'theta', latin: 'th', sound: 'th in thin' },
  { glyph: 'Ι', pair: 'ι', name: 'iota', latin: 'i', sound: 'ee in see' },
  { glyph: 'Κ', pair: 'κ', name: 'kappa', latin: 'k', sound: 'k in kite' },
  { glyph: 'Λ', pair: 'λ', name: 'lambda', latin: 'l', sound: 'l in lamp' },
  { glyph: 'Μ', pair: 'μ', name: 'mu', latin: 'm', sound: 'm in moon' },
  { glyph: 'Ν', pair: 'ν', name: 'nu', latin: 'n', sound: 'n in nest' },
  { glyph: 'Ξ', pair: 'ξ', name: 'xi', latin: 'x', sound: 'x in box' },
  { glyph: 'Ο', pair: 'ο', name: 'omicron', latin: 'o', sound: 'o in got' },
  { glyph: 'Π', pair: 'π', name: 'pi', latin: 'p', sound: 'p in spin' },
  { glyph: 'Ρ', pair: 'ρ', name: 'rho', latin: 'r', sound: 'a rolled r' },
  { glyph: 'Σ', pair: 'σ', name: 'sigma', latin: 's', sound: 's in sun, written ς at the end of a word' },
  { glyph: 'Τ', pair: 'τ', name: 'tau', latin: 't', sound: 't in stop' },
  { glyph: 'Υ', pair: 'υ', name: 'upsilon', latin: 'y', sound: 'ee in see' },
  { glyph: 'Φ', pair: 'φ', name: 'phi', latin: 'f', sound: 'f in fun' },
  { glyph: 'Χ', pair: 'χ', name: 'chi', latin: 'ch', sound: 'ch in Scottish loch' },
  { glyph: 'Ψ', pair: 'ψ', name: 'psi', latin: 'ps', sound: 'ps in lapse' },
  { glyph: 'Ω', pair: 'ω', name: 'omega', latin: 'o', sound: 'o in got' },
];

const cyrillic = [
  { glyph: 'А', pair: 'а', name: 'a', latin: 'a', sound: 'a in father' },
  { glyph: 'Б', pair: 'б', name: 'be', latin: 'b', sound: 'b in bed' },
  { glyph: 'В', pair: 'в', name: 've', latin: 'v', sound: 'v in van' },
  { glyph: 'Г', pair: 'г', name: 'ge', latin: 'g', sound: 'g in go' },
  { glyph: 'Д', pair: 'д', name: 'de', latin: 'd', sound: 'd in dog' },
  { glyph: 'Е', pair: 'е', name: 'ye', latin: 'ye', sound: 'ye in yes' },
  { glyph: 'Ё', pair: 'ё', name: 'yo', latin: 'yo', sound: 'yo in yonder, always stressed' },
  { glyph: 'Ж', pair: 'ж', name: 'zhe', latin: 'zh', sound: 's in measure' },
  { glyph: 'З', pair: 'з', name: 'ze', latin: 'z', sound: 'z in zoo' },
  { glyph: 'И', pair: 'и', name: 'i', latin: 'i', sound: 'ee in see' },
  { glyph: 'Й', pair: 'й', name: 'i kratkoye', latin: 'y', sound: 'y in boy' },
  { glyph: 'К', pair: 'к', name: 'ka', latin: 'k', sound: 'k in kite' },
  { glyph: 'Л', pair: 'л', name: 'el', latin: 'l', sound: 'l in lamp' },
  { glyph: 'М', pair: 'м', name: 'em', latin: 'm', sound: 'm in moon' },
  { glyph: 'Н', pair: 'н', name: 'en', latin: 'n', sound: 'n in nest' },
  { glyph: 'О', pair: 'о', name: 'o', latin: 'o', sound: 'o in more when stressed' },
  { glyph: 'П', pair: 'п', name: 'pe', latin: 'p', sound: 'p in spin' },
  { glyph: 'Р', pair: 'р', name: 'er', latin: 'r', sound: 'a rolled r' },
  { glyph: 'С', pair: 'с', name: 'es', latin: 's', sound: 's in sun' },
  { glyph: 'Т', pair: 'т', name: 'te', latin: 't', sound: 't in stop' },
  { glyph: 'У', pair: 'у', name: 'u', latin: 'u', sound: 'oo in boot' },
  { glyph: 'Ф', pair: 'ф', name: 'ef', latin: 'f', sound: 'f in fun' },
  { glyph: 'Х', pair: 'х', name: 'kha', latin: 'kh', sound: 'ch in Scottish loch' },
  { glyph: 'Ц', pair: 'ц', name: 'tse', latin: 'ts', sound: 'ts in cats' },
  { glyph: 'Ч', pair: 'ч', name: 'che', latin: 'ch', sound: 'ch in chair' },
  { glyph: 'Ш', pair: 'ш', name: 'sha', latin: 'sh', sound: 'sh in shop' },
  { glyph: 'Щ', pair: 'щ', name: 'shcha', latin: 'shch', sound: 'a longer, softer sh' },
  { glyph: 'Ъ', pair: 'ъ', name: 'hard sign', latin: '', sound: 'no sound, it keeps the letter before it hard' },
  { glyph: 'Ы', pair: 'ы', name: 'y', latin: 'y', sound: 'i in bill, said further back' },
  { glyph: 'Ь', pair: 'ь', name: 'soft sign', latin: '', sound: 'no sound, it softens the letter before it' },
  { glyph: 'Э', pair: 'э', name: 'e', latin: 'e', sound: 'e in bed' },
  { glyph: 'Ю', pair: 'ю', name: 'yu', latin: 'yu', sound: 'u in use' },
  { glyph: 'Я', pair: 'я', name: 'ya', latin: 'ya', sound: 'ya in yard' },
];

const VOWEL_CUES = {
  a: 'a in father',
  i: 'ee in see',
  u: 'oo in boot, with the lips barely rounded',
  e: 'e in bed',
  o: 'o in more',
};

const ODD_KANA = {
  shi: 'she',
  chi: 'chee',
  tsu: 'ts in cats, then oo',
  fu: 'between f and h, blown softly',
  n: 'n on its own, the only letter that is not a syllable',
  wo: 'said o, used only to mark the object of a sentence',
};

const kanaSound = (latin) => {
  if (ODD_KANA[latin]) return ODD_KANA[latin];
  const vowel = latin.slice(-1);
  const cue = VOWEL_CUES[vowel];
  if (!cue) return latin;
  const head = latin.slice(0, -1);
  return head ? `${head} then ${cue}` : cue;
};

const kana = (rows) =>
  rows.flatMap(([glyphs, latins]) =>
    [...glyphs].map((glyph, at) => ({
      glyph,
      name: latins[at],
      latin: latins[at],
      sound: kanaSound(latins[at]),
    })),
  );

const hiragana = kana([
  ['あいうえお', ['a', 'i', 'u', 'e', 'o']],
  ['かきくけこ', ['ka', 'ki', 'ku', 'ke', 'ko']],
  ['さしすせそ', ['sa', 'shi', 'su', 'se', 'so']],
  ['たちつてと', ['ta', 'chi', 'tsu', 'te', 'to']],
  ['なにぬねの', ['na', 'ni', 'nu', 'ne', 'no']],
  ['はひふへほ', ['ha', 'hi', 'fu', 'he', 'ho']],
  ['まみむめも', ['ma', 'mi', 'mu', 'me', 'mo']],
  ['やゆよ', ['ya', 'yu', 'yo']],
  ['らりるれろ', ['ra', 'ri', 'ru', 're', 'ro']],
  ['わを', ['wa', 'wo']],
  ['ん', ['n']],
]);

const katakana = kana([
  ['アイウエオ', ['a', 'i', 'u', 'e', 'o']],
  ['カキクケコ', ['ka', 'ki', 'ku', 'ke', 'ko']],
  ['サシスセソ', ['sa', 'shi', 'su', 'se', 'so']],
  ['タチツテト', ['ta', 'chi', 'tsu', 'te', 'to']],
  ['ナニヌネノ', ['na', 'ni', 'nu', 'ne', 'no']],
  ['ハヒフヘホ', ['ha', 'hi', 'fu', 'he', 'ho']],
  ['マミムメモ', ['ma', 'mi', 'mu', 'me', 'mo']],
  ['ヤユヨ', ['ya', 'yu', 'yo']],
  ['ラリルレロ', ['ra', 'ri', 'ru', 're', 'ro']],
  ['ワヲ', ['wa', 'wo']],
  ['ン', ['n']],
]);

const bopomofo = [
  { glyph: 'ㄅ', name: 'bo', latin: 'b', sound: 'b in bed', group: 'consonant' },
  { glyph: 'ㄆ', name: 'po', latin: 'p', sound: 'p in pan', group: 'consonant' },
  { glyph: 'ㄇ', name: 'mo', latin: 'm', sound: 'm in moon', group: 'consonant' },
  { glyph: 'ㄈ', name: 'fo', latin: 'f', sound: 'f in fun', group: 'consonant' },
  { glyph: 'ㄉ', name: 'de', latin: 'd', sound: 'd in dog', group: 'consonant' },
  { glyph: 'ㄊ', name: 'te', latin: 't', sound: 't in top', group: 'consonant' },
  { glyph: 'ㄋ', name: 'ne', latin: 'n', sound: 'n in nest', group: 'consonant' },
  { glyph: 'ㄌ', name: 'le', latin: 'l', sound: 'l in lamp', group: 'consonant' },
  { glyph: 'ㄍ', name: 'ge', latin: 'g', sound: 'g in go', group: 'consonant' },
  { glyph: 'ㄎ', name: 'ke', latin: 'k', sound: 'k in kite', group: 'consonant' },
  { glyph: 'ㄏ', name: 'he', latin: 'h', sound: 'h in hat', group: 'consonant' },
  { glyph: 'ㄐ', name: 'ji', latin: 'j', sound: 'j in jeep, said further forward', group: 'consonant' },
  { glyph: 'ㄑ', name: 'qi', latin: 'q', sound: 'ch in cheese, said further forward', group: 'consonant' },
  { glyph: 'ㄒ', name: 'xi', latin: 'x', sound: 'sh in sheep, said further forward', group: 'consonant' },
  { glyph: 'ㄓ', name: 'zhi', latin: 'zh', sound: 'j in jar with the tongue curled back', group: 'consonant' },
  { glyph: 'ㄔ', name: 'chi', latin: 'ch', sound: 'ch in char with the tongue curled back', group: 'consonant' },
  { glyph: 'ㄕ', name: 'shi', latin: 'sh', sound: 'sh in shore with the tongue curled back', group: 'consonant' },
  { glyph: 'ㄖ', name: 'ri', latin: 'r', sound: 'between r and the s in measure', group: 'consonant' },
  { glyph: 'ㄗ', name: 'zi', latin: 'z', sound: 'ds in reads', group: 'consonant' },
  { glyph: 'ㄘ', name: 'ci', latin: 'c', sound: 'ts in cats', group: 'consonant' },
  { glyph: 'ㄙ', name: 'si', latin: 's', sound: 's in sun', group: 'consonant' },
  { glyph: 'ㄧ', name: 'yi', latin: 'i', sound: 'ee in see', group: 'medial' },
  { glyph: 'ㄨ', name: 'wu', latin: 'u', sound: 'oo in boot', group: 'medial' },
  { glyph: 'ㄩ', name: 'yu', latin: 'ü', sound: 'ee in see with rounded lips', group: 'medial' },
  { glyph: 'ㄚ', name: 'a', latin: 'a', sound: 'a in father', group: 'final' },
  { glyph: 'ㄛ', name: 'o', latin: 'o', sound: 'o in more', group: 'final' },
  { glyph: 'ㄜ', name: 'e', latin: 'e', sound: 'u in bud', group: 'final' },
  { glyph: 'ㄝ', name: 'ê', latin: 'ê', sound: 'e in bed', group: 'final' },
  { glyph: 'ㄞ', name: 'ai', latin: 'ai', sound: 'ai in aisle', group: 'final' },
  { glyph: 'ㄟ', name: 'ei', latin: 'ei', sound: 'ei in eight', group: 'final' },
  { glyph: 'ㄠ', name: 'ao', latin: 'ao', sound: 'ow in cow', group: 'final' },
  { glyph: 'ㄡ', name: 'ou', latin: 'ou', sound: 'o in go', group: 'final' },
  { glyph: 'ㄢ', name: 'an', latin: 'an', sound: 'an in ran', group: 'final' },
  { glyph: 'ㄣ', name: 'en', latin: 'en', sound: 'en in taken', group: 'final' },
  { glyph: 'ㄤ', name: 'ang', latin: 'ang', sound: 'ong in song', group: 'final' },
  { glyph: 'ㄥ', name: 'eng', latin: 'eng', sound: 'ung in sung', group: 'final' },
  { glyph: 'ㄦ', name: 'er', latin: 'er', sound: 'er in her', group: 'final' },
];

const radicals = [
  { glyph: '一', name: 'yī', latin: 'one', sound: 'said yī', example: { word: '一天', say: 'yī tiān', means: 'one day' } },
  { glyph: '丨', name: 'gǔn', latin: 'line', sound: 'said gǔn' },
  { glyph: '丶', name: 'zhǔ', latin: 'dot', sound: 'said zhǔ' },
  { glyph: '丿', name: 'piě', latin: 'slash', sound: 'said piě' },
  { glyph: '乙', name: 'yǐ', latin: 'second', sound: 'said yǐ' },
  { glyph: '亅', name: 'jué', latin: 'hook', sound: 'said jué' },
  { glyph: '二', name: 'èr', latin: 'two', sound: 'said èr', example: { word: '二月', say: 'èr yuè', means: 'February' } },
  { glyph: '亠', name: 'tóu', latin: 'lid', sound: 'said tóu' },
  { glyph: '人', name: 'rén', latin: 'person', sound: 'said rén', example: { word: '人口', say: 'rén kǒu', means: 'population' } },
  { glyph: '儿', name: 'ér', latin: 'legs', sound: 'said ér' },
  { glyph: '入', name: 'rù', latin: 'enter', sound: 'said rù' },
  { glyph: '八', name: 'bā', latin: 'eight', sound: 'said bā', example: { word: '八月', say: 'bā yuè', means: 'August' } },
  { glyph: '冂', name: 'jiōng', latin: 'down box', sound: 'said jiōng' },
  { glyph: '冖', name: 'mì', latin: 'cover', sound: 'said mì' },
  { glyph: '冫', name: 'bīng', latin: 'ice', sound: 'said bīng' },
  { glyph: '几', name: 'jī', latin: 'table', sound: 'said jī' },
  { glyph: '凵', name: 'kǎn', latin: 'open box', sound: 'said kǎn' },
  { glyph: '刀', name: 'dāo', latin: 'knife', sound: 'said dāo', example: { word: '刀子', say: 'dāo zi', means: 'knife' } },
  { glyph: '力', name: 'lì', latin: 'power', sound: 'said lì', example: { word: '力气', say: 'lì qi', means: 'strength' } },
  { glyph: '勹', name: 'bāo', latin: 'wrap', sound: 'said bāo' },
  { glyph: '匕', name: 'bǐ', latin: 'spoon', sound: 'said bǐ' },
  { glyph: '匚', name: 'fāng', latin: 'box', sound: 'said fāng' },
  { glyph: '匸', name: 'xǐ', latin: 'hiding enclosure', sound: 'said xǐ' },
  { glyph: '十', name: 'shí', latin: 'ten', sound: 'said shí', example: { word: '十分', say: 'shí fēn', means: 'very' } },
  { glyph: '卜', name: 'bǔ', latin: 'divination', sound: 'said bǔ' },
  { glyph: '卩', name: 'jié', latin: 'seal', sound: 'said jié' },
  { glyph: '厂', name: 'hǎn', latin: 'cliff', sound: 'said hǎn' },
  { glyph: '厶', name: 'sī', latin: 'private', sound: 'said sī' },
  { glyph: '又', name: 'yòu', latin: 'again', sound: 'said yòu', example: { word: '又是', say: 'yòu shì', means: 'again' } },
  { glyph: '口', name: 'kǒu', latin: 'mouth', sound: 'said kǒu', example: { word: '口水', say: 'kǒu shuǐ', means: 'saliva' } },
  { glyph: '囗', name: 'wéi', latin: 'enclosure', sound: 'said wéi' },
  { glyph: '土', name: 'tǔ', latin: 'earth', sound: 'said tǔ', example: { word: '土地', say: 'tǔ dì', means: 'land' } },
  { glyph: '士', name: 'shì', latin: 'scholar', sound: 'said shì' },
  { glyph: '夂', name: 'zhǐ', latin: 'go', sound: 'said zhǐ' },
  { glyph: '夊', name: 'suī', latin: 'go slowly', sound: 'said suī' },
  { glyph: '夕', name: 'xī', latin: 'evening', sound: 'said xī' },
  { glyph: '大', name: 'dà', latin: 'big', sound: 'said dà', example: { word: '大学', say: 'dà xué', means: 'university' } },
  { glyph: '女', name: 'nǚ', latin: 'woman', sound: 'said nǚ', example: { word: '女人', say: 'nǚ rén', means: 'woman' } },
  { glyph: '子', name: 'zǐ', latin: 'child', sound: 'said zǐ', example: { word: '孩子', say: 'hái zi', means: 'child' } },
  { glyph: '宀', name: 'mián', latin: 'roof', sound: 'said mián', example: { word: '家', say: 'jiā', means: 'home' } },
  { glyph: '寸', name: 'cùn', latin: 'inch', sound: 'said cùn' },
  { glyph: '小', name: 'xiǎo', latin: 'small', sound: 'said xiǎo', example: { word: '小心', say: 'xiǎo xīn', means: 'careful' } },
  { glyph: '尢', name: 'wāng', latin: 'lame', sound: 'said wāng' },
  { glyph: '尸', name: 'shī', latin: 'corpse', sound: 'said shī' },
  { glyph: '屮', name: 'chè', latin: 'sprout', sound: 'said chè' },
  { glyph: '山', name: 'shān', latin: 'mountain', sound: 'said shān', example: { word: '山水', say: 'shān shuǐ', means: 'landscape' } },
  { glyph: '巛', name: 'chuān', latin: 'river', sound: 'said chuān' },
  { glyph: '工', name: 'gōng', latin: 'work', sound: 'said gōng', example: { word: '工作', say: 'gōng zuò', means: 'work' } },
  { glyph: '己', name: 'jǐ', latin: 'oneself', sound: 'said jǐ' },
  { glyph: '巾', name: 'jīn', latin: 'turban', sound: 'said jīn' },
  { glyph: '干', name: 'gān', latin: 'dry', sound: 'said gān' },
  { glyph: '幺', name: 'yāo', latin: 'short thread', sound: 'said yāo' },
  { glyph: '广', name: 'yǎn', latin: 'dotted cliff', sound: 'said yǎn' },
  { glyph: '廴', name: 'yǐn', latin: 'long stride', sound: 'said yǐn' },
  { glyph: '廾', name: 'gǒng', latin: 'two hands', sound: 'said gǒng' },
  { glyph: '弋', name: 'yì', latin: 'shoot', sound: 'said yì' },
  { glyph: '弓', name: 'gōng', latin: 'bow', sound: 'said gōng' },
  { glyph: '彐', name: 'jì', latin: 'snout', sound: 'said jì' },
  { glyph: '彡', name: 'shān', latin: 'bristle', sound: 'said shān' },
  { glyph: '彳', name: 'chì', latin: 'step', sound: 'said chì' },
  { glyph: '心', name: 'xīn', latin: 'heart', sound: 'said xīn', example: { word: '心情', say: 'xīn qíng', means: 'mood' } },
  { glyph: '戈', name: 'gē', latin: 'halberd', sound: 'said gē' },
  { glyph: '戶', name: 'hù', latin: 'door', sound: 'said hù' },
  { glyph: '手', name: 'shǒu', latin: 'hand', sound: 'said shǒu', example: { word: '手机', say: 'shǒu jī', means: 'phone' } },
  { glyph: '支', name: 'zhī', latin: 'branch', sound: 'said zhī' },
  { glyph: '攴', name: 'pū', latin: 'rap', sound: 'said pū' },
  { glyph: '文', name: 'wén', latin: 'script', sound: 'said wén' },
  { glyph: '斗', name: 'dǒu', latin: 'dipper', sound: 'said dǒu' },
  { glyph: '斤', name: 'jīn', latin: 'axe', sound: 'said jīn' },
  { glyph: '方', name: 'fāng', latin: 'square', sound: 'said fāng' },
  { glyph: '无', name: 'wú', latin: 'not', sound: 'said wú' },
  { glyph: '日', name: 'rì', latin: 'sun', sound: 'said rì', example: { word: '日子', say: 'rì zi', means: 'day' } },
  { glyph: '曰', name: 'yuē', latin: 'say', sound: 'said yuē' },
  { glyph: '月', name: 'yuè', latin: 'moon', sound: 'said yuè', example: { word: '月亮', say: 'yuè liàng', means: 'moon' } },
  { glyph: '木', name: 'mù', latin: 'tree', sound: 'said mù', example: { word: '木头', say: 'mù tou', means: 'wood' } },
  { glyph: '欠', name: 'qiàn', latin: 'lack', sound: 'said qiàn' },
  { glyph: '止', name: 'zhǐ', latin: 'stop', sound: 'said zhǐ' },
  { glyph: '歹', name: 'dǎi', latin: 'death', sound: 'said dǎi' },
  { glyph: '殳', name: 'shū', latin: 'weapon', sound: 'said shū' },
  { glyph: '毋', name: 'wú', latin: 'do not', sound: 'said wú' },
  { glyph: '比', name: 'bǐ', latin: 'compare', sound: 'said bǐ' },
  { glyph: '毛', name: 'máo', latin: 'fur', sound: 'said máo' },
  { glyph: '氏', name: 'shì', latin: 'clan', sound: 'said shì' },
  { glyph: '气', name: 'qì', latin: 'steam', sound: 'said qì', example: { word: '空气', say: 'kōng qì', means: 'air' } },
  { glyph: '水', name: 'shuǐ', latin: 'water', sound: 'said shuǐ', example: { word: '水果', say: 'shuǐ guǒ', means: 'fruit' } },
  { glyph: '火', name: 'huǒ', latin: 'fire', sound: 'said huǒ', example: { word: '火车', say: 'huǒ chē', means: 'train' } },
  { glyph: '爪', name: 'zhǎo', latin: 'claw', sound: 'said zhǎo' },
  { glyph: '父', name: 'fù', latin: 'father', sound: 'said fù' },
  { glyph: '爻', name: 'yáo', latin: 'lines', sound: 'said yáo' },
  { glyph: '爿', name: 'qiáng', latin: 'split wood', sound: 'said qiáng' },
  { glyph: '片', name: 'piàn', latin: 'slice', sound: 'said piàn' },
  { glyph: '牙', name: 'yá', latin: 'tooth', sound: 'said yá' },
  { glyph: '牛', name: 'niú', latin: 'cow', sound: 'said niú', example: { word: '牛奶', say: 'niú nǎi', means: 'milk' } },
  { glyph: '犬', name: 'quǎn', latin: 'dog', sound: 'said quǎn', example: { word: '狗', say: 'gǒu', means: 'dog' } },
  { glyph: '玄', name: 'xuán', latin: 'dark', sound: 'said xuán' },
  { glyph: '玉', name: 'yù', latin: 'jade', sound: 'said yù', example: { word: '玉石', say: 'yù shí', means: 'jade' } },
  { glyph: '瓜', name: 'guā', latin: 'melon', sound: 'said guā' },
  { glyph: '瓦', name: 'wǎ', latin: 'tile', sound: 'said wǎ' },
  { glyph: '甘', name: 'gān', latin: 'sweet', sound: 'said gān' },
  { glyph: '生', name: 'shēng', latin: 'life', sound: 'said shēng', example: { word: '生活', say: 'shēng huó', means: 'life' } },
  { glyph: '用', name: 'yòng', latin: 'use', sound: 'said yòng' },
  { glyph: '田', name: 'tián', latin: 'field', sound: 'said tián', example: { word: '田野', say: 'tián yě', means: 'field' } },
  { glyph: '疋', name: 'pǐ', latin: 'bolt of cloth', sound: 'said pǐ' },
  { glyph: '疒', name: 'nè', latin: 'sickness', sound: 'said nè' },
  { glyph: '癶', name: 'bō', latin: 'footsteps', sound: 'said bō' },
  { glyph: '白', name: 'bái', latin: 'white', sound: 'said bái', example: { word: '白色', say: 'bái sè', means: 'white' } },
  { glyph: '皮', name: 'pí', latin: 'skin', sound: 'said pí' },
  { glyph: '皿', name: 'mǐn', latin: 'dish', sound: 'said mǐn' },
  { glyph: '目', name: 'mù', latin: 'eye', sound: 'said mù', example: { word: '目光', say: 'mù guāng', means: 'gaze' } },
  { glyph: '矛', name: 'máo', latin: 'spear', sound: 'said máo' },
  { glyph: '矢', name: 'shǐ', latin: 'arrow', sound: 'said shǐ' },
  { glyph: '石', name: 'shí', latin: 'stone', sound: 'said shí', example: { word: '石头', say: 'shí tou', means: 'stone' } },
  { glyph: '示', name: 'shì', latin: 'spirit', sound: 'said shì' },
  { glyph: '禸', name: 'róu', latin: 'track', sound: 'said róu' },
  { glyph: '禾', name: 'hé', latin: 'grain', sound: 'said hé', example: { word: '禾苗', say: 'hé miáo', means: 'seedling' } },
  { glyph: '穴', name: 'xué', latin: 'cave', sound: 'said xué' },
  { glyph: '立', name: 'lì', latin: 'stand', sound: 'said lì', example: { word: '立刻', say: 'lì kè', means: 'at once' } },
  { glyph: '竹', name: 'zhú', latin: 'bamboo', sound: 'said zhú', example: { word: '竹子', say: 'zhú zi', means: 'bamboo' } },
  { glyph: '米', name: 'mǐ', latin: 'rice', sound: 'said mǐ', example: { word: '米饭', say: 'mǐ fàn', means: 'rice' } },
  { glyph: '糸', name: 'mì', latin: 'silk', sound: 'said mì', example: { word: '红', say: 'hóng', means: 'red' } },
  { glyph: '缶', name: 'fǒu', latin: 'jar', sound: 'said fǒu' },
  { glyph: '网', name: 'wǎng', latin: 'net', sound: 'said wǎng' },
  { glyph: '羊', name: 'yáng', latin: 'sheep', sound: 'said yáng', example: { word: '羊肉', say: 'yáng ròu', means: 'mutton' } },
  { glyph: '羽', name: 'yǔ', latin: 'feather', sound: 'said yǔ' },
  { glyph: '老', name: 'lǎo', latin: 'old', sound: 'said lǎo', example: { word: '老师', say: 'lǎo shī', means: 'teacher' } },
  { glyph: '而', name: 'ér', latin: 'and', sound: 'said ér', example: { word: '而且', say: 'ér qiě', means: 'moreover' } },
  { glyph: '耒', name: 'lěi', latin: 'plough', sound: 'said lěi' },
  { glyph: '耳', name: 'ěr', latin: 'ear', sound: 'said ěr', example: { word: '耳朵', say: 'ěr duo', means: 'ear' } },
  { glyph: '聿', name: 'yù', latin: 'brush', sound: 'said yù' },
  { glyph: '肉', name: 'ròu', latin: 'meat', sound: 'said ròu', example: { word: '肉类', say: 'ròu lèi', means: 'meat' } },
  { glyph: '臣', name: 'chén', latin: 'minister', sound: 'said chén' },
  { glyph: '自', name: 'zì', latin: 'self', sound: 'said zì', example: { word: '自己', say: 'zì jǐ', means: 'oneself' } },
  { glyph: '至', name: 'zhì', latin: 'arrive', sound: 'said zhì', example: { word: '至少', say: 'zhì shǎo', means: 'at least' } },
  { glyph: '臼', name: 'jiù', latin: 'mortar', sound: 'said jiù' },
  { glyph: '舌', name: 'shé', latin: 'tongue', sound: 'said shé', example: { word: '舌头', say: 'shé tou', means: 'tongue' } },
  { glyph: '舛', name: 'chuǎn', latin: 'oppose', sound: 'said chuǎn' },
  { glyph: '舟', name: 'zhōu', latin: 'boat', sound: 'said zhōu', example: { word: '小舟', say: 'xiǎo zhōu', means: 'small boat' } },
  { glyph: '艮', name: 'gèn', latin: 'stopping', sound: 'said gèn' },
  { glyph: '色', name: 'sè', latin: 'colour', sound: 'said sè', example: { word: '颜色', say: 'yán sè', means: 'colour' } },
  { glyph: '艸', name: 'cǎo', latin: 'grass', sound: 'said cǎo', example: { word: '花草', say: 'huā cǎo', means: 'flowers and grass' } },
  { glyph: '虍', name: 'hū', latin: 'tiger', sound: 'said hū' },
  { glyph: '虫', name: 'chóng', latin: 'insect', sound: 'said chóng', example: { word: '虫子', say: 'chóng zi', means: 'insect' } },
  { glyph: '血', name: 'xuè', latin: 'blood', sound: 'said xuè', example: { word: '血液', say: 'xuè yè', means: 'blood' } },
  { glyph: '行', name: 'xíng', latin: 'walk', sound: 'said xíng', example: { word: '行走', say: 'xíng zǒu', means: 'to walk' } },
  { glyph: '衣', name: 'yī', latin: 'clothes', sound: 'said yī', example: { word: '衣服', say: 'yī fu', means: 'clothes' } },
  { glyph: '襾', name: 'yà', latin: 'cover', sound: 'said yà' },
  { glyph: '見', name: 'jiàn', latin: 'see', sound: 'said jiàn', example: { word: '看见', say: 'kàn jiàn', means: 'to see' } },
  { glyph: '角', name: 'jiǎo', latin: 'horn', sound: 'said jiǎo' },
  { glyph: '言', name: 'yán', latin: 'speech', sound: 'said yán', example: { word: '语言', say: 'yǔ yán', means: 'language' } },
  { glyph: '谷', name: 'gǔ', latin: 'valley', sound: 'said gǔ' },
  { glyph: '豆', name: 'dòu', latin: 'bean', sound: 'said dòu', example: { word: '豆腐', say: 'dòu fu', means: 'tofu' } },
  { glyph: '豕', name: 'shǐ', latin: 'pig', sound: 'said shǐ' },
  { glyph: '豸', name: 'zhì', latin: 'badger', sound: 'said zhì' },
  { glyph: '貝', name: 'bèi', latin: 'shell', sound: 'said bèi', example: { word: '宝贝', say: 'bǎo bèi', means: 'treasure' } },
  { glyph: '赤', name: 'chì', latin: 'red', sound: 'said chì' },
  { glyph: '走', name: 'zǒu', latin: 'run', sound: 'said zǒu', example: { word: '走路', say: 'zǒu lù', means: 'to walk' } },
  { glyph: '足', name: 'zú', latin: 'foot', sound: 'said zú', example: { word: '足球', say: 'zú qiú', means: 'football' } },
  { glyph: '身', name: 'shēn', latin: 'body', sound: 'said shēn', example: { word: '身体', say: 'shēn tǐ', means: 'body' } },
  { glyph: '車', name: 'chē', latin: 'cart', sound: 'said chē', example: { word: '汽车', say: 'qì chē', means: 'car' } },
  { glyph: '辛', name: 'xīn', latin: 'bitter', sound: 'said xīn' },
  { glyph: '辰', name: 'chén', latin: 'morning', sound: 'said chén' },
  { glyph: '辵', name: 'chuò', latin: 'walk', sound: 'said chuò' },
  { glyph: '邑', name: 'yì', latin: 'city', sound: 'said yì' },
  { glyph: '酉', name: 'yǒu', latin: 'wine', sound: 'said yǒu' },
  { glyph: '釆', name: 'biàn', latin: 'distinguish', sound: 'said biàn' },
  { glyph: '里', name: 'lǐ', latin: 'village', sound: 'said lǐ', example: { word: '里面', say: 'lǐ miàn', means: 'inside' } },
  { glyph: '金', name: 'jīn', latin: 'gold', sound: 'said jīn', example: { word: '金子', say: 'jīn zi', means: 'gold' } },
  { glyph: '長', name: 'cháng', latin: 'long', sound: 'said cháng', example: { word: '长大', say: 'zhǎng dà', means: 'to grow up' } },
  { glyph: '門', name: 'mén', latin: 'gate', sound: 'said mén', example: { word: '门口', say: 'mén kǒu', means: 'doorway' } },
  { glyph: '阜', name: 'fù', latin: 'mound', sound: 'said fù' },
  { glyph: '隶', name: 'lì', latin: 'slave', sound: 'said lì' },
  { glyph: '隹', name: 'zhuī', latin: 'short tailed bird', sound: 'said zhuī' },
  { glyph: '雨', name: 'yǔ', latin: 'rain', sound: 'said yǔ', example: { word: '下雨', say: 'xià yǔ', means: 'to rain' } },
  { glyph: '靑', name: 'qīng', latin: 'blue', sound: 'said qīng' },
  { glyph: '非', name: 'fēi', latin: 'wrong', sound: 'said fēi' },
  { glyph: '面', name: 'miàn', latin: 'face', sound: 'said miàn' },
  { glyph: '革', name: 'gé', latin: 'leather', sound: 'said gé' },
  { glyph: '韋', name: 'wéi', latin: 'tanned leather', sound: 'said wéi' },
  { glyph: '韭', name: 'jiǔ', latin: 'leek', sound: 'said jiǔ' },
  { glyph: '音', name: 'yīn', latin: 'sound', sound: 'said yīn' },
  { glyph: '頁', name: 'yè', latin: 'leaf', sound: 'said yè' },
  { glyph: '風', name: 'fēng', latin: 'wind', sound: 'said fēng', example: { word: '大风', say: 'dà fēng', means: 'strong wind' } },
  { glyph: '飛', name: 'fēi', latin: 'fly', sound: 'said fēi', example: { word: '飞机', say: 'fēi jī', means: 'aeroplane' } },
  { glyph: '食', name: 'shí', latin: 'eat', sound: 'said shí', example: { word: '食物', say: 'shí wù', means: 'food' } },
  { glyph: '首', name: 'shǒu', latin: 'head', sound: 'said shǒu', example: { word: '首都', say: 'shǒu dū', means: 'capital' } },
  { glyph: '香', name: 'xiāng', latin: 'fragrant', sound: 'said xiāng' },
  { glyph: '馬', name: 'mǎ', latin: 'horse', sound: 'said mǎ', example: { word: '马路', say: 'mǎ lù', means: 'road' } },
  { glyph: '骨', name: 'gǔ', latin: 'bone', sound: 'said gǔ', example: { word: '骨头', say: 'gǔ tou', means: 'bone' } },
  { glyph: '高', name: 'gāo', latin: 'tall', sound: 'said gāo', example: { word: '高兴', say: 'gāo xìng', means: 'happy' } },
  { glyph: '髟', name: 'biāo', latin: 'hair', sound: 'said biāo' },
  { glyph: '鬥', name: 'dòu', latin: 'fight', sound: 'said dòu' },
  { glyph: '鬯', name: 'chàng', latin: 'sacrificial wine', sound: 'said chàng' },
  { glyph: '鬲', name: 'lì', latin: 'cauldron', sound: 'said lì' },
  { glyph: '鬼', name: 'guǐ', latin: 'ghost', sound: 'said guǐ' },
  { glyph: '魚', name: 'yú', latin: 'fish', sound: 'said yú', example: { word: '鱼肉', say: 'yú ròu', means: 'fish' } },
  { glyph: '鳥', name: 'niǎo', latin: 'bird', sound: 'said niǎo', example: { word: '小鸟', say: 'xiǎo niǎo', means: 'little bird' } },
  { glyph: '鹵', name: 'lǔ', latin: 'salt', sound: 'said lǔ' },
  { glyph: '鹿', name: 'lù', latin: 'deer', sound: 'said lù' },
  { glyph: '麥', name: 'mài', latin: 'wheat', sound: 'said mài' },
  { glyph: '麻', name: 'má', latin: 'hemp', sound: 'said má' },
  { glyph: '黃', name: 'huáng', latin: 'yellow', sound: 'said huáng' },
  { glyph: '黍', name: 'shǔ', latin: 'millet', sound: 'said shǔ' },
  { glyph: '黑', name: 'hēi', latin: 'black', sound: 'said hēi', example: { word: '黑色', say: 'hēi sè', means: 'black' } },
  { glyph: '黹', name: 'zhǐ', latin: 'embroidery', sound: 'said zhǐ' },
  { glyph: '黽', name: 'mǐn', latin: 'frog', sound: 'said mǐn' },
  { glyph: '鼎', name: 'dǐng', latin: 'tripod', sound: 'said dǐng' },
  { glyph: '鼓', name: 'gǔ', latin: 'drum', sound: 'said gǔ', example: { word: '打鼓', say: 'dǎ gǔ', means: 'to drum' } },
  { glyph: '鼠', name: 'shǔ', latin: 'rat', sound: 'said shǔ' },
  { glyph: '鼻', name: 'bí', latin: 'nose', sound: 'said bí', example: { word: '鼻子', say: 'bí zi', means: 'nose' } },
  { glyph: '齊', name: 'qí', latin: 'even', sound: 'said qí' },
  { glyph: '齒', name: 'chǐ', latin: 'tooth', sound: 'said chǐ', example: { word: '牙齿', say: 'yá chǐ', means: 'teeth' } },
  { glyph: '龍', name: 'lóng', latin: 'dragon', sound: 'said lóng', example: { word: '龙', say: 'lóng', means: 'dragon' } },
  { glyph: '龜', name: 'guī', latin: 'turtle', sound: 'said guī' },
  { glyph: '龠', name: 'yuè', latin: 'flute', sound: 'said yuè' },
];

const commonHanzi = [
  { glyph: '的', name: 'de', latin: 'possessive particle', sound: 'said de' },
  { glyph: '一', name: 'yī', latin: 'one', sound: 'said yī' },
  { glyph: '是', name: 'shì', latin: 'to be', sound: 'said shì' },
  { glyph: '不', name: 'bù', latin: 'not', sound: 'said bù' },
  { glyph: '了', name: 'le', latin: 'completed action', sound: 'said le' },
  { glyph: '人', name: 'rén', latin: 'person', sound: 'said rén' },
  { glyph: '我', name: 'wǒ', latin: 'I', sound: 'said wǒ' },
  { glyph: '在', name: 'zài', latin: 'at', sound: 'said zài' },
  { glyph: '有', name: 'yǒu', latin: 'to have', sound: 'said yǒu' },
  { glyph: '他', name: 'tā', latin: 'he', sound: 'said tā' },
  { glyph: '这', name: 'zhè', latin: 'this', sound: 'said zhè' },
  { glyph: '为', name: 'wèi', latin: 'for', sound: 'said wèi' },
  { glyph: '之', name: 'zhī', latin: 'of', sound: 'said zhī' },
  { glyph: '大', name: 'dà', latin: 'big', sound: 'said dà' },
  { glyph: '来', name: 'lái', latin: 'to come', sound: 'said lái' },
  { glyph: '以', name: 'yǐ', latin: 'by means of', sound: 'said yǐ' },
  { glyph: '个', name: 'gè', latin: 'general measure word', sound: 'said gè' },
  { glyph: '中', name: 'zhōng', latin: 'middle', sound: 'said zhōng' },
  { glyph: '上', name: 'shàng', latin: 'above', sound: 'said shàng' },
  { glyph: '们', name: 'men', latin: 'plural marker', sound: 'said men' },
  { glyph: '到', name: 'dào', latin: 'to arrive', sound: 'said dào' },
  { glyph: '说', name: 'shuō', latin: 'to speak', sound: 'said shuō' },
  { glyph: '国', name: 'guó', latin: 'country', sound: 'said guó' },
  { glyph: '和', name: 'hé', latin: 'and', sound: 'said hé' },
  { glyph: '地', name: 'dì', latin: 'earth', sound: 'said dì' },
  { glyph: '也', name: 'yě', latin: 'also', sound: 'said yě' },
  { glyph: '子', name: 'zi', latin: 'child', sound: 'said zi' },
  { glyph: '时', name: 'shí', latin: 'time', sound: 'said shí' },
  { glyph: '道', name: 'dào', latin: 'way', sound: 'said dào' },
  { glyph: '出', name: 'chū', latin: 'to go out', sound: 'said chū' },
  { glyph: '而', name: 'ér', latin: 'and yet', sound: 'said ér' },
  { glyph: '要', name: 'yào', latin: 'to want', sound: 'said yào' },
  { glyph: '于', name: 'yú', latin: 'at', sound: 'said yú' },
  { glyph: '就', name: 'jiù', latin: 'then', sound: 'said jiù' },
  { glyph: '下', name: 'xià', latin: 'below', sound: 'said xià' },
  { glyph: '得', name: 'dé', latin: 'to obtain', sound: 'said dé' },
  { glyph: '可', name: 'kě', latin: 'can', sound: 'said kě' },
  { glyph: '你', name: 'nǐ', latin: 'you', sound: 'said nǐ' },
  { glyph: '年', name: 'nián', latin: 'year', sound: 'said nián' },
  { glyph: '生', name: 'shēng', latin: 'to be born', sound: 'said shēng' },
  { glyph: '自', name: 'zì', latin: 'self', sound: 'said zì' },
  { glyph: '会', name: 'huì', latin: 'can', sound: 'said huì' },
  { glyph: '那', name: 'nà', latin: 'that', sound: 'said nà' },
  { glyph: '后', name: 'hòu', latin: 'after', sound: 'said hòu' },
  { glyph: '能', name: 'néng', latin: 'to be able', sound: 'said néng' },
  { glyph: '对', name: 'duì', latin: 'correct', sound: 'said duì' },
  { glyph: '着', name: 'zhe', latin: 'ongoing action', sound: 'said zhe' },
  { glyph: '事', name: 'shì', latin: 'matter', sound: 'said shì' },
  { glyph: '其', name: 'qí', latin: 'its', sound: 'said qí' },
  { glyph: '里', name: 'lǐ', latin: 'inside', sound: 'said lǐ' },
  { glyph: '所', name: 'suǒ', latin: 'place', sound: 'said suǒ' },
  { glyph: '去', name: 'qù', latin: 'to go', sound: 'said qù' },
  { glyph: '行', name: 'xíng', latin: 'to walk', sound: 'said xíng' },
  { glyph: '家', name: 'jiā', latin: 'home', sound: 'said jiā' },
  { glyph: '十', name: 'shí', latin: 'ten', sound: 'said shí' },
  { glyph: '用', name: 'yòng', latin: 'to use', sound: 'said yòng' },
  { glyph: '发', name: 'fā', latin: 'to send', sound: 'said fā' },
  { glyph: '天', name: 'tiān', latin: 'day', sound: 'said tiān' },
  { glyph: '如', name: 'rú', latin: 'as if', sound: 'said rú' },
  { glyph: '然', name: 'rán', latin: 'so', sound: 'said rán' },
  { glyph: '作', name: 'zuò', latin: 'to do', sound: 'said zuò' },
  { glyph: '方', name: 'fāng', latin: 'square', sound: 'said fāng' },
  { glyph: '成', name: 'chéng', latin: 'to become', sound: 'said chéng' },
  { glyph: '者', name: 'zhě', latin: 'one who', sound: 'said zhě' },
  { glyph: '多', name: 'duō', latin: 'many', sound: 'said duō' },
  { glyph: '日', name: 'rì', latin: 'sun', sound: 'said rì' },
  { glyph: '都', name: 'dōu', latin: 'all', sound: 'said dōu' },
  { glyph: '三', name: 'sān', latin: 'three', sound: 'said sān' },
  { glyph: '小', name: 'xiǎo', latin: 'small', sound: 'said xiǎo' },
  { glyph: '军', name: 'jūn', latin: 'army', sound: 'said jūn' },
  { glyph: '二', name: 'èr', latin: 'two', sound: 'said èr' },
  { glyph: '无', name: 'wú', latin: 'without', sound: 'said wú' },
  { glyph: '同', name: 'tóng', latin: 'same', sound: 'said tóng' },
  { glyph: '经', name: 'jīng', latin: 'to pass through', sound: 'said jīng' },
  { glyph: '法', name: 'fǎ', latin: 'law', sound: 'said fǎ' },
  { glyph: '当', name: 'dāng', latin: 'to serve as', sound: 'said dāng' },
  { glyph: '起', name: 'qǐ', latin: 'to rise', sound: 'said qǐ' },
  { glyph: '与', name: 'yǔ', latin: 'with', sound: 'said yǔ' },
  { glyph: '好', name: 'hǎo', latin: 'good', sound: 'said hǎo' },
  { glyph: '看', name: 'kàn', latin: 'to look', sound: 'said kàn' },
  { glyph: '学', name: 'xué', latin: 'to study', sound: 'said xué' },
  { glyph: '进', name: 'jìn', latin: 'to enter', sound: 'said jìn' },
  { glyph: '种', name: 'zhǒng', latin: 'kind', sound: 'said zhǒng' },
  { glyph: '将', name: 'jiāng', latin: 'will', sound: 'said jiāng' },
  { glyph: '还', name: 'hái', latin: 'still', sound: 'said hái' },
  { glyph: '分', name: 'fēn', latin: 'to divide', sound: 'said fēn' },
  { glyph: '此', name: 'cǐ', latin: 'this', sound: 'said cǐ' },
  { glyph: '心', name: 'xīn', latin: 'heart', sound: 'said xīn' },
  { glyph: '前', name: 'qián', latin: 'front', sound: 'said qián' },
  { glyph: '面', name: 'miàn', latin: 'face', sound: 'said miàn' },
  { glyph: '又', name: 'yòu', latin: 'again', sound: 'said yòu' },
  { glyph: '定', name: 'dìng', latin: 'to settle', sound: 'said dìng' },
  { glyph: '见', name: 'jiàn', latin: 'to see', sound: 'said jiàn' },
  { glyph: '只', name: 'zhǐ', latin: 'only', sound: 'said zhǐ' },
  { glyph: '主', name: 'zhǔ', latin: 'main', sound: 'said zhǔ' },
  { glyph: '没', name: 'méi', latin: 'not have', sound: 'said méi' },
  { glyph: '公', name: 'gōng', latin: 'public', sound: 'said gōng' },
  { glyph: '从', name: 'cóng', latin: 'from', sound: 'said cóng' },
  { glyph: '问', name: 'wèn', latin: 'to ask', sound: 'said wèn' },
  { glyph: '点', name: 'diǎn', latin: 'dot', sound: 'said diǎn' },
  { glyph: '现', name: 'xiàn', latin: 'now', sound: 'said xiàn' },
  { glyph: '高', name: 'gāo', latin: 'tall', sound: 'said gāo' },
  { glyph: '月', name: 'yuè', latin: 'moon', sound: 'said yuè' },
  { glyph: '本', name: 'běn', latin: 'root', sound: 'said běn' },
  { glyph: '知', name: 'zhī', latin: 'to know', sound: 'said zhī' },
  { glyph: '理', name: 'lǐ', latin: 'reason', sound: 'said lǐ' },
  { glyph: '车', name: 'chē', latin: 'car', sound: 'said chē' },
  { glyph: '水', name: 'shuǐ', latin: 'water', sound: 'said shuǐ' },
  { glyph: '手', name: 'shǒu', latin: 'hand', sound: 'said shǒu' },
  { glyph: '四', name: 'sì', latin: 'four', sound: 'said sì' },
  { glyph: '开', name: 'kāi', latin: 'to open', sound: 'said kāi' },
  { glyph: '外', name: 'wài', latin: 'outside', sound: 'said wài' },
  { glyph: '王', name: 'wáng', latin: 'king', sound: 'said wáng' },
  { glyph: '明', name: 'míng', latin: 'bright', sound: 'said míng' },
  { glyph: '力', name: 'lì', latin: 'strength', sound: 'said lì' },
  { glyph: '文', name: 'wén', latin: 'writing', sound: 'said wén' },
  { glyph: '金', name: 'jīn', latin: 'gold', sound: 'said jīn' },
  { glyph: '东', name: 'dōng', latin: 'east', sound: 'said dōng' },
  { glyph: '西', name: 'xī', latin: 'west', sound: 'said xī' },
  { glyph: '南', name: 'nán', latin: 'south', sound: 'said nán' },
  { glyph: '北', name: 'běi', latin: 'north', sound: 'said běi' },
  { glyph: '白', name: 'bái', latin: 'white', sound: 'said bái' },
  { glyph: '话', name: 'huà', latin: 'speech', sound: 'said huà' },
  { glyph: '长', name: 'cháng', latin: 'long', sound: 'said cháng' },
  { glyph: '新', name: 'xīn', latin: 'new', sound: 'said xīn' },
  { glyph: '老', name: 'lǎo', latin: 'old', sound: 'said lǎo' },
  { glyph: '名', name: 'míng', latin: 'name', sound: 'said míng' },
  { glyph: '放', name: 'fàng', latin: 'to put', sound: 'said fàng' },
  { glyph: '听', name: 'tīng', latin: 'to listen', sound: 'said tīng' },
  { glyph: '吃', name: 'chī', latin: 'to eat', sound: 'said chī' },
  { glyph: '写', name: 'xiě', latin: 'to write', sound: 'said xiě' },
  { glyph: '爱', name: 'ài', latin: 'love', sound: 'said ài' },
  { glyph: '朋', name: 'péng', latin: 'friend', sound: 'said péng' },
  { glyph: '友', name: 'yǒu', latin: 'friend', sound: 'said yǒu' },
  { glyph: '女', name: 'nǚ', latin: 'woman', sound: 'said nǚ' },
  { glyph: '男', name: 'nán', latin: 'man', sound: 'said nán' },
  { glyph: '父', name: 'fù', latin: 'father', sound: 'said fù' },
  { glyph: '母', name: 'mǔ', latin: 'mother', sound: 'said mǔ' },
  { glyph: '哥', name: 'gē', latin: 'elder brother', sound: 'said gē' },
  { glyph: '姐', name: 'jiě', latin: 'elder sister', sound: 'said jiě' },
  { glyph: '儿', name: 'ér', latin: 'son', sound: 'said ér' },
  { glyph: '书', name: 'shū', latin: 'book', sound: 'said shū' },
  { glyph: '校', name: 'xiào', latin: 'school', sound: 'said xiào' },
  { glyph: '师', name: 'shī', latin: 'teacher', sound: 'said shī' },
  { glyph: '医', name: 'yī', latin: 'medicine', sound: 'said yī' },
  { glyph: '院', name: 'yuàn', latin: 'courtyard', sound: 'said yuàn' },
  { glyph: '店', name: 'diàn', latin: 'shop', sound: 'said diàn' },
  { glyph: '钱', name: 'qián', latin: 'money', sound: 'said qián' },
  { glyph: '买', name: 'mǎi', latin: 'to buy', sound: 'said mǎi' },
  { glyph: '卖', name: 'mài', latin: 'to sell', sound: 'said mài' },
  { glyph: '路', name: 'lù', latin: 'road', sound: 'said lù' },
  { glyph: '门', name: 'mén', latin: 'door', sound: 'said mén' },
  { glyph: '房', name: 'fáng', latin: 'house', sound: 'said fáng' },
  { glyph: '床', name: 'chuáng', latin: 'bed', sound: 'said chuáng' },
  { glyph: '饭', name: 'fàn', latin: 'cooked rice', sound: 'said fàn' },
  { glyph: '茶', name: 'chá', latin: 'tea', sound: 'said chá' },
  { glyph: '菜', name: 'cài', latin: 'dish', sound: 'said cài' },
  { glyph: '肉', name: 'ròu', latin: 'meat', sound: 'said ròu' },
  { glyph: '鱼', name: 'yú', latin: 'fish', sound: 'said yú' },
  { glyph: '果', name: 'guǒ', latin: 'fruit', sound: 'said guǒ' },
  { glyph: '花', name: 'huā', latin: 'flower', sound: 'said huā' },
  { glyph: '草', name: 'cǎo', latin: 'grass', sound: 'said cǎo' },
  { glyph: '树', name: 'shù', latin: 'tree', sound: 'said shù' },
  { glyph: '风', name: 'fēng', latin: 'wind', sound: 'said fēng' },
  { glyph: '雨', name: 'yǔ', latin: 'rain', sound: 'said yǔ' },
  { glyph: '雪', name: 'xuě', latin: 'snow', sound: 'said xuě' },
  { glyph: '火', name: 'huǒ', latin: 'fire', sound: 'said huǒ' },
  { glyph: '山', name: 'shān', latin: 'mountain', sound: 'said shān' },
  { glyph: '石', name: 'shí', latin: 'stone', sound: 'said shí' },
  { glyph: '土', name: 'tǔ', latin: 'soil', sound: 'said tǔ' },
  { glyph: '田', name: 'tián', latin: 'field', sound: 'said tián' },
  { glyph: '牛', name: 'niú', latin: 'cow', sound: 'said niú' },
  { glyph: '马', name: 'mǎ', latin: 'horse', sound: 'said mǎ' },
  { glyph: '鸟', name: 'niǎo', latin: 'bird', sound: 'said niǎo' },
  { glyph: '狗', name: 'gǒu', latin: 'dog', sound: 'said gǒu' },
  { glyph: '猫', name: 'māo', latin: 'cat', sound: 'said māo' },
  { glyph: '五', name: 'wǔ', latin: 'five', sound: 'said wǔ' },
  { glyph: '六', name: 'liù', latin: 'six', sound: 'said liù' },
  { glyph: '七', name: 'qī', latin: 'seven', sound: 'said qī' },
  { glyph: '八', name: 'bā', latin: 'eight', sound: 'said bā' },
  { glyph: '九', name: 'jiǔ', latin: 'nine', sound: 'said jiǔ' },
  { glyph: '百', name: 'bǎi', latin: 'hundred', sound: 'said bǎi' },
  { glyph: '千', name: 'qiān', latin: 'thousand', sound: 'said qiān' },
  { glyph: '万', name: 'wàn', latin: 'ten thousand', sound: 'said wàn' },
];

const chineseNumbers = [
  { glyph: '〇', name: 'líng', latin: '0', sound: 'zero, also written 零' },
  { glyph: '一', name: 'yī', latin: '1', sound: 'one' },
  { glyph: '二', name: 'èr', latin: '2', sound: 'two' },
  { glyph: '三', name: 'sān', latin: '3', sound: 'three' },
  { glyph: '四', name: 'sì', latin: '4', sound: 'four' },
  { glyph: '五', name: 'wǔ', latin: '5', sound: 'five' },
  { glyph: '六', name: 'liù', latin: '6', sound: 'six' },
  { glyph: '七', name: 'qī', latin: '7', sound: 'seven' },
  { glyph: '八', name: 'bā', latin: '8', sound: 'eight' },
  { glyph: '九', name: 'jiǔ', latin: '9', sound: 'nine' },
  { glyph: '十', name: 'shí', latin: '10', sound: 'ten' },
  { glyph: '百', name: 'bǎi', latin: '100', sound: 'hundred' },
  { glyph: '千', name: 'qiān', latin: '1000', sound: 'thousand' },
  { glyph: '万', name: 'wàn', latin: '10000', sound: 'ten thousand' },
];

// a word that shows the letter at work
const EXAMPLES = {
  'Α': { word: 'άνθρωπος', say: 'anthropos', means: 'person' },
  'Β': { word: 'βιβλίο', say: 'vivlio', means: 'book' },
  'Γ': { word: 'γάλα', say: 'gala', means: 'milk' },
  'Δ': { word: 'δρόμος', say: 'dromos', means: 'road' },
  'Ε': { word: 'ελπίδα', say: 'elpida', means: 'hope' },
  'Ζ': { word: 'ζωή', say: 'zoi', means: 'life' },
  'Η': { word: 'ήλιος', say: 'ilios', means: 'sun' },
  'Θ': { word: 'θάλασσα', say: 'thalassa', means: 'sea' },
  'Ι': { word: 'ιδέα', say: 'idea', means: 'idea' },
  'Κ': { word: 'καφές', say: 'kafes', means: 'coffee' },
  'Λ': { word: 'λέξη', say: 'lexi', means: 'word' },
  'Μ': { word: 'μέρα', say: 'mera', means: 'day' },
  'Ν': { word: 'νερό', say: 'nero', means: 'water' },
  'Ξ': { word: 'ξύλο', say: 'xylo', means: 'wood' },
  'Ο': { word: 'όνομα', say: 'onoma', means: 'name' },
  'Π': { word: 'πόλη', say: 'poli', means: 'city' },
  'Ρ': { word: 'ρολόι', say: 'roloi', means: 'clock' },
  'Σ': { word: 'σπίτι', say: 'spiti', means: 'house' },
  'Τ': { word: 'τραπέζι', say: 'trapezi', means: 'table' },
  'Υ': { word: 'ύπνος', say: 'ypnos', means: 'sleep' },
  'Φ': { word: 'φίλος', say: 'filos', means: 'friend' },
  'Χ': { word: 'χέρι', say: 'cheri', means: 'hand' },
  'Ψ': { word: 'ψωμί', say: 'psomi', means: 'bread' },
  'Ω': { word: 'ώρα', say: 'ora', means: 'hour' },
  'А': { word: 'август', say: 'avgust', means: 'August' },
  'Б': { word: 'брат', say: 'brat', means: 'brother' },
  'В': { word: 'вода', say: 'voda', means: 'water' },
  'Г': { word: 'город', say: 'gorod', means: 'city' },
  'Д': { word: 'дом', say: 'dom', means: 'house' },
  'Е': { word: 'еда', say: 'yeda', means: 'food' },
  'Ё': { word: 'ёж', say: 'yozh', means: 'hedgehog' },
  'Ж': { word: 'жизнь', say: 'zhizn', means: 'life' },
  'З': { word: 'зима', say: 'zima', means: 'winter' },
  'И': { word: 'имя', say: 'imya', means: 'name' },
  'Й': { word: 'йогурт', say: 'yogurt', means: 'yoghurt' },
  'К': { word: 'книга', say: 'kniga', means: 'book' },
  'Л': { word: 'лес', say: 'les', means: 'forest' },
  'М': { word: 'море', say: 'more', means: 'sea' },
  'Н': { word: 'ночь', say: 'noch', means: 'night' },
  'О': { word: 'окно', say: 'okno', means: 'window' },
  'П': { word: 'парк', say: 'park', means: 'park' },
  'Р': { word: 'река', say: 'reka', means: 'river' },
  'С': { word: 'солнце', say: 'solntse', means: 'sun' },
  'Т': { word: 'театр', say: 'teatr', means: 'theatre' },
  'У': { word: 'улица', say: 'ulitsa', means: 'street' },
  'Ф': { word: 'фильм', say: 'film', means: 'film' },
  'Х': { word: 'хлеб', say: 'khleb', means: 'bread' },
  'Ц': { word: 'цветок', say: 'tsvetok', means: 'flower' },
  'Ч': { word: 'час', say: 'chas', means: 'hour' },
  'Ш': { word: 'школа', say: 'shkola', means: 'school' },
  'Щ': { word: 'щенок', say: 'shchenok', means: 'puppy' },
  'Ъ': { word: 'объект', say: 'obyekt', means: 'object' },
  'Ы': { word: 'сыр', say: 'syr', means: 'cheese' },
  'Ь': { word: 'день', say: 'den', means: 'day' },
  'Э': { word: 'этаж', say: 'etazh', means: 'floor' },
  'Ю': { word: 'юг', say: 'yug', means: 'south' },
  'Я': { word: 'яблоко', say: 'yabloko', means: 'apple' },
  'あ': { word: 'あめ', say: 'ame', means: 'rain' },
  'い': { word: 'いぬ', say: 'inu', means: 'dog' },
  'う': { word: 'うみ', say: 'umi', means: 'sea' },
  'え': { word: 'えき', say: 'eki', means: 'station' },
  'お': { word: 'おちゃ', say: 'ocha', means: 'tea' },
  'か': { word: 'かさ', say: 'kasa', means: 'umbrella' },
  'き': { word: 'きって', say: 'kitte', means: 'stamp' },
  'く': { word: 'くつ', say: 'kutsu', means: 'shoes' },
  'け': { word: 'けさ', say: 'kesa', means: 'this morning' },
  'こ': { word: 'こども', say: 'kodomo', means: 'child' },
  'さ': { word: 'さかな', say: 'sakana', means: 'fish' },
  'し': { word: 'しろ', say: 'shiro', means: 'white' },
  'す': { word: 'すし', say: 'sushi', means: 'sushi' },
  'せ': { word: 'せんせい', say: 'sensei', means: 'teacher' },
  'そ': { word: 'そら', say: 'sora', means: 'sky' },
  'た': { word: 'たまご', say: 'tamago', means: 'egg' },
  'ち': { word: 'ちず', say: 'chizu', means: 'map' },
  'つ': { word: 'つき', say: 'tsuki', means: 'moon' },
  'て': { word: 'てがみ', say: 'tegami', means: 'letter' },
  'と': { word: 'とり', say: 'tori', means: 'bird' },
  'な': { word: 'なつ', say: 'natsu', means: 'summer' },
  'に': { word: 'にわ', say: 'niwa', means: 'garden' },
  'ぬ': { word: 'ぬの', say: 'nuno', means: 'cloth' },
  'ね': { word: 'ねこ', say: 'neko', means: 'cat' },
  'の': { word: 'のり', say: 'nori', means: 'seaweed' },
  'は': { word: 'はな', say: 'hana', means: 'flower' },
  'ひ': { word: 'ひと', say: 'hito', means: 'person' },
  'ふ': { word: 'ふゆ', say: 'fuyu', means: 'winter' },
  'へ': { word: 'へや', say: 'heya', means: 'room' },
  'ほ': { word: 'ほん', say: 'hon', means: 'book' },
  'ま': { word: 'まど', say: 'mado', means: 'window' },
  'み': { word: 'みず', say: 'mizu', means: 'water' },
  'む': { word: 'むし', say: 'mushi', means: 'insect' },
  'め': { word: 'め', say: 'me', means: 'eye' },
  'も': { word: 'もり', say: 'mori', means: 'forest' },
  'や': { word: 'やま', say: 'yama', means: 'mountain' },
  'ゆ': { word: 'ゆき', say: 'yuki', means: 'snow' },
  'よ': { word: 'よる', say: 'yoru', means: 'night' },
  'ら': { word: 'らいねん', say: 'rainen', means: 'next year' },
  'り': { word: 'りんご', say: 'ringo', means: 'apple' },
  'る': { word: 'るす', say: 'rusu', means: 'away from home' },
  'れ': { word: 'れきし', say: 'rekishi', means: 'history' },
  'ろ': { word: 'ろく', say: 'roku', means: 'six' },
  'わ': { word: 'わたし', say: 'watashi', means: 'I' },
  'を': { word: 'ほんをよむ', say: 'hon o yomu', means: 'to read a book' },
  'ん': { word: 'でんわ', say: 'denwa', means: 'telephone' },
  'ア': { word: 'アメリカ', say: 'amerika', means: 'America' },
  'イ': { word: 'インク', say: 'inku', means: 'ink' },
  'ウ': { word: 'ウール', say: 'uuru', means: 'wool' },
  'エ': { word: 'エレベーター', say: 'erebeetaa', means: 'lift' },
  'オ': { word: 'オレンジ', say: 'orenji', means: 'orange' },
  'カ': { word: 'カメラ', say: 'kamera', means: 'camera' },
  'キ': { word: 'キロ', say: 'kiro', means: 'kilo' },
  'ク': { word: 'クラス', say: 'kurasu', means: 'class' },
  'ケ': { word: 'ケーキ', say: 'keeki', means: 'cake' },
  'コ': { word: 'コーヒー', say: 'koohii', means: 'coffee' },
  'サ': { word: 'サラダ', say: 'sarada', means: 'salad' },
  'シ': { word: 'シャツ', say: 'shatsu', means: 'shirt' },
  'ス': { word: 'スープ', say: 'suupu', means: 'soup' },
  'セ': { word: 'セーター', say: 'seetaa', means: 'jumper' },
  'ソ': { word: 'ソファ', say: 'sofa', means: 'sofa' },
  'タ': { word: 'タクシー', say: 'takushii', means: 'taxi' },
  'チ': { word: 'チーズ', say: 'chiizu', means: 'cheese' },
  'ツ': { word: 'ツアー', say: 'tsuaa', means: 'tour' },
  'テ': { word: 'テレビ', say: 'terebi', means: 'television' },
  'ト': { word: 'トマト', say: 'tomato', means: 'tomato' },
  'ナ': { word: 'ナイフ', say: 'naifu', means: 'knife' },
  'ニ': { word: 'ニュース', say: 'nyuusu', means: 'news' },
  'ヌ': { word: 'ヌードル', say: 'nuudoru', means: 'noodle' },
  'ネ': { word: 'ネクタイ', say: 'nekutai', means: 'tie' },
  'ノ': { word: 'ノート', say: 'nooto', means: 'notebook' },
  'ハ': { word: 'ハンカチ', say: 'hankachi', means: 'handkerchief' },
  'ヒ': { word: 'ヒーター', say: 'hiitaa', means: 'heater' },
  'フ': { word: 'フォーク', say: 'fooku', means: 'fork' },
  'ヘ': { word: 'ヘリコプター', say: 'herikoputaa', means: 'helicopter' },
  'ホ': { word: 'ホテル', say: 'hoteru', means: 'hotel' },
  'マ': { word: 'マスク', say: 'masuku', means: 'mask' },
  'ミ': { word: 'ミルク', say: 'miruku', means: 'milk' },
  'ム': { word: 'ムービー', say: 'muubii', means: 'movie' },
  'メ': { word: 'メニュー', say: 'menyuu', means: 'menu' },
  'モ': { word: 'モデル', say: 'moderu', means: 'model' },
  'ヤ': { word: 'タイヤ', say: 'taiya', means: 'tyre' },
  'ユ': { word: 'ユーロ', say: 'yuuro', means: 'euro' },
  'ヨ': { word: 'ヨガ', say: 'yoga', means: 'yoga' },
  'ラ': { word: 'ラジオ', say: 'rajio', means: 'radio' },
  'リ': { word: 'リボン', say: 'ribon', means: 'ribbon' },
  'ル': { word: 'ルール', say: 'ruuru', means: 'rule' },
  'レ': { word: 'レモン', say: 'remon', means: 'lemon' },
  'ロ': { word: 'ロボット', say: 'robotto', means: 'robot' },
  'ワ': { word: 'ワイン', say: 'wain', means: 'wine' },
  'ヲ': { word: 'ヲ', say: 'o', means: 'only used as a particle' },
  'ン': { word: 'パン', say: 'pan', means: 'bread' },
  'ㄅ': { word: '八', say: 'bā', means: 'eight' },
  'ㄆ': { word: '怕', say: 'pà', means: 'to fear' },
  'ㄇ': { word: '馬', say: 'mǎ', means: 'horse' },
  'ㄈ': { word: '飛', say: 'fēi', means: 'to fly' },
  'ㄉ': { word: '大', say: 'dà', means: 'big' },
  'ㄊ': { word: '天', say: 'tiān', means: 'sky' },
  'ㄋ': { word: '你', say: 'nǐ', means: 'you' },
  'ㄌ': { word: '六', say: 'liù', means: 'six' },
  'ㄍ': { word: '哥', say: 'gē', means: 'elder brother' },
  'ㄎ': { word: '看', say: 'kàn', means: 'to look' },
  'ㄏ': { word: '好', say: 'hǎo', means: 'good' },
  'ㄐ': { word: '家', say: 'jiā', means: 'home' },
  'ㄑ': { word: '七', say: 'qī', means: 'seven' },
  'ㄒ': { word: '小', say: 'xiǎo', means: 'small' },
  'ㄓ': { word: '中', say: 'zhōng', means: 'middle' },
  'ㄔ': { word: '吃', say: 'chī', means: 'to eat' },
  'ㄕ': { word: '十', say: 'shí', means: 'ten' },
  'ㄖ': { word: '日', say: 'rì', means: 'sun' },
  'ㄗ': { word: '字', say: 'zì', means: 'character' },
  'ㄘ': { word: '菜', say: 'cài', means: 'dish' },
  'ㄙ': { word: '四', say: 'sì', means: 'four' },
  'ㄧ': { word: '一', say: 'yī', means: 'one' },
  'ㄨ': { word: '五', say: 'wǔ', means: 'five' },
  'ㄩ': { word: '雨', say: 'yǔ', means: 'rain' },
  'ㄚ': { word: '八', say: 'bā', means: 'eight' },
  'ㄛ': { word: '我', say: 'wǒ', means: 'I' },
  'ㄜ': { word: '餓', say: 'è', means: 'hungry' },
  'ㄝ': { word: '爺', say: 'yé', means: 'grandfather' },
  'ㄞ': { word: '愛', say: 'ài', means: 'love' },
  'ㄟ': { word: '美', say: 'měi', means: 'beautiful' },
  'ㄠ': { word: '好', say: 'hǎo', means: 'good' },
  'ㄡ': { word: '狗', say: 'gǒu', means: 'dog' },
  'ㄢ': { word: '安', say: 'ān', means: 'peace' },
  'ㄣ': { word: '人', say: 'rén', means: 'person' },
  'ㄤ': { word: '忙', say: 'máng', means: 'busy' },
  'ㄥ': { word: '風', say: 'fēng', means: 'wind' },
  'ㄦ': { word: '二', say: 'èr', means: 'two' },
  '〇': { word: '〇', say: 'líng', means: 'zero' },
  '一': { word: '一月', say: 'yī yuè', means: 'January' },
  '二': { word: '二十', say: 'èr shí', means: 'twenty' },
  '三': { word: '三天', say: 'sān tiān', means: 'three days' },
  '四': { word: '四季', say: 'sì jì', means: 'four seasons' },
  '五': { word: '五分', say: 'wǔ fēn', means: 'five minutes' },
  '六': { word: '六月', say: 'liù yuè', means: 'June' },
  '七': { word: '七天', say: 'qī tiān', means: 'seven days' },
  '八': { word: '八点', say: 'bā diǎn', means: 'eight o clock' },
  '九': { word: '九十', say: 'jiǔ shí', means: 'ninety' },
  '十': { word: '十年', say: 'shí nián', means: 'ten years' },
  '百': { word: '一百', say: 'yī bǎi', means: 'one hundred' },
  '千': { word: '一千', say: 'yī qiān', means: 'one thousand' },
  '万': { word: '一万', say: 'yī wàn', means: 'ten thousand' },
};

const withExamples = (letters) =>
  letters.map((letter) => (letter.example || !EXAMPLES[letter.glyph] ? letter : { ...letter, example: EXAMPLES[letter.glyph] }));

export const SCRIPTS = [
  {
    id: 'greek',
    name: 'Greek',
    speech: 'el-GR',
    note: 'Twenty four letters, each with a capital and a small form.',
    sets: [{ id: 'greek', name: 'Alphabet', letters: withExamples(greek), cased: true }],
  },
  {
    id: 'cyrillic',
    name: 'Cyrillic',
    speech: 'ru-RU',
    note: 'The Russian alphabet, thirty three letters with capitals and small forms.',
    sets: [{ id: 'russian', name: 'Russian', letters: withExamples(cyrillic), cased: true }],
  },
  {
    id: 'japanese',
    name: 'Japanese',
    speech: 'ja-JP',
    note: 'Two syllabaries of the same sounds: hiragana for Japanese words, katakana for borrowed ones.',
    sets: [
      { id: 'hiragana', name: 'Hiragana', letters: withExamples(hiragana) },
      { id: 'katakana', name: 'Katakana', letters: withExamples(katakana) },
    ],
  },
  {
    id: 'chinese',
    name: 'Chinese',
    speech: 'zh-CN',
    note: 'Chinese is written in characters rather than letters. Bopomofo spells out their sounds, the two hundred and fourteen radicals are the parts every character is built from, and the common characters are the ones that turn up most.',
    sets: [
      { id: 'bopomofo', name: 'Bopomofo', letters: withExamples(bopomofo) },
      { id: 'radicals', name: 'Radicals', letters: withExamples(radicals) },
      { id: 'common', name: 'Common characters', letters: withExamples(commonHanzi) },
      { id: 'numbers', name: 'Numbers', letters: withExamples(chineseNumbers) },
    ],
  },
];

export const scriptById = (id) => SCRIPTS.find((script) => script.id === id) ?? SCRIPTS[0];

export const setById = (scriptId, setId) => {
  const script = scriptById(scriptId);
  return script.sets.find((set) => set.id === setId) ?? script.sets[0];
};

export const letterKey = (letter) => letter.glyph;

// what someone has to answer, and what else could plausibly be offered instead
export const choicesFor = (letters, answer, count = 4) => {
  const others = letters.filter((letter) => letter.latin !== answer.latin);
  const picked = [];
  while (picked.length < Math.min(count - 1, others.length)) {
    const at = Math.floor(Math.random() * others.length);
    const [taken] = others.splice(at, 1);
    if (!picked.some((letter) => letter.latin === taken.latin)) picked.push(taken);
  }
  const all = [answer, ...picked];
  for (let at = all.length - 1; at > 0; at -= 1) {
    const swap = Math.floor(Math.random() * (at + 1));
    [all[at], all[swap]] = [all[swap], all[at]];
  }
  return all;
};

export const LEARNED_AT = 4;

export const strengthOf = (record) => {
  if (!record?.seen) return 0;
  return Math.max(0, Math.min(1, (record.streak ?? 0) / LEARNED_AT));
};

// the ones gone wrong most recently come round again soonest, and anything
// never seen comes before anything already answered
export const nextLetter = (letters, progress, avoid) => {
  const weigh = (letter) => {
    const record = progress[letterKey(letter)];
    if (!record?.seen) return 100;
    const wrong = (record.wrong ?? 0) + 1;
    const streak = Math.min(record.streak ?? 0, LEARNED_AT);
    return Math.max(1, (wrong * 12) / (streak + 1));
  };

  const pool = letters.filter((letter) => letters.length < 2 || letterKey(letter) !== avoid);
  const total = pool.reduce((sum, letter) => sum + weigh(letter), 0);
  let ticket = Math.random() * total;
  for (const letter of pool) {
    ticket -= weigh(letter);
    if (ticket <= 0) return letter;
  }
  return pool[pool.length - 1];
};

export const scoreOf = (letters, progress) => {
  let learned = 0;
  let started = 0;
  for (const letter of letters) {
    const record = progress[letterKey(letter)];
    if (!record?.seen) continue;
    started += 1;
    if ((record.streak ?? 0) >= LEARNED_AT) learned += 1;
  }
  return { learned, started, total: letters.length };
};
