export default {
  id: "ai-writer",
  name: "AI Writer",
  tagline: "Summarise, rewrite, translate and proofread",
  category: "ai",
  glyph: "AIW",
  icon: "pencil",
  tint: "#7e22ce",
  keywords: ["ai","write","summarise","translate","rewrite","commit"],
  tag: "jg-app-ai-writer",
  i18n: {
    de: { name: 'KI-Autor', tagline: 'Zusammenfassen, umschreiben, übersetzen und korrigieren' },
    es: { name: 'Escritor IA', tagline: 'Resumir, reescribir, traducir y corregir' },
    zh: { name: 'AI 写作', tagline: '摘要、改写、翻译与校对' },
    fr: { name: 'Rédacteur IA', tagline: 'Résumer, réécrire, traduire et relire' },
    pt: { name: 'Escritor com IA', tagline: 'Resuma, reescreva, traduza e revise' },
    ja: { name: 'AI ライター', tagline: '要約、書き換え、翻訳、校正' },
    ko: { name: 'AI 글쓰기', tagline: '요약, 다시 쓰기, 번역, 교정' },
  },
  load: () => import('./index.js'),
};
