// Amsterdam's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'amsterdam',
  name: 'Amsterdam',
  system: 'Metro',
  country: 'Netherlands',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '50',
      short: '50',
      name: 'Metro 50',
      colour: '#29ab4d',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['gein', 'reigersbos', 'holendrecht', 'bullewijk', 'bijlmer-arena', 'strandvliet', 'duivendrecht', 'van-der-madeweg', 'overamstel', 'station-rai', 'zuid', 'amstelveenseweg', 'henk-sneevlietweg', 'heemstedestraat', 'lelylaan', 'postjesweg', 'jan-van-galenstraat', 'de-vlugtlaan', 'station-sloterdijk', 'isolatorweg'],
      ],
    },
    {
      id: '51',
      short: '51',
      name: 'Metro 51',
      colour: '#f69931',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['centraal-station', 'nieuwmarkt', 'waterlooplein', 'weesperplein', 'wibautstraat', 'amstelstation', 'spaklerweg', 'overamstel', 'station-rai', 'zuid', 'amstelveenseweg', 'henk-sneevlietweg', 'heemstedestraat', 'lelylaan', 'postjesweg', 'jan-van-galenstraat', 'de-vlugtlaan', 'station-sloterdijk', 'isolatorweg'],
      ],
    },
    {
      id: '52',
      short: '52',
      name: 'Metro 52',
      colour: '#00adef',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['noord', 'noorderpark', 'centraal-station', 'rokin', 'vijzelgracht', 'de-pijp', 'europaplein', 'zuid'],
      ],
    },
    {
      id: '53',
      short: '53',
      name: 'Metro 53',
      colour: '#ff0000',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['centraal-station', 'nieuwmarkt', 'waterlooplein', 'weesperplein', 'wibautstraat', 'amstelstation', 'spaklerweg', 'van-der-madeweg', 'venserpolder', 'station-diemen-zuid', 'verrijn-stuartweg', 'ganzenhoef', 'kraaiennest', 'gaasperplas'],
      ],
    },
    {
      id: '54',
      short: '54',
      name: 'Metro 54',
      colour: '#fcfb05',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['centraal-station', 'nieuwmarkt', 'waterlooplein', 'weesperplein', 'wibautstraat', 'amstelstation', 'spaklerweg', 'van-der-madeweg', 'duivendrecht', 'strandvliet', 'bijlmer-arena', 'bullewijk', 'holendrecht', 'reigersbos', 'gein'],
      ],
    },
  ],
  times: {
    'holendrecht bullewijk': 3,
    'overamstel station-rai': 4,
    'zuid amstelveenseweg': 3,
    'amstelveenseweg henk-sneevlietweg': 4,
    'nieuwmarkt waterlooplein': 1,
    'noord noorderpark': 4,
    'noorderpark centraal-station': 4,
    'de-pijp europaplein': 3,
    'europaplein zuid': 3,
    'spaklerweg van-der-madeweg': 3,
    'van-der-madeweg venserpolder': 3,
    'bullewijk holendrecht': 3,
  },
  stations: {
    'centraal-station': { name: 'Centraal Station', x: 9, y: 3.5 },
    nieuwmarkt: { name: 'Nieuwmarkt', x: 9.5, y: 5 },
    waterlooplein: { name: 'Waterlooplein', x: 8.5, y: 6.5 },
    weesperplein: { name: 'Weesperplein', x: 9.5, y: 7.5 },
    wibautstraat: { name: 'Wibautstraat', x: 9.5, y: 9.5 },
    amstelstation: { name: 'Amstelstation', x: 11, y: 11 },
    spaklerweg: { name: 'Spaklerweg', x: 11, y: 12.5 },
    'van-der-madeweg': { name: 'Van der Madeweg', x: 12, y: 14 },
    duivendrecht: { name: 'Duivendrecht', x: 13.5, y: 15.5 },
    strandvliet: { name: 'Strandvliet', x: 15, y: 17 },
    'bijlmer-arena': { name: 'Bijlmer ArenA', x: 16.5, y: 18.5 },
    bullewijk: { name: 'Bullewijk', x: 18, y: 20 },
    holendrecht: { name: 'Holendrecht', x: 19, y: 21.5 },
    reigersbos: { name: 'Reigersbos', x: 21, y: 21.5 },
    gein: { name: 'Gein', x: 23, y: 21.5 },
    venserpolder: { name: 'Venserpolder', x: 14.5, y: 14 },
    'station-diemen-zuid': { name: 'Station Diemen Zuid', x: 16.5, y: 14 },
    'verrijn-stuartweg': { name: 'Verrijn Stuartweg', x: 18.5, y: 14 },
    ganzenhoef: { name: 'Ganzenhoef', x: 19.5, y: 15.5 },
    kraaiennest: { name: 'Kraaiennest', x: 21, y: 17 },
    gaasperplas: { name: 'Gaasperplas', x: 22.5, y: 18.5 },
    overamstel: { name: 'Overamstel', x: 10, y: 14 },
    'station-rai': { name: 'Station RAI', x: 8, y: 13.5 },
    zuid: { name: 'Zuid', x: 6, y: 13.5 },
    amstelveenseweg: { name: 'Amstelveenseweg', x: 3.5, y: 13 },
    'henk-sneevlietweg': { name: 'Henk Sneevlietweg', x: 1.5, y: 13 },
    heemstedestraat: { name: 'Heemstedestraat', x: 0, y: 11.5 },
    lelylaan: { name: 'Lelylaan', x: 0, y: 9.5 },
    postjesweg: { name: 'Postjesweg', x: 0, y: 7.5 },
    'jan-van-galenstraat': { name: 'Jan van Galenstraat', x: 0, y: 5.5 },
    'de-vlugtlaan': { name: 'De Vlugtlaan', x: 0, y: 3.5 },
    'station-sloterdijk': { name: 'Station Sloterdijk', x: 0, y: 1.5 },
    isolatorweg: { name: 'Isolatorweg', x: 1.5, y: 0 },
    noord: { name: 'Noord', x: 12, y: 0.5 },
    noorderpark: { name: 'Noorderpark', x: 10.5, y: 2 },
    rokin: { name: 'Rokin', x: 7.5, y: 5 },
    vijzelgracht: { name: 'Vijzelgracht', x: 7.5, y: 7.5 },
    'de-pijp': { name: 'De Pijp', x: 7.5, y: 9.5 },
    europaplein: { name: 'Europaplein', x: 7.5, y: 11.5 },
  },
};
