// Athens's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'athens',
  name: 'Athens',
  system: 'Metro',
  country: 'Greece',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: 'Μ1',
      name: 'Μετρό Μ1',
      colour: '#007a33',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['piraeus', 'faliro', 'moschato', 'kallithea', 'tavros-eleftherios-venizelos', 'petralona', 'thiseio', 'monastiraki', 'omonia', 'victoria', 'attiki', 'agios-nikolaos', 'kato-patisia', 'agios-eleftherios', 'ano-patisia', 'perissos', 'pefkakia', 'nea-ionia', 'irakleio', 'eirini', 'station-21', 'marousi', 'kat', 'kifissia'],
      ],
    },
    {
      id: '2',
      short: 'Μ2',
      name: 'Μετρό Μ2',
      colour: '#da291c',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['elliniko', 'argyroupoli', 'alimos', 'ilioupoli', 'agios-dimitrios', 'dafni', 'agios-ioannis', 'neos-kosmos', 'syngrou-fix', 'akropoli', 'syntagma', 'panepistimio', 'omonia', 'metaxourgeio', 'station-63', 'attiki', 'sepolia', 'agios-antonios', 'peristeri', 'anthoupoli'],
      ],
    },
    {
      id: '3',
      short: 'Μ3',
      name: 'Μετρό Μ3',
      colour: '#10069f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['station-25', 'piraeus', 'station-26', 'station-27', 'korydallos', 'agia-varvara', 'agia-marina', 'egaleo', 'eleonas', 'kerameikos', 'monastiraki', 'syntagma', 'evangelismos', 'megaro-mousikis', 'ambelokipi', 'panormou', 'katechaki', 'ethniki-amyna', 'cholargos', 'nomismatokopio', 'agia-paraskevi', 'chalandri', 'station-45', 'station-46', 'peania-kantza', 'station-48', 'station-49'],
        ['station-49', 'station-48', 'station-50', 'station-46', 'station-45', 'chalandri', 'agia-paraskevi', 'nomismatokopio', 'cholargos', 'ethniki-amyna', 'katechaki', 'panormou', 'ambelokipi', 'megaro-mousikis', 'evangelismos', 'syntagma', 'monastiraki', 'kerameikos', 'eleonas', 'egaleo', 'agia-marina', 'agia-varvara', 'korydallos', 'station-27', 'station-26', 'piraeus', 'station-25'],
      ],
    },
  ],
  times: {
    'piraeus faliro': 4,
    'faliro moschato': 4,
    'moschato kallithea': 3,
    'petralona thiseio': 3,
    'thiseio monastiraki': 1,
    'agios-nikolaos kato-patisia': 1,
    'ano-patisia perissos': 3,
    'nea-ionia irakleio': 3,
    'irakleio eirini': 3,
    'station-21 marousi': 3,
    'elliniko argyroupoli': 3,
    'argyroupoli alimos': 4,
    'alimos ilioupoli': 3,
    'ilioupoli agios-dimitrios': 3,
    'agios-ioannis neos-kosmos': 1,
    'syngrou-fix akropoli': 1,
    'sepolia agios-antonios': 3,
    'piraeus station-26': 3,
    'station-27 korydallos': 3,
    'korydallos agia-varvara': 4,
    'agia-marina egaleo': 3,
    'eleonas kerameikos': 4,
    'kerameikos monastiraki': 3,
    'panormou katechaki': 3,
    'station-45 station-46': 8,
    'station-46 peania-kantza': 5,
    'peania-kantza station-48': 16,
    'station-48 station-49': 10,
    'station-49 station-48': 10,
    'station-48 station-50': 16,
    'station-50 station-46': 5,
    'station-46 station-45': 8,
    'katechaki panormou': 3,
    'monastiraki kerameikos': 3,
    'kerameikos eleonas': 4,
    'egaleo agia-marina': 3,
    'agia-varvara korydallos': 4,
    'korydallos station-27': 3,
    'station-26 piraeus': 3,
  },
  stations: {
    piraeus: { name: 'Piraeus', x: 1, y: 26, aka: ['Πειραιάς'] },
    faliro: { name: 'Faliro', x: 3, y: 26, aka: ['Φάληρο'] },
    moschato: { name: 'Moschato', x: 5, y: 26, aka: ['Μοσχάτο'] },
    kallithea: { name: 'Kallithea', x: 6, y: 25, aka: ['Καλλιθέα'] },
    'tavros-eleftherios-venizelos': { name: 'Tavros-Eleftherios Venizelos', x: 8, y: 25, aka: ['Ταύρος-Ελευθέριος Βενιζέλος'] },
    petralona: { name: 'Petralona', x: 9.5, y: 23.5, aka: ['Πετράλωνα'] },
    thiseio: { name: 'Thiseio', x: 10.5, y: 22, aka: ['Θησείο'] },
    monastiraki: { name: 'Monastiraki', x: 12, y: 21, aka: ['Μοναστηράκι'] },
    omonia: { name: 'Omonia', x: 13.5, y: 19, aka: ['Ομόνοια'] },
    victoria: { name: 'Victoria', x: 13.5, y: 17, aka: ['Βικτώρια'] },
    attiki: { name: 'Attiki', x: 12, y: 15.5, aka: ['Αττική'] },
    'agios-nikolaos': { name: 'Agios Nikolaos', x: 13.5, y: 14, aka: ['Άγιος Νικόλαος'] },
    'kato-patisia': { name: 'Kato Patisia', x: 12, y: 12.5, aka: ['Κάτω Πατήσια'] },
    'agios-eleftherios': { name: 'Agios Eleftherios', x: 12, y: 10.5, aka: ['Άγιος Ελευθέριος'] },
    'ano-patisia': { name: 'Ano Patisia', x: 14, y: 10.5, aka: ['Άνω Πατήσια'] },
    perissos: { name: 'Perissos', x: 14, y: 8.5, aka: ['Περισσός'] },
    pefkakia: { name: 'Pefkakia', x: 15.5, y: 7, aka: ['Πευκάκια'] },
    'nea-ionia': { name: 'Nea Ionia', x: 17, y: 5.5, aka: ['Νέα Ιωνία'] },
    irakleio: { name: 'Irakleio', x: 19, y: 5.5, aka: ['Ηράκλειο'] },
    eirini: { name: 'Eirini', x: 21.5, y: 5.5, aka: ['Ειρήνη'] },
    'station-21': { name: 'Νεραντζιώτισσα', x: 23.5, y: 5.5 },
    marousi: { name: 'Marousi', x: 24.5, y: 4, aka: ['Μαρούσι'] },
    kat: { name: 'KAT', x: 25, y: 2, aka: ['ΚΑΤ'] },
    kifissia: { name: 'Kifissia', x: 25, y: 0, aka: ['Κηφισιά'] },
    'station-25': { name: 'Δημοτικό Θέατρο', x: 1, y: 28 },
    'station-26': { name: 'Μανιάτικα', x: 0, y: 24.5 },
    'station-27': { name: 'Νίκαια', x: 0, y: 22.5 },
    korydallos: { name: 'Korydallos', x: 0.5, y: 20.5, aka: ['Κορυδαλλός'] },
    'agia-varvara': { name: 'Agia Varvara', x: 2, y: 19, aka: ['Αγία Βαρβάρα'] },
    'agia-marina': { name: 'Agia Marina', x: 4, y: 18, aka: ['Αγία Μαρίνα'] },
    egaleo: { name: 'Egaleo', x: 6, y: 18, aka: ['Αιγάλεω'] },
    eleonas: { name: 'Eleonas', x: 8, y: 19, aka: ['Ελαιώνας'] },
    kerameikos: { name: 'Kerameikos', x: 9.5, y: 20.5, aka: ['Κεραμεικός'] },
    syntagma: { name: 'Syntagma', x: 14, y: 21, aka: ['Σύνταγμα'] },
    evangelismos: { name: 'Evangelismos', x: 16.5, y: 21, aka: ['Ευαγγελισμός'] },
    'megaro-mousikis': { name: 'Megaro Mousikis', x: 18, y: 20, aka: ['Μέγαρο Μουσικής'] },
    ambelokipi: { name: 'Ambelokipi', x: 18, y: 18, aka: ['Αμπελόκηποι'] },
    panormou: { name: 'Panormou', x: 19.5, y: 17, aka: ['Πανόρμου'] },
    katechaki: { name: 'Katechaki', x: 22, y: 17.5, aka: ['Κατεχάκη'] },
    'ethniki-amyna': { name: 'Ethniki Amyna', x: 23.5, y: 16, aka: ['Εθνική Άμυνα'] },
    cholargos: { name: 'Cholargos', x: 25, y: 15, aka: ['Χολαργός'] },
    nomismatokopio: { name: 'Nomismatokopio', x: 26.5, y: 14, aka: ['Νομισματοκοπείο'] },
    'agia-paraskevi': { name: 'Agia Paraskevi', x: 29, y: 14, aka: ['Αγία Παρασκευή'] },
    chalandri: { name: 'Chalandri', x: 31, y: 14.5, aka: ['Χαλάνδρι'] },
    'station-45': { name: 'Δουκίσσης Πλακεντίας', x: 32.5, y: 16 },
    'station-46': { name: 'Παλλήνη', x: 34, y: 18 },
    'peania-kantza': { name: 'Peania-Kantza', x: 35.5, y: 20, aka: ['Παιανία-Κάντζα'] },
    'station-48': { name: 'Κορωπί', x: 37, y: 21 },
    'station-49': { name: 'Αεροδρόμιο', x: 38.5, y: 22.5 },
    'station-50': { name: 'Παιανία-Κάντζα', x: 35.5, y: 19 },
    elliniko: { name: 'Elliniko', x: 14, y: 37.5, aka: ['Ελληνικό'] },
    argyroupoli: { name: 'Argyroupoli', x: 14, y: 35.5, aka: ['Αργυρούπολη'] },
    alimos: { name: 'Alimos', x: 14, y: 33.5, aka: ['Άλιμος'] },
    ilioupoli: { name: 'Ilioupoli', x: 14, y: 31.5, aka: ['Ηλιούπολη'] },
    'agios-dimitrios': { name: 'Agios Dimitrios', x: 14, y: 29.5, aka: ['Άγιος Δημήτριος'] },
    dafni: { name: 'Dafni', x: 13.5, y: 27.5, aka: ['Δάφνη'] },
    'agios-ioannis': { name: 'Agios Ioannis', x: 13.5, y: 25.5, aka: ['Άγιος Ιωάννης'] },
    'neos-kosmos': { name: 'Neos Kosmos', x: 11.5, y: 25.5, aka: ['Νέος Κόσμος'] },
    'syngrou-fix': { name: 'Syngrou-Fix', x: 11.5, y: 23.5, aka: ['Συγγρού-Φιξ'] },
    akropoli: { name: 'Akropoli', x: 13, y: 22.5, aka: ['Ακρόπολη'] },
    panepistimio: { name: 'Panepistimio', x: 15.5, y: 19.5, aka: ['Πανεπιστήμιο'] },
    metaxourgeio: { name: 'Metaxourgeio', x: 11.5, y: 19, aka: ['Μεταξουργείο'] },
    'station-63': { name: 'Σταθμός Λαρίσης', x: 11.5, y: 17.5 },
    sepolia: { name: 'Sepolia', x: 10, y: 15.5, aka: ['Σεπόλια'] },
    'agios-antonios': { name: 'Agios Antonios', x: 8, y: 15.5, aka: ['Άγιος Αντώνιος'] },
    peristeri: { name: 'Peristeri', x: 8, y: 13.5, aka: ['Περιστέρι'] },
    anthoupoli: { name: 'Anthoupoli', x: 6.5, y: 12, aka: ['Ανθούπολη'] },
  },
};
