// Barcelona's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'barcelona',
  name: 'Barcelona',
  system: 'Metro',
  country: 'Spain',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'l1',
      short: 'L1',
      name: 'L1',
      colour: '#c8102e',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hospital-de-bellvitge', 'bellvitge-rambla-marina', 'avinguda-carrilet', 'rambla-just-oliveras', 'can-serra', 'florida', 'torrassa', 'santa-eulalia', 'mercat-nou', 'placa-de-sants', 'hostafrancs', 'espanya', 'rocafort', 'urgell', 'universitat', 'catalunya', 'urquinaona', 'arc-de-triomf', 'marina', 'glories', 'el-clot', 'navas', 'la-sagrera', 'fabra-i-puig', 'sant-andreu', 'torras-i-bages', 'trinitat-vella', 'baro-de-viver', 'santa-coloma', 'fondo'],
      ],
    },
    {
      id: 'l2',
      short: 'L2',
      name: 'L2',
      colour: '#93328e',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['paral-lel', 'sant-antoni', 'universitat', 'passeig-de-gracia', 'tetuan', 'monumental', 'sagrada-familia', 'encants', 'el-clot', 'bac-de-roda', 'sant-marti', 'la-pau', 'verneda', 'artigues-sant-adria', 'sant-roc', 'gorg', 'pep-ventura', 'badalona-pompeu-fabra'],
      ],
    },
    {
      id: 'l3',
      short: 'L3',
      name: 'L3',
      colour: '#43b02a',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['trinitat-nova', 'roquetes', 'canyelles', 'valldaura', 'mundet', 'montbau', 'vall-d-hebron-sant-genis', 'penitents', 'vallcarca', 'lesseps', 'fontana', 'diagonal', 'passeig-de-gracia', 'catalunya', 'liceu', 'la-rambla-drassanes', 'paral-lel', 'el-poble-sec', 'espanya', 'tarragona', 'sants-estacio', 'placa-del-centre', 'les-corts', 'maria-cristina', 'palau-reial', 'zona-universitaria'],
      ],
    },
    {
      id: 'l4',
      short: 'L4',
      name: 'L4',
      colour: '#f2a900',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['la-pau', 'besos', 'besos-mar', 'el-maresme-forum', 'selva-de-mar', 'poblenou', 'llacuna', 'bogatell', 'ciutadella-vila-olimpica', 'barceloneta', 'jaume-i', 'urquinaona', 'passeig-de-gracia', 'girona', 'verdaguer', 'joanic', 'alfons-x', 'guinardo-hospital-de-sant-pau', 'maragall', 'llucmajor-republica', 'via-julia', 'trinitat-nova'],
      ],
    },
    {
      id: 'l5',
      short: 'L5',
      name: 'L5',
      colour: '#0072ce',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['cornella-centre', 'gavarra', 'sant-ildefons', 'can-boixeres', 'can-vidalet', 'pubilla-cases', 'ernest-lluch', 'collblanc', 'badal', 'placa-de-sants', 'sants-estacio', 'entenca', 'hospital-clinic', 'diagonal', 'verdaguer', 'sagrada-familia', 'sant-pau-dos-de-maig', 'camp-de-l-arpa', 'la-sagrera', 'congres-indians', 'maragall', 'virrei-amat', 'vilapicina', 'horta', 'el-carmel', 'el-coll-la-teixonera', 'vall-d-hebron-sant-genis'],
      ],
    },
    {
      id: 'l6',
      short: 'L6',
      name: 'L6',
      colour: '#797fbc',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['catalunya', 'provenca', 'gracia', 'sant-gervasi', 'muntaner', 'la-bonanova', 'les-tres-torres', 'sarria'],
      ],
    },
    {
      id: 'l7',
      short: 'L7',
      name: 'L7',
      colour: '#b2600b',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['catalunya', 'provenca', 'gracia', 'placa-molina', 'padua', 'el-putxet', 'avinguda-tibidabo'],
      ],
    },
    {
      id: 'l8',
      short: 'L8',
      name: 'L8',
      colour: '#e274aa',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['barcelona-placa-espanya', 'magoria-la-campana', 'ildefons-cerda', 'europa-fira', 'gornal', 'sant-josep', 'avinguda-carrilet', 'almeda', 'cornella-riera', 'sant-boi', 'moli-nou-ciutat-cooperativa'],
      ],
    },
    {
      id: 'l9n',
      short: 'L9N',
      name: 'L9 Nord',
      colour: '#fe5000',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['la-sagrera', 'onze-de-setembre', 'bon-pastor', 'can-peixauet', 'santa-rosa', 'fondo', 'esglesia-major', 'singuerlin', 'can-zam'],
      ],
    },
    {
      id: 'l9s',
      short: 'L9S',
      name: 'L9S',
      colour: '#fe5000',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['aeroport-t1', 'aeroport-t2', 'mas-blau', 'parc-nou', 'centric', 'el-prat-estacio', 'les-moreres', 'mercabarna', 'parc-logistic', 'fira', 'europa-fira', 'can-tries-gornal', 'torrassa', 'collblanc', 'zona-universitaria'],
      ],
    },
    {
      id: 'l10n',
      short: 'L10N',
      name: 'L10 Nord',
      colour: '#00adef',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['la-sagrera', 'onze-de-setembre', 'bon-pastor', 'llefia', 'la-salut', 'gorg'],
      ],
    },
    {
      id: 'l10s',
      short: 'L10S',
      name: 'L10S',
      colour: '#009fe3',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['collblanc', 'torrassa', 'can-tries-gornal', 'provencana', 'ciutat-de-la-justicia', 'foneria', 'foc', 'zona-franca', 'port-comercial-la-factoria', 'ecoparc', 'zal-riu-vell'],
      ],
    },
    {
      id: 'l11',
      short: 'L11',
      name: 'L11',
      colour: '#97d700',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['trinitat-nova', 'casa-de-l-aigua', 'torre-baro-vallbona', 'ciutat-meridiana', 'can-cuias'],
      ],
    },
    {
      id: 'l12',
      short: 'L12',
      name: 'L12',
      colour: '#b2aed3',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['reina-elisenda', 'sarria'],
      ],
    },
  ],
  times: {
    'rambla-just-oliveras can-serra': 1,
    'florida torrassa': 1,
    'mercat-nou placa-de-sants': 1,
    'placa-de-sants hostafrancs': 1,
    'espanya rocafort': 1,
    'rocafort urgell': 1,
    'urgell universitat': 1,
    'universitat catalunya': 1,
    'catalunya urquinaona': 1,
    'arc-de-triomf marina': 1,
    'navas la-sagrera': 1,
    'trinitat-vella baro-de-viver': 1,
    'encants el-clot': 1,
    'gorg pep-ventura': 1,
    'lesseps fontana': 1,
    'passeig-de-gracia catalunya': 1,
    'liceu la-rambla-drassanes': 1,
    'la-rambla-drassanes paral-lel': 1,
    'espanya tarragona': 1,
    'tarragona sants-estacio': 1,
    'sants-estacio placa-del-centre': 1,
    'placa-del-centre les-corts': 1,
    'les-corts maria-cristina': 1,
    'palau-reial zona-universitaria': 1,
    'la-pau besos': 1,
    'besos-mar el-maresme-forum': 1,
    'maragall llucmajor-republica': 3,
    'pubilla-cases ernest-lluch': 1,
    'ernest-lluch collblanc': 1,
    'sants-estacio entenca': 1,
    'la-sagrera congres-indians': 1,
    'congres-indians maragall': 1,
    'virrei-amat vilapicina': 1,
    'el-carmel el-coll-la-teixonera': 1,
    'catalunya provenca': 3,
    'provenca gracia': 2,
    'magoria-la-campana ildefons-cerda': 2,
    'ildefons-cerda europa-fira': 1,
    'europa-fira gornal': 2,
    'gornal sant-josep': 2,
    'sant-josep avinguda-carrilet': 2,
    'cornella-riera sant-boi': 5,
    'onze-de-setembre bon-pastor': 3,
    'can-peixauet santa-rosa': 1,
    'aeroport-t1 aeroport-t2': 4,
    'mas-blau parc-nou': 3,
    'centric el-prat-estacio': 3,
    'el-prat-estacio les-moreres': 3,
    'mercabarna parc-logistic': 4,
    'parc-logistic fira': 3,
    'bon-pastor llefia': 3,
    'can-tries-gornal provencana': 1,
    'ciutat-de-la-justicia foneria': 1,
    'foc zona-franca': 3,
    'casa-de-l-aigua torre-baro-vallbona': 2,
  },
  walks: [
    ['provenca', 'diagonal', 3],
  ],
  stations: {
    'trinitat-nova': { name: 'Trinitat Nova', x: 28, y: 5 },
    roquetes: { name: 'Roquetes', x: 26, y: 4.5 },
    canyelles: { name: 'Canyelles', x: 24.5, y: 6 },
    valldaura: { name: 'Valldaura', x: 23, y: 7.5 },
    mundet: { name: 'Mundet', x: 21.5, y: 8.5 },
    montbau: { name: 'Montbau', x: 20, y: 10 },
    'vall-d-hebron-sant-genis': { name: 'Vall d’Hebron | Sant Genís', x: 20, y: 11.5 },
    penitents: { name: 'Penitents', x: 20, y: 14 },
    vallcarca: { name: 'Vallcarca', x: 19.5, y: 16 },
    lesseps: { name: 'Lesseps', x: 21, y: 17.5 },
    fontana: { name: 'Fontana', x: 22.5, y: 18.5 },
    diagonal: { name: 'Diagonal', x: 23.5, y: 20 },
    'passeig-de-gracia': { name: 'Passeig de Gràcia', x: 25.5, y: 21.5 },
    catalunya: { name: 'Catalunya', x: 25.5, y: 23.5, aka: ['Barcelona-Plaça Catalunya'] },
    liceu: { name: 'Liceu', x: 26.5, y: 25 },
    'la-rambla-drassanes': { name: 'La Rambla | Drassanes', x: 27.5, y: 27 },
    'paral-lel': { name: 'Paral·lel', x: 25.5, y: 27 },
    'el-poble-sec': { name: 'El Poble-sec', x: 23.5, y: 27.5 },
    espanya: { name: 'Espanya', x: 21.5, y: 27.5 },
    tarragona: { name: 'Tarragona', x: 20, y: 26 },
    'sants-estacio': { name: 'Sants Estació', x: 19, y: 25 },
    'placa-del-centre': { name: 'Plaça del Centre', x: 16.5, y: 25.5 },
    'les-corts': { name: 'les Corts', x: 15, y: 24.5 },
    'maria-cristina': { name: 'Maria Cristina', x: 15, y: 22.5 },
    'palau-reial': { name: 'Palau Reial', x: 13.5, y: 24 },
    'zona-universitaria': { name: 'Zona Universitària', x: 12, y: 25.5 },
    'la-pau': { name: 'La Pau', x: 34.5, y: 12 },
    besos: { name: 'Besòs', x: 36, y: 13 },
    'besos-mar': { name: 'Besòs Mar', x: 37.5, y: 14.5 },
    'el-maresme-forum': { name: 'El Maresme | Fòrum', x: 37.5, y: 16.5 },
    'selva-de-mar': { name: 'Selva de Mar', x: 35.5, y: 16.5 },
    poblenou: { name: 'Poblenou', x: 34, y: 18 },
    llacuna: { name: 'Llacuna', x: 33, y: 19.5 },
    bogatell: { name: 'Bogatell', x: 31.5, y: 21 },
    'ciutadella-vila-olimpica': { name: 'Ciutadella | Vila Olímpica', x: 31.5, y: 22.5 },
    barceloneta: { name: 'Barceloneta', x: 30, y: 24 },
    'jaume-i': { name: 'Jaume I', x: 28.5, y: 24 },
    urquinaona: { name: 'Urquinaona', x: 27, y: 22.5 },
    girona: { name: 'Girona', x: 26.5, y: 20 },
    verdaguer: { name: 'Verdaguer', x: 25, y: 18.5 },
    joanic: { name: 'Joanic', x: 24.5, y: 16.5 },
    'alfons-x': { name: 'Alfons X', x: 26, y: 14.5 },
    'guinardo-hospital-de-sant-pau': { name: 'Guinardó | Hospital de Sant Pau', x: 27, y: 13 },
    maragall: { name: 'Maragall', x: 27, y: 11 },
    'llucmajor-republica': { name: 'Llucmajor | República', x: 27, y: 8.5 },
    'via-julia': { name: 'Via Júlia', x: 27, y: 6.5 },
    'sant-antoni': { name: 'Sant Antoni', x: 24, y: 25.5 },
    universitat: { name: 'Universitat', x: 23.5, y: 23.5 },
    tetuan: { name: 'Tetuan', x: 27, y: 21 },
    monumental: { name: 'Monumental', x: 28.5, y: 19.5 },
    'sagrada-familia': { name: 'Sagrada Família', x: 27, y: 17.5 },
    encants: { name: 'Encants', x: 29, y: 17.5 },
    'el-clot': { name: 'El Clot', x: 30.5, y: 16 },
    'bac-de-roda': { name: 'Bac de Roda', x: 32, y: 14.5 },
    'sant-marti': { name: 'Sant Martí', x: 33, y: 13.5 },
    verneda: { name: 'Verneda', x: 36, y: 10.5 },
    'artigues-sant-adria': { name: 'Artigues | Sant Adrià', x: 37, y: 9 },
    'sant-roc': { name: 'Sant Roc', x: 39, y: 9 },
    gorg: { name: 'Gorg', x: 40.5, y: 7.5 },
    'pep-ventura': { name: 'Pep Ventura', x: 41.5, y: 6 },
    'badalona-pompeu-fabra': { name: 'Badalona Pompeu Fabra', x: 43, y: 5 },
    'hospital-de-bellvitge': { name: 'Hospital de Bellvitge', x: 10, y: 37 },
    'bellvitge-rambla-marina': { name: 'Bellvitge Rambla Marina', x: 10, y: 35 },
    'avinguda-carrilet': { name: 'Avinguda Carrilet', x: 8.5, y: 33.5 },
    'rambla-just-oliveras': { name: 'Rambla Just Oliveras', x: 8.5, y: 31.5 },
    'can-serra': { name: 'Can Serra', x: 9.5, y: 30 },
    florida: { name: 'Florida', x: 11.5, y: 30 },
    torrassa: { name: 'Torrassa', x: 13.5, y: 29.5 },
    'santa-eulalia': { name: 'Santa Eulàlia', x: 15.5, y: 30 },
    'mercat-nou': { name: 'Mercat Nou', x: 17, y: 28.5 },
    'placa-de-sants': { name: 'Plaça de Sants', x: 17.5, y: 27 },
    hostafrancs: { name: 'Hostafrancs', x: 19, y: 27.5 },
    rocafort: { name: 'Rocafort', x: 22.5, y: 26 },
    urgell: { name: 'Urgell', x: 22.5, y: 24.5 },
    'arc-de-triomf': { name: 'Arc de Triomf', x: 28.5, y: 21.5 },
    marina: { name: 'Marina', x: 30, y: 20 },
    glories: { name: 'Glòries', x: 30.5, y: 18 },
    navas: { name: 'Navas', x: 30.5, y: 14 },
    'la-sagrera': { name: 'La Sagrera', x: 30.5, y: 12 },
    'fabra-i-puig': { name: 'Fabra i Puig', x: 30, y: 10 },
    'sant-andreu': { name: 'Sant Andreu', x: 31.5, y: 8.5 },
    'torras-i-bages': { name: 'Torras i Bages', x: 31.5, y: 6.5 },
    'trinitat-vella': { name: 'Trinitat Vella', x: 31, y: 4.5 },
    'baro-de-viver': { name: 'Baró de Viver', x: 33, y: 4.5 },
    'santa-coloma': { name: 'Santa Coloma', x: 35, y: 4.5 },
    fondo: { name: 'Fondo', x: 37, y: 4 },
    'barcelona-placa-espanya': { name: 'Barcelona-Plaça Espanya', x: 19.5, y: 29.5 },
    'magoria-la-campana': { name: 'Magòria-La Campana', x: 18.5, y: 30.5 },
    'ildefons-cerda': { name: 'Ildefons Cerdà', x: 16.5, y: 32.5 },
    'europa-fira': { name: 'Europa | Fira', x: 15, y: 33.5 },
    gornal: { name: 'Gornal', x: 12.5, y: 33.5 },
    'sant-josep': { name: 'Sant Josep', x: 10.5, y: 33.5 },
    almeda: { name: 'Almeda', x: 6, y: 34 },
    'cornella-riera': { name: 'Cornellà-Riera', x: 4, y: 34 },
    'sant-boi': { name: 'Sant Boi', x: 2, y: 34 },
    'moli-nou-ciutat-cooperativa': { name: 'Molí Nou | Ciutat Cooperativa', x: 0, y: 34 },
    'cornella-centre': { name: 'Cornellà Centre', x: 2, y: 32.5 },
    gavarra: { name: 'Gavarra', x: 4, y: 32.5 },
    'sant-ildefons': { name: 'Sant Ildefons', x: 5.5, y: 31 },
    'can-boixeres': { name: 'Can Boixeres', x: 6.5, y: 29.5 },
    'can-vidalet': { name: 'Can Vidalet', x: 8, y: 28.5 },
    'pubilla-cases': { name: 'Pubilla Cases', x: 10, y: 28.5 },
    'ernest-lluch': { name: 'Ernest Lluch', x: 11.5, y: 27 },
    collblanc: { name: 'Collblanc', x: 13.5, y: 27.5 },
    badal: { name: 'Badal', x: 15.5, y: 27 },
    entenca: { name: 'Entença', x: 20.5, y: 23.5 },
    'hospital-clinic': { name: 'Hospital Clínic', x: 22, y: 22 },
    'sant-pau-dos-de-maig': { name: 'Sant Pau | Dos de Maig', x: 27, y: 15.5 },
    'camp-de-l-arpa': { name: 'Camp de l\'Arpa', x: 28.5, y: 14 },
    'congres-indians': { name: 'Congrés | Indians', x: 28.5, y: 12 },
    'virrei-amat': { name: 'Virrei Amat', x: 28, y: 9.5 },
    vilapicina: { name: 'Vilapicina', x: 26, y: 10 },
    horta: { name: 'Horta', x: 24, y: 10 },
    'el-carmel': { name: 'el Carmel', x: 22.5, y: 11.5 },
    'el-coll-la-teixonera': { name: 'El Coll | La Teixonera', x: 21.5, y: 13 },
    provenca: { name: 'Provença', x: 23.5, y: 22 },
    gracia: { name: 'Gràcia', x: 22, y: 20.5 },
    'sant-gervasi': { name: 'Sant Gervasi', x: 20.5, y: 19 },
    muntaner: { name: 'Muntaner', x: 19, y: 20.5 },
    'la-bonanova': { name: 'La Bonanova', x: 17, y: 20 },
    'les-tres-torres': { name: 'Les Tres Torres', x: 16, y: 21.5 },
    sarria: { name: 'Sarrià', x: 14.5, y: 20 },
    'placa-molina': { name: 'Plaça Molina', x: 20.5, y: 20.5 },
    padua: { name: 'Pàdua', x: 19, y: 19 },
    'el-putxet': { name: 'El Putxet', x: 17.5, y: 17.5 },
    'avinguda-tibidabo': { name: 'Avinguda Tibidabo', x: 17.5, y: 15.5 },
    'casa-de-l-aigua': { name: 'Casa de l\'Aigua', x: 29.5, y: 3.5 },
    'torre-baro-vallbona': { name: 'Torre Baró | Vallbona', x: 28, y: 2 },
    'ciutat-meridiana': { name: 'Ciutat Meridiana', x: 26.5, y: 2 },
    'can-cuias': { name: 'Can Cuiàs', x: 26.5, y: 0 },
    'onze-de-setembre': { name: 'Onze de Setembre', x: 32, y: 10.5 },
    'bon-pastor': { name: 'Bon Pastor', x: 34, y: 9 },
    llefia: { name: 'Llefià', x: 36, y: 7.5 },
    'la-salut': { name: 'la Salut', x: 38, y: 7.5 },
    'can-peixauet': { name: 'Can Peixauet', x: 35, y: 7.5 },
    'santa-rosa': { name: 'Santa Rosa', x: 36.5, y: 6 },
    'esglesia-major': { name: 'Església Major', x: 35.5, y: 2.5 },
    singuerlin: { name: 'Singuerlín', x: 34, y: 1.5 },
    'can-zam': { name: 'Can Zam', x: 32, y: 1.5 },
    'aeroport-t1': { name: 'Aeroport T1', x: 4.5, y: 50.5 },
    'aeroport-t2': { name: 'Aeroport T2', x: 4.5, y: 48.5 },
    'mas-blau': { name: 'Mas Blau', x: 4.5, y: 46.5 },
    'parc-nou': { name: 'Parc Nou', x: 6, y: 45 },
    centric: { name: 'Cèntric', x: 7.5, y: 43.5 },
    'el-prat-estacio': { name: 'El Prat Estació', x: 9, y: 42 },
    'les-moreres': { name: 'Les Moreres', x: 10.5, y: 40.5 },
    mercabarna: { name: 'Mercabarna', x: 12, y: 39 },
    'parc-logistic': { name: 'Parc Logístic', x: 13.5, y: 37.5 },
    fira: { name: 'Fira', x: 15, y: 36 },
    'can-tries-gornal': { name: 'Can Tries - Gornal', x: 13.5, y: 32 },
    'reina-elisenda': { name: 'Reina Elisenda', x: 12.5, y: 20 },
    provencana: { name: 'Provençana', x: 15, y: 32 },
    'ciutat-de-la-justicia': { name: 'Ciutat de la Justícia', x: 17, y: 30.5 },
    foneria: { name: 'Foneria', x: 18.5, y: 32.5 },
    foc: { name: 'Foc', x: 18.5, y: 34.5 },
    'zona-franca': { name: 'Zona Franca', x: 18.5, y: 36.5 },
    'port-comercial-la-factoria': { name: 'Port Comercial | La Factoria', x: 18.5, y: 38.5 },
    ecoparc: { name: 'Ecoparc', x: 18.5, y: 40.5 },
    'zal-riu-vell': { name: 'ZAL | Riu Vell', x: 17, y: 42 },
  },
};
