// Berlin's U-Bahn and S-Bahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-15.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'berlin',
  name: 'Berlin',
  system: 'U-Bahn and S-Bahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 's1',
      short: 'S1',
      name: 'S1',
      colour: '#d474ae',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['oranienburg', 'lehnitz', 'borgsdorf', 'birkenwerder', 'hohen-neuendorf-b-berlin', 'frohnau', 'hermsdorf', 'waidmannslust', 'wittenau', 'wilhelmsruh', 'schonholz', 'wollankstrasse', 'bornholmer-strasse', 'gesundbrunnen', 'humboldthain', 'nordbahnhof', 'oranienburger-strasse', 'friedrichstrasse', 'brandenburger-tor', 'potsdamer-platz', 'anhalter-bahnhof', 'yorckstrasse-grossgorschenstrasse', 'julius-leber-brucke', 'schoneberg', 'friedenau', 'feuerbachstrasse', 'rathaus-steglitz', 'botanischer-garten', 'lichterfelde-west', 'sundgauer-strasse', 'zehlendorf', 'mexikoplatz', 'schlachtensee', 'nikolassee', 'wannsee'],
        ['wannsee', 'nikolassee', 'schlachtensee', 'mexikoplatz', 'zehlendorf', 'sundgauer-strasse', 'lichterfelde-west', 'botanischer-garten', 'rathaus-steglitz', 'feuerbachstrasse', 'friedenau', 'schoneberg', 'julius-leber-brucke', 'yorckstrasse-grossgorschenstrasse', 'anhalter-bahnhof', 'potsdamer-platz', 'brandenburger-tor', 'friedrichstrasse', 'oranienburger-strasse', 'nordbahnhof', 'humboldthain', 'gesundbrunnen', 'bornholmer-strasse', 'schonholz', 'wilhelmsruh', 'wittenau', 'waidmannslust', 'hermsdorf', 'frohnau', 'hohen-neuendorf-b-berlin', 'birkenwerder', 'borgsdorf', 'lehnitz', 'oranienburg'],
      ],
    },
    {
      id: 's2',
      short: 'S2',
      name: 'S2',
      colour: '#018a47',
      text: '#ffffff',
      minutes: 4,
      branches: [
        ['bernau', 'bernau-friedenstal', 'zepernick-bei-bernau', 'rontgental', 'buch', 'karow', 'blankenburg', 'pankow-heinersdorf', 'pankow', 'bornholmer-strasse', 'gesundbrunnen', 'humboldthain', 'nordbahnhof', 'oranienburger-strasse', 'friedrichstrasse', 'brandenburger-tor', 'potsdamer-platz', 'anhalter-bahnhof', 'yorckstrasse', 'sudkreuz', 'priesterweg', 'attilastrasse', 'marienfelde', 'buckower-chaussee', 'schichauweg', 'lichtenrade', 'mahlow', 'blankenfelde-teltow-flaming'],
      ],
    },
    {
      id: 's3',
      short: 'S3',
      name: 'S3',
      colour: '#055a99',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['erkner', 'wilhelmshagen', 'rahnsdorf', 'friedrichshagen', 'hirschgarten', 'kopenick', 'wuhlheide', 'karlshorst', 'betriebsbahnhof-rummelsburg', 'rummelsburg', 'ostkreuz', 'warschauer-strasse', 'ostbahnhof', 'jannowitzbrucke', 'alexanderplatz', 'hackescher-markt', 'friedrichstrasse', 'hauptbahnhof', 'bellevue', 'tiergarten', 'zoologischer-garten', 'savignyplatz', 'charlottenburg', 'westkreuz', 'messe-sud-eichkamp', 'heerstrasse', 'olympiastadion', 'pichelsberg', 'stresow', 'spandau'],
      ],
    },
    {
      id: 's5',
      short: 'S5',
      name: 'S5',
      colour: '#f25721',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['strausberg-nord', 'strausberg-stadt', 'hegermuhle', 'strausberg', 'petershagen-nord', 'fredersdorf-bei-berlin', 'neuenhagen', 'hoppegarten-mark', 'birkenstein', 'mahlsdorf', 'kaulsdorf', 'wuhletal', 'biesdorf', 'friedrichsfelde-ost', 'lichtenberg', 'noldnerplatz', 'ostkreuz', 'warschauer-strasse', 'ostbahnhof', 'jannowitzbrucke', 'alexanderplatz', 'hackescher-markt', 'friedrichstrasse', 'hauptbahnhof', 'bellevue', 'tiergarten', 'zoologischer-garten', 'savignyplatz', 'charlottenburg', 'westkreuz'],
      ],
    },
    {
      id: 's7',
      short: 'S7',
      name: 'S7',
      colour: '#8070b7',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['ahrensfelde', 'mehrower-allee', 'raoul-wallenberg-strasse', 'marzahn', 'poelchaustrasse', 'springpfuhl', 'friedrichsfelde-ost', 'lichtenberg', 'noldnerplatz', 'ostkreuz', 'warschauer-strasse', 'ostbahnhof', 'jannowitzbrucke', 'alexanderplatz', 'hackescher-markt', 'friedrichstrasse', 'hauptbahnhof', 'bellevue', 'tiergarten', 'zoologischer-garten', 'savignyplatz', 'charlottenburg', 'westkreuz', 'grunewald', 'nikolassee', 'wannsee', 'griebnitzsee', 'babelsberg', 'potsdam-hauptbahnhof'],
      ],
    },
    {
      id: 's8',
      short: 'S8',
      name: 'S8',
      colour: '#52b447',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['birkenwerder', 'hohen-neuendorf-b-berlin', 'bergfelde', 'schonfliess', 'muhlenbeck-monchmuhle', 'blankenburg', 'pankow-heinersdorf', 'pankow', 'bornholmer-strasse', 'schonhauser-allee', 'prenzlauer-allee', 'greifswalder-strasse', 'landsberger-allee', 'storkower-strasse', 'frankfurter-allee', 'ostkreuz', 'treptower-park', 'planterwald', 'baumschulenweg', 'schoneweide', 'johannisthal', 'adlershof', 'grunau', 'eichwalde', 'zeuthen', 'wildau'],
      ],
    },
    {
      id: 's9',
      short: 'S9',
      name: 'S9',
      colour: '#9a3052',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['flughafen-ber', 'wassmannsdorf', 'schonefeld', 'grunbergallee', 'altglienicke', 'adlershof', 'johannisthal', 'schoneweide', 'baumschulenweg', 'planterwald', 'treptower-park', 'warschauer-strasse', 'ostbahnhof', 'jannowitzbrucke', 'alexanderplatz', 'hackescher-markt', 'friedrichstrasse', 'hauptbahnhof', 'bellevue', 'tiergarten', 'zoologischer-garten', 'savignyplatz', 'charlottenburg', 'westkreuz', 'messe-sud-eichkamp', 'heerstrasse', 'olympiastadion', 'pichelsberg', 'stresow', 'spandau'],
      ],
    },
    {
      id: 's15',
      short: 'S15',
      name: 'S15',
      colour: '#d474ae',
      text: '#ffffff',
      minutes: 4,
      branches: [
        ['wedding', 'gesundbrunnen'],
      ],
    },
    {
      id: 's25',
      short: 'S25',
      name: 'S25',
      colour: '#018a47',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hennigsdorf-bei-berlin', 'heiligensee', 'schulzendorf', 'tegel', 'eichborndamm', 'karl-bonhoeffer-nervenklinik', 'alt-reinickendorf', 'schonholz', 'wollankstrasse', 'bornholmer-strasse', 'gesundbrunnen', 'humboldthain', 'nordbahnhof', 'oranienburger-strasse', 'friedrichstrasse', 'brandenburger-tor', 'potsdamer-platz', 'anhalter-bahnhof', 'yorckstrasse', 'sudkreuz', 'priesterweg', 'sudende', 'lankwitz', 'lichterfelde-ost', 'osdorfer-strasse', 'lichterfelde-sud', 'teltow-stadt'],
        ['teltow-stadt', 'lichterfelde-sud', 'osdorfer-strasse', 'lichterfelde-ost', 'lankwitz', 'sudende', 'priesterweg', 'sudkreuz', 'yorckstrasse', 'anhalter-bahnhof', 'potsdamer-platz', 'brandenburger-tor', 'friedrichstrasse', 'oranienburger-strasse', 'nordbahnhof', 'humboldthain', 'gesundbrunnen', 'bornholmer-strasse', 'schonholz', 'alt-reinickendorf', 'karl-bonhoeffer-nervenklinik', 'eichborndamm', 'tegel', 'schulzendorf', 'heiligensee', 'hennigsdorf-bei-berlin'],
      ],
    },
    {
      id: 's26',
      short: 'S26',
      name: 'S26',
      colour: '#018a47',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['teltow-stadt', 'lichterfelde-sud', 'osdorfer-strasse', 'lichterfelde-ost', 'lankwitz', 'sudende', 'priesterweg', 'sudkreuz', 'yorckstrasse', 'anhalter-bahnhof', 'potsdamer-platz', 'brandenburger-tor', 'friedrichstrasse', 'oranienburger-strasse', 'nordbahnhof', 'humboldthain', 'gesundbrunnen', 'bornholmer-strasse', 'pankow', 'pankow-heinersdorf', 'blankenburg'],
      ],
    },
    {
      id: 's41',
      short: 'S41',
      name: 'S41',
      colour: '#9f4c37',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['gesundbrunnen', 'schonhauser-allee', 'prenzlauer-allee', 'greifswalder-strasse', 'landsberger-allee', 'storkower-strasse', 'frankfurter-allee', 'ostkreuz', 'treptower-park', 'sonnenallee', 'neukolln', 'hermannstrasse', 'tempelhof', 'sudkreuz', 'schoneberg', 'innsbrucker-platz', 'bundesplatz', 'heidelberger-platz', 'hohenzollerndamm', 'halensee', 'westkreuz', 'messe-nord-zob', 'westend', 'jungfernheide', 'beusselstrasse', 'westhafen', 'wedding', 'gesundbrunnen'],
      ],
    },
    {
      id: 's42',
      short: 'S42',
      name: 'S42',
      colour: '#c36939',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['gesundbrunnen', 'wedding', 'westhafen', 'beusselstrasse', 'jungfernheide', 'westend', 'messe-nord-zob', 'westkreuz', 'halensee', 'hohenzollerndamm', 'heidelberger-platz', 'bundesplatz', 'innsbrucker-platz', 'schoneberg', 'sudkreuz', 'tempelhof', 'hermannstrasse', 'neukolln', 'sonnenallee', 'treptower-park', 'ostkreuz', 'frankfurter-allee', 'storkower-strasse', 'landsberger-allee', 'greifswalder-strasse', 'prenzlauer-allee', 'schonhauser-allee', 'gesundbrunnen'],
      ],
    },
    {
      id: 's46',
      short: 'S46',
      name: 'S46',
      colour: '#ba8a4d',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['konigs-wusterhausen', 'wildau', 'zeuthen', 'eichwalde', 'grunau', 'adlershof', 'johannisthal', 'schoneweide', 'baumschulenweg', 'kollnische-heide', 'neukolln', 'hermannstrasse', 'tempelhof', 'sudkreuz', 'schoneberg', 'innsbrucker-platz', 'bundesplatz', 'heidelberger-platz', 'hohenzollerndamm', 'halensee', 'westkreuz', 'messe-nord-zob', 'westend'],
      ],
    },
    {
      id: 's47',
      short: 'S47',
      name: 'S47',
      colour: '#ba8a4d',
      text: '#ffffff',
      minutes: 4,
      branches: [
        ['sudkreuz', 'tempelhof', 'hermannstrasse', 'neukolln', 'kollnische-heide', 'baumschulenweg', 'schoneweide', 'oberspree', 'spindlersfeld'],
      ],
    },
    {
      id: 's75',
      short: 'S75',
      name: 'S75',
      colour: '#8070b7',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['ostbahnhof', 'warschauer-strasse', 'ostkreuz', 'noldnerplatz', 'lichtenberg', 'friedrichsfelde-ost', 'springpfuhl', 'gehrenseestrasse', 'hohenschonhausen', 'wartenberg'],
      ],
    },
    {
      id: 's85',
      short: 'S85',
      name: 'S85',
      colour: '#52b447',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['frohnau', 'hermsdorf', 'waidmannslust', 'wittenau', 'wilhelmsruh', 'schonholz', 'wollankstrasse', 'bornholmer-strasse', 'schonhauser-allee', 'prenzlauer-allee', 'greifswalder-strasse', 'landsberger-allee', 'storkower-strasse', 'frankfurter-allee', 'ostkreuz', 'treptower-park', 'planterwald', 'baumschulenweg', 'schoneweide', 'johannisthal', 'adlershof', 'altglienicke', 'grunbergallee', 'schonefeld', 'wassmannsdorf', 'flughafen-ber'],
        ['flughafen-ber', 'wassmannsdorf', 'schonefeld', 'grunbergallee', 'altglienicke', 'adlershof', 'johannisthal', 'schoneweide', 'baumschulenweg', 'planterwald', 'treptower-park', 'ostkreuz', 'frankfurter-allee', 'storkower-strasse', 'landsberger-allee', 'greifswalder-strasse', 'prenzlauer-allee', 'schonhauser-allee', 'bornholmer-strasse', 'schonholz', 'wilhelmsruh', 'wittenau', 'waidmannslust', 'hermsdorf', 'frohnau'],
        ['flughafen-ber', 'wassmannsdorf', 'schonefeld', 'grunbergallee', 'altglienicke', 'adlershof', 'johannisthal', 'schoneweide', 'baumschulenweg', 'planterwald', 'treptower-park', 'ostkreuz', 'frankfurter-allee', 'storkower-strasse', 'landsberger-allee', 'greifswalder-strasse', 'prenzlauer-allee', 'schonhauser-allee', 'bornholmer-strasse', 'pankow'],
      ],
    },
    {
      id: 'u1',
      short: 'U1',
      name: 'U1',
      colour: '#7dad4c',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['uhlandstrasse', 'kurfurstendamm', 'wittenbergplatz', 'nollendorfplatz', 'kurfurstenstrasse', 'gleisdreieck', 'mockernbrucke', 'hallesches-tor', 'prinzenstrasse', 'kottbusser-tor', 'gorlitzer-bahnhof', 'schlesisches-tor', 'warschauer-strasse'],
      ],
    },
    {
      id: 'u2',
      short: 'U2',
      name: 'U2',
      colour: '#da421e',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['pankow', 'vinetastrasse', 'schonhauser-allee', 'eberswalder-strasse', 'senefelderplatz', 'rosa-luxemburg-platz', 'alexanderplatz', 'klosterstrasse', 'markisches-museum', 'spittelmarkt', 'hausvogteiplatz', 'stadtmitte', 'anton-wilhelm-amo-strasse', 'potsdamer-platz', 'mendelssohn-bartholdy-park', 'gleisdreieck', 'bulowstrasse', 'nollendorfplatz', 'wittenbergplatz', 'zoologischer-garten', 'ernst-reuter-platz', 'deutsche-oper', 'bismarckstrasse', 'sophie-charlotte-platz', 'kaiserdamm', 'theodor-heuss-platz', 'neu-westend', 'olympia-stadion', 'ruhleben'],
      ],
    },
    {
      id: 'u3',
      short: 'U3',
      name: 'U3',
      colour: '#16683d',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['krumme-lanke', 'onkel-toms-hutte', 'oskar-helene-heim', 'freie-universitat-thielplatz', 'dahlem-dorf', 'podbielskiallee', 'breitenbachplatz', 'rudesheimer-platz', 'heidelberger-platz', 'fehrbelliner-platz', 'hohenzollernplatz', 'spichernstrasse', 'augsburger-strasse', 'wittenbergplatz', 'nollendorfplatz', 'kurfurstenstrasse', 'gleisdreieck', 'mockernbrucke', 'hallesches-tor', 'prinzenstrasse', 'kottbusser-tor', 'gorlitzer-bahnhof', 'schlesisches-tor', 'warschauer-strasse'],
      ],
    },
    {
      id: 'u4',
      short: 'U4',
      name: 'U4',
      colour: '#f0d722',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['innsbrucker-platz', 'rathaus-schoneberg', 'bayerischer-platz', 'viktoria-luise-platz', 'nollendorfplatz'],
      ],
    },
    {
      id: 'u5',
      short: 'U5',
      name: 'U5',
      colour: '#7e5330',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hauptbahnhof', 'bundestag', 'brandenburger-tor', 'unter-den-linden', 'museumsinsel', 'rotes-rathaus', 'alexanderplatz', 'schillingstrasse', 'strausberger-platz', 'weberwiese', 'frankfurter-tor', 'samariterstrasse', 'frankfurter-allee', 'magdalenenstrasse-campus-fur-demokratie', 'lichtenberg', 'friedrichsfelde', 'tierpark', 'biesdorf-sud', 'elsterwerdaer-platz', 'wuhletal', 'kaulsdorf-nord', 'kienberg-garten-der-welt', 'cottbusser-platz', 'hellersdorf', 'louis-lewin-strasse', 'honow'],
      ],
    },
    {
      id: 'u6',
      short: 'U6',
      name: 'U6',
      colour: '#8c6dab',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['alt-mariendorf', 'westphalweg', 'ullsteinstrasse', 'kaiserin-augusta-strasse', 'alt-tempelhof', 'tempelhof', 'paradestrasse', 'platz-der-luftbrucke', 'mehringdamm', 'hallesches-tor', 'kochstrasse-checkpoint-charlie', 'stadtmitte', 'unter-den-linden', 'friedrichstrasse', 'oranienburger-tor', 'naturkundemuseum', 'schwartzkopffstrasse', 'reinickendorfer-strasse', 'wedding', 'leopoldplatz', 'seestrasse', 'rehberge', 'afrikanische-strasse', 'kurt-schumacher-platz'],
      ],
    },
    {
      id: 'u7',
      short: 'U7',
      name: 'U7',
      colour: '#528dba',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['rudow', 'zwickauer-damm', 'wutzkyallee', 'lipschitzallee', 'johannisthaler-chaussee', 'britz-sud', 'parchimer-allee', 'blaschkoallee', 'grenzallee', 'neukolln', 'karl-marx-strasse', 'rathaus-neukolln', 'hermannplatz', 'sudstern', 'gneisenaustrasse', 'mehringdamm', 'mockernbrucke', 'yorckstrasse', 'kleistpark', 'eisenacher-strasse', 'bayerischer-platz', 'berliner-strasse', 'blissestrasse', 'fehrbelliner-platz', 'konstanzer-strasse', 'adenauerplatz', 'wilmersdorfer-strasse', 'bismarckstrasse', 'richard-wagner-platz', 'mierendorffplatz', 'jungfernheide', 'jakob-kaiser-platz', 'halemweg', 'siemensdamm', 'rohrdamm', 'paulsternstrasse', 'haselhorst', 'zitadelle', 'altstadt-spandau', 'rathaus-spandau'],
      ],
    },
    {
      id: 'u8',
      short: 'U8',
      name: 'U8',
      colour: '#224f86',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hermannstrasse', 'leinestrasse', 'boddinstrasse', 'hermannplatz', 'schonleinstrasse', 'kottbusser-tor', 'moritzplatz', 'heinrich-heine-strasse', 'jannowitzbrucke', 'alexanderplatz', 'weinmeisterstrasse', 'rosenthaler-platz', 'bernauer-strasse', 'voltastrasse', 'gesundbrunnen', 'pankstrasse', 'osloer-strasse', 'franz-neumann-platz', 'residenzstrasse', 'paracelsus-bad', 'lindauer-allee', 'karl-bonhoeffer-nervenklinik', 'rathaus-reinickendorf', 'wittenau'],
      ],
    },
    {
      id: 'u9',
      short: 'U9',
      name: 'U9',
      colour: '#f3791d',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['osloer-strasse', 'nauener-platz', 'leopoldplatz', 'amrumer-strasse', 'westhafen', 'birkenstrasse', 'turmstrasse', 'hansaplatz', 'zoologischer-garten', 'kurfurstendamm', 'spichernstrasse', 'guntzelstrasse', 'berliner-strasse', 'bundesplatz', 'friedrich-wilhelm-platz', 'walther-schreiber-platz', 'schlossstrasse', 'rathaus-steglitz'],
      ],
    },
  ],
  times: {
    'oranienburg lehnitz': 4,
    'lehnitz borgsdorf': 6,
    'borgsdorf birkenwerder': 6,
    'birkenwerder hohen-neuendorf-b-berlin': 5,
    'hohen-neuendorf-b-berlin frohnau': 8,
    'frohnau hermsdorf': 4,
    'wittenau wilhelmsruh': 5,
    'wilhelmsruh schonholz': 4,
    'schonholz wollankstrasse': 2,
    'bornholmer-strasse gesundbrunnen': 2,
    'gesundbrunnen humboldthain': 2,
    'nordbahnhof oranienburger-strasse': 2,
    'oranienburger-strasse friedrichstrasse': 2,
    'friedrichstrasse brandenburger-tor': 1,
    'brandenburger-tor potsdamer-platz': 2,
    'potsdamer-platz anhalter-bahnhof': 2,
    'yorckstrasse-grossgorschenstrasse julius-leber-brucke': 2,
    'julius-leber-brucke schoneberg': 2,
    'friedenau feuerbachstrasse': 2,
    'botanischer-garten lichterfelde-west': 2,
    'zehlendorf mexikoplatz': 4,
    'schlachtensee nikolassee': 4,
    'nikolassee schlachtensee': 4,
    'mexikoplatz zehlendorf': 4,
    'lichterfelde-west botanischer-garten': 2,
    'feuerbachstrasse friedenau': 2,
    'schoneberg julius-leber-brucke': 2,
    'julius-leber-brucke yorckstrasse-grossgorschenstrasse': 2,
    'anhalter-bahnhof potsdamer-platz': 2,
    'potsdamer-platz brandenburger-tor': 2,
    'brandenburger-tor friedrichstrasse': 1,
    'friedrichstrasse oranienburger-strasse': 2,
    'oranienburger-strasse nordbahnhof': 2,
    'humboldthain gesundbrunnen': 2,
    'gesundbrunnen bornholmer-strasse': 2,
    'bornholmer-strasse schonholz': 4,
    'schonholz wilhelmsruh': 4,
    'wilhelmsruh wittenau': 5,
    'hermsdorf frohnau': 4,
    'frohnau hohen-neuendorf-b-berlin': 8,
    'hohen-neuendorf-b-berlin birkenwerder': 5,
    'birkenwerder borgsdorf': 6,
    'borgsdorf lehnitz': 6,
    'lehnitz oranienburg': 4,
    'bernau-friedenstal zepernick-bei-bernau': 5,
    'buch karow': 6,
    'karow blankenburg': 6,
    'pankow bornholmer-strasse': 3,
    'humboldthain nordbahnhof': 3,
    'anhalter-bahnhof yorckstrasse': 3,
    'priesterweg attilastrasse': 3,
    'attilastrasse marienfelde': 6,
    'buckower-chaussee schichauweg': 3,
    'schichauweg lichtenrade': 3,
    'lichtenrade mahlow': 6,
    'mahlow blankenfelde-teltow-flaming': 6,
    'erkner wilhelmshagen': 5,
    'wilhelmshagen rahnsdorf': 5,
    'rahnsdorf friedrichshagen': 9,
    'kopenick wuhlheide': 4,
    'wuhlheide karlshorst': 5,
    'karlshorst betriebsbahnhof-rummelsburg': 5,
    'rummelsburg ostkreuz': 2,
    'jannowitzbrucke alexanderplatz': 2,
    'alexanderplatz hackescher-markt': 2,
    'hackescher-markt friedrichstrasse': 2,
    'bellevue tiergarten': 2,
    'tiergarten zoologischer-garten': 2,
    'zoologischer-garten savignyplatz': 2,
    'savignyplatz charlottenburg': 2,
    'westkreuz messe-sud-eichkamp': 2,
    'olympiastadion pichelsberg': 2,
    'pichelsberg stresow': 6,
    'stresow spandau': 2,
    'strausberg-nord strausberg-stadt': 4,
    'strausberg-stadt hegermuhle': 7,
    'hegermuhle strausberg': 6,
    'strausberg petershagen-nord': 6,
    'petershagen-nord fredersdorf-bei-berlin': 4,
    'fredersdorf-bei-berlin neuenhagen': 8,
    'neuenhagen hoppegarten-mark': 4,
    'hoppegarten-mark birkenstein': 4,
    'birkenstein mahlsdorf': 5,
    'kaulsdorf wuhletal': 2,
    'biesdorf friedrichsfelde-ost': 5,
    'noldnerplatz ostkreuz': 2,
    'ahrensfelde mehrower-allee': 4,
    'springpfuhl friedrichsfelde-ost': 4,
    'friedrichsfelde-ost lichtenberg': 3,
    'lichtenberg noldnerplatz': 3,
    'ostkreuz warschauer-strasse': 3,
    'warschauer-strasse ostbahnhof': 3,
    'ostbahnhof jannowitzbrucke': 3,
    'friedrichstrasse hauptbahnhof': 3,
    'hauptbahnhof bellevue': 3,
    'charlottenburg westkreuz': 3,
    'westkreuz grunewald': 4,
    'grunewald nikolassee': 15,
    'nikolassee wannsee': 3,
    'wannsee griebnitzsee': 9,
    'griebnitzsee babelsberg': 5,
    'babelsberg potsdam-hauptbahnhof': 4,
    'hohen-neuendorf-b-berlin bergfelde': 5,
    'schonfliess muhlenbeck-monchmuhle': 7,
    'muhlenbeck-monchmuhle blankenburg': 16,
    'blankenburg pankow-heinersdorf': 4,
    'pankow-heinersdorf pankow': 4,
    'schonhauser-allee prenzlauer-allee': 2,
    'prenzlauer-allee greifswalder-strasse': 2,
    'landsberger-allee storkower-strasse': 2,
    'treptower-park planterwald': 4,
    'baumschulenweg schoneweide': 4,
    'johannisthal adlershof': 4,
    'adlershof grunau': 7,
    'grunau eichwalde': 11,
    'eichwalde zeuthen': 5,
    'zeuthen wildau': 7,
    'flughafen-ber wassmannsdorf': 6,
    'wassmannsdorf schonefeld': 8,
    'schonefeld grunbergallee': 5,
    'altglienicke adlershof': 7,
    'adlershof johannisthal': 4,
    'schoneweide baumschulenweg': 4,
    'planterwald treptower-park': 4,
    'hennigsdorf-bei-berlin heiligensee': 4,
    'heiligensee schulzendorf': 4,
    'schulzendorf tegel': 8,
    'tegel eichborndamm': 4,
    'karl-bonhoeffer-nervenklinik alt-reinickendorf': 3,
    'alt-reinickendorf schonholz': 5,
    'wollankstrasse bornholmer-strasse': 3,
    'yorckstrasse sudkreuz': 4,
    'sudkreuz priesterweg': 4,
    'priesterweg sudende': 3,
    'sudende lankwitz': 3,
    'lankwitz lichterfelde-ost': 3,
    'lichterfelde-ost osdorfer-strasse': 3,
    'lichterfelde-sud teltow-stadt': 5,
    'teltow-stadt lichterfelde-sud': 5,
    'osdorfer-strasse lichterfelde-ost': 3,
    'lichterfelde-ost lankwitz': 3,
    'lankwitz sudende': 3,
    'sudende priesterweg': 3,
    'priesterweg sudkreuz': 4,
    'sudkreuz yorckstrasse': 4,
    'yorckstrasse anhalter-bahnhof': 3,
    'nordbahnhof humboldthain': 3,
    'schonholz alt-reinickendorf': 5,
    'alt-reinickendorf karl-bonhoeffer-nervenklinik': 3,
    'eichborndamm tegel': 4,
    'tegel schulzendorf': 8,
    'schulzendorf heiligensee': 4,
    'heiligensee hennigsdorf-bei-berlin': 4,
    'bornholmer-strasse pankow': 3,
    'pankow pankow-heinersdorf': 4,
    'pankow-heinersdorf blankenburg': 4,
    'gesundbrunnen schonhauser-allee': 4,
    'greifswalder-strasse landsberger-allee': 3,
    'storkower-strasse frankfurter-allee': 3,
    'frankfurter-allee ostkreuz': 3,
    'ostkreuz treptower-park': 3,
    'treptower-park sonnenallee': 5,
    'hermannstrasse tempelhof': 6,
    'tempelhof sudkreuz': 3,
    'bundesplatz heidelberger-platz': 3,
    'heidelberger-platz hohenzollerndamm': 3,
    'messe-nord-zob westend': 3,
    'westend jungfernheide': 4,
    'jungfernheide beusselstrasse': 4,
    'westhafen wedding': 4,
    'wedding gesundbrunnen': 4,
    'gesundbrunnen wedding': 4,
    'wedding westhafen': 4,
    'beusselstrasse jungfernheide': 4,
    'jungfernheide westend': 4,
    'westend messe-nord-zob': 3,
    'hohenzollerndamm heidelberger-platz': 3,
    'heidelberger-platz bundesplatz': 3,
    'sudkreuz tempelhof': 3,
    'tempelhof hermannstrasse': 6,
    'sonnenallee treptower-park': 5,
    'treptower-park ostkreuz': 3,
    'ostkreuz frankfurter-allee': 3,
    'frankfurter-allee storkower-strasse': 3,
    'landsberger-allee greifswalder-strasse': 3,
    'schonhauser-allee gesundbrunnen': 4,
    'konigs-wusterhausen wildau': 5,
    'wildau zeuthen': 7,
    'zeuthen eichwalde': 5,
    'eichwalde grunau': 11,
    'grunau adlershof': 7,
    'johannisthal schoneweide': 3,
    'baumschulenweg kollnische-heide': 3,
    'kollnische-heide neukolln': 4,
    'hermannstrasse neukolln': 2,
    'kollnische-heide baumschulenweg': 3,
    'ostkreuz noldnerplatz': 2,
    'friedrichsfelde-ost springpfuhl': 4,
    'springpfuhl gehrenseestrasse': 7,
    'hohenschonhausen wartenberg': 2,
    'adlershof altglienicke': 7,
    'grunbergallee schonefeld': 5,
    'schonefeld wassmannsdorf': 8,
    'wassmannsdorf flughafen-ber': 6,
    'storkower-strasse landsberger-allee': 2,
    'greifswalder-strasse prenzlauer-allee': 2,
    'prenzlauer-allee schonhauser-allee': 2,
    'uhlandstrasse kurfurstendamm': 1,
    'nollendorfplatz kurfurstenstrasse': 1,
    'mockernbrucke hallesches-tor': 1,
    'vinetastrasse schonhauser-allee': 3,
    'senefelderplatz rosa-luxemburg-platz': 1,
    'alexanderplatz klosterstrasse': 1,
    'klosterstrasse markisches-museum': 1,
    'markisches-museum spittelmarkt': 1,
    'hausvogteiplatz stadtmitte': 1,
    'stadtmitte anton-wilhelm-amo-strasse': 1,
    'mendelssohn-bartholdy-park gleisdreieck': 1,
    'deutsche-oper bismarckstrasse': 1,
    'theodor-heuss-platz neu-westend': 3,
    'olympia-stadion ruhleben': 3,
    'krumme-lanke onkel-toms-hutte': 3,
    'heidelberger-platz fehrbelliner-platz': 3,
    'hohenzollernplatz spichernstrasse': 1,
    'spichernstrasse augsburger-strasse': 1,
    'augsburger-strasse wittenbergplatz': 1,
    'innsbrucker-platz rathaus-schoneberg': 1,
    'brandenburger-tor unter-den-linden': 1,
    'rotes-rathaus alexanderplatz': 1,
    'friedrichsfelde tierpark': 3,
    'tierpark biesdorf-sud': 3,
    'biesdorf-sud elsterwerdaer-platz': 3,
    'elsterwerdaer-platz wuhletal': 3,
    'wuhletal kaulsdorf-nord': 3,
    'mehringdamm hallesches-tor': 1,
    'unter-den-linden friedrichstrasse': 1,
    'reinickendorfer-strasse wedding': 1,
    'leopoldplatz seestrasse': 1,
    'seestrasse rehberge': 3,
    'blaschkoallee grenzallee': 3,
    'hermannplatz sudstern': 3,
    'gneisenaustrasse mehringdamm': 1,
    'wilmersdorfer-strasse bismarckstrasse': 1,
    'mierendorffplatz jungfernheide': 1,
    'jakob-kaiser-platz halemweg': 1,
    'altstadt-spandau rathaus-spandau': 1,
    'heinrich-heine-strasse jannowitzbrucke': 1,
    'bernauer-strasse voltastrasse': 1,
    'karl-bonhoeffer-nervenklinik rathaus-reinickendorf': 3,
    'westhafen birkenstrasse': 1,
    'hansaplatz zoologischer-garten': 3,
    'zoologischer-garten kurfurstendamm': 1,
    'spichernstrasse guntzelstrasse': 1,
    'guntzelstrasse berliner-strasse': 1,
    'walther-schreiber-platz schlossstrasse': 1,
  },
  stations: {
    gesundbrunnen: { name: 'Gesundbrunnen', x: 54, y: 32.5 },
    'schonhauser-allee': { name: 'Schönhauser Allee', x: 60, y: 34 },
    'prenzlauer-allee': { name: 'Prenzlauer Allee', x: 67.5, y: 36 },
    'greifswalder-strasse': { name: 'Greifswalder Straße', x: 72.5, y: 40 },
    'landsberger-allee': { name: 'Landsberger Allee', x: 76, y: 45 },
    'storkower-strasse': { name: 'Storkower Straße', x: 78.5, y: 50 },
    'frankfurter-allee': { name: 'Frankfurter Allee', x: 81, y: 55.5 },
    ostkreuz: { name: 'Ostkreuz', x: 79, y: 61 },
    'treptower-park': { name: 'Treptower Park', x: 76, y: 66 },
    sonnenallee: { name: 'Sonnenallee', x: 73, y: 71 },
    neukolln: { name: 'Neukölln', x: 67.5, y: 74.5 },
    hermannstrasse: { name: 'Hermannstraße', x: 61, y: 76.5 },
    tempelhof: { name: 'Tempelhof', x: 54, y: 78.5 },
    sudkreuz: { name: 'Südkreuz', x: 47, y: 79 },
    schoneberg: { name: 'Schöneberg', x: 40, y: 77.5 },
    'innsbrucker-platz': { name: 'Innsbrucker Platz', x: 33.5, y: 75.5 },
    bundesplatz: { name: 'Bundesplatz', x: 27.5, y: 73 },
    'heidelberger-platz': { name: 'Heidelberger Platz', x: 23.5, y: 68.5 },
    hohenzollerndamm: { name: 'Hohenzollerndamm', x: 20.5, y: 63.5 },
    halensee: { name: 'Halensee', x: 18, y: 58.5 },
    westkreuz: { name: 'Westkreuz', x: 18, y: 53 },
    'messe-nord-zob': { name: 'Messe Nord/ZOB', x: 20.5, y: 47.5 },
    westend: { name: 'Westend', x: 23.5, y: 42.5 },
    jungfernheide: { name: 'Jungfernheide', x: 27, y: 38 },
    beusselstrasse: { name: 'Beusselstraße', x: 33.5, y: 35 },
    westhafen: { name: 'Westhafen', x: 40, y: 33.5 },
    wedding: { name: 'Wedding', x: 47, y: 31.5 },
    'kollnische-heide': { name: 'Köllnische Heide', x: 72, y: 74 },
    baumschulenweg: { name: 'Baumschulenweg', x: 76.5, y: 74 },
    schoneweide: { name: 'Schöneweide', x: 80.5, y: 76.5 },
    oberspree: { name: 'Oberspree', x: 83.5, y: 76.5 },
    spindlersfeld: { name: 'Spindlersfeld', x: 86.5, y: 76.5 },
    oranienburg: { name: 'Oranienburg', x: 33, y: 0 },
    lehnitz: { name: 'Lehnitz', x: 35.5, y: 2.5 },
    borgsdorf: { name: 'Borgsdorf', x: 38, y: 4.5 },
    birkenwerder: { name: 'Birkenwerder', x: 40.5, y: 7 },
    'hohen-neuendorf-b-berlin': { name: 'Hohen Neuendorf (b Berlin)', x: 43, y: 10 },
    frohnau: { name: 'Frohnau', x: 40.5, y: 12 },
    hermsdorf: { name: 'Hermsdorf', x: 40, y: 15 },
    waidmannslust: { name: 'Waidmannslust', x: 42.5, y: 17.5 },
    wittenau: { name: 'Wittenau', x: 44.5, y: 20 },
    wilhelmsruh: { name: 'Wilhelmsruh', x: 48, y: 22 },
    schonholz: { name: 'Schönholz', x: 50.5, y: 25.5 },
    wollankstrasse: { name: 'Wollankstraße', x: 53, y: 27 },
    'bornholmer-strasse': { name: 'Bornholmer Straße', x: 55.5, y: 29.5 },
    humboldthain: { name: 'Humboldthain', x: 53.5, y: 38.5 },
    nordbahnhof: { name: 'Nordbahnhof', x: 53.5, y: 42.5 },
    'oranienburger-strasse': { name: 'Oranienburger Straße', x: 53.5, y: 46.5 },
    friedrichstrasse: { name: 'Friedrichstraße', x: 51, y: 50 },
    'brandenburger-tor': { name: 'Brandenburger Tor', x: 50, y: 55 },
    'potsdamer-platz': { name: 'Potsdamer Platz', x: 48.5, y: 60 },
    'anhalter-bahnhof': { name: 'Anhalter Bahnhof', x: 47.5, y: 66.5 },
    'yorckstrasse-grossgorschenstrasse': { name: 'Yorckstraße (Großgörschenstraße)', x: 44.5, y: 69.5 },
    'julius-leber-brucke': { name: 'Julius-Leber-Brücke', x: 41.5, y: 73 },
    friedenau: { name: 'Friedenau', x: 36, y: 79 },
    feuerbachstrasse: { name: 'Feuerbachstraße', x: 32.5, y: 81 },
    'rathaus-steglitz': { name: 'Rathaus Steglitz', x: 28, y: 81 },
    'botanischer-garten': { name: 'Botanischer Garten', x: 24.5, y: 81 },
    'lichterfelde-west': { name: 'Lichterfelde West', x: 21.5, y: 80 },
    'sundgauer-strasse': { name: 'Sundgauer Straße', x: 18.5, y: 79.5 },
    zehlendorf: { name: 'Zehlendorf', x: 16, y: 76.5 },
    mexikoplatz: { name: 'Mexikoplatz', x: 13.5, y: 72.5 },
    schlachtensee: { name: 'Schlachtensee', x: 13, y: 67.5 },
    nikolassee: { name: 'Nikolassee', x: 13, y: 62.5 },
    wannsee: { name: 'Wannsee', x: 10, y: 66 },
    'strausberg-nord': { name: 'Strausberg Nord', x: 127, y: 41 },
    'strausberg-stadt': { name: 'Strausberg Stadt', x: 127, y: 44 },
    hegermuhle: { name: 'Hegermühle', x: 126.5, y: 47 },
    strausberg: { name: 'Strausberg', x: 126.5, y: 50 },
    'petershagen-nord': { name: 'Petershagen Nord', x: 124, y: 52.5 },
    'fredersdorf-bei-berlin': { name: 'Fredersdorf (bei Berlin)', x: 120.5, y: 52.5 },
    neuenhagen: { name: 'Neuenhagen', x: 117, y: 52.5 },
    'hoppegarten-mark': { name: 'Hoppegarten (Mark)', x: 113.5, y: 52.5 },
    birkenstein: { name: 'Birkenstein', x: 110, y: 53 },
    mahlsdorf: { name: 'Mahlsdorf', x: 106, y: 53 },
    kaulsdorf: { name: 'Kaulsdorf', x: 102.5, y: 53 },
    wuhletal: { name: 'Wuhletal', x: 98.5, y: 53 },
    biesdorf: { name: 'Biesdorf', x: 94.5, y: 53 },
    'friedrichsfelde-ost': { name: 'Friedrichsfelde Ost', x: 90, y: 52.5 },
    lichtenberg: { name: 'Lichtenberg', x: 86.5, y: 55.5 },
    noldnerplatz: { name: 'Nöldnerplatz', x: 82.5, y: 58.5 },
    'warschauer-strasse': { name: 'Warschauer Straße', x: 73, y: 61.5 },
    ostbahnhof: { name: 'Ostbahnhof', x: 69, y: 57 },
    jannowitzbrucke: { name: 'Jannowitzbrücke', x: 65, y: 53.5 },
    alexanderplatz: { name: 'Alexanderplatz', x: 61.5, y: 49.5 },
    'hackescher-markt': { name: 'Hackescher Markt', x: 56, y: 49.5 },
    hauptbahnhof: { name: 'Hauptbahnhof', x: 46, y: 50 },
    bellevue: { name: 'Bellevue', x: 41.5, y: 50 },
    tiergarten: { name: 'Tiergarten', x: 38, y: 52 },
    'zoologischer-garten': { name: 'Zoologischer Garten', x: 34, y: 54 },
    savignyplatz: { name: 'Savignyplatz', x: 28.5, y: 53.5 },
    charlottenburg: { name: 'Charlottenburg', x: 23.5, y: 53.5 },
    ahrensfelde: { name: 'Ahrensfelde', x: 99.5, y: 37.5 },
    'mehrower-allee': { name: 'Mehrower Allee', x: 97.5, y: 39.5 },
    'raoul-wallenberg-strasse': { name: 'Raoul-Wallenberg-Straße', x: 95.5, y: 42 },
    marzahn: { name: 'Marzahn', x: 93, y: 44 },
    poelchaustrasse: { name: 'Poelchaustraße', x: 93, y: 47 },
    springpfuhl: { name: 'Springpfuhl', x: 90.5, y: 49.5 },
    grunewald: { name: 'Grunewald', x: 15.5, y: 58.5 },
    griebnitzsee: { name: 'Griebnitzsee', x: 7.5, y: 68.5 },
    babelsberg: { name: 'Babelsberg', x: 5, y: 71 },
    'potsdam-hauptbahnhof': { name: 'Potsdam Hauptbahnhof', x: 2, y: 71 },
    gehrenseestrasse: { name: 'Gehrenseestraße', x: 90.5, y: 46 },
    hohenschonhausen: { name: 'Hohenschönhausen', x: 90.5, y: 43 },
    wartenberg: { name: 'Wartenberg', x: 90.5, y: 40 },
    bundestag: { name: 'Bundestag', x: 48, y: 52.5 },
    'unter-den-linden': { name: 'Unter den Linden', x: 53, y: 53 },
    museumsinsel: { name: 'Museumsinsel', x: 56, y: 52 },
    'rotes-rathaus': { name: 'Rotes Rathaus', x: 59, y: 52 },
    schillingstrasse: { name: 'Schillingstraße', x: 65, y: 50 },
    'strausberger-platz': { name: 'Strausberger Platz', x: 67.5, y: 52 },
    weberwiese: { name: 'Weberwiese', x: 71, y: 52.5 },
    'frankfurter-tor': { name: 'Frankfurter Tor', x: 74.5, y: 52.5 },
    samariterstrasse: { name: 'Samariterstraße', x: 78, y: 53 },
    'magdalenenstrasse-campus-fur-demokratie': { name: 'Magdalenenstraße (Campus für Demokratie)', x: 83.5, y: 55.5 },
    friedrichsfelde: { name: 'Friedrichsfelde', x: 89.5, y: 55 },
    tierpark: { name: 'Tierpark', x: 92, y: 57 },
    'biesdorf-sud': { name: 'Biesdorf-Süd', x: 95, y: 56.5 },
    'elsterwerdaer-platz': { name: 'Elsterwerdaer Platz', x: 98.5, y: 56.5 },
    'kaulsdorf-nord': { name: 'Kaulsdorf-Nord', x: 101, y: 51 },
    'kienberg-garten-der-welt': { name: 'Kienberg (Gärten der Welt)', x: 101, y: 48 },
    'cottbusser-platz': { name: 'Cottbusser Platz', x: 101, y: 45 },
    hellersdorf: { name: 'Hellersdorf', x: 104.5, y: 45 },
    'louis-lewin-strasse': { name: 'Louis-Lewin-Straße', x: 106.5, y: 43 },
    honow: { name: 'Hönow', x: 108.5, y: 45 },
    bernau: { name: 'Bernau', x: 78, y: 15.5 },
    'bernau-friedenstal': { name: 'Bernau-Friedenstal', x: 75, y: 15.5 },
    'zepernick-bei-bernau': { name: 'Zepernick (bei Bernau)', x: 71.5, y: 15.5 },
    rontgental: { name: 'Röntgental', x: 68, y: 16 },
    buch: { name: 'Buch', x: 64.5, y: 16 },
    karow: { name: 'Karow', x: 61, y: 16.5 },
    blankenburg: { name: 'Blankenburg', x: 57, y: 17 },
    'pankow-heinersdorf': { name: 'Pankow-Heinersdorf', x: 57.5, y: 22 },
    pankow: { name: 'Pankow', x: 57.5, y: 26.5 },
    yorckstrasse: { name: 'Yorckstraße', x: 46.5, y: 71 },
    priesterweg: { name: 'Priesterweg', x: 44, y: 82 },
    attilastrasse: { name: 'Attilastraße', x: 44.5, y: 85.5 },
    marienfelde: { name: 'Marienfelde', x: 46.5, y: 88.5 },
    'buckower-chaussee': { name: 'Buckower Chaussee', x: 49, y: 91.5 },
    schichauweg: { name: 'Schichauweg', x: 51, y: 94 },
    lichtenrade: { name: 'Lichtenrade', x: 53.5, y: 96.5 },
    mahlow: { name: 'Mahlow', x: 55.5, y: 99 },
    'blankenfelde-teltow-flaming': { name: 'Blankenfelde (Teltow-Fläming)', x: 57.5, y: 101 },
    bergfelde: { name: 'Bergfelde', x: 47, y: 10.5 },
    schonfliess: { name: 'Schönfließ', x: 51, y: 11 },
    'muhlenbeck-monchmuhle': { name: 'Mühlenbeck-Mönchmühle', x: 54, y: 14 },
    planterwald: { name: 'Plänterwald', x: 76.5, y: 69.5 },
    johannisthal: { name: 'Johannisthal', x: 84, y: 79.5 },
    adlershof: { name: 'Adlershof', x: 87, y: 82.5 },
    grunau: { name: 'Grünau', x: 90, y: 84.5 },
    eichwalde: { name: 'Eichwalde', x: 92, y: 87 },
    zeuthen: { name: 'Zeuthen', x: 92.5, y: 90.5 },
    wildau: { name: 'Wildau', x: 92.5, y: 93.5 },
    erkner: { name: 'Erkner', x: 110.5, y: 71 },
    wilhelmshagen: { name: 'Wilhelmshagen', x: 108.5, y: 68.5 },
    rahnsdorf: { name: 'Rahnsdorf', x: 105, y: 68.5 },
    friedrichshagen: { name: 'Friedrichshagen', x: 102, y: 68.5 },
    hirschgarten: { name: 'Hirschgarten', x: 98.5, y: 68.5 },
    kopenick: { name: 'Köpenick', x: 95, y: 68.5 },
    wuhlheide: { name: 'Wuhlheide', x: 92, y: 66 },
    karlshorst: { name: 'Karlshorst', x: 89, y: 63.5 },
    'betriebsbahnhof-rummelsburg': { name: 'Betriebsbahnhof Rummelsburg', x: 86.5, y: 61.5 },
    rummelsburg: { name: 'Rummelsburg', x: 82.5, y: 61 },
    'messe-sud-eichkamp': { name: 'Messe Süd (Eichkamp)', x: 15.5, y: 53 },
    heerstrasse: { name: 'Heerstraße', x: 12.5, y: 53 },
    olympiastadion: { name: 'Olympiastadion', x: 9, y: 53 },
    pichelsberg: { name: 'Pichelsberg', x: 7, y: 51 },
    stresow: { name: 'Stresow', x: 4.5, y: 49 },
    spandau: { name: 'Spandau', x: 2.5, y: 47 },
    'flughafen-ber': { name: 'Flughafen BER', x: 82, y: 96.5 },
    wassmannsdorf: { name: 'Waßmannsdorf', x: 82, y: 93.5 },
    schonefeld: { name: 'Schönefeld', x: 84, y: 91 },
    grunbergallee: { name: 'Grünbergallee', x: 86, y: 88.5 },
    altglienicke: { name: 'Altglienicke', x: 87.5, y: 86 },
    'konigs-wusterhausen': { name: 'Königs Wusterhausen', x: 92.5, y: 96.5 },
    'hennigsdorf-bei-berlin': { name: 'Hennigsdorf (bei Berlin)', x: 23, y: 19 },
    heiligensee: { name: 'Heiligensee', x: 25.5, y: 21.5 },
    schulzendorf: { name: 'Schulzendorf', x: 29, y: 22 },
    tegel: { name: 'Tegel', x: 32.5, y: 22 },
    eichborndamm: { name: 'Eichborndamm', x: 36.5, y: 22.5 },
    'karl-bonhoeffer-nervenklinik': { name: 'Karl-Bonhoeffer-Nervenklinik', x: 40.5, y: 23.5 },
    'alt-reinickendorf': { name: 'Alt-Reinickendorf', x: 45, y: 25 },
    sudende: { name: 'Südende', x: 41.5, y: 84.5 },
    lankwitz: { name: 'Lankwitz', x: 39, y: 87 },
    'lichterfelde-ost': { name: 'Lichterfelde Ost', x: 36.5, y: 89.5 },
    'osdorfer-strasse': { name: 'Osdorfer Straße', x: 34, y: 92 },
    'lichterfelde-sud': { name: 'Lichterfelde Süd', x: 32, y: 94 },
    'teltow-stadt': { name: 'Teltow Stadt', x: 28.5, y: 94.5 },
    vinetastrasse: { name: 'Vinetastraße', x: 58.5, y: 30 },
    'eberswalder-strasse': { name: 'Eberswalder Straße', x: 61.5, y: 37 },
    senefelderplatz: { name: 'Senefelderplatz', x: 61.5, y: 41.5 },
    'rosa-luxemburg-platz': { name: 'Rosa-Luxemburg-Platz', x: 61.5, y: 45.5 },
    klosterstrasse: { name: 'Klosterstraße', x: 63, y: 52 },
    'markisches-museum': { name: 'Märkisches Museum', x: 60.5, y: 54 },
    spittelmarkt: { name: 'Spittelmarkt', x: 58, y: 56.5 },
    hausvogteiplatz: { name: 'Hausvogteiplatz', x: 55.5, y: 54.5 },
    stadtmitte: { name: 'Stadtmitte', x: 53, y: 57 },
    'anton-wilhelm-amo-strasse': { name: 'Anton-Wilhelm-Amo-Straße', x: 50.5, y: 57.5 },
    'mendelssohn-bartholdy-park': { name: 'Mendelssohn-Bartholdy-Park', x: 46, y: 62 },
    gleisdreieck: { name: 'Gleisdreieck', x: 46, y: 65 },
    bulowstrasse: { name: 'Bülowstraße', x: 42, y: 64.5 },
    nollendorfplatz: { name: 'Nollendorfplatz', x: 39.5, y: 62.5 },
    wittenbergplatz: { name: 'Wittenbergplatz', x: 36.5, y: 57.5 },
    'ernst-reuter-platz': { name: 'Ernst-Reuter-Platz', x: 31.5, y: 53.5 },
    'deutsche-oper': { name: 'Deutsche Oper', x: 29.5, y: 51 },
    bismarckstrasse: { name: 'Bismarckstraße', x: 26.5, y: 50.5 },
    'sophie-charlotte-platz': { name: 'Sophie-Charlotte-Platz', x: 23, y: 50.5 },
    kaiserdamm: { name: 'Kaiserdamm', x: 20, y: 51 },
    'theodor-heuss-platz': { name: 'Theodor-Heuss-Platz', x: 17, y: 51 },
    'neu-westend': { name: 'Neu-Westend', x: 14, y: 51 },
    'olympia-stadion': { name: 'Olympia-Stadion', x: 11, y: 51 },
    ruhleben: { name: 'Ruhleben', x: 8.5, y: 48.5 },
    uhlandstrasse: { name: 'Uhlandstraße', x: 30, y: 57.5 },
    kurfurstendamm: { name: 'Kurfürstendamm', x: 33, y: 57.5 },
    kurfurstenstrasse: { name: 'Kurfürstenstraße', x: 43, y: 62 },
    mockernbrucke: { name: 'Möckernbrücke', x: 49.5, y: 68 },
    'hallesches-tor': { name: 'Hallesches Tor', x: 53, y: 64 },
    prinzenstrasse: { name: 'Prinzenstraße', x: 57.5, y: 63.5 },
    'kottbusser-tor': { name: 'Kottbusser Tor', x: 61.5, y: 62.5 },
    'gorlitzer-bahnhof': { name: 'Görlitzer Bahnhof', x: 65.5, y: 62 },
    'schlesisches-tor': { name: 'Schlesisches Tor', x: 69.5, y: 62 },
    'krumme-lanke': { name: 'Krumme Lanke', x: 3, y: 77 },
    'onkel-toms-hutte': { name: 'Onkel Toms Hütte', x: 6, y: 76.5 },
    'oskar-helene-heim': { name: 'Oskar-Helene-Heim', x: 8.5, y: 79 },
    'freie-universitat-thielplatz': { name: 'Freie Universität (Thielplatz)', x: 11.5, y: 78.5 },
    'dahlem-dorf': { name: 'Dahlem-Dorf', x: 13.5, y: 76.5 },
    podbielskiallee: { name: 'Podbielskiallee', x: 16, y: 74 },
    breitenbachplatz: { name: 'Breitenbachplatz', x: 18.5, y: 72 },
    'rudesheimer-platz': { name: 'Rüdesheimer Platz', x: 21, y: 70 },
    'fehrbelliner-platz': { name: 'Fehrbelliner Platz', x: 26.5, y: 65.5 },
    hohenzollernplatz: { name: 'Hohenzollernplatz', x: 29.5, y: 63.5 },
    spichernstrasse: { name: 'Spichernstraße', x: 32, y: 61.5 },
    'augsburger-strasse': { name: 'Augsburger Straße', x: 34.5, y: 60 },
    'rathaus-schoneberg': { name: 'Rathaus Schöneberg', x: 34.5, y: 72 },
    'bayerischer-platz': { name: 'Bayerischer Platz', x: 35, y: 69 },
    'viktoria-luise-platz': { name: 'Viktoria-Luise-Platz', x: 37, y: 65.5 },
    rudow: { name: 'Rudow', x: 81.5, y: 91 },
    'zwickauer-damm': { name: 'Zwickauer Damm', x: 79.5, y: 89 },
    wutzkyallee: { name: 'Wutzkyallee', x: 77, y: 89 },
    lipschitzallee: { name: 'Lipschitzallee', x: 74, y: 89.5 },
    'johannisthaler-chaussee': { name: 'Johannisthaler Chaussee', x: 72, y: 87.5 },
    'britz-sud': { name: 'Britz-Süd', x: 72, y: 84.5 },
    'parchimer-allee': { name: 'Parchimer Allee', x: 72, y: 81.5 },
    blaschkoallee: { name: 'Blaschkoallee', x: 72, y: 78.5 },
    grenzallee: { name: 'Grenzallee', x: 70, y: 76.5 },
    'karl-marx-strasse': { name: 'Karl-Marx-Straße', x: 67.5, y: 71.5 },
    'rathaus-neukolln': { name: 'Rathaus Neukölln', x: 65.5, y: 69.5 },
    hermannplatz: { name: 'Hermannplatz', x: 63, y: 67.5 },
    sudstern: { name: 'Südstern', x: 60, y: 67.5 },
    gneisenaustrasse: { name: 'Gneisenaustraße', x: 56.5, y: 67.5 },
    mehringdamm: { name: 'Mehringdamm', x: 53, y: 67.5 },
    kleistpark: { name: 'Kleistpark', x: 42.5, y: 70.5 },
    'eisenacher-strasse': { name: 'Eisenacher Straße', x: 38.5, y: 69.5 },
    'berliner-strasse': { name: 'Berliner Straße', x: 31, y: 69.5 },
    blissestrasse: { name: 'Blissestraße', x: 29, y: 67.5 },
    'konstanzer-strasse': { name: 'Konstanzer Straße', x: 26.5, y: 61.5 },
    adenauerplatz: { name: 'Adenauerplatz', x: 26.5, y: 58 },
    'wilmersdorfer-strasse': { name: 'Wilmersdorfer Straße', x: 26, y: 54.5 },
    'richard-wagner-platz': { name: 'Richard-Wagner-Platz', x: 27, y: 46.5 },
    mierendorffplatz: { name: 'Mierendorffplatz', x: 27, y: 42.5 },
    'jakob-kaiser-platz': { name: 'Jakob-Kaiser-Platz', x: 24, y: 39 },
    halemweg: { name: 'Halemweg', x: 21, y: 39 },
    siemensdamm: { name: 'Siemensdamm', x: 17.5, y: 39.5 },
    rohrdamm: { name: 'Rohrdamm', x: 14.5, y: 39.5 },
    paulsternstrasse: { name: 'Paulsternstraße', x: 11.5, y: 39.5 },
    haselhorst: { name: 'Haselhorst', x: 8.5, y: 40 },
    zitadelle: { name: 'Zitadelle', x: 5, y: 40 },
    'altstadt-spandau': { name: 'Altstadt Spandau', x: 2, y: 40 },
    'rathaus-spandau': { name: 'Rathaus Spandau', x: 0, y: 42 },
    leinestrasse: { name: 'Leinestraße', x: 63, y: 74 },
    boddinstrasse: { name: 'Boddinstraße', x: 63, y: 71 },
    schonleinstrasse: { name: 'Schönleinstraße', x: 63.5, y: 64.5 },
    moritzplatz: { name: 'Moritzplatz', x: 62, y: 59 },
    'heinrich-heine-strasse': { name: 'Heinrich-Heine-Straße', x: 62.5, y: 56 },
    weinmeisterstrasse: { name: 'Weinmeisterstraße', x: 59.5, y: 46 },
    'rosenthaler-platz': { name: 'Rosenthaler Platz', x: 57.5, y: 43 },
    'bernauer-strasse': { name: 'Bernauer Straße', x: 56, y: 39.5 },
    voltastrasse: { name: 'Voltastraße', x: 54, y: 36 },
    pankstrasse: { name: 'Pankstraße', x: 52, y: 31 },
    'osloer-strasse': { name: 'Osloer Straße', x: 49.5, y: 28.5 },
    'franz-neumann-platz': { name: 'Franz-Neumann-Platz', x: 48, y: 26.5 },
    residenzstrasse: { name: 'Residenzstraße', x: 47, y: 24.5 },
    'paracelsus-bad': { name: 'Paracelsus-Bad', x: 45.5, y: 22.5 },
    'lindauer-allee': { name: 'Lindauer Allee', x: 43, y: 23 },
    'rathaus-reinickendorf': { name: 'Rathaus Reinickendorf', x: 41, y: 20 },
    'nauener-platz': { name: 'Nauener Platz', x: 46.5, y: 30 },
    leopoldplatz: { name: 'Leopoldplatz', x: 43, y: 32 },
    'amrumer-strasse': { name: 'Amrumer Straße', x: 39, y: 32 },
    birkenstrasse: { name: 'Birkenstraße', x: 37, y: 38.5 },
    turmstrasse: { name: 'Turmstraße', x: 36, y: 44 },
    hansaplatz: { name: 'Hansaplatz', x: 35, y: 49 },
    guntzelstrasse: { name: 'Güntzelstraße', x: 31.5, y: 65.5 },
    'friedrich-wilhelm-platz': { name: 'Friedrich-Wilhelm-Platz', x: 27, y: 75 },
    'walther-schreiber-platz': { name: 'Walther-Schreiber-Platz', x: 26, y: 77 },
    schlossstrasse: { name: 'Schloßstraße', x: 24.5, y: 79 },
    'alt-mariendorf': { name: 'Alt-Mariendorf', x: 54, y: 93.5 },
    westphalweg: { name: 'Westphalweg', x: 54, y: 90.5 },
    ullsteinstrasse: { name: 'Ullsteinstraße', x: 54, y: 87.5 },
    'kaiserin-augusta-strasse': { name: 'Kaiserin-Augusta-Straße', x: 54, y: 84.5 },
    'alt-tempelhof': { name: 'Alt-Tempelhof', x: 54, y: 81 },
    paradestrasse: { name: 'Paradestraße', x: 53.5, y: 74.5 },
    'platz-der-luftbrucke': { name: 'Platz der Luftbrücke', x: 53.5, y: 71 },
    'kochstrasse-checkpoint-charlie': { name: 'Kochstraße/Checkpoint Charlie', x: 53.5, y: 60.5 },
    'oranienburger-tor': { name: 'Oranienburger Tor', x: 50.5, y: 46 },
    naturkundemuseum: { name: 'Naturkundemuseum', x: 51, y: 42 },
    schwartzkopffstrasse: { name: 'Schwartzkopffstraße', x: 48.5, y: 39 },
    'reinickendorfer-strasse': { name: 'Reinickendorfer Straße', x: 46.5, y: 36 },
    seestrasse: { name: 'Seestraße', x: 41, y: 30 },
    rehberge: { name: 'Rehberge', x: 38.5, y: 28 },
    'afrikanische-strasse': { name: 'Afrikanische Straße', x: 36.5, y: 26 },
    'kurt-schumacher-platz': { name: 'Kurt-Schumacher-Platz', x: 34.5, y: 24 },
  },
};
