// Brussels's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'brussels',
  name: 'Brussels',
  system: 'Metro',
  country: 'Belgium',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Metro 1',
      colour: '#b5378c',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['gare-de-l-ouest-weststation', 'beekkant', 'etangs-noirs-zwarte-vijvers', 'comte-de-flandre-graaf-van-vlaanderen', 'sainte-catherine-sint-katelijne', 'de-brouckere', 'gare-centrale-centraal-station', 'parc-park', 'arts-loi-kunst-wet', 'maelbeek-maalbeek', 'schuman', 'merode', 'montgomery', 'josephine-charlotte', 'gribaumont', 'tomberg', 'roodebeek', 'vandervelde', 'alma', 'crainhem-kraainem', 'stockel-stokkel'],
      ],
    },
    {
      id: '2',
      short: '2',
      name: 'Metro 2',
      colour: '#ed6c23',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['simonis', 'osseghem-ossegem', 'beekkant', 'gare-de-l-ouest-weststation', 'delacroix', 'clemenceau', 'gare-du-midi-zuidstation', 'porte-de-hal-hallepoort', 'hotel-des-monnaies-munthof', 'louise-louiza', 'porte-de-namur-naamsepoort', 'trone-troon', 'arts-loi-kunst-wet', 'madou', 'botanique-kruidtuin', 'rogier', 'yser-ijzer', 'ribaucourt', 'elisabeth'],
      ],
    },
    {
      id: '5',
      short: '5',
      name: 'Metro 5',
      colour: '#f6a90b',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['erasme-erasmus', 'eddy-merckx', 'ceria-coovi', 'la-roue-het-rad', 'bizet', 'veeweyde-veeweide', 'saint-guidon-sint-guido', 'aumale', 'jacques-brel', 'gare-de-l-ouest-weststation', 'beekkant', 'etangs-noirs-zwarte-vijvers', 'comte-de-flandre-graaf-van-vlaanderen', 'sainte-catherine-sint-katelijne', 'de-brouckere', 'gare-centrale-centraal-station', 'parc-park', 'arts-loi-kunst-wet', 'maelbeek-maalbeek', 'schuman', 'merode', 'thieffry', 'petillon', 'hankar', 'delta', 'beaulieu', 'demey', 'herrmann-debroux'],
      ],
    },
    {
      id: '6',
      short: '6',
      name: 'Metro 6',
      colour: '#0066a3',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['roi-baudouin-koning-boudewijn', 'heysel-heizel', 'houba-brugmann', 'stuyvenbergh', 'bockstael', 'pannenhuis', 'belgica', 'simonis', 'osseghem-ossegem', 'beekkant', 'gare-de-l-ouest-weststation', 'delacroix', 'clemenceau', 'gare-du-midi-zuidstation', 'porte-de-hal-hallepoort', 'hotel-des-monnaies-munthof', 'louise-louiza', 'porte-de-namur-naamsepoort', 'trone-troon', 'arts-loi-kunst-wet', 'madou', 'botanique-kruidtuin', 'rogier', 'yser-ijzer', 'ribaucourt', 'elisabeth'],
      ],
    },
  ],
  times: {
    'beekkant etangs-noirs-zwarte-vijvers': 2,
    'etangs-noirs-zwarte-vijvers comte-de-flandre-graaf-van-vlaanderen': 2,
    'comte-de-flandre-graaf-van-vlaanderen sainte-catherine-sint-katelijne': 2,
    'arts-loi-kunst-wet maelbeek-maalbeek': 2,
    'schuman merode': 3,
    'merode montgomery': 2,
    'tomberg roodebeek': 2,
    'roodebeek vandervelde': 2,
    'crainhem-kraainem stockel-stokkel': 2,
    'simonis osseghem-ossegem': 2,
    'delacroix clemenceau': 2,
    'clemenceau gare-du-midi-zuidstation': 2,
    'louise-louiza porte-de-namur-naamsepoort': 2,
    'yser-ijzer ribaucourt': 2,
    'ribaucourt elisabeth': 2,
    'la-roue-het-rad bizet': 1,
    'bizet veeweyde-veeweide': 1,
    'jacques-brel gare-de-l-ouest-weststation': 1,
    'gare-de-l-ouest-weststation beekkant': 1,
    'sainte-catherine-sint-katelijne de-brouckere': 1,
    'de-brouckere gare-centrale-centraal-station': 1,
    'gare-centrale-centraal-station parc-park': 1,
    'parc-park arts-loi-kunst-wet': 1,
    'maelbeek-maalbeek schuman': 1,
    'hankar delta': 1,
    'delta beaulieu': 1,
    'demey herrmann-debroux': 1,
    'heysel-heizel houba-brugmann': 2,
    'stuyvenbergh bockstael': 2,
    'bockstael pannenhuis': 2,
    'pannenhuis belgica': 2,
    'belgica simonis': 2,
  },
  stations: {
    'gare-de-l-ouest-weststation': { name: 'Gare de l\'Ouest - Weststation', x: 12.5, y: 16.5 },
    beekkant: { name: 'Beekkant', x: 14, y: 14.5 },
    'etangs-noirs-zwarte-vijvers': { name: 'Étangs Noirs - Zwarte Vijvers', x: 15.5, y: 13 },
    'comte-de-flandre-graaf-van-vlaanderen': { name: 'Comte de Flandre - Graaf van Vlaanderen', x: 17.5, y: 13 },
    'sainte-catherine-sint-katelijne': { name: 'Sainte-Catherine - Sint-Katelijne', x: 19, y: 14.5 },
    'de-brouckere': { name: 'De Brouckère', x: 20.5, y: 15.5 },
    'gare-centrale-centraal-station': { name: 'Gare Centrale - Centraal Station', x: 20.5, y: 17.5 },
    'parc-park': { name: 'Parc - Park', x: 23, y: 17.5 },
    'arts-loi-kunst-wet': { name: 'Arts-Loi - Kunst-Wet', x: 25, y: 17.5 },
    'maelbeek-maalbeek': { name: 'Maelbeek - Maalbeek', x: 26.5, y: 18.5 },
    schuman: { name: 'Schuman', x: 28.5, y: 18.5 },
    merode: { name: 'Merode', x: 30, y: 20 },
    montgomery: { name: 'Montgomery', x: 32, y: 20 },
    'josephine-charlotte': { name: 'Joséphine-Charlotte', x: 34, y: 20 },
    gribaumont: { name: 'Gribaumont', x: 35.5, y: 18.5 },
    tomberg: { name: 'Tomberg', x: 37.5, y: 18.5 },
    roodebeek: { name: 'Roodebeek', x: 39, y: 17 },
    vandervelde: { name: 'Vandervelde', x: 41, y: 17 },
    alma: { name: 'Alma', x: 42.5, y: 16 },
    'crainhem-kraainem': { name: 'Crainhem - Kraainem', x: 44.5, y: 16 },
    'stockel-stokkel': { name: 'Stockel - Stokkel', x: 46, y: 17.5 },
    'erasme-erasmus': { name: 'Erasme - Erasmus', x: 0, y: 27 },
    'eddy-merckx': { name: 'Eddy Merckx', x: 2, y: 27 },
    'ceria-coovi': { name: 'CERIA - COOVI', x: 4, y: 27 },
    'la-roue-het-rad': { name: 'La Roue - Het Rad', x: 5.5, y: 25.5 },
    bizet: { name: 'Bizet', x: 7, y: 24.5 },
    'veeweyde-veeweide': { name: 'Veeweyde - Veeweide', x: 8, y: 23 },
    'saint-guidon-sint-guido': { name: 'Saint-Guidon - Sint-Guido', x: 9.5, y: 21.5 },
    aumale: { name: 'Aumale', x: 11, y: 20 },
    'jacques-brel': { name: 'Jacques Brel', x: 12.5, y: 18.5 },
    thieffry: { name: 'Thieffry', x: 31.5, y: 21.5 },
    petillon: { name: 'Pétillon', x: 31.5, y: 23.5 },
    hankar: { name: 'Hankar', x: 31.5, y: 25.5 },
    delta: { name: 'Delta', x: 31.5, y: 27.5 },
    beaulieu: { name: 'Beaulieu', x: 33, y: 29 },
    demey: { name: 'Demey', x: 35, y: 29 },
    'herrmann-debroux': { name: 'Herrmann-Debroux', x: 37, y: 29 },
    simonis: { name: 'Simonis', x: 14, y: 10.5 },
    'osseghem-ossegem': { name: 'Osseghem - Ossegem', x: 14, y: 12.5 },
    delacroix: { name: 'Delacroix', x: 14, y: 18 },
    clemenceau: { name: 'Clemenceau', x: 15, y: 19.5 },
    'gare-du-midi-zuidstation': { name: 'Gare du Midi - Zuidstation', x: 16.5, y: 21 },
    'porte-de-hal-hallepoort': { name: 'Porte de Hal - Hallepoort', x: 18, y: 22.5 },
    'hotel-des-monnaies-munthof': { name: 'Hôtel des Monnaies - Munthof', x: 19.5, y: 22.5 },
    'louise-louiza': { name: 'Louise - Louiza', x: 21, y: 21 },
    'porte-de-namur-naamsepoort': { name: 'Porte de Namur - Naamsepoort', x: 22.5, y: 20 },
    'trone-troon': { name: 'Trône - Troon', x: 23.5, y: 18.5 },
    madou: { name: 'Madou', x: 25, y: 15.5 },
    'botanique-kruidtuin': { name: 'Botanique - Kruidtuin', x: 23.5, y: 14 },
    rogier: { name: 'Rogier', x: 21.5, y: 14 },
    'yser-ijzer': { name: 'Yser - IJzer', x: 20, y: 12.5 },
    ribaucourt: { name: 'Ribaucourt', x: 18.5, y: 11 },
    elisabeth: { name: 'Elisabeth', x: 16.5, y: 11 },
    'roi-baudouin-koning-boudewijn': { name: 'Roi Baudouin - Koning Boudewijn', x: 13.5, y: 0 },
    'heysel-heizel': { name: 'Heysel - Heizel', x: 15.5, y: 0 },
    'houba-brugmann': { name: 'Houba-Brugmann', x: 15.5, y: 2 },
    stuyvenbergh: { name: 'Stuyvenbergh', x: 17, y: 3.5 },
    bockstael: { name: 'Bockstael', x: 17, y: 5.5 },
    pannenhuis: { name: 'Pannenhuis', x: 17, y: 7.5 },
    belgica: { name: 'Belgica', x: 15.5, y: 9 },
  },
};
