// Budapest's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'budapest',
  name: 'Budapest',
  system: 'Metro',
  country: 'Hungary',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'm1',
      short: 'M1',
      name: 'Millenniumi Földalatti Vasút',
      colour: '#ffd800',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['vorosmarty-ter', 'deak-ferenc-ter', 'bajcsy-zsilinszky-ut', 'opera', 'oktogon', 'vorosmarty-utca', 'kodaly-korond', 'bajza-utca', 'hosok-tere', 'szechenyi-furdo', 'mexikoi-ut'],
      ],
    },
    {
      id: 'm2',
      short: 'M2',
      name: 'M2',
      colour: '#e41f18',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['deli-palyaudvar', 'szell-kalman-ter', 'batthyany-ter', 'kossuth-lajos-ter', 'deak-ferenc-ter', 'astoria', 'blaha-lujza-ter', 'keleti-palyaudvar', 'puskas-ferenc-stadion', 'pillango-utca', 'ors-vezer-tere'],
      ],
    },
    {
      id: 'm3',
      short: 'M3',
      name: 'M3',
      colour: '#005ca5',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['kobanya-kispest', 'hatar-ut', 'pottyos-utca', 'ecseri-ut', 'nepliget', 'nagyvarad-ter', 'semmelweis-klinikak', 'corvin-negyed', 'kalvin-ter', 'ferenciek-tere', 'deak-ferenc-ter', 'arany-janos-utca', 'nyugati-palyaudvar', 'lehel-ter', 'dozsa-gyorgy-ut', 'goncz-arpad-varoskozpont', 'forgach-utca', 'gyongyosi-utca', 'ujpest-varoskapu', 'ujpest-kozpont'],
      ],
    },
    {
      id: 'm4',
      short: 'M4',
      name: 'M4',
      colour: '#4ca22f',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['kelenfold-vasutallomas', 'bikas-park', 'ujbuda-kozpont', 'moricz-zsigmond-korter', 'szent-gellert-ter-muegyetem', 'fovam-ter', 'kalvin-ter', 'rakoczi-ter', 'ii-janos-pal-papa-ter', 'keleti-palyaudvar'],
      ],
    },
  ],
  times: {
    'szechenyi-furdo mexikoi-ut': 2,
    'batthyany-ter kossuth-lajos-ter': 1,
    'keleti-palyaudvar puskas-ferenc-stadion': 4,
    'pillango-utca ors-vezer-tere': 3,
    'kobanya-kispest hatar-ut': 4,
    'semmelweis-klinikak corvin-negyed': 1,
    'kalvin-ter ferenciek-tere': 1,
    'forgach-utca gyongyosi-utca': 3,
    'gyongyosi-utca ujpest-varoskapu': 3,
    'kelenfold-vasutallomas bikas-park': 2,
    'bikas-park ujbuda-kozpont': 3,
    'moricz-zsigmond-korter szent-gellert-ter-muegyetem': 2,
    'kalvin-ter rakoczi-ter': 2,
  },
  stations: {
    'vorosmarty-ter': { name: 'Vörösmarty tér', x: 4.5, y: 18.5 },
    'deak-ferenc-ter': { name: 'Deák Ferenc tér', x: 6, y: 17 },
    'bajcsy-zsilinszky-ut': { name: 'Bajcsy-Zsilinszky út', x: 5, y: 16 },
    opera: { name: 'Opera', x: 7, y: 16 },
    oktogon: { name: 'Oktogon', x: 7, y: 14 },
    'vorosmarty-utca': { name: 'Vörösmarty utca', x: 8.5, y: 15.5 },
    'kodaly-korond': { name: 'Kodály körönd', x: 8.5, y: 13.5 },
    'bajza-utca': { name: 'Bajza utca', x: 10, y: 15 },
    'hosok-tere': { name: 'Hősök tere', x: 10, y: 13 },
    'szechenyi-furdo': { name: 'Széchenyi fürdő', x: 11.5, y: 11.5 },
    'mexikoi-ut': { name: 'Mexikói út', x: 13.5, y: 11.5 },
    'deli-palyaudvar': { name: 'Déli pályaudvar', x: 0.5, y: 16 },
    'szell-kalman-ter': { name: 'Széll Kálmán tér', x: 0.5, y: 14 },
    'batthyany-ter': { name: 'Batthyány tér', x: 2.5, y: 14 },
    'kossuth-lajos-ter': { name: 'Kossuth Lajos tér', x: 4, y: 15.5 },
    astoria: { name: 'Astoria', x: 8, y: 17 },
    'blaha-lujza-ter': { name: 'Blaha Lujza tér', x: 10, y: 17 },
    'keleti-palyaudvar': { name: 'Keleti pályaudvar', x: 12.5, y: 17 },
    'puskas-ferenc-stadion': { name: 'Puskás Ferenc Stadion', x: 14.5, y: 17 },
    'pillango-utca': { name: 'Pillangó utca', x: 16.5, y: 17 },
    'ors-vezer-tere': { name: 'Örs vezér tere', x: 18.5, y: 17 },
    'kobanya-kispest': { name: 'Kőbánya-Kispest', x: 21, y: 28 },
    'hatar-ut': { name: 'Határ út', x: 18.5, y: 28 },
    'pottyos-utca': { name: 'Pöttyös utca', x: 16.5, y: 28 },
    'ecseri-ut': { name: 'Ecseri út', x: 15, y: 26.5 },
    nepliget: { name: 'Népliget', x: 13.5, y: 25 },
    'nagyvarad-ter': { name: 'Nagyvárad tér', x: 12, y: 23.5 },
    'semmelweis-klinikak': { name: 'Semmelweis Klinikák', x: 10.5, y: 22.5 },
    'corvin-negyed': { name: 'Corvin-negyed', x: 9, y: 21 },
    'kalvin-ter': { name: 'Kálvin tér', x: 7.5, y: 19.5 },
    'ferenciek-tere': { name: 'Ferenciek tere', x: 6, y: 19.5 },
    'arany-janos-utca': { name: 'Arany János utca', x: 5.5, y: 15 },
    'nyugati-palyaudvar': { name: 'Nyugati pályaudvar', x: 6, y: 13 },
    'lehel-ter': { name: 'Lehel tér', x: 6, y: 11 },
    'dozsa-gyorgy-ut': { name: 'Dózsa György út', x: 6, y: 9 },
    'goncz-arpad-varoskozpont': { name: 'Göncz Árpád városközpont', x: 6, y: 7 },
    'forgach-utca': { name: 'Forgách utca', x: 6.5, y: 5 },
    'gyongyosi-utca': { name: 'Gyöngyösi utca', x: 6.5, y: 3 },
    'ujpest-varoskapu': { name: 'Újpest-városkapu', x: 8, y: 1.5 },
    'ujpest-kozpont': { name: 'Újpest-központ', x: 9.5, y: 0 },
    'kelenfold-vasutallomas': { name: 'Kelenföld vasútállomás', x: 0, y: 27 },
    'bikas-park': { name: 'Bikás park', x: 2, y: 27 },
    'ujbuda-kozpont': { name: 'Újbuda-központ', x: 3.5, y: 25.5 },
    'moricz-zsigmond-korter': { name: 'Móricz Zsigmond körtér', x: 5, y: 24.5 },
    'szent-gellert-ter-muegyetem': { name: 'Szent Gellért tér – Műegyetem', x: 6.5, y: 23 },
    'fovam-ter': { name: 'Fővám tér', x: 6.5, y: 21 },
    'rakoczi-ter': { name: 'Rákóczi tér', x: 9, y: 18.5 },
    'ii-janos-pal-papa-ter': { name: 'II. János Pál pápa tér', x: 11, y: 18.5 },
  },
};
