// Busan's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'busan',
  name: 'Busan',
  system: 'Metro',
  country: 'South Korea',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Busan Metro Line 1',
      colour: '#f06a00',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['nopo', 'beomeosa', 'namsan', 'dusil', 'guseo', 'jangjeon', 'pusan-nat-l-univ', 'oncheonjan', 'myeongnyun', 'dongnae', 'busan-national-university-of-education', 'yeonsan', 'city-hall', 'yangjeong', 'bujeon', 'seomyeon', 'beomnaegol', 'beomil', 'jwacheon', 'busanjin', 'choryang', 'busan', 'jungang', 'nampo', 'jagalchi', 'toseong', 'dongdaesin', 'seodaesin', 'daeti', 'goejeong', 'saha', 'dangni', 'hadan', 'sinpyeong', 'dongmae', 'jangnim', 'sinjangnim', 'natgae', 'dadaepo-harbor', 'dadaepo-beach'],
      ],
    },
    {
      id: '2',
      short: '2',
      name: 'Busan Metro Line 2 (Green Line)',
      colour: '#81bf48',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['jangsan', 'jung-dong', 'haeundae', 'dongbaek', 'bexco', 'centum-city', 'millak', 'suyeong', 'gwangan', 'geumryeonsan', 'namcheon', 'kyungsung-univ-pukyong-nat-l-univ', 'daeyeon', 'motgol', 'jigegol', 'munhyeon', 'busan-international-finance-center-busan-bank', 'jeonpo', 'seomyeon', 'buam', 'gaya', 'dong-eui-university', 'gaegeum', 'naengjeong', 'jurye', 'gamjeon', 'sasang', 'deokpo', 'modeok', 'mora', 'gunam', 'gumyeong', 'deokcheon', 'sujeong', 'hwamyeong', 'yulli', 'dongwon', 'geumgok', 'hopo', 'jeungsan', 'pusan-nat-l-univ-yangsan-campus', 'namyangsan', 'yangsan'],
      ],
    },
    {
      id: '3',
      short: '3',
      name: 'Busan Metro Line 3 (Brown Line)',
      colour: '#bb8c00',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['suyeong', 'mangmi', 'baesan', 'mulmangol', 'yeonsan', 'geoje', 'sports-complex', 'sajik', 'minam', 'mandeok', 'namsanjeong', 'sukdeung', 'deokcheon', 'gupo', 'gangseo-office', 'sports-park', 'daejeo'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'Line 4 (Blue Line)',
      colour: '#217dcb',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['minam', 'dongnae', 'suan', 'nakmin', 'chungryeolsa', 'myeongjang', 'seo-dong', 'geumsa', 'banyeo-agricultural-market', 'seokdae', 'youngsan-university', 'witbansong', 'gochon', 'anpyeong'],
      ],
    },
    {
      id: 'bgl',
      short: 'BGL',
      name: 'Busan–Gimhae Light Rail Transit',
      colour: '#8652a1',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['sasang', 'gwaebeop-renecite', 'seobusan-yutongjigu', 'gimhae-international-airport', 'deokdu', 'deunggu', 'daejeo', 'pyeonggang', 'daesa', 'buram', 'jinae', 'gimhae-college', 'inje-university', 'gimhae-city-hall', 'buwon', 'bonghwang', 'royal-tomb-of-king-suro', 'gimhae-national-museum', 'yeonji-park', 'presbyterian-university', 'kaya-university'],
      ],
    },
  ],
  times: {
    'nopo beomeosa': 3,
    'yangjeong bujeon': 3,
    'seomyeon beomnaegol': 3,
    'busan jungang': 3,
    'dongdaesin seodaesin': 1,
    'seodaesin daeti': 3,
    'hadan sinpyeong': 3,
    'sinpyeong dongmae': 3,
    'natgae dadaepo-harbor': 3,
    'dadaepo-harbor dadaepo-beach': 3,
    'dongbaek bexco': 3,
    'jurye gamjeon': 3,
    'sasang deokpo': 3,
    'deokcheon sujeong': 3,
    'sujeong hwamyeong': 3,
    'hwamyeong yulli': 3,
    'yulli dongwon': 3,
    'geumgok hopo': 3,
    'hopo jeungsan': 6,
    'namyangsan yangsan': 3,
    'mulmangol yeonsan': 3,
    'minam mandeok': 6,
    'mandeok namsanjeong': 3,
    'gupo gangseo-office': 3,
    'gangseo-office sports-park': 3,
    'banyeo-agricultural-market seokdae': 3,
    'seokdae youngsan-university': 3,
    'gwaebeop-renecite seobusan-yutongjigu': 4,
    'gimhae-international-airport deokdu': 3,
    'deokdu deunggu': 4,
    'deunggu daejeo': 4,
    'pyeonggang daesa': 3,
    'gimhae-college inje-university': 3,
    'yeonji-park presbyterian-university': 3,
  },
  stations: {
    jangsan: { name: 'Jangsan', x: 58.5, y: 33.5, aka: ['장산'] },
    'jung-dong': { name: 'Jung-dong', x: 57.5, y: 34.5, aka: ['중동'] },
    haeundae: { name: 'Haeundae', x: 55.5, y: 34.5, aka: ['해운대'] },
    dongbaek: { name: 'Dongbaek', x: 53, y: 34.5, aka: ['동백'] },
    bexco: { name: 'BEXCO', x: 52, y: 33.5, aka: ['벡스코'] },
    'centum-city': { name: 'Centum City', x: 50, y: 33.5, aka: ['센텀시티'] },
    millak: { name: 'Millak', x: 48, y: 33.5, aka: ['민락'] },
    suyeong: { name: 'Suyeong', x: 46, y: 33.5, aka: ['수영'] },
    gwangan: { name: 'Gwangan', x: 46, y: 35.5, aka: ['광안'] },
    geumryeonsan: { name: 'Geumryeonsan', x: 46, y: 37.5, aka: ['금련산'] },
    namcheon: { name: 'Namcheon', x: 46, y: 39.5, aka: ['남천'] },
    'kyungsung-univ-pukyong-nat-l-univ': { name: 'Kyungsung Univ. · Pukyong Nat\'l Univ.', x: 44.5, y: 41, aka: ['경성대·부경대'] },
    daeyeon: { name: 'Daeyeon', x: 42.5, y: 41, aka: ['대연'] },
    motgol: { name: 'Motgol', x: 40.5, y: 41, aka: ['못골'] },
    jigegol: { name: 'Jigegol', x: 38.5, y: 41.5, aka: ['지게골'] },
    munhyeon: { name: 'Munhyeon', x: 37, y: 40, aka: ['문현'] },
    'busan-international-finance-center-busan-bank': { name: 'Busan International Finance Center·Busan Bank', x: 37, y: 38, aka: ['국제금융센터·부산은행'] },
    jeonpo: { name: 'Jeonpo', x: 37, y: 36, aka: ['전포'] },
    seomyeon: { name: 'Seomyeon', x: 35.5, y: 35, aka: ['서면'] },
    buam: { name: 'Buam', x: 34, y: 35, aka: ['부암'] },
    gaya: { name: 'Gaya', x: 32, y: 35, aka: ['가야'] },
    'dong-eui-university': { name: 'Dong-Eui University', x: 30, y: 35, aka: ['동의대'] },
    gaegeum: { name: 'Gaegeum', x: 28.5, y: 35, aka: ['개금'] },
    naengjeong: { name: 'Naengjeong', x: 26.5, y: 35.5, aka: ['냉정'] },
    jurye: { name: 'Jurye', x: 24.5, y: 35.5, aka: ['주례'] },
    gamjeon: { name: 'Gamjeon', x: 23.5, y: 34, aka: ['감전'] },
    sasang: { name: 'Sasang', x: 22, y: 32.5, aka: ['사상'] },
    deokpo: { name: 'Deokpo', x: 22, y: 31, aka: ['덕포'] },
    modeok: { name: 'Modeok', x: 22.5, y: 29, aka: ['모덕'] },
    mora: { name: 'Mora', x: 22.5, y: 27, aka: ['모라'] },
    gunam: { name: 'Gunam', x: 24, y: 25.5, aka: ['구남'] },
    gumyeong: { name: 'Gumyeong', x: 25.5, y: 24, aka: ['구명'] },
    deokcheon: { name: 'Deokcheon', x: 26.5, y: 22.5, aka: ['덕천'] },
    sujeong: { name: 'Sujeong', x: 26.5, y: 20, aka: ['수정'] },
    hwamyeong: { name: 'Hwamyeong', x: 26.5, y: 18, aka: ['화명'] },
    yulli: { name: 'Yulli', x: 26.5, y: 15.5, aka: ['율리'] },
    dongwon: { name: 'Dongwon', x: 26.5, y: 13, aka: ['동원'] },
    geumgok: { name: 'Geumgok', x: 26.5, y: 11, aka: ['금곡'] },
    hopo: { name: 'Hopo', x: 27, y: 8.5, aka: ['호포'] },
    jeungsan: { name: 'Jeungsan', x: 27, y: 6.5, aka: ['증산'] },
    'pusan-nat-l-univ-yangsan-campus': { name: 'Pusan Nat\'l Univ. Yangsan Campus', x: 27, y: 4, aka: ['부산대양산캠퍼스'] },
    namyangsan: { name: 'Namyangsan', x: 27, y: 2, aka: ['남양산'] },
    yangsan: { name: 'Yangsan', x: 27, y: 0, aka: ['양산'] },
    mangmi: { name: 'Mangmi', x: 44.5, y: 32, aka: ['망미'] },
    baesan: { name: 'Baesan', x: 42, y: 32, aka: ['배산'] },
    mulmangol: { name: 'Mulmangol', x: 41, y: 30.5, aka: ['물만골'] },
    yeonsan: { name: 'Yeonsan', x: 40.5, y: 28.5, aka: ['연산'] },
    geoje: { name: 'Geoje', x: 38.5, y: 28.5, aka: ['거제'] },
    'sports-complex': { name: 'Sports Complex', x: 37, y: 27, aka: ['종합운동장'] },
    sajik: { name: 'Sajik', x: 37, y: 25.5, aka: ['사직'] },
    minam: { name: 'Minam', x: 36, y: 24, aka: ['미남'] },
    mandeok: { name: 'Mandeok', x: 33.5, y: 23.5, aka: ['만덕'] },
    namsanjeong: { name: 'Namsanjeong', x: 31, y: 23, aka: ['남산정'] },
    sukdeung: { name: 'Sukdeung', x: 29, y: 23, aka: ['숙등'] },
    gupo: { name: 'Gupo', x: 24, y: 24, aka: ['구포'] },
    'gangseo-office': { name: 'Gangseo Office', x: 22, y: 24, aka: ['강서구청'] },
    'sports-park': { name: 'Sports Park', x: 19.5, y: 24.5, aka: ['체육공원'] },
    daejeo: { name: 'Daejeo', x: 17, y: 24.5, aka: ['대저'] },
    nopo: { name: 'Nopo', x: 41.5, y: 7, aka: ['노포'] },
    beomeosa: { name: 'Beomeosa', x: 41.5, y: 9, aka: ['범어사'] },
    namsan: { name: 'Namsan', x: 41.5, y: 11, aka: ['남산'] },
    dusil: { name: 'Dusil', x: 41.5, y: 13, aka: ['두실'] },
    guseo: { name: 'Guseo', x: 41.5, y: 15, aka: ['구서'] },
    jangjeon: { name: 'Jangjeon', x: 41.5, y: 17, aka: ['장전'] },
    'pusan-nat-l-univ': { name: 'Pusan Nat\'l Univ.', x: 41.5, y: 19, aka: ['부산대'] },
    oncheonjan: { name: 'Oncheonjan', x: 41.5, y: 21, aka: ['온천장'] },
    myeongnyun: { name: 'Myeongnyun', x: 40, y: 22.5, aka: ['명륜'] },
    dongnae: { name: 'Dongnae', x: 38.5, y: 24, aka: ['동래'] },
    'busan-national-university-of-education': { name: 'Busan National University of Education', x: 40, y: 26, aka: ['교대'] },
    'city-hall': { name: 'City Hall', x: 39, y: 30, aka: ['시청'] },
    yangjeong: { name: 'Yangjeong', x: 38, y: 31.5, aka: ['양정'] },
    bujeon: { name: 'Bujeon', x: 37, y: 33, aka: ['부전'] },
    beomnaegol: { name: 'Beomnaegol', x: 35.5, y: 37, aka: ['범내골'] },
    beomil: { name: 'Beomil', x: 35.5, y: 39, aka: ['범일'] },
    jwacheon: { name: 'Jwacheon', x: 34.5, y: 40.5, aka: ['좌천'] },
    busanjin: { name: 'Busanjin', x: 33, y: 42, aka: ['부산진'] },
    choryang: { name: 'Choryang', x: 31.5, y: 43.5, aka: ['초량'] },
    busan: { name: 'Busan', x: 31.5, y: 45.5, aka: ['부산'] },
    jungang: { name: 'Jungang', x: 31.5, y: 47.5, aka: ['중앙'] },
    nampo: { name: 'Nampo', x: 31.5, y: 50, aka: ['남포'] },
    jagalchi: { name: 'Jagalchi', x: 29.5, y: 50, aka: ['자갈치'] },
    toseong: { name: 'Toseong', x: 28, y: 48.5, aka: ['토성'] },
    dongdaesin: { name: 'Dongdaesin', x: 28, y: 46.5, aka: ['동대신'] },
    seodaesin: { name: 'Seodaesin', x: 26, y: 46.5, aka: ['서대신'] },
    daeti: { name: 'Daeti', x: 24.5, y: 48, aka: ['대티'] },
    goejeong: { name: 'Goejeong', x: 23, y: 49.5, aka: ['괴정'] },
    saha: { name: 'Saha', x: 21, y: 49.5, aka: ['사하'] },
    dangni: { name: 'Dangni', x: 19.5, y: 48, aka: ['당리'] },
    hadan: { name: 'Hadan', x: 17.5, y: 48, aka: ['하단'] },
    sinpyeong: { name: 'Sinpyeong', x: 17.5, y: 50.5, aka: ['신평'] },
    dongmae: { name: 'Dongmae', x: 19, y: 51.5, aka: ['동매'] },
    jangnim: { name: 'Jangnim', x: 20.5, y: 53, aka: ['장림'] },
    sinjangnim: { name: 'Sinjangnim', x: 20.5, y: 55, aka: ['신장림'] },
    natgae: { name: 'Natgae', x: 20.5, y: 57, aka: ['낫개'] },
    'dadaepo-harbor': { name: 'Dadaepo Harbor', x: 19, y: 58.5, aka: ['다대포항'] },
    'dadaepo-beach': { name: 'Dadaepo Beach', x: 17.5, y: 60, aka: ['다대포해수욕장'] },
    'gwaebeop-renecite': { name: 'Gwaebeop Renecite', x: 20, y: 32.5, aka: ['괘법르네시떼'] },
    'seobusan-yutongjigu': { name: 'Seobusan Yutongjigu', x: 18, y: 32.5, aka: ['서부산유통지구'] },
    'gimhae-international-airport': { name: 'Gimhae International Airport', x: 17, y: 31, aka: ['공항'] },
    deokdu: { name: 'Deokdu', x: 17, y: 28.5, aka: ['덕두'] },
    deunggu: { name: 'Deunggu', x: 17, y: 26.5, aka: ['등구'] },
    pyeonggang: { name: 'Pyeonggang', x: 15.5, y: 23, aka: ['평강'] },
    daesa: { name: 'Daesa', x: 14, y: 21.5, aka: ['대사'] },
    buram: { name: 'Buram', x: 12.5, y: 20.5, aka: ['불암'] },
    jinae: { name: 'Jinae', x: 11, y: 19, aka: ['지내'] },
    'gimhae-college': { name: 'Gimhae College', x: 8.5, y: 19, aka: ['김해대학'] },
    'inje-university': { name: 'Inje University', x: 6.5, y: 19, aka: ['인제대'] },
    'gimhae-city-hall': { name: 'Gimhae City Hall', x: 4.5, y: 19, aka: ['김해시청'] },
    buwon: { name: 'Buwon', x: 2.5, y: 19, aka: ['부원'] },
    bonghwang: { name: 'Bonghwang', x: 0, y: 19, aka: ['봉황'] },
    'royal-tomb-of-king-suro': { name: 'Royal Tomb of King Suro', x: 0, y: 17, aka: ['수로왕릉'] },
    'gimhae-national-museum': { name: 'Gimhae National Museum', x: 0, y: 15, aka: ['박물관'] },
    'yeonji-park': { name: 'Yeonji Park', x: 0, y: 13, aka: ['연지공원'] },
    'presbyterian-university': { name: 'Presbyterian University', x: 0, y: 11, aka: ['장신대'] },
    'kaya-university': { name: 'Kaya University', x: 0, y: 9, aka: ['가야대'] },
    suan: { name: 'Suan', x: 40.5, y: 24, aka: ['수안'] },
    nakmin: { name: 'Nakmin', x: 42.5, y: 24.5, aka: ['낙민'] },
    chungryeolsa: { name: 'Chungryeolsa', x: 44, y: 24.5, aka: ['충렬사'] },
    myeongjang: { name: 'Myeongjang', x: 44, y: 22.5, aka: ['명장'] },
    'seo-dong': { name: 'Seo-dong', x: 45.5, y: 21, aka: ['서동'] },
    geumsa: { name: 'Geumsa', x: 47.5, y: 21, aka: ['금사'] },
    'banyeo-agricultural-market': { name: 'Banyeo Agricultural Market', x: 49.5, y: 21, aka: ['반여농산물시장'] },
    seokdae: { name: 'Seokdae', x: 51.5, y: 21, aka: ['석대'] },
    'youngsan-university': { name: 'Youngsan University', x: 53, y: 19.5, aka: ['영신대'] },
    witbansong: { name: 'Witbansong', x: 54.5, y: 18, aka: ['윗반송'] },
    gochon: { name: 'Gochon', x: 56, y: 17, aka: ['고촌'] },
    anpyeong: { name: 'Anpyeong', x: 58, y: 17, aka: ['안평'] },
  },
};
