// Calgary's CTrain, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'calgary',
  name: 'Calgary',
  system: 'CTrain',
  country: 'Canada',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '201',
      short: '201',
      name: 'CTrain Red Line',
      colour: '#e3000f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['tuscany', 'crowfoot', 'dalhousie', 'brentwood', 'university', 'banff-trail', 'lions-park', 'sait-auarts-jubilee', 'sunnyside', 's-8-street-southwest', 's-6-street-southwest', 's-3-street-southwest', 'centre-street', 'city-hall-bow-valley-college', 'victoria-park-stampede', 'erlton-stampede', 's-39-avenue', 'chinook', 'heritage', 'southland', 'anderson', 'canyon-meadows', 'fish-creek-lacombe', 'shawnessy', 'somerset-bridlewood'],
        ['somerset-bridlewood', 'shawnessy', 'fish-creek-lacombe', 'canyon-meadows', 'anderson', 'southland', 'heritage', 'chinook', 's-39-avenue', 'erlton-stampede', 'victoria-park-stampede', 'city-hall-bow-valley-college', 's-1-street-southwest', 's-4-street-southwest', 's-7-street-southwest', 'sunnyside', 'sait-auarts-jubilee', 'lions-park', 'banff-trail', 'university', 'brentwood', 'dalhousie', 'crowfoot', 'tuscany'],
      ],
    },
    {
      id: '202',
      short: '202',
      name: 'CTrain Blue Line',
      colour: '#0065bd',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['s-69-street', 'sirocco', 's-45-street', 'westbrook', 'shaganappi-point', 'sunalta', 'downtown-west-kerby', 's-8-street-southwest', 's-6-street-southwest', 's-3-street-southwest', 'centre-street', 'city-hall-bow-valley-college', 'bridgeland-memorial', 'zoo', 'barlow-max-bell', 'franklin', 'marlborough', 'rundle', 'whitehorn', 'mcknight-westwinds', 'martindale', 'saddletowne'],
        ['saddletowne', 'martindale', 'mcknight-westwinds', 'whitehorn', 'rundle', 'marlborough', 'franklin', 'barlow-max-bell', 'zoo', 'bridgeland-memorial', 'city-hall-bow-valley-college', 's-1-street-southwest', 's-4-street-southwest', 's-7-street-southwest', 'downtown-west-kerby', 'sunalta', 'shaganappi-point', 'westbrook', 's-45-street', 'sirocco', 's-69-street'],
      ],
    },
  ],
  times: {
    'tuscany crowfoot': 5,
    'crowfoot dalhousie': 8,
    'dalhousie brentwood': 6,
    'university banff-trail': 3,
    's-8-street-southwest s-6-street-southwest': 1,
    's-6-street-southwest s-3-street-southwest': 1,
    's-3-street-southwest centre-street': 1,
    'centre-street city-hall-bow-valley-college': 1,
    'erlton-stampede s-39-avenue': 3,
    's-39-avenue chinook': 5,
    'chinook heritage': 5,
    'heritage southland': 3,
    'anderson canyon-meadows': 5,
    'canyon-meadows fish-creek-lacombe': 3,
    'fish-creek-lacombe shawnessy': 3,
    'shawnessy somerset-bridlewood': 3,
    'somerset-bridlewood shawnessy': 3,
    'shawnessy fish-creek-lacombe': 3,
    'fish-creek-lacombe canyon-meadows': 3,
    'canyon-meadows anderson': 5,
    'southland heritage': 3,
    'heritage chinook': 5,
    'chinook s-39-avenue': 5,
    's-39-avenue erlton-stampede': 3,
    'city-hall-bow-valley-college s-1-street-southwest': 1,
    's-4-street-southwest s-7-street-southwest': 1,
    's-7-street-southwest sunnyside': 3,
    'banff-trail university': 3,
    'brentwood dalhousie': 6,
    'dalhousie crowfoot': 8,
    'crowfoot tuscany': 5,
    'sirocco s-45-street': 2,
    'westbrook shaganappi-point': 2,
    'shaganappi-point sunalta': 4,
    'sunalta downtown-west-kerby': 2,
    'downtown-west-kerby s-8-street-southwest': 1,
    'barlow-max-bell franklin': 2,
    'marlborough rundle': 4,
    'whitehorn mcknight-westwinds': 5,
    'mcknight-westwinds martindale': 2,
    'martindale mcknight-westwinds': 2,
    'mcknight-westwinds whitehorn': 5,
    'rundle marlborough': 4,
    'franklin barlow-max-bell': 2,
    's-1-street-southwest s-4-street-southwest': 2,
    's-7-street-southwest downtown-west-kerby': 2,
    'downtown-west-kerby sunalta': 2,
    'sunalta shaganappi-point': 4,
    'shaganappi-point westbrook': 2,
    's-45-street sirocco': 2,
  },
  stations: {
    's-69-street': { name: '69 Street', x: 0, y: 14 },
    sirocco: { name: 'Sirocco', x: 2, y: 14 },
    's-45-street': { name: '45 Street', x: 4, y: 14 },
    westbrook: { name: 'Westbrook', x: 6, y: 14 },
    'shaganappi-point': { name: 'Shaganappi Point', x: 8, y: 13.5 },
    sunalta: { name: 'Sunalta', x: 10, y: 13.5 },
    'downtown-west-kerby': { name: 'Downtown West–Kerby', x: 11, y: 12.5 },
    's-8-street-southwest': { name: '8 Street Southwest', x: 12.5, y: 13.5 },
    's-6-street-southwest': { name: '6 Street Southwest', x: 14, y: 11.5 },
    's-3-street-southwest': { name: '3 Street Southwest', x: 14.5, y: 13.5 },
    'centre-street': { name: 'Centre Street', x: 16.5, y: 13.5 },
    'city-hall-bow-valley-college': { name: 'City Hall/Bow Valley College', x: 17.5, y: 15 },
    'bridgeland-memorial': { name: 'Bridgeland/Memorial', x: 19, y: 13.5 },
    zoo: { name: 'Zoo', x: 21, y: 13 },
    'barlow-max-bell': { name: 'Barlow/Max Bell', x: 23, y: 13 },
    franklin: { name: 'Franklin', x: 24.5, y: 11.5 },
    marlborough: { name: 'Marlborough', x: 26, y: 10 },
    rundle: { name: 'Rundle', x: 26, y: 8 },
    whitehorn: { name: 'Whitehorn', x: 26, y: 6 },
    'mcknight-westwinds': { name: 'McKnight-Westwinds', x: 26, y: 4 },
    martindale: { name: 'Martindale', x: 27.5, y: 2.5 },
    saddletowne: { name: 'Saddletowne', x: 29, y: 1 },
    'somerset-bridlewood': { name: 'Somerset–Bridlewood', x: 16, y: 38 },
    shawnessy: { name: 'Shawnessy', x: 16, y: 36 },
    'fish-creek-lacombe': { name: 'Fish Creek–Lacombe', x: 16, y: 34 },
    'canyon-meadows': { name: 'Canyon Meadows', x: 16, y: 32 },
    anderson: { name: 'Anderson', x: 16, y: 29.5 },
    southland: { name: 'Southland', x: 16, y: 27.5 },
    heritage: { name: 'Heritage', x: 16, y: 25.5 },
    chinook: { name: 'Chinook', x: 16, y: 23 },
    's-39-avenue': { name: '39 Avenue', x: 16, y: 21 },
    'erlton-stampede': { name: 'Erlton/Stampede', x: 16, y: 18.5 },
    'victoria-park-stampede': { name: 'Victoria Park/Stampede', x: 16, y: 16.5 },
    's-1-street-southwest': { name: '1 Street Southwest', x: 15.5, y: 15 },
    's-4-street-southwest': { name: '4 Street Southwest', x: 15.5, y: 12.5 },
    's-7-street-southwest': { name: '7 Street Southwest', x: 13.5, y: 12.5 },
    sunnyside: { name: 'Sunnyside', x: 12, y: 11 },
    'sait-auarts-jubilee': { name: 'SAIT/AUArts/Jubilee', x: 12, y: 9 },
    'lions-park': { name: 'Lions Park', x: 10, y: 9 },
    'banff-trail': { name: 'Banff Trail', x: 8.5, y: 7.5 },
    university: { name: 'University', x: 7, y: 6 },
    brentwood: { name: 'Brentwood', x: 5.5, y: 4.5 },
    dalhousie: { name: 'Dalhousie', x: 4, y: 3 },
    crowfoot: { name: 'Crowfoot', x: 2.5, y: 1.5 },
    tuscany: { name: 'Tuscany', x: 1, y: 0 },
  },
};
