// Köln's Stadtbahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'cologne',
  name: 'Köln',
  system: 'Stadtbahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Linie 1',
      colour: '#d52330',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['weiden-west', 'weiden-romergrab', 'weiden-zentrum', 'bahnstrasse', 'mohnweg', 'junkersdorf', 'rheinenergie-stadion', 'alter-militarring', 'eupener-strasse', 'clarenbachstift', 'maarweg', 'aachener-strasse-gurtel', 'melaten', 'universitatsstrasse', 'moltkestrasse', 'rudolfplatz', 'neumarkt', 'heumarkt', 'deutzer-freiheit', 'bf-deutz-messe', 'deutz-technische-hochschule', 'kalk-post', 'kalk-kapelle', 'fuldaer-strasse', 'sportpark-hohenberg', 'kalker-friedhof', 'merheim', 'flehbachstrasse', 'bruck-mauspfad', 'lustheide', 'refrath', 'kippekausen', 'frankenforst', 'neuenweg', 'kolner-strasse', 'im-hoppenkamp', 'bensberg-u'],
      ],
    },
    {
      id: '3',
      short: '3',
      name: 'Linie 3',
      colour: '#e693b5',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['gorlinger-zentrum', 'ollenhauerring', 'schaffrathsgasse', 'bocklemund', 'westfriedhof', 'wolffsohnstrasse', 'akazienweg', 'rochusplatz', 'leyendeckerstrasse', 'venloer-strasse-gurtel', 'kornerstrasse', 'piusstrasse', 'hans-bockler-platz-bf-west', 'friesenplatz', 'appellhofplatz', 'neumarkt', 'poststrasse', 'severinstrasse', 'suevenstrasse', 'bahnhof-deutz-lanxess-arena', 'koelnmesse', 'stegerwaldsiedlung', 'waldecker-strasse', 'buchheim-frankfurter-strasse', 'buchheim-herler-strasse', 'wichheimer-strasse', 'vischeringstrasse', 'maria-himmelfahrt-strasse', 'neufelder-strasse-krankenhaus-holweide', 'dellbruck-mauspfad', 'dellbruck-hauptstrasse', 'thielenbruch'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'Linie 4',
      colour: '#e06e9f',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['bocklemund', 'westfriedhof', 'wolffsohnstrasse', 'akazienweg', 'rochusplatz', 'leyendeckerstrasse', 'venloer-strasse-gurtel', 'kornerstrasse', 'piusstrasse', 'hans-bockler-platz-bf-west', 'friesenplatz', 'appellhofplatz', 'neumarkt', 'poststrasse', 'severinstrasse', 'suevenstrasse', 'bahnhof-deutz-lanxess-arena', 'koelnmesse', 'stegerwaldsiedlung', 'grunstrasse', 'mulheim-wiener-platz', 'keupstrasse', 'von-sparr-strasse', 'mulheim-berliner-strasse', 'im-weidenbruch', 'am-emberg', 'leuchterstrasse', 'odenthaler-strasse', 'schlebusch'],
      ],
    },
    {
      id: '5',
      short: '5',
      name: 'Linie 5',
      colour: '#948fb8',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['heumarkt', 'rathaus', 'dom-hbf', 'appellhofplatz', 'friesenplatz', 'hans-bockler-platz-bf-west', 'gutenbergstrasse', 'liebigstrasse', 'subbelrather-strasse-gurtel', 'nussbaumerstrasse', 'lenauplatz', 'iltisstrasse', 'margaretastrasse', 'rektor-klein-strasse', 'alter-flughafen-butzweilerhof', 'ikea-am-butzweilerhof', 'sparkasse-am-butzweilerhof'],
      ],
    },
    {
      id: '7',
      short: '7',
      name: 'Linie 7',
      colour: '#e6855c',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['frechen-benzelrath', 'frechen-muhlengasse', 'frechen-rathaus', 'frechen-kirche', 'frechen-bahnhof', 'haus-vorst', 'marsdorf', 'stuttgenhof', 'brahmsstrasse', 'durener-strasse-gurtel', 'wullnerstrasse', 'aachener-strasse-gurtel', 'melaten', 'universitatsstrasse', 'moltkestrasse', 'rudolfplatz', 'neumarkt', 'heumarkt', 'deutzer-freiheit', 'severinsbrucke', 'drehbrucke', 'poller-kirchweg', 'raiffeisenstrasse', 'poll-salmstrasse', 'baumschulenweg', 'westhoven-kolner-strasse', 'westhoven-berliner-strasse', 'gilgaustrasse', 'ensen-kloster', 'steinstrasse', 'porz-markt', 'rosenhugel', 'zundorf'],
      ],
    },
    {
      id: '9',
      short: '9',
      name: 'Linie 9',
      colour: '#e6877e',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['konigsforst', 'rottgensweg', 'rath-heumar', 'porzer-strasse', 'steinweg', 'autobahn-stadtbahn', 'ostheim', 'vingst', 'kalk-kapelle', 'kalk-post', 'deutz-technische-hochschule', 'bf-deutz-messe', 'deutzer-freiheit', 'heumarkt', 'neumarkt', 'mauritiuskirche', 'zulpicher-platz', 'dasselstrasse-bf-sud', 'universitat', 'weyertal', 'uniklinik-koln', 'zulpicher-strasse-gurtel', 'mommsenstrasse', 'sulz-hermeskeiler-platz'],
      ],
    },
    {
      id: '12',
      short: '12',
      name: 'Linie 12',
      colour: '#8cc63f',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['merkenich', 'merkenich-mitte', 'fordwerke-nord', 'fordwerke-mitte', 'fordwerke-sud', 'geestemunder-strasse', 'niehl-nord', 'wilhelm-sollmann-strasse', 'scheibenstrasse', 'mollwitzstrasse', 'neusser-strasse-gurtel', 'florastrasse', 'lohsestrasse', 'ebertplatz', 'hansaring', 'christophstrasse-mediapark', 'friesenplatz', 'rudolfplatz', 'zulpicher-platz', 'barbarossaplatz', 'eifelstrasse', 'eifelplatz', 'pohligstrasse', 'herthastrasse', 'gottesweg', 'zollstockgurtel', 'zollstock-sudfriedhof'],
      ],
    },
    {
      id: '13',
      short: '13',
      name: 'Linie 13',
      colour: '#967b68',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['thielenbruch', 'dellbruck-hauptstrasse', 'dellbruck-mauspfad', 'neufelder-strasse-krankenhaus-holweide', 'maria-himmelfahrt-strasse', 'vischeringstrasse', 'wichheimer-strasse', 'buchheim-herler-strasse', 'bahnhof-mulheim', 'mulheim-wiener-platz', 'slabystrasse', 'amsterdamer-strasse-gurtel', 'neusser-strasse-gurtel', 'geldernstrasse-parkgurtel', 'escher-strasse', 'nussbaumerstrasse', 'subbelrather-strasse-gurtel', 'venloer-strasse-gurtel', 'weinsbergstrasse-gurtel', 'melatengurtel', 'aachener-strasse-gurtel', 'wullnerstrasse', 'durener-strasse-gurtel', 'gleueler-strasse-gurtel', 'zulpicher-strasse-gurtel', 'euskirchener-strasse', 'berrenrather-strasse-gurtel', 'sulzgurtel'],
      ],
    },
    {
      id: '15',
      short: '15',
      name: 'Linie 15',
      colour: '#54ad4b',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['ubierring', 'chlodwigplatz', 'ulrepforte', 'eifelstrasse', 'barbarossaplatz', 'zulpicher-platz', 'rudolfplatz', 'friesenplatz', 'christophstrasse-mediapark', 'hansaring', 'ebertplatz', 'lohsestrasse', 'florastrasse', 'neusser-strasse-gurtel', 'mollwitzstrasse', 'scheibenstrasse', 'wilhelm-sollmann-strasse', 'altonaer-platz', 'herforder-strasse', 'meerfeldstrasse', 'longericher-strasse', 'heimersdorf', 'chorweiler'],
        ['chorweiler', 'heimersdorf', 'longericher-strasse', 'meerfeldstrasse', 'herforder-strasse', 'altonaer-platz', 'wilhelm-sollmann-strasse', 'scheibenstrasse', 'mollwitzstrasse', 'neusser-strasse-gurtel', 'florastrasse', 'lohsestrasse', 'ebertplatz', 'hansaring', 'christophstrasse-mediapark', 'rudolfplatz', 'zulpicher-platz', 'barbarossaplatz', 'eifelstrasse', 'ulrepforte', 'chlodwigplatz', 'ubierring'],
        ['longerich-friedhof', 'longericher-strasse', 'meerfeldstrasse', 'herforder-strasse', 'altonaer-platz', 'wilhelm-sollmann-strasse', 'scheibenstrasse', 'mollwitzstrasse', 'neusser-strasse-gurtel', 'florastrasse', 'lohsestrasse', 'ebertplatz', 'hansaring', 'christophstrasse-mediapark', 'rudolfplatz', 'zulpicher-platz', 'barbarossaplatz', 'eifelstrasse', 'ulrepforte', 'chlodwigplatz', 'ubierring'],
        ['ubierring', 'chlodwigplatz', 'ulrepforte', 'eifelstrasse', 'barbarossaplatz', 'zulpicher-platz', 'rudolfplatz', 'friesenplatz', 'christophstrasse-mediapark', 'hansaring', 'ebertplatz', 'lohsestrasse', 'florastrasse', 'neusser-strasse-gurtel', 'mollwitzstrasse', 'scheibenstrasse', 'wilhelm-sollmann-strasse', 'altonaer-platz', 'herforder-strasse', 'longericher-strasse', 'longerich-friedhof'],
      ],
    },
    {
      id: '16',
      short: '16',
      name: 'Linie 16',
      colour: '#21bfc1',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['stadthalle', 'bad-godesberg-bahnhof', 'plittersdorfer-strasse', 'wurzerstrasse', 'hochkreuz-deutsches-museum-bonn', 'max-lobner-strasse', 'olof-palme-allee', 'ollenhauerstrasse', 'heussallee-museumsmeile', 'museum-koenig', 'bundesrechnungshof-auswartiges-amt', 'juridicum', 'universitat-markt', 'bonn-hauptbahnhof', 'bonn-west', 'propsthof-nord', 'tannenbusch-sud', 'tannenbusch-mitte', 'buschdorf', 'hersel', 'uedorf', 'widdig', 'urfeld', 'wesseling-sud', 'wesseling', 'wesseling-nord', 'godorf', 'surth-bahnhof', 'michaelshoven', 'siegstrasse', 'rodenkirchen-bahnhof', 'heinrich-lubke-ufer', 'bayenthalgurtel', 'schonhauser-strasse', 'ubierring', 'chlodwigplatz', 'ulrepforte', 'eifelstrasse', 'barbarossaplatz', 'poststrasse', 'neumarkt', 'appellhofplatz', 'dom-hbf', 'breslauer-platz-hbf', 'ebertplatz', 'reichenspergerplatz', 'kinderkrankenhaus', 'amsterdamer-strasse-gurtel', 'nesselrodestrasse', 'niehl-sebastianstrasse'],
      ],
    },
    {
      id: '17',
      short: '17',
      name: 'Linie 17',
      colour: '#6dcff6',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['severinstrasse', 'kartauserhof', 'chlodwigplatz', 'bonner-wall', 'schonhauser-strasse', 'bayenthalgurtel', 'heinrich-lubke-ufer', 'rodenkirchen-bahnhof', 'siegstrasse', 'michaelshoven', 'surth-bahnhof'],
      ],
    },
    {
      id: '18',
      short: '18',
      name: 'Linie 18',
      colour: '#0095da',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['buchheim-herler-strasse', 'bahnhof-mulheim', 'mulheim-wiener-platz', 'slabystrasse', 'boltensternstrasse', 'zoo-flora', 'reichenspergerplatz', 'ebertplatz', 'breslauer-platz-hbf', 'dom-hbf', 'appellhofplatz', 'neumarkt', 'poststrasse', 'barbarossaplatz', 'eifelwall-stadtarchiv', 'weisshausstrasse', 'arnulfstrasse', 'sulzburgstrasse', 'sulzgurtel', 'klettenbergpark', 'efferen', 'kiebitzweg', 'hurth-hermulheim', 'fischenich', 'bruhl-vochem', 'bruhl-nord', 'bruhl-mitte', 'bruhl-sud', 'badorf', 'schwadorf', 'walberberg', 'merten', 'waldorf', 'dersdorf', 'bornheim', 'bornheim-rathaus', 'roisdorf-west', 'alfter-alanus-hochschule', 'dransdorf', 'robert-kirchhoff-strasse', 'bruhler-strasse', 'bonn-west', 'bonn-hauptbahnhof'],
      ],
    },
  ],
  times: {
    'weiden-romergrab weiden-zentrum': 1,
    'junkersdorf rheinenergie-stadion': 1,
    'rheinenergie-stadion alter-militarring': 1,
    'alter-militarring eupener-strasse': 1,
    'eupener-strasse clarenbachstift': 1,
    'clarenbachstift maarweg': 1,
    'aachener-strasse-gurtel melaten': 1,
    'universitatsstrasse moltkestrasse': 1,
    'moltkestrasse rudolfplatz': 1,
    'deutzer-freiheit bf-deutz-messe': 1,
    'fuldaer-strasse sportpark-hohenberg': 1,
    'kalker-friedhof merheim': 1,
    'merheim flehbachstrasse': 4,
    'flehbachstrasse bruck-mauspfad': 1,
    'bruck-mauspfad lustheide': 4,
    'frankenforst neuenweg': 1,
    'neuenweg kolner-strasse': 1,
    'kolner-strasse im-hoppenkamp': 1,
    'im-hoppenkamp bensberg-u': 1,
    'gorlinger-zentrum ollenhauerring': 1,
    'ollenhauerring schaffrathsgasse': 1,
    'schaffrathsgasse bocklemund': 1,
    'bocklemund westfriedhof': 1,
    'westfriedhof wolffsohnstrasse': 1,
    'rochusplatz leyendeckerstrasse': 1,
    'venloer-strasse-gurtel kornerstrasse': 1,
    'kornerstrasse piusstrasse': 1,
    'hans-bockler-platz-bf-west friesenplatz': 1,
    'appellhofplatz neumarkt': 1,
    'neumarkt poststrasse': 1,
    'poststrasse severinstrasse': 1,
    'severinstrasse suevenstrasse': 3,
    'bahnhof-deutz-lanxess-arena koelnmesse': 1,
    'vischeringstrasse maria-himmelfahrt-strasse': 1,
    'wolffsohnstrasse akazienweg': 2,
    'akazienweg rochusplatz': 2,
    'leyendeckerstrasse venloer-strasse-gurtel': 2,
    'piusstrasse hans-bockler-platz-bf-west': 2,
    'friesenplatz appellhofplatz': 2,
    'suevenstrasse bahnhof-deutz-lanxess-arena': 2,
    'koelnmesse stegerwaldsiedlung': 2,
    'stegerwaldsiedlung grunstrasse': 2,
    'grunstrasse mulheim-wiener-platz': 2,
    'mulheim-berliner-strasse im-weidenbruch': 2,
    'im-weidenbruch am-emberg': 2,
    'am-emberg leuchterstrasse': 2,
    'leuchterstrasse odenthaler-strasse': 2,
    'odenthaler-strasse schlebusch': 4,
    'appellhofplatz friesenplatz': 2,
    'hans-bockler-platz-bf-west gutenbergstrasse': 2,
    'lenauplatz iltisstrasse': 2,
    'iltisstrasse margaretastrasse': 2,
    'rektor-klein-strasse alter-flughafen-butzweilerhof': 2,
    'frechen-benzelrath frechen-muhlengasse': 1,
    'frechen-muhlengasse frechen-rathaus': 1,
    'frechen-kirche frechen-bahnhof': 1,
    'frechen-bahnhof haus-vorst': 4,
    'marsdorf stuttgenhof': 3,
    'stuttgenhof brahmsstrasse': 3,
    'durener-strasse-gurtel wullnerstrasse': 1,
    'severinsbrucke drehbrucke': 1,
    'poll-salmstrasse baumschulenweg': 1,
    'baumschulenweg westhoven-kolner-strasse': 3,
    'westhoven-berliner-strasse gilgaustrasse': 1,
    'gilgaustrasse ensen-kloster': 3,
    'porz-markt rosenhugel': 3,
    'rosenhugel zundorf': 3,
    'rottgensweg rath-heumar': 2,
    'porzer-strasse steinweg': 2,
    'steinweg autobahn-stadtbahn': 2,
    'autobahn-stadtbahn ostheim': 2,
    'ostheim vingst': 3,
    'vingst kalk-kapelle': 3,
    'kalk-kapelle kalk-post': 2,
    'kalk-post deutz-technische-hochschule': 2,
    'deutz-technische-hochschule bf-deutz-messe': 2,
    'deutzer-freiheit heumarkt': 2,
    'heumarkt neumarkt': 2,
    'merkenich merkenich-mitte': 1,
    'fordwerke-sud geestemunder-strasse': 1,
    'christophstrasse-mediapark friesenplatz': 1,
    'friesenplatz rudolfplatz': 1,
    'rudolfplatz zulpicher-platz': 1,
    'zulpicher-platz barbarossaplatz': 1,
    'barbarossaplatz eifelstrasse': 1,
    'eifelstrasse eifelplatz': 1,
    'pohligstrasse herthastrasse': 1,
    'herthastrasse gottesweg': 1,
    'gottesweg zollstockgurtel': 1,
    'zollstockgurtel zollstock-sudfriedhof': 1,
    'maria-himmelfahrt-strasse vischeringstrasse': 1,
    'mulheim-wiener-platz slabystrasse': 3,
    'slabystrasse amsterdamer-strasse-gurtel': 3,
    'amsterdamer-strasse-gurtel neusser-strasse-gurtel': 3,
    'nussbaumerstrasse subbelrather-strasse-gurtel': 1,
    'melatengurtel aachener-strasse-gurtel': 1,
    'wullnerstrasse durener-strasse-gurtel': 1,
    'durener-strasse-gurtel gleueler-strasse-gurtel': 1,
    'gleueler-strasse-gurtel zulpicher-strasse-gurtel': 1,
    'zulpicher-strasse-gurtel euskirchener-strasse': 1,
    'euskirchener-strasse berrenrather-strasse-gurtel': 1,
    'berrenrather-strasse-gurtel sulzgurtel': 1,
    'ubierring chlodwigplatz': 1,
    'ulrepforte eifelstrasse': 1,
    'eifelstrasse barbarossaplatz': 1,
    'barbarossaplatz zulpicher-platz': 1,
    'zulpicher-platz rudolfplatz': 1,
    'rudolfplatz friesenplatz': 1,
    'friesenplatz christophstrasse-mediapark': 1,
    'altonaer-platz herforder-strasse': 1,
    'herforder-strasse meerfeldstrasse': 1,
    'meerfeldstrasse longericher-strasse': 1,
    'longericher-strasse heimersdorf': 4,
    'heimersdorf chorweiler': 3,
    'chorweiler heimersdorf': 3,
    'heimersdorf longericher-strasse': 4,
    'longericher-strasse meerfeldstrasse': 1,
    'meerfeldstrasse herforder-strasse': 1,
    'herforder-strasse altonaer-platz': 1,
    'eifelstrasse ulrepforte': 1,
    'chlodwigplatz ubierring': 1,
    'longerich-friedhof longericher-strasse': 1,
    'longericher-strasse longerich-friedhof': 1,
    'stadthalle bad-godesberg-bahnhof': 1,
    'bad-godesberg-bahnhof plittersdorfer-strasse': 1,
    'max-lobner-strasse olof-palme-allee': 1,
    'museum-koenig bundesrechnungshof-auswartiges-amt': 1,
    'bundesrechnungshof-auswartiges-amt juridicum': 1,
    'juridicum universitat-markt': 1,
    'universitat-markt bonn-hauptbahnhof': 1,
    'propsthof-nord tannenbusch-sud': 3,
    'tannenbusch-sud tannenbusch-mitte': 3,
    'buschdorf hersel': 3,
    'hersel uedorf': 3,
    'uedorf widdig': 3,
    'widdig urfeld': 3,
    'urfeld wesseling-sud': 3,
    'wesseling-sud wesseling': 4,
    'wesseling wesseling-nord': 3,
    'wesseling-nord godorf': 4,
    'godorf surth-bahnhof': 5,
    'surth-bahnhof michaelshoven': 3,
    'poststrasse neumarkt': 1,
    'neumarkt appellhofplatz': 1,
    'appellhofplatz dom-hbf': 1,
    'dom-hbf breslauer-platz-hbf': 1,
    'ebertplatz reichenspergerplatz': 1,
    'severinstrasse kartauserhof': 1,
    'kartauserhof chlodwigplatz': 1,
    'chlodwigplatz bonner-wall': 1,
    'michaelshoven surth-bahnhof': 3,
    'reichenspergerplatz ebertplatz': 1,
    'breslauer-platz-hbf dom-hbf': 1,
    'dom-hbf appellhofplatz': 1,
    'eifelwall-stadtarchiv weisshausstrasse': 1,
    'weisshausstrasse arnulfstrasse': 1,
    'arnulfstrasse sulzburgstrasse': 1,
    'sulzburgstrasse sulzgurtel': 1,
    'sulzgurtel klettenbergpark': 1,
    'klettenbergpark efferen': 4,
    'hurth-hermulheim fischenich': 4,
    'fischenich bruhl-vochem': 5,
    'badorf schwadorf': 4,
    'walberberg merten': 4,
    'merten waldorf': 4,
    'waldorf dersdorf': 3,
    'dersdorf bornheim': 3,
    'bornheim-rathaus roisdorf-west': 1,
    'roisdorf-west alfter-alanus-hochschule': 3,
    'alfter-alanus-hochschule dransdorf': 5,
  },
  stations: {
    'gorlinger-zentrum': { name: 'Görlinger-Zentrum', x: 13, y: 15 },
    ollenhauerring: { name: 'Ollenhauerring', x: 13, y: 17 },
    schaffrathsgasse: { name: 'Schaffrathsgasse', x: 11.5, y: 18 },
    bocklemund: { name: 'Bocklemünd', x: 13, y: 19.5 },
    westfriedhof: { name: 'Westfriedhof', x: 15, y: 19.5 },
    wolffsohnstrasse: { name: 'Wolffsohnstraße', x: 16, y: 21 },
    akazienweg: { name: 'Akazienweg', x: 17.5, y: 22.5 },
    rochusplatz: { name: 'Rochusplatz', x: 19, y: 24 },
    leyendeckerstrasse: { name: 'Leyendeckerstraße', x: 21, y: 24 },
    'venloer-strasse-gurtel': { name: 'Venloer Straße/Gürtel', x: 22.5, y: 25.5 },
    kornerstrasse: { name: 'Körnerstraße', x: 24, y: 27 },
    piusstrasse: { name: 'Piusstraße', x: 25.5, y: 28.5 },
    'hans-bockler-platz-bf-west': { name: 'Hans-Böckler-Platz/Bf West', x: 26.5, y: 27.5 },
    friesenplatz: { name: 'Friesenplatz', x: 28, y: 29 },
    appellhofplatz: { name: 'Appellhofplatz', x: 30, y: 29 },
    neumarkt: { name: 'Neumarkt', x: 31.5, y: 30.5 },
    poststrasse: { name: 'Poststraße', x: 31.5, y: 33 },
    severinstrasse: { name: 'Severinstraße', x: 33.5, y: 33.5 },
    suevenstrasse: { name: 'Suevenstraße', x: 35.5, y: 31.5 },
    'bahnhof-deutz-lanxess-arena': { name: 'Bahnhof Deutz / LANXESS arena', x: 36.5, y: 30 },
    koelnmesse: { name: 'Koelnmesse', x: 38, y: 28 },
    stegerwaldsiedlung: { name: 'Stegerwaldsiedlung', x: 39, y: 26 },
    'waldecker-strasse': { name: 'Waldecker Straße', x: 41, y: 26 },
    'buchheim-frankfurter-strasse': { name: 'Buchheim Frankfurter Straße', x: 42, y: 24.5 },
    'buchheim-herler-strasse': { name: 'Buchheim Herler Straße', x: 43.5, y: 23 },
    'wichheimer-strasse': { name: 'Wichheimer Straße', x: 45, y: 21.5 },
    vischeringstrasse: { name: 'Vischeringstraße', x: 46.5, y: 20 },
    'maria-himmelfahrt-strasse': { name: 'Maria-Himmelfahrt-Straße', x: 48.5, y: 20 },
    'neufelder-strasse-krankenhaus-holweide': { name: 'Neufelder Straße/Krankenhaus Holweide', x: 50.5, y: 20 },
    'dellbruck-mauspfad': { name: 'Dellbrück Mauspfad', x: 52.5, y: 20 },
    'dellbruck-hauptstrasse': { name: 'Dellbrück Hauptstraße', x: 54, y: 18.5 },
    thielenbruch: { name: 'Thielenbruch', x: 55.5, y: 17 },
    stadthalle: { name: 'Stadthalle', x: 73.5, y: 113.5 },
    'bad-godesberg-bahnhof': { name: 'Bad Godesberg Bahnhof', x: 73.5, y: 111.5 },
    'plittersdorfer-strasse': { name: 'Plittersdorfer Straße', x: 72, y: 110 },
    wurzerstrasse: { name: 'Wurzerstraße', x: 70.5, y: 108.5 },
    'hochkreuz-deutsches-museum-bonn': { name: 'Hochkreuz / Deutsches Museum Bonn', x: 69, y: 107 },
    'max-lobner-strasse': { name: 'Max-Löbner-Straße', x: 67.5, y: 105.5 },
    'olof-palme-allee': { name: 'Olof-Palme-Allee', x: 66, y: 103.5 },
    ollenhauerstrasse: { name: 'Ollenhauerstraße', x: 64.5, y: 102 },
    'heussallee-museumsmeile': { name: 'Heussallee/Museumsmeile', x: 63, y: 100 },
    'museum-koenig': { name: 'Museum Koenig', x: 61.5, y: 98.5 },
    'bundesrechnungshof-auswartiges-amt': { name: 'Bundesrechnungshof/Auswärtiges Amt', x: 59.5, y: 96.5 },
    juridicum: { name: 'Juridicum', x: 59.5, y: 94 },
    'universitat-markt': { name: 'Universität / Markt', x: 57.5, y: 92 },
    'bonn-hauptbahnhof': { name: 'Bonn Hauptbahnhof', x: 55.5, y: 91.5 },
    'bonn-west': { name: 'Bonn West', x: 53, y: 90.5 },
    'propsthof-nord': { name: 'Propsthof Nord', x: 51.5, y: 88.5 },
    'tannenbusch-sud': { name: 'Tannenbusch Süd', x: 50.5, y: 86.5 },
    'tannenbusch-mitte': { name: 'Tannenbusch Mitte', x: 49, y: 84.5 },
    buschdorf: { name: 'Buschdorf', x: 47.5, y: 82 },
    hersel: { name: 'Hersel', x: 46, y: 80 },
    uedorf: { name: 'Uedorf', x: 44.5, y: 77.5 },
    widdig: { name: 'Widdig', x: 43, y: 75 },
    urfeld: { name: 'Urfeld', x: 41.5, y: 72.5 },
    'wesseling-sud': { name: 'Wesseling Süd', x: 40, y: 70 },
    wesseling: { name: 'Wesseling', x: 38.5, y: 67.5 },
    'wesseling-nord': { name: 'Wesseling Nord', x: 38.5, y: 64.5 },
    godorf: { name: 'Godorf', x: 38.5, y: 61 },
    'surth-bahnhof': { name: 'Sürth Bahnhof', x: 38.5, y: 58 },
    michaelshoven: { name: 'Michaelshoven', x: 38, y: 55 },
    siegstrasse: { name: 'Siegstraße', x: 38, y: 52 },
    'rodenkirchen-bahnhof': { name: 'Rodenkirchen Bahnhof', x: 38, y: 49 },
    'heinrich-lubke-ufer': { name: 'Heinrich-Lübke-Ufer', x: 38, y: 46 },
    bayenthalgurtel: { name: 'Bayenthalgürtel', x: 36.5, y: 43.5 },
    'schonhauser-strasse': { name: 'Schönhauser Straße', x: 35, y: 41.5 },
    ubierring: { name: 'Ubierring', x: 35, y: 39 },
    chlodwigplatz: { name: 'Chlodwigplatz', x: 33.5, y: 37 },
    ulrepforte: { name: 'Ulrepforte', x: 31, y: 37 },
    eifelstrasse: { name: 'Eifelstraße', x: 31, y: 35 },
    barbarossaplatz: { name: 'Barbarossaplatz', x: 29.5, y: 33.5 },
    'dom-hbf': { name: 'Dom/Hbf', x: 31.5, y: 28.5 },
    'breslauer-platz-hbf': { name: 'Breslauer Platz/Hbf', x: 32.5, y: 27 },
    ebertplatz: { name: 'Ebertplatz', x: 32, y: 25 },
    reichenspergerplatz: { name: 'Reichenspergerplatz', x: 33.5, y: 23.5 },
    kinderkrankenhaus: { name: 'Kinderkrankenhaus', x: 34, y: 21.5 },
    'amsterdamer-strasse-gurtel': { name: 'Amsterdamer Straße/Gürtel', x: 34, y: 19.5 },
    nesselrodestrasse: { name: 'Nesselrodestraße', x: 34, y: 17.5 },
    'niehl-sebastianstrasse': { name: 'Niehl Sebastianstraße', x: 33, y: 16 },
    'frechen-benzelrath': { name: 'Frechen-Benzelrath', x: 0, y: 37.5 },
    'frechen-muhlengasse': { name: 'Frechen Mühlengasse', x: 1.5, y: 36 },
    'frechen-rathaus': { name: 'Frechen Rathaus', x: 3.5, y: 36 },
    'frechen-kirche': { name: 'Frechen Kirche', x: 5.5, y: 36 },
    'frechen-bahnhof': { name: 'Frechen Bahnhof', x: 8, y: 36 },
    'haus-vorst': { name: 'Haus Vorst', x: 10, y: 35.5 },
    marsdorf: { name: 'Marsdorf', x: 12, y: 35.5 },
    stuttgenhof: { name: 'Stüttgenhof', x: 14.5, y: 35.5 },
    brahmsstrasse: { name: 'Brahmsstraße', x: 16.5, y: 35.5 },
    'durener-strasse-gurtel': { name: 'Dürener Straße/Gürtel', x: 19, y: 35 },
    wullnerstrasse: { name: 'Wüllnerstraße', x: 20.5, y: 33.5 },
    'aachener-strasse-gurtel': { name: 'Aachener Straße/Gürtel', x: 20.5, y: 31 },
    melaten: { name: 'Melaten', x: 23, y: 31 },
    universitatsstrasse: { name: 'Universitätsstraße', x: 25, y: 30.5 },
    moltkestrasse: { name: 'Moltkestraße', x: 27, y: 30.5 },
    rudolfplatz: { name: 'Rudolfplatz', x: 29, y: 30.5 },
    heumarkt: { name: 'Heumarkt', x: 33, y: 31.5 },
    'deutzer-freiheit': { name: 'Deutzer Freiheit', x: 34.5, y: 30 },
    severinsbrucke: { name: 'Severinsbrücke', x: 34.5, y: 32 },
    drehbrucke: { name: 'Drehbrücke', x: 36, y: 33.5 },
    'poller-kirchweg': { name: 'Poller Kirchweg', x: 37.5, y: 34.5 },
    raiffeisenstrasse: { name: 'Raiffeisenstraße', x: 39, y: 36 },
    'poll-salmstrasse': { name: 'Poll Salmstraße', x: 40.5, y: 37.5 },
    baumschulenweg: { name: 'Baumschulenweg', x: 42, y: 39 },
    'westhoven-kolner-strasse': { name: 'Westhoven, Kölner Straße', x: 43.5, y: 40 },
    'westhoven-berliner-strasse': { name: 'Westhoven Berliner Straße', x: 45, y: 41.5 },
    gilgaustrasse: { name: 'Gilgaustraße', x: 46.5, y: 43 },
    'ensen-kloster': { name: 'Ensen Kloster', x: 48, y: 44.5 },
    steinstrasse: { name: 'Steinstraße', x: 49.5, y: 46 },
    'porz-markt': { name: 'Porz Markt', x: 50, y: 48 },
    rosenhugel: { name: 'Rosenhügel', x: 50, y: 50 },
    zundorf: { name: 'Zündorf', x: 48.5, y: 51 },
    grunstrasse: { name: 'Grünstraße', x: 39, y: 23.5 },
    'mulheim-wiener-platz': { name: 'Mülheim Wiener Platz', x: 39, y: 21.5 },
    keupstrasse: { name: 'Keupstraße', x: 40.5, y: 20 },
    'von-sparr-strasse': { name: 'Von-Sparr-Straße', x: 42, y: 18.5 },
    'mulheim-berliner-strasse': { name: 'Mülheim Berliner Straße', x: 43.5, y: 17 },
    'im-weidenbruch': { name: 'Im Weidenbruch', x: 45, y: 15.5 },
    'am-emberg': { name: 'Am Emberg', x: 46.5, y: 14 },
    leuchterstrasse: { name: 'Leuchterstraße', x: 48, y: 12.5 },
    'odenthaler-strasse': { name: 'Odenthaler Straße', x: 48, y: 10 },
    schlebusch: { name: 'Schlebusch', x: 48, y: 8 },
    'weiden-west': { name: 'Weiden West', x: 1.5, y: 30 },
    'weiden-romergrab': { name: 'Weiden Römergrab', x: 3.5, y: 30 },
    'weiden-zentrum': { name: 'Weiden Zentrum', x: 5.5, y: 30 },
    bahnstrasse: { name: 'Bahnstraße', x: 7.5, y: 30 },
    mohnweg: { name: 'Mohnweg', x: 9.5, y: 30.5 },
    junkersdorf: { name: 'Junkersdorf', x: 11.5, y: 30.5 },
    'rheinenergie-stadion': { name: 'Rheinenergie-Stadion', x: 13, y: 30.5 },
    'alter-militarring': { name: 'Alter Militärring', x: 14.5, y: 29 },
    'eupener-strasse': { name: 'Eupener Straße', x: 16, y: 30.5 },
    clarenbachstift: { name: 'Clarenbachstift', x: 18, y: 31 },
    maarweg: { name: 'Maarweg', x: 19.5, y: 29.5 },
    'bf-deutz-messe': { name: 'Bf Deutz/Messe', x: 36.5, y: 28.5 },
    'deutz-technische-hochschule': { name: 'Deutz Technische Hochschule', x: 38.5, y: 29.5 },
    'kalk-post': { name: 'Kalk Post', x: 41, y: 29.5 },
    'kalk-kapelle': { name: 'Kalk Kapelle', x: 43.5, y: 29.5 },
    'fuldaer-strasse': { name: 'Fuldaer Straße', x: 45, y: 28 },
    'sportpark-hohenberg': { name: 'Sportpark Höhenberg', x: 47.5, y: 27.5 },
    'kalker-friedhof': { name: 'Kalker Friedhof', x: 49.5, y: 27.5 },
    merheim: { name: 'Merheim', x: 52, y: 27 },
    flehbachstrasse: { name: 'Flehbachstraße', x: 54.5, y: 27 },
    'bruck-mauspfad': { name: 'Brück Mauspfad', x: 56.5, y: 26.5 },
    lustheide: { name: 'Lustheide', x: 59, y: 26.5 },
    refrath: { name: 'Refrath', x: 61, y: 26.5 },
    kippekausen: { name: 'Kippekausen', x: 63.5, y: 26 },
    frankenforst: { name: 'Frankenforst', x: 65, y: 24.5 },
    neuenweg: { name: 'Neuenweg', x: 66.5, y: 23 },
    'kolner-strasse': { name: 'Kölner Straße', x: 68.5, y: 23 },
    'im-hoppenkamp': { name: 'Im Hoppenkamp', x: 70.5, y: 23 },
    'bensberg-u': { name: 'Bensberg U', x: 72.5, y: 23 },
    'bahnhof-mulheim': { name: 'Bahnhof Mülheim', x: 41, y: 23 },
    slabystrasse: { name: 'Slabystraße', x: 37, y: 20 },
    boltensternstrasse: { name: 'Boltensternstraße', x: 36, y: 21.5 },
    'zoo-flora': { name: 'Zoo/Flora', x: 35.5, y: 23 },
    'eifelwall-stadtarchiv': { name: 'Eifelwall/Stadtarchiv', x: 28, y: 35.5 },
    weisshausstrasse: { name: 'Weißhausstraße', x: 28, y: 37.5 },
    arnulfstrasse: { name: 'Arnulfstraße', x: 26, y: 38 },
    sulzburgstrasse: { name: 'Sülzburgstraße', x: 26, y: 40.5 },
    sulzgurtel: { name: 'Sülzgürtel', x: 24.5, y: 42.5 },
    klettenbergpark: { name: 'Klettenbergpark', x: 23.5, y: 44.5 },
    efferen: { name: 'Efferen', x: 22, y: 47 },
    kiebitzweg: { name: 'Kiebitzweg', x: 22.5, y: 49.5 },
    'hurth-hermulheim': { name: 'Hürth-Hermülheim', x: 22.5, y: 52.5 },
    fischenich: { name: 'Fischenich', x: 23, y: 55.5 },
    'bruhl-vochem': { name: 'Brühl-Vochem', x: 23, y: 58.5 },
    'bruhl-nord': { name: 'Brühl Nord', x: 23.5, y: 61.5 },
    'bruhl-mitte': { name: 'Brühl Mitte', x: 24, y: 64.5 },
    'bruhl-sud': { name: 'Brühl Süd', x: 24, y: 67 },
    badorf: { name: 'Badorf', x: 24.5, y: 70 },
    schwadorf: { name: 'Schwadorf', x: 26.5, y: 72.5 },
    walberberg: { name: 'Walberberg', x: 28.5, y: 74.5 },
    merten: { name: 'Merten', x: 30.5, y: 77 },
    waldorf: { name: 'Waldorf', x: 33, y: 79 },
    dersdorf: { name: 'Dersdorf', x: 35, y: 81 },
    bornheim: { name: 'Bornheim', x: 37, y: 83 },
    'bornheim-rathaus': { name: 'Bornheim Rathaus', x: 39, y: 85 },
    'roisdorf-west': { name: 'Roisdorf West', x: 41, y: 86.5 },
    'alfter-alanus-hochschule': { name: 'Alfter / Alanus Hochschule', x: 43.5, y: 88.5 },
    dransdorf: { name: 'Dransdorf', x: 45.5, y: 90 },
    'robert-kirchhoff-strasse': { name: 'Robert-Kirchhoff-Straße', x: 48, y: 90.5 },
    'bruhler-strasse': { name: 'Brühler Straße', x: 50.5, y: 90.5 },
    rathaus: { name: 'Rathaus', x: 33, y: 30 },
    gutenbergstrasse: { name: 'Gutenbergstraße', x: 27, y: 25.5 },
    liebigstrasse: { name: 'Liebigstraße', x: 25, y: 25.5 },
    'subbelrather-strasse-gurtel': { name: 'Subbelrather Straße/Gürtel', x: 24, y: 24 },
    nussbaumerstrasse: { name: 'Nußbaumerstraße', x: 25.5, y: 22.5 },
    lenauplatz: { name: 'Lenauplatz', x: 23.5, y: 22.5 },
    iltisstrasse: { name: 'Iltisstraße', x: 22, y: 21 },
    margaretastrasse: { name: 'Margaretastraße', x: 20.5, y: 19.5 },
    'rektor-klein-strasse': { name: 'Rektor-Klein-Straße', x: 20.5, y: 17.5 },
    'alter-flughafen-butzweilerhof': { name: 'Alter Flughafen Butzweilerhof', x: 19, y: 16 },
    'ikea-am-butzweilerhof': { name: 'IKEA Am Butzweilerhof', x: 19, y: 14 },
    'sparkasse-am-butzweilerhof': { name: 'Sparkasse Am Butzweilerhof', x: 17.5, y: 12.5 },
    'neusser-strasse-gurtel': { name: 'Neusser Straße/Gürtel', x: 31.5, y: 19.5 },
    'geldernstrasse-parkgurtel': { name: 'Geldernstraße/Parkgürtel', x: 29.5, y: 19.5 },
    'escher-strasse': { name: 'Escher Straße', x: 27.5, y: 21 },
    'weinsbergstrasse-gurtel': { name: 'Weinsbergstraße/Gürtel', x: 22.5, y: 27.5 },
    melatengurtel: { name: 'Melatengürtel', x: 22, y: 29.5 },
    'gleueler-strasse-gurtel': { name: 'Gleueler Straße/Gürtel', x: 21, y: 35.5 },
    'zulpicher-strasse-gurtel': { name: 'Zülpicher Straße/Gürtel', x: 22.5, y: 37 },
    'euskirchener-strasse': { name: 'Euskirchener Straße', x: 22.5, y: 39.5 },
    'berrenrather-strasse-gurtel': { name: 'Berrenrather Straße/Gürtel', x: 24.5, y: 40 },
    konigsforst: { name: 'Königsforst', x: 59, y: 33 },
    rottgensweg: { name: 'Röttgensweg', x: 57, y: 33 },
    'rath-heumar': { name: 'Rath/Heumar', x: 55, y: 33 },
    'porzer-strasse': { name: 'Porzer Straße', x: 53.5, y: 31.5 },
    steinweg: { name: 'Steinweg', x: 51.5, y: 31.5 },
    'autobahn-stadtbahn': { name: 'Autobahn (Stadtbahn)', x: 49, y: 31.5 },
    ostheim: { name: 'Ostheim', x: 47, y: 31 },
    vingst: { name: 'Vingst', x: 45, y: 31 },
    mauritiuskirche: { name: 'Mauritiuskirche', x: 30, y: 32 },
    'zulpicher-platz': { name: 'Zülpicher Platz', x: 28, y: 32 },
    'dasselstrasse-bf-sud': { name: 'Dasselstraße/Bf Süd', x: 28, y: 33.5 },
    universitat: { name: 'Universität', x: 26, y: 33.5 },
    weyertal: { name: 'Weyertal', x: 26, y: 35.5 },
    'uniklinik-koln': { name: 'Uniklinik Köln', x: 24, y: 35.5 },
    mommsenstrasse: { name: 'Mommsenstraße', x: 20.5, y: 37 },
    'sulz-hermeskeiler-platz': { name: 'Sülz Hermeskeiler Platz', x: 20.5, y: 39 },
    kartauserhof: { name: 'Kartäuserhof', x: 32.5, y: 35.5 },
    'bonner-wall': { name: 'Bonner Wall', x: 33.5, y: 39.5 },
    chorweiler: { name: 'Chorweiler', x: 22, y: 6 },
    heimersdorf: { name: 'Heimersdorf', x: 23.5, y: 7.5 },
    'longericher-strasse': { name: 'Longericher Straße', x: 25, y: 9 },
    meerfeldstrasse: { name: 'Meerfeldstraße', x: 25, y: 11 },
    'herforder-strasse': { name: 'Herforder Straße', x: 26.5, y: 10 },
    'altonaer-platz': { name: 'Altonaer Platz', x: 28, y: 11.5 },
    'wilhelm-sollmann-strasse': { name: 'Wilhelm-Sollmann-Straße', x: 29.5, y: 13 },
    scheibenstrasse: { name: 'Scheibenstraße', x: 30, y: 15.5 },
    mollwitzstrasse: { name: 'Mollwitzstraße', x: 30, y: 17.5 },
    florastrasse: { name: 'Florastraße', x: 32, y: 21 },
    lohsestrasse: { name: 'Lohsestraße', x: 32, y: 23 },
    hansaring: { name: 'Hansaring', x: 30.5, y: 26.5 },
    'christophstrasse-mediapark': { name: 'Christophstraße/Mediapark', x: 29, y: 28 },
    merkenich: { name: 'Merkenich', x: 29.5, y: 0 },
    'merkenich-mitte': { name: 'Merkenich Mitte', x: 31, y: 1.5 },
    'fordwerke-nord': { name: 'Fordwerke Nord', x: 31, y: 3.5 },
    'fordwerke-mitte': { name: 'Fordwerke Mitte', x: 31, y: 5.5 },
    'fordwerke-sud': { name: 'Fordwerke Süd', x: 31, y: 7.5 },
    'geestemunder-strasse': { name: 'Geestemünder Straße', x: 31, y: 9.5 },
    'niehl-nord': { name: 'Niehl Nord', x: 31, y: 11.5 },
    eifelplatz: { name: 'Eifelplatz', x: 29.5, y: 36 },
    pohligstrasse: { name: 'Pohligstraße', x: 29.5, y: 38 },
    herthastrasse: { name: 'Herthastraße', x: 28, y: 39.5 },
    gottesweg: { name: 'Gottesweg', x: 29.5, y: 40.5 },
    zollstockgurtel: { name: 'Zollstockgürtel', x: 28, y: 42 },
    'zollstock-sudfriedhof': { name: 'Zollstock Südfriedhof', x: 29.5, y: 43.5 },
    'longerich-friedhof': { name: 'Longerich Friedhof', x: 23.5, y: 10.5 },
  },
};
