// Copenhagen's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'copenhagen',
  name: 'Copenhagen',
  system: 'Metro',
  country: 'Denmark',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'm1',
      short: 'M1',
      name: 'Metro M1',
      colour: '#008d41',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['vanl-se', 'flintholm', 'lindevang', 'fasanvej', 'frederiksberg', 'forum', 'n-rreport', 'kongens-nytorv', 'christianshavn', 'islands-brygge', 'dr-byen', 'sundby', 'bella-center', 'restad', 'vestamager'],
      ],
    },
    {
      id: 'm2',
      short: 'M2',
      name: 'Metro M2',
      colour: '#ffc600',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['vanl-se', 'flintholm', 'lindevang', 'fasanvej', 'frederiksberg', 'forum', 'n-rreport', 'kongens-nytorv', 'christianshavn', 'amagerbro', 'lergravsparken', 'resund', 'amager-strand', 'fem-ren', 'kastrup', 'lufthavnen-metro'],
      ],
    },
    {
      id: 'm3',
      short: 'M3',
      name: 'Cityringen',
      colour: '#ff0a0a',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['aksel-m-llers-have', 'nuuks-plads', 'n-rrebros-runddel', 'n-rrebro', 'skjolds-plads', 'vibenhus-runddel', 'poul-henningsens-plads', 'trianglen', 'sterport', 'marmorkirken', 'kongens-nytorv', 'gammel-strand', 'radhuspladsen', 'k-benhavn-h', 'enghave-plads', 'frederiksberg-alle', 'frederiksberg', 'aksel-m-llers-have'],
      ],
    },
    {
      id: 'm4',
      short: 'M4',
      name: 'Nordhavnsmetro',
      colour: '#009cd3',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['orientkaj', 'nordhavn', 'sterport', 'marmorkirken', 'kongens-nytorv', 'gammel-strand', 'radhuspladsen', 'k-benhavn-h', 'havneholmen', 'enghave-brygge', 'sluseholmen', 'mozarts-plads', 'k-benhavn-syd'],
      ],
    },
  ],
  times: {
    'vanl-se flintholm': 1,
    'fasanvej frederiksberg': 1,
    'frederiksberg forum': 3,
    'forum n-rreport': 3,
    'dr-byen sundby': 3,
    'christianshavn amagerbro': 3,
    'amager-strand fem-ren': 3,
    'fem-ren kastrup': 3,
    'kastrup lufthavnen-metro': 1,
    'poul-henningsens-plads trianglen': 3,
    'kongens-nytorv gammel-strand': 1,
    'k-benhavn-h enghave-plads': 3,
    'frederiksberg aksel-m-llers-have': 1,
    'orientkaj nordhavn': 1,
    'nordhavn sterport': 4,
    'k-benhavn-h havneholmen': 3,
    'enghave-brygge sluseholmen': 3,
    'mozarts-plads k-benhavn-syd': 3,
  },
  stations: {
    'vanl-se': { name: 'Vanløse', x: 0, y: 6 },
    flintholm: { name: 'Flintholm', x: 2, y: 6 },
    lindevang: { name: 'Lindevang', x: 4, y: 6 },
    fasanvej: { name: 'Fasanvej', x: 5.5, y: 7.5 },
    frederiksberg: { name: 'Frederiksberg', x: 7.5, y: 7.5 },
    forum: { name: 'Forum', x: 9.5, y: 7.5 },
    'n-rreport': { name: 'Nørreport', x: 12, y: 7.5 },
    'kongens-nytorv': { name: 'Kongens Nytorv', x: 14, y: 8 },
    christianshavn: { name: 'Christianshavn', x: 14, y: 10 },
    'islands-brygge': { name: 'Islands Brygge', x: 14, y: 12 },
    'dr-byen': { name: 'DR Byen', x: 14, y: 14 },
    sundby: { name: 'Sundby', x: 14, y: 16 },
    'bella-center': { name: 'Bella Center', x: 14, y: 18 },
    restad: { name: 'Ørestad', x: 14, y: 20 },
    vestamager: { name: 'Vestamager', x: 14, y: 22 },
    amagerbro: { name: 'Amagerbro', x: 15.5, y: 11.5 },
    lergravsparken: { name: 'Lergravsparken', x: 17.5, y: 11.5 },
    resund: { name: 'Øresund', x: 19.5, y: 11.5 },
    'amager-strand': { name: 'Amager Strand', x: 19.5, y: 13.5 },
    'fem-ren': { name: 'Femøren', x: 19.5, y: 15.5 },
    kastrup: { name: 'Kastrup', x: 21, y: 17 },
    'lufthavnen-metro': { name: 'Lufthavnen (Metro)', x: 21, y: 19 },
    'aksel-m-llers-have': { name: 'Aksel Møllers Have', x: 6, y: 6 },
    'nuuks-plads': { name: 'Nuuks Plads', x: 8, y: 6 },
    'n-rrebros-runddel': { name: 'Nørrebros Runddel', x: 9, y: 4 },
    'n-rrebro': { name: 'Nørrebro', x: 7.5, y: 2.5 },
    'skjolds-plads': { name: 'Skjolds Plads', x: 9, y: 1 },
    'vibenhus-runddel': { name: 'Vibenhus Runddel', x: 11, y: 1 },
    'poul-henningsens-plads': { name: 'Poul Henningsens Plads', x: 13, y: 1 },
    trianglen: { name: 'Trianglen', x: 12.5, y: 3 },
    sterport: { name: 'Østerport', x: 14, y: 4 },
    marmorkirken: { name: 'Marmorkirken', x: 14, y: 6 },
    'gammel-strand': { name: 'Gammel Strand', x: 12.5, y: 9 },
    radhuspladsen: { name: 'Rådhuspladsen', x: 10.5, y: 9 },
    'k-benhavn-h': { name: 'København H', x: 10.5, y: 11 },
    'enghave-plads': { name: 'Enghave Plads', x: 8.5, y: 11 },
    'frederiksberg-alle': { name: 'Frederiksberg Allé', x: 7.5, y: 9.5 },
    orientkaj: { name: 'Orientkaj', x: 14, y: 0 },
    nordhavn: { name: 'Nordhavn', x: 14, y: 2 },
    havneholmen: { name: 'Havneholmen', x: 10.5, y: 13 },
    'enghave-brygge': { name: 'Enghave Brygge', x: 10.5, y: 15 },
    sluseholmen: { name: 'Sluseholmen', x: 9, y: 16.5 },
    'mozarts-plads': { name: 'Mozarts Plads', x: 7, y: 16.5 },
    'k-benhavn-syd': { name: 'København Syd', x: 5, y: 16.5 },
  },
};
