// Dublin's Luas, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'dublin',
  name: 'Dublin',
  system: 'Luas',
  country: 'Ireland',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'luas-green-line',
      short: '',
      name: 'Luas Green Line',
      colour: '#008531',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['bride-s-glen', 'cherrywood', 'laughanstown', 'carrickmines', 'ballyogan-wood', 'leopardstown-valley', 'the-gallops', 'glencairn', 'central-park', 'sandyford', 'stillorgan', 'kilmacud', 'balally', 'dundrum', 'windy-arbour', 'milltown', 'cowper', 'beechwood', 'ranelagh', 'charlemont', 'harcourt', 'st-stephen-s-green', 'dawson', 'westmoreland', 'o-connell-gpo', 'o-connell-upper', 'dominick', 'broadstone-university', 'grangegorman', 'phibsborough', 'cabra', 'broombridge'],
        ['broombridge', 'cabra', 'phibsborough', 'grangegorman', 'broadstone-university', 'dominick', 'parnell', 'marlborough', 'trinity', 'dawson', 'st-stephen-s-green', 'harcourt', 'charlemont', 'ranelagh', 'beechwood', 'cowper', 'milltown', 'windy-arbour', 'dundrum', 'balally', 'kilmacud', 'stillorgan', 'sandyford', 'central-park', 'glencairn', 'the-gallops', 'leopardstown-valley', 'ballyogan-wood', 'carrickmines', 'laughanstown', 'cherrywood', 'bride-s-glen'],
      ],
    },
    {
      id: 'red',
      short: '',
      name: 'Luas Red Line',
      colour: '#cd5c5c',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['saggart', 'fortunestown', 'citywest-campus', 'cheeverstown', 'fettercairn', 'belgard', 'kingswood', 'red-cow', 'kylemore', 'bluebell', 'blackhorse', 'drimnagh', 'goldenbridge', 'suir-road', 'rialto', 'fatima', 'james-s', 'heuston', 'museum', 'smithfield', 'four-courts', 'jervis', 'abbey-street', 'busaras', 'george-s-dock', 'mayor-square-nci', 'spencer-dock', 'the-point'],
        ['the-point', 'spencer-dock', 'mayor-square-nci', 'george-s-dock', 'busaras', 'abbey-street', 'jervis', 'four-courts', 'museum', 'heuston', 'james-s', 'fatima', 'rialto', 'suir-road', 'goldenbridge', 'drimnagh', 'blackhorse', 'bluebell', 'kylemore', 'red-cow', 'kingswood', 'belgard', 'fettercairn', 'cheeverstown', 'citywest-campus', 'fortunestown', 'saggart'],
        ['tallaght', 'hospital', 'cookstown', 'belgard', 'kingswood', 'red-cow', 'kylemore', 'bluebell', 'blackhorse', 'drimnagh', 'goldenbridge', 'suir-road', 'rialto', 'fatima', 'james-s', 'heuston', 'museum', 'smithfield', 'four-courts', 'jervis', 'abbey-street', 'busaras', 'connolly'],
        ['connolly', 'busaras', 'abbey-street', 'jervis', 'four-courts', 'museum', 'heuston', 'james-s', 'fatima', 'rialto', 'suir-road', 'goldenbridge', 'drimnagh', 'blackhorse', 'bluebell', 'kylemore', 'red-cow', 'kingswood', 'belgard', 'cookstown', 'hospital', 'tallaght'],
      ],
    },
  ],
  times: {
    'bride-s-glen cherrywood': 1,
    'sandyford stillorgan': 1,
    'cowper beechwood': 1,
    'ranelagh charlemont': 1,
    'charlemont harcourt': 1,
    'st-stephen-s-green dawson': 1,
    'dawson westmoreland': 1,
    'westmoreland o-connell-gpo': 1,
    'o-connell-gpo o-connell-upper': 1,
    'o-connell-upper dominick': 1,
    'broadstone-university grangegorman': 1,
    'grangegorman phibsborough': 1,
    'phibsborough cabra': 1,
    'cabra broombridge': 3,
    'broombridge cabra': 3,
    'cabra phibsborough': 1,
    'phibsborough grangegorman': 1,
    'grangegorman broadstone-university': 1,
    'dominick parnell': 1,
    'parnell marlborough': 1,
    'marlborough trinity': 1,
    'trinity dawson': 1,
    'dawson st-stephen-s-green': 1,
    'harcourt charlemont': 1,
    'charlemont ranelagh': 1,
    'beechwood cowper': 1,
    'stillorgan sandyford': 1,
    'cherrywood bride-s-glen': 1,
    'saggart fortunestown': 2,
    'citywest-campus cheeverstown': 2,
    'cheeverstown fettercairn': 2,
    'fettercairn belgard': 3,
    'belgard kingswood': 2,
    'kingswood red-cow': 3,
    'red-cow kylemore': 4,
    'kylemore bluebell': 2,
    'bluebell blackhorse': 2,
    'blackhorse drimnagh': 2,
    'suir-road rialto': 2,
    'museum smithfield': 2,
    'four-courts museum': 2,
    'rialto suir-road': 2,
    'drimnagh blackhorse': 2,
    'blackhorse bluebell': 2,
    'bluebell kylemore': 2,
    'kylemore red-cow': 4,
    'red-cow kingswood': 3,
    'kingswood belgard': 2,
    'belgard fettercairn': 3,
    'fettercairn cheeverstown': 2,
    'cheeverstown citywest-campus': 2,
    'fortunestown saggart': 2,
    'hospital cookstown': 2,
    'cookstown belgard': 2,
    'belgard cookstown': 2,
    'cookstown hospital': 2,
  },
  walks: [
    ['abbey-street', 'marlborough', 2],
    ['abbey-street', 'o-connell-gpo', 2],
  ],
  stations: {
    connolly: { name: 'Connolly', x: 40, y: 7.5 },
    busaras: { name: 'Busáras', x: 38.5, y: 7.5 },
    'abbey-street': { name: 'Abbey Street', x: 37.5, y: 9 },
    jervis: { name: 'Jervis', x: 34.5, y: 9.5 },
    'four-courts': { name: 'Four Courts', x: 32.5, y: 9.5 },
    museum: { name: 'Museum', x: 30, y: 9.5 },
    heuston: { name: 'Heuston', x: 28, y: 9.5 },
    'james-s': { name: 'James\'s', x: 28, y: 12 },
    fatima: { name: 'Fatima', x: 27.5, y: 14 },
    rialto: { name: 'Rialto', x: 25.5, y: 14 },
    'suir-road': { name: 'Suir Road', x: 23, y: 14.5 },
    goldenbridge: { name: 'Goldenbridge', x: 21, y: 14.5 },
    drimnagh: { name: 'Drimnagh', x: 19, y: 15 },
    blackhorse: { name: 'Blackhorse', x: 17, y: 16.5 },
    bluebell: { name: 'Bluebell', x: 15.5, y: 18 },
    kylemore: { name: 'Kylemore', x: 13.5, y: 20 },
    'red-cow': { name: 'Red Cow', x: 12, y: 21.5 },
    kingswood: { name: 'Kingswood', x: 10, y: 23 },
    belgard: { name: 'Belgard', x: 8.5, y: 25 },
    cookstown: { name: 'Cookstown', x: 8.5, y: 27 },
    hospital: { name: 'Hospital', x: 8.5, y: 29 },
    tallaght: { name: 'Tallaght', x: 10, y: 30.5 },
    saggart: { name: 'Saggart', x: 0, y: 31 },
    fortunestown: { name: 'Fortunestown', x: 2, y: 31, aka: ['Fortunestown Tram Stop'] },
    'citywest-campus': { name: 'Citywest Campus', x: 3.5, y: 29.5 },
    cheeverstown: { name: 'Cheeverstown', x: 5, y: 28 },
    fettercairn: { name: 'Fettercairn', x: 7, y: 26.5 },
    smithfield: { name: 'Smithfield', x: 31, y: 11 },
    'george-s-dock': { name: 'George\'s Dock', x: 40, y: 9 },
    'mayor-square-nci': { name: 'Mayor Square - NCI', x: 41.5, y: 7.5 },
    'spencer-dock': { name: 'Spencer Dock', x: 43, y: 9 },
    'the-point': { name: 'The Point', x: 45, y: 9 },
    'bride-s-glen': { name: 'Bride\'s Glen', x: 61, y: 47 },
    cherrywood: { name: 'Cherrywood', x: 59.5, y: 46 },
    laughanstown: { name: 'Laughanstown', x: 58, y: 44.5 },
    carrickmines: { name: 'Carrickmines', x: 56, y: 44 },
    'ballyogan-wood': { name: 'Ballyogan Wood', x: 53.5, y: 44 },
    'leopardstown-valley': { name: 'Leopardstown Valley', x: 51.5, y: 44 },
    'the-gallops': { name: 'The Gallops', x: 50, y: 42.5 },
    glencairn: { name: 'Glencairn', x: 48.5, y: 40.5 },
    'central-park': { name: 'Central Park', x: 48, y: 38.5 },
    sandyford: { name: 'Sandyford', x: 48, y: 36.5 },
    stillorgan: { name: 'Stillorgan', x: 46, y: 34.5 },
    kilmacud: { name: 'Kilmacud', x: 44.5, y: 33 },
    balally: { name: 'Balally', x: 42.5, y: 31.5 },
    dundrum: { name: 'Dundrum', x: 41, y: 30 },
    'windy-arbour': { name: 'Windy Arbour', x: 39.5, y: 28 },
    milltown: { name: 'Milltown', x: 39, y: 26 },
    cowper: { name: 'Cowper', x: 38.5, y: 23.5 },
    beechwood: { name: 'Beechwood', x: 38.5, y: 21.5 },
    ranelagh: { name: 'Ranelagh', x: 38, y: 19.5 },
    charlemont: { name: 'Charlemont', x: 38, y: 17.5 },
    harcourt: { name: 'Harcourt', x: 36, y: 16 },
    'st-stephen-s-green': { name: 'St. Stephen\'s Green', x: 36, y: 13.5 },
    dawson: { name: 'Dawson', x: 37, y: 12 },
    westmoreland: { name: 'Westmoreland', x: 35.5, y: 11 },
    'o-connell-gpo': { name: 'O\'Connell - GPO', x: 36, y: 9 },
    'o-connell-upper': { name: 'O\'Connell Upper', x: 36, y: 6.5 },
    dominick: { name: 'Dominick', x: 34.5, y: 8 },
    'broadstone-university': { name: 'Broadstone - University', x: 33, y: 6.5 },
    grangegorman: { name: 'Grangegorman', x: 31.5, y: 5 },
    phibsborough: { name: 'Phibsborough', x: 31.5, y: 3 },
    cabra: { name: 'Cabra', x: 30.5, y: 1.5 },
    broombridge: { name: 'Broombridge', x: 29, y: 0 },
    parnell: { name: 'Parnell', x: 34.5, y: 6 },
    marlborough: { name: 'Marlborough', x: 36.5, y: 7.5 },
    trinity: { name: 'Trinity', x: 37, y: 10 },
  },
};
