// Düsseldorf's Stadtbahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'dusseldorf',
  name: 'Düsseldorf',
  system: 'Stadtbahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'u70',
      short: 'U70',
      name: 'Subway U70',
      colour: '#70b1d0',
      text: '#1a1a1a',
      minutes: 3,
      branches: [
        ['handelszentrum-moskauer-strasse', 'hauptbahnhof', 'oststrasse', 'steinstrasse-konigsallee', 'heinrich-heine-allee', 'tonhalle-ehrenhof', 'belsenplatz', 'prinzenallee', 'dusseldorf-lorick', 'meerbusch-buderich-landsknecht', 'haus-meer', 'bovert', 'hoterheide', 'grundend', 'konigshof', 'diessem', 'krefeld-hbf', 'rheinstrasse'],
      ],
    },
    {
      id: 'u71',
      short: 'U71',
      name: 'Subway U71',
      colour: '#59c6f2',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['hellriegelstrasse', 'krahkampweg', 'volmerswerther-strasse', 'aachener-platz', 'sudring', 'suitbertusstrasse', 'bilk-s', 'kirchplatz', 'graf-adolf-platz', 'benrather-strasse-u', 'heinrich-heine-allee', 'schadowstrasse', 'pempelforter-strasse', 'wehrhahn-s', 'uhlandstrasse', 'schillerplatz', 'brehmplatz', 'grunerstrasse', 'hansaplatz', 'heinrichstrasse', 'haeselerstrasse', 'am-schein', 'rath-mitte-s', 'rotdornstrasse', 'rath-s'],
      ],
    },
    {
      id: 'u72',
      short: 'U72',
      name: 'Subway U72',
      colour: '#25b8c5',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['ratingen-mitte', 'weststrasse', 'europaring', 'gerhardstrasse', 'ratingen-felderhof', 'dusseldorf-hubertushain', 'hirschweg', 'oberrath', 'rather-waldstadion', 'rather-broich', 'morsenbroicher-weg', 'graf-recke-strasse', 'vautierstrasse', 'schluterstrasse-arbeitsagentur', 'engerstrasse', 'lindemannstrasse', 'uhlandstrasse', 'wehrhahn-s', 'pempelforter-strasse', 'schadowstrasse', 'heinrich-heine-allee', 'benrather-strasse-u', 'graf-adolf-platz', 'kirchplatz', 'bilk-s', 'karolingerplatz', 'auf-m-hennekamp', 'uni-kliniken', 'universitat-nord-christophstrasse', 'sudpark', 'werstener-dorfstrasse', 'opladener-strasse', 'ickerswarder-strasse', 'elbruchstrasse', 'holthausen', 'niederheid', 'am-trippelsberg', 'schone-aussicht', 'kappeler-strasse', 'schloss-benrath', 'urdenbacher-allee', 'benrath-s', 'benrath-betriebshof'],
      ],
    },
    {
      id: 'u73',
      short: 'U73',
      name: 'Subway U73',
      colour: '#4465ad',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['gerresheim-s', 'morper-strasse', 'hardenbergstrasse', 'dorpfeldstrasse', 'schonaustrasse', 'gerresheim-rathaus', 'von-gahlen-strasse', 'friedingstrasse', 'auf-der-hardt-lvr-klinikum', 'pohlenweg', 'staufenplatz', 'schluterstrasse-arbeitsagentur', 'engerstrasse', 'lindemannstrasse', 'uhlandstrasse', 'wehrhahn-s', 'pempelforter-strasse', 'schadowstrasse', 'heinrich-heine-allee', 'benrather-strasse-u', 'graf-adolf-platz', 'kirchplatz', 'bilk-s', 'karolingerplatz', 'auf-m-hennekamp', 'uni-kliniken', 'universitat-nord-christophstrasse', 'sudpark', 'universitat-ost-botanischer-garten'],
      ],
    },
    {
      id: 'u75',
      short: 'U75',
      name: 'Subway U75',
      colour: '#008fc2',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['vennhauser-allee', 'alt-eller', 'eller-mitte-s', 'jagerstrasse', 'am-hackenbruch', 'schlesische-strasse', 'lierenfeld-betriebshof', 'ronsdorfer-strasse', 'kettwiger-strasse', 'handelszentrum-moskauer-strasse', 'hauptbahnhof', 'oststrasse', 'steinstrasse-konigsallee', 'heinrich-heine-allee', 'tonhalle-ehrenhof', 'luegplatz', 'barbarossaplatz', 'belsenplatz', 'drususstrasse', 'heerdter-krankenhaus', 'nikolaus-knopp-platz', 'heesenstrasse', 'aldekerkstrasse', 'handweiser', 'vogesenstrasse', 'am-kaiser', 'blucherstrasse', 'neuss-hbf'],
      ],
    },
    {
      id: 'u76',
      short: 'U76',
      name: 'Subway U76',
      colour: '#0063af',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['holthausen', 'elbruchstrasse', 'ickerswarder-strasse', 'opladener-strasse', 'werstener-dorfstrasse', 'provinzialplatz', 'kaiserslauterner-strasse', 'oberbilk-s', 'ellerstrasse', 'oberbilker-markt-warschauer-strasse', 'hauptbahnhof', 'oststrasse', 'steinstrasse-konigsallee', 'heinrich-heine-allee', 'tonhalle-ehrenhof', 'luegplatz', 'barbarossaplatz', 'belsenplatz', 'comenius-gymnasium', 'heerdter-sandberg', 'prinzenallee', 'lohweg', 'loricker-strasse', 'dusseldorf-lorick', 'meerbusch-buderich-landsknecht', 'forsthaus', 'haus-meer', 'bovert', 'kamperweg', 'hoterheide', 'meerbusch-gorgesheide', 'grundend', 'fischeln', 'konigshof', 'diessem', 'krefeld-hbf', 'rheinstrasse'],
      ],
    },
    {
      id: 'u77',
      short: 'U77',
      name: 'Subway U77',
      colour: '#7197cf',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['am-seestern', 'prinzenallee', 'heerdter-sandberg', 'comenius-gymnasium', 'belsenplatz', 'barbarossaplatz', 'luegplatz', 'tonhalle-ehrenhof', 'heinrich-heine-allee', 'steinstrasse-konigsallee', 'oststrasse', 'hauptbahnhof', 'handelszentrum-moskauer-strasse', 'kettwiger-strasse', 'ronsdorfer-strasse', 'lierenfeld-betriebshof'],
      ],
    },
    {
      id: 'u78',
      short: 'U78',
      name: 'Subway U78',
      colour: '#009adf',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['hauptbahnhof', 'oststrasse', 'steinstrasse-konigsallee', 'heinrich-heine-allee', 'ergo-platz-klever-strasse', 'kennedydamm', 'golzheimer-platz', 'theodor-heuss-brucke', 'reeser-platz', 'nordpark-aquazoo', 'messe-ost-stockumer-kirchstrasse', 'freiligrathplatz', 'morikestrasse', 'sportpark-nord-europaplatz', 'merkur-spiel-arena-messe-nord'],
        ['hauptbahnhof', 'oststrasse', 'steinstrasse-konigsallee', 'heinrich-heine-allee', 'ergo-platz-klever-strasse', 'kennedydamm', 'golzheimer-platz', 'theodor-heuss-brucke', 'reeser-platz', 'nordpark-aquazoo', 'messe-ost-stockumer-kirchstrasse', 'freiligrathplatz', 'morikestrasse', 'merkur-spiel-arena-messe-nord'],
      ],
    },
    {
      id: 'u79',
      short: 'U79',
      name: 'Subway U79',
      colour: '#009a93',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['duisburg-meiderich-bf', 'auf-dem-damm', 'duissern', 'duisburg-hauptbahnhof-u', 'konig-heinrich-platz', 'steinsche-gasse', 'platanenhof', 'musfeldstrasse', 'kremerstrasse', 'karl-jarres-strasse', 'grunewald', 'grunewald-betriebshof', 'kulturstrasse', 'im-schlenk', 'waldfriedhof', 'munchener-strasse', 'sittardsberg', 'muhlenkamp', 'st-anna-klinik', 'kesselsberg', 'froschenteich', 'wittlaer', 'am-muhlenacker', 'kalkumer-schlossallee', 'klemensplatz', 'kittelbachstrasse', 'alte-landstrasse', 'lohausen', 'freiligrathplatz', 'messe-ost-stockumer-kirchstrasse', 'nordpark-aquazoo', 'reeser-platz', 'theodor-heuss-brucke', 'golzheimer-platz', 'kennedydamm', 'ergo-platz-klever-strasse', 'heinrich-heine-allee', 'steinstrasse-konigsallee', 'oststrasse', 'hauptbahnhof', 'oberbilker-markt-warschauer-strasse', 'ellerstrasse', 'oberbilk-s', 'kaiserslauterner-strasse', 'provinzialplatz', 'werstener-dorfstrasse', 'sudpark', 'universitat-ost-botanischer-garten'],
      ],
    },
  ],
  times: {
    'handelszentrum-moskauer-strasse hauptbahnhof': 2,
    'hauptbahnhof oststrasse': 1,
    'oststrasse steinstrasse-konigsallee': 1,
    'steinstrasse-konigsallee heinrich-heine-allee': 1,
    'heinrich-heine-allee tonhalle-ehrenhof': 2,
    'tonhalle-ehrenhof belsenplatz': 4,
    'meerbusch-buderich-landsknecht haus-meer': 5,
    'bovert hoterheide': 4,
    'hoterheide grundend': 7,
    'grundend konigshof': 4,
    'diessem krefeld-hbf': 2,
    'krefeld-hbf rheinstrasse': 2,
    'brehmplatz grunerstrasse': 2,
    'heinrichstrasse haeselerstrasse': 2,
    'gerhardstrasse ratingen-felderhof': 2,
    'ratingen-felderhof dusseldorf-hubertushain': 2,
    'rather-waldstadion rather-broich': 2,
    'morsenbroicher-weg graf-recke-strasse': 2,
    'vautierstrasse schluterstrasse-arbeitsagentur': 2,
    'schluterstrasse-arbeitsagentur engerstrasse': 2,
    'uni-kliniken universitat-nord-christophstrasse': 2,
    'sudpark werstener-dorfstrasse': 2,
    'werstener-dorfstrasse opladener-strasse': 2,
    'ickerswarder-strasse elbruchstrasse': 2,
    'elbruchstrasse holthausen': 2,
    'holthausen niederheid': 2,
    'niederheid am-trippelsberg': 2,
    'am-trippelsberg schone-aussicht': 2,
    'kappeler-strasse schloss-benrath': 2,
    'auf-der-hardt-lvr-klinikum pohlenweg': 2,
    'pohlenweg staufenplatz': 2,
    'staufenplatz schluterstrasse-arbeitsagentur': 2,
    'schlesische-strasse lierenfeld-betriebshof': 2,
    'ronsdorfer-strasse kettwiger-strasse': 2,
    'tonhalle-ehrenhof luegplatz': 2,
    'belsenplatz drususstrasse': 2,
    'drususstrasse heerdter-krankenhaus': 2,
    'am-kaiser blucherstrasse': 2,
    'blucherstrasse neuss-hbf': 3,
    'ickerswarder-strasse opladener-strasse': 1,
    'provinzialplatz kaiserslauterner-strasse': 1,
    'kaiserslauterner-strasse oberbilk-s': 1,
    'ellerstrasse oberbilker-markt-warschauer-strasse': 1,
    'luegplatz barbarossaplatz': 1,
    'barbarossaplatz belsenplatz': 1,
    'belsenplatz comenius-gymnasium': 1,
    'comenius-gymnasium heerdter-sandberg': 1,
    'heerdter-sandberg prinzenallee': 1,
    'prinzenallee lohweg': 1,
    'lohweg loricker-strasse': 1,
    'loricker-strasse dusseldorf-lorick': 1,
    'dusseldorf-lorick meerbusch-buderich-landsknecht': 3,
    'meerbusch-buderich-landsknecht forsthaus': 4,
    'haus-meer bovert': 3,
    'meerbusch-gorgesheide grundend': 5,
    'fischeln konigshof': 3,
    'konigshof diessem': 3,
    'luegplatz tonhalle-ehrenhof': 2,
    'tonhalle-ehrenhof heinrich-heine-allee': 2,
    'hauptbahnhof handelszentrum-moskauer-strasse': 2,
    'kettwiger-strasse ronsdorfer-strasse': 2,
    'heinrich-heine-allee ergo-platz-klever-strasse': 3,
    'messe-ost-stockumer-kirchstrasse freiligrathplatz': 2,
    'morikestrasse sportpark-nord-europaplatz': 2,
    'morikestrasse merkur-spiel-arena-messe-nord': 2,
    'auf-dem-damm duissern': 6,
    'duissern duisburg-hauptbahnhof-u': 2,
    'duisburg-hauptbahnhof-u konig-heinrich-platz': 2,
    'steinsche-gasse platanenhof': 2,
    'kremerstrasse karl-jarres-strasse': 2,
    'karl-jarres-strasse grunewald': 2,
    'im-schlenk waldfriedhof': 2,
    'waldfriedhof munchener-strasse': 2,
    'munchener-strasse sittardsberg': 2,
    'sittardsberg muhlenkamp': 2,
    'muhlenkamp st-anna-klinik': 2,
    'st-anna-klinik kesselsberg': 2,
    'kesselsberg froschenteich': 4,
    'froschenteich wittlaer': 5,
    'am-muhlenacker kalkumer-schlossallee': 2,
    'kalkumer-schlossallee klemensplatz': 2,
    'klemensplatz kittelbachstrasse': 2,
    'kittelbachstrasse alte-landstrasse': 2,
    'alte-landstrasse lohausen': 4,
    'lohausen freiligrathplatz': 2,
    'freiligrathplatz messe-ost-stockumer-kirchstrasse': 2,
    'ergo-platz-klever-strasse heinrich-heine-allee': 3,
    'hauptbahnhof oberbilker-markt-warschauer-strasse': 2,
    'ellerstrasse oberbilk-s': 2,
    'provinzialplatz werstener-dorfstrasse': 2,
    'werstener-dorfstrasse sudpark': 2,
  },
  stations: {
    'duisburg-meiderich-bf': { name: 'Duisburg-Meiderich Bf', x: 36.5, y: 0 },
    'auf-dem-damm': { name: 'Auf dem Damm', x: 36.5, y: 2 },
    duissern: { name: 'Duissern', x: 36.5, y: 4.5 },
    'duisburg-hauptbahnhof-u': { name: 'Duisburg Hauptbahnhof U', x: 36.5, y: 6.5 },
    'konig-heinrich-platz': { name: 'König-Heinrich-Platz', x: 35, y: 8 },
    'steinsche-gasse': { name: 'Steinsche Gasse', x: 33.5, y: 9.5 },
    platanenhof: { name: 'Platanenhof', x: 32, y: 11.5 },
    musfeldstrasse: { name: 'Musfeldstraße', x: 32, y: 13.5 },
    kremerstrasse: { name: 'Kremerstraße', x: 34, y: 14 },
    'karl-jarres-strasse': { name: 'Karl-Jarres-Straße', x: 34, y: 16.5 },
    grunewald: { name: 'Grunewald', x: 33.5, y: 19 },
    'grunewald-betriebshof': { name: 'Grunewald Betriebshof', x: 33.5, y: 21.5 },
    kulturstrasse: { name: 'Kulturstraße', x: 33.5, y: 24 },
    'im-schlenk': { name: 'Im Schlenk', x: 33, y: 26.5 },
    waldfriedhof: { name: 'Waldfriedhof', x: 33, y: 29.5 },
    'munchener-strasse': { name: 'Münchener Straße', x: 32.5, y: 32 },
    sittardsberg: { name: 'Sittardsberg', x: 32.5, y: 35 },
    muhlenkamp: { name: 'Mühlenkamp', x: 32.5, y: 38 },
    'st-anna-klinik': { name: 'St. Anna Klinik', x: 32, y: 41 },
    kesselsberg: { name: 'Kesselsberg', x: 32, y: 44 },
    froschenteich: { name: 'Froschenteich', x: 31.5, y: 47 },
    wittlaer: { name: 'Wittlaer', x: 31.5, y: 50 },
    'am-muhlenacker': { name: 'Am Mühlenacker', x: 31, y: 53 },
    'kalkumer-schlossallee': { name: 'Kalkumer Schloßallee', x: 31, y: 56 },
    klemensplatz: { name: 'Klemensplatz', x: 31, y: 58.5 },
    kittelbachstrasse: { name: 'Kittelbachstraße', x: 30.5, y: 61.5 },
    'alte-landstrasse': { name: 'Alte Landstraße', x: 30.5, y: 64.5 },
    lohausen: { name: 'Lohausen', x: 30.5, y: 67.5 },
    freiligrathplatz: { name: 'Freiligrathplatz', x: 30.5, y: 70 },
    'messe-ost-stockumer-kirchstrasse': { name: 'Messe Ost/Stockumer Kirchstraße', x: 30.5, y: 72.5 },
    'nordpark-aquazoo': { name: 'Nordpark/Aquazoo', x: 30, y: 75.5 },
    'reeser-platz': { name: 'Reeser Platz', x: 31.5, y: 77.5 },
    'theodor-heuss-brucke': { name: 'Theodor-Heuss-Brücke', x: 32.5, y: 79.5 },
    'golzheimer-platz': { name: 'Golzheimer Platz', x: 34, y: 81.5 },
    kennedydamm: { name: 'Kennedydamm', x: 35, y: 83 },
    'ergo-platz-klever-strasse': { name: 'ERGO-Platz/Klever Straße', x: 35, y: 85.5 },
    'heinrich-heine-allee': { name: 'Heinrich-Heine-Allee', x: 34.5, y: 88 },
    'steinstrasse-konigsallee': { name: 'Steinstraße/Königsallee', x: 36.5, y: 90 },
    oststrasse: { name: 'Oststraße', x: 38.5, y: 91.5 },
    hauptbahnhof: { name: 'Hauptbahnhof', x: 40.5, y: 93.5, aka: ['Düsseldorf Hauptbahnhof'] },
    'oberbilker-markt-warschauer-strasse': { name: 'Oberbilker Markt/Warschauer Straße', x: 42, y: 95 },
    ellerstrasse: { name: 'Ellerstraße', x: 43.5, y: 96.5 },
    'oberbilk-s': { name: 'Oberbilk S', x: 44, y: 98.5 },
    'kaiserslauterner-strasse': { name: 'Kaiserslauterner Straße', x: 44, y: 101 },
    provinzialplatz: { name: 'Provinzialplatz', x: 44.5, y: 103 },
    'werstener-dorfstrasse': { name: 'Werstener Dorfstraße', x: 44.5, y: 105 },
    sudpark: { name: 'Südpark', x: 42.5, y: 105 },
    'universitat-ost-botanischer-garten': { name: 'Universität Ost/Botanischer Garten', x: 41, y: 106.5 },
    'am-seestern': { name: 'Am Seestern', x: 26.5, y: 83 },
    prinzenallee: { name: 'Prinzenallee', x: 24.5, y: 83 },
    'heerdter-sandberg': { name: 'Heerdter Sandberg', x: 25.5, y: 84.5 },
    'comenius-gymnasium': { name: 'Comenius-Gymnasium', x: 26.5, y: 86 },
    belsenplatz: { name: 'Belsenplatz', x: 28, y: 85.5 },
    barbarossaplatz: { name: 'Barbarossaplatz', x: 29.5, y: 87 },
    luegplatz: { name: 'Luegplatz', x: 31, y: 88.5 },
    'tonhalle-ehrenhof': { name: 'Tonhalle/Ehrenhof', x: 31.5, y: 86.5 },
    'handelszentrum-moskauer-strasse': { name: 'Handelszentrum/Moskauer Straße', x: 42.5, y: 93.5 },
    'kettwiger-strasse': { name: 'Kettwiger Straße', x: 45, y: 93.5 },
    'ronsdorfer-strasse': { name: 'Ronsdorfer Straße', x: 46.5, y: 95 },
    'lierenfeld-betriebshof': { name: 'Lierenfeld Betriebshof', x: 48, y: 96.5 },
    'vennhauser-allee': { name: 'Vennhauser Allee', x: 55.5, y: 103 },
    'alt-eller': { name: 'Alt Eller', x: 54, y: 101.5 },
    'eller-mitte-s': { name: 'Eller Mitte S', x: 52.5, y: 103 },
    jagerstrasse: { name: 'Jägerstraße', x: 52.5, y: 101 },
    'am-hackenbruch': { name: 'Am Hackenbruch', x: 51, y: 99.5 },
    'schlesische-strasse': { name: 'Schlesische Straße', x: 49.5, y: 98 },
    drususstrasse: { name: 'Drususstraße', x: 26.5, y: 87.5 },
    'heerdter-krankenhaus': { name: 'Heerdter Krankenhaus', x: 24.5, y: 87.5 },
    'nikolaus-knopp-platz': { name: 'Nikolaus-Knopp-Platz', x: 23, y: 88 },
    heesenstrasse: { name: 'Heesenstraße', x: 21, y: 88 },
    aldekerkstrasse: { name: 'Aldekerkstraße', x: 19, y: 88 },
    handweiser: { name: 'Handweiser', x: 17, y: 88.5 },
    vogesenstrasse: { name: 'Vogesenstraße', x: 17, y: 90.5 },
    'am-kaiser': { name: 'Am Kaiser', x: 17, y: 92.5 },
    blucherstrasse: { name: 'Blücherstraße', x: 15.5, y: 94 },
    'neuss-hbf': { name: 'Neuss Hbf', x: 14, y: 95.5 },
    holthausen: { name: 'Holthausen', x: 51, y: 111.5 },
    elbruchstrasse: { name: 'Elbruchstraße', x: 49.5, y: 110 },
    'ickerswarder-strasse': { name: 'Ickerswarder Straße', x: 48, y: 108.5 },
    'opladener-strasse': { name: 'Opladener Straße', x: 46.5, y: 106.5 },
    lohweg: { name: 'Lohweg', x: 23.5, y: 84.5 },
    'loricker-strasse': { name: 'Löricker Straße', x: 22.5, y: 83 },
    'dusseldorf-lorick': { name: 'Düsseldorf-Lörick', x: 21, y: 81.5 },
    'meerbusch-buderich-landsknecht': { name: 'Meerbusch-Büderich, Landsknecht', x: 18.5, y: 79 },
    forsthaus: { name: 'Forsthaus', x: 17, y: 78 },
    'haus-meer': { name: 'Haus Meer', x: 15.5, y: 76.5 },
    bovert: { name: 'Bovert', x: 12.5, y: 74.5 },
    kamperweg: { name: 'Kamperweg', x: 11.5, y: 73.5 },
    hoterheide: { name: 'Hoterheide', x: 10, y: 72 },
    'meerbusch-gorgesheide': { name: 'Meerbusch-Görgesheide', x: 8.5, y: 71 },
    grundend: { name: 'Grundend', x: 7.5, y: 69.5 },
    fischeln: { name: 'Fischeln', x: 6, y: 68.5 },
    konigshof: { name: 'Königshof', x: 5, y: 67.5 },
    diessem: { name: 'Dießem', x: 3, y: 66 },
    'krefeld-hbf': { name: 'Krefeld Hbf', x: 1.5, y: 64 },
    rheinstrasse: { name: 'Rheinstraße', x: 0, y: 62.5 },
    morikestrasse: { name: 'Mörikestraße', x: 29, y: 72 },
    'merkur-spiel-arena-messe-nord': { name: 'MERKUR SPIEL-ARENA/Messe Nord', x: 27.5, y: 73.5 },
    'sportpark-nord-europaplatz': { name: 'Sportpark Nord/Europaplatz', x: 27, y: 71.5 },
    hellriegelstrasse: { name: 'Hellriegelstraße', x: 33, y: 106 },
    krahkampweg: { name: 'Krahkampweg', x: 35, y: 105.5 },
    'volmerswerther-strasse': { name: 'Volmerswerther Straße', x: 33.5, y: 104 },
    'aachener-platz': { name: 'Aachener Platz', x: 35, y: 103 },
    sudring: { name: 'Südring', x: 34.5, y: 100.5 },
    suitbertusstrasse: { name: 'Suitbertusstraße', x: 34.5, y: 98.5 },
    'bilk-s': { name: 'Bilk S', x: 36, y: 97 },
    kirchplatz: { name: 'Kirchplatz', x: 35.5, y: 95 },
    'graf-adolf-platz': { name: 'Graf-Adolf-Platz', x: 35, y: 92.5 },
    'benrather-strasse-u': { name: 'Benrather Straße U', x: 34.5, y: 90.5 },
    schadowstrasse: { name: 'Schadowstraße', x: 37, y: 88.5 },
    'pempelforter-strasse': { name: 'Pempelforter Straße', x: 39, y: 88.5 },
    'wehrhahn-s': { name: 'Wehrhahn S', x: 41, y: 89 },
    uhlandstrasse: { name: 'Uhlandstraße', x: 43.5, y: 89 },
    schillerplatz: { name: 'Schillerplatz', x: 42, y: 87.5 },
    brehmplatz: { name: 'Brehmplatz', x: 43, y: 86 },
    grunerstrasse: { name: 'Grunerstraße', x: 43, y: 84, aka: ['Düsseldorf Grunerstraße'] },
    hansaplatz: { name: 'Hansaplatz', x: 44.5, y: 83, aka: ['Düsseldorf Hansaplatz'] },
    heinrichstrasse: { name: 'Heinrichstraße', x: 43, y: 81.5 },
    haeselerstrasse: { name: 'Haeselerstraße', x: 44, y: 80 },
    'am-schein': { name: 'Am Schein', x: 45.5, y: 78.5 },
    'rath-mitte-s': { name: 'Rath Mitte S', x: 45.5, y: 76.5 },
    rotdornstrasse: { name: 'Rotdornstraße', x: 47, y: 76.5 },
    'rath-s': { name: 'Rath S', x: 48.5, y: 75.5 },
    'gerresheim-s': { name: 'Gerresheim S', x: 60.5, y: 94.5 },
    'morper-strasse': { name: 'Morper Straße', x: 60.5, y: 92.5 },
    hardenbergstrasse: { name: 'Hardenbergstraße', x: 59, y: 91.5 },
    dorpfeldstrasse: { name: 'Dörpfeldstraße', x: 57.5, y: 90 },
    schonaustrasse: { name: 'Schönaustraße', x: 59, y: 88.5 },
    'gerresheim-rathaus': { name: 'Gerresheim Rathaus', x: 59, y: 86.5 },
    'von-gahlen-strasse': { name: 'Von-Gahlen-Straße', x: 57.5, y: 88 },
    friedingstrasse: { name: 'Friedingstraße', x: 56, y: 86.5 },
    'auf-der-hardt-lvr-klinikum': { name: 'Auf der Hardt/LVR-Klinikum', x: 54.5, y: 85 },
    pohlenweg: { name: 'Pöhlenweg', x: 52.5, y: 85 },
    staufenplatz: { name: 'Staufenplatz', x: 50.5, y: 85 },
    'schluterstrasse-arbeitsagentur': { name: 'Schlüterstraße/Arbeitsagentur', x: 49, y: 86.5 },
    engerstrasse: { name: 'Engerstraße', x: 47, y: 87.5, aka: ['Düsseldorf Engerstraße'] },
    lindemannstrasse: { name: 'Lindemannstraße', x: 45.5, y: 89, aka: ['Düsseldorf Lindemannstraße'] },
    karolingerplatz: { name: 'Karolingerplatz', x: 36, y: 99 },
    'auf-m-hennekamp': { name: 'Auf\'m Hennekamp', x: 38, y: 100.5 },
    'uni-kliniken': { name: 'Uni-Kliniken', x: 39.5, y: 102 },
    'universitat-nord-christophstrasse': { name: 'Universität Nord / Christophstraße', x: 41, y: 103.5 },
    'ratingen-mitte': { name: 'Ratingen Mitte', x: 57.5, y: 64.5 },
    weststrasse: { name: 'Weststraße', x: 55.5, y: 64.5 },
    europaring: { name: 'Europaring', x: 54, y: 66 },
    gerhardstrasse: { name: 'Gerhardstraße', x: 54, y: 68 },
    'ratingen-felderhof': { name: 'Ratingen, Felderhof', x: 52.5, y: 69.5 },
    'dusseldorf-hubertushain': { name: 'Düsseldorf-Hubertushain', x: 52.5, y: 71.5 },
    hirschweg: { name: 'Hirschweg', x: 51, y: 73 },
    oberrath: { name: 'Oberrath', x: 49.5, y: 74.5 },
    'rather-waldstadion': { name: 'Rather Waldstadion', x: 49.5, y: 76.5 },
    'rather-broich': { name: 'Rather Broich', x: 49.5, y: 78.5 },
    'morsenbroicher-weg': { name: 'Mörsenbroicher Weg', x: 49.5, y: 80.5 },
    'graf-recke-strasse': { name: 'Graf-Recke-Straße', x: 49, y: 82.5 },
    vautierstrasse: { name: 'Vautierstraße', x: 49, y: 84.5 },
    niederheid: { name: 'Niederheid', x: 52.5, y: 113 },
    'am-trippelsberg': { name: 'Am Trippelsberg', x: 54, y: 114.5 },
    'schone-aussicht': { name: 'Schöne Aussicht', x: 55.5, y: 116 },
    'kappeler-strasse': { name: 'Kappeler Straße', x: 58, y: 116 },
    'schloss-benrath': { name: 'Schloss Benrath', x: 60, y: 116 },
    'urdenbacher-allee': { name: 'Urdenbacher Allee', x: 62, y: 116 },
    'benrath-s': { name: 'Benrath S', x: 63.5, y: 117.5 },
    'benrath-betriebshof': { name: 'Benrath Betriebshof', x: 65.5, y: 117.5 },
  },
};
