// Edmonton's LRT, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'edmonton',
  name: 'Edmonton',
  system: 'LRT',
  country: 'Canada',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'capital',
      short: 'C',
      name: 'Capital Line',
      colour: '#3a59a9',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['clareview', 'belvedere', 'coliseum', 'stadium', 'churchill', 'central', 'bay-enterprise-square', 'corona', 'government-centre', 'university', 'health-sciences-jubilee', 'mckernan-belgravia', 'south-campus-fort-edmonton-park', 'southgate', 'century-park'],
      ],
    },
    {
      id: 'metro',
      short: 'M',
      name: 'Metro Line',
      colour: '#fc6357',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['health-sciences-jubilee', 'university', 'government-centre', 'corona', 'bay-enterprise-square', 'central', 'churchill', 'macewan', 'kingsway-royal-alex', 'nait-blatchford-market'],
      ],
    },
    {
      id: 'valley',
      short: 'V',
      name: 'Valley Line',
      colour: '#009158',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['mill-woods', 'grey-nuns', 'millbourne-woodvale', 'davies', 'avonmore', 'bonnie-doon', 'holyrood', 'strathearn', 'muttart', 'quarters', 'churchill', 's-102-street'],
      ],
    },
  ],
  times: {
    'clareview belvedere': 4,
    'belvedere coliseum': 5,
    'stadium churchill': 5,
    'churchill central': 1,
    'central bay-enterprise-square': 1,
    'bay-enterprise-square corona': 1,
    'corona government-centre': 2,
    'university health-sciences-jubilee': 2,
    'health-sciences-jubilee mckernan-belgravia': 2,
    'south-campus-fort-edmonton-park southgate': 4,
    'southgate century-park': 6,
    'university government-centre': 3,
    'corona bay-enterprise-square': 1,
    'bay-enterprise-square central': 1,
    'central churchill': 1,
    'macewan kingsway-royal-alex': 3,
    'kingsway-royal-alex nait-blatchford-market': 3,
    'grey-nuns millbourne-woodvale': 3,
    'millbourne-woodvale davies': 6,
    'davies avonmore': 3,
    'avonmore bonnie-doon': 3,
    'bonnie-doon holyrood': 2,
    'strathearn muttart': 3,
    'muttart quarters': 2,
  },
  stations: {
    clareview: { name: 'Clareview', x: 11.5, y: 0 },
    belvedere: { name: 'Belvedere', x: 10, y: 1.5 },
    coliseum: { name: 'Coliseum', x: 8.5, y: 3 },
    stadium: { name: 'Stadium', x: 7, y: 4.5 },
    churchill: { name: 'Churchill', x: 5.5, y: 6 },
    central: { name: 'Central', x: 5.5, y: 8 },
    'bay-enterprise-square': { name: 'Bay/Enterprise Square', x: 4, y: 9.5 },
    corona: { name: 'Corona', x: 2.5, y: 8 },
    'government-centre': { name: 'Government Centre', x: 2.5, y: 10 },
    university: { name: 'University', x: 1.5, y: 11.5 },
    'health-sciences-jubilee': { name: 'Health Sciences/Jubilee', x: 0, y: 13 },
    'mckernan-belgravia': { name: 'McKernan/Belgravia', x: 0, y: 15 },
    'south-campus-fort-edmonton-park': { name: 'South Campus/Fort Edmonton Park', x: 0, y: 17 },
    southgate: { name: 'Southgate', x: 0, y: 19 },
    'century-park': { name: 'Century Park', x: 0, y: 21 },
    macewan: { name: 'MacEwan', x: 3.5, y: 6 },
    'kingsway-royal-alex': { name: 'Kingsway/Royal Alex', x: 3.5, y: 4 },
    'nait-blatchford-market': { name: 'NAIT/Blatchford Market', x: 2, y: 2.5 },
    'mill-woods': { name: 'Mill Woods', x: 10.5, y: 23 },
    'grey-nuns': { name: 'Grey Nuns', x: 10.5, y: 21 },
    'millbourne-woodvale': { name: 'Millbourne/Woodvale', x: 10.5, y: 19 },
    davies: { name: 'Davies', x: 10.5, y: 17 },
    avonmore: { name: 'Avonmore', x: 10.5, y: 15 },
    'bonnie-doon': { name: 'Bonnie Doon', x: 10.5, y: 13 },
    holyrood: { name: 'Holyrood', x: 10.5, y: 11 },
    strathearn: { name: 'Strathearn', x: 9, y: 9.5 },
    muttart: { name: 'Muttart', x: 7, y: 9.5 },
    quarters: { name: 'Quarters', x: 7, y: 7.5 },
    's-102-street': { name: '102 Street', x: 4, y: 7.5 },
  },
};
