// Florence's Tramvia, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'florence',
  name: 'Florence',
  system: 'Tramvia',
  country: 'Italy',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 't1',
      short: 'T1',
      name: 'T1 Leonardo',
      colour: '#254395',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['careggi-ospedale', 'morgagni-universita', 'dalmazia', 'pisacane', 'leopoldo', 'muratori-stazione-statuto', 'statuto', 'strozzi-fallaci', 'fortezza', 'valfonda-stazione-santa-maria-novella', 'alamanni-stazione-santa-maria-novella', 'porta-al-prato-leopolda-parco-della-musica', 'cascine-olmi-carlo-monni', 'paolo-uccello-arno', 'sansovino', 'batoni', 'talenti', 'federiga-foggini', 'arcipressi-ronco-corto', 'nenni-torregalli-lupi-di-toscana', 'aldo-moro', 'resistenza-pantin', 'de-andre-ciliegi', 'villa-costanza'],
        ['villa-costanza', 'de-andre-ciliegi', 'resistenza-pantin', 'aldo-moro', 'nenni-torregalli-lupi-di-toscana', 'arcipressi-ronco-corto', 'federiga-foggini', 'talenti', 'batoni', 'sansovino', 'paolo-uccello-arno', 'cascine-olmi-carlo-monni', 'porta-al-prato-leopolda-parco-della-musica', 'alamanni-stazione-santa-maria-novella', 'valfonda-stazione-santa-maria-novella', 'fortezza', 'strozzi-fallaci', 'statuto', 'muratori-stazione-statuto', 'leopoldo', 'poggetto', 'vittorio-emanuele-ii', 'morgagni-universita', 'careggi-ospedale'],
      ],
    },
    {
      id: 't2',
      short: 'T2',
      name: 'T2 Vespucci',
      colour: '#5d3988',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['san-marco-universita', 'la-marmora-orto-botanico', 'liberta-parterre', 'lavagnini-poliziano', 'lavagnini-fortezza', 'fortezza', 'valfonda-stazione-santa-maria-novella', 'alamanni-stazione-santa-maria-novella', 'rosselli', 'belfiore', 'redi', 'ponte-all-asse', 'buonsignori-liceo-da-vinci', 'san-donato-universita', 'novoli-regione-toscana', 'novoli-torre-degli-agli', 'novoli-palazzi-rossi', 'guidoni', 'peretola-aeroporto'],
        ['peretola-aeroporto', 'guidoni', 'novoli-palazzi-rossi', 'novoli-torre-degli-agli', 'novoli-regione-toscana', 'san-donato-universita', 'buonsignori-liceo-da-vinci', 'ponte-all-asse', 'redi', 'belfiore', 'rosselli', 'alamanni-stazione-santa-maria-novella', 'valfonda-stazione-santa-maria-novella', 'fortezza', 'lavagnini-fortezza', 'lavagnini-poliziano', 'liberta-parterre', 'cavour', 'san-marco-universita'],
      ],
    },
  ],
  times: {
    'alamanni-stazione-santa-maria-novella porta-al-prato-leopolda-parco-della-musica': 2,
    'arcipressi-ronco-corto nenni-torregalli-lupi-di-toscana': 2,
    'nenni-torregalli-lupi-di-toscana aldo-moro': 2,
    'aldo-moro resistenza-pantin': 2,
    'resistenza-pantin aldo-moro': 2,
    'aldo-moro nenni-torregalli-lupi-di-toscana': 2,
    'nenni-torregalli-lupi-di-toscana arcipressi-ronco-corto': 2,
    'porta-al-prato-leopolda-parco-della-musica alamanni-stazione-santa-maria-novella': 2,
    'buonsignori-liceo-da-vinci san-donato-universita': 2,
    'guidoni peretola-aeroporto': 2,
    'peretola-aeroporto guidoni': 2,
    'san-donato-universita buonsignori-liceo-da-vinci': 2,
  },
  stations: {
    'careggi-ospedale': { name: 'Careggi - Ospedale', x: 25, y: 0.5 },
    'morgagni-universita': { name: 'Morgagni - Università', x: 23.5, y: 2 },
    dalmazia: { name: 'Dalmazia', x: 22, y: 3.5 },
    pisacane: { name: 'Pisacane', x: 23.5, y: 5.5 },
    leopoldo: { name: 'Leopoldo', x: 25, y: 7 },
    'muratori-stazione-statuto': { name: 'Muratori - Stazione Statuto', x: 26, y: 8 },
    statuto: { name: 'Statuto', x: 27.5, y: 9.5 },
    'strozzi-fallaci': { name: 'Strozzi - Fallaci', x: 27.5, y: 11.5 },
    fortezza: { name: 'Fortezza', x: 26, y: 13 },
    'valfonda-stazione-santa-maria-novella': { name: 'Valfonda - Stazione Santa Maria Novella', x: 26, y: 15 },
    'alamanni-stazione-santa-maria-novella': { name: 'Alamanni - Stazione Santa Maria Novella', x: 24, y: 15 },
    'porta-al-prato-leopolda-parco-della-musica': { name: 'Porta al Prato - Leopolda (Parco della Musica)', x: 22, y: 15.5 },
    'cascine-olmi-carlo-monni': { name: 'Cascine (Olmi - Carlo Monni)', x: 19.5, y: 15.5 },
    'paolo-uccello-arno': { name: 'Paolo Uccello (Arno)', x: 17.5, y: 15.5 },
    sansovino: { name: 'Sansovino', x: 15.5, y: 15.5 },
    batoni: { name: 'Batoni', x: 13.5, y: 16 },
    talenti: { name: 'Talenti', x: 11.5, y: 16 },
    'federiga-foggini': { name: 'Federiga (Foggini)', x: 9.5, y: 17.5 },
    'arcipressi-ronco-corto': { name: 'Arcipressi (Ronco Corto)', x: 8, y: 19 },
    'nenni-torregalli-lupi-di-toscana': { name: 'Nenni - Torregalli (Lupi di Toscana)', x: 6.5, y: 20.5 },
    'aldo-moro': { name: 'Aldo Moro', x: 5, y: 22 },
    'resistenza-pantin': { name: 'Resistenza (Pantin)', x: 3.5, y: 23.5 },
    'de-andre-ciliegi': { name: 'De André (Ciliegi)', x: 2, y: 25 },
    'villa-costanza': { name: 'Villa Costanza', x: 0, y: 25 },
    poggetto: { name: 'Poggetto', x: 25, y: 5 },
    'vittorio-emanuele-ii': { name: 'Vittorio Emanuele II', x: 23.5, y: 3.5 },
    'san-marco-universita': { name: 'San Marco Università', x: 30.5, y: 15 },
    'la-marmora-orto-botanico': { name: 'La Marmora Orto Botanico', x: 32, y: 13.5 },
    'liberta-parterre': { name: 'Libertà Parterre', x: 31.5, y: 11.5 },
    'lavagnini-poliziano': { name: 'Lavagnini Poliziano', x: 29.5, y: 11.5 },
    'lavagnini-fortezza': { name: 'Lavagnini Fortezza', x: 28, y: 13 },
    rosselli: { name: 'Rosselli', x: 24, y: 13 },
    belfiore: { name: 'Belfiore', x: 22.5, y: 12 },
    redi: { name: 'Redi', x: 22.5, y: 10 },
    'ponte-all-asse': { name: 'Ponte all\'Asse', x: 21, y: 8.5 },
    'buonsignori-liceo-da-vinci': { name: 'Buonsignori - Liceo Da Vinci', x: 19.5, y: 7 },
    'san-donato-universita': { name: 'San Donato - Università', x: 17.5, y: 7 },
    'novoli-regione-toscana': { name: 'Novoli - Regione Toscana', x: 16, y: 5.5 },
    'novoli-torre-degli-agli': { name: 'Novoli - Torre degli Agli', x: 14.5, y: 4 },
    'novoli-palazzi-rossi': { name: 'Novoli - Palazzi Rossi', x: 13, y: 3 },
    guidoni: { name: 'Guidoni', x: 11.5, y: 1.5 },
    'peretola-aeroporto': { name: 'Peretola Aeroporto', x: 10.5, y: 0 },
    cavour: { name: 'Cavour', x: 30.5, y: 13 },
  },
};
