// Frankfurt's U-Bahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'frankfurt',
  name: 'Frankfurt',
  system: 'U-Bahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'u1',
      short: 'U1',
      name: 'U1',
      colour: '#b8282e',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['ginnheim-mitte', 'ginnheim-niddapark', 'romerstadt', 'nordwestzentrum', 'heddernheimer-landstrasse', 'zeilweg', 'heddernheim', 'weisser-stein', 'lindenbaum', 'hugelstrasse', 'fritz-tarnow-strasse', 'dornbusch', 'miquel-adickesallee', 'holzhausenstrasse', 'gruneburgweg', 'eschenheimer-tor', 'hauptwache', 'willy-brandt-platz', 'schweizer-platz', 'sudbahnhof'],
      ],
    },
    {
      id: 'u2',
      short: 'U2',
      name: 'U2',
      colour: '#00a54f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['gonzenheim', 'ober-eschbach', 'nieder-eschbach', 'bonames-mitte', 'kalbach', 'riedwiese-mertonviertel', 'sandelmuhle', 'heddernheim', 'weisser-stein', 'lindenbaum', 'hugelstrasse', 'fritz-tarnow-strasse', 'dornbusch', 'miquel-adickesallee', 'holzhausenstrasse', 'gruneburgweg', 'eschenheimer-tor', 'hauptwache', 'willy-brandt-platz', 'schweizer-platz', 'sudbahnhof'],
      ],
    },
    {
      id: 'u3',
      short: 'U3',
      name: 'U3',
      colour: '#4a5eaa',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hohemark', 'waldlust', 'rosengartchen', 'kupferhammer', 'glocknerwiese', 'lahnstrasse', 'oberursel-altstadt', 'oberursel-stadtmitte', 'oberursel-bahnhof', 'bommersheim', 'weisskirchen-ost', 'niederursel', 'wiesenau', 'zeilweg', 'heddernheim', 'weisser-stein', 'lindenbaum', 'hugelstrasse', 'fritz-tarnow-strasse', 'dornbusch', 'miquel-adickesallee', 'holzhausenstrasse', 'gruneburgweg', 'eschenheimer-tor', 'hauptwache', 'willy-brandt-platz', 'schweizer-platz', 'sudbahnhof'],
      ],
    },
    {
      id: 'u4',
      short: 'U4',
      name: 'U4',
      colour: '#f172ac',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['bockenheimer-warte', 'festhalle-messe', 'hauptbahnhof', 'willy-brandt-platz', 'dom-romer', 'konstablerwache', 'merianplatz', 'hohenstrasse', 'bornheim-mitte', 'seckbacher-landstrasse', 'schafflestrasse', 'gwinnerstrasse', 'kruppstrasse', 'hessen-center', 'enkheim'],
      ],
    },
    {
      id: 'u5',
      short: 'U5',
      name: 'U5',
      colour: '#007942',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['preungesheim', 'sigmund-freud-strasse', 'ronneburgstrasse', 'theobald-ziegler-strasse', 'feuerwehrstrasse', 'marbachweg-sozialzentrum', 'hauptfriedhof', 'deutsche-nationalbibliothek', 'glauburgstrasse', 'musterschule', 'konstablerwache', 'dom-romer', 'willy-brandt-platz', 'hauptbahnhof'],
        ['hauptbahnhof', 'willy-brandt-platz', 'dom-romer', 'konstablerwache', 'glauburgstrasse', 'deutsche-nationalbibliothek', 'hauptfriedhof', 'marbachweg-sozialzentrum', 'feuerwehrstrasse', 'theobald-ziegler-strasse', 'ronneburgstrasse', 'sigmund-freud-strasse', 'preungesheim'],
      ],
    },
    {
      id: 'u6',
      short: 'U6',
      name: 'U6',
      colour: '#007ec6',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hausen', 'grosse-nelkenstrasse', 'industriehof', 'kirchplatz', 'leipziger-strasse', 'bockenheimer-warte', 'westend', 'alte-oper', 'hauptwache', 'konstablerwache', 'zoo', 'ostbahnhof'],
      ],
    },
    {
      id: 'u7',
      short: 'U7',
      name: 'U7',
      colour: '#e4a024',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['enkheim', 'hessen-center', 'kruppstrasse', 'gwinnerstrasse', 'schafflestrasse', 'johanna-tesch-platz', 'eissporthalle-festplatz', 'parlamentsplatz', 'habsburgerallee', 'zoo', 'konstablerwache', 'hauptwache', 'alte-oper', 'westend', 'bockenheimer-warte', 'leipziger-strasse', 'kirchplatz', 'industriehof', 'fischstein', 'hausener-weg', 'stephan-heise-strasse', 'friedhof-westhausen', 'heerstrasse'],
      ],
    },
    {
      id: 'u8',
      short: 'U8',
      name: 'U8',
      colour: '#c77db5',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['riedberg', 'uni-campus-riedberg', 'niederursel', 'wiesenau', 'zeilweg', 'heddernheim', 'weisser-stein', 'lindenbaum', 'hugelstrasse', 'fritz-tarnow-strasse', 'dornbusch', 'miquel-adickesallee', 'holzhausenstrasse', 'gruneburgweg', 'eschenheimer-tor', 'hauptwache', 'willy-brandt-platz', 'schweizer-platz', 'sudbahnhof'],
      ],
    },
    {
      id: 'u9',
      short: 'U9',
      name: 'U9',
      colour: '#eed700',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['nieder-eschbach', 'bonames-mitte', 'kalbach', 'riedberg', 'uni-campus-riedberg', 'niederursel', 'wiesenau', 'heddernheimer-landstrasse', 'nordwestzentrum', 'romerstadt', 'ginnheim-niddapark', 'ginnheim-mitte'],
      ],
    },
  ],
  times: {
    'ginnheim-mitte ginnheim-niddapark': 1,
    'romerstadt nordwestzentrum': 1,
    'miquel-adickesallee holzhausenstrasse': 1,
    'holzhausenstrasse gruneburgweg': 1,
    'gruneburgweg eschenheimer-tor': 1,
    'eschenheimer-tor hauptwache': 1,
    'hauptwache willy-brandt-platz': 1,
    'ober-eschbach nieder-eschbach': 5,
    'nieder-eschbach bonames-mitte': 4,
    'bonames-mitte kalbach': 1,
    'kalbach riedwiese-mertonviertel': 4,
    'hohemark waldlust': 1,
    'waldlust rosengartchen': 1,
    'rosengartchen kupferhammer': 1,
    'kupferhammer glocknerwiese': 1,
    'oberursel-stadtmitte oberursel-bahnhof': 1,
    'weisskirchen-ost niederursel': 5,
    'bockenheimer-warte festhalle-messe': 2,
    'festhalle-messe hauptbahnhof': 2,
    'hauptbahnhof willy-brandt-platz': 2,
    'willy-brandt-platz dom-romer': 2,
    'konstablerwache merianplatz': 2,
    'bornheim-mitte seckbacher-landstrasse': 2,
    'seckbacher-landstrasse schafflestrasse': 4,
    'marbachweg-sozialzentrum hauptfriedhof': 2,
    'hauptfriedhof deutsche-nationalbibliothek': 2,
    'musterschule konstablerwache': 2,
    'dom-romer willy-brandt-platz': 2,
    'willy-brandt-platz hauptbahnhof': 2,
    'konstablerwache glauburgstrasse': 3,
    'deutsche-nationalbibliothek hauptfriedhof': 2,
    'hauptfriedhof marbachweg-sozialzentrum': 2,
    'grosse-nelkenstrasse industriehof': 1,
    'enkheim hessen-center': 1,
    'hessen-center kruppstrasse': 1,
    'kruppstrasse gwinnerstrasse': 1,
    'gwinnerstrasse schafflestrasse': 1,
    'eissporthalle-festplatz parlamentsplatz': 1,
    'parlamentsplatz habsburgerallee': 1,
    'industriehof fischstein': 1,
    'fischstein hausener-weg': 1,
    'stephan-heise-strasse friedhof-westhausen': 1,
    'kalbach riedberg': 4,
    'wiesenau heddernheimer-landstrasse': 1,
    'nordwestzentrum romerstadt': 1,
    'ginnheim-niddapark ginnheim-mitte': 1,
  },
  stations: {
    hohemark: { name: 'Hohemark', x: 0, y: 0 },
    waldlust: { name: 'Waldlust', x: 2, y: 0 },
    rosengartchen: { name: 'Rosengärtchen', x: 4, y: 0 },
    kupferhammer: { name: 'Kupferhammer', x: 5.5, y: 1.5 },
    glocknerwiese: { name: 'Glöcknerwiese', x: 7.5, y: 1.5 },
    lahnstrasse: { name: 'Lahnstraße', x: 9, y: 3 },
    'oberursel-altstadt': { name: 'Oberursel Altstadt', x: 11, y: 4.5 },
    'oberursel-stadtmitte': { name: 'Oberursel Stadtmitte', x: 12.5, y: 6 },
    'oberursel-bahnhof': { name: 'Oberursel Bahnhof', x: 14, y: 7.5 },
    bommersheim: { name: 'Bommersheim', x: 15.5, y: 9.5 },
    'weisskirchen-ost': { name: 'Weißkirchen Ost', x: 17.5, y: 11 },
    niederursel: { name: 'Niederursel', x: 19, y: 12.5 },
    wiesenau: { name: 'Wiesenau', x: 21, y: 14 },
    zeilweg: { name: 'Zeilweg', x: 22.5, y: 15.5 },
    heddernheim: { name: 'Heddernheim', x: 24, y: 17 },
    'weisser-stein': { name: 'Weißer Stein', x: 26, y: 18.5 },
    lindenbaum: { name: 'Lindenbaum', x: 27.5, y: 20 },
    hugelstrasse: { name: 'Hügelstraße', x: 29, y: 21.5 },
    'fritz-tarnow-strasse': { name: 'Fritz-Tarnow-Straße', x: 29, y: 23.5 },
    dornbusch: { name: 'Dornbusch', x: 29.5, y: 25.5 },
    'miquel-adickesallee': { name: 'Miquel-/Adickesallee', x: 29.5, y: 27.5 },
    holzhausenstrasse: { name: 'Holzhausenstraße', x: 29.5, y: 29.5 },
    gruneburgweg: { name: 'Grüneburgweg', x: 30, y: 31.5 },
    'eschenheimer-tor': { name: 'Eschenheimer Tor', x: 31.5, y: 33 },
    hauptwache: { name: 'Hauptwache', x: 31.5, y: 35 },
    'willy-brandt-platz': { name: 'Willy-Brandt-Platz', x: 30.5, y: 36.5 },
    'schweizer-platz': { name: 'Schweizer Platz', x: 31.5, y: 38 },
    sudbahnhof: { name: 'Südbahnhof', x: 33, y: 39.5 },
    'bockenheimer-warte': { name: 'Bockenheimer Warte', x: 26, y: 34 },
    'festhalle-messe': { name: 'Festhalle/Messe', x: 27, y: 35.5 },
    hauptbahnhof: { name: 'Hauptbahnhof', x: 28.5, y: 36.5 },
    'dom-romer': { name: 'Dom/Römer', x: 32.5, y: 36.5 },
    konstablerwache: { name: 'Konstablerwache', x: 33.5, y: 35 },
    merianplatz: { name: 'Merianplatz', x: 35.5, y: 33.5 },
    hohenstrasse: { name: 'Höhenstraße', x: 37, y: 32 },
    'bornheim-mitte': { name: 'Bornheim Mitte', x: 38.5, y: 30.5 },
    'seckbacher-landstrasse': { name: 'Seckbacher Landstraße', x: 40, y: 29 },
    schafflestrasse: { name: 'Schäfflestraße', x: 42, y: 29 },
    gwinnerstrasse: { name: 'Gwinnerstraße', x: 44, y: 29 },
    kruppstrasse: { name: 'Kruppstraße', x: 45.5, y: 27.5 },
    'hessen-center': { name: 'Hessen-Center', x: 47, y: 26 },
    enkheim: { name: 'Enkheim', x: 48.5, y: 24.5 },
    glauburgstrasse: { name: 'Glauburgstraße', x: 33, y: 32.5 },
    'deutsche-nationalbibliothek': { name: 'Deutsche Nationalbibliothek', x: 33, y: 30.5 },
    hauptfriedhof: { name: 'Hauptfriedhof', x: 33, y: 28.5 },
    'marbachweg-sozialzentrum': { name: 'Marbachweg/Sozialzentrum', x: 33, y: 26.5 },
    feuerwehrstrasse: { name: 'Feuerwehrstraße', x: 35, y: 26 },
    'theobald-ziegler-strasse': { name: 'Theobald-Ziegler-Straße', x: 35, y: 24 },
    ronneburgstrasse: { name: 'Ronneburgstraße', x: 35, y: 22 },
    'sigmund-freud-strasse': { name: 'Sigmund-Freud-Straße', x: 33.5, y: 21 },
    preungesheim: { name: 'Preungesheim', x: 35, y: 19.5 },
    'johanna-tesch-platz': { name: 'Johanna-Tesch-Platz', x: 42, y: 31 },
    'eissporthalle-festplatz': { name: 'Eissporthalle/Festplatz', x: 40.5, y: 32.5 },
    parlamentsplatz: { name: 'Parlamentsplatz', x: 39, y: 33.5 },
    habsburgerallee: { name: 'Habsburgerallee', x: 38, y: 35 },
    zoo: { name: 'Zoo', x: 35.5, y: 35 },
    'alte-oper': { name: 'Alte Oper', x: 29.5, y: 35 },
    westend: { name: 'Westend', x: 28, y: 34 },
    'leipziger-strasse': { name: 'Leipziger Straße', x: 24.5, y: 32.5 },
    kirchplatz: { name: 'Kirchplatz', x: 23, y: 31.5 },
    industriehof: { name: 'Industriehof', x: 21.5, y: 30 },
    fischstein: { name: 'Fischstein', x: 19, y: 30 },
    'hausener-weg': { name: 'Hausener Weg', x: 17.5, y: 28.5 },
    'stephan-heise-strasse': { name: 'Stephan-Heise-Straße', x: 17.5, y: 26.5 },
    'friedhof-westhausen': { name: 'Friedhof Westhausen', x: 16, y: 25 },
    heerstrasse: { name: 'Heerstraße', x: 14.5, y: 23.5 },
    hausen: { name: 'Hausen', x: 19, y: 27.5 },
    'grosse-nelkenstrasse': { name: 'Große Nelkenstraße', x: 20, y: 28.5 },
    ostbahnhof: { name: 'Ostbahnhof', x: 37, y: 36.5 },
    'ginnheim-mitte': { name: 'Ginnheim Mitte', x: 22.5, y: 24 },
    'ginnheim-niddapark': { name: 'Ginnheim/Niddapark', x: 21, y: 22.5 },
    romerstadt: { name: 'Römerstadt', x: 21, y: 20.5 },
    nordwestzentrum: { name: 'Nordwestzentrum', x: 21, y: 18.5 },
    'heddernheimer-landstrasse': { name: 'Heddernheimer Landstraße', x: 21, y: 16.5 },
    gonzenheim: { name: 'Gonzenheim', x: 24.5, y: 3.5 },
    'ober-eschbach': { name: 'Ober-Eschbach', x: 26, y: 5 },
    'nieder-eschbach': { name: 'Nieder-Eschbach', x: 26, y: 7.5 },
    'bonames-mitte': { name: 'Bonames Mitte', x: 26, y: 9.5 },
    kalbach: { name: 'Kalbach', x: 24.5, y: 11 },
    'riedwiese-mertonviertel': { name: 'Riedwiese/Mertonviertel', x: 24.5, y: 13 },
    sandelmuhle: { name: 'Sandelmühle', x: 24.5, y: 15 },
    riedberg: { name: 'Riedberg', x: 22.5, y: 11 },
    'uni-campus-riedberg': { name: 'Uni-Campus Riedberg', x: 21, y: 12.5 },
    musterschule: { name: 'Musterschule', x: 34, y: 33.5 },
  },
};
