// Hamburg's U-Bahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'hamburg',
  name: 'Hamburg',
  system: 'U-Bahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'u1',
      short: 'U1',
      name: 'U1',
      colour: '#006ab3',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['grosshansdorf', 'kiekut', 'schmalenbeck', 'ahrensburg-ost', 'ahrensburg-west', 'buchenkamp', 'volksdorf', 'meiendorfer-weg', 'berne', 'oldenfelde', 'farmsen', 'trabrennbahn', 'wandsbek-gartenstadt', 'alter-teichweg', 'strassburger-strasse', 'wandsbek-markt', 'wandsbeker-chaussee', 'ritterstrasse', 'wartenau', 'lubecker-strasse', 'lohmuhlenstrasse', 'hauptbahnhof-sud', 'steinstrasse', 'messberg', 'jungfernstieg', 'stephansplatz-oper-cch', 'hallerstrasse', 'klosterstern', 'kellinghusenstrasse', 'hudtwalckerstrasse', 'lattenkamp-sporthalle', 'alsterdorf', 'sengelmannstrasse-city-nord', 'ohlsdorf', 'klein-borstel', 'fuhlsbuttel', 'fuhlsbuttel-nord', 'langenhorn-markt', 'langenhorn-nord', 'kiwittsmoor', 'ochsenzoll', 'garstedt', 'richtweg', 'norderstedt-mitte'],
        ['ohlstedt', 'hoisbuttel', 'buckhorn', 'volksdorf', 'meiendorfer-weg', 'berne', 'oldenfelde', 'farmsen', 'trabrennbahn', 'wandsbek-gartenstadt', 'alter-teichweg', 'strassburger-strasse', 'wandsbek-markt', 'wandsbeker-chaussee', 'ritterstrasse', 'wartenau', 'lubecker-strasse', 'lohmuhlenstrasse', 'hauptbahnhof-sud', 'steinstrasse', 'messberg', 'jungfernstieg', 'stephansplatz-oper-cch', 'hallerstrasse', 'klosterstern', 'kellinghusenstrasse', 'hudtwalckerstrasse', 'lattenkamp-sporthalle', 'alsterdorf', 'sengelmannstrasse-city-nord', 'ohlsdorf', 'klein-borstel', 'fuhlsbuttel', 'fuhlsbuttel-nord', 'langenhorn-markt', 'langenhorn-nord', 'kiwittsmoor', 'ochsenzoll', 'garstedt', 'richtweg', 'norderstedt-mitte'],
      ],
    },
    {
      id: 'u2',
      short: 'U2',
      name: 'U2',
      colour: '#e2001a',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['niendorf-nord', 'schippelsweg', 'joachim-mahl-strasse', 'niendorf-markt', 'hagendeel', 'hagenbecks-tierpark', 'lutterothstrasse', 'osterstrasse', 'emilienstrasse', 'christuskirche', 'schlump', 'messehallen', 'gansemarkt-oper', 'jungfernstieg', 'hauptbahnhof-nord', 'berliner-tor', 'burgstrasse', 'hammer-kirche', 'rauhes-haus', 'horner-rennbahn', 'legienstrasse', 'billstedt', 'merkenstrasse', 'steinfurther-allee', 'mummelmannsberg'],
      ],
    },
    {
      id: 'u3',
      short: 'U3',
      name: 'U3',
      colour: '#ffdd00',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['wandsbek-gartenstadt', 'habichtstrasse', 'barmbek', 'dehnhaide', 'hamburger-strasse', 'mundsburg', 'uhlandstrasse', 'lubecker-strasse', 'berliner-tor', 'hauptbahnhof-sud', 'monckebergstrasse', 'rathaus', 'rodingsmarkt', 'baumwall-elbphilharmonie', 'landungsbrucken', 'st-pauli', 'feldstrasse-heiligengeistfeld', 'sternschanze-messe', 'schlump', 'hoheluftbrucke', 'eppendorfer-baum', 'kellinghusenstrasse', 'sierichstrasse', 'borgweg-stadtpark', 'saarlandstrasse'],
        ['barmbek', 'saarlandstrasse', 'borgweg-stadtpark', 'sierichstrasse', 'kellinghusenstrasse', 'eppendorfer-baum', 'hoheluftbrucke', 'schlump', 'sternschanze-messe', 'feldstrasse-heiligengeistfeld', 'st-pauli', 'landungsbrucken', 'baumwall-elbphilharmonie', 'rodingsmarkt', 'rathaus', 'monckebergstrasse', 'hauptbahnhof-sud', 'berliner-tor', 'lubecker-strasse', 'uhlandstrasse', 'mundsburg', 'hamburger-strasse', 'dehnhaide'],
      ],
    },
    {
      id: 'u4',
      short: 'U4',
      name: 'U4',
      colour: '#256d7b',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['billstedt', 'legienstrasse', 'horner-rennbahn', 'rauhes-haus', 'hammer-kirche', 'burgstrasse', 'berliner-tor', 'hauptbahnhof-nord', 'jungfernstieg', 'uberseequartier', 'hafencity-universitat', 'elbbrucken'],
      ],
    },
  ],
  times: {
    'grosshansdorf kiekut': 3,
    'kiekut schmalenbeck': 3,
    'schmalenbeck ahrensburg-ost': 3,
    'ahrensburg-ost ahrensburg-west': 3,
    'ahrensburg-west buchenkamp': 5,
    'buchenkamp volksdorf': 3,
    'volksdorf meiendorfer-weg': 3,
    'meiendorfer-weg berne': 4,
    'berne oldenfelde': 3,
    'oldenfelde farmsen': 3,
    'farmsen trabrennbahn': 3,
    'trabrennbahn wandsbek-gartenstadt': 4,
    'alter-teichweg strassburger-strasse': 1,
    'strassburger-strasse wandsbek-markt': 3,
    'hauptbahnhof-sud steinstrasse': 1,
    'steinstrasse messberg': 1,
    'stephansplatz-oper-cch hallerstrasse': 3,
    'hudtwalckerstrasse lattenkamp-sporthalle': 1,
    'lattenkamp-sporthalle alsterdorf': 3,
    'sengelmannstrasse-city-nord ohlsdorf': 3,
    'langenhorn-markt langenhorn-nord': 3,
    'langenhorn-nord kiwittsmoor': 3,
    'ochsenzoll garstedt': 3,
    'garstedt richtweg': 3,
    'richtweg norderstedt-mitte': 3,
    'ohlstedt hoisbuttel': 4,
    'hoisbuttel buckhorn': 3,
    'buckhorn volksdorf': 3,
    'niendorf-markt hagendeel': 4,
    'hagendeel hagenbecks-tierpark': 3,
    'hagenbecks-tierpark lutterothstrasse': 3,
    'osterstrasse emilienstrasse': 1,
    'christuskirche schlump': 1,
    'schlump messehallen': 3,
    'hauptbahnhof-nord berliner-tor': 3,
    'berliner-tor burgstrasse': 3,
    'rauhes-haus horner-rennbahn': 3,
    'billstedt merkenstrasse': 3,
    'steinfurther-allee mummelmannsberg': 3,
    'wandsbek-gartenstadt habichtstrasse': 3,
    'dehnhaide hamburger-strasse': 1,
    'mundsburg uhlandstrasse': 1,
    'uhlandstrasse lubecker-strasse': 1,
    'hauptbahnhof-sud monckebergstrasse': 1,
    'monckebergstrasse rathaus': 1,
    'rathaus rodingsmarkt': 1,
    'rodingsmarkt baumwall-elbphilharmonie': 1,
    'landungsbrucken st-pauli': 1,
    'sternschanze-messe schlump': 1,
    'schlump hoheluftbrucke': 3,
    'borgweg-stadtpark saarlandstrasse': 3,
    'saarlandstrasse borgweg-stadtpark': 3,
    'hoheluftbrucke schlump': 3,
    'schlump sternschanze-messe': 1,
    'st-pauli landungsbrucken': 1,
    'baumwall-elbphilharmonie rodingsmarkt': 1,
    'rodingsmarkt rathaus': 1,
    'rathaus monckebergstrasse': 1,
    'monckebergstrasse hauptbahnhof-sud': 1,
    'lubecker-strasse uhlandstrasse': 1,
    'uhlandstrasse mundsburg': 1,
    'hamburger-strasse dehnhaide': 1,
    'horner-rennbahn rauhes-haus': 3,
    'burgstrasse berliner-tor': 3,
    'berliner-tor hauptbahnhof-nord': 3,
    'jungfernstieg uberseequartier': 3,
    'hafencity-universitat elbbrucken': 3,
  },
  stations: {
    'niendorf-nord': { name: 'Niendorf Nord', x: 0.5, y: 14 },
    schippelsweg: { name: 'Schippelsweg', x: 0.5, y: 16 },
    'joachim-mahl-strasse': { name: 'Joachim-Mähl-Straße', x: 0.5, y: 18 },
    'niendorf-markt': { name: 'Niendorf Markt', x: 0, y: 20 },
    hagendeel: { name: 'Hagendeel', x: 0, y: 22 },
    'hagenbecks-tierpark': { name: 'Hagenbecks Tierpark', x: 0, y: 24 },
    lutterothstrasse: { name: 'Lutterothstraße', x: 0, y: 26 },
    osterstrasse: { name: 'Osterstraße', x: 0, y: 28 },
    emilienstrasse: { name: 'Emilienstraße', x: 0, y: 30 },
    christuskirche: { name: 'Christuskirche', x: 2, y: 30 },
    schlump: { name: 'Schlump', x: 4, y: 30 },
    messehallen: { name: 'Messehallen', x: 4, y: 32 },
    'gansemarkt-oper': { name: 'Gänsemarkt (Oper)', x: 5, y: 33 },
    jungfernstieg: { name: 'Jungfernstieg', x: 7, y: 33.5 },
    'hauptbahnhof-nord': { name: 'Hauptbahnhof Nord', x: 9.5, y: 33 },
    'berliner-tor': { name: 'Berliner Tor', x: 12, y: 33.5 },
    burgstrasse: { name: 'Burgstraße', x: 14, y: 33.5 },
    'hammer-kirche': { name: 'Hammer Kirche', x: 16, y: 34 },
    'rauhes-haus': { name: 'Rauhes Haus', x: 18, y: 34 },
    'horner-rennbahn': { name: 'Horner Rennbahn', x: 20, y: 34 },
    legienstrasse: { name: 'Legienstraße', x: 21.5, y: 35.5 },
    billstedt: { name: 'Billstedt', x: 23, y: 37 },
    merkenstrasse: { name: 'Merkenstraße', x: 25, y: 37 },
    'steinfurther-allee': { name: 'Steinfurther Allee', x: 27, y: 37 },
    mummelmannsberg: { name: 'Mümmelmannsberg', x: 28.5, y: 38.5 },
    grosshansdorf: { name: 'Großhansdorf', x: 44, y: 10.5 },
    kiekut: { name: 'Kiekut', x: 42.5, y: 12 },
    schmalenbeck: { name: 'Schmalenbeck', x: 40.5, y: 12 },
    'ahrensburg-ost': { name: 'Ahrensburg Ost', x: 38, y: 12 },
    'ahrensburg-west': { name: 'Ahrensburg West', x: 36, y: 12 },
    buchenkamp: { name: 'Buchenkamp', x: 33.5, y: 12.5 },
    volksdorf: { name: 'Volksdorf', x: 31.5, y: 12.5 },
    'meiendorfer-weg': { name: 'Meiendorfer Weg', x: 29.5, y: 14.5 },
    berne: { name: 'Berne', x: 27.5, y: 16 },
    oldenfelde: { name: 'Oldenfelde', x: 26, y: 18 },
    farmsen: { name: 'Farmsen', x: 24, y: 19.5 },
    trabrennbahn: { name: 'Trabrennbahn', x: 22, y: 21.5 },
    'wandsbek-gartenstadt': { name: 'Wandsbek-Gartenstadt', x: 20.5, y: 23 },
    'alter-teichweg': { name: 'Alter Teichweg', x: 19, y: 24.5 },
    'strassburger-strasse': { name: 'Straßburger Straße', x: 19, y: 26.5 },
    'wandsbek-markt': { name: 'Wandsbek Markt', x: 19, y: 28.5 },
    'wandsbeker-chaussee': { name: 'Wandsbeker Chaussee', x: 17.5, y: 30 },
    ritterstrasse: { name: 'Ritterstraße', x: 15.5, y: 30 },
    wartenau: { name: 'Wartenau', x: 13.5, y: 30 },
    'lubecker-strasse': { name: 'Lübecker Straße', x: 13.5, y: 32 },
    lohmuhlenstrasse: { name: 'Lohmühlenstraße', x: 11.5, y: 32 },
    'hauptbahnhof-sud': { name: 'Hauptbahnhof Süd', x: 10.5, y: 34 },
    steinstrasse: { name: 'Steinstraße', x: 10, y: 36 },
    messberg: { name: 'Meßberg', x: 9, y: 34.5 },
    'stephansplatz-oper-cch': { name: 'Stephansplatz (Oper/CCH)', x: 7, y: 31 },
    hallerstrasse: { name: 'Hallerstraße', x: 7, y: 29 },
    klosterstern: { name: 'Klosterstern', x: 7, y: 27 },
    kellinghusenstrasse: { name: 'Kellinghusenstraße', x: 7, y: 25 },
    hudtwalckerstrasse: { name: 'Hudtwalckerstraße', x: 8.5, y: 23.5 },
    'lattenkamp-sporthalle': { name: 'Lattenkamp (Sporthalle)', x: 8.5, y: 21.5 },
    alsterdorf: { name: 'Alsterdorf', x: 10.5, y: 21.5 },
    'sengelmannstrasse-city-nord': { name: 'Sengelmannstraße (City Nord)', x: 12, y: 20 },
    ohlsdorf: { name: 'Ohlsdorf', x: 13.5, y: 18.5 },
    'klein-borstel': { name: 'Klein Borstel', x: 13, y: 16.5 },
    fuhlsbuttel: { name: 'Fuhlsbüttel', x: 12, y: 15 },
    'fuhlsbuttel-nord': { name: 'Fuhlsbüttel Nord', x: 10.5, y: 13.5 },
    'langenhorn-markt': { name: 'Langenhorn Markt', x: 10.5, y: 11 },
    'langenhorn-nord': { name: 'Langenhorn Nord', x: 10.5, y: 9 },
    kiwittsmoor: { name: 'Kiwittsmoor', x: 10.5, y: 7 },
    ochsenzoll: { name: 'Ochsenzoll', x: 9, y: 5.5 },
    garstedt: { name: 'Garstedt', x: 7.5, y: 4 },
    richtweg: { name: 'Richtweg', x: 7.5, y: 2 },
    'norderstedt-mitte': { name: 'Norderstedt Mitte', x: 7.5, y: 0 },
    barmbek: { name: 'Barmbek', x: 16, y: 25 },
    saarlandstrasse: { name: 'Saarlandstraße', x: 14, y: 25 },
    'borgweg-stadtpark': { name: 'Borgweg (Stadtpark)', x: 11.5, y: 25 },
    sierichstrasse: { name: 'Sierichstraße', x: 9.5, y: 25 },
    'eppendorfer-baum': { name: 'Eppendorfer Baum', x: 5.5, y: 26.5 },
    hoheluftbrucke: { name: 'Hoheluftbrücke', x: 4, y: 28 },
    'sternschanze-messe': { name: 'Sternschanze (Messe)', x: 2.5, y: 31.5 },
    'feldstrasse-heiligengeistfeld': { name: 'Feldstraße (Heiligengeistfeld)', x: 2, y: 33.5 },
    'st-pauli': { name: 'St. Pauli', x: 3, y: 35 },
    landungsbrucken: { name: 'Landungsbrücken', x: 3, y: 37 },
    'baumwall-elbphilharmonie': { name: 'Baumwall (Elbphilharmonie)', x: 5, y: 37 },
    rodingsmarkt: { name: 'Rödingsmarkt', x: 5, y: 35 },
    rathaus: { name: 'Rathaus', x: 6.5, y: 34.5 },
    monckebergstrasse: { name: 'Mönckebergstraße', x: 8, y: 33.5 },
    uhlandstrasse: { name: 'Uhlandstraße', x: 12, y: 30.5 },
    mundsburg: { name: 'Mundsburg', x: 12.5, y: 28.5 },
    'hamburger-strasse': { name: 'Hamburger Straße', x: 14.5, y: 28.5 },
    dehnhaide: { name: 'Dehnhaide', x: 14.5, y: 26.5 },
    habichtstrasse: { name: 'Habichtstraße', x: 18, y: 23 },
    uberseequartier: { name: 'Überseequartier', x: 7.5, y: 36 },
    'hafencity-universitat': { name: 'HafenCity Universität', x: 9, y: 37 },
    elbbrucken: { name: 'Elbbrücken', x: 11, y: 37.5 },
    ohlstedt: { name: 'Ohlstedt', x: 28.5, y: 7.5 },
    hoisbuttel: { name: 'Hoisbüttel', x: 28.5, y: 9.5 },
    buckhorn: { name: 'Buckhorn', x: 30, y: 11 },
  },
};
