// Hannover's Stadtbahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'hannover',
  name: 'Hannover',
  system: 'Stadtbahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Linie 1',
      colour: '#e4003a',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['sarstedt', 'sarstedt-rontgenstrasse', 'sarstedt-am-boksberg', 'heisede-langer-kamp', 'heisede-marienburger-strasse', 'gleidingen-am-leinkamp', 'gleidingen-thorstrasse', 'gleidingen', 'rethen-galgenbergweg', 'rethen-bahnhof', 'rethen-pattenser-strasse', 'laatzen-rethener-winkel', 'laatzen', 'laatzen-zentrum', 'laatzen-park-der-sinne', 'laatzen-eichstrasse', 'laatzen-birkenstrasse', 'am-brabrinke', 'wiehbergstrasse', 'bothmerstrasse', 'peiner-strasse', 'fiedelerstrasse', 'dohrener-turm', 'altenbekener-damm', 'geibelstrasse', 'schlagerstrasse', 'aegidientorplatz', 'kropcke', 'hauptbahnhof', 'werderstrasse', 'vahrenwalder-platz', 'dragonerstrasse', 'niedersachsenring', 'buttnerstrasse', 'windausstrasse', 'kabelkamp', 'alter-flughafen', 'wiesenau', 'berliner-platz', 'langenhagen-angerstrasse', 'langenhagen-langenforther-platz', 'langenhagen-zentrum', 'langenhagen-kurt-schumacher-allee', 'langenhagen'],
        ['langenhagen', 'langenhagen-kurt-schumacher-allee', 'langenhagen-zentrum', 'langenhagen-langenforther-platz', 'langenhagen-angerstrasse', 'berliner-platz', 'wiesenau', 'alter-flughafen', 'kabelkamp', 'windausstrasse', 'buttnerstrasse', 'niedersachsenring', 'dragonerstrasse', 'vahrenwalder-platz', 'hauptbahnhof', 'kropcke', 'aegidientorplatz', 'schlagerstrasse', 'geibelstrasse', 'altenbekener-damm', 'dohrener-turm', 'fiedelerstrasse', 'peiner-strasse', 'bothmerstrasse', 'wiehbergstrasse', 'am-brabrinke', 'laatzen-birkenstrasse', 'laatzen-eichstrasse', 'laatzen-park-der-sinne', 'laatzen-zentrum', 'laatzen', 'laatzen-rethener-winkel', 'rethen-pattenser-strasse', 'rethen-bahnhof', 'rethen-galgenbergweg', 'gleidingen', 'gleidingen-thorstrasse', 'gleidingen-am-leinkamp', 'heisede-marienburger-strasse', 'heisede-langer-kamp', 'sarstedt-am-boksberg', 'sarstedt-rontgenstrasse', 'sarstedt'],
      ],
    },
    {
      id: '2',
      short: '2',
      name: 'Linie 2',
      colour: '#e4003a',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['alte-heide', 'bahnstrift', 'tempelhofweg', 'zehlendorfweg', 'papenwinkel', 'vahrenheider-markt', 'reiterstadion', 'grosser-kolonnenweg', 'buttnerstrasse', 'niedersachsenring', 'dragonerstrasse', 'vahrenwalder-platz', 'werderstrasse', 'hauptbahnhof', 'kropcke', 'aegidientorplatz', 'schlagerstrasse', 'geibelstrasse', 'altenbekener-damm', 'dohrener-turm', 'fiedelerstrasse', 'peiner-strasse', 'bothmerstrasse', 'wiehbergstrasse', 'am-brabrinke', 'laatzen-birkenstrasse', 'laatzen-eichstrasse', 'laatzen-aqualaatzium', 'laatzen-krankenhaus', 'laatzen-neuer-schlag', 'laatzen-ginsterweg', 'rethen-pattenser-strasse', 'rethen-bahnhof', 'rethen-galgenbergweg', 'gleidingen'],
      ],
    },
    {
      id: '3',
      short: '3',
      name: 'Linie 3',
      colour: '#0069b4',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['altwarmbuchen', 'altwarmbuchen-zentrum', 'altwarmbuchen-ernst-grote-strasse', 'altwarmbuchen-opelstrasse', 'oldenburger-allee', 'stadtfriedhof-lahe', 'paracelsusweg', 'in-den-sieben-stucken', 'noltemeyerbrucke', 'klingerstrasse', 'spannhagengarten', 'pelikanstrasse', 'vier-grenzen', 'lortzingstrasse', 'lister-platz', 'sedanstrasse-lister-meile', 'hauptbahnhof', 'kropcke', 'markthalle-landtag-u', 'waterloo', 'allerweg', 'stadionbrucke', 'bahnhof-linden-fischerhof', 'schunemannplatz', 'beekestrasse', 'wallensteinstrasse', 'bartold-knaust-strasse', 'am-sauerwinkel', 'muhlenberger-markt', 'tresckowstrasse', 'wettbergen'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'Linie 4',
      colour: '#f9b000',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['garbsen', 'auf-der-horst-marshof', 'auf-der-horst-skorpiongasse', 'schonebecker-allee', 'pascalstrasse', 'wissenschaftspark-marienwerder', 'jadekamp', 'auf-der-klappenburg', 'lauckerthof', 'freudenthalstrasse', 'stadtfriedhof-stocken', 'bahnhof-leinhausen', 'herrenhauser-markt', 'schaumburgstrasse', 'herrenhauser-garten', 'appelstrasse', 'schneiderberg-wilhelm-busch-museum', 'leibniz-universitat', 'konigsworther-platz', 'steintor', 'kropcke', 'aegidientorplatz', 'marienstrasse', 'braunschweiger-platz', 'clausewitzstrasse', 'kantplatz', 'uhlhornstrasse', 'nackenberg', 'bahnhof-karl-wiechert-allee', 'misburger-strasse', 'medizinische-hochschule', 'roderbruchmarkt', 'roderbruch'],
        ['roderbruch', 'roderbruchmarkt', 'medizinische-hochschule', 'misburger-strasse', 'bahnhof-karl-wiechert-allee', 'nackenberg', 'uhlhornstrasse', 'kantplatz', 'clausewitzstrasse', 'braunschweiger-platz', 'marienstrasse', 'aegidientorplatz', 'kropcke', 'steintor', 'konigsworther-platz', 'leibniz-universitat', 'schneiderberg-wilhelm-busch-museum', 'appelstrasse', 'herrenhauser-garten', 'schaumburgstrasse', 'herrenhauser-markt', 'bahnhof-leinhausen', 'betriebshof-fuhsestrasse'],
      ],
    },
    {
      id: '5',
      short: '5',
      name: 'Linie 5',
      colour: '#f9b000',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['anderten', 'konigsberger-ring', 'ostfeldstrasse', 'tiergarten', 'grosser-hillen', 'saarbruckener-strasse', 'bleekstrasse', 'annastift', 'nackenberg', 'uhlhornstrasse', 'kantplatz', 'clausewitzstrasse', 'braunschweiger-platz', 'marienstrasse', 'aegidientorplatz', 'kropcke', 'steintor', 'konigsworther-platz', 'leibniz-universitat', 'schneiderberg-wilhelm-busch-museum', 'appelstrasse', 'herrenhauser-garten', 'schaumburgstrasse', 'herrenhauser-markt', 'bahnhof-leinhausen', 'stadtfriedhof-stocken', 'freudenthalstrasse', 'stockener-markt', 'stocken'],
        ['stocken', 'stockener-markt', 'freudenthalstrasse', 'stadtfriedhof-stocken', 'betriebshof-fuhsestrasse'],
      ],
    },
    {
      id: '6',
      short: '6',
      name: 'Linie 6',
      colour: '#f9b000',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['messe-ost-expo-plaza', 'stockholmer-allee', 'krugerskamp', 'kronsberg', 'feldbuschwende', 'brabeckstrasse', 'emslandstrasse', 'seelhorster-allee', 'august-madsack-strasse', 'bunteweg-tierarztliche-hochschule', 'zuschlagstrasse', 'kinderkrankenhaus-auf-der-bult', 'kerstingstrasse', 'freundallee', 'braunschweiger-platz', 'marienstrasse', 'aegidientorplatz', 'kropcke', 'steintor', 'christuskirche', 'kopernikusstrasse', 'an-der-strangriede', 'bahnhof-nordstadt', 'fenskestrasse', 'hainholzer-markt', 'krepenstrasse', 'friedenauer-strasse', 'beneckeallee', 'mecklenheidestrasse', 'nordhafen'],
      ],
    },
    {
      id: '7',
      short: '7',
      name: 'Linie 7',
      colour: '#0069b4',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['misburg', 'am-forstkamp', 'kafkastrasse', 'schierholzstrasse', 'pappelwiese', 'paracelsusweg', 'in-den-sieben-stucken', 'noltemeyerbrucke', 'klingerstrasse', 'spannhagengarten', 'pelikanstrasse', 'vier-grenzen', 'lortzingstrasse', 'lister-platz', 'sedanstrasse-lister-meile', 'hauptbahnhof', 'kropcke', 'markthalle-landtag-u', 'waterloo', 'allerweg', 'stadionbrucke', 'bahnhof-linden-fischerhof', 'schunemannplatz', 'beekestrasse', 'wallensteinstrasse', 'bartold-knaust-strasse', 'am-sauerwinkel', 'muhlenberger-markt', 'tresckowstrasse', 'wettbergen'],
      ],
    },
    {
      id: '8',
      short: '8',
      name: 'Linie 8',
      colour: '#e4003a',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['messe-nord', 'am-mittelfelde', 'stadtfriedhof-seelhorst', 'bothmerstrasse', 'peiner-strasse', 'fiedelerstrasse', 'dohrener-turm', 'altenbekener-damm', 'geibelstrasse', 'schlagerstrasse', 'aegidientorplatz', 'kropcke', 'hauptbahnhof', 'werderstrasse', 'vahrenwalder-platz', 'dragonerstrasse'],
      ],
    },
    {
      id: '9',
      short: '9',
      name: 'Linie 9',
      colour: '#0069b4',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['empelde', 'hermann-ehlers-allee', 'safariweg', 'am-soltekampe', 'kortingsdorfer-weg', 'bauweg', 'am-lindener-hafen', 'bernhard-caspar-strasse', 'nieschlagstrasse', 'lindener-marktplatz', 'schwarzer-bar', 'waterloo', 'markthalle-landtag-u', 'kropcke', 'hauptbahnhof'],
      ],
    },
    {
      id: '10',
      short: '10',
      name: 'Linie 10',
      colour: '#76b82a',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['hauptbahnhof', 'kropcke', 'markthalle-landtag-u', 'waterloo', 'humboldtstrasse', 'glocksee', 'am-kuchengarten', 'leinaustrasse', 'wunstorfer-strasse', 'harenberger-strasse', 'brunnenstrasse', 'gedenkstatte-ahlem', 'ahlem'],
        ['ahlem', 'gedenkstatte-ahlem', 'brunnenstrasse', 'harenberger-strasse', 'wunstorfer-strasse', 'leinaustrasse', 'am-kuchengarten', 'glocksee', 'goetheplatz', 'steintor', 'hauptbahnhof-rosenstrasse', 'hauptbahnhof-zob'],
      ],
    },
    {
      id: '11',
      short: '11',
      name: 'Linie 11',
      colour: '#f9b000',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['zoo', 'congress-centrum', 'clausewitzstrasse', 'braunschweiger-platz', 'marienstrasse', 'aegidientorplatz', 'kropcke', 'steintor', 'christuskirche', 'kopernikusstrasse', 'an-der-strangriede', 'haltenhoffstrasse'],
        ['haltenhoffstrasse', 'kopernikusstrasse', 'christuskirche', 'steintor', 'kropcke', 'aegidientorplatz', 'braunschweiger-platz'],
      ],
    },
    {
      id: '13',
      short: '13',
      name: 'Linie 13',
      colour: '#0069b4',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['fasanenkrug', 'stadtfriedhof-bothfeld', 'kurze-kamp-strasse', 'bothfeld', 'bothfelder-kirchweg', 'noltemeyerbrucke', 'klingerstrasse', 'spannhagengarten', 'pelikanstrasse', 'vier-grenzen', 'lortzingstrasse', 'lister-platz', 'sedanstrasse-lister-meile', 'hauptbahnhof', 'kropcke', 'markthalle-landtag-u', 'waterloo', 'allerweg', 'stadionbrucke', 'bahnhof-linden-fischerhof', 'schunemannplatz', 'beekestrasse', 'wallensteinstrasse', 'unter-den-birken', 'stadtfriedhof-ricklingen', 'hemmingen-saarstrasse', 'hemmingen-zentrum', 'hemmingen-berliner-strasse', 'hemmingen'],
      ],
    },
    {
      id: '16',
      short: '16',
      name: 'Linie 16',
      colour: '#f9b000',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['konigsworther-platz', 'steintor', 'kropcke', 'aegidientorplatz', 'marienstrasse', 'braunschweiger-platz', 'freundallee', 'kerstingstrasse', 'kinderkrankenhaus-auf-der-bult', 'zuschlagstrasse', 'bunteweg-tierarztliche-hochschule', 'august-madsack-strasse', 'seelhorster-allee', 'emslandstrasse', 'brabeckstrasse', 'feldbuschwende', 'kronsberg', 'krugerskamp', 'stockholmer-allee', 'messe-ost-expo-plaza'],
      ],
    },
    {
      id: '17',
      short: '17',
      name: 'Linie 17',
      colour: '#76b82a',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['hauptbahnhof-zob', 'hauptbahnhof-rosenstrasse', 'steintor', 'goetheplatz', 'humboldtstrasse', 'schwarzer-bar', 'allerweg', 'stadionbrucke', 'bahnhof-linden-fischerhof', 'schunemannplatz', 'beekestrasse', 'wallensteinstrasse'],
      ],
    },
    {
      id: '18',
      short: '18',
      name: 'Linie 18',
      colour: '#e4003a',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hauptbahnhof', 'kropcke', 'aegidientorplatz', 'schlagerstrasse', 'geibelstrasse', 'altenbekener-damm', 'dohrener-turm', 'fiedelerstrasse', 'peiner-strasse', 'bothmerstrasse', 'stadtfriedhof-seelhorst', 'am-mittelfelde', 'messe-nord'],
      ],
    },
  ],
  times: {
    'sarstedt sarstedt-rontgenstrasse': 2,
    'sarstedt-am-boksberg heisede-langer-kamp': 2,
    'heisede-marienburger-strasse gleidingen-am-leinkamp': 3,
    'gleidingen rethen-galgenbergweg': 2,
    'rethen-galgenbergweg rethen-bahnhof': 2,
    'rethen-bahnhof rethen-pattenser-strasse': 2,
    'rethen-pattenser-strasse laatzen-rethener-winkel': 2,
    'laatzen-rethener-winkel laatzen': 2,
    'laatzen laatzen-zentrum': 2,
    'laatzen-zentrum laatzen-park-der-sinne': 2,
    'laatzen-park-der-sinne laatzen-eichstrasse': 2,
    'laatzen-eichstrasse laatzen-birkenstrasse': 2,
    'am-brabrinke wiehbergstrasse': 2,
    'dohrener-turm altenbekener-damm': 3,
    'altenbekener-damm geibelstrasse': 2,
    'schlagerstrasse aegidientorplatz': 2,
    'aegidientorplatz kropcke': 2,
    'kropcke hauptbahnhof': 2,
    'hauptbahnhof werderstrasse': 3,
    'alter-flughafen wiesenau': 2,
    'wiesenau berliner-platz': 2,
    'berliner-platz wiesenau': 2,
    'wiesenau alter-flughafen': 2,
    'vahrenwalder-platz hauptbahnhof': 3,
    'hauptbahnhof kropcke': 2,
    'kropcke aegidientorplatz': 2,
    'aegidientorplatz schlagerstrasse': 2,
    'geibelstrasse altenbekener-damm': 2,
    'altenbekener-damm dohrener-turm': 3,
    'wiehbergstrasse am-brabrinke': 2,
    'laatzen-birkenstrasse laatzen-eichstrasse': 2,
    'laatzen-eichstrasse laatzen-park-der-sinne': 2,
    'laatzen-park-der-sinne laatzen-zentrum': 2,
    'laatzen-zentrum laatzen': 2,
    'laatzen laatzen-rethener-winkel': 2,
    'laatzen-rethener-winkel rethen-pattenser-strasse': 2,
    'rethen-pattenser-strasse rethen-bahnhof': 2,
    'rethen-bahnhof rethen-galgenbergweg': 2,
    'rethen-galgenbergweg gleidingen': 2,
    'gleidingen-am-leinkamp heisede-marienburger-strasse': 3,
    'heisede-langer-kamp sarstedt-am-boksberg': 2,
    'sarstedt-rontgenstrasse sarstedt': 2,
    'alte-heide bahnstrift': 2,
    'zehlendorfweg papenwinkel': 2,
    'reiterstadion grosser-kolonnenweg': 2,
    'werderstrasse hauptbahnhof': 3,
    'laatzen-ginsterweg rethen-pattenser-strasse': 3,
    'altwarmbuchen-zentrum altwarmbuchen-ernst-grote-strasse': 1,
    'altwarmbuchen-ernst-grote-strasse altwarmbuchen-opelstrasse': 1,
    'oldenburger-allee stadtfriedhof-lahe': 1,
    'paracelsusweg in-den-sieben-stucken': 1,
    'vier-grenzen lortzingstrasse': 1,
    'kropcke markthalle-landtag-u': 1,
    'markthalle-landtag-u waterloo': 1,
    'allerweg stadionbrucke': 1,
    'bahnhof-linden-fischerhof schunemannplatz': 1,
    'schunemannplatz beekestrasse': 1,
    'beekestrasse wallensteinstrasse': 1,
    'wallensteinstrasse bartold-knaust-strasse': 1,
    'bartold-knaust-strasse am-sauerwinkel': 1,
    'muhlenberger-markt tresckowstrasse': 1,
    'tresckowstrasse wettbergen': 1,
    'garbsen auf-der-horst-marshof': 1,
    'auf-der-horst-marshof auf-der-horst-skorpiongasse': 1,
    'auf-der-horst-skorpiongasse schonebecker-allee': 1,
    'jadekamp auf-der-klappenburg': 1,
    'auf-der-klappenburg lauckerthof': 1,
    'stadtfriedhof-stocken bahnhof-leinhausen': 1,
    'schaumburgstrasse herrenhauser-garten': 1,
    'herrenhauser-garten appelstrasse': 1,
    'schneiderberg-wilhelm-busch-museum leibniz-universitat': 1,
    'leibniz-universitat konigsworther-platz': 1,
    'steintor kropcke': 1,
    'kantplatz uhlhornstrasse': 1,
    'bahnhof-karl-wiechert-allee misburger-strasse': 1,
    'misburger-strasse medizinische-hochschule': 1,
    'roderbruchmarkt roderbruch': 1,
    'roderbruch roderbruchmarkt': 1,
    'medizinische-hochschule misburger-strasse': 1,
    'misburger-strasse bahnhof-karl-wiechert-allee': 1,
    'uhlhornstrasse kantplatz': 1,
    'kropcke steintor': 1,
    'konigsworther-platz leibniz-universitat': 1,
    'leibniz-universitat schneiderberg-wilhelm-busch-museum': 1,
    'appelstrasse herrenhauser-garten': 1,
    'herrenhauser-garten schaumburgstrasse': 1,
    'ostfeldstrasse tiergarten': 2,
    'nackenberg uhlhornstrasse': 2,
    'kantplatz clausewitzstrasse': 2,
    'clausewitzstrasse braunschweiger-platz': 2,
    'braunschweiger-platz marienstrasse': 2,
    'marienstrasse aegidientorplatz': 2,
    'steintor konigsworther-platz': 2,
    'schneiderberg-wilhelm-busch-museum appelstrasse': 2,
    'schaumburgstrasse herrenhauser-markt': 2,
    'herrenhauser-markt bahnhof-leinhausen': 2,
    'stadtfriedhof-stocken freudenthalstrasse': 2,
    'stockener-markt stocken': 2,
    'stocken stockener-markt': 2,
    'freudenthalstrasse stadtfriedhof-stocken': 2,
    'stockholmer-allee krugerskamp': 2,
    'feldbuschwende brabeckstrasse': 2,
    'seelhorster-allee august-madsack-strasse': 2,
    'august-madsack-strasse bunteweg-tierarztliche-hochschule': 2,
    'zuschlagstrasse kinderkrankenhaus-auf-der-bult': 3,
    'freundallee braunschweiger-platz': 2,
    'steintor christuskirche': 2,
    'fenskestrasse hainholzer-markt': 2,
    'hainholzer-markt krepenstrasse': 2,
    'beneckeallee mecklenheidestrasse': 2,
    'misburg am-forstkamp': 1,
    'am-forstkamp kafkastrasse': 1,
    'messe-nord am-mittelfelde': 2,
    'stadtfriedhof-seelhorst bothmerstrasse': 3,
    'safariweg am-soltekampe': 2,
    'am-soltekampe kortingsdorfer-weg': 2,
    'bernhard-caspar-strasse nieschlagstrasse': 2,
    'schwarzer-bar waterloo': 2,
    'leinaustrasse wunstorfer-strasse': 2,
    'brunnenstrasse gedenkstatte-ahlem': 2,
    'gedenkstatte-ahlem ahlem': 2,
    'ahlem gedenkstatte-ahlem': 2,
    'gedenkstatte-ahlem brunnenstrasse': 2,
    'wunstorfer-strasse leinaustrasse': 2,
    'goetheplatz steintor': 2,
    'zoo congress-centrum': 1,
    'christuskirche kopernikusstrasse': 1,
    'kopernikusstrasse an-der-strangriede': 1,
    'an-der-strangriede haltenhoffstrasse': 1,
    'kopernikusstrasse christuskirche': 1,
    'aegidientorplatz braunschweiger-platz': 3,
    'stadtfriedhof-bothfeld kurze-kamp-strasse': 2,
    'kurze-kamp-strasse bothfeld': 2,
    'bothfelder-kirchweg noltemeyerbrucke': 2,
    'noltemeyerbrucke klingerstrasse': 2,
    'klingerstrasse spannhagengarten': 2,
    'spannhagengarten pelikanstrasse': 2,
    'pelikanstrasse vier-grenzen': 2,
    'lortzingstrasse lister-platz': 2,
    'lister-platz sedanstrasse-lister-meile': 2,
    'sedanstrasse-lister-meile hauptbahnhof': 2,
    'waterloo allerweg': 2,
    'stadionbrucke bahnhof-linden-fischerhof': 2,
    'hemmingen-berliner-strasse hemmingen': 2,
    'freundallee kerstingstrasse': 1,
    'kerstingstrasse kinderkrankenhaus-auf-der-bult': 1,
    'kinderkrankenhaus-auf-der-bult zuschlagstrasse': 3,
    'zuschlagstrasse bunteweg-tierarztliche-hochschule': 1,
    'seelhorster-allee emslandstrasse': 1,
    'emslandstrasse brabeckstrasse': 1,
    'feldbuschwende kronsberg': 1,
    'kronsberg krugerskamp': 1,
    'stockholmer-allee messe-ost-expo-plaza': 1,
    'steintor goetheplatz': 2,
    'schwarzer-bar allerweg': 2,
    'schlagerstrasse geibelstrasse': 1,
    'dohrener-turm fiedelerstrasse': 1,
    'fiedelerstrasse peiner-strasse': 1,
    'peiner-strasse bothmerstrasse': 1,
    'bothmerstrasse stadtfriedhof-seelhorst': 3,
    'stadtfriedhof-seelhorst am-mittelfelde': 1,
  },
  stations: {
    'messe-ost-expo-plaza': { name: 'Messe/Ost (EXPO-Plaza)', x: 53, y: 45.5 },
    'stockholmer-allee': { name: 'Stockholmer Allee', x: 53, y: 43.5 },
    krugerskamp: { name: 'Krügerskamp', x: 54.5, y: 42 },
    kronsberg: { name: 'Kronsberg', x: 56, y: 41 },
    feldbuschwende: { name: 'Feldbuschwende', x: 56, y: 39 },
    brabeckstrasse: { name: 'Brabeckstraße', x: 54.5, y: 37.5 },
    emslandstrasse: { name: 'Emslandstraße', x: 52, y: 37.5 },
    'seelhorster-allee': { name: 'Seelhorster Allee', x: 50.5, y: 36 },
    'august-madsack-strasse': { name: 'August-Madsack-Straße', x: 49, y: 35 },
    'bunteweg-tierarztliche-hochschule': { name: 'Bünteweg/Tierärztliche Hochschule', x: 47.5, y: 33.5 },
    zuschlagstrasse: { name: 'Zuschlagstraße', x: 46, y: 32 },
    'kinderkrankenhaus-auf-der-bult': { name: 'Kinderkrankenhaus auf der Bult', x: 44, y: 31 },
    kerstingstrasse: { name: 'Kerstingstraße', x: 42.5, y: 29.5 },
    freundallee: { name: 'Freundallee', x: 41, y: 28 },
    'braunschweiger-platz': { name: 'Braunschweiger Platz', x: 39.5, y: 27 },
    marienstrasse: { name: 'Marienstraße', x: 38, y: 28 },
    aegidientorplatz: { name: 'Aegidientorplatz', x: 37, y: 27 },
    kropcke: { name: 'Kröpcke', x: 35, y: 25 },
    steintor: { name: 'Steintor', x: 33.5, y: 23.5 },
    christuskirche: { name: 'Christuskirche', x: 32, y: 22 },
    kopernikusstrasse: { name: 'Kopernikusstraße', x: 30.5, y: 20.5 },
    'an-der-strangriede': { name: 'An der Strangriede', x: 30.5, y: 19 },
    'bahnhof-nordstadt': { name: 'Bahnhof Nordstadt', x: 29, y: 17.5 },
    fenskestrasse: { name: 'Fenskestraße', x: 29, y: 15.5 },
    'hainholzer-markt': { name: 'Hainhölzer Markt', x: 28, y: 14 },
    krepenstrasse: { name: 'Krepenstraße', x: 28, y: 12 },
    'friedenauer-strasse': { name: 'Friedenauer Straße', x: 26.5, y: 10.5 },
    beneckeallee: { name: 'Beneckeallee', x: 25, y: 9 },
    mecklenheidestrasse: { name: 'Mecklenheidestraße', x: 23.5, y: 7.5 },
    nordhafen: { name: 'Nordhafen', x: 22, y: 6 },
    hauptbahnhof: { name: 'Hauptbahnhof', x: 35, y: 22.5 },
    schlagerstrasse: { name: 'Schlägerstraße', x: 37, y: 29.5 },
    geibelstrasse: { name: 'Geibelstraße', x: 37, y: 31.5 },
    'altenbekener-damm': { name: 'Altenbekener Damm', x: 38, y: 33.5 },
    'dohrener-turm': { name: 'Döhrener Turm', x: 39.5, y: 35.5 },
    fiedelerstrasse: { name: 'Fiedelerstraße', x: 41, y: 37 },
    'peiner-strasse': { name: 'Peiner Straße', x: 42.5, y: 39 },
    bothmerstrasse: { name: 'Bothmerstraße', x: 44, y: 40.5 },
    'stadtfriedhof-seelhorst': { name: 'Stadtfriedhof Seelhorst', x: 46, y: 40.5 },
    'am-mittelfelde': { name: 'Am Mittelfelde', x: 48, y: 41 },
    'messe-nord': { name: 'Messe / Nord', x: 49.5, y: 42 },
    langenhagen: { name: 'Langenhagen', x: 39.5, y: 0 },
    'langenhagen-kurt-schumacher-allee': { name: 'Langenhagen/Kurt-Schumacher-Allee', x: 37.5, y: 0 },
    'langenhagen-zentrum': { name: 'Langenhagen/Zentrum', x: 35.5, y: 0 },
    'langenhagen-langenforther-platz': { name: 'Langenhagen/Langenforther Platz', x: 33.5, y: 0 },
    'langenhagen-angerstrasse': { name: 'Langenhagen/Angerstraße', x: 33.5, y: 2 },
    'berliner-platz': { name: 'Berliner Platz', x: 33.5, y: 4 },
    wiesenau: { name: 'Wiesenau', x: 33.5, y: 6 },
    'alter-flughafen': { name: 'Alter Flughafen', x: 34, y: 8 },
    kabelkamp: { name: 'Kabelkamp', x: 34, y: 10 },
    windausstrasse: { name: 'Windausstraße', x: 34, y: 12 },
    buttnerstrasse: { name: 'Büttnerstraße', x: 34, y: 14 },
    niedersachsenring: { name: 'Niedersachsenring', x: 34.5, y: 16 },
    dragonerstrasse: { name: 'Dragonerstraße', x: 34.5, y: 18.5 },
    'vahrenwalder-platz': { name: 'Vahrenwalder Platz', x: 35, y: 20.5 },
    wiehbergstrasse: { name: 'Wiehbergstraße', x: 44, y: 43 },
    'am-brabrinke': { name: 'Am Brabrinke', x: 45.5, y: 45 },
    'laatzen-birkenstrasse': { name: 'Laatzen/Birkenstraße', x: 46.5, y: 46.5 },
    'laatzen-eichstrasse': { name: 'Laatzen/Eichstraße', x: 48, y: 48.5 },
    'laatzen-park-der-sinne': { name: 'Laatzen/Park der Sinne', x: 49.5, y: 50 },
    'laatzen-zentrum': { name: 'Laatzen/Zentrum', x: 51.5, y: 51.5 },
    laatzen: { name: 'Laatzen', x: 53, y: 53 },
    'laatzen-rethener-winkel': { name: 'Laatzen/Rethener Winkel', x: 53, y: 55 },
    'rethen-pattenser-strasse': { name: 'Rethen/Pattenser Straße', x: 53, y: 57 },
    'rethen-bahnhof': { name: 'Rethen/Bahnhof', x: 54.5, y: 59 },
    'rethen-galgenbergweg': { name: 'Rethen/Galgenbergweg', x: 56, y: 60.5 },
    gleidingen: { name: 'Gleidingen', x: 57.5, y: 62 },
    'gleidingen-thorstrasse': { name: 'Gleidingen/Thorstraße', x: 59, y: 64 },
    'gleidingen-am-leinkamp': { name: 'Gleidingen/Am Leinkamp', x: 60, y: 65.5 },
    'heisede-marienburger-strasse': { name: 'Heisede/Marienburger Straße', x: 61.5, y: 67 },
    'heisede-langer-kamp': { name: 'Heisede/Langer Kamp', x: 63, y: 68.5 },
    'sarstedt-am-boksberg': { name: 'Sarstedt/Am Boksberg', x: 63, y: 71 },
    'sarstedt-rontgenstrasse': { name: 'Sarstedt/Röntgenstraße', x: 63, y: 73 },
    sarstedt: { name: 'Sarstedt', x: 63, y: 75 },
    'alte-heide': { name: 'Alte Heide', x: 45, y: 7.5 },
    bahnstrift: { name: 'Bahnstrift', x: 43, y: 7.5 },
    tempelhofweg: { name: 'Tempelhofweg', x: 41, y: 7.5 },
    zehlendorfweg: { name: 'Zehlendorfweg', x: 39, y: 7.5 },
    papenwinkel: { name: 'Papenwinkel', x: 37.5, y: 9 },
    'vahrenheider-markt': { name: 'Vahrenheider Markt', x: 37.5, y: 11 },
    reiterstadion: { name: 'Reiterstadion', x: 35.5, y: 11 },
    'grosser-kolonnenweg': { name: 'Großer Kolonnenweg', x: 35.5, y: 13 },
    werderstrasse: { name: 'Werderstraße', x: 33.5, y: 21.5 },
    'laatzen-aqualaatzium': { name: 'Laatzen/aquaLaatzium', x: 48, y: 50.5 },
    'laatzen-krankenhaus': { name: 'Laatzen/Krankenhaus', x: 49, y: 52.5 },
    'laatzen-neuer-schlag': { name: 'Laatzen/Neuer Schlag', x: 50.5, y: 54 },
    'laatzen-ginsterweg': { name: 'Laatzen/Ginsterweg', x: 51.5, y: 55.5 },
    'hauptbahnhof-zob': { name: 'Hauptbahnhof/ZOB', x: 37.5, y: 23.5 },
    'hauptbahnhof-rosenstrasse': { name: 'Hauptbahnhof/Rosenstraße', x: 35.5, y: 23.5 },
    goetheplatz: { name: 'Goetheplatz', x: 31.5, y: 25 },
    humboldtstrasse: { name: 'Humboldtstraße', x: 31.5, y: 27 },
    'schwarzer-bar': { name: 'Schwarzer Bär', x: 30, y: 28 },
    allerweg: { name: 'Allerweg', x: 31, y: 29.5 },
    stadionbrucke: { name: 'Stadionbrücke', x: 31, y: 31.5 },
    'bahnhof-linden-fischerhof': { name: 'Bahnhof Linden/Fischerhof', x: 31, y: 33.5 },
    schunemannplatz: { name: 'Schünemannplatz', x: 31, y: 35.5 },
    beekestrasse: { name: 'Beekestraße', x: 31, y: 37.5 },
    wallensteinstrasse: { name: 'Wallensteinstraße', x: 29, y: 37.5 },
    misburg: { name: 'Misburg', x: 60, y: 18.5 },
    'am-forstkamp': { name: 'Am Forstkamp', x: 59, y: 17 },
    kafkastrasse: { name: 'Kafkastraße', x: 57.5, y: 15.5 },
    schierholzstrasse: { name: 'Schierholzstraße', x: 56, y: 14 },
    pappelwiese: { name: 'Pappelwiese', x: 54.5, y: 13 },
    paracelsusweg: { name: 'Paracelsusweg', x: 53, y: 11.5 },
    'in-den-sieben-stucken': { name: 'In den Sieben Stücken', x: 50.5, y: 11.5 },
    noltemeyerbrucke: { name: 'Noltemeyerbrücke', x: 48.5, y: 11.5 },
    klingerstrasse: { name: 'Klingerstraße', x: 46.5, y: 13 },
    spannhagengarten: { name: 'Spannhagengarten', x: 45, y: 14 },
    pelikanstrasse: { name: 'Pelikanstraße', x: 43.5, y: 15.5 },
    'vier-grenzen': { name: 'Vier Grenzen', x: 41.5, y: 17 },
    lortzingstrasse: { name: 'Lortzingstraße', x: 40, y: 18.5 },
    'lister-platz': { name: 'Lister Platz', x: 38, y: 20 },
    'sedanstrasse-lister-meile': { name: 'Sedanstraße/Lister Meile', x: 36.5, y: 21.5 },
    'markthalle-landtag-u': { name: 'Markthalle/Landtag (U)', x: 34, y: 26.5 },
    waterloo: { name: 'Waterloo', x: 32.5, y: 28 },
    'bartold-knaust-strasse': { name: 'Bartold-Knaust-Straße', x: 27, y: 37.5 },
    'am-sauerwinkel': { name: 'Am Sauerwinkel', x: 25, y: 37.5 },
    'muhlenberger-markt': { name: 'Mühlenberger Markt', x: 23, y: 37.5 },
    tresckowstrasse: { name: 'Tresckowstraße', x: 21.5, y: 39 },
    wettbergen: { name: 'Wettbergen', x: 21.5, y: 41 },
    altwarmbuchen: { name: 'Altwarmbüchen', x: 59, y: 1.5 },
    'altwarmbuchen-zentrum': { name: 'Altwarmbüchen / Zentrum', x: 59, y: 3.5 },
    'altwarmbuchen-ernst-grote-strasse': { name: 'Altwarmbüchen/Ernst-Grote-Straße', x: 59, y: 5.5 },
    'altwarmbuchen-opelstrasse': { name: 'Altwarmbüchen/Opelstraße', x: 57.5, y: 7 },
    'oldenburger-allee': { name: 'Oldenburger Allee', x: 56, y: 8.5 },
    'stadtfriedhof-lahe': { name: 'Stadtfriedhof Lahe', x: 54.5, y: 10 },
    empelde: { name: 'Empelde', x: 16.5, y: 36 },
    'hermann-ehlers-allee': { name: 'Hermann-Ehlers-Allee', x: 17.5, y: 34.5 },
    safariweg: { name: 'Safariweg', x: 17.5, y: 32.5 },
    'am-soltekampe': { name: 'Am Soltekampe', x: 19, y: 31 },
    'kortingsdorfer-weg': { name: 'Körtingsdorfer Weg', x: 20.5, y: 29.5 },
    bauweg: { name: 'Bauweg', x: 22.5, y: 29.5 },
    'am-lindener-hafen': { name: 'Am Lindener Hafen', x: 22.5, y: 27.5 },
    'bernhard-caspar-strasse': { name: 'Bernhard-Caspar-Straße', x: 24.5, y: 27 },
    nieschlagstrasse: { name: 'Nieschlagstraße', x: 26.5, y: 27 },
    'lindener-marktplatz': { name: 'Lindener Marktplatz', x: 28, y: 28.5 },
    zoo: { name: 'Zoo', x: 41.5, y: 22.5 },
    'congress-centrum': { name: 'Congress Centrum', x: 41.5, y: 24.5, aka: ['Hannover Congress Centrum'] },
    clausewitzstrasse: { name: 'Clausewitzstraße', x: 41.5, y: 26.5 },
    haltenhoffstrasse: { name: 'Haltenhoffstraße', x: 29, y: 19 },
    ahlem: { name: 'Ahlem', x: 17, y: 24 },
    'gedenkstatte-ahlem': { name: 'Gedenkstätte Ahlem', x: 19, y: 24 },
    brunnenstrasse: { name: 'Brunnenstraße', x: 21, y: 24 },
    'harenberger-strasse': { name: 'Harenberger Straße', x: 23.5, y: 24 },
    'wunstorfer-strasse': { name: 'Wunstorfer Straße', x: 24.5, y: 25 },
    leinaustrasse: { name: 'Leinaustraße', x: 27, y: 25 },
    'am-kuchengarten': { name: 'Am Küchengarten', x: 28, y: 26.5 },
    glocksee: { name: 'Glocksee', x: 29.5, y: 25 },
    anderten: { name: 'Anderten', x: 63, y: 30 },
    'konigsberger-ring': { name: 'Königsberger Ring', x: 61, y: 30 },
    ostfeldstrasse: { name: 'Ostfeldstraße', x: 59, y: 30 },
    tiergarten: { name: 'Tiergarten', x: 57, y: 30 },
    'grosser-hillen': { name: 'Großer Hillen', x: 55, y: 30 },
    'saarbruckener-strasse': { name: 'Saarbrückener Straße', x: 53, y: 30 },
    bleekstrasse: { name: 'Bleekstraße', x: 51.5, y: 28.5 },
    annastift: { name: 'Annastift', x: 50, y: 27 },
    nackenberg: { name: 'Nackenberg', x: 48, y: 27 },
    uhlhornstrasse: { name: 'Uhlhornstraße', x: 46, y: 27 },
    kantplatz: { name: 'Kantplatz', x: 44, y: 26.5 },
    'konigsworther-platz': { name: 'Königsworther Platz', x: 31, y: 23.5 },
    'leibniz-universitat': { name: 'Leibniz Universität', x: 29.5, y: 22 },
    'schneiderberg-wilhelm-busch-museum': { name: 'Schneiderberg / Wilhelm-Busch-Museum', x: 28, y: 20.5 },
    appelstrasse: { name: 'Appelstraße', x: 26.5, y: 19 },
    'herrenhauser-garten': { name: 'Herrenhäuser Gärten', x: 24.5, y: 18.5 },
    schaumburgstrasse: { name: 'Schaumburgstraße', x: 22, y: 18.5 },
    'herrenhauser-markt': { name: 'Herrenhäuser Markt', x: 20, y: 18 },
    'bahnhof-leinhausen': { name: 'Bahnhof Leinhausen', x: 18.5, y: 16.5 },
    'stadtfriedhof-stocken': { name: 'Stadtfriedhof Stöcken', x: 17, y: 15.5 },
    freudenthalstrasse: { name: 'Freudenthalstraße', x: 15.5, y: 14 },
    'stockener-markt': { name: 'Stöckener Markt', x: 15.5, y: 12 },
    stocken: { name: 'Stöcken', x: 17, y: 10.5 },
    garbsen: { name: 'Garbsen', x: 0, y: 9 },
    'auf-der-horst-marshof': { name: 'Auf der Horst/Marshof', x: 2, y: 9 },
    'auf-der-horst-skorpiongasse': { name: 'Auf der Horst/Skorpiongasse', x: 4, y: 9 },
    'schonebecker-allee': { name: 'Schönebecker Allee', x: 5.5, y: 8 },
    pascalstrasse: { name: 'Pascalstraße', x: 7, y: 9.5 },
    'wissenschaftspark-marienwerder': { name: 'Wissenschaftspark Marienwerder', x: 9, y: 9.5 },
    jadekamp: { name: 'Jädekamp', x: 11, y: 9.5 },
    'auf-der-klappenburg': { name: 'Auf der Klappenburg', x: 12.5, y: 11 },
    lauckerthof: { name: 'Lauckerthof', x: 14, y: 12.5 },
    'bahnhof-karl-wiechert-allee': { name: 'Bahnhof Karl-Wiechert-Allee', x: 49.5, y: 25.5 },
    'misburger-strasse': { name: 'Misburger Straße', x: 49.5, y: 23.5 },
    'medizinische-hochschule': { name: 'Medizinische Hochschule', x: 49.5, y: 21.5 },
    roderbruchmarkt: { name: 'Roderbruchmarkt', x: 51, y: 20 },
    roderbruch: { name: 'Roderbruch', x: 52.5, y: 18.5 },
    'betriebshof-fuhsestrasse': { name: 'Betriebshof Fuhsestraße', x: 18.5, y: 14 },
    fasanenkrug: { name: 'Fasanenkrug', x: 47, y: 2 },
    'stadtfriedhof-bothfeld': { name: 'Stadtfriedhof Bothfeld', x: 47, y: 4 },
    'kurze-kamp-strasse': { name: 'Kurze-Kamp-Straße', x: 47, y: 6 },
    bothfeld: { name: 'Bothfeld', x: 47, y: 8 },
    'bothfelder-kirchweg': { name: 'Bothfelder Kirchweg', x: 48.5, y: 9.5 },
    'unter-den-birken': { name: 'Unter den Birken', x: 29, y: 39.5 },
    'stadtfriedhof-ricklingen': { name: 'Stadtfriedhof Ricklingen', x: 29, y: 41.5 },
    'hemmingen-saarstrasse': { name: 'Hemmingen/Saarstraße', x: 30.5, y: 43 },
    'hemmingen-zentrum': { name: 'Hemmingen/Zentrum', x: 30.5, y: 45 },
    'hemmingen-berliner-strasse': { name: 'Hemmingen/Berliner Straße', x: 32, y: 46.5 },
    hemmingen: { name: 'Hemmingen', x: 32, y: 48.5 },
  },
};
