// The maps this app knows. A new city is a data file beside this one, in the
// format described at the top of js/lib/metro.js, and one line here.
// scripts/metro-import.mjs writes both for a city in scripts/metro-cities.mjs.
export default [
  { id: 'toronto', city: 'Toronto', system: 'TTC Subway', country: 'Canada', flag: '🇨🇦', load: () => import('./toronto.js') },
  { id: 'vancouver', city: 'Vancouver', system: 'SkyTrain', country: 'Canada', flag: '🇨🇦', load: () => import('./vancouver.js') },
  { id: 'montreal', city: 'Montreal', system: 'Métro', country: 'Canada', flag: '🇨🇦', load: () => import('./montreal.js') },
  { id: 'ottawa', city: 'Ottawa', system: 'O-Train', country: 'Canada', flag: '🇨🇦', load: () => import('./ottawa.js') },
  { id: 'edmonton', city: 'Edmonton', system: 'LRT', country: 'Canada', flag: '🇨🇦', load: () => import('./edmonton.js') },
  { id: 'calgary', city: 'Calgary', system: 'CTrain', country: 'Canada', flag: '🇨🇦', load: () => import('./calgary.js') },
  { id: 'amsterdam', city: 'Amsterdam', system: 'Metro', country: 'Netherlands', flag: '🇳🇱', load: () => import('./amsterdam.js') },
  { id: 'utrecht', city: 'Utrecht', system: 'Tram', country: 'Netherlands', flag: '🇳🇱', load: () => import('./utrecht.js') },
  { id: 'the-hague', city: 'The Hague', system: 'RandstadRail', country: 'Netherlands', flag: '🇳🇱', load: () => import('./the-hague.js') },
  { id: 'rotterdam', city: 'Rotterdam', system: 'Metro', country: 'Netherlands', flag: '🇳🇱', load: () => import('./rotterdam.js') },
  { id: 'berlin', city: 'Berlin', system: 'U-Bahn and S-Bahn', country: 'Germany', flag: '🇩🇪', load: () => import('./berlin.js') },
  { id: 'hamburg', city: 'Hamburg', system: 'U-Bahn', country: 'Germany', flag: '🇩🇪', load: () => import('./hamburg.js') },
  { id: 'frankfurt', city: 'Frankfurt', system: 'U-Bahn', country: 'Germany', flag: '🇩🇪', load: () => import('./frankfurt.js') },
  { id: 'cologne', city: 'Köln', system: 'Stadtbahn', country: 'Germany', flag: '🇩🇪', load: () => import('./cologne.js') },
  { id: 'dusseldorf', city: 'Düsseldorf', system: 'Stadtbahn', country: 'Germany', flag: '🇩🇪', load: () => import('./dusseldorf.js') },
  { id: 'nuremberg', city: 'Nuremberg', system: 'U-Bahn', country: 'Germany', flag: '🇩🇪', load: () => import('./nuremberg.js') },
  { id: 'stuttgart', city: 'Stuttgart', system: 'Stadtbahn', country: 'Germany', flag: '🇩🇪', load: () => import('./stuttgart.js') },
  { id: 'hannover', city: 'Hannover', system: 'Stadtbahn', country: 'Germany', flag: '🇩🇪', load: () => import('./hannover.js') },
  { id: 'munich', city: 'Munich', system: 'U-Bahn', country: 'Germany', flag: '🇩🇪', load: () => import('./munich.js') },
  { id: 'london', city: 'London', system: 'Underground', country: 'United Kingdom', flag: '🇬🇧', load: () => import('./london.js') },
  { id: 'dublin', city: 'Dublin', system: 'Luas', country: 'Ireland', flag: '🇮🇪', load: () => import('./dublin.js') },
  { id: 'madrid', city: 'Madrid', system: 'Metro', country: 'Spain', flag: '🇪🇸', load: () => import('./madrid.js') },
  { id: 'zaragoza', city: 'Zaragoza', system: 'Tranvía', country: 'Spain', flag: '🇪🇸', load: () => import('./zaragoza.js') },
  { id: 'rome', city: 'Rome', system: 'Metropolitana', country: 'Italy', flag: '🇮🇹', load: () => import('./rome.js') },
  { id: 'milan', city: 'Milan', system: 'Metropolitana', country: 'Italy', flag: '🇮🇹', load: () => import('./milan.js') },
  { id: 'paris', city: 'Paris', system: 'Métro', country: 'France', flag: '🇫🇷', load: () => import('./paris.js') },
  { id: 'manchester', city: 'Manchester', system: 'Metrolink', country: 'United Kingdom', flag: '🇬🇧', load: () => import('./manchester.js') },
  { id: 'barcelona', city: 'Barcelona', system: 'Metro', country: 'Spain', flag: '🇪🇸', load: () => import('./barcelona.js') },
  { id: 'istanbul', city: 'Istanbul', system: 'Metro', country: 'Türkiye', flag: '🇹🇷', load: () => import('./istanbul.js') },
  { id: 'vienna', city: 'Vienna', system: 'U-Bahn', country: 'Austria', flag: '🇦🇹', load: () => import('./vienna.js') },
  { id: 'lisbon', city: 'Lisbon', system: 'Metro', country: 'Portugal', flag: '🇵🇹', load: () => import('./lisbon.js') },
  { id: 'athens', city: 'Athens', system: 'Metro', country: 'Greece', flag: '🇬🇷', load: () => import('./athens.js') },
  { id: 'budapest', city: 'Budapest', system: 'Metro', country: 'Hungary', flag: '🇭🇺', load: () => import('./budapest.js') },
  { id: 'copenhagen', city: 'Copenhagen', system: 'Metro', country: 'Denmark', flag: '🇩🇰', load: () => import('./copenhagen.js') },
  { id: 'brussels', city: 'Brussels', system: 'Metro', country: 'Belgium', flag: '🇧🇪', load: () => import('./brussels.js') },
  { id: 'stockholm', city: 'Stockholm', system: 'Tunnelbana', country: 'Sweden', flag: '🇸🇪', load: () => import('./stockholm.js') },
  { id: 'florence', city: 'Florence', system: 'Tramvia', country: 'Italy', flag: '🇮🇹', load: () => import('./florence.js') },
  { id: 'prague', city: 'Prague', system: 'Metro', country: 'Czechia', flag: '🇨🇿', load: () => import('./prague.js') },
  { id: 'busan', city: 'Busan', system: 'Metro', country: 'South Korea', flag: '🇰🇷', load: () => import('./busan.js') },
  { id: 'seoul', city: 'Seoul', system: 'Subway', country: 'South Korea', flag: '🇰🇷', load: () => import('./seoul.js') },
];
