// Istanbul's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'istanbul',
  name: 'Istanbul',
  system: 'Metro',
  country: 'Türkiye',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'b1',
      short: 'B1',
      name: 'Marmaray',
      colour: '#808080',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['gebze', 'dar-ca', 'osmangazi', 'gtu-fatih', 'cay-rova', 'tuzla', 'icmeler', 'ayd-ntepe', 'guzelyal', 'tersane', 'kaynarca', 'pendik-2', 'yunus', 'kartal-2', 'basak', 'atalar', 'cevizli', 'maltepe-2', 'sureyya-plaj', 'idealtepe', 'kucukyal-2', 'bostanc-2', 'suadiye', 'erenkoy', 'goztepe-2', 'feneryolu', 'sogutlucesme', 'ayr-l-k-cesmesi', 'uskudar', 'sirkeci', 'yenikap', 'kazl-cesme', 'zeytinburnu-fisekhane', 'yeni-mahalle', 'bak-rkoy', 'atakoy', 'yesilyurt', 'yesilkoy', 'florya-akvaryum', 'florya', 'kucukcekmece', 'mustafa-kemal', 'halkal'],
        ['atakoy', 'bak-rkoy', 'yeni-mahalle', 'zeytinburnu-fisekhane', 'kazl-cesme', 'yenikap', 'uskudar', 'ayr-l-k-cesmesi', 'sogutlucesme', 'feneryolu', 'goztepe-2', 'erenkoy', 'suadiye', 'bostanc-2', 'kucukyal-2', 'idealtepe', 'sureyya-plaj', 'maltepe-2', 'cevizli', 'atalar', 'basak', 'kartal-2', 'yunus', 'pendik-2'],
      ],
    },
    {
      id: 'm1a',
      short: 'M1A',
      name: 'M1A Yenikapı - Atatürk Havalimanı Metro Hattı',
      colour: '#ee3124',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['yenikap', 'aksaray', 'emniyet-fatih', 'topkap-ulubatl', 'bayrampasa-maltepe', 'sagmalc-lar', 'kocatepe', 'otogar', 'terazidere', 'davutpasa-ytu', 'merter', 'zeytinburnu', 'bak-rkoy-incirli', 'bahcelievler', 'atakoy-sirinevler', 'yenibosna', 'dtm-istanbul-fuar-merkezi', 'ataturk-havaliman'],
      ],
    },
    {
      id: 'm1b',
      short: 'M1B',
      name: 'M1B Yenikapı - Kirazlı Metro Hattı',
      colour: '#ee3124',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['yenikap', 'aksaray', 'emniyet-fatih', 'topkap-ulubatl', 'bayrampasa-maltepe', 'sagmalc-lar', 'kocatepe', 'otogar', 'esenler', 'menderes', 'ucyuzlu', 'bagc-lar-meydan', 'kirazl'],
      ],
    },
    {
      id: 'm2',
      short: 'M2',
      name: 'M2 Yenikapı - Seyrantepe - Hacıosman Metro Hattı',
      colour: '#009944',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['hac-osman', 'darussafaka', 'ataturk-oto-sanayi', 'itu-ayazaga', 'sanayi', 's-4-levent', 'levent', 'gayrettepe', 'sisli', 'osmanbey', 'taksim', 'sishane', 'halic', 'vezneciler', 'yenikap'],
        ['seyrantepe', 'sanayi'],
      ],
    },
    {
      id: 'm3',
      short: 'M3',
      name: 'M3 Bakırköy - Kayaşehir Metro Hattı',
      colour: '#00a8e1',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['bak-rkoy-sahil', 'ozgurluk-meydan', 'incirli', 'haznedar', 'ilkyuva', 'y-ld-ztepe', 'molla-gurani', 'kirazl', 'yeni-mahalle-2', 'mahmutbey', 'istoc', 'ikitelli-sanayi', 'turgut-ozal', 'siteler', 'basak-konutlar', 'metrokent', 'onurkent', 'sehir-hastanesi', 'toplu-konutlar', 'kayasehir-merkez'],
      ],
    },
    {
      id: 'm4',
      short: 'M4',
      name: 'M4 Kadıköy - Sabiha Gökçen Havalimanı Metro Hattı',
      colour: '#e91e76',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['kad-koy', 'ayr-l-k-cesmesi', 'ac-badem', 'unalan', 'goztepe', 'yenisahra', 'kozyatag', 'bostanc', 'kucukyal', 'maltepe', 'huzurevi', 'gulsuyu', 'esenkent', 'hastane-adliye', 'soganl-k', 'kartal', 'yakac-k-adnan-kahveci', 'pendik', 'tavsantepe', 'fevzi-cakmak-hastane', 'yayalar-seyhli', 'kurtkoy', 'sabiha-gokcen-havaliman'],
      ],
    },
    {
      id: 'm5',
      short: 'M5',
      name: 'M5 Üsküdar - Sultanbeyli Metro Hattı',
      colour: '#683064',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['uskudar', 'f-st-kagac', 'baglarbas', 'altunizade', 'k-s-kl', 'bulgurlu', 'umraniye', 'cars', 'yamanevler', 'cakmak', 'ihlamurkuyu', 'alt-nsehir', 'imam-hatip-lisesi', 'dudullu', 'necip-faz-l', 'cekmekoy', 'meclis', 'sar-gazi', 'sancaktepe-sehir-hastanesi', 'sancaktepe', 'samand-ra-merkez', 'veysel-karani', 'hasanpasa', 'sultanbeyli'],
      ],
    },
    {
      id: 'm6',
      short: 'M6',
      name: 'M6 Levent - Boğaziçi Üniversitesi/Hisarüstü Metro Hattı',
      colour: '#caa977',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['bogazici-universitesi-hisarustu', 'etiler', 'nispetiye', 'levent'],
      ],
    },
    {
      id: 'm7',
      short: 'M7',
      name: 'M7 Yıldız - Mahmutbey Metro Hattı',
      colour: '#f89aba',
      text: '#1a1a1a',
      minutes: 3,
      branches: [
        ['mecidiyekoy', 'caglayan', 'kag-thane', 'nurtepe', 'alibeykoy', 'c-rc-r-mahallesi', 'veysel-karani-aksemsettin', 'yesilp-nar', 'kaz-m-karabekir', 'yenimahalle', 'karadeniz-mahallesi', 'giyimkent-tekstilkent', 'oruc-reis-yuzy-l', 'goztepe-3', 'mahmutbey'],
        ['y-ld-z', 'fulya', 'mecidiyekoy'],
      ],
    },
    {
      id: 'm8',
      short: 'M8',
      name: 'M8 Bostancı - Parseller Metro Hattı',
      colour: '#447abe',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['bostanc-2', 'emin-ali-pasa', 'aysekad-n', 'kozyatag', 'kucukbakkalkoy', 'icerenkoy', 'kay-sdag', 'mevlana', 'imes', 'modoko', 'dudullu', 'huzur', 'parseller'],
      ],
    },
    {
      id: 'm9',
      short: 'M9',
      name: 'M9 Ataköy - Olimpiyat Metro Hattı',
      colour: '#f0e514',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['atakoy', 'yenibosna', 'cobancesme', 's-29-ekim-cumhuriyet', 'dogu-sanayi', 'mimar-sinan', 's-15-temmuz', 'halkal-caddesi', 'ataturk-mahallesi', 'bahariye', 'masko', 'ikitelli-sanayi', 'ziya-gokalp', 'olimpiyat'],
      ],
    },
    {
      id: 'm11',
      short: 'M11',
      name: 'M11 Gayrettepe - İstanbul Havalimanı - Halkalı Metro Hattı',
      colour: '#ab548f',
      text: '#ffffff',
      minutes: 8,
      branches: [
        ['halkal', 'halkal-stad', 'olimpiyatkoy', 'kayasehir', 'ibn-haldun-universitesi', 'arnavutkoy-hastane', 'tasoluk', 'kargo-terminali', 'istanbul-havaliman', 'ihsaniye', 'gokturk', 'kemerburgaz', 'hasdal', 'kag-thane', 'gayrettepe'],
      ],
    },
  ],
  times: {
    'gebze dar-ca': 4,
    'osmangazi gtu-fatih': 4,
    'cay-rova tuzla': 6,
    'tuzla icmeler': 5,
    'icmeler ayd-ntepe': 2,
    'ayd-ntepe guzelyal': 2,
    'guzelyal tersane': 2,
    'tersane kaynarca': 4,
    'kaynarca pendik-2': 5,
    'pendik-2 yunus': 4,
    'yunus kartal-2': 4,
    'atalar cevizli': 4,
    'cevizli maltepe-2': 5,
    'maltepe-2 sureyya-plaj': 2,
    'ayr-l-k-cesmesi uskudar': 6,
    'uskudar sirkeci': 7,
    'sirkeci yenikap': 5,
    'yenikap kazl-cesme': 6,
    'zeytinburnu-fisekhane yeni-mahalle': 4,
    'yeni-mahalle bak-rkoy': 2,
    'atakoy yesilyurt': 5,
    'yesilyurt yesilkoy': 2,
    'yesilkoy florya-akvaryum': 5,
    'florya-akvaryum florya': 2,
    'florya kucukcekmece': 4,
    'kucukcekmece mustafa-kemal': 4,
    'bak-rkoy yeni-mahalle': 2,
    'yeni-mahalle zeytinburnu-fisekhane': 4,
    'kazl-cesme yenikap': 6,
    'yenikap uskudar': 11,
    'uskudar ayr-l-k-cesmesi': 6,
    'sureyya-plaj maltepe-2': 2,
    'maltepe-2 cevizli': 5,
    'cevizli atalar': 4,
    'kartal-2 yunus': 4,
    'yunus pendik-2': 4,
    'topkap-ulubatl bayrampasa-maltepe': 3,
    'bayrampasa-maltepe sagmalc-lar': 3,
    'sagmalc-lar kocatepe': 3,
    'otogar terazidere': 3,
    'terazidere davutpasa-ytu': 3,
    'davutpasa-ytu merter': 3,
    'zeytinburnu bak-rkoy-incirli': 3,
    'bahcelievler atakoy-sirinevler': 3,
    'ucyuzlu bagc-lar-meydan': 3,
    'bagc-lar-meydan kirazl': 3,
    'itu-ayazaga sanayi': 4,
    'sanayi s-4-levent': 2,
    'levent gayrettepe': 2,
    'osmanbey taksim': 4,
    'sishane halic': 2,
    'vezneciler yenikap': 2,
    'ozgurluk-meydan incirli': 4,
    'yeni-mahalle-2 mahmutbey': 4,
    'mahmutbey istoc': 3,
    'istoc ikitelli-sanayi': 4,
    'ikitelli-sanayi turgut-ozal': 3,
    'siteler basak-konutlar': 3,
    'basak-konutlar metrokent': 3,
    'onurkent sehir-hastanesi': 3,
    'toplu-konutlar kayasehir-merkez': 3,
    'unalan goztepe': 2,
    'goztepe yenisahra': 4,
    'bostanc kucukyal': 5,
    'kucukyal maltepe': 4,
    'maltepe huzurevi': 2,
    'huzurevi gulsuyu': 2,
    'gulsuyu esenkent': 2,
    'soganl-k kartal': 4,
    'kartal yakac-k-adnan-kahveci': 4,
    'fevzi-cakmak-hastane yayalar-seyhli': 4,
    'yayalar-seyhli kurtkoy': 4,
    'uskudar f-st-kagac': 3,
    'altunizade k-s-kl': 3,
    'k-s-kl bulgurlu': 3,
    'bulgurlu umraniye': 3,
    'dudullu necip-faz-l': 3,
    'meclis sar-gazi': 3,
    'sancaktepe-sehir-hastanesi sancaktepe': 3,
    'samand-ra-merkez veysel-karani': 4,
    'veysel-karani hasanpasa': 3,
    'hasanpasa sultanbeyli': 3,
    'etiler nispetiye': 3,
    'kag-thane nurtepe': 2,
    'c-rc-r-mahallesi veysel-karani-aksemsettin': 2,
    'veysel-karani-aksemsettin yesilp-nar': 2,
    'yesilp-nar kaz-m-karabekir': 2,
    'oruc-reis-yuzy-l goztepe-3': 2,
    'y-ld-z fulya': 2,
    'fulya mecidiyekoy': 2,
    'aysekad-n kozyatag': 3,
    'kucukbakkalkoy icerenkoy': 3,
    'icerenkoy kay-sdag': 3,
    'kay-sdag mevlana': 3,
    'huzur parseller': 3,
    'atakoy yenibosna': 4,
    'yenibosna cobancesme': 4,
    'dogu-sanayi mimar-sinan': 3,
    'mimar-sinan s-15-temmuz': 3,
    'ikitelli-sanayi ziya-gokalp': 3,
    'ziya-gokalp olimpiyat': 4,
    'halkal-stad olimpiyatkoy': 5,
    'olimpiyatkoy kayasehir': 9,
    'kayasehir ibn-haldun-universitesi': 7,
    'ibn-haldun-universitesi arnavutkoy-hastane': 12,
    'tasoluk kargo-terminali': 11,
    'kargo-terminali istanbul-havaliman': 5,
    'istanbul-havaliman ihsaniye': 11,
    'ihsaniye gokturk': 19,
    'gokturk kemerburgaz': 6,
    'kemerburgaz hasdal': 10,
    'hasdal kag-thane': 10,
    'kag-thane gayrettepe': 7,
  },
  stations: {
    yenikap: { name: 'Yenikapı', x: 28, y: 25 },
    aksaray: { name: 'Aksaray', x: 26, y: 25 },
    'emniyet-fatih': { name: 'Emniyet - Fatih', x: 24.5, y: 23 },
    'topkap-ulubatl': { name: 'Topkapı Ulubatlı', x: 23, y: 21.5 },
    'bayrampasa-maltepe': { name: 'Bayrampaşa-Maltepe', x: 21.5, y: 20 },
    'sagmalc-lar': { name: 'Sağmalcılar', x: 20.5, y: 18.5 },
    kocatepe: { name: 'Kocatepe', x: 19, y: 16.5 },
    otogar: { name: 'Otogar', x: 18.5, y: 18.5 },
    terazidere: { name: 'Terazidere', x: 19, y: 20 },
    'davutpasa-ytu': { name: 'Davutpaşa - YTÜ', x: 19, y: 22 },
    merter: { name: 'Merter', x: 19, y: 24 },
    zeytinburnu: { name: 'Zeytinburnu', x: 17.5, y: 25 },
    'bak-rkoy-incirli': { name: 'Bakırköy-İncirli', x: 16, y: 25 },
    bahcelievler: { name: 'Bahçelievler', x: 13.5, y: 24.5 },
    'atakoy-sirinevler': { name: 'Ataköy-Şirinevler', x: 12, y: 25.5 },
    yenibosna: { name: 'Yenibosna', x: 11, y: 26.5 },
    'dtm-istanbul-fuar-merkezi': { name: 'DTM-İstanbul Fuar Merkezi', x: 8.5, y: 26.5 },
    'ataturk-havaliman': { name: 'Atatürk Havalimanı', x: 8.5, y: 29 },
    'kad-koy': { name: 'Kadıköy', x: 33.5, y: 27.5 },
    'ayr-l-k-cesmesi': { name: 'Ayrılık Çeşmesi', x: 34, y: 25.5 },
    'ac-badem': { name: 'Acıbadem', x: 36.5, y: 26 },
    unalan: { name: 'Ünalan', x: 39, y: 26 },
    goztepe: { name: 'Göztepe', x: 41, y: 28 },
    yenisahra: { name: 'Yenisahra', x: 43, y: 29.5 },
    kozyatag: { name: 'Kozyatağı', x: 45, y: 31 },
    bostanc: { name: 'Bostancı', x: 46.5, y: 33 },
    kucukyal: { name: 'Küçükyalı', x: 48, y: 34.5 },
    maltepe: { name: 'Maltepe', x: 50, y: 36 },
    huzurevi: { name: 'Huzurevi', x: 51.5, y: 37.5 },
    gulsuyu: { name: 'Gülsuyu', x: 53, y: 39 },
    esenkent: { name: 'Esenkent', x: 55.5, y: 39 },
    'hastane-adliye': { name: 'Hastane Adliye', x: 57, y: 40.5 },
    'soganl-k': { name: 'Soğanlık', x: 59, y: 40.5 },
    kartal: { name: 'Kartal', x: 61, y: 42 },
    'yakac-k-adnan-kahveci': { name: 'Yakacık—Adnan Kahveci', x: 62.5, y: 43.5 },
    pendik: { name: 'Pendik', x: 64, y: 45 },
    tavsantepe: { name: 'Tavşantepe', x: 65.5, y: 46.5 },
    'fevzi-cakmak-hastane': { name: 'Fevzi Çakmak - Hastane', x: 67, y: 45 },
    'yayalar-seyhli': { name: 'Yayalar-Şeyhli', x: 68.5, y: 43.5 },
    kurtkoy: { name: 'Kurtköy', x: 70, y: 42.5 },
    'sabiha-gokcen-havaliman': { name: 'Sabiha Gökçen Havalimanı', x: 72, y: 42.5 },
    esenler: { name: 'Esenler', x: 17.5, y: 19.5 },
    menderes: { name: 'Menderes', x: 16, y: 18 },
    ucyuzlu: { name: 'Üçyüzlü', x: 14.5, y: 19.5 },
    'bagc-lar-meydan': { name: 'Bağcılar Meydan', x: 12.5, y: 19.5 },
    kirazl: { name: 'Kirazlı', x: 10.5, y: 19.5 },
    atakoy: { name: 'Ataköy', x: 13.5, y: 26.5 },
    'bak-rkoy': { name: 'Bakırköy', x: 16.5, y: 26 },
    'yeni-mahalle': { name: 'Yeni Mahalle', x: 19, y: 26 },
    'zeytinburnu-fisekhane': { name: 'Zeytinburnu-Fişekhane', x: 22, y: 25.5 },
    'kazl-cesme': { name: 'Kazlıçeşme', x: 24.5, y: 25.5 },
    uskudar: { name: 'Üsküdar', x: 30.5, y: 25 },
    sogutlucesme: { name: 'Söğütlüçeşme', x: 35.5, y: 27.5 },
    feneryolu: { name: 'Feneryolu', x: 37.5, y: 29 },
    'goztepe-2': { name: 'Göztepe', x: 39.5, y: 30.5 },
    erenkoy: { name: 'Erenköy', x: 41, y: 32.5 },
    suadiye: { name: 'Suadiye', x: 43, y: 34 },
    'bostanc-2': { name: 'Bostancı', x: 45, y: 35.5 },
    'kucukyal-2': { name: 'Küçükyalı', x: 46.5, y: 37 },
    idealtepe: { name: 'İdealtepe', x: 48.5, y: 39 },
    'sureyya-plaj': { name: 'Süreyya Plajı', x: 50, y: 40.5 },
    'maltepe-2': { name: 'Maltepe', x: 52, y: 42 },
    cevizli: { name: 'Cevizli', x: 53.5, y: 43.5 },
    atalar: { name: 'Atalar', x: 55.5, y: 45 },
    basak: { name: 'Başak', x: 57, y: 46.5 },
    'kartal-2': { name: 'Kartal', x: 59.5, y: 47 },
    yunus: { name: 'Yunus', x: 61.5, y: 47 },
    'pendik-2': { name: 'Pendik', x: 64, y: 47 },
    'bak-rkoy-sahil': { name: 'Bakırköy Sahil', x: 14.5, y: 29 },
    'ozgurluk-meydan': { name: 'Özgürlük Meydanı', x: 16, y: 28 },
    incirli: { name: 'İncirli', x: 14.5, y: 26 },
    haznedar: { name: 'Haznedar', x: 15, y: 24 },
    ilkyuva: { name: 'İlkyuva', x: 13.5, y: 22.5 },
    'y-ld-ztepe': { name: 'Yıldıztepe', x: 12, y: 21.5 },
    'molla-gurani': { name: 'Molla Gürani', x: 10.5, y: 21.5 },
    'yeni-mahalle-2': { name: 'Yeni Mahalle', x: 9, y: 18 },
    mahmutbey: { name: 'Mahmutbey', x: 9.5, y: 16 },
    istoc: { name: 'İSTOÇ', x: 8.5, y: 14.5 },
    'ikitelli-sanayi': { name: 'İkitelli Sanayi', x: 7, y: 13.5 },
    'turgut-ozal': { name: 'Turgut Özal', x: 6, y: 12 },
    siteler: { name: 'Siteler', x: 5.5, y: 10.5 },
    'basak-konutlar': { name: 'Başak Konutları', x: 3.5, y: 9 },
    metrokent: { name: 'Metrokent', x: 5, y: 7.5 },
    onurkent: { name: 'Onurkent', x: 3.5, y: 6 },
    'sehir-hastanesi': { name: 'Şehir Hastanesi', x: 2, y: 7.5 },
    'toplu-konutlar': { name: 'Toplu Konutlar', x: 0, y: 7.5 },
    'kayasehir-merkez': { name: 'Kayaşehir Merkez', x: 0, y: 5.5 },
    cobancesme: { name: 'Çobançeşme', x: 9.5, y: 25.5 },
    's-29-ekim-cumhuriyet': { name: '29 Ekim Cumhuriyet', x: 8, y: 24.5 },
    'dogu-sanayi': { name: 'Doğu Sanayi', x: 8, y: 22.5 },
    'mimar-sinan': { name: 'Mimar Sinan', x: 8, y: 21 },
    's-15-temmuz': { name: '15 Temmuz', x: 8, y: 19 },
    'halkal-caddesi': { name: 'Halkalı Caddesi', x: 7, y: 18 },
    'ataturk-mahallesi': { name: 'Atatürk Mahallesi', x: 5.5, y: 17 },
    bahariye: { name: 'Bahariye', x: 5.5, y: 15 },
    masko: { name: 'MASKO', x: 7, y: 15.5 },
    'ziya-gokalp': { name: 'Ziya Gökalp', x: 5, y: 13.5 },
    olimpiyat: { name: 'Olimpiyat', x: 3, y: 13.5 },
    'hac-osman': { name: 'Hacıosman', x: 33, y: 0.5 },
    darussafaka: { name: 'Darüşşafaka', x: 33, y: 2.5 },
    'ataturk-oto-sanayi': { name: 'Atatürk Oto Sanayi', x: 33, y: 4.5 },
    'itu-ayazaga': { name: 'İTÜ-Ayazağa', x: 33, y: 6.5 },
    sanayi: { name: 'Sanayi', x: 31.5, y: 8 },
    's-4-levent': { name: '4. Levent', x: 31, y: 10 },
    levent: { name: 'Levent', x: 29.5, y: 11.5 },
    gayrettepe: { name: 'Gayrettepe', x: 27.5, y: 10 },
    sisli: { name: 'Şişli', x: 28, y: 13 },
    osmanbey: { name: 'Osmanbey', x: 28.5, y: 15.5 },
    taksim: { name: 'Taksim', x: 29, y: 17.5 },
    sishane: { name: 'Şişhane', x: 28, y: 19.5 },
    halic: { name: 'Haliç', x: 27, y: 21.5 },
    vezneciler: { name: 'Vezneciler', x: 26, y: 23 },
    'bogazici-universitesi-hisarustu': { name: 'Boğaziçi Üniversitesi/Hisarüstü', x: 35, y: 10 },
    etiler: { name: 'Etiler', x: 33.5, y: 11.5 },
    nispetiye: { name: 'Nispetiye', x: 31.5, y: 11.5 },
    seyrantepe: { name: 'Seyrantepe', x: 29.5, y: 8 },
    gebze: { name: 'Gebze', x: 82.5, y: 63.5 },
    'dar-ca': { name: 'Darıca', x: 81, y: 62.5 },
    osmangazi: { name: 'Osmangazi', x: 79.5, y: 61 },
    'gtu-fatih': { name: 'GTÜ-Fatih', x: 78, y: 59.5 },
    'cay-rova': { name: 'Çayırova', x: 76, y: 58 },
    tuzla: { name: 'Tuzla', x: 74.5, y: 56.5 },
    icmeler: { name: 'İçmeler', x: 73, y: 55 },
    'ayd-ntepe': { name: 'Aydıntepe', x: 71, y: 53.5 },
    guzelyal: { name: 'Güzelyalı', x: 69.5, y: 52 },
    tersane: { name: 'Tersane', x: 67.5, y: 50 },
    kaynarca: { name: 'Kaynarca', x: 66, y: 48.5 },
    sirkeci: { name: 'Sirkeci', x: 29.5, y: 23.5 },
    yesilyurt: { name: 'Yeşilyurt', x: 12, y: 28 },
    yesilkoy: { name: 'Yeşilköy', x: 9.5, y: 27.5 },
    'florya-akvaryum': { name: 'Florya Akvaryum', x: 7, y: 27 },
    florya: { name: 'Florya', x: 5.5, y: 25 },
    kucukcekmece: { name: 'Küçükçekmece', x: 4, y: 23 },
    'mustafa-kemal': { name: 'Mustafa Kemal', x: 4, y: 20 },
    halkal: { name: 'Halkalı', x: 4, y: 17.5 },
    'f-st-kagac': { name: 'Fıstıkağacı', x: 32, y: 23.5 },
    baglarbas: { name: 'Bağlarbaşı', x: 34.5, y: 23 },
    altunizade: { name: 'Altunizade', x: 36.5, y: 23 },
    'k-s-kl': { name: 'Kısıklı', x: 38.5, y: 22.5 },
    bulgurlu: { name: 'Bulgurlu', x: 40, y: 24 },
    umraniye: { name: 'Ümraniye', x: 41.5, y: 22 },
    cars: { name: 'Çarşı', x: 43.5, y: 22 },
    yamanevler: { name: 'Yamanevler', x: 45.5, y: 21.5 },
    cakmak: { name: 'Çakmak', x: 47, y: 23 },
    ihlamurkuyu: { name: 'Ihlamurkuyu', x: 49, y: 22.5 },
    'alt-nsehir': { name: 'Altınşehir', x: 50, y: 23.5 },
    'imam-hatip-lisesi': { name: 'İmam Hatip Lisesi', x: 52, y: 23.5 },
    dudullu: { name: 'Dudullu', x: 54, y: 23 },
    'necip-faz-l': { name: 'Necip Fazıl', x: 56, y: 23.5 },
    cekmekoy: { name: 'Çekmeköy', x: 58, y: 23.5 },
    meclis: { name: 'Meclis', x: 59.5, y: 24.5 },
    'sar-gazi': { name: 'Sarıgazi', x: 61.5, y: 24.5 },
    'sancaktepe-sehir-hastanesi': { name: 'Sancaktepe Şehir Hastanesi', x: 61.5, y: 26.5 },
    sancaktepe: { name: 'Sancaktepe', x: 63, y: 28 },
    'samand-ra-merkez': { name: 'Samandıra Merkez', x: 63, y: 30 },
    'veysel-karani': { name: 'Veysel Karani', x: 64.5, y: 31.5 },
    hasanpasa: { name: 'Hasanpaşa', x: 66.5, y: 31.5 },
    sultanbeyli: { name: 'Sultanbeyli', x: 68.5, y: 31.5 },
    mecidiyekoy: { name: 'Mecidiyeköy', x: 28, y: 11.5 },
    caglayan: { name: 'Çağlayan', x: 26.5, y: 10 },
    'kag-thane': { name: 'Kağıthane', x: 25, y: 8.5 },
    nurtepe: { name: 'Nurtepe', x: 25, y: 10.5 },
    alibeykoy: { name: 'Alibeyköy', x: 24, y: 12 },
    'c-rc-r-mahallesi': { name: 'Çırçır Mahallesi', x: 22.5, y: 12 },
    'veysel-karani-aksemsettin': { name: 'Veysel Karani-Akşemsettin', x: 21, y: 13.5 },
    'yesilp-nar': { name: 'Yeşilpınar', x: 20, y: 12 },
    'kaz-m-karabekir': { name: 'Kâzım Karabekir', x: 18, y: 12 },
    yenimahalle: { name: 'Yenimahalle', x: 16.5, y: 12 },
    'karadeniz-mahallesi': { name: 'Karadeniz Mahallesi', x: 14.5, y: 12 },
    'giyimkent-tekstilkent': { name: 'Giyimkent-Tekstilkent', x: 13.5, y: 13 },
    'oruc-reis-yuzy-l': { name: 'Oruç Reis - Yüzyıl', x: 12.5, y: 14.5 },
    'goztepe-3': { name: 'Göztepe', x: 11, y: 16 },
    'emin-ali-pasa': { name: 'Emin Ali Paşa', x: 45, y: 34 },
    'aysekad-n': { name: 'Ayşekadın', x: 43.5, y: 32.5 },
    kucukbakkalkoy: { name: 'Küçükbakkalköy', x: 46.5, y: 30 },
    icerenkoy: { name: 'İçerenköy', x: 49, y: 30.5 },
    'kay-sdag': { name: 'Kayışdağı', x: 50.5, y: 29 },
    mevlana: { name: 'Mevlana', x: 52, y: 28 },
    imes: { name: 'İMES', x: 52.5, y: 26 },
    modoko: { name: 'MODOKO', x: 54, y: 25 },
    huzur: { name: 'Huzur', x: 52.5, y: 22 },
    parseller: { name: 'Parseller', x: 51, y: 20.5 },
    'halkal-stad': { name: 'Halkalı Stadı', x: 4, y: 14.5 },
    olimpiyatkoy: { name: 'Olimpiyatköy', x: 4.5, y: 11.5 },
    kayasehir: { name: 'Kayaşehir', x: 5, y: 9 },
    'ibn-haldun-universitesi': { name: 'İbn Haldun Üniversitesi', x: 6, y: 6.5 },
    'arnavutkoy-hastane': { name: 'Arnavutköy Hastane', x: 6.5, y: 4 },
    tasoluk: { name: 'Taşoluk', x: 7, y: 1.5 },
    'kargo-terminali': { name: 'Kargo Terminali', x: 9.5, y: 0 },
    'istanbul-havaliman': { name: 'İstanbul Havalimanı', x: 12.5, y: 0 },
    ihsaniye: { name: 'İhsaniye', x: 15, y: 1.5 },
    gokturk: { name: 'Göktürk', x: 17.5, y: 3 },
    kemerburgaz: { name: 'Kemerburgaz', x: 20, y: 5 },
    hasdal: { name: 'Hasdal', x: 22.5, y: 7 },
    'y-ld-z': { name: 'Yıldız', x: 31, y: 14.5 },
    fulya: { name: 'Fulya', x: 29.5, y: 13 },
  },
};
