// Lisbon's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'lisbon',
  name: 'Lisbon',
  system: 'Metro',
  country: 'Portugal',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'amarela',
      short: '',
      name: 'Linha Amarela',
      colour: '#f4bc18',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['rato', 'marques-de-pombal', 'picoas', 'saldanha', 'campo-pequeno', 'entrecampos', 'cidade-universitaria', 'campo-grande', 'quinta-das-conchas', 'lumiar', 'ameixoeira', 'senhor-roubado', 'odivelas'],
      ],
    },
    {
      id: 'azul',
      short: '',
      name: 'Linha Azul',
      colour: '#4e84c4',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['santa-apolonia', 'terreiro-do-paco', 'baixa-chiado', 'restauradores', 'avenida', 'marques-de-pombal', 'parque', 'sao-sebastiao', 'praca-de-espanha', 'jardim-zoologico', 'laranjeiras', 'alto-dos-moinhos', 'colegio-militar-luz', 'carnide', 'pontinha', 'alfornelos', 'amadora-este', 'reboleira'],
      ],
    },
    {
      id: 'verde',
      short: '',
      name: 'Linha Verde',
      colour: '#00aaa6',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['cais-do-sodre', 'baixa-chiado', 'rossio', 'martim-moniz', 'intendente', 'anjos', 'arroios', 'alameda', 'areeiro', 'roma', 'alvalade', 'campo-grande', 'telheiras'],
      ],
    },
    {
      id: 'vermelha',
      short: '',
      name: 'Linha Vermelha',
      colour: '#df096f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['sao-sebastiao', 'saldanha', 'alameda', 'olaias', 'bela-vista', 'chelas', 'olivais', 'cabo-ruivo', 'oriente', 'moscavide', 'encarnacao', 'aeroporto'],
      ],
    },
  ],
  times: {
    'picoas saldanha': 1,
    'ameixoeira senhor-roubado': 3,
    'santa-apolonia terreiro-do-paco': 3,
    'restauradores avenida': 1,
    'marques-de-pombal parque': 1,
    'carnide pontinha': 1,
    'alfornelos amadora-este': 3,
    'baixa-chiado rossio': 1,
    'rossio martim-moniz': 1,
    'intendente anjos': 1,
    'arroios alameda': 1,
    'alvalade campo-grande': 3,
    'encarnacao aeroporto': 3,
  },
  stations: {
    rato: { name: 'Rato', x: 15, y: 21 },
    'marques-de-pombal': { name: 'Marquês de Pombal', x: 16.5, y: 20 },
    picoas: { name: 'Picoas', x: 18, y: 18.5 },
    saldanha: { name: 'Saldanha', x: 18.5, y: 16 },
    'campo-pequeno': { name: 'Campo Pequeno', x: 17, y: 14.5 },
    entrecampos: { name: 'Entrecampos', x: 17, y: 13 },
    'cidade-universitaria': { name: 'Cidade Universitária', x: 16, y: 11.5 },
    'campo-grande': { name: 'Campo Grande', x: 16, y: 9.5 },
    'quinta-das-conchas': { name: 'Quinta das Conchas', x: 16, y: 7.5 },
    lumiar: { name: 'Lumiar', x: 16, y: 5.5 },
    ameixoeira: { name: 'Ameixoeira', x: 15.5, y: 3.5 },
    'senhor-roubado': { name: 'Senhor Roubado', x: 14.5, y: 2 },
    odivelas: { name: 'Odivelas', x: 14.5, y: 0 },
    'santa-apolonia': { name: 'Santa Apolónia', x: 21.5, y: 23.5 },
    'terreiro-do-paco': { name: 'Terreiro do Paço', x: 20, y: 25 },
    'baixa-chiado': { name: 'Baixa-Chiado', x: 18, y: 25 },
    restauradores: { name: 'Restauradores', x: 18, y: 23 },
    avenida: { name: 'Avenida', x: 18, y: 21 },
    parque: { name: 'Parque', x: 16.5, y: 18 },
    'sao-sebastiao': { name: 'São Sebastião', x: 16.5, y: 16 },
    'praca-de-espanha': { name: 'Praça de Espanha', x: 14.5, y: 16 },
    'jardim-zoologico': { name: 'Jardim Zoológico', x: 13, y: 14.5 },
    laranjeiras: { name: 'Laranjeiras', x: 11.5, y: 13 },
    'alto-dos-moinhos': { name: 'Alto dos Moinhos', x: 9.5, y: 13 },
    'colegio-militar-luz': { name: 'Colégio Militar/Luz', x: 8, y: 12 },
    carnide: { name: 'Carnide', x: 7, y: 10.5 },
    pontinha: { name: 'Pontinha', x: 5.5, y: 9 },
    alfornelos: { name: 'Alfornelos', x: 3.5, y: 9 },
    'amadora-este': { name: 'Amadora Este', x: 1.5, y: 9 },
    reboleira: { name: 'Reboleira', x: 0, y: 10.5 },
    'cais-do-sodre': { name: 'Cais do Sodré', x: 16, y: 25 },
    rossio: { name: 'Rossio', x: 19.5, y: 23.5 },
    'martim-moniz': { name: 'Martim Moniz', x: 21, y: 22 },
    intendente: { name: 'Intendente', x: 19.5, y: 20.5 },
    anjos: { name: 'Anjos', x: 21, y: 19 },
    arroios: { name: 'Arroios', x: 19.5, y: 17.5 },
    alameda: { name: 'Alameda', x: 20.5, y: 16 },
    areeiro: { name: 'Areeiro', x: 20.5, y: 14 },
    roma: { name: 'Roma', x: 19, y: 12.5 },
    alvalade: { name: 'Alvalade', x: 17.5, y: 11 },
    telheiras: { name: 'Telheiras', x: 14, y: 9.5 },
    olaias: { name: 'Olaias', x: 22, y: 14.5 },
    'bela-vista': { name: 'Bela Vista', x: 23.5, y: 13 },
    chelas: { name: 'Chelas', x: 25, y: 11.5 },
    olivais: { name: 'Olivais', x: 25, y: 9.5 },
    'cabo-ruivo': { name: 'Cabo Ruivo', x: 26.5, y: 8.5 },
    oriente: { name: 'Oriente', x: 28, y: 7 },
    moscavide: { name: 'Moscavide', x: 26.5, y: 5.5 },
    encarnacao: { name: 'Encarnação', x: 24.5, y: 5.5 },
    aeroporto: { name: 'Aeroporto', x: 23, y: 7 },
  },
};
