// London's Underground, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'london',
  name: 'London',
  system: 'Underground',
  country: 'United Kingdom',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'bakerloo',
      short: '',
      name: 'Bakerloo line',
      colour: '#ae6017',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['harrow-wealdstone', 'kenton', 'south-kenton', 'north-wembley', 'wembley-central', 'stonebridge-park', 'harlesden', 'willesden-junction', 'kensal-green', 'queen-s-park', 'kilburn-park', 'maida-vale', 'warwick-avenue', 'paddington', 'edgware-road', 'marylebone', 'baker-street', 'regent-s-park', 'oxford-circus', 'piccadilly-circus', 'charing-cross', 'embankment', 'waterloo', 'lambeth-north', 'elephant-castle'],
      ],
    },
    {
      id: 'central',
      short: '',
      name: 'Central line',
      colour: '#e42313',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['west-ruislip', 'ruislip-gardens', 'south-ruislip', 'northolt', 'greenford', 'perivale', 'hanger-lane', 'north-acton', 'east-acton', 'white-city', 'shepherd-s-bush', 'holland-park', 'notting-hill-gate', 'queensway', 'lancaster-gate', 'marble-arch', 'bond-street', 'oxford-circus', 'tottenham-court-road', 'holborn', 'chancery-lane', 'st-paul-s', 'bank', 'liverpool-street', 'bethnal-green', 'mile-end', 'stratford', 'leyton', 'leytonstone', 'snaresbrook', 'south-woodford', 'woodford', 'buckhurst-hill', 'loughton', 'debden', 'theydon-bois', 'epping'],
        ['epping', 'theydon-bois', 'debden', 'loughton', 'buckhurst-hill', 'woodford', 'south-woodford', 'snaresbrook', 'leytonstone', 'leyton', 'stratford', 'mile-end', 'bethnal-green', 'liverpool-street', 'bank', 'st-paul-s', 'chancery-lane', 'holborn', 'tottenham-court-road', 'oxford-circus', 'marble-arch', 'lancaster-gate', 'queensway', 'notting-hill-gate', 'holland-park', 'shepherd-s-bush', 'white-city', 'east-acton', 'north-acton', 'hanger-lane', 'perivale', 'greenford', 'northolt', 'south-ruislip', 'ruislip-gardens', 'west-ruislip'],
        ['ealing-broadway', 'west-acton', 'north-acton', 'east-acton', 'white-city', 'shepherd-s-bush', 'holland-park', 'notting-hill-gate', 'queensway', 'lancaster-gate', 'marble-arch', 'bond-street', 'oxford-circus', 'tottenham-court-road', 'holborn', 'chancery-lane', 'st-paul-s', 'bank', 'liverpool-street', 'bethnal-green', 'mile-end', 'stratford', 'leyton', 'leytonstone', 'wanstead', 'redbridge', 'gants-hill', 'newbury-park', 'barkingside', 'fairlop', 'hainault'],
        ['hainault', 'fairlop', 'barkingside', 'newbury-park', 'gants-hill', 'redbridge', 'wanstead', 'leytonstone', 'leyton', 'stratford', 'mile-end', 'bethnal-green', 'liverpool-street', 'bank', 'st-paul-s', 'chancery-lane', 'holborn', 'tottenham-court-road', 'oxford-circus', 'marble-arch', 'lancaster-gate', 'queensway', 'notting-hill-gate', 'holland-park', 'shepherd-s-bush', 'white-city', 'east-acton', 'north-acton', 'west-acton', 'ealing-broadway'],
        ['ealing-broadway', 'west-acton', 'north-acton', 'east-acton', 'white-city', 'shepherd-s-bush', 'holland-park', 'notting-hill-gate', 'queensway', 'lancaster-gate', 'marble-arch', 'bond-street', 'oxford-circus', 'tottenham-court-road', 'holborn', 'chancery-lane', 'st-paul-s', 'bank', 'liverpool-street', 'bethnal-green', 'mile-end', 'stratford', 'leyton', 'leytonstone', 'snaresbrook', 'south-woodford', 'woodford', 'buckhurst-hill', 'loughton'],
        ['loughton', 'buckhurst-hill', 'woodford', 'south-woodford', 'snaresbrook', 'leytonstone', 'leyton', 'stratford', 'mile-end', 'bethnal-green', 'liverpool-street', 'bank', 'st-paul-s', 'chancery-lane', 'holborn', 'tottenham-court-road', 'oxford-circus', 'marble-arch', 'lancaster-gate', 'queensway', 'notting-hill-gate', 'holland-park', 'shepherd-s-bush', 'white-city', 'east-acton', 'north-acton', 'west-acton', 'ealing-broadway'],
        ['woodford', 'roding-valley', 'chigwell', 'grange-hill', 'hainault'],
      ],
    },
    {
      id: 'circle',
      short: '',
      name: 'Circle line',
      colour: '#ffd329',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['hammersmith', 'goldhawk-road', 'shepherd-s-bush-market', 'wood-lane', 'latimer-road', 'ladbroke-grove', 'westbourne-park', 'royal-oak', 'paddington', 'edgware-road', 'baker-street', 'great-portland-street', 'euston-square', 'king-s-cross-st-pancras', 'farringdon', 'barbican', 'moorgate', 'liverpool-street', 'aldgate', 'tower-hill', 'monument', 'cannon-street', 'mansion-house', 'blackfriars', 'temple', 'embankment', 'westminster', 'st-james-s-park', 'victoria', 'sloane-square', 'south-kensington', 'gloucester-road', 'high-street-kensington', 'notting-hill-gate', 'bayswater'],
        ['edgware-road', 'paddington', 'bayswater', 'notting-hill-gate', 'high-street-kensington', 'gloucester-road', 'south-kensington', 'sloane-square', 'victoria', 'st-james-s-park', 'westminster', 'embankment', 'temple', 'blackfriars', 'mansion-house', 'cannon-street', 'monument', 'tower-hill', 'aldgate', 'liverpool-street', 'moorgate', 'barbican', 'farringdon', 'king-s-cross-st-pancras', 'euston-square', 'great-portland-street', 'baker-street'],
      ],
    },
    {
      id: 'district',
      short: '',
      name: 'District line',
      colour: '#00a166',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['ealing-broadway', 'ealing-common', 'acton-town', 'chiswick-park', 'turnham-green', 'stamford-brook', 'ravenscourt-park', 'hammersmith', 'barons-court', 'west-kensington', 'earl-s-court', 'gloucester-road', 'south-kensington', 'sloane-square', 'victoria', 'st-james-s-park', 'westminster', 'embankment', 'temple', 'blackfriars', 'mansion-house', 'cannon-street', 'monument', 'tower-hill', 'aldgate-east', 'whitechapel', 'stepney-green', 'mile-end', 'bow-road', 'bromley-by-bow', 'west-ham', 'plaistow', 'upton-park', 'east-ham', 'barking', 'upney', 'becontree', 'dagenham-heathway', 'dagenham-east', 'elm-park', 'hornchurch', 'upminster-bridge', 'upminster'],
        ['upminster', 'upminster-bridge', 'hornchurch', 'elm-park', 'dagenham-east', 'dagenham-heathway', 'becontree', 'upney', 'barking', 'east-ham', 'upton-park', 'plaistow', 'west-ham', 'bromley-by-bow', 'bow-road', 'mile-end', 'stepney-green', 'whitechapel', 'aldgate-east', 'tower-hill', 'monument', 'cannon-street', 'mansion-house', 'blackfriars', 'temple', 'embankment', 'westminster', 'st-james-s-park', 'victoria', 'sloane-square', 'south-kensington', 'gloucester-road', 'earl-s-court', 'west-kensington', 'barons-court', 'hammersmith', 'ravenscourt-park', 'stamford-brook', 'turnham-green', 'gunnersbury', 'kew-gardens', 'richmond'],
        ['barking', 'east-ham', 'upton-park', 'plaistow', 'west-ham', 'bromley-by-bow', 'bow-road', 'mile-end', 'stepney-green', 'whitechapel', 'aldgate-east', 'tower-hill', 'monument', 'cannon-street', 'mansion-house', 'blackfriars', 'temple', 'embankment', 'westminster', 'st-james-s-park', 'victoria', 'sloane-square', 'south-kensington', 'gloucester-road', 'earl-s-court', 'west-brompton', 'fulham-broadway', 'parsons-green', 'putney-bridge', 'east-putney', 'southfields', 'wimbledon-park', 'wimbledon'],
        ['wimbledon', 'wimbledon-park', 'southfields', 'east-putney', 'putney-bridge', 'parsons-green', 'fulham-broadway', 'west-brompton', 'earl-s-court', 'gloucester-road', 'south-kensington', 'sloane-square', 'victoria', 'st-james-s-park', 'westminster', 'embankment', 'temple', 'mansion-house', 'cannon-street', 'monument', 'tower-hill', 'aldgate-east', 'whitechapel', 'stepney-green', 'mile-end', 'bow-road', 'bromley-by-bow', 'west-ham', 'plaistow', 'upton-park', 'east-ham', 'barking'],
        ['edgware-road', 'paddington', 'bayswater', 'notting-hill-gate', 'high-street-kensington', 'earl-s-court', 'west-brompton', 'fulham-broadway', 'parsons-green', 'putney-bridge', 'east-putney', 'southfields', 'wimbledon-park', 'wimbledon'],
        ['high-street-kensington', 'earl-s-court', 'kensington-olympia'],
      ],
    },
    {
      id: 'hammersmith-city',
      short: '',
      name: 'Hammersmith & City line',
      colour: '#f4a9be',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['hammersmith', 'goldhawk-road', 'shepherd-s-bush-market', 'wood-lane', 'latimer-road', 'ladbroke-grove', 'westbourne-park', 'royal-oak', 'paddington', 'edgware-road', 'baker-street', 'great-portland-street', 'euston-square', 'king-s-cross-st-pancras', 'farringdon', 'barbican', 'moorgate', 'liverpool-street', 'aldgate-east', 'whitechapel', 'stepney-green', 'mile-end', 'bow-road', 'bromley-by-bow', 'west-ham', 'plaistow', 'upton-park', 'east-ham', 'barking'],
      ],
    },
    {
      id: 'jubilee',
      short: '',
      name: 'Jubilee line',
      colour: '#949699',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['stratford', 'west-ham', 'canning-town', 'north-greenwich', 'canary-wharf', 'canada-water', 'bermondsey', 'london-bridge', 'southwark', 'waterloo', 'westminster', 'green-park', 'bond-street', 'baker-street', 'st-john-s-wood', 'swiss-cottage', 'finchley-road', 'west-hampstead', 'kilburn', 'willesden-green', 'dollis-hill', 'neasden', 'wembley-park', 'kingsbury', 'queensbury', 'canons-park', 'stanmore'],
      ],
    },
    {
      id: 'metropolitan',
      short: '',
      name: 'Metropolitan line',
      colour: '#91005a',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['aldgate', 'liverpool-street', 'moorgate', 'barbican', 'farringdon', 'king-s-cross-st-pancras', 'euston-square', 'great-portland-street', 'baker-street', 'finchley-road', 'wembley-park', 'preston-road', 'northwick-park', 'harrow-on-the-hill', 'north-harrow', 'pinner', 'northwood-hills', 'northwood', 'moor-park', 'rickmansworth', 'chorleywood', 'chalfont-latimer', 'amersham'],
        ['aldgate', 'liverpool-street', 'moorgate', 'barbican', 'farringdon', 'king-s-cross-st-pancras', 'euston-square', 'great-portland-street', 'baker-street', 'finchley-road', 'wembley-park', 'preston-road', 'northwick-park', 'harrow-on-the-hill', 'north-harrow', 'pinner', 'northwood-hills', 'northwood', 'moor-park', 'rickmansworth', 'chorleywood', 'chalfont-latimer', 'chesham'],
        ['aldgate', 'liverpool-street', 'moorgate', 'barbican', 'farringdon', 'king-s-cross-st-pancras', 'euston-square', 'great-portland-street', 'baker-street', 'finchley-road', 'wembley-park', 'preston-road', 'northwick-park', 'harrow-on-the-hill', 'west-harrow', 'rayners-lane', 'eastcote', 'ruislip-manor', 'ruislip', 'ickenham', 'hillingdon', 'uxbridge'],
        ['watford', 'croxley', 'moor-park', 'northwood', 'northwood-hills', 'pinner', 'north-harrow', 'harrow-on-the-hill', 'northwick-park', 'preston-road', 'wembley-park', 'finchley-road', 'baker-street'],
      ],
    },
    {
      id: 'northern',
      short: '',
      name: 'Northern line',
      colour: '#000000',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['morden', 'south-wimbledon', 'colliers-wood', 'tooting-broadway', 'tooting-bec', 'balham', 'clapham-south', 'clapham-common', 'clapham-north', 'stockwell', 'oval', 'kennington', 'elephant-castle', 'borough', 'london-bridge', 'bank', 'moorgate', 'old-street', 'angel', 'king-s-cross-st-pancras', 'euston', 'camden-town', 'kentish-town', 'tufnell-park', 'archway', 'highgate', 'east-finchley', 'finchley-central', 'west-finchley', 'woodside-park', 'totteridge-whetstone', 'high-barnet'],
        ['high-barnet', 'totteridge-whetstone', 'woodside-park', 'west-finchley', 'finchley-central', 'east-finchley', 'highgate', 'archway', 'tufnell-park', 'kentish-town', 'camden-town', 'mornington-crescent', 'euston', 'warren-street', 'goodge-street', 'tottenham-court-road', 'leicester-square', 'charing-cross', 'embankment', 'waterloo', 'kennington', 'oval', 'stockwell', 'clapham-north', 'clapham-common', 'clapham-south', 'balham', 'tooting-bec', 'tooting-broadway', 'colliers-wood', 'south-wimbledon', 'morden'],
        ['morden', 'south-wimbledon', 'colliers-wood', 'tooting-broadway', 'tooting-bec', 'balham', 'clapham-south', 'clapham-common', 'clapham-north', 'stockwell', 'oval', 'kennington', 'elephant-castle', 'borough', 'london-bridge', 'bank', 'moorgate', 'old-street', 'angel', 'king-s-cross-st-pancras', 'euston', 'camden-town', 'chalk-farm', 'belsize-park', 'hampstead', 'golders-green', 'brent-cross', 'hendon-central', 'colindale', 'burnt-oak', 'edgware'],
        ['morden', 'south-wimbledon', 'colliers-wood', 'tooting-broadway', 'tooting-bec', 'balham', 'clapham-south', 'clapham-common', 'clapham-north', 'stockwell', 'oval', 'kennington', 'waterloo', 'embankment', 'charing-cross', 'leicester-square', 'tottenham-court-road', 'goodge-street', 'warren-street', 'euston', 'mornington-crescent', 'camden-town', 'chalk-farm', 'belsize-park', 'hampstead', 'golders-green', 'brent-cross', 'hendon-central', 'colindale', 'burnt-oak', 'edgware'],
        ['mill-hill-east', 'finchley-central', 'east-finchley', 'highgate', 'archway', 'tufnell-park', 'kentish-town', 'camden-town', 'euston', 'king-s-cross-st-pancras', 'angel', 'old-street', 'moorgate', 'bank', 'london-bridge', 'borough', 'elephant-castle', 'kennington', 'oval', 'stockwell', 'clapham-north', 'clapham-common', 'clapham-south', 'balham', 'tooting-bec', 'tooting-broadway', 'colliers-wood', 'south-wimbledon', 'morden'],
        ['mill-hill-east', 'finchley-central', 'east-finchley', 'highgate', 'archway', 'tufnell-park', 'kentish-town', 'camden-town', 'mornington-crescent', 'euston', 'warren-street', 'goodge-street', 'tottenham-court-road', 'leicester-square', 'charing-cross', 'embankment', 'waterloo', 'kennington', 'oval', 'stockwell', 'clapham-north', 'clapham-common', 'clapham-south', 'balham', 'tooting-bec', 'tooting-broadway', 'colliers-wood', 'south-wimbledon', 'morden'],
        ['battersea-power-station', 'nine-elms', 'kennington', 'waterloo', 'embankment', 'charing-cross', 'leicester-square', 'tottenham-court-road', 'goodge-street', 'warren-street', 'euston', 'mornington-crescent', 'camden-town', 'kentish-town', 'tufnell-park', 'archway', 'highgate', 'east-finchley', 'finchley-central', 'west-finchley', 'woodside-park', 'totteridge-whetstone', 'high-barnet'],
        ['edgware', 'burnt-oak', 'colindale', 'hendon-central', 'brent-cross', 'golders-green', 'hampstead', 'belsize-park', 'chalk-farm', 'camden-town', 'mornington-crescent', 'euston', 'warren-street', 'goodge-street', 'tottenham-court-road', 'leicester-square', 'charing-cross', 'embankment', 'waterloo', 'kennington', 'nine-elms', 'battersea-power-station'],
        ['mill-hill-east', 'finchley-central', 'east-finchley', 'highgate', 'archway', 'tufnell-park', 'kentish-town', 'camden-town', 'mornington-crescent', 'euston', 'warren-street', 'goodge-street', 'tottenham-court-road', 'leicester-square', 'charing-cross', 'embankment', 'waterloo', 'kennington', 'nine-elms', 'battersea-power-station'],
      ],
    },
    {
      id: 'piccadilly',
      short: '',
      name: 'Piccadilly line',
      colour: '#094fa3',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['uxbridge', 'hillingdon', 'ickenham', 'ruislip', 'ruislip-manor', 'eastcote', 'rayners-lane', 'sudbury-hill', 'sudbury-town', 'alperton', 'park-royal', 'ealing-common', 'acton-town', 'turnham-green', 'hammersmith', 'barons-court', 'earl-s-court', 'gloucester-road', 'south-kensington', 'knightsbridge', 'hyde-park-corner', 'green-park', 'piccadilly-circus', 'leicester-square', 'covent-garden', 'holborn', 'russell-square', 'king-s-cross-st-pancras', 'caledonian-road', 'holloway-road', 'arsenal', 'finsbury-park', 'manor-house', 'turnpike-lane', 'wood-green', 'bounds-green', 'arnos-grove', 'southgate', 'oakwood', 'cockfosters'],
        ['heathrow-terminal-4', 'heathrow-terminals-2-3', 'hatton-cross', 'hounslow-west', 'hounslow-central', 'hounslow-east', 'osterley', 'boston-manor', 'northfields', 'south-ealing', 'acton-town', 'turnham-green', 'hammersmith', 'barons-court', 'earl-s-court', 'gloucester-road', 'south-kensington', 'knightsbridge', 'hyde-park-corner', 'green-park', 'piccadilly-circus', 'leicester-square', 'covent-garden', 'holborn', 'russell-square', 'king-s-cross-st-pancras', 'caledonian-road', 'holloway-road', 'arsenal', 'finsbury-park', 'manor-house', 'turnpike-lane', 'wood-green', 'bounds-green', 'arnos-grove', 'southgate', 'oakwood', 'cockfosters'],
        ['heathrow-terminal-5', 'heathrow-terminals-2-3', 'hatton-cross', 'hounslow-west', 'hounslow-central', 'hounslow-east', 'osterley', 'boston-manor', 'northfields', 'south-ealing', 'acton-town', 'turnham-green', 'hammersmith', 'barons-court', 'earl-s-court', 'gloucester-road', 'south-kensington', 'knightsbridge', 'hyde-park-corner', 'green-park', 'piccadilly-circus', 'leicester-square', 'covent-garden', 'holborn', 'russell-square', 'king-s-cross-st-pancras', 'caledonian-road', 'holloway-road', 'arsenal', 'finsbury-park', 'manor-house', 'turnpike-lane', 'wood-green', 'bounds-green', 'arnos-grove', 'southgate', 'oakwood', 'cockfosters'],
        ['cockfosters', 'oakwood', 'southgate', 'bounds-green', 'wood-green', 'turnpike-lane', 'manor-house', 'finsbury-park', 'arsenal', 'holloway-road', 'caledonian-road', 'king-s-cross-st-pancras', 'russell-square', 'holborn', 'covent-garden', 'leicester-square', 'piccadilly-circus', 'green-park', 'hyde-park-corner', 'knightsbridge', 'south-kensington', 'gloucester-road', 'earl-s-court', 'barons-court', 'hammersmith', 'turnham-green', 'acton-town', 'south-ealing', 'northfields', 'boston-manor', 'osterley', 'hounslow-east', 'hounslow-central', 'hounslow-west', 'hatton-cross', 'heathrow-terminals-2-3', 'heathrow-terminal-5'],
        ['cockfosters', 'oakwood', 'southgate', 'bounds-green', 'wood-green', 'turnpike-lane', 'manor-house', 'finsbury-park', 'arsenal', 'holloway-road', 'caledonian-road', 'king-s-cross-st-pancras', 'russell-square', 'holborn', 'covent-garden', 'leicester-square', 'piccadilly-circus', 'green-park', 'hyde-park-corner', 'knightsbridge', 'south-kensington', 'gloucester-road', 'earl-s-court', 'barons-court', 'hammersmith', 'turnham-green', 'acton-town', 'south-ealing', 'northfields', 'boston-manor', 'osterley', 'hounslow-east', 'hounslow-central', 'hounslow-west', 'hatton-cross', 'heathrow-terminal-4'],
      ],
    },
    {
      id: 'victoria',
      short: '',
      name: 'Victoria line',
      colour: '#0a9cda',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['brixton', 'stockwell', 'vauxhall', 'pimlico', 'victoria', 'green-park', 'oxford-circus', 'warren-street', 'euston', 'king-s-cross-st-pancras', 'highbury-islington', 'finsbury-park', 'seven-sisters', 'tottenham-hale', 'blackhorse-road-station', 'walthamstow-central'],
        ['walthamstow-central', 'blackhorse-road', 'tottenham-hale', 'seven-sisters', 'finsbury-park', 'highbury-islington', 'king-s-cross-st-pancras', 'euston', 'warren-street', 'oxford-circus', 'green-park', 'victoria', 'pimlico', 'vauxhall', 'stockwell', 'brixton'],
      ],
    },
    {
      id: 'waterloo-city',
      short: '',
      name: 'Waterloo & City line',
      colour: '#93ceba',
      text: '#1a1a1a',
      minutes: 4,
      branches: [
        ['waterloo', 'bank'],
      ],
    },
  ],
  times: {
    'harrow-wealdstone kenton': 4,
    'kenton south-kenton': 3,
    'north-wembley wembley-central': 3,
    'wembley-central stonebridge-park': 4,
    'stonebridge-park harlesden': 3,
    'willesden-junction kensal-green': 3,
    'kensal-green queen-s-park': 3,
    'edgware-road marylebone': 1,
    'marylebone baker-street': 1,
    'charing-cross embankment': 1,
    'waterloo lambeth-north': 1,
    'west-ruislip ruislip-gardens': 4,
    'south-ruislip northolt': 5,
    'northolt greenford': 4,
    'greenford perivale': 4,
    'perivale hanger-lane': 5,
    'hanger-lane north-acton': 5,
    'east-acton white-city': 4,
    'lancaster-gate marble-arch': 3,
    'bond-street oxford-circus': 1,
    'holborn chancery-lane': 1,
    'liverpool-street bethnal-green': 5,
    'bethnal-green mile-end': 3,
    'mile-end stratford': 6,
    'stratford leyton': 4,
    'leyton leytonstone': 3,
    'leytonstone snaresbrook': 3,
    'snaresbrook south-woodford': 3,
    'south-woodford woodford': 4,
    'woodford buckhurst-hill': 5,
    'buckhurst-hill loughton': 4,
    'loughton debden': 4,
    'debden theydon-bois': 7,
    'theydon-bois epping': 5,
    'epping theydon-bois': 5,
    'theydon-bois debden': 7,
    'debden loughton': 4,
    'loughton buckhurst-hill': 4,
    'buckhurst-hill woodford': 5,
    'woodford south-woodford': 4,
    'south-woodford snaresbrook': 3,
    'snaresbrook leytonstone': 3,
    'leytonstone leyton': 3,
    'leyton stratford': 4,
    'stratford mile-end': 6,
    'mile-end bethnal-green': 3,
    'bethnal-green liverpool-street': 5,
    'chancery-lane holborn': 1,
    'oxford-circus marble-arch': 3,
    'marble-arch lancaster-gate': 3,
    'white-city east-acton': 4,
    'north-acton hanger-lane': 5,
    'hanger-lane perivale': 5,
    'perivale greenford': 4,
    'greenford northolt': 4,
    'northolt south-ruislip': 5,
    'ruislip-gardens west-ruislip': 4,
    'ealing-broadway west-acton': 3,
    'west-acton north-acton': 3,
    'leytonstone wanstead': 3,
    'wanstead redbridge': 3,
    'redbridge gants-hill': 3,
    'gants-hill newbury-park': 4,
    'newbury-park barkingside': 3,
    'barkingside fairlop': 3,
    'fairlop barkingside': 3,
    'barkingside newbury-park': 3,
    'newbury-park gants-hill': 4,
    'gants-hill redbridge': 3,
    'redbridge wanstead': 3,
    'wanstead leytonstone': 3,
    'north-acton west-acton': 3,
    'west-acton ealing-broadway': 3,
    'woodford roding-valley': 3,
    'roding-valley chigwell': 5,
    'chigwell grange-hill': 3,
    'goldhawk-road shepherd-s-bush-market': 1,
    'shepherd-s-bush-market wood-lane': 1,
    'wood-lane latimer-road': 1,
    'king-s-cross-st-pancras farringdon': 4,
    'farringdon barbican': 1,
    'moorgate liverpool-street': 1,
    'aldgate tower-hill': 1,
    'monument cannon-street': 1,
    'cannon-street mansion-house': 1,
    'sloane-square south-kensington': 3,
    'south-kensington sloane-square': 3,
    'mansion-house cannon-street': 1,
    'cannon-street monument': 1,
    'tower-hill aldgate': 1,
    'liverpool-street moorgate': 1,
    'barbican farringdon': 1,
    'farringdon king-s-cross-st-pancras': 4,
    'acton-town chiswick-park': 3,
    'bromley-by-bow west-ham': 3,
    'plaistow upton-park': 3,
    'upton-park east-ham': 3,
    'east-ham barking': 4,
    'barking upney': 3,
    'upney becontree': 4,
    'becontree dagenham-heathway': 3,
    'dagenham-heathway dagenham-east': 3,
    'dagenham-east elm-park': 5,
    'elm-park hornchurch': 3,
    'hornchurch upminster-bridge': 3,
    'upminster-bridge upminster': 3,
    'upminster upminster-bridge': 3,
    'upminster-bridge hornchurch': 3,
    'hornchurch elm-park': 3,
    'elm-park dagenham-east': 5,
    'dagenham-east dagenham-heathway': 3,
    'dagenham-heathway becontree': 3,
    'becontree upney': 4,
    'upney barking': 3,
    'barking east-ham': 4,
    'east-ham upton-park': 3,
    'upton-park plaistow': 3,
    'west-ham bromley-by-bow': 3,
    'turnham-green gunnersbury': 3,
    'gunnersbury kew-gardens': 4,
    'kew-gardens richmond': 4,
    'earl-s-court west-brompton': 1,
    'east-putney southfields': 3,
    'southfields wimbledon-park': 3,
    'wimbledon-park wimbledon': 3,
    'wimbledon wimbledon-park': 3,
    'wimbledon-park southfields': 3,
    'southfields east-putney': 3,
    'west-brompton earl-s-court': 1,
    'temple mansion-house': 3,
    'earl-s-court kensington-olympia': 3,
    'canary-wharf canada-water': 5,
    'canada-water bermondsey': 2,
    'bermondsey london-bridge': 4,
    'southwark waterloo': 1,
    'waterloo westminster': 2,
    'green-park bond-street': 2,
    'bond-street baker-street': 2,
    'baker-street st-john-s-wood': 4,
    'st-john-s-wood swiss-cottage': 2,
    'swiss-cottage finchley-road': 1,
    'finchley-road west-hampstead': 2,
    'west-hampstead kilburn': 2,
    'dollis-hill neasden': 2,
    'neasden wembley-park': 5,
    'wembley-park kingsbury': 5,
    'queensbury canons-park': 4,
    'baker-street finchley-road': 6,
    'finchley-road wembley-park': 14,
    'wembley-park preston-road': 3,
    'preston-road northwick-park': 4,
    'northwick-park harrow-on-the-hill': 3,
    'harrow-on-the-hill north-harrow': 4,
    'north-harrow pinner': 3,
    'pinner northwood-hills': 4,
    'northwood-hills northwood': 3,
    'northwood moor-park': 5,
    'moor-park rickmansworth': 6,
    'rickmansworth chorleywood': 7,
    'chorleywood chalfont-latimer': 7,
    'chalfont-latimer amersham': 7,
    'chalfont-latimer chesham': 11,
    'harrow-on-the-hill west-harrow': 3,
    'west-harrow rayners-lane': 3,
    'rayners-lane eastcote': 4,
    'ruislip ickenham': 4,
    'hillingdon uxbridge': 4,
    'watford croxley': 4,
    'croxley moor-park': 4,
    'moor-park northwood': 5,
    'northwood northwood-hills': 3,
    'northwood-hills pinner': 4,
    'pinner north-harrow': 3,
    'north-harrow harrow-on-the-hill': 4,
    'harrow-on-the-hill northwick-park': 3,
    'northwick-park preston-road': 4,
    'preston-road wembley-park': 3,
    'wembley-park finchley-road': 14,
    'finchley-road baker-street': 6,
    'morden south-wimbledon': 3,
    'colliers-wood tooting-broadway': 3,
    'clapham-south clapham-common': 3,
    'stockwell oval': 3,
    'old-street angel': 3,
    'angel king-s-cross-st-pancras': 3,
    'euston camden-town': 3,
    'camden-town kentish-town': 3,
    'archway highgate': 4,
    'highgate east-finchley': 4,
    'east-finchley finchley-central': 5,
    'woodside-park totteridge-whetstone': 3,
    'totteridge-whetstone high-barnet': 5,
    'high-barnet totteridge-whetstone': 5,
    'totteridge-whetstone woodside-park': 3,
    'finchley-central east-finchley': 5,
    'east-finchley highgate': 4,
    'highgate archway': 4,
    'kentish-town camden-town': 3,
    'euston warren-street': 1,
    'warren-street goodge-street': 1,
    'goodge-street tottenham-court-road': 1,
    'tottenham-court-road leicester-square': 1,
    'leicester-square charing-cross': 1,
    'waterloo kennington': 4,
    'oval stockwell': 3,
    'clapham-common clapham-south': 3,
    'tooting-broadway colliers-wood': 3,
    'south-wimbledon morden': 3,
    'belsize-park hampstead': 3,
    'hampstead golders-green': 4,
    'golders-green brent-cross': 3,
    'brent-cross hendon-central': 3,
    'hendon-central colindale': 4,
    'colindale burnt-oak': 3,
    'burnt-oak edgware': 3,
    'kennington waterloo': 4,
    'embankment charing-cross': 1,
    'charing-cross leicester-square': 1,
    'leicester-square tottenham-court-road': 1,
    'tottenham-court-road goodge-street': 1,
    'goodge-street warren-street': 1,
    'warren-street euston': 1,
    'mill-hill-east finchley-central': 3,
    'camden-town euston': 3,
    'king-s-cross-st-pancras angel': 3,
    'angel old-street': 3,
    'nine-elms kennington': 4,
    'edgware burnt-oak': 3,
    'burnt-oak colindale': 3,
    'colindale hendon-central': 4,
    'hendon-central brent-cross': 3,
    'brent-cross golders-green': 3,
    'golders-green hampstead': 4,
    'hampstead belsize-park': 3,
    'kennington nine-elms': 4,
    'uxbridge hillingdon': 4,
    'ickenham ruislip': 4,
    'eastcote rayners-lane': 4,
    'rayners-lane sudbury-hill': 6,
    'sudbury-hill sudbury-town': 3,
    'sudbury-town alperton': 3,
    'alperton park-royal': 4,
    'park-royal ealing-common': 4,
    'acton-town turnham-green': 4,
    'turnham-green hammersmith': 4,
    'barons-court earl-s-court': 3,
    'south-kensington knightsbridge': 3,
    'knightsbridge hyde-park-corner': 1,
    'piccadilly-circus leicester-square': 1,
    'leicester-square covent-garden': 1,
    'covent-garden holborn': 1,
    'king-s-cross-st-pancras caledonian-road': 4,
    'manor-house turnpike-lane': 5,
    'wood-green bounds-green': 3,
    'bounds-green arnos-grove': 3,
    'arnos-grove southgate': 4,
    'southgate oakwood': 4,
    'oakwood cockfosters': 3,
    'heathrow-terminal-4 heathrow-terminals-2-3': 3,
    'heathrow-terminals-2-3 hatton-cross': 4,
    'hatton-cross hounslow-west': 6,
    'hounslow-west hounslow-central': 3,
    'osterley boston-manor': 5,
    'northfields south-ealing': 1,
    'south-ealing acton-town': 4,
    'heathrow-terminal-5 heathrow-terminals-2-3': 5,
    'cockfosters oakwood': 3,
    'oakwood southgate': 4,
    'southgate bounds-green': 6,
    'bounds-green wood-green': 3,
    'turnpike-lane manor-house': 5,
    'caledonian-road king-s-cross-st-pancras': 4,
    'holborn covent-garden': 1,
    'covent-garden leicester-square': 1,
    'leicester-square piccadilly-circus': 1,
    'hyde-park-corner knightsbridge': 1,
    'knightsbridge south-kensington': 3,
    'earl-s-court barons-court': 3,
    'hammersmith turnham-green': 4,
    'turnham-green acton-town': 4,
    'acton-town south-ealing': 4,
    'south-ealing northfields': 1,
    'boston-manor osterley': 5,
    'hounslow-central hounslow-west': 3,
    'hounslow-west hatton-cross': 6,
    'hatton-cross heathrow-terminals-2-3': 4,
    'heathrow-terminals-2-3 heathrow-terminal-5': 5,
    'hatton-cross heathrow-terminal-4': 4,
    'brixton stockwell': 3,
    'stockwell vauxhall': 3,
    'victoria green-park': 3,
    'king-s-cross-st-pancras highbury-islington': 5,
    'highbury-islington finsbury-park': 4,
    'finsbury-park seven-sisters': 6,
    'tottenham-hale blackhorse-road-station': 3,
    'blackhorse-road-station walthamstow-central': 3,
    'walthamstow-central blackhorse-road': 4,
    'blackhorse-road tottenham-hale': 3,
    'seven-sisters finsbury-park': 6,
    'finsbury-park highbury-islington': 4,
    'highbury-islington king-s-cross-st-pancras': 5,
    'green-park victoria': 3,
    'vauxhall stockwell': 3,
    'stockwell brixton': 3,
  },
  stations: {
    waterloo: { name: 'Waterloo', x: 44, y: 27.5 },
    bank: { name: 'Bank', x: 46, y: 26 },
    edgware: { name: 'Edgware', x: 26, y: 8 },
    'burnt-oak': { name: 'Burnt Oak', x: 27.5, y: 9.5 },
    colindale: { name: 'Colindale', x: 29, y: 10.5 },
    'hendon-central': { name: 'Hendon Central', x: 30.5, y: 12 },
    'brent-cross': { name: 'Brent Cross', x: 31.5, y: 13.5 },
    'golders-green': { name: 'Golders Green', x: 33, y: 15 },
    hampstead: { name: 'Hampstead', x: 34.5, y: 16.5 },
    'belsize-park': { name: 'Belsize Park', x: 36, y: 17.5 },
    'chalk-farm': { name: 'Chalk Farm', x: 37.5, y: 19 },
    'camden-town': { name: 'Camden Town', x: 39.5, y: 19 },
    'mornington-crescent': { name: 'Mornington Crescent', x: 38.5, y: 20 },
    euston: { name: 'Euston', x: 40.5, y: 20 },
    'warren-street': { name: 'Warren Street', x: 39, y: 21.5 },
    'goodge-street': { name: 'Goodge Street', x: 40.5, y: 23 },
    'tottenham-court-road': { name: 'Tottenham Court Road', x: 40.5, y: 25 },
    'leicester-square': { name: 'Leicester Square', x: 39.5, y: 24 },
    'charing-cross': { name: 'Charing Cross', x: 39.5, y: 26.5 },
    embankment: { name: 'Embankment', x: 42, y: 26 },
    kennington: { name: 'Kennington', x: 44, y: 30 },
    'nine-elms': { name: 'Nine Elms', x: 42.5, y: 31.5 },
    'battersea-power-station': { name: 'Battersea Power Station', x: 40.5, y: 31.5 },
    epping: { name: 'Epping', x: 68.5, y: 1 },
    'theydon-bois': { name: 'Theydon Bois', x: 67.5, y: 2.5 },
    debden: { name: 'Debden', x: 66, y: 4 },
    loughton: { name: 'Loughton', x: 64.5, y: 5.5 },
    'buckhurst-hill': { name: 'Buckhurst Hill', x: 63, y: 7 },
    woodford: { name: 'Woodford', x: 61, y: 9 },
    'south-woodford': { name: 'South Woodford', x: 61, y: 11.5 },
    snaresbrook: { name: 'Snaresbrook', x: 61, y: 13.5 },
    leytonstone: { name: 'Leytonstone', x: 59, y: 16 },
    leyton: { name: 'Leyton', x: 57.5, y: 18 },
    stratford: { name: 'Stratford', x: 55.5, y: 20 },
    'mile-end': { name: 'Mile End', x: 53.5, y: 22 },
    'bethnal-green': { name: 'Bethnal Green', x: 51, y: 22 },
    'liverpool-street': { name: 'Liverpool Street', x: 49, y: 23 },
    'st-paul-s': { name: 'St. Paul\'s', x: 44.5, y: 24.5 },
    'chancery-lane': { name: 'Chancery Lane', x: 43.5, y: 23 },
    holborn: { name: 'Holborn', x: 42, y: 24 },
    'oxford-circus': { name: 'Oxford Circus', x: 39, y: 23.5 },
    'marble-arch': { name: 'Marble Arch', x: 37, y: 25 },
    'lancaster-gate': { name: 'Lancaster Gate', x: 35.5, y: 26.5 },
    queensway: { name: 'Queensway', x: 33.5, y: 26.5 },
    'notting-hill-gate': { name: 'Notting Hill Gate', x: 31.5, y: 27 },
    'holland-park': { name: 'Holland Park', x: 30, y: 28 },
    'shepherd-s-bush': { name: 'Shepherd\'s Bush', x: 28.5, y: 26.5 },
    'white-city': { name: 'White City', x: 27, y: 25 },
    'east-acton': { name: 'East Acton', x: 25.5, y: 24 },
    'north-acton': { name: 'North Acton', x: 23.5, y: 23 },
    'hanger-lane': { name: 'Hanger Lane', x: 22, y: 21.5 },
    perivale: { name: 'Perivale', x: 20, y: 21 },
    greenford: { name: 'Greenford', x: 17, y: 21 },
    northolt: { name: 'Northolt', x: 15, y: 21 },
    'south-ruislip': { name: 'South Ruislip', x: 13.5, y: 19.5 },
    'ruislip-gardens': { name: 'Ruislip Gardens', x: 12, y: 18.5 },
    'west-ruislip': { name: 'West Ruislip', x: 10, y: 18.5 },
    hammersmith: { name: 'Hammersmith', x: 27, y: 30 },
    'goldhawk-road': { name: 'Goldhawk Road', x: 28.5, y: 28.5 },
    'shepherd-s-bush-market': { name: 'Shepherd\'s Bush Market', x: 27, y: 26.5 },
    'wood-lane': { name: 'Wood Lane', x: 28.5, y: 25 },
    'latimer-road': { name: 'Latimer Road', x: 30, y: 26.5 },
    'ladbroke-grove': { name: 'Ladbroke Grove', x: 30, y: 24.5 },
    'westbourne-park': { name: 'Westbourne Park', x: 31.5, y: 23 },
    'royal-oak': { name: 'Royal Oak', x: 33, y: 24 },
    paddington: { name: 'Paddington', x: 34.5, y: 25.5 },
    'edgware-road': { name: 'Edgware Road', x: 35.5, y: 24 },
    'baker-street': { name: 'Baker Street', x: 35, y: 21.5 },
    'great-portland-street': { name: 'Great Portland Street', x: 38, y: 22 },
    'euston-square': { name: 'Euston Square', x: 40.5, y: 21.5 },
    'king-s-cross-st-pancras': { name: 'King\'s Cross St Pancras', x: 42.5, y: 20 },
    farringdon: { name: 'Farringdon', x: 43.5, y: 21.5 },
    barbican: { name: 'Barbican', x: 45, y: 23 },
    moorgate: { name: 'Moorgate', x: 46.5, y: 23 },
    aldgate: { name: 'Aldgate', x: 47.5, y: 24.5 },
    'tower-hill': { name: 'Tower Hill', x: 49, y: 26.5 },
    monument: { name: 'Monument', x: 47.5, y: 26 },
    'cannon-street': { name: 'Cannon Street', x: 46, y: 24.5 },
    'mansion-house': { name: 'Mansion House', x: 44.5, y: 26 },
    blackfriars: { name: 'Blackfriars', x: 43, y: 27 },
    temple: { name: 'Temple', x: 43, y: 25 },
    westminster: { name: 'Westminster', x: 41, y: 27.5 },
    'st-james-s-park': { name: 'St. James\'s Park', x: 41, y: 29.5 },
    victoria: { name: 'Victoria', x: 39.5, y: 28 },
    'sloane-square': { name: 'Sloane Square', x: 38, y: 30 },
    'south-kensington': { name: 'South Kensington', x: 36, y: 30.5 },
    'gloucester-road': { name: 'Gloucester Road', x: 34.5, y: 29.5 },
    'high-street-kensington': { name: 'High Street Kensington', x: 33.5, y: 28.5 },
    bayswater: { name: 'Bayswater', x: 32.5, y: 25.5 },
    'ealing-broadway': { name: 'Ealing Broadway', x: 20, y: 25 },
    'ealing-common': { name: 'Ealing Common', x: 21.5, y: 26 },
    'acton-town': { name: 'Acton Town', x: 23, y: 28 },
    'chiswick-park': { name: 'Chiswick Park', x: 23, y: 29.5 },
    'turnham-green': { name: 'Turnham Green', x: 25, y: 29.5 },
    'stamford-brook': { name: 'Stamford Brook', x: 25.5, y: 28 },
    'ravenscourt-park': { name: 'Ravenscourt Park', x: 27, y: 28 },
    'barons-court': { name: 'Barons Court', x: 29.5, y: 30 },
    'west-kensington': { name: 'West Kensington', x: 31, y: 31 },
    'earl-s-court': { name: 'Earl\'s Court', x: 32, y: 29.5 },
    'aldgate-east': { name: 'Aldgate East', x: 49, y: 25 },
    whitechapel: { name: 'Whitechapel', x: 50.5, y: 23.5 },
    'stepney-green': { name: 'Stepney Green', x: 52, y: 23.5 },
    'bow-road': { name: 'Bow Road', x: 53.5, y: 23.5 },
    'bromley-by-bow': { name: 'Bromley-By-Bow', x: 55.5, y: 23.5 },
    'west-ham': { name: 'West Ham', x: 57, y: 22 },
    plaistow: { name: 'Plaistow', x: 59.5, y: 22 },
    'upton-park': { name: 'Upton Park', x: 62, y: 22 },
    'east-ham': { name: 'East Ham', x: 64, y: 21.5 },
    barking: { name: 'Barking', x: 66.5, y: 21.5 },
    upney: { name: 'Upney', x: 69, y: 21.5 },
    becontree: { name: 'Becontree', x: 71, y: 21.5 },
    'dagenham-heathway': { name: 'Dagenham Heathway', x: 73.5, y: 21.5 },
    'dagenham-east': { name: 'Dagenham East', x: 75.5, y: 21.5 },
    'elm-park': { name: 'Elm Park', x: 77.5, y: 21 },
    hornchurch: { name: 'Hornchurch', x: 80, y: 21 },
    'upminster-bridge': { name: 'Upminster Bridge', x: 82, y: 21 },
    upminster: { name: 'Upminster', x: 84, y: 21 },
    'harrow-wealdstone': { name: 'Harrow & Wealdstone', x: 19, y: 13 },
    kenton: { name: 'Kenton', x: 20.5, y: 14.5 },
    'south-kenton': { name: 'South Kenton', x: 20.5, y: 16.5 },
    'north-wembley': { name: 'North Wembley', x: 21.5, y: 17.5 },
    'wembley-central': { name: 'Wembley Central', x: 23, y: 19 },
    'stonebridge-park': { name: 'Stonebridge Park', x: 24, y: 20.5 },
    harlesden: { name: 'Harlesden', x: 25.5, y: 21.5 },
    'willesden-junction': { name: 'Willesden Junction', x: 26.5, y: 23 },
    'kensal-green': { name: 'Kensal Green', x: 28.5, y: 23 },
    'queen-s-park': { name: 'Queen\'s Park', x: 30, y: 22.5 },
    'kilburn-park': { name: 'Kilburn Park', x: 32, y: 21.5 },
    'maida-vale': { name: 'Maida Vale', x: 33, y: 22.5 },
    'warwick-avenue': { name: 'Warwick Avenue', x: 34.5, y: 23.5 },
    marylebone: { name: 'Marylebone', x: 36, y: 22.5 },
    'regent-s-park': { name: 'Regent\'s Park', x: 37, y: 21.5 },
    'piccadilly-circus': { name: 'Piccadilly Circus', x: 38, y: 25.5 },
    'lambeth-north': { name: 'Lambeth North', x: 43, y: 29 },
    'elephant-castle': { name: 'Elephant & Castle', x: 45, y: 29 },
    'canning-town': { name: 'Canning Town', x: 57, y: 24.5 },
    'north-greenwich': { name: 'North Greenwich', x: 57, y: 26.5 },
    'canary-wharf': { name: 'Canary Wharf', x: 55, y: 27 },
    'canada-water': { name: 'Canada Water', x: 52.5, y: 27 },
    bermondsey: { name: 'Bermondsey', x: 50.5, y: 27.5 },
    'london-bridge': { name: 'London Bridge', x: 48, y: 27.5 },
    southwark: { name: 'Southwark', x: 46, y: 27.5 },
    'green-park': { name: 'Green Park', x: 39, y: 25.5 },
    'bond-street': { name: 'Bond Street', x: 37, y: 23.5 },
    'st-john-s-wood': { name: 'St. John\'s Wood', x: 35.5, y: 20 },
    'swiss-cottage': { name: 'Swiss Cottage', x: 34, y: 18.5 },
    'finchley-road': { name: 'Finchley Road', x: 32, y: 19 },
    'west-hampstead': { name: 'West Hampstead', x: 33.5, y: 20 },
    kilburn: { name: 'Kilburn', x: 31.5, y: 20 },
    'willesden-green': { name: 'Willesden Green', x: 30.5, y: 18.5 },
    'dollis-hill': { name: 'Dollis Hill', x: 28.5, y: 18.5 },
    neasden: { name: 'Neasden', x: 27, y: 18.5 },
    'wembley-park': { name: 'Wembley Park', x: 29, y: 17 },
    kingsbury: { name: 'Kingsbury', x: 27, y: 15.5 },
    queensbury: { name: 'Queensbury', x: 26, y: 14 },
    'canons-park': { name: 'Canons Park', x: 24.5, y: 12.5 },
    stanmore: { name: 'Stanmore', x: 23, y: 11 },
    'preston-road': { name: 'Preston Road', x: 25.5, y: 16.5 },
    'northwick-park': { name: 'Northwick Park', x: 22.5, y: 16 },
    'harrow-on-the-hill': { name: 'Harrow-on-the-Hill', x: 19, y: 15.5 },
    'north-harrow': { name: 'North Harrow', x: 17, y: 13.5 },
    pinner: { name: 'Pinner', x: 14.5, y: 12 },
    'northwood-hills': { name: 'Northwood Hills', x: 12, y: 10 },
    northwood: { name: 'Northwood', x: 10, y: 8 },
    'moor-park': { name: 'Moor Park', x: 8, y: 6.5 },
    rickmansworth: { name: 'Rickmansworth', x: 6, y: 5 },
    chorleywood: { name: 'Chorleywood', x: 4, y: 3 },
    'chalfont-latimer': { name: 'Chalfont & Latimer', x: 2, y: 1.5 },
    amersham: { name: 'Amersham', x: 0, y: 1.5 },
    cockfosters: { name: 'Cockfosters', x: 40.5, y: 3 },
    oakwood: { name: 'Oakwood', x: 42, y: 4.5 },
    southgate: { name: 'Southgate', x: 42, y: 6.5 },
    'bounds-green': { name: 'Bounds Green', x: 42, y: 8.5 },
    'wood-green': { name: 'Wood Green', x: 43.5, y: 10 },
    'turnpike-lane': { name: 'Turnpike Lane', x: 45, y: 11.5 },
    'manor-house': { name: 'Manor House', x: 45, y: 13.5 },
    'finsbury-park': { name: 'Finsbury Park', x: 44.5, y: 16 },
    arsenal: { name: 'Arsenal', x: 43.5, y: 17 },
    'holloway-road': { name: 'Holloway Road', x: 42, y: 18 },
    'caledonian-road': { name: 'Caledonian Road', x: 41, y: 19 },
    'russell-square': { name: 'Russell Square', x: 42, y: 22 },
    'covent-garden': { name: 'Covent Garden', x: 41, y: 26 },
    'hyde-park-corner': { name: 'Hyde Park Corner', x: 37.5, y: 27 },
    knightsbridge: { name: 'Knightsbridge', x: 36, y: 28.5 },
    'south-ealing': { name: 'South Ealing', x: 21, y: 28 },
    northfields: { name: 'Northfields', x: 19, y: 28.5 },
    'boston-manor': { name: 'Boston Manor', x: 17.5, y: 30 },
    osterley: { name: 'Osterley', x: 16, y: 31.5 },
    'hounslow-east': { name: 'Hounslow East', x: 14.5, y: 33 },
    'hounslow-central': { name: 'Hounslow Central', x: 12.5, y: 33 },
    'hounslow-west': { name: 'Hounslow West', x: 10.5, y: 33.5 },
    'hatton-cross': { name: 'Hatton Cross', x: 8.5, y: 33.5 },
    'heathrow-terminals-2-3': { name: 'Heathrow Terminals 2 & 3', x: 6, y: 33.5 },
    'heathrow-terminal-5': { name: 'Heathrow Terminal 5', x: 4, y: 33.5 },
    brixton: { name: 'Brixton', x: 43.5, y: 34.5 },
    stockwell: { name: 'Stockwell', x: 42, y: 33 },
    vauxhall: { name: 'Vauxhall', x: 42, y: 30.5 },
    pimlico: { name: 'Pimlico', x: 39.5, y: 30.5 },
    'highbury-islington': { name: 'Highbury & Islington', x: 44.5, y: 18 },
    'seven-sisters': { name: 'Seven Sisters', x: 46.5, y: 14.5 },
    'tottenham-hale': { name: 'Tottenham Hale', x: 48, y: 13 },
    'blackhorse-road-station': { name: 'Blackhorse Road station', x: 49.5, y: 11.5 },
    'walthamstow-central': { name: 'Walthamstow Central', x: 51.5, y: 13 },
    'blackhorse-road': { name: 'Blackhorse Road', x: 49.5, y: 13 },
    wanstead: { name: 'Wanstead', x: 60.5, y: 15 },
    redbridge: { name: 'Redbridge', x: 62.5, y: 15 },
    'gants-hill': { name: 'Gants Hill', x: 64.5, y: 15 },
    'newbury-park': { name: 'Newbury Park', x: 66.5, y: 15 },
    barkingside: { name: 'Barkingside', x: 68, y: 13.5 },
    fairlop: { name: 'Fairlop', x: 68, y: 11.5 },
    hainault: { name: 'Hainault', x: 68, y: 9.5 },
    'west-acton': { name: 'West Acton', x: 22.5, y: 24.5 },
    'roding-valley': { name: 'Roding Valley', x: 62.5, y: 8 },
    chigwell: { name: 'Chigwell', x: 64.5, y: 8 },
    'grange-hill': { name: 'Grange Hill', x: 66.5, y: 8 },
    chesham: { name: 'Chesham', x: 0.5, y: 0 },
    watford: { name: 'Watford', x: 10.5, y: 3.5 },
    croxley: { name: 'Croxley', x: 9, y: 5 },
    'west-harrow': { name: 'West Harrow', x: 17, y: 15.5 },
    'rayners-lane': { name: 'Rayners Lane', x: 15.5, y: 17 },
    eastcote: { name: 'Eastcote', x: 13, y: 17 },
    'ruislip-manor': { name: 'Ruislip Manor', x: 11, y: 17 },
    ruislip: { name: 'Ruislip', x: 9, y: 17 },
    ickenham: { name: 'Ickenham', x: 7.5, y: 18.5 },
    hillingdon: { name: 'Hillingdon', x: 6, y: 19.5 },
    uxbridge: { name: 'Uxbridge', x: 4.5, y: 21 },
    'west-brompton': { name: 'West Brompton', x: 34, y: 31 },
    'fulham-broadway': { name: 'Fulham Broadway', x: 34, y: 33.5 },
    'parsons-green': { name: 'Parsons Green', x: 32, y: 33.5 },
    'putney-bridge': { name: 'Putney Bridge', x: 31, y: 35 },
    'east-putney': { name: 'East Putney', x: 31, y: 37 },
    southfields: { name: 'Southfields', x: 31, y: 39 },
    'wimbledon-park': { name: 'Wimbledon Park', x: 31, y: 41 },
    wimbledon: { name: 'Wimbledon', x: 31, y: 43 },
    'kensington-olympia': { name: 'Kensington (Olympia)', x: 31, y: 28.5 },
    gunnersbury: { name: 'Gunnersbury', x: 23.5, y: 31 },
    'kew-gardens': { name: 'Kew Gardens', x: 22, y: 32.5 },
    richmond: { name: 'Richmond', x: 20.5, y: 34 },
    morden: { name: 'Morden', x: 33.5, y: 47 },
    'south-wimbledon': { name: 'South Wimbledon', x: 33.5, y: 45 },
    'colliers-wood': { name: 'Colliers Wood', x: 35, y: 43.5 },
    'tooting-broadway': { name: 'Tooting Broadway', x: 36.5, y: 42 },
    'tooting-bec': { name: 'Tooting Bec', x: 37.5, y: 40.5 },
    balham: { name: 'Balham', x: 39, y: 39 },
    'clapham-south': { name: 'Clapham South', x: 39, y: 37 },
    'clapham-common': { name: 'Clapham Common', x: 40.5, y: 35.5 },
    'clapham-north': { name: 'Clapham North', x: 42, y: 35.5 },
    oval: { name: 'Oval', x: 44, y: 32 },
    borough: { name: 'Borough', x: 47, y: 29 },
    'old-street': { name: 'Old Street', x: 46.5, y: 21.5 },
    angel: { name: 'Angel', x: 44.5, y: 20 },
    'finchley-central': { name: 'Finchley Central', x: 35.5, y: 10 },
    'mill-hill-east': { name: 'Mill Hill East', x: 34, y: 8.5 },
    'kentish-town': { name: 'Kentish Town', x: 38, y: 17.5 },
    'tufnell-park': { name: 'Tufnell Park', x: 39.5, y: 16 },
    archway: { name: 'Archway', x: 39.5, y: 14 },
    highgate: { name: 'Highgate', x: 38, y: 13 },
    'east-finchley': { name: 'East Finchley', x: 36.5, y: 11.5 },
    'west-finchley': { name: 'West Finchley', x: 35.5, y: 8 },
    'woodside-park': { name: 'Woodside Park', x: 35.5, y: 6 },
    'totteridge-whetstone': { name: 'Totteridge & Whetstone', x: 35.5, y: 4 },
    'high-barnet': { name: 'High Barnet', x: 35.5, y: 2 },
    'heathrow-terminal-4': { name: 'Heathrow Terminal 4', x: 7, y: 35 },
    'arnos-grove': { name: 'Arnos Grove', x: 40.5, y: 7.5 },
    'sudbury-hill': { name: 'Sudbury Hill', x: 17, y: 19 },
    'sudbury-town': { name: 'Sudbury Town', x: 18.5, y: 20.5 },
    alperton: { name: 'Alperton', x: 20, y: 22.5 },
    'park-royal': { name: 'Park Royal', x: 21.5, y: 24 },
  },
};
