// Madrid's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'madrid',
  name: 'Madrid',
  system: 'Metro',
  country: 'Spain',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'l1',
      short: 'L1',
      name: 'Línea 1',
      colour: '#67c0dd',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['pinar-de-chamartin', 'bambu', 'chamartin', 'plaza-de-castilla', 'valdeacederas', 'tetuan', 'estrecho', 'alvarado', 'cuatro-caminos', 'rios-rosas', 'iglesia', 'bilbao', 'tribunal', 'gran-via', 'sol', 'tirso-de-molina', 'anton-martin', 'estacion-del-arte', 'atocha', 'menendez-pelayo', 'pacifico', 'puente-de-vallecas', 'nueva-numancia', 'portazgo', 'buenos-aires', 'alto-del-arenal', 'miguel-hernandez', 'sierra-de-guadalupe', 'villa-de-vallecas', 'congosto', 'la-gavia', 'las-suertes', 'valdecarros'],
      ],
    },
    {
      id: 'l2',
      short: 'L2',
      name: 'Línea 2',
      colour: '#fb0f0c',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['cuatro-caminos', 'canal', 'quevedo', 'san-bernardo', 'noviciado', 'santo-domingo', 'opera', 'sol', 'sevilla', 'banco-de-espana', 'retiro', 'principe-de-vergara', 'goya', 'manuel-becerra', 'ventas', 'la-elipa', 'la-almudena', 'alsacia', 'avenida-de-guadalajara', 'las-rosas'],
      ],
    },
    {
      id: 'l3',
      short: 'L3',
      name: 'Línea 3',
      colour: '#ffdf00',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['moncloa', 'arguelles', 'ventura-rodriguez', 'plaza-de-espana', 'callao', 'sol', 'lavapies', 'embajadores', 'palos-de-la-frontera', 'delicias', 'legazpi', 'almendrales', 'hospital-12-de-octubre', 'san-fermin-orcasur', 'ciudad-de-los-angeles', 'villaverde-bajo-cruce', 'san-cristobal', 'villaverde-alto', 'el-casar'],
      ],
    },
    {
      id: 'l4',
      short: 'L4',
      name: 'Línea 4',
      colour: '#824100',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['pinar-de-chamartin', 'manoteras', 'hortaleza', 'parque-de-santa-maria', 'san-lorenzo', 'mar-de-cristal', 'canillas', 'esperanza', 'arturo-soria', 'avenida-de-la-paz', 'alfonso-xiii', 'prosperidad', 'avenida-de-america', 'diego-de-leon', 'lista', 'goya', 'velazquez', 'serrano', 'colon', 'alonso-martinez', 'bilbao', 'san-bernardo', 'arguelles'],
      ],
    },
    {
      id: 'l5',
      short: 'L5',
      name: 'Línea 5',
      colour: '#96bf0d',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['casa-de-campo', 'campamento', 'empalme', 'aluche', 'eugenia-de-montijo', 'carabanchel', 'vista-alegre', 'oporto', 'urgel', 'marques-de-vadillo', 'piramides', 'acacias', 'puerta-de-toledo', 'la-latina', 'opera', 'callao', 'gran-via', 'chueca', 'alonso-martinez', 'ruben-dario', 'nunez-de-balboa', 'diego-de-leon', 'ventas', 'el-carmen', 'quintana', 'pueblo-nuevo', 'ciudad-lineal', 'suanzes', 'torre-arias', 'canillejas', 'el-capricho', 'alameda-de-osuna'],
      ],
    },
    {
      id: 'l6',
      short: 'L6',
      name: 'Línea 6',
      colour: '#939393',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['laguna', 'lucero', 'alto-de-extremadura', 'puerta-del-angel', 'principe-pio', 'arguelles', 'moncloa', 'ciudad-universitaria', 'vicente-aleixandre', 'guzman-el-bueno', 'cuatro-caminos', 'nuevos-ministerios', 'republica-argentina', 'avenida-de-america', 'diego-de-leon', 'manuel-becerra', 'o-donnell', 'sainz-de-baranda', 'conde-de-casal', 'pacifico', 'mendez-alvaro', 'arganzuela-planetario', 'legazpi', 'usera', 'plaza-eliptica', 'opanel', 'oporto', 'carpetana', 'laguna'],
      ],
    },
    {
      id: 'l7',
      short: 'L7',
      name: 'Línea 7',
      colour: '#ed7b24',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['pitis', 'arroyofresno', 'lacoma', 'avenida-de-la-ilustracion', 'penagrande', 'antonio-machado', 'valdezarza', 'francos-rodriguez', 'guzman-el-bueno', 'islas-filipinas', 'canal', 'alonso-cano', 'gregorio-maranon', 'avenida-de-america', 'cartagena', 'parque-de-las-avenidas', 'barrio-de-la-concepcion', 'pueblo-nuevo', 'ascao', 'garcia-noblejas', 'simancas', 'san-blas', 'las-musas', 'estadio-metropolitano', 'barrio-del-puerto', 'coslada-central', 'la-rambla', 'san-fernando', 'jarama', 'henares', 'hospital-de-henares'],
      ],
    },
    {
      id: 'l8',
      short: 'L8',
      name: 'Línea 8',
      colour: '#eba6c9',
      text: '#1a1a1a',
      minutes: 4,
      branches: [
        ['nuevos-ministerios', 'colombia', 'pinar-del-rey', 'mar-de-cristal', 'feria-de-madrid', 'aeropuerto-t1-t2-t3', 'barajas', 'aeropuerto-t4'],
      ],
    },
    {
      id: 'l9',
      short: 'L9',
      name: 'Línea 9',
      colour: '#9c3293',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['paco-de-lucia', 'mirasierra', 'herrera-oria', 'barrio-del-pilar', 'ventilla', 'plaza-de-castilla', 'duque-de-pastrana', 'pio-xii', 'colombia', 'concha-espina', 'cruz-del-rayo', 'avenida-de-america', 'nunez-de-balboa', 'principe-de-vergara', 'ibiza', 'sainz-de-baranda', 'estrella', 'vinateros', 'artilleros', 'pavones', 'valdebernardo', 'vicalvaro', 'san-cipriano', 'puerta-de-arganda', 'rivas-urbanizaciones', 'rivas-futura', 'rivas-vaciamadrid', 'la-poveda', 'arganda-del-rey'],
      ],
    },
    {
      id: 'l10',
      short: 'L10',
      name: 'Línea 10',
      colour: '#015396',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['tres-olivos', 'fuencarral', 'begona', 'chamartin', 'plaza-de-castilla', 'cuzco', 'santiago-bernabeu', 'nuevos-ministerios', 'gregorio-maranon', 'alonso-martinez', 'tribunal', 'plaza-de-espana', 'principe-pio', 'lago', 'batan', 'casa-de-campo', 'colonia-jardin', 'aviacion-espanola', 'cuatro-vientos', 'joaquin-vilumbrales', 'puerta-del-sur'],
        ['hospital-infanta-sofia', 'reyes-catolicos', 'baunatal', 'manuel-de-falla', 'marques-de-la-valdavia', 'la-moraleja', 'la-granja', 'ronda-de-la-comunicacion', 'las-tablas', 'montecarmelo', 'tres-olivos'],
      ],
    },
    {
      id: 'l11',
      short: 'L11',
      name: 'Línea 11',
      colour: '#006400',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['plaza-eliptica', 'abrantes', 'pan-bendito', 'san-francisco', 'carabanchel-alto', 'la-peseta', 'la-fortuna'],
      ],
    },
    {
      id: 'l12',
      short: 'L12',
      name: 'Línea 12. Metrosur',
      colour: '#a49a00',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['puerta-del-sur', 'san-nicasio', 'leganes-central', 'hospital-severo-ochoa', 'casa-del-reloj', 'julian-besteiro', 'el-carrascal', 'el-bercial', 'los-espartales', 'el-casar', 'juan-de-la-cierva', 'getafe-central', 'alonso-de-mendoza', 'conservatorio', 'arroyo-culebro', 'parque-de-los-estados', 'fuenlabrada-central', 'parque-europa', 'hospital-de-fuenlabrada', 'loranca', 'manuela-malasana', 'hospital-de-mostoles', 'pradillo', 'mostoles-central', 'universidad-rey-juan-carlos', 'parque-oeste', 'alcorcon-central', 'parque-lisboa', 'puerta-del-sur'],
      ],
    },
    {
      id: 'r',
      short: 'R',
      name: 'Línea Ramal',
      colour: '#dddddd',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['opera', 'principe-pio'],
      ],
    },
  ],
  times: {
    'valdeacederas tetuan': 1,
    'estrecho alvarado': 1,
    'alvarado cuatro-caminos': 1,
    'cuatro-caminos rios-rosas': 1,
    'bilbao tribunal': 1,
    'gran-via sol': 1,
    'sol tirso-de-molina': 1,
    'tirso-de-molina anton-martin': 1,
    'estacion-del-arte atocha': 1,
    'puente-de-vallecas nueva-numancia': 1,
    'nueva-numancia portazgo': 1,
    'portazgo buenos-aires': 1,
    'alto-del-arenal miguel-hernandez': 1,
    'miguel-hernandez sierra-de-guadalupe': 3,
    'sierra-de-guadalupe villa-de-vallecas': 1,
    'la-gavia las-suertes': 3,
    'cuatro-caminos canal': 2,
    'canal quevedo': 2,
    'san-bernardo noviciado': 2,
    'banco-de-espana retiro': 2,
    'goya manuel-becerra': 2,
    'ventas la-elipa': 3,
    'la-elipa la-almudena': 2,
    'la-almudena alsacia': 3,
    'alsacia avenida-de-guadalajara': 2,
    'avenida-de-guadalajara las-rosas': 2,
    'moncloa arguelles': 1,
    'arguelles ventura-rodriguez': 1,
    'ventura-rodriguez plaza-de-espana': 1,
    'plaza-de-espana callao': 1,
    'callao sol': 1,
    'lavapies embajadores': 1,
    'palos-de-la-frontera delicias': 1,
    'san-cristobal villaverde-alto': 3,
    'villaverde-alto el-casar': 5,
    'pinar-de-chamartin manoteras': 1,
    'san-lorenzo mar-de-cristal': 1,
    'diego-de-leon lista': 1,
    'lista goya': 1,
    'goya velazquez': 1,
    'velazquez serrano': 1,
    'serrano colon': 1,
    'colon alonso-martinez': 1,
    'alonso-martinez bilbao': 1,
    'bilbao san-bernardo': 1,
    'casa-de-campo campamento': 3,
    'campamento empalme': 1,
    'carabanchel vista-alegre': 1,
    'piramides acacias': 1,
    'acacias puerta-de-toledo': 1,
    'opera callao': 1,
    'callao gran-via': 1,
    'gran-via chueca': 1,
    'nunez-de-balboa diego-de-leon': 1,
    'quintana pueblo-nuevo': 1,
    'canillejas el-capricho': 3,
    'principe-pio arguelles': 3,
    'arguelles moncloa': 1,
    'moncloa ciudad-universitaria': 3,
    'vicente-aleixandre guzman-el-bueno': 1,
    'plaza-eliptica opanel': 1,
    'pitis arroyofresno': 1,
    'avenida-de-la-ilustracion penagrande': 1,
    'francos-rodriguez guzman-el-bueno': 3,
    'canal alonso-cano': 1,
    'estadio-metropolitano barrio-del-puerto': 6,
    'coslada-central la-rambla': 3,
    'colombia pinar-del-rey': 5,
    'pinar-del-rey mar-de-cristal': 2,
    'feria-de-madrid aeropuerto-t1-t2-t3': 7,
    'aeropuerto-t1-t2-t3 barajas': 3,
    'paco-de-lucia mirasierra': 3,
    'pio-xii colombia': 1,
    'nunez-de-balboa principe-de-vergara': 3,
    'principe-de-vergara ibiza': 1,
    'pavones valdebernardo': 3,
    'valdebernardo vicalvaro': 3,
    'vicalvaro san-cipriano': 1,
    'puerta-de-arganda rivas-urbanizaciones': 11,
    'rivas-urbanizaciones rivas-futura': 7,
    'rivas-futura rivas-vaciamadrid': 3,
    'rivas-vaciamadrid la-poveda': 8,
    'la-poveda arganda-del-rey': 6,
    'fuencarral begona': 3,
    'gregorio-maranon alonso-martinez': 3,
    'alonso-martinez tribunal': 1,
    'principe-pio lago': 3,
    'lago batan': 4,
    'casa-de-campo colonia-jardin': 3,
    'colonia-jardin aviacion-espanola': 4,
    'cuatro-vientos joaquin-vilumbrales': 7,
    'hospital-infanta-sofia reyes-catolicos': 3,
    'manuel-de-falla marques-de-la-valdavia': 3,
    'la-moraleja la-granja': 4,
    'la-granja ronda-de-la-comunicacion': 3,
    'las-tablas montecarmelo': 5,
    'montecarmelo tres-olivos': 1,
    'pan-bendito san-francisco': 1,
    'la-peseta la-fortuna': 4,
    'puerta-del-sur san-nicasio': 6,
    'el-carrascal el-bercial': 3,
    'el-bercial los-espartales': 3,
    'el-casar juan-de-la-cierva': 3,
    'getafe-central alonso-de-mendoza': 3,
    'alonso-de-mendoza conservatorio': 3,
    'arroyo-culebro parque-de-los-estados': 5,
    'hospital-de-fuenlabrada loranca': 4,
    'loranca manuela-malasana': 6,
    'manuela-malasana hospital-de-mostoles': 3,
    'universidad-rey-juan-carlos parque-oeste': 5,
    'parque-oeste alcorcon-central': 3,
  },
  stations: {
    'plaza-eliptica': { name: 'Plaza Elíptica', x: 26.5, y: 48.5 },
    abrantes: { name: 'Abrantes', x: 24.5, y: 49 },
    'pan-bendito': { name: 'Pan Bendito', x: 23, y: 50 },
    'san-francisco': { name: 'San Francisco', x: 21.5, y: 51.5 },
    'carabanchel-alto': { name: 'Carabanchel Alto', x: 20, y: 53 },
    'la-peseta': { name: 'La Peseta', x: 18.5, y: 54.5 },
    'la-fortuna': { name: 'La Fortuna', x: 17, y: 55.5 },
    laguna: { name: 'Laguna', x: 20.5, y: 44.5 },
    lucero: { name: 'Lucero', x: 20.5, y: 43 },
    'alto-de-extremadura': { name: 'Alto de Extremadura', x: 22, y: 41.5 },
    'puerta-del-angel': { name: 'Puerta del Ángel', x: 23, y: 40 },
    'principe-pio': { name: 'Príncipe Pío', x: 23, y: 38.5 },
    arguelles: { name: 'Argüelles', x: 23.5, y: 35.5 },
    moncloa: { name: 'Moncloa', x: 24, y: 33 },
    'ciudad-universitaria': { name: 'Ciudad Universitaria', x: 23, y: 31.5 },
    'vicente-aleixandre': { name: 'Vicente Aleixandre', x: 24.5, y: 29.5 },
    'guzman-el-bueno': { name: 'Guzmán el Bueno', x: 27, y: 29.5 },
    'cuatro-caminos': { name: 'Cuatro Caminos', x: 29.5, y: 29.5 },
    'nuevos-ministerios': { name: 'Nuevos Ministerios', x: 32, y: 29.5 },
    'republica-argentina': { name: 'República Argentina', x: 32, y: 31 },
    'avenida-de-america': { name: 'Avenida de América', x: 33.5, y: 32.5 },
    'diego-de-leon': { name: 'Diego de León', x: 35.5, y: 34 },
    'manuel-becerra': { name: 'Manuel Becerra', x: 36, y: 36 },
    'o-donnell': { name: 'O\'Donnell', x: 36.5, y: 38 },
    'sainz-de-baranda': { name: 'Sainz de Baranda', x: 36.5, y: 40 },
    'conde-de-casal': { name: 'Conde de Casal', x: 36.5, y: 42 },
    pacifico: { name: 'Pacífico', x: 35, y: 43.5 },
    'mendez-alvaro': { name: 'Méndez Álvaro', x: 33.5, y: 45.5 },
    'arganzuela-planetario': { name: 'Arganzuela-Planetario', x: 31.5, y: 45.5 },
    legazpi: { name: 'Legazpi', x: 30, y: 47 },
    usera: { name: 'Usera', x: 28, y: 47 },
    opanel: { name: 'Opañel', x: 25.5, y: 47.5 },
    oporto: { name: 'Oporto', x: 23.5, y: 47.5 },
    carpetana: { name: 'Carpetana', x: 22, y: 46 },
    'ventura-rodriguez': { name: 'Ventura Rodríguez', x: 25, y: 35.5 },
    'plaza-de-espana': { name: 'Plaza de España', x: 25.5, y: 37.5 },
    callao: { name: 'Callao', x: 27, y: 37.5 },
    sol: { name: 'Sol', x: 27.5, y: 39 },
    lavapies: { name: 'Lavapiés', x: 29, y: 41 },
    embajadores: { name: 'Embajadores', x: 28.5, y: 43.5 },
    'palos-de-la-frontera': { name: 'Palos de la Frontera', x: 30, y: 42.5 },
    delicias: { name: 'Delicias', x: 30, y: 44.5 },
    almendrales: { name: 'Almendrales', x: 29.5, y: 49 },
    'hospital-12-de-octubre': { name: 'Hospital 12 de Octubre', x: 29, y: 51.5 },
    'san-fermin-orcasur': { name: 'San Fermín-Orcasur', x: 29, y: 53.5 },
    'ciudad-de-los-angeles': { name: 'Ciudad de los Ángeles', x: 28.5, y: 55.5 },
    'villaverde-bajo-cruce': { name: 'Villaverde Bajo - Cruce', x: 28, y: 58 },
    'san-cristobal': { name: 'San Cristóbal', x: 27.5, y: 60 },
    'villaverde-alto': { name: 'Villaverde Alto', x: 26, y: 61.5 },
    'el-casar': { name: 'El Casar', x: 24, y: 63.5 },
    'hospital-infanta-sofia': { name: 'Hospital Infanta Sofía', x: 45, y: 0 },
    'reyes-catolicos': { name: 'Reyes Católicos', x: 43.5, y: 1.5 },
    baunatal: { name: 'Baunatal', x: 41.5, y: 1.5 },
    'manuel-de-falla': { name: 'Manuel de Falla', x: 40, y: 3 },
    'marques-de-la-valdavia': { name: 'Marqués de la Valdavia', x: 40, y: 5 },
    'la-moraleja': { name: 'La Moraleja', x: 40, y: 7 },
    'la-granja': { name: 'La Granja', x: 38.5, y: 8.5 },
    'ronda-de-la-comunicacion': { name: 'Ronda de la Comunicación', x: 36.5, y: 10.5 },
    'las-tablas': { name: 'Las Tablas', x: 35, y: 12 },
    montecarmelo: { name: 'Montecarmelo', x: 33.5, y: 13.5 },
    'tres-olivos': { name: 'Tres Olivos', x: 32, y: 15 },
    canal: { name: 'Canal', x: 27.5, y: 30.5 },
    quevedo: { name: 'Quevedo', x: 27, y: 32.5 },
    'san-bernardo': { name: 'San Bernardo', x: 25.5, y: 34 },
    noviciado: { name: 'Noviciado', x: 26, y: 36 },
    'santo-domingo': { name: 'Santo Domingo', x: 26.5, y: 38 },
    opera: { name: 'Ópera', x: 25, y: 39 },
    sevilla: { name: 'Sevilla', x: 29.5, y: 39.5 },
    'banco-de-espana': { name: 'Banco de España', x: 31, y: 38 },
    retiro: { name: 'Retiro', x: 33, y: 38.5 },
    'principe-de-vergara': { name: 'Príncipe de Vergara', x: 33, y: 37 },
    goya: { name: 'Goya', x: 34.5, y: 37 },
    ventas: { name: 'Ventas', x: 37.5, y: 35 },
    'la-elipa': { name: 'La Elipa', x: 39, y: 36.5 },
    'la-almudena': { name: 'La Almudena', x: 41, y: 36.5 },
    alsacia: { name: 'Alsacia', x: 43, y: 36.5 },
    'avenida-de-guadalajara': { name: 'Avenida de Guadalajara', x: 45, y: 36.5 },
    'las-rosas': { name: 'Las Rosas', x: 47.5, y: 36.5 },
    'casa-de-campo': { name: 'Casa de Campo', x: 16.5, y: 44.5 },
    campamento: { name: 'Campamento', x: 15, y: 45.5 },
    empalme: { name: 'Empalme', x: 16.5, y: 47 },
    aluche: { name: 'Aluche', x: 17, y: 48.5 },
    'eugenia-de-montijo': { name: 'Eugenia de Montijo', x: 19, y: 49 },
    carabanchel: { name: 'Carabanchel', x: 20, y: 47.5 },
    'vista-alegre': { name: 'Vista Alegre', x: 21.5, y: 47.5 },
    urgel: { name: 'Urgel', x: 24.5, y: 46 },
    'marques-de-vadillo': { name: 'Marqués de Vadillo', x: 25.5, y: 45 },
    piramides: { name: 'Pirámides', x: 27, y: 43.5 },
    acacias: { name: 'Acacias', x: 28, y: 42.5 },
    'puerta-de-toledo': { name: 'Puerta de Toledo', x: 26, y: 42.5 },
    'la-latina': { name: 'La Latina', x: 26, y: 40.5 },
    'gran-via': { name: 'Gran Vía', x: 29, y: 37.5 },
    chueca: { name: 'Chueca', x: 29, y: 35.5 },
    'alonso-martinez': { name: 'Alonso Martínez', x: 30, y: 34 },
    'ruben-dario': { name: 'Rubén Darío', x: 31.5, y: 33.5 },
    'nunez-de-balboa': { name: 'Núñez de Balboa', x: 33.5, y: 34 },
    'el-carmen': { name: 'El Carmen', x: 39, y: 33.5 },
    quintana: { name: 'Quintana', x: 40.5, y: 34.5 },
    'pueblo-nuevo': { name: 'Pueblo Nuevo', x: 42, y: 33 },
    'ciudad-lineal': { name: 'Ciudad Lineal', x: 44, y: 33 },
    suanzes: { name: 'Suanzes', x: 46, y: 33 },
    'torre-arias': { name: 'Torre Arias', x: 47.5, y: 31.5 },
    canillejas: { name: 'Canillejas', x: 49, y: 30 },
    'el-capricho': { name: 'El Capricho', x: 50.5, y: 28.5 },
    'alameda-de-osuna': { name: 'Alameda de Osuna', x: 52, y: 27 },
    'pinar-de-chamartin': { name: 'Pinar de Chamartín', x: 34.5, y: 20.5 },
    bambu: { name: 'Bambú', x: 33.5, y: 21.5 },
    chamartin: { name: 'Chamartín', x: 31.5, y: 21.5 },
    'plaza-de-castilla': { name: 'Plaza de Castilla', x: 31.5, y: 23.5 },
    valdeacederas: { name: 'Valdeacederas', x: 30, y: 24.5 },
    tetuan: { name: 'Tetuán', x: 30, y: 26.5 },
    estrecho: { name: 'Estrecho', x: 28, y: 26.5 },
    alvarado: { name: 'Alvarado', x: 28, y: 28 },
    'rios-rosas': { name: 'Ríos Rosas', x: 28.5, y: 31.5 },
    iglesia: { name: 'Iglesia', x: 29.5, y: 32.5 },
    bilbao: { name: 'Bilbao', x: 28, y: 34 },
    tribunal: { name: 'Tribunal', x: 27.5, y: 36 },
    'tirso-de-molina': { name: 'Tirso de Molina', x: 27.5, y: 40.5 },
    'anton-martin': { name: 'Antón Martín', x: 30, y: 40.5 },
    'estacion-del-arte': { name: 'Estación del Arte', x: 31.5, y: 42 },
    atocha: { name: 'Atocha', x: 31.5, y: 44 },
    'menendez-pelayo': { name: 'Menéndez Pelayo', x: 33.5, y: 42.5 },
    'puente-de-vallecas': { name: 'Puente de Vallecas', x: 36, y: 45 },
    'nueva-numancia': { name: 'Nueva Numancia', x: 38, y: 45 },
    portazgo: { name: 'Portazgo', x: 38, y: 47 },
    'buenos-aires': { name: 'Buenos Aires', x: 40, y: 47 },
    'alto-del-arenal': { name: 'Alto del Arenal', x: 42, y: 46.5 },
    'miguel-hernandez': { name: 'Miguel Hernández', x: 43.5, y: 48 },
    'sierra-de-guadalupe': { name: 'Sierra de Guadalupe', x: 45.5, y: 48 },
    'villa-de-vallecas': { name: 'Villa de Vallecas', x: 47, y: 49.5 },
    congosto: { name: 'Congosto', x: 47, y: 51.5 },
    'la-gavia': { name: 'La Gavia', x: 48.5, y: 53 },
    'las-suertes': { name: 'Las Suertes', x: 50, y: 54 },
    valdecarros: { name: 'Valdecarros', x: 51.5, y: 55.5 },
    pitis: { name: 'Pitis', x: 23.5, y: 16 },
    arroyofresno: { name: 'Arroyofresno', x: 23.5, y: 18 },
    lacoma: { name: 'Lacoma', x: 25, y: 19 },
    'avenida-de-la-ilustracion': { name: 'Avenida de la Ilustración', x: 26.5, y: 20.5 },
    penagrande: { name: 'Peñagrande', x: 28, y: 22 },
    'antonio-machado': { name: 'Antonio Machado', x: 26.5, y: 23.5 },
    valdezarza: { name: 'Valdezarza', x: 26.5, y: 25.5 },
    'francos-rodriguez': { name: 'Francos Rodríguez', x: 26.5, y: 27.5 },
    'islas-filipinas': { name: 'Islas Filipinas', x: 25.5, y: 31 },
    'alonso-cano': { name: 'Alonso Cano', x: 30, y: 31 },
    'gregorio-maranon': { name: 'Gregorio Marañón', x: 31.5, y: 32 },
    cartagena: { name: 'Cartagena', x: 35.5, y: 32.5 },
    'parque-de-las-avenidas': { name: 'Parque de las Avenidas', x: 38, y: 32.5 },
    'barrio-de-la-concepcion': { name: 'Barrio de la Concepción', x: 40, y: 32.5 },
    ascao: { name: 'Ascao', x: 42, y: 35 },
    'garcia-noblejas': { name: 'García Noblejas', x: 44.5, y: 35 },
    simancas: { name: 'Simancas', x: 46.5, y: 35 },
    'san-blas': { name: 'San Blas', x: 49, y: 35 },
    'las-musas': { name: 'Las Musas', x: 51, y: 35 },
    'estadio-metropolitano': { name: 'Estadio Metropolitano', x: 53, y: 35 },
    'barrio-del-puerto': { name: 'Barrio del Puerto', x: 55.5, y: 35 },
    'coslada-central': { name: 'Coslada Central', x: 57.5, y: 35.5 },
    'la-rambla': { name: 'La Rambla', x: 59.5, y: 35.5 },
    'san-fernando': { name: 'San Fernando', x: 61.5, y: 35.5 },
    jarama: { name: 'Jarama', x: 64, y: 35.5 },
    henares: { name: 'Henares', x: 65.5, y: 37 },
    'hospital-de-henares': { name: 'Hospital de Henares', x: 63.5, y: 37 },
    colombia: { name: 'Colombia', x: 35, y: 27 },
    'pinar-del-rey': { name: 'Pinar del Rey', x: 37.5, y: 25.5 },
    'mar-de-cristal': { name: 'Mar de Cristal', x: 40, y: 25 },
    'feria-de-madrid': { name: 'Feria de Madrid', x: 42.5, y: 25 },
    'aeropuerto-t1-t2-t3': { name: 'Aeropuerto T1-T2-T3', x: 44.5, y: 25 },
    barajas: { name: 'Barajas', x: 46, y: 23.5 },
    'aeropuerto-t4': { name: 'Aeropuerto T4', x: 46, y: 21.5 },
    'paco-de-lucia': { name: 'Paco de Lucía', x: 26, y: 15.5 },
    mirasierra: { name: 'Mirasierra', x: 26, y: 17.5 },
    'herrera-oria': { name: 'Herrera Oria', x: 27, y: 19 },
    'barrio-del-pilar': { name: 'Barrio del Pilar', x: 28.5, y: 20.5 },
    ventilla: { name: 'Ventilla', x: 30, y: 22 },
    'duque-de-pastrana': { name: 'Duque de Pastrana', x: 33.5, y: 23.5 },
    'pio-xii': { name: 'Pío XII', x: 33.5, y: 25.5 },
    'concha-espina': { name: 'Concha Espina', x: 33.5, y: 28.5 },
    'cruz-del-rayo': { name: 'Cruz del Rayo', x: 33.5, y: 30 },
    ibiza: { name: 'Ibiza', x: 35, y: 38.5 },
    estrella: { name: 'Estrella', x: 38.5, y: 42 },
    vinateros: { name: 'Vinateros', x: 41, y: 42 },
    artilleros: { name: 'Artilleros', x: 43.5, y: 43.5 },
    pavones: { name: 'Pavones', x: 45.5, y: 45.5 },
    valdebernardo: { name: 'Valdebernardo', x: 48, y: 45.5 },
    vicalvaro: { name: 'Vicálvaro', x: 50.5, y: 46 },
    'san-cipriano': { name: 'San Cipriano', x: 52.5, y: 47.5 },
    'puerta-de-arganda': { name: 'Puerta de Arganda', x: 54.5, y: 49.5 },
    'rivas-urbanizaciones': { name: 'Rivas Urbanizaciones', x: 56.5, y: 51 },
    'rivas-futura': { name: 'Rivas Futura', x: 58.5, y: 53 },
    'rivas-vaciamadrid': { name: 'Rivas Vaciamadrid', x: 60.5, y: 54.5 },
    'la-poveda': { name: 'La Poveda', x: 62, y: 56 },
    'arganda-del-rey': { name: 'Arganda del Rey', x: 63.5, y: 57.5 },
    'puerta-del-sur': { name: 'Puerta del Sur', x: 9.5, y: 56.5 },
    'san-nicasio': { name: 'San Nicasio', x: 11, y: 58 },
    'leganes-central': { name: 'Leganés Central', x: 12.5, y: 59.5 },
    'hospital-severo-ochoa': { name: 'Hospital Severo Ochoa', x: 14, y: 61.5 },
    'casa-del-reloj': { name: 'Casa del Reloj', x: 16, y: 61.5 },
    'julian-besteiro': { name: 'Julián Besteiro', x: 17.5, y: 60 },
    'el-carrascal': { name: 'El Carrascal', x: 19.5, y: 60.5 },
    'el-bercial': { name: 'El Bercial', x: 21, y: 62 },
    'los-espartales': { name: 'Los Espartales', x: 22, y: 63.5 },
    'juan-de-la-cierva': { name: 'Juan de la Cierva', x: 22.5, y: 65 },
    'getafe-central': { name: 'Getafe Central', x: 20.5, y: 66.5 },
    'alonso-de-mendoza': { name: 'Alonso de Mendoza', x: 18.5, y: 68 },
    conservatorio: { name: 'Conservatorio', x: 16.5, y: 69.5 },
    'arroyo-culebro': { name: 'Arroyo Culebro', x: 15, y: 71 },
    'parque-de-los-estados': { name: 'Parque de los Estados', x: 12.5, y: 71 },
    'fuenlabrada-central': { name: 'Fuenlabrada Central', x: 10, y: 71 },
    'parque-europa': { name: 'Parque Europa', x: 7.5, y: 71 },
    'hospital-de-fuenlabrada': { name: 'Hospital de Fuenlabrada', x: 5, y: 71 },
    loranca: { name: 'Loranca', x: 3.5, y: 69 },
    'manuela-malasana': { name: 'Manuela Malasaña', x: 2, y: 67.5 },
    'hospital-de-mostoles': { name: 'Hospital de Móstoles', x: 0, y: 66 },
    pradillo: { name: 'Pradillo', x: 0, y: 63.5 },
    'mostoles-central': { name: 'Móstoles Central', x: 0, y: 61 },
    'universidad-rey-juan-carlos': { name: 'Universidad Rey Juan Carlos', x: 1.5, y: 59.5 },
    'parque-oeste': { name: 'Parque Oeste', x: 3, y: 57.5 },
    'alcorcon-central': { name: 'Alcorcón Central', x: 5, y: 57 },
    'parque-lisboa': { name: 'Parque Lisboa', x: 7.5, y: 56.5 },
    manoteras: { name: 'Manoteras', x: 36, y: 22 },
    hortaleza: { name: 'Hortaleza', x: 38, y: 22.5 },
    'parque-de-santa-maria': { name: 'Parque de Santa María', x: 39, y: 21 },
    'san-lorenzo': { name: 'San Lorenzo', x: 40.5, y: 23 },
    canillas: { name: 'Canillas', x: 41, y: 27 },
    esperanza: { name: 'Esperanza', x: 39, y: 27 },
    'arturo-soria': { name: 'Arturo Soria', x: 37.5, y: 27 },
    'avenida-de-la-paz': { name: 'Avenida de la Paz', x: 36.5, y: 28.5 },
    'alfonso-xiii': { name: 'Alfonso XIII', x: 35.5, y: 29.5 },
    prosperidad: { name: 'Prosperidad', x: 34.5, y: 31 },
    lista: { name: 'Lista', x: 34.5, y: 35 },
    velazquez: { name: 'Velázquez', x: 33, y: 35.5 },
    serrano: { name: 'Serrano', x: 31.5, y: 35 },
    colon: { name: 'Colón', x: 30, y: 36.5 },
    fuencarral: { name: 'Fuencarral', x: 32, y: 17 },
    begona: { name: 'Begoña', x: 31.5, y: 19.5 },
    cuzco: { name: 'Cuzco', x: 31.5, y: 25.5 },
    'santiago-bernabeu': { name: 'Santiago Bernabéu', x: 31, y: 27.5 },
    lago: { name: 'Lago', x: 21, y: 40 },
    batan: { name: 'Batán', x: 19, y: 42.5 },
    'colonia-jardin': { name: 'Colonia Jardín', x: 14.5, y: 47 },
    'aviacion-espanola': { name: 'Aviación Española', x: 13, y: 49 },
    'cuatro-vientos': { name: 'Cuatro Vientos', x: 11.5, y: 51.5 },
    'joaquin-vilumbrales': { name: 'Joaquín Vilumbrales', x: 9.5, y: 53.5 },
  },
};
