// Manchester's Metrolink, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'manchester',
  name: 'Manchester',
  system: 'Metrolink',
  country: 'United Kingdom',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'altrincham-bury',
      short: '',
      name: 'Altrincham – Bury',
      colour: '#008800',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['bury', 'radcliffe', 'whitefield', 'besses-o-th-barn', 'prestwich', 'heaton-park', 'bowker-vale', 'crumpsall', 'abraham-moss', 'queens-road', 'victoria', 'shudehill', 'market-street', 'st-peter-s-square', 'deansgate-castlefield', 'cornbrook', 'trafford-bar', 'old-trafford', 'stretford', 'dane-road', 'sale', 'brooklands', 'timperley', 'navigation-road', 'altrincham'],
      ],
    },
    {
      id: 'ashton-under-lyne-eccles',
      short: '',
      name: 'Ashton-under-Lyne – Eccles',
      colour: '#00ccff',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['ashton-under-lyne', 'ashton-west', 'ashton-moss', 'audenshaw', 'droylsden', 'cemetery-road', 'edge-lane', 'clayton-hall', 'velopark', 'etihad-campus', 'holt-town', 'new-islington', 'piccadilly', 'piccadilly-gardens', 'st-peter-s-square', 'deansgate-castlefield', 'cornbrook', 'pomona', 'exchange-quay', 'salford-quays', 'anchorage', 'harbour-city', 'mediacityuk', 'broadway', 'langworthy', 'weaste', 'ladywell', 'eccles'],
        ['ashton-under-lyne', 'ashton-west', 'ashton-moss', 'audenshaw', 'droylsden', 'cemetery-road', 'edge-lane', 'clayton-hall', 'velopark', 'etihad-campus', 'holt-town', 'new-islington', 'piccadilly', 'piccadilly-gardens', 'st-peter-s-square', 'deansgate-castlefield', 'cornbrook', 'pomona', 'exchange-quay', 'salford-quays', 'anchorage', 'harbour-city', 'broadway', 'langworthy', 'weaste', 'ladywell', 'eccles'],
      ],
    },
    {
      id: 'ashton-under-lyne-mediacityuk',
      short: '',
      name: 'Ashton-under-Lyne – MediaCityUK',
      colour: '#ff7700',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['mediacityuk', 'harbour-city', 'anchorage', 'salford-quays', 'exchange-quay', 'pomona', 'cornbrook', 'deansgate-castlefield', 'st-peter-s-square', 'piccadilly-gardens', 'piccadilly', 'new-islington', 'holt-town', 'etihad-campus', 'velopark', 'clayton-hall', 'edge-lane', 'cemetery-road', 'droylsden', 'audenshaw', 'ashton-moss', 'ashton-west', 'ashton-under-lyne'],
      ],
    },
    {
      id: 'bury-manchester-piccadilly',
      short: '',
      name: 'Bury - Manchester Piccadilly',
      colour: '#ffbb00',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['bury', 'radcliffe', 'whitefield', 'besses-o-th-barn', 'prestwich', 'heaton-park', 'bowker-vale', 'crumpsall', 'abraham-moss', 'queens-road', 'victoria', 'shudehill', 'market-street', 'piccadilly-gardens', 'piccadilly'],
      ],
    },
    {
      id: 'manchester-airport-manchester-victoria',
      short: '',
      name: 'Manchester Airport - Manchester Victoria',
      colour: '#0066bb',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['victoria', 'shudehill', 'market-street', 'st-peter-s-square', 'deansgate-castlefield', 'cornbrook', 'trafford-bar', 'firswood', 'chorlton', 'st-werburgh-s-road', 'barlow-moor-road', 'sale-water-park', 'northern-moor', 'wythenshawe-park', 'moor-road', 'baguley', 'roundthorn', 'martinscroft', 'benchill', 'crossacres', 'wythenshawe-town-centre', 'robinswood-road', 'peel-hall', 'shadowmoss', 'manchester-airport'],
      ],
    },
    {
      id: 'piccadilly-altrincham',
      short: '',
      name: 'Piccadilly - Altrincham',
      colour: '#881188',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['piccadilly', 'piccadilly-gardens', 'st-peter-s-square', 'deansgate-castlefield', 'cornbrook', 'trafford-bar', 'old-trafford', 'stretford', 'dane-road', 'sale', 'brooklands', 'timperley', 'navigation-road', 'altrincham'],
      ],
    },
    {
      id: 'rochdale-east-didsbury',
      short: '',
      name: 'Rochdale - East Didsbury',
      colour: '#ff88bb',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['rochdale-town-centre', 'rochdale-railway-station', 'newbold', 'kingsway-business-park', 'milnrow', 'newhey', 'shaw-and-crompton', 'derker', 'oldham-mumps', 'oldham-central', 'oldham-king-street', 'westwood', 'freehold', 'south-chadderton', 'hollinwood', 'failsworth', 'newton-heath-and-moston', 'central-park', 'monsall', 'victoria', 'exchange-square', 'st-peter-s-square', 'deansgate-castlefield', 'cornbrook', 'trafford-bar', 'firswood', 'chorlton', 'st-werburgh-s-road', 'withington', 'burton-road', 'west-didsbury', 'didsbury-village', 'east-didsbury'],
      ],
    },
    {
      id: 'shaw-and-crompton-east-didsbury',
      short: '',
      name: 'Shaw and Crompton - East Didsbury',
      colour: '#887766',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['shaw-and-crompton', 'derker', 'oldham-mumps', 'oldham-central', 'oldham-king-street', 'westwood', 'freehold', 'south-chadderton', 'hollinwood', 'failsworth', 'newton-heath-and-moston', 'central-park', 'monsall', 'victoria', 'exchange-square', 'st-peter-s-square', 'deansgate-castlefield', 'cornbrook', 'trafford-bar', 'firswood', 'chorlton', 'st-werburgh-s-road', 'withington', 'burton-road', 'west-didsbury', 'didsbury-village', 'east-didsbury'],
      ],
    },
    {
      id: 'the-trafford-centre-cornbrook',
      short: '',
      name: 'The Trafford Centre – Cornbrook',
      colour: '#ee0011',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['cornbrook', 'pomona', 'wharfside', 'imperial-war-museum', 'village', 'parkway', 'trafford-palazzo', 'the-trafford-centre'],
      ],
    },
  ],
  times: {
    'bury radcliffe': 7,
    'radcliffe whitefield': 4,
    'whitefield besses-o-th-barn': 3,
    'heaton-park bowker-vale': 3,
    'abraham-moss queens-road': 3,
    'queens-road victoria': 4,
    'victoria shudehill': 1,
    'shudehill market-street': 1,
    'market-street st-peter-s-square': 1,
    'deansgate-castlefield cornbrook': 3,
    'cornbrook trafford-bar': 3,
    'old-trafford stretford': 4,
    'stretford dane-road': 4,
    'brooklands timperley': 4,
    'edge-lane clayton-hall': 3,
    'holt-town new-islington': 1,
    'piccadilly piccadilly-gardens': 1,
    'piccadilly-gardens st-peter-s-square': 1,
    'pomona exchange-quay': 1,
    'exchange-quay salford-quays': 1,
    'salford-quays anchorage': 1,
    'anchorage harbour-city': 1,
    'harbour-city mediacityuk': 1,
    'mediacityuk broadway': 1,
    'weaste ladywell': 3,
    'ladywell eccles': 1,
    'harbour-city broadway': 1,
    'mediacityuk harbour-city': 1,
    'harbour-city anchorage': 1,
    'anchorage salford-quays': 1,
    'salford-quays exchange-quay': 1,
    'exchange-quay pomona': 1,
    'cornbrook deansgate-castlefield': 3,
    'st-peter-s-square piccadilly-gardens': 1,
    'piccadilly-gardens piccadilly': 1,
    'new-islington holt-town': 1,
    'clayton-hall edge-lane': 3,
    'market-street piccadilly-gardens': 1,
    'trafford-bar firswood': 3,
    'barlow-moor-road sale-water-park': 3,
    'sale-water-park northern-moor': 3,
    'wythenshawe-park moor-road': 1,
    'baguley roundthorn': 1,
    'martinscroft benchill': 4,
    'benchill crossacres': 1,
    'wythenshawe-town-centre robinswood-road': 1,
    'shadowmoss manchester-airport': 3,
    'rochdale-railway-station newbold': 3,
    'milnrow newhey': 3,
    'newhey shaw-and-crompton': 6,
    'shaw-and-crompton derker': 6,
    'oldham-central oldham-king-street': 1,
    'freehold south-chadderton': 3,
    'hollinwood failsworth': 3,
    'failsworth newton-heath-and-moston': 3,
    'monsall victoria': 5,
    'victoria exchange-square': 1,
    'st-werburgh-s-road withington': 3,
    'parkway trafford-palazzo': 3,
    'trafford-palazzo the-trafford-centre': 1,
  },
  stations: {
    'ashton-under-lyne': { name: 'Ashton-under-Lyne', x: 40.5, y: 30 },
    'ashton-west': { name: 'Ashton West', x: 38.5, y: 30 },
    'ashton-moss': { name: 'Ashton Moss', x: 37, y: 31.5 },
    audenshaw: { name: 'Audenshaw', x: 35.5, y: 32.5 },
    droylsden: { name: 'Droylsden', x: 33.5, y: 32.5 },
    'cemetery-road': { name: 'Cemetery Road', x: 31.5, y: 32.5 },
    'edge-lane': { name: 'Edge Lane', x: 29.5, y: 32.5 },
    'clayton-hall': { name: 'Clayton Hall', x: 27.5, y: 32.5 },
    velopark: { name: 'Velopark', x: 25.5, y: 32.5 },
    'etihad-campus': { name: 'Etihad Campus', x: 24, y: 31 },
    'holt-town': { name: 'Holt Town', x: 22.5, y: 32.5 },
    'new-islington': { name: 'New Islington', x: 21.5, y: 33.5 },
    piccadilly: { name: 'Piccadilly', x: 20, y: 35 },
    'piccadilly-gardens': { name: 'Piccadilly Gardens', x: 18.5, y: 33.5 },
    'st-peter-s-square': { name: 'St Peter\'s Square', x: 17, y: 34 },
    'deansgate-castlefield': { name: 'Deansgate-Castlefield', x: 15.5, y: 36 },
    cornbrook: { name: 'Cornbrook', x: 14, y: 37.5 },
    pomona: { name: 'Pomona', x: 12, y: 37.5 },
    'exchange-quay': { name: 'Exchange Quay', x: 11, y: 39 },
    'salford-quays': { name: 'Salford Quays', x: 11, y: 36.5 },
    anchorage: { name: 'Anchorage', x: 11, y: 34.5 },
    'harbour-city': { name: 'Harbour City', x: 9.5, y: 36 },
    broadway: { name: 'Broadway', x: 8.5, y: 34.5 },
    langworthy: { name: 'Langworthy', x: 8.5, y: 32.5 },
    weaste: { name: 'Weaste', x: 6.5, y: 32.5 },
    ladywell: { name: 'Ladywell', x: 4.5, y: 32.5 },
    eccles: { name: 'Eccles', x: 2.5, y: 32.5 },
    bury: { name: 'Bury', x: 8.5, y: 12.5 },
    radcliffe: { name: 'Radcliffe', x: 8.5, y: 14.5 },
    whitefield: { name: 'Whitefield', x: 10, y: 16 },
    'besses-o-th-barn': { name: 'Besses o\' th\' Barn', x: 11.5, y: 17.5 },
    prestwich: { name: 'Prestwich', x: 13, y: 19 },
    'heaton-park': { name: 'Heaton Park', x: 14.5, y: 20.5 },
    'bowker-vale': { name: 'Bowker Vale', x: 16, y: 22 },
    crumpsall: { name: 'Crumpsall', x: 17.5, y: 24 },
    'abraham-moss': { name: 'Abraham Moss', x: 19, y: 25.5 },
    'queens-road': { name: 'Queens Road', x: 19, y: 27.5 },
    victoria: { name: 'Victoria', x: 19.5, y: 30 },
    shudehill: { name: 'Shudehill', x: 19, y: 32 },
    'market-street': { name: 'Market Street', x: 17, y: 32.5 },
    'trafford-bar': { name: 'Trafford Bar', x: 12.5, y: 39.5 },
    'old-trafford': { name: 'Old Trafford', x: 11, y: 41 },
    stretford: { name: 'Stretford', x: 9.5, y: 42.5 },
    'dane-road': { name: 'Dane Road', x: 8, y: 44.5 },
    sale: { name: 'Sale', x: 6.5, y: 46 },
    brooklands: { name: 'Brooklands', x: 5, y: 47.5 },
    timperley: { name: 'Timperley', x: 3.5, y: 49 },
    'navigation-road': { name: 'Navigation Road', x: 2, y: 50.5 },
    altrincham: { name: 'Altrincham', x: 2, y: 52.5 },
    firswood: { name: 'Firswood', x: 12.5, y: 41.5 },
    chorlton: { name: 'Chorlton', x: 12.5, y: 43.5 },
    'st-werburgh-s-road': { name: 'St Werburgh\'s Road', x: 14, y: 45 },
    'barlow-moor-road': { name: 'Barlow Moor Road', x: 12.5, y: 46.5 },
    'sale-water-park': { name: 'Sale Water Park', x: 11, y: 48 },
    'northern-moor': { name: 'Northern Moor', x: 10.5, y: 50.5 },
    'wythenshawe-park': { name: 'Wythenshawe Park', x: 9.5, y: 52 },
    'moor-road': { name: 'Moor Road', x: 9, y: 54 },
    baguley: { name: 'Baguley', x: 9, y: 56 },
    roundthorn: { name: 'Roundthorn', x: 10.5, y: 57.5 },
    martinscroft: { name: 'Martinscroft', x: 12.5, y: 57.5 },
    benchill: { name: 'Benchill', x: 14.5, y: 57.5 },
    crossacres: { name: 'Crossacres', x: 16, y: 59 },
    'wythenshawe-town-centre': { name: 'Wythenshawe Town Centre', x: 14, y: 59.5 },
    'robinswood-road': { name: 'Robinswood Road', x: 15, y: 61 },
    'peel-hall': { name: 'Peel Hall', x: 17, y: 61 },
    shadowmoss: { name: 'Shadowmoss', x: 15.5, y: 62.5 },
    'manchester-airport': { name: 'Manchester Airport', x: 13.5, y: 62.5 },
    'shaw-and-crompton': { name: 'Shaw and Crompton', x: 38.5, y: 8.5 },
    derker: { name: 'Derker', x: 38, y: 11 },
    'oldham-mumps': { name: 'Oldham Mumps', x: 38, y: 13.5 },
    'oldham-central': { name: 'Oldham Central', x: 38, y: 15.5 },
    'oldham-king-street': { name: 'Oldham King Street', x: 36, y: 17 },
    westwood: { name: 'Westwood', x: 34, y: 17.5 },
    freehold: { name: 'Freehold', x: 32.5, y: 19 },
    'south-chadderton': { name: 'South Chadderton', x: 30.5, y: 21 },
    hollinwood: { name: 'Hollinwood', x: 29, y: 22.5 },
    failsworth: { name: 'Failsworth', x: 27, y: 24.5 },
    'newton-heath-and-moston': { name: 'Newton Heath and Moston', x: 25.5, y: 26 },
    'central-park': { name: 'Central Park', x: 23.5, y: 28 },
    monsall: { name: 'Monsall', x: 21, y: 28 },
    'exchange-square': { name: 'Exchange Square', x: 17.5, y: 31.5 },
    withington: { name: 'Withington', x: 15, y: 46.5 },
    'burton-road': { name: 'Burton Road', x: 16.5, y: 48 },
    'west-didsbury': { name: 'West Didsbury', x: 18, y: 49.5 },
    'didsbury-village': { name: 'Didsbury Village', x: 19.5, y: 51 },
    'east-didsbury': { name: 'East Didsbury', x: 21, y: 52 },
    mediacityuk: { name: 'MediaCityUK', x: 7, y: 36 },
    'rochdale-town-centre': { name: 'Rochdale Town Centre', x: 31, y: 0 },
    'rochdale-railway-station': { name: 'Rochdale Railway Station', x: 32.5, y: 1.5 },
    newbold: { name: 'Newbold', x: 34.5, y: 1.5 },
    'kingsway-business-park': { name: 'Kingsway Business Park', x: 36, y: 3 },
    milnrow: { name: 'Milnrow', x: 37, y: 4.5 },
    newhey: { name: 'Newhey', x: 38.5, y: 6.5 },
    wharfside: { name: 'Wharfside', x: 10, y: 37.5 },
    'imperial-war-museum': { name: 'Imperial War Museum', x: 8, y: 37.5 },
    village: { name: 'Village', x: 6, y: 37.5 },
    parkway: { name: 'Parkway', x: 4, y: 37.5 },
    'trafford-palazzo': { name: 'Trafford Palazzo', x: 2, y: 37.5 },
    'the-trafford-centre': { name: 'The Trafford Centre', x: 0, y: 37.5 },
  },
};
