// Milan's Metropolitana, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'milan',
  name: 'Milan',
  system: 'Metropolitana',
  country: 'Italy',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'm1',
      short: 'M1',
      name: 'Metropolitana M1',
      colour: '#ee333e',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['rho-fieramilano', 'pero', 'molino-dorino', 'san-leonardo', 'bonola', 'uruguay', 'lampugnano', 'qt8', 'lotto', 'amendola', 'buonarroti', 'pagano', 'conciliazione', 'cadorna-fn', 'cairoli', 'cordusio', 'duomo', 'san-babila', 'palestro', 'porta-venezia', 'lima', 'loreto', 'pasteur', 'rovereto', 'turro', 'gorla', 'precotto', 'villa-san-giovanni', 'sesto-marelli', 'sesto-rondo', 'sesto-1-maggio-fs'],
        ['bisceglie', 'inganni', 'primaticcio', 'bande-nere', 'gambara', 'de-angeli', 'wagner', 'pagano', 'conciliazione', 'cadorna-fn', 'cairoli', 'cordusio', 'duomo', 'san-babila', 'palestro', 'porta-venezia', 'lima', 'loreto', 'pasteur', 'rovereto', 'turro', 'gorla', 'precotto', 'villa-san-giovanni', 'sesto-marelli', 'sesto-rondo', 'sesto-1-maggio-fs'],
      ],
    },
    {
      id: 'm2',
      short: 'M2',
      name: 'Metropolitana M2',
      colour: '#5d9842',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['abbiategrasso-chiesa-rossa', 'famagosta', 'romolo', 'porta-genova', 'sant-agostino', 'sant-ambrogio', 'cadorna-fn', 'lanza', 'moscova', 'garibaldi-fs', 'gioia', 'centrale-fs', 'caiazzo', 'loreto', 'piola', 'lambrate-fs', 'udine', 'cimiano', 'crescenzago', 'cascina-gobba', 'vimodrone', 'cascina-burrona', 'cernusco-sul-naviglio', 'villa-fiorita', 'cassina-de-pecchi', 'bussero', 'villa-pompea', 'gorgonzola', 'cascina-antonietta', 'gessate'],
        ['assago-milanofiori-forum', 'assago-milanofiori-nord', 'famagosta', 'romolo', 'porta-genova', 'sant-agostino', 'sant-ambrogio', 'cadorna-fn', 'lanza', 'moscova', 'garibaldi-fs', 'gioia', 'centrale-fs', 'caiazzo', 'loreto', 'piola', 'lambrate-fs', 'udine', 'cimiano', 'crescenzago', 'cascina-gobba', 'cologno-sud', 'cologno-centro', 'cologno-nord'],
        ['abbiategrasso-chiesa-rossa', 'famagosta', 'romolo', 'porta-genova', 'sant-agostino', 'sant-ambrogio', 'cadorna-fn', 'lanza', 'moscova', 'garibaldi-fs', 'gioia', 'centrale-fs', 'caiazzo', 'loreto', 'piola', 'lambrate-fs', 'udine', 'cimiano', 'crescenzago', 'cascina-gobba', 'cologno-sud', 'cologno-centro', 'cologno-nord'],
      ],
    },
    {
      id: 'm3',
      short: 'M3',
      name: 'Metropolitana M3',
      colour: '#febf2e',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['san-donato', 'rogoredo-fs', 'porto-di-mare', 'corvetto', 'brenta', 'lodi-t-i-b-b', 'porta-romana', 'crocetta', 'missori', 'duomo', 'montenapoleone', 'turati', 'repubblica', 'centrale-fs', 'sondrio', 'zara', 'maciachini', 'dergano', 'affori-centro', 'affori-fn', 'comasina'],
      ],
    },
    {
      id: 'm4',
      short: 'M4',
      name: 'Metropolitana M4',
      colour: '#224981',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['linate-aeroporto', 'repetti', 'stazione-forlanini', 'argonne', 'susa', 'dateo', 'tricolore', 'san-babila', 'sforza-policlinico', 'santa-sofia', 'vetra', 'de-amicis', 'sant-ambrogio', 'coni-zugna', 'california', 'bolivar', 'tolstoj', 'frattini', 'gelsomini', 'segneri', 'san-cristoforo'],
      ],
    },
    {
      id: 'm5',
      short: 'M5',
      name: 'Metropolitana M5',
      colour: '#9d91c5',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['san-siro-stadio', 'san-siro-ippodromo', 'segesta', 'lotto', 'portello', 'tre-torri', 'domodossola-fn', 'gerusalemme', 'cenisio', 'monumentale', 'garibaldi-fs', 'isola', 'zara', 'marche', 'istria', 'ca-granda-pratocentenaro', 'bicocca', 'ponale', 'bignami'],
      ],
    },
  ],
  times: {
    'rho-fieramilano pero': 3,
    'amendola buonarroti': 1,
    'buonarroti pagano': 1,
    'pagano conciliazione': 1,
    'cadorna-fn cairoli': 1,
    'cairoli cordusio': 1,
    'cordusio duomo': 1,
    'palestro porta-venezia': 1,
    'rovereto turro': 1,
    'sesto-marelli sesto-rondo': 3,
    'gambara de-angeli': 1,
    'de-angeli wagner': 1,
    'wagner pagano': 1,
    'sant-agostino sant-ambrogio': 1,
    'centrale-fs caiazzo': 1,
    'caiazzo loreto': 1,
    'crescenzago cascina-gobba': 3,
    'cascina-gobba vimodrone': 4,
    'cascina-burrona cernusco-sul-naviglio': 6,
    'villa-fiorita cassina-de-pecchi': 3,
    'villa-pompea gorgonzola': 4,
    'gorgonzola cascina-antonietta': 4,
    'assago-milanofiori-nord famagosta': 7,
    'cascina-gobba cologno-sud': 3,
    'san-donato rogoredo-fs': 3,
    'corvetto brenta': 1,
    'missori duomo': 1,
    'montenapoleone turati': 1,
    'linate-aeroporto repetti': 6,
    'dateo tricolore': 2,
    'tricolore san-babila': 2,
    'san-babila sforza-policlinico': 2,
    'sant-ambrogio coni-zugna': 2,
    'california bolivar': 2,
    'lotto portello': 1,
    'tre-torri domodossola-fn': 1,
    'domodossola-fn gerusalemme': 1,
    'gerusalemme cenisio': 1,
    'monumentale garibaldi-fs': 1,
    'garibaldi-fs isola': 1,
    'isola zara': 1,
    'zara marche': 1,
    'ponale bignami': 1,
  },
  stations: {
    'rho-fieramilano': { name: 'Rho Fieramilano', x: 0, y: 6.5 },
    pero: { name: 'Pero', x: 0, y: 8.5 },
    'molino-dorino': { name: 'Molino Dorino', x: 1.5, y: 10 },
    'san-leonardo': { name: 'San Leonardo', x: 3, y: 11 },
    bonola: { name: 'Bonola', x: 4.5, y: 12.5 },
    uruguay: { name: 'Uruguay', x: 6, y: 14 },
    lampugnano: { name: 'Lampugnano', x: 7.5, y: 15.5 },
    qt8: { name: 'QT8', x: 9, y: 17 },
    lotto: { name: 'Lotto', x: 10.5, y: 18 },
    amendola: { name: 'Amendola', x: 12, y: 19.5 },
    buonarroti: { name: 'Buonarroti', x: 13.5, y: 21 },
    pagano: { name: 'Pagano', x: 15.5, y: 21 },
    conciliazione: { name: 'Conciliazione', x: 16.5, y: 22.5 },
    'cadorna-fn': { name: 'Cadorna FN', x: 18.5, y: 22.5 },
    cairoli: { name: 'Cairoli', x: 21, y: 22 },
    cordusio: { name: 'Cordusio', x: 21, y: 24 },
    duomo: { name: 'Duomo', x: 23, y: 23.5 },
    'san-babila': { name: 'San Babila', x: 25.5, y: 23.5 },
    palestro: { name: 'Palestro', x: 25.5, y: 21.5 },
    'porta-venezia': { name: 'Porta Venezia', x: 27, y: 20 },
    lima: { name: 'Lima', x: 28.5, y: 19 },
    loreto: { name: 'Loreto', x: 30, y: 17.5 },
    pasteur: { name: 'Pasteur', x: 30, y: 15.5 },
    rovereto: { name: 'Rovereto', x: 30, y: 13.5 },
    turro: { name: 'Turro', x: 30, y: 11.5 },
    gorla: { name: 'Gorla', x: 30, y: 9.5 },
    precotto: { name: 'Precotto', x: 30, y: 7.5 },
    'villa-san-giovanni': { name: 'Villa San Giovanni', x: 30, y: 5.5 },
    'sesto-marelli': { name: 'Sesto Marelli', x: 30, y: 3.5 },
    'sesto-rondo': { name: 'Sesto Rondò', x: 30, y: 1.5 },
    'sesto-1-maggio-fs': { name: 'Sesto 1º Maggio FS', x: 31.5, y: 0 },
    bisceglie: { name: 'Bisceglie', x: 2.5, y: 24.5 },
    inganni: { name: 'Inganni', x: 4.5, y: 24.5 },
    primaticcio: { name: 'Primaticcio', x: 6.5, y: 24.5 },
    'bande-nere': { name: 'Bande Nere', x: 8.5, y: 24.5 },
    gambara: { name: 'Gambara', x: 10, y: 23 },
    'de-angeli': { name: 'De Angeli', x: 12, y: 22.5 },
    wagner: { name: 'Wagner', x: 14, y: 22.5 },
    'abbiategrasso-chiesa-rossa': { name: 'Abbiategrasso-Chiesa Rossa', x: 19, y: 33 },
    famagosta: { name: 'Famagosta', x: 17, y: 33 },
    romolo: { name: 'Romolo', x: 17, y: 31 },
    'porta-genova': { name: 'Porta Genova', x: 17, y: 28.5 },
    'sant-agostino': { name: 'Sant\'Agostino', x: 17, y: 26.5 },
    'sant-ambrogio': { name: 'Sant\'Ambrogio', x: 17, y: 24.5 },
    lanza: { name: 'Lanza', x: 20, y: 21 },
    moscova: { name: 'Moscova', x: 21.5, y: 19.5 },
    'garibaldi-fs': { name: 'Garibaldi FS', x: 21.5, y: 17 },
    gioia: { name: 'Gioia', x: 24, y: 17 },
    'centrale-fs': { name: 'Centrale FS', x: 26, y: 16.5 },
    caiazzo: { name: 'Caiazzo', x: 28.5, y: 16.5 },
    piola: { name: 'Piola', x: 32.5, y: 17 },
    'lambrate-fs': { name: 'Lambrate FS', x: 34.5, y: 15 },
    udine: { name: 'Udine', x: 36.5, y: 13.5 },
    cimiano: { name: 'Cimiano', x: 38.5, y: 11.5 },
    crescenzago: { name: 'Crescenzago', x: 40.5, y: 10 },
    'cascina-gobba': { name: 'Cascina Gobba', x: 42.5, y: 8 },
    vimodrone: { name: 'Vimodrone', x: 45, y: 7.5 },
    'cascina-burrona': { name: 'Cascina Burrona', x: 48, y: 7.5 },
    'cernusco-sul-naviglio': { name: 'Cernusco sul Naviglio', x: 50.5, y: 7 },
    'villa-fiorita': { name: 'Villa Fiorita', x: 53, y: 7 },
    'cassina-de-pecchi': { name: 'Cassina de\' Pecchi', x: 55.5, y: 6.5 },
    bussero: { name: 'Bussero', x: 58, y: 6.5 },
    'villa-pompea': { name: 'Villa Pompea', x: 60.5, y: 6 },
    gorgonzola: { name: 'Gorgonzola', x: 62, y: 4.5 },
    'cascina-antonietta': { name: 'Cascina Antonietta', x: 64, y: 3 },
    gessate: { name: 'Gessate', x: 66, y: 3 },
    'cologno-sud': { name: 'Cologno Sud', x: 42.5, y: 6 },
    'cologno-centro': { name: 'Cologno Centro', x: 44, y: 4.5 },
    'cologno-nord': { name: 'Cologno Nord', x: 45.5, y: 3 },
    'san-donato': { name: 'San Donato', x: 34.5, y: 35 },
    'rogoredo-fs': { name: 'Rogoredo FS', x: 32.5, y: 35 },
    'porto-di-mare': { name: 'Porto di Mare', x: 31, y: 33.5 },
    corvetto: { name: 'Corvetto', x: 30, y: 32.5 },
    brenta: { name: 'Brenta', x: 28.5, y: 31 },
    'lodi-t-i-b-b': { name: 'Lodi T.I.B.B.', x: 27, y: 29.5 },
    'porta-romana': { name: 'Porta Romana', x: 25.5, y: 28 },
    crocetta: { name: 'Crocetta', x: 24, y: 26.5 },
    missori: { name: 'Missori', x: 22.5, y: 25 },
    montenapoleone: { name: 'Montenapoleone', x: 23, y: 21.5 },
    turati: { name: 'Turati', x: 23, y: 19.5 },
    repubblica: { name: 'Repubblica', x: 24.5, y: 18 },
    sondrio: { name: 'Sondrio', x: 24.5, y: 15 },
    zara: { name: 'Zara', x: 23, y: 13.5 },
    maciachini: { name: 'Maciachini', x: 21.5, y: 12 },
    dergano: { name: 'Dergano', x: 20, y: 10.5 },
    'affori-centro': { name: 'Affori Centro', x: 18.5, y: 9.5 },
    'affori-fn': { name: 'Affori FN', x: 17, y: 8 },
    comasina: { name: 'Comasina', x: 16, y: 6.5 },
    'san-siro-stadio': { name: 'San Siro Stadio', x: 5, y: 19.5 },
    'san-siro-ippodromo': { name: 'San Siro Ippodromo', x: 7, y: 19.5 },
    segesta: { name: 'Segesta', x: 9, y: 19.5 },
    portello: { name: 'Portello', x: 12.5, y: 18 },
    'tre-torri': { name: 'Tre Torri', x: 14, y: 19.5 },
    'domodossola-fn': { name: 'Domodossola FN', x: 15.5, y: 17.5 },
    gerusalemme: { name: 'Gerusalemme', x: 17, y: 16 },
    cenisio: { name: 'Cenisio', x: 18.5, y: 14.5 },
    monumentale: { name: 'Monumentale', x: 20, y: 16 },
    isola: { name: 'Isola', x: 23, y: 15.5 },
    marche: { name: 'Marche', x: 24.5, y: 12.5 },
    istria: { name: 'Istria', x: 24.5, y: 10.5 },
    'ca-granda-pratocentenaro': { name: 'Ca\' Granda - Pratocentenaro', x: 24.5, y: 8.5 },
    bicocca: { name: 'Bicocca', x: 24.5, y: 6.5 },
    ponale: { name: 'Ponale', x: 24.5, y: 4.5 },
    bignami: { name: 'Bignami', x: 24.5, y: 2.5 },
    'assago-milanofiori-forum': { name: 'Assago Milanofiori Forum', x: 14, y: 36 },
    'assago-milanofiori-nord': { name: 'Assago Milanofiori Nord', x: 15.5, y: 34.5 },
    'linate-aeroporto': { name: 'Linate Aeroporto', x: 38.5, y: 25 },
    repetti: { name: 'Repetti', x: 36.5, y: 25 },
    'stazione-forlanini': { name: 'Stazione Forlanini', x: 34.5, y: 25 },
    argonne: { name: 'Argonne', x: 33, y: 23.5 },
    susa: { name: 'Susa', x: 31, y: 23.5 },
    dateo: { name: 'Dateo', x: 29, y: 23.5 },
    tricolore: { name: 'Tricolore', x: 27, y: 23.5 },
    'sforza-policlinico': { name: 'Sforza-Policlinico', x: 24, y: 25 },
    'santa-sofia': { name: 'Santa Sofia', x: 22.5, y: 26.5 },
    vetra: { name: 'Vetra', x: 20.5, y: 26 },
    'de-amicis': { name: 'De Amicis', x: 18.5, y: 26 },
    'coni-zugna': { name: 'Coni Zugna', x: 15, y: 24.5 },
    california: { name: 'California', x: 15, y: 26.5 },
    bolivar: { name: 'Bolivar', x: 13.5, y: 26.5 },
    tolstoj: { name: 'Tolstoj', x: 12, y: 27.5 },
    frattini: { name: 'Frattini', x: 10.5, y: 29 },
    gelsomini: { name: 'Gelsomini', x: 8.5, y: 29 },
    segneri: { name: 'Segneri', x: 7, y: 30.5 },
    'san-cristoforo': { name: 'San Cristoforo', x: 7, y: 32.5 },
  },
};
