// Montreal's Métro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'montreal',
  name: 'Montreal',
  system: 'Métro',
  country: 'Canada',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Ligne verte',
      colour: '#069037',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['angrignon', 'monk', 'jolicoeur', 'verdun', 'de-l-eglise', 'lasalle', 'charlevoix', 'lionel-groulx', 'atwater', 'guy-concordia', 'peel', 'mcgill', 'place-des-arts', 'saint-laurent', 'berri-uqam', 'beaudry', 'papineau', 'frontenac', 'prefontaine', 'joliette', 'pie-ix', 'viau', 'assomption', 'cadillac', 'langelier', 'radisson', 'honore-beaugrand'],
      ],
    },
    {
      id: '2',
      short: '2',
      name: 'Ligne orange',
      colour: '#d06d07',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['cote-vertu', 'du-college', 'de-la-savane', 'namur', 'plamondon', 'cote-sainte-catherine', 'snowdon', 'villa-maria', 'vendome', 'place-saint-henri', 'lionel-groulx', 'georges-vanier', 'lucien-l-allier', 'bonaventure', 'square-victoria-oaci', 'place-d-armes', 'champ-de-mars', 'berri-uqam', 'sherbrooke', 'mont-royal', 'laurier', 'rosemont', 'beaubien', 'jean-talon', 'jarry', 'cremazie', 'sauve', 'henri-bourassa', 'cartier', 'de-la-concorde', 'montmorency'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'Ligne jaune',
      colour: '#f1ce00',
      text: '#1a1a1a',
      minutes: 4,
      branches: [
        ['longueuil-universite-de-sherbrooke', 'jean-drapeau', 'berri-uqam'],
      ],
    },
    {
      id: '5',
      short: '5',
      name: 'Ligne bleue',
      colour: '#3465b4',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['snowdon', 'cote-des-neiges', 'universite-de-montreal', 'edouard-montpetit', 'outremont', 'acadie', 'parc', 'de-castelnau', 'jean-talon', 'fabre', 'd-iberville', 'saint-michel'],
      ],
    },
  ],
  times: {
    'monk jolicoeur': 3,
    'peel mcgill': 1,
    'mcgill place-des-arts': 1,
    'place-des-arts saint-laurent': 1,
    'saint-laurent berri-uqam': 1,
    'du-college de-la-savane': 3,
    'namur plamondon': 3,
    'plamondon cote-sainte-catherine': 1,
    'villa-maria vendome': 3,
    'vendome place-saint-henri': 3,
    'lucien-l-allier bonaventure': 1,
    'bonaventure square-victoria-oaci': 1,
    'square-victoria-oaci place-d-armes': 1,
    'place-d-armes champ-de-mars': 1,
    'berri-uqam sherbrooke': 1,
    'sherbrooke mont-royal': 3,
    'jean-talon jarry': 3,
    'cremazie sauve': 3,
    'henri-bourassa cartier': 3,
    'cartier de-la-concorde': 4,
    'jean-drapeau berri-uqam': 5,
    'snowdon cote-des-neiges': 3,
    'edouard-montpetit outremont': 3,
  },
  stations: {
    angrignon: { name: 'Angrignon', x: 18, y: 40.5 },
    monk: { name: 'Monk', x: 19, y: 39 },
    jolicoeur: { name: 'Jolicoeur', x: 20.5, y: 37.5 },
    verdun: { name: 'Verdun', x: 22, y: 36 },
    'de-l-eglise': { name: 'De l\'Église', x: 23.5, y: 34.5 },
    lasalle: { name: 'LaSalle', x: 23.5, y: 32.5 },
    charlevoix: { name: 'Charlevoix', x: 22, y: 31 },
    'lionel-groulx': { name: 'Lionel-Groulx', x: 20, y: 31 },
    atwater: { name: 'Atwater', x: 18.5, y: 29.5 },
    'guy-concordia': { name: 'Guy-Concordia', x: 19.5, y: 28 },
    peel: { name: 'Peel', x: 20.5, y: 26.5 },
    mcgill: { name: 'McGill', x: 22, y: 25.5 },
    'place-des-arts': { name: 'Place-des-Arts', x: 22, y: 23.5 },
    'saint-laurent': { name: 'Saint-Laurent', x: 23.5, y: 22 },
    'berri-uqam': { name: 'Berri-UQAM', x: 25, y: 21 },
    beaudry: { name: 'Beaudry', x: 24, y: 19.5 },
    papineau: { name: 'Papineau', x: 25.5, y: 18.5 },
    frontenac: { name: 'Frontenac', x: 25.5, y: 16.5 },
    prefontaine: { name: 'Préfontaine', x: 25.5, y: 14.5 },
    joliette: { name: 'Joliette', x: 25.5, y: 12.5 },
    'pie-ix': { name: 'Pie IX', x: 25.5, y: 10.5 },
    viau: { name: 'Viau', x: 27, y: 9.5 },
    assomption: { name: 'Assomption', x: 27, y: 7.5 },
    cadillac: { name: 'Cadillac', x: 27, y: 5.5 },
    langelier: { name: 'Langelier', x: 28.5, y: 4 },
    radisson: { name: 'Radisson', x: 28.5, y: 2 },
    'honore-beaugrand': { name: 'Honoré-Beaugrand', x: 28.5, y: 0 },
    'cote-vertu': { name: 'Côte-Vertu', x: 3.5, y: 23.5 },
    'du-college': { name: 'Du Collège', x: 5, y: 25 },
    'de-la-savane': { name: 'De La Savane', x: 6.5, y: 26.5 },
    namur: { name: 'Namur', x: 8, y: 27.5 },
    plamondon: { name: 'Plamondon', x: 10, y: 28 },
    'cote-sainte-catherine': { name: 'Côte-Sainte-Catherine', x: 12, y: 28 },
    snowdon: { name: 'Snowdon', x: 13.5, y: 29 },
    'villa-maria': { name: 'Villa-Maria', x: 15, y: 31 },
    vendome: { name: 'Vendôme', x: 16.5, y: 32.5 },
    'place-saint-henri': { name: 'Place Saint-Henri', x: 18.5, y: 32.5 },
    'georges-vanier': { name: 'Georges-Vanier', x: 20, y: 29.5 },
    'lucien-l-allier': { name: 'Lucien-L\'Allier', x: 21.5, y: 28 },
    bonaventure: { name: 'Bonaventure', x: 23, y: 26.5 },
    'square-victoria-oaci': { name: 'Square-Victoria-OACI', x: 24.5, y: 25 },
    'place-d-armes': { name: 'Place d’Armes', x: 23.5, y: 23.5 },
    'champ-de-mars': { name: 'Champ-de-Mars', x: 25, y: 23.5 },
    sherbrooke: { name: 'Sherbrooke', x: 22.5, y: 21 },
    'mont-royal': { name: 'Mont-Royal', x: 21, y: 19.5 },
    laurier: { name: 'Laurier', x: 19.5, y: 18.5 },
    rosemont: { name: 'Rosemont', x: 18, y: 17 },
    beaubien: { name: 'Beaubien', x: 16.5, y: 15.5 },
    'jean-talon': { name: 'Jean-Talon', x: 15, y: 14 },
    jarry: { name: 'Jarry', x: 12.5, y: 14 },
    cremazie: { name: 'Crémazie', x: 10.5, y: 14 },
    sauve: { name: 'Sauvé', x: 8.5, y: 14 },
    'henri-bourassa': { name: 'Henri-Bourassa', x: 6, y: 13.5 },
    cartier: { name: 'Cartier', x: 4, y: 13.5 },
    'de-la-concorde': { name: 'De la Concorde', x: 2, y: 13.5 },
    montmorency: { name: 'Montmorency', x: 0, y: 13.5 },
    'longueuil-universite-de-sherbrooke': { name: 'Longueuil–Université-de-Sherbrooke', x: 28.5, y: 19.5 },
    'jean-drapeau': { name: 'Jean-Drapeau', x: 27, y: 21 },
    'cote-des-neiges': { name: 'Côte-des-Neiges', x: 13.5, y: 27 },
    'universite-de-montreal': { name: 'Université-de-Montréal', x: 15, y: 25.5 },
    'edouard-montpetit': { name: 'Édouard-Montpetit', x: 15, y: 23.5 },
    outremont: { name: 'Outremont', x: 15, y: 21.5 },
    acadie: { name: 'Acadie', x: 13.5, y: 20 },
    parc: { name: 'Parc', x: 13.5, y: 17.5 },
    'de-castelnau': { name: 'De Castelnau', x: 15, y: 16 },
    fabre: { name: 'Fabre', x: 16, y: 13 },
    'd-iberville': { name: 'D’Iberville', x: 17.5, y: 11.5 },
    'saint-michel': { name: 'Saint-Michel', x: 17.5, y: 9.5 },
  },
};
