// Munich's U-Bahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'munich',
  name: 'Munich',
  system: 'U-Bahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'u1',
      short: 'U1',
      name: 'U-Bahn U1',
      colour: '#46b450',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['mangfallplatz', 'sankt-quirin-platz', 'wettersteinplatz', 'candidplatz', 'kolumbusplatz', 'fraunhoferstrasse', 'sendlinger-tor', 'hauptbahnhof', 'stiglmaierplatz', 'maillingerstrasse', 'rotkreuzplatz', 'gern', 'westfriedhof', 'georg-brauchle-ring', 'olympia-einkaufszentrum'],
      ],
    },
    {
      id: 'u2',
      short: 'U2',
      name: 'U-Bahn U2',
      colour: '#b4283c',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['feldmoching', 'hasenbergl', 'dulferstrasse', 'harthof', 'am-hart', 'frankfurter-ring', 'milbertshofen', 'scheidplatz', 'hohenzollernplatz', 'josephsplatz', 'theresienstrasse', 'konigsplatz', 'hauptbahnhof', 'sendlinger-tor', 'fraunhoferstrasse', 'kolumbusplatz', 'silberhornstrasse', 'untersbergstrasse', 'giesing', 'karl-preis-platz', 'innsbrucker-ring', 'josephsburg', 'kreillerstrasse', 'trudering', 'moosfeld', 'messestadt-west', 'messestadt-ost'],
      ],
    },
    {
      id: 'u3',
      short: 'U3',
      name: 'U-Bahn U3',
      colour: '#e66432',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['furstenried-west', 'basler-strasse', 'forstenrieder-allee', 'machtlfinger-strasse', 'aidenbachstrasse', 'obersendling', 'thalkirchen-tierpark', 'brudermuhlstrasse', 'implerstrasse', 'poccistrasse', 'goetheplatz', 'sendlinger-tor', 'marienplatz', 'odeonsplatz', 'universitat', 'giselastrasse', 'munchner-freiheit', 'bonner-platz', 'scheidplatz', 'petuelring', 'olympiazentrum', 'oberwiesenfeld', 'olympia-einkaufszentrum', 'moosacher-st-martins-platz', 'moosach'],
      ],
    },
    {
      id: 'u4',
      short: 'U4',
      name: 'U-Bahn U4',
      colour: '#00a082',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['arabellapark', 'richard-strauss-strasse', 'bohmerwaldplatz', 'prinzregentenplatz', 'max-weber-platz', 'lehel', 'odeonsplatz', 'karlsplatz-stachus', 'hauptbahnhof', 'theresienwiese', 'schwanthalerhohe', 'heimeranplatz', 'westendstrasse'],
      ],
    },
    {
      id: 'u5',
      short: 'U5',
      name: 'U-Bahn U5',
      colour: '#a06e1e',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['laimer-platz', 'friedenheimer-strasse', 'westendstrasse', 'heimeranplatz', 'schwanthalerhohe', 'theresienwiese', 'hauptbahnhof', 'karlsplatz-stachus', 'odeonsplatz', 'lehel', 'max-weber-platz', 'ostbahnhof', 'innsbrucker-ring', 'michaelibad', 'quiddestrasse', 'neuperlach-zentrum', 'therese-giehse-allee', 'neuperlach-sud'],
      ],
    },
    {
      id: 'u6',
      short: 'U6',
      name: 'U-Bahn U6',
      colour: '#005a96',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['garching-forschungszentrum', 'garching', 'garching-hochbruck-u', 'frottmaning', 'kieferngarten', 'freimann', 'studentenstadt', 'alte-heide', 'nordfriedhof', 'dietlindenstrasse', 'munchner-freiheit', 'giselastrasse', 'universitat', 'odeonsplatz', 'marienplatz', 'sendlinger-tor', 'goetheplatz', 'poccistrasse', 'implerstrasse', 'harras', 'partnachplatz', 'westpark', 'holzapfelkreuth', 'haderner-stern', 'grosshadern', 'klinikum-grosshadern'],
      ],
    },
    {
      id: 'u7',
      short: 'U7',
      name: 'U-Bahn U7',
      colour: '#46b450',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['neuperlach-zentrum', 'quiddestrasse', 'michaelibad', 'innsbrucker-ring', 'karl-preis-platz', 'giesing', 'untersbergstrasse', 'silberhornstrasse', 'kolumbusplatz', 'fraunhoferstrasse', 'sendlinger-tor', 'hauptbahnhof', 'stiglmaierplatz', 'maillingerstrasse', 'rotkreuzplatz', 'gern', 'westfriedhof', 'georg-brauchle-ring', 'olympia-einkaufszentrum'],
      ],
    },
    {
      id: 'u8',
      short: 'U8',
      name: 'U-Bahn U8',
      colour: '#b4283c',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['olympiazentrum', 'petuelring', 'scheidplatz', 'hohenzollernplatz', 'josephsplatz', 'theresienstrasse', 'konigsplatz', 'hauptbahnhof', 'sendlinger-tor', 'fraunhoferstrasse', 'kolumbusplatz', 'silberhornstrasse', 'untersbergstrasse', 'giesing', 'karl-preis-platz', 'innsbrucker-ring', 'michaelibad', 'quiddestrasse', 'neuperlach-zentrum'],
      ],
    },
  ],
  times: {
    'josephsplatz theresienstrasse': 1,
    'silberhornstrasse untersbergstrasse': 1,
    'giesing karl-preis-platz': 3,
    'innsbrucker-ring josephsburg': 3,
    'kreillerstrasse trudering': 3,
    'moosfeld messestadt-west': 3,
    'forstenrieder-allee machtlfinger-strasse': 3,
    'giselastrasse munchner-freiheit': 1,
    'oberwiesenfeld olympia-einkaufszentrum': 3,
    'richard-strauss-strasse bohmerwaldplatz': 1,
    'karlsplatz-stachus hauptbahnhof': 1,
    'hauptbahnhof karlsplatz-stachus': 1,
    'ostbahnhof innsbrucker-ring': 3,
    'michaelibad quiddestrasse': 3,
    'garching-forschungszentrum garching': 5,
    'garching garching-hochbruck-u': 3,
    'garching-hochbruck-u frottmaning': 8,
    'kieferngarten freimann': 3,
    'munchner-freiheit giselastrasse': 1,
    'quiddestrasse michaelibad': 3,
    'karl-preis-platz giesing': 3,
    'untersbergstrasse silberhornstrasse': 1,
  },
  stations: {
    arabellapark: { name: 'Arabellapark', x: 26.5, y: 20.5 },
    'richard-strauss-strasse': { name: 'Richard-Strauss-Straße', x: 25, y: 21.5 },
    bohmerwaldplatz: { name: 'Böhmerwaldplatz', x: 25, y: 23.5 },
    prinzregentenplatz: { name: 'Prinzregentenplatz', x: 24, y: 25 },
    'max-weber-platz': { name: 'Max-Weber-Platz', x: 22.5, y: 26.5 },
    lehel: { name: 'Lehel', x: 21, y: 25 },
    odeonsplatz: { name: 'Odeonsplatz', x: 19.5, y: 24 },
    'karlsplatz-stachus': { name: 'Karlsplatz (Stachus)', x: 17.5, y: 24 },
    hauptbahnhof: { name: 'Hauptbahnhof', x: 15.5, y: 24 },
    theresienwiese: { name: 'Theresienwiese', x: 14, y: 25.5 },
    schwanthalerhohe: { name: 'Schwanthalerhöhe', x: 12, y: 25.5 },
    heimeranplatz: { name: 'Heimeranplatz', x: 10, y: 25.5 },
    westendstrasse: { name: 'Westendstraße', x: 8, y: 25.5 },
    'laimer-platz': { name: 'Laimer Platz', x: 4, y: 25.5 },
    'friedenheimer-strasse': { name: 'Friedenheimer Straße', x: 6, y: 25.5 },
    ostbahnhof: { name: 'Ostbahnhof', x: 24, y: 28 },
    'innsbrucker-ring': { name: 'Innsbrucker Ring', x: 25.5, y: 29 },
    michaelibad: { name: 'Michaelibad', x: 27, y: 30.5 },
    quiddestrasse: { name: 'Quiddestraße', x: 28.5, y: 32 },
    'neuperlach-zentrum': { name: 'Neuperlach Zentrum', x: 28.5, y: 34 },
    'therese-giehse-allee': { name: 'Therese-Giehse-Allee', x: 28.5, y: 36 },
    'neuperlach-sud': { name: 'Neuperlach Süd', x: 28.5, y: 38 },
    'garching-forschungszentrum': { name: 'Garching-Forschungszentrum', x: 30, y: 0 },
    garching: { name: 'Garching', x: 28.5, y: 1.5 },
    'garching-hochbruck-u': { name: 'Garching-Hochbrück (U)', x: 27, y: 3 },
    frottmaning: { name: 'Fröttmaning', x: 25.5, y: 4.5 },
    kieferngarten: { name: 'Kieferngarten', x: 25.5, y: 7 },
    freimann: { name: 'Freimann', x: 25.5, y: 9 },
    studentenstadt: { name: 'Studentenstadt', x: 25.5, y: 11 },
    'alte-heide': { name: 'Alte Heide', x: 24, y: 13 },
    nordfriedhof: { name: 'Nordfriedhof', x: 22.5, y: 14.5 },
    dietlindenstrasse: { name: 'Dietlindenstraße', x: 21, y: 16 },
    'munchner-freiheit': { name: 'Münchner Freiheit', x: 21, y: 18 },
    giselastrasse: { name: 'Giselastraße', x: 19.5, y: 19.5 },
    universitat: { name: 'Universität', x: 19.5, y: 21.5 },
    marienplatz: { name: 'Marienplatz', x: 19, y: 25.5 },
    'sendlinger-tor': { name: 'Sendlinger Tor', x: 17, y: 25.5 },
    goetheplatz: { name: 'Goetheplatz', x: 15.5, y: 27 },
    poccistrasse: { name: 'Poccistraße', x: 13.5, y: 28.5 },
    implerstrasse: { name: 'Implerstraße', x: 13.5, y: 30.5 },
    harras: { name: 'Harras', x: 11.5, y: 30.5 },
    partnachplatz: { name: 'Partnachplatz', x: 9.5, y: 30.5 },
    westpark: { name: 'Westpark', x: 7.5, y: 30.5 },
    holzapfelkreuth: { name: 'Holzapfelkreuth', x: 5.5, y: 30.5 },
    'haderner-stern': { name: 'Haderner Stern', x: 3.5, y: 30.5 },
    grosshadern: { name: 'Großhadern', x: 1.5, y: 30.5 },
    'klinikum-grosshadern': { name: 'Klinikum Großhadern', x: 0, y: 32 },
    'furstenried-west': { name: 'Fürstenried West', x: 3, y: 39 },
    'basler-strasse': { name: 'Basler Straße', x: 4.5, y: 37.5 },
    'forstenrieder-allee': { name: 'Forstenrieder Allee', x: 5.5, y: 36 },
    'machtlfinger-strasse': { name: 'Machtlfinger Straße', x: 8, y: 36 },
    aidenbachstrasse: { name: 'Aidenbachstraße', x: 10, y: 36 },
    obersendling: { name: 'Obersendling', x: 12, y: 36 },
    'thalkirchen-tierpark': { name: 'Thalkirchen (Tierpark)', x: 13.5, y: 34.5 },
    brudermuhlstrasse: { name: 'Brudermühlstraße', x: 13.5, y: 32.5 },
    'bonner-platz': { name: 'Bonner Platz', x: 19.5, y: 17 },
    scheidplatz: { name: 'Scheidplatz', x: 17.5, y: 15.5 },
    petuelring: { name: 'Petuelring', x: 16, y: 14 },
    olympiazentrum: { name: 'Olympiazentrum', x: 14.5, y: 13 },
    oberwiesenfeld: { name: 'Oberwiesenfeld', x: 13, y: 11.5 },
    'olympia-einkaufszentrum': { name: 'Olympia-Einkaufszentrum', x: 11, y: 11.5 },
    'moosacher-st-martins-platz': { name: 'Moosacher St.-Martins-Platz', x: 9, y: 11.5 },
    moosach: { name: 'Moosach', x: 7, y: 11.5 },
    feldmoching: { name: 'Feldmoching', x: 12, y: 6 },
    hasenbergl: { name: 'Hasenbergl', x: 14, y: 6 },
    dulferstrasse: { name: 'Dülferstraße', x: 16, y: 6 },
    harthof: { name: 'Harthof', x: 17.5, y: 7.5 },
    'am-hart': { name: 'Am Hart', x: 17.5, y: 9.5 },
    'frankfurter-ring': { name: 'Frankfurter Ring', x: 17.5, y: 11.5 },
    milbertshofen: { name: 'Milbertshofen', x: 17.5, y: 13.5 },
    hohenzollernplatz: { name: 'Hohenzollernplatz', x: 17.5, y: 17.5 },
    josephsplatz: { name: 'Josephsplatz', x: 18, y: 19.5 },
    theresienstrasse: { name: 'Theresienstraße', x: 16.5, y: 20.5 },
    konigsplatz: { name: 'Königsplatz', x: 16.5, y: 22.5 },
    fraunhoferstrasse: { name: 'Fraunhoferstraße', x: 18.5, y: 27 },
    kolumbusplatz: { name: 'Kolumbusplatz', x: 18.5, y: 29 },
    silberhornstrasse: { name: 'Silberhornstraße', x: 18.5, y: 30.5 },
    untersbergstrasse: { name: 'Untersbergstraße', x: 20, y: 32 },
    giesing: { name: 'Giesing', x: 22.5, y: 32 },
    'karl-preis-platz': { name: 'Karl-Preis-Platz', x: 24, y: 30.5 },
    josephsburg: { name: 'Josephsburg', x: 27.5, y: 29 },
    kreillerstrasse: { name: 'Kreillerstraße', x: 29.5, y: 29 },
    trudering: { name: 'Trudering', x: 31.5, y: 29 },
    moosfeld: { name: 'Moosfeld', x: 33.5, y: 29 },
    'messestadt-west': { name: 'Messestadt West', x: 36, y: 29 },
    'messestadt-ost': { name: 'Messestadt Ost', x: 38, y: 29 },
    mangfallplatz: { name: 'Mangfallplatz', x: 20, y: 35.5 },
    'sankt-quirin-platz': { name: 'Sankt-Quirin-Platz', x: 20, y: 33.5 },
    wettersteinplatz: { name: 'Wettersteinplatz', x: 18.5, y: 32 },
    candidplatz: { name: 'Candidplatz', x: 17, y: 30.5 },
    stiglmaierplatz: { name: 'Stiglmaierplatz', x: 15, y: 22 },
    maillingerstrasse: { name: 'Maillingerstraße', x: 14, y: 20.5 },
    rotkreuzplatz: { name: 'Rotkreuzplatz', x: 12.5, y: 19 },
    gern: { name: 'Gern', x: 11, y: 18 },
    westfriedhof: { name: 'Westfriedhof', x: 11, y: 15.5 },
    'georg-brauchle-ring': { name: 'Georg-Brauchle-Ring', x: 11, y: 13.5 },
  },
};
