// Nuremberg's U-Bahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'nuremberg',
  name: 'Nuremberg',
  system: 'U-Bahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'u1',
      short: 'U1',
      name: 'U-Bahn U1',
      colour: '#000066',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['furth-hardhohe', 'furth-klinikum', 'furth-stadthalle', 'furth-rathaus', 'furth-hauptbahnhof', 'furth-jakobinenstrasse', 'stadtgrenze', 'muggenhof', 'eberhardshof', 'maximilianstrasse', 'barenschanze', 'gostenhof', 'plarrer', 'weisser-turm', 'lorenzkirche', 'hauptbahnhof', 'aufsessplatz', 'maffeiplatz', 'frankenstrasse', 'hasenbuck', 'bauernfeindstrasse', 'messe', 'langwasser-nord', 'scharfreiterring', 'langwasser-mitte', 'gemeinschaftshaus', 'langwasser-sud'],
      ],
    },
    {
      id: 'u2',
      short: 'U2',
      name: 'U-Bahn U2',
      colour: '#e3000f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['rothenbach', 'hohe-marter', 'schweinau', 'st-leonhard', 'rothenburger-strasse', 'plarrer', 'opernhaus', 'hauptbahnhof', 'wohrder-wiese', 'rathenauplatz', 'rennweg', 'schoppershof', 'nordostbahnhof', 'herrnhutte', 'ziegelstein', 'flughafen'],
      ],
    },
    {
      id: 'u3',
      short: 'U3',
      name: 'U-Bahn U3',
      colour: '#00868b',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['grossreuth-bei-schweinau', 'gustav-adolf-strasse', 'sundersbuhl', 'rothenburger-strasse', 'plarrer', 'opernhaus', 'hauptbahnhof', 'wohrder-wiese', 'rathenauplatz', 'maxfeld', 'kaulbachplatz', 'friedrich-ebert-platz', 'klinikum-nord', 'nordwestring'],
      ],
    },
  ],
  times: {
    'barenschanze gostenhof': 1,
    'plarrer weisser-turm': 1,
    'weisser-turm lorenzkirche': 1,
    'lorenzkirche hauptbahnhof': 1,
    'hasenbuck bauernfeindstrasse': 3,
    'bauernfeindstrasse messe': 1,
    'langwasser-nord scharfreiterring': 1,
    'langwasser-mitte gemeinschaftshaus': 1,
    'gemeinschaftshaus langwasser-sud': 1,
    'rothenbach hohe-marter': 3,
    'schweinau st-leonhard': 1,
    'opernhaus hauptbahnhof': 1,
    'wohrder-wiese rathenauplatz': 1,
    'rathenauplatz rennweg': 1,
    'ziegelstein flughafen': 5,
    'maxfeld kaulbachplatz': 1,
    'kaulbachplatz friedrich-ebert-platz': 1,
    'friedrich-ebert-platz klinikum-nord': 1,
  },
  stations: {
    'furth-hardhohe': { name: 'Fürth Hardhöhe', x: 0, y: 0.5 },
    'furth-klinikum': { name: 'Fürth Klinikum', x: 2, y: 0.5 },
    'furth-stadthalle': { name: 'Fürth-Stadthalle', x: 4, y: 0.5 },
    'furth-rathaus': { name: 'Fürth Rathaus', x: 5.5, y: 1.5 },
    'furth-hauptbahnhof': { name: 'Fürth Hauptbahnhof', x: 7, y: 3 },
    'furth-jakobinenstrasse': { name: 'Fürth Jakobinenstraße', x: 8.5, y: 4.5 },
    stadtgrenze: { name: 'Stadtgrenze', x: 10, y: 5.5 },
    muggenhof: { name: 'Muggenhof', x: 12, y: 7 },
    eberhardshof: { name: 'Eberhardshof', x: 13.5, y: 8.5 },
    maximilianstrasse: { name: 'Maximilianstraße', x: 15, y: 9.5 },
    barenschanze: { name: 'Bärenschanze', x: 16.5, y: 11 },
    gostenhof: { name: 'Gostenhof', x: 18, y: 12 },
    plarrer: { name: 'Plärrer', x: 19.5, y: 13.5 },
    'weisser-turm': { name: 'Weißer Turm', x: 21, y: 12 },
    lorenzkirche: { name: 'Lorenzkirche', x: 22.5, y: 12 },
    hauptbahnhof: { name: 'Hauptbahnhof', x: 24, y: 13.5, aka: ['Nürnberg Hauptbahnhof'] },
    aufsessplatz: { name: 'Aufseßplatz', x: 24, y: 15.5 },
    maffeiplatz: { name: 'Maffeiplatz', x: 25.5, y: 17 },
    frankenstrasse: { name: 'Frankenstraße', x: 25.5, y: 19 },
    hasenbuck: { name: 'Hasenbuck', x: 27, y: 20 },
    bauernfeindstrasse: { name: 'Bauernfeindstraße', x: 28.5, y: 21.5 },
    messe: { name: 'Messe', x: 30, y: 23 },
    'langwasser-nord': { name: 'Langwasser Nord', x: 31.5, y: 24.5 },
    scharfreiterring: { name: 'Scharfreiterring', x: 33, y: 25.5 },
    'langwasser-mitte': { name: 'Langwasser Mitte', x: 34.5, y: 27 },
    gemeinschaftshaus: { name: 'Gemeinschaftshaus', x: 34.5, y: 29 },
    'langwasser-sud': { name: 'Langwasser Süd', x: 36, y: 30.5 },
    rothenbach: { name: 'Röthenbach', x: 13.5, y: 20 },
    'hohe-marter': { name: 'Hohe Marter', x: 15, y: 18.5 },
    schweinau: { name: 'Schweinau', x: 16, y: 17 },
    'st-leonhard': { name: 'St. Leonhard', x: 16, y: 15 },
    'rothenburger-strasse': { name: 'Rothenburger Straße', x: 17.5, y: 13.5 },
    opernhaus: { name: 'Opernhaus', x: 22, y: 13.5 },
    'wohrder-wiese': { name: 'Wöhrder Wiese', x: 25.5, y: 12 },
    rathenauplatz: { name: 'Rathenauplatz', x: 25.5, y: 10 },
    rennweg: { name: 'Rennweg', x: 27, y: 8.5 },
    schoppershof: { name: 'Schoppershof', x: 28.5, y: 7 },
    nordostbahnhof: { name: 'Nordostbahnhof', x: 28.5, y: 5 },
    herrnhutte: { name: 'Herrnhütte', x: 28.5, y: 3 },
    ziegelstein: { name: 'Ziegelstein', x: 27, y: 1.5 },
    flughafen: { name: 'Flughafen', x: 25.5, y: 0 },
    'grossreuth-bei-schweinau': { name: 'Großreuth bei Schweinau', x: 12, y: 15 },
    'gustav-adolf-strasse': { name: 'Gustav-Adolf-Straße', x: 14, y: 15 },
    sundersbuhl: { name: 'Sündersbühl', x: 15.5, y: 13.5 },
    maxfeld: { name: 'Maxfeld', x: 25.5, y: 8 },
    kaulbachplatz: { name: 'Kaulbachplatz', x: 23.5, y: 8 },
    'friedrich-ebert-platz': { name: 'Friedrich-Ebert-Platz', x: 22, y: 9 },
    'klinikum-nord': { name: 'Klinikum Nord', x: 20.5, y: 7.5 },
    nordwestring: { name: 'Nordwestring', x: 18.5, y: 7.5, aka: ['Nürnberg Nordwestring'] },
  },
};
