// Ottawa's O-Train, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'ottawa',
  name: 'Ottawa',
  system: 'O-Train',
  country: 'Canada',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'O-Train Line 1',
      colour: '#d30f1d',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['blair', 'cyrville', 'st-laurent', 'tremblay', 'hurdman', 'lees', 'uottawa', 'rideau', 'parliament', 'lyon', 'pimisi', 'bayview', 'tunney-s-pasture'],
      ],
    },
    {
      id: '2',
      short: '2',
      name: 'O-Train Line 2',
      colour: '#508128',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['limebank', 'bowesville', 'leitrim', 'south-keys', 'greenboro', 'walkley', 'mooney-s-bay', 'carleton', 'dow-s-lake', 'corso-italia', 'bayview'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'O-Train Line 4',
      colour: '#0980a5',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['airport', 'uplands', 'south-keys'],
      ],
    },
  ],
  times: {
    'blair cyrville': 4,
    'st-laurent tremblay': 3,
    'parliament lyon': 1,
    'bayview tunney-s-pasture': 3,
    'limebank bowesville': 6,
    'bowesville leitrim': 5,
    'leitrim south-keys': 9,
    'greenboro walkley': 3,
    'walkley mooney-s-bay': 4,
    'mooney-s-bay carleton': 3,
    'carleton dow-s-lake': 4,
    'uplands south-keys': 5,
  },
  stations: {
    blair: { name: 'Blair', x: 17, y: 0, aka: ['Blair O-Train West/Ouest', 'Blair O-Train'] },
    cyrville: { name: 'Cyrville', x: 15.5, y: 1.5, aka: ['Cyrville O-Train West/Ouest', 'Cyrville O-Train East/Est'] },
    'st-laurent': { name: 'St-Laurent', x: 13.5, y: 1.5, aka: ['St-Laurent O-Train West/Ouest', 'St-Laurent O-Train East/Est'] },
    tremblay: { name: 'Tremblay', x: 11.5, y: 1.5, aka: ['Tremblay O-Train West/Ouest', 'Tremblay O-Train East/Est'] },
    hurdman: { name: 'Hurdman', x: 10, y: 3, aka: ['Hurdman O-Train West/Ouest', 'Hurdman O-Train East/Est'] },
    lees: { name: 'Lees', x: 8.5, y: 1.5, aka: ['Lees O-Train West/Ouest', 'Lees O-Train East/Est'] },
    uottawa: { name: 'UOttawa', x: 7, y: 1.5, aka: ['UOttawa O-Train West/Ouest', 'UOttawa O-Train East/Est'] },
    rideau: { name: 'Rideau', x: 5.5, y: 0, aka: ['Rideau O-Train West/Ouest', 'Rideau O-Train East/Est'] },
    parliament: { name: 'Parliament', x: 5.5, y: 2.5 },
    lyon: { name: 'Lyon', x: 3.5, y: 2.5, aka: ['Lyon B', 'Lyon A'] },
    pimisi: { name: 'Pimisi', x: 3.5, y: 4.5, aka: ['Pimisi O-Train West/Ouest', 'Pimisi O-Train East/Est'] },
    bayview: { name: 'Bayview', x: 1.5, y: 4.5, aka: ['Bayview O-Train West/Ouest', 'Bayview O-Train East/Est'] },
    'tunney-s-pasture': { name: 'Tunney\'s Pasture', x: 0, y: 6, aka: ['Tunney\'s Pasture O-Train East/Est', 'Tunney\'s Pasture O-Train'] },
    airport: { name: 'Airport', x: 7.5, y: 19, aka: ['Airport / Aéroport'] },
    uplands: { name: 'Uplands', x: 9, y: 17.5 },
    'south-keys': { name: 'South Keys', x: 10.5, y: 16 },
    limebank: { name: 'Limebank', x: 9, y: 21.5 },
    bowesville: { name: 'Bowesville', x: 10.5, y: 20 },
    leitrim: { name: 'Leitrim', x: 10.5, y: 18 },
    greenboro: { name: 'Greenboro', x: 10.5, y: 14 },
    walkley: { name: 'Walkley', x: 9, y: 12 },
    'mooney-s-bay': { name: 'Mooney\'s Bay', x: 7.5, y: 10.5 },
    carleton: { name: 'Carleton', x: 6, y: 9 },
    'dow-s-lake': { name: 'Dow\'s Lake', x: 4.5, y: 7.5, aka: ['Dow\'s Lake / Lac Dow'] },
    'corso-italia': { name: 'Corso Italia', x: 3, y: 6 },
  },
};
