// Paris's Métro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'paris',
  name: 'Paris',
  system: 'Métro',
  country: 'France',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Ligne 1',
      colour: '#ffbe00',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['chateau-de-vincennes', 'berault', 'saint-mande', 'porte-de-vincennes', 'nation', 'reuilly-diderot', 'gare-de-lyon', 'bastille', 'saint-paul', 'hotel-de-ville', 'chatelet', 'louvre-rivoli', 'palais-royal-musee-du-louvre', 'tuileries', 'concorde', 'champs-elysees-clemenceau', 'franklin-d-roosevelt', 'george-v', 'charles-de-gaulle-etoile', 'argentine', 'porte-maillot', 'les-sablons', 'pont-de-neuilly', 'esplanade-de-la-defense', 'la-defense-grande-arche'],
      ],
    },
    {
      id: '2',
      short: '2',
      name: 'Ligne 2',
      colour: '#0055c8',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['nation', 'avron', 'alexandre-dumas', 'philippe-auguste', 'pere-lachaise', 'menilmontant', 'couronnes', 'belleville', 'colonel-fabien', 'jaures', 'stalingrad', 'la-chapelle', 'barbes-rochechouart', 'anvers', 'pigalle', 'blanche', 'place-de-clichy', 'rome', 'villiers', 'monceau', 'courcelles', 'ternes', 'charles-de-gaulle-etoile', 'victor-hugo', 'porte-dauphine'],
      ],
    },
    {
      id: '3',
      short: '3',
      name: 'Ligne 3',
      colour: '#6e6e00',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['pont-de-levallois-becon', 'anatole-france', 'louise-michel', 'porte-de-champerret', 'pereire', 'wagram', 'malesherbes', 'villiers', 'europe', 'saint-lazare', 'havre-caumartin', 'opera', 'quatre-septembre', 'bourse', 'sentier', 'reaumur-sebastopol', 'arts-et-metiers', 'temple', 'republique', 'parmentier', 'rue-saint-maur', 'pere-lachaise', 'gambetta', 'porte-de-bagnolet', 'gallieni'],
      ],
    },
    {
      id: '3bis',
      short: '3bis',
      name: 'Ligne 3bis',
      colour: '#82c8e6',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['porte-des-lilas', 'saint-fargeau', 'pelleport', 'gambetta'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'Ligne 4',
      colour: '#a0006e',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['porte-de-clignancourt', 'simplon', 'marcadet-poissonniers', 'chateau-rouge', 'barbes-rochechouart', 'gare-du-nord', 'gare-de-l-est', 'chateau-d-eau', 'strasbourg-saint-denis', 'reaumur-sebastopol', 'etienne-marcel', 'les-halles', 'chatelet', 'cite', 'saint-michel', 'odeon', 'saint-germain-des-pres', 'saint-sulpice', 'saint-placide', 'montparnasse-bienvenue', 'vavin', 'raspail', 'denfert-rochereau', 'mouton-duvernet', 'alesia', 'porte-d-orleans', 'mairie-de-montrouge', 'barbara', 'bagneux-lucie-aubrac'],
      ],
    },
    {
      id: '5',
      short: '5',
      name: 'Ligne 5',
      colour: '#ff7f32',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['bobigny-pablo-picasso', 'bobigny-pantin-raymond-queneau', 'eglise-de-pantin', 'hoche', 'porte-de-pantin-parc-de-la-villette', 'ourcq', 'laumiere', 'jaures', 'stalingrad', 'gare-du-nord', 'gare-de-l-est', 'jacques-bonsergent', 'republique', 'oberkampf', 'richard-lenoir', 'breguet-sabin', 'bastille', 'quai-de-la-rapee', 'gare-d-austerlitz', 'saint-marcel', 'campo-formio', 'place-d-italie'],
      ],
    },
    {
      id: '6',
      short: '6',
      name: 'Ligne 6',
      colour: '#82dc73',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['charles-de-gaulle-etoile', 'kleber', 'boissiere', 'trocadero', 'passy', 'bir-hakeim', 'dupleix', 'la-motte-picquet-grenelle', 'cambronne', 'sevres-lecourbe', 'pasteur', 'montparnasse-bienvenue', 'edgar-quinet', 'raspail', 'denfert-rochereau', 'saint-jacques', 'glaciere', 'corvisart', 'place-d-italie', 'nationale', 'chevaleret', 'quai-de-la-gare', 'bercy', 'dugommier', 'daumesnil', 'bel-air', 'picpus', 'nation'],
      ],
    },
    {
      id: '7',
      short: '7',
      name: 'Ligne 7',
      colour: '#ff82b4',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['la-courneuve-8-mai-1945', 'fort-d-aubervilliers', 'aubervilliers-pantin-quatre-chemins', 'porte-de-la-villette', 'corentin-cariou', 'crimee', 'riquet', 'stalingrad', 'louis-blanc', 'chateau-landon', 'gare-de-l-est', 'poissonniere', 'cadet', 'le-peletier', 'chaussee-d-antin-la-fayette', 'opera', 'pyramides', 'palais-royal-musee-du-louvre', 'pont-neuf', 'chatelet', 'pont-marie', 'sully-morland', 'jussieu', 'place-monge', 'censier-daubenton', 'les-gobelins', 'place-d-italie', 'tolbiac', 'maison-blanche', 'porte-d-italie', 'porte-de-choisy', 'porte-d-ivry', 'pierre-et-marie-curie', 'mairie-d-ivry'],
        ['villejuif-louis-aragon', 'villejuif-paul-vaillant-couturier', 'villejuif-leo-lagrange', 'le-kremlin-bicetre', 'maison-blanche', 'tolbiac', 'place-d-italie', 'les-gobelins', 'censier-daubenton', 'place-monge', 'jussieu', 'sully-morland', 'pont-marie', 'chatelet', 'pont-neuf', 'palais-royal-musee-du-louvre', 'pyramides', 'opera', 'chaussee-d-antin-la-fayette', 'le-peletier', 'cadet', 'poissonniere', 'gare-de-l-est', 'chateau-landon', 'louis-blanc', 'stalingrad', 'riquet', 'crimee', 'corentin-cariou', 'porte-de-la-villette', 'aubervilliers-pantin-quatre-chemins', 'fort-d-aubervilliers', 'la-courneuve-8-mai-1945'],
      ],
    },
    {
      id: '7bis',
      short: '7bis',
      name: 'Ligne 7 bis',
      colour: '#82dc73',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['louis-blanc', 'jaures', 'bolivar', 'buttes-chaumont', 'botzaris', 'place-des-fetes', 'pre-saint-gervais'],
        ['pre-saint-gervais', 'danube', 'botzaris', 'buttes-chaumont', 'bolivar', 'jaures', 'louis-blanc'],
      ],
    },
    {
      id: '8',
      short: '8',
      name: 'Ligne 8',
      colour: '#d282be',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['pointe-du-lac', 'creteil-prefecture', 'creteil-universite', 'creteil-l-echat-hopital-henri-mondor', 'maisons-alfort-les-juilliottes', 'maisons-alfort-stade', 'ecole-veterinaire-de-maisons-alfort', 'charenton-ecoles', 'liberte', 'porte-de-charenton', 'porte-doree', 'michel-bizot', 'daumesnil', 'montgallet', 'reuilly-diderot', 'faidherbe-chaligny', 'ledru-rollin', 'bastille', 'chemin-vert', 'saint-sebastien-froissart', 'filles-du-calvaire', 'republique', 'strasbourg-saint-denis', 'bonne-nouvelle', 'grands-boulevards', 'richelieu-drouot', 'opera', 'madeleine', 'concorde', 'invalides', 'la-tour-maubourg', 'ecole-militaire', 'la-motte-picquet-grenelle', 'commerce', 'felix-faure', 'boucicaut', 'lourmel', 'balard'],
      ],
    },
    {
      id: '9',
      short: '9',
      name: 'Ligne 9',
      colour: '#b6bd00',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['pont-de-sevres', 'billancourt', 'marcel-sembat', 'porte-de-saint-cloud', 'exelmans', 'michel-ange-molitor', 'michel-ange-auteuil', 'jasmin', 'ranelagh', 'la-muette', 'rue-de-la-pompe', 'trocadero', 'iena', 'alma-marceau', 'franklin-d-roosevelt', 'saint-philippe-du-roule', 'miromesnil', 'saint-augustin', 'havre-caumartin', 'chaussee-d-antin-la-fayette', 'richelieu-drouot', 'grands-boulevards', 'bonne-nouvelle', 'strasbourg-saint-denis', 'republique', 'oberkampf', 'saint-ambroise', 'voltaire', 'charonne', 'rue-des-boulets', 'nation', 'buzenval', 'maraichers', 'porte-de-montreuil', 'robespierre', 'croix-de-chavaux', 'mairie-de-montreuil'],
      ],
    },
    {
      id: '10',
      short: '10',
      name: 'Ligne 10',
      colour: '#dc9600',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['boulogne-pont-de-saint-cloud', 'boulogne-jean-jaures', 'michel-ange-molitor', 'chardon-lagache', 'mirabeau', 'javel-andre-citroen', 'charles-michels', 'avenue-emile-zola', 'la-motte-picquet-grenelle', 'segur', 'duroc', 'vaneau', 'sevres-babylone', 'mabillon', 'odeon', 'cluny-la-sorbonne', 'maubert-mutualite', 'cardinal-lemoine', 'jussieu', 'gare-d-austerlitz'],
        ['gare-d-austerlitz', 'jussieu', 'cardinal-lemoine', 'maubert-mutualite', 'cluny-la-sorbonne', 'odeon', 'mabillon', 'sevres-babylone', 'vaneau', 'duroc', 'segur', 'la-motte-picquet-grenelle', 'avenue-emile-zola', 'charles-michels', 'javel-andre-citroen', 'eglise-d-auteuil', 'michel-ange-auteuil', 'porte-d-auteuil', 'boulogne-jean-jaures', 'boulogne-pont-de-saint-cloud'],
      ],
    },
    {
      id: '11',
      short: '11',
      name: 'Ligne 11',
      colour: '#6e491e',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['chatelet', 'hotel-de-ville', 'rambuteau', 'arts-et-metiers', 'republique', 'goncourt', 'belleville', 'pyrenees', 'jourdain', 'place-des-fetes', 'telegraphe', 'porte-des-lilas', 'mairie-des-lilas', 'serge-gainsbourg', 'romainville-carnot', 'montreuil-hopital', 'la-dhuys', 'coteaux-beauclair', 'rosny-bois-perrier'],
      ],
    },
    {
      id: '12',
      short: '12',
      name: 'Ligne 12',
      colour: '#00643c',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['mairie-d-aubervilliers', 'aime-cesaire', 'front-populaire', 'porte-de-la-chapelle', 'marx-dormoy', 'marcadet-poissonniers', 'jules-joffrin', 'lamarck-caulaincourt', 'abbesses', 'pigalle', 'saint-georges', 'notre-dame-de-lorette', 'trinite-d-estienne-d-orves', 'saint-lazare', 'madeleine', 'concorde', 'assemblee-nationale', 'solferino', 'rue-du-bac', 'sevres-babylone', 'rennes', 'notre-dame-des-champs', 'montparnasse-bienvenue', 'falguiere', 'pasteur', 'volontaires', 'vaugirard', 'convention', 'porte-de-versailles', 'corentin-celton', 'mairie-d-issy'],
      ],
    },
    {
      id: '13',
      short: '13',
      name: 'Ligne 13',
      colour: '#82c8e6',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['saint-denis-universite', 'basilique-de-saint-denis', 'saint-denis-porte-de-paris', 'carrefour-pleyel', 'mairie-de-saint-ouen', 'garibaldi', 'porte-de-saint-ouen', 'guy-moquet', 'la-fourche', 'place-de-clichy', 'liege', 'saint-lazare', 'miromesnil', 'champs-elysees-clemenceau', 'invalides', 'varenne', 'saint-francois-xavier', 'duroc', 'montparnasse-bienvenue', 'gaite', 'pernety', 'plaisance', 'porte-de-vanves', 'malakoff-plateau-de-vanves', 'malakoff-rue-etienne-dolet', 'chatillon-montrouge'],
        ['chatillon-montrouge', 'malakoff-rue-etienne-dolet', 'malakoff-plateau-de-vanves', 'porte-de-vanves', 'plaisance', 'pernety', 'gaite', 'montparnasse-bienvenue', 'duroc', 'saint-francois-xavier', 'varenne', 'invalides', 'champs-elysees-clemenceau', 'miromesnil', 'saint-lazare', 'liege', 'place-de-clichy', 'la-fourche', 'brochant', 'porte-de-clichy', 'mairie-de-clichy', 'gabriel-peri', 'les-agnettes', 'asnieres-gennevilliers-les-courtilles'],
      ],
    },
    {
      id: '14',
      short: '14',
      name: 'Ligne 14',
      colour: '#640082',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['saint-denis-pleyel', 'mairie-de-saint-ouen', 'saint-ouen', 'porte-de-clichy', 'pont-cardinet', 'saint-lazare', 'madeleine', 'pyramides', 'chatelet', 'gare-de-lyon', 'bercy', 'cour-saint-emilion', 'bibliotheque-francois-mitterrand', 'olympiades', 'maison-blanche', 'hopital-bicetre', 'villejuif-gustave-roussy', 'l-hay-les-roses', 'chevilly-larue', 'thiais-orly', 'aeroport-d-orly'],
      ],
    },
  ],
  times: {
    'hotel-de-ville chatelet': 1,
    'chatelet louvre-rivoli': 1,
    'louvre-rivoli palais-royal-musee-du-louvre': 1,
    'palais-royal-musee-du-louvre tuileries': 1,
    'tuileries concorde': 1,
    'champs-elysees-clemenceau franklin-d-roosevelt': 1,
    'george-v charles-de-gaulle-etoile': 1,
    'charles-de-gaulle-etoile argentine': 1,
    'avron alexandre-dumas': 2,
    'belleville colonel-fabien': 2,
    'la-chapelle barbes-rochechouart': 2,
    'charles-de-gaulle-etoile victor-hugo': 2,
    'victor-hugo porte-dauphine': 2,
    'pont-de-levallois-becon anatole-france': 2,
    'villiers europe': 2,
    'republique parmentier': 2,
    'rue-saint-maur pere-lachaise': 2,
    'pere-lachaise gambetta': 2,
    'gambetta porte-de-bagnolet': 2,
    'porte-de-bagnolet gallieni': 2,
    'porte-des-lilas saint-fargeau': 2,
    'barbes-rochechouart gare-du-nord': 2,
    'porte-d-orleans mairie-de-montrouge': 2,
    'mairie-de-montrouge barbara': 2,
    'barbara bagneux-lucie-aubrac': 2,
    'bobigny-pablo-picasso bobigny-pantin-raymond-queneau': 4,
    'bobigny-pantin-raymond-queneau eglise-de-pantin': 2,
    'eglise-de-pantin hoche': 2,
    'hoche porte-de-pantin-parc-de-la-villette': 2,
    'laumiere jaures': 2,
    'stalingrad gare-du-nord': 2,
    'gare-de-l-est jacques-bonsergent': 2,
    'bastille quai-de-la-rapee': 2,
    'trocadero passy': 2,
    'pasteur montparnasse-bienvenue': 2,
    'quai-de-la-gare bercy': 2,
    'bercy dugommier': 2,
    'la-courneuve-8-mai-1945 fort-d-aubervilliers': 2,
    'fort-d-aubervilliers aubervilliers-pantin-quatre-chemins': 3,
    'aubervilliers-pantin-quatre-chemins porte-de-la-villette': 2,
    'riquet stalingrad': 2,
    'gare-de-l-est poissonniere': 2,
    'palais-royal-musee-du-louvre pont-neuf': 2,
    'chatelet pont-marie': 2,
    'sully-morland jussieu': 2,
    'place-d-italie tolbiac': 2,
    'porte-d-ivry pierre-et-marie-curie': 2,
    'pierre-et-marie-curie mairie-d-ivry': 2,
    'villejuif-louis-aragon villejuif-paul-vaillant-couturier': 2,
    'villejuif-paul-vaillant-couturier villejuif-leo-lagrange': 2,
    'villejuif-leo-lagrange le-kremlin-bicetre': 2,
    'le-kremlin-bicetre maison-blanche': 3,
    'tolbiac place-d-italie': 2,
    'jussieu sully-morland': 2,
    'pont-marie chatelet': 2,
    'pont-neuf palais-royal-musee-du-louvre': 2,
    'poissonniere gare-de-l-est': 2,
    'stalingrad riquet': 2,
    'porte-de-la-villette aubervilliers-pantin-quatre-chemins': 2,
    'aubervilliers-pantin-quatre-chemins fort-d-aubervilliers': 3,
    'fort-d-aubervilliers la-courneuve-8-mai-1945': 2,
    'bolivar buttes-chaumont': 2,
    'buttes-chaumont bolivar': 2,
    'pointe-du-lac creteil-prefecture': 3,
    'creteil-prefecture creteil-universite': 3,
    'creteil-universite creteil-l-echat-hopital-henri-mondor': 2,
    'creteil-l-echat-hopital-henri-mondor maisons-alfort-les-juilliottes': 2,
    'maisons-alfort-les-juilliottes maisons-alfort-stade': 2,
    'maisons-alfort-stade ecole-veterinaire-de-maisons-alfort': 3,
    'ecole-veterinaire-de-maisons-alfort charenton-ecoles': 2,
    'charenton-ecoles liberte': 2,
    'liberte porte-de-charenton': 2,
    'daumesnil montgallet': 2,
    'faidherbe-chaligny ledru-rollin': 2,
    'republique strasbourg-saint-denis': 2,
    'concorde invalides': 2,
    'ecole-militaire la-motte-picquet-grenelle': 2,
    'la-motte-picquet-grenelle commerce': 2,
    'marcel-sembat porte-de-saint-cloud': 2,
    'porte-de-saint-cloud exelmans': 2,
    'michel-ange-auteuil jasmin': 2,
    'la-muette rue-de-la-pompe': 2,
    'rue-de-la-pompe trocadero': 2,
    'alma-marceau franklin-d-roosevelt': 2,
    'strasbourg-saint-denis republique': 2,
    'rue-des-boulets nation': 2,
    'porte-de-montreuil robespierre': 2,
    'robespierre croix-de-chavaux': 2,
    'croix-de-chavaux mairie-de-montreuil': 2,
    'boulogne-pont-de-saint-cloud boulogne-jean-jaures': 2,
    'boulogne-jean-jaures michel-ange-molitor': 4,
    'charles-michels avenue-emile-zola': 2,
    'la-motte-picquet-grenelle segur': 2,
    'segur duroc': 2,
    'sevres-babylone mabillon': 2,
    'jussieu gare-d-austerlitz': 2,
    'gare-d-austerlitz jussieu': 2,
    'mabillon sevres-babylone': 2,
    'duroc segur': 2,
    'segur la-motte-picquet-grenelle': 2,
    'avenue-emile-zola charles-michels': 2,
    'javel-andre-citroen eglise-d-auteuil': 2,
    'porte-d-auteuil boulogne-jean-jaures': 3,
    'boulogne-jean-jaures boulogne-pont-de-saint-cloud': 2,
    'chatelet hotel-de-ville': 1,
    'hotel-de-ville rambuteau': 1,
    'rambuteau arts-et-metiers': 1,
    'goncourt belleville': 1,
    'pyrenees jourdain': 1,
    'jourdain place-des-fetes': 1,
    'place-des-fetes telegraphe': 1,
    'romainville-carnot montreuil-hopital': 3,
    'la-dhuys coteaux-beauclair': 1,
    'mairie-d-aubervilliers aime-cesaire': 2,
    'aime-cesaire front-populaire': 2,
    'front-populaire porte-de-la-chapelle': 2,
    'porte-de-la-chapelle marx-dormoy': 2,
    'marx-dormoy marcadet-poissonniers': 2,
    'saint-lazare madeleine': 2,
    'concorde assemblee-nationale': 2,
    'convention porte-de-versailles': 2,
    'porte-de-versailles corentin-celton': 2,
    'saint-denis-porte-de-paris carrefour-pleyel': 3,
    'porte-de-saint-ouen guy-moquet': 1,
    'la-fourche place-de-clichy': 1,
    'place-de-clichy liege': 1,
    'liege saint-lazare': 1,
    'invalides varenne': 1,
    'varenne saint-francois-xavier': 1,
    'saint-francois-xavier duroc': 1,
    'montparnasse-bienvenue gaite': 1,
    'pernety plaisance': 1,
    'plaisance pernety': 1,
    'gaite montparnasse-bienvenue': 1,
    'duroc saint-francois-xavier': 1,
    'saint-francois-xavier varenne': 1,
    'varenne invalides': 1,
    'saint-lazare liege': 1,
    'liege place-de-clichy': 1,
    'place-de-clichy la-fourche': 1,
    'la-fourche brochant': 1,
    'mairie-de-clichy gabriel-peri': 4,
    'mairie-de-saint-ouen saint-ouen': 3,
    'saint-ouen porte-de-clichy': 3,
    'pont-cardinet saint-lazare': 4,
    'pyramides chatelet': 3,
    'chatelet gare-de-lyon': 5,
    'maison-blanche hopital-bicetre': 3,
    'hopital-bicetre villejuif-gustave-roussy': 4,
    'villejuif-gustave-roussy l-hay-les-roses': 4,
    'l-hay-les-roses chevilly-larue': 4,
    'chevilly-larue thiais-orly': 3,
    'thiais-orly aeroport-d-orly': 5,
  },
  stations: {
    'pointe-du-lac': { name: 'Pointe du Lac', x: 59.5, y: 54.5 },
    'creteil-prefecture': { name: 'Créteil-Préfecture', x: 59, y: 52 },
    'creteil-universite': { name: 'Créteil-Université', x: 57.5, y: 50.5 },
    'creteil-l-echat-hopital-henri-mondor': { name: 'Créteil-L\'Échat (Hopital Henri Mondor)', x: 56, y: 49 },
    'maisons-alfort-les-juilliottes': { name: 'Maisons-Alfort — Les Juilliottes', x: 54.5, y: 47.5 },
    'maisons-alfort-stade': { name: 'Maisons-Alfort — Stade', x: 53, y: 45.5 },
    'ecole-veterinaire-de-maisons-alfort': { name: 'École Vétérinaire de Maisons-Alfort', x: 51, y: 44 },
    'charenton-ecoles': { name: 'Charenton-Écoles', x: 49.5, y: 42.5 },
    liberte: { name: 'Liberté', x: 48, y: 40.5 },
    'porte-de-charenton': { name: 'Porte de Charenton', x: 46, y: 39 },
    'porte-doree': { name: 'Porte Dorée', x: 46, y: 36.5 },
    'michel-bizot': { name: 'Michel Bizot', x: 44, y: 35 },
    daumesnil: { name: 'Daumesnil', x: 42.5, y: 33 },
    montgallet: { name: 'Montgallet', x: 41, y: 31.5 },
    'reuilly-diderot': { name: 'Reuilly — Diderot', x: 39.5, y: 30 },
    'faidherbe-chaligny': { name: 'Faidherbe — Chaligny', x: 39.5, y: 28.5 },
    'ledru-rollin': { name: 'Ledru-Rollin', x: 38, y: 28.5 },
    bastille: { name: 'Bastille', x: 36, y: 28.5 },
    'chemin-vert': { name: 'Chemin Vert', x: 36.5, y: 26 },
    'saint-sebastien-froissart': { name: 'Saint-Sébastien - Froissart', x: 36.5, y: 24 },
    'filles-du-calvaire': { name: 'Filles du Calvaire', x: 35.5, y: 23 },
    republique: { name: 'République', x: 36, y: 21.5 },
    'strasbourg-saint-denis': { name: 'Strasbourg - Saint-Denis', x: 34.5, y: 20 },
    'bonne-nouvelle': { name: 'Bonne Nouvelle', x: 32.5, y: 20 },
    'grands-boulevards': { name: 'Grands Boulevards', x: 31, y: 19 },
    'richelieu-drouot': { name: 'Richelieu - Drouot', x: 29.5, y: 20.5 },
    opera: { name: 'Opéra', x: 28, y: 21.5 },
    madeleine: { name: 'Madeleine', x: 26.5, y: 21.5 },
    concorde: { name: 'Concorde', x: 24.5, y: 22.5 },
    invalides: { name: 'Invalides', x: 22.5, y: 24 },
    'la-tour-maubourg': { name: 'La Tour Maubourg', x: 20.5, y: 25.5 },
    'ecole-militaire': { name: 'École Militaire', x: 19, y: 27.5 },
    'la-motte-picquet-grenelle': { name: 'La Motte-Picquet - Grenelle', x: 17.5, y: 29 },
    commerce: { name: 'Commerce', x: 17.5, y: 31 },
    'felix-faure': { name: 'Félix Faure', x: 16, y: 32.5 },
    boucicaut: { name: 'Boucicaut', x: 14, y: 32.5 },
    lourmel: { name: 'Lourmel', x: 12.5, y: 34 },
    balard: { name: 'Balard', x: 11, y: 35.5 },
    'la-courneuve-8-mai-1945': { name: 'La Courneuve - 8 mai 1945', x: 46.5, y: 3.5 },
    'fort-d-aubervilliers': { name: 'Fort d\'Aubervilliers', x: 45, y: 5 },
    'aubervilliers-pantin-quatre-chemins': { name: 'Aubervilliers - Pantin - Quatre Chemins', x: 44, y: 6.5 },
    'porte-de-la-villette': { name: 'Porte de la Villette', x: 42.5, y: 8 },
    'corentin-cariou': { name: 'Corentin Cariou', x: 41, y: 9.5 },
    crimee: { name: 'Crimée', x: 39.5, y: 10.5 },
    riquet: { name: 'Riquet', x: 38, y: 12 },
    stalingrad: { name: 'Stalingrad', x: 36.5, y: 13.5 },
    'louis-blanc': { name: 'Louis Blanc', x: 36.5, y: 15.5 },
    'chateau-landon': { name: 'Château Landon', x: 36.5, y: 17.5 },
    'gare-de-l-est': { name: 'Gare de L\'Est', x: 34.5, y: 17.5 },
    poissonniere: { name: 'Poissonnière', x: 32.5, y: 17 },
    cadet: { name: 'Cadet', x: 31, y: 17.5 },
    'le-peletier': { name: 'Le Peletier', x: 29.5, y: 19 },
    'chaussee-d-antin-la-fayette': { name: 'Chaussée d\'Antin - La Fayette', x: 28, y: 19.5 },
    pyramides: { name: 'Pyramides', x: 29.5, y: 24 },
    'palais-royal-musee-du-louvre': { name: 'Palais Royal - Musée du Louvre', x: 28, y: 25 },
    'pont-neuf': { name: 'Pont Neuf', x: 30, y: 26.5 },
    chatelet: { name: 'Châtelet', x: 32.5, y: 26.5 },
    'pont-marie': { name: 'Pont Marie', x: 33.5, y: 28 },
    'sully-morland': { name: 'Sully - Morland', x: 34.5, y: 29 },
    jussieu: { name: 'Jussieu', x: 33.5, y: 31 },
    'place-monge': { name: 'Place Monge', x: 32, y: 32.5 },
    'censier-daubenton': { name: 'Censier - Daubenton', x: 32, y: 34.5 },
    'les-gobelins': { name: 'Les Gobelins', x: 32, y: 36.5 },
    'place-d-italie': { name: 'Place d\'Italie', x: 33.5, y: 38.5 },
    tolbiac: { name: 'Tolbiac', x: 33.5, y: 40.5 },
    'maison-blanche': { name: 'Maison Blanche', x: 33.5, y: 42.5 },
    'porte-d-italie': { name: 'Porte d\'Italie', x: 36, y: 43 },
    'porte-de-choisy': { name: 'Porte de Choisy', x: 36, y: 41 },
    'porte-d-ivry': { name: 'Porte d\'Ivry', x: 38, y: 41 },
    'pierre-et-marie-curie': { name: 'Pierre et Marie Curie', x: 39.5, y: 42.5 },
    'mairie-d-ivry': { name: 'Mairie d\'Ivry', x: 41, y: 44 },
    'bobigny-pablo-picasso': { name: 'Bobigny - Pablo Picasso', x: 51, y: 10.5 },
    'bobigny-pantin-raymond-queneau': { name: 'Bobigny - Pantin - Raymond Queneau', x: 49.5, y: 12 },
    'eglise-de-pantin': { name: 'Église de Pantin', x: 48, y: 13 },
    hoche: { name: 'Hoche', x: 46, y: 13.5 },
    'porte-de-pantin-parc-de-la-villette': { name: 'Porte de Pantin (Parc de la Villette)', x: 44, y: 13.5 },
    ourcq: { name: 'Ourcq', x: 41.5, y: 13.5 },
    laumiere: { name: 'Laumière', x: 39.5, y: 13.5 },
    jaures: { name: 'Jaurès', x: 38, y: 15 },
    'gare-du-nord': { name: 'Gare du Nord', x: 35, y: 15 },
    'jacques-bonsergent': { name: 'Jacques Bonsergent', x: 36, y: 19 },
    oberkampf: { name: 'Oberkampf', x: 37.5, y: 23 },
    'richard-lenoir': { name: 'Richard Lenoir', x: 37.5, y: 25 },
    'breguet-sabin': { name: 'Bréguet-Sabin', x: 37.5, y: 27 },
    'quai-de-la-rapee': { name: 'Quai de la Rapée', x: 34.5, y: 30.5 },
    'gare-d-austerlitz': { name: 'Gare d\'Austerlitz', x: 35, y: 32.5 },
    'saint-marcel': { name: 'Saint-Marcel', x: 35, y: 34.5 },
    'campo-formio': { name: 'Campo-Formio', x: 33.5, y: 36 },
    'saint-denis-pleyel': { name: 'Saint-Denis Pleyel', x: 28, y: 6 },
    'mairie-de-saint-ouen': { name: 'Mairie de Saint-Ouen', x: 27, y: 7 },
    'saint-ouen': { name: 'Saint-Ouen', x: 25.5, y: 9 },
    'porte-de-clichy': { name: 'Porte de Clichy', x: 24.5, y: 11 },
    'pont-cardinet': { name: 'Pont Cardinet', x: 24.5, y: 14.5 },
    'saint-lazare': { name: 'Saint-Lazare', x: 25, y: 17.5 },
    'gare-de-lyon': { name: 'Gare de Lyon', x: 36, y: 30 },
    bercy: { name: 'Bercy', x: 37.5, y: 32.5 },
    'cour-saint-emilion': { name: 'Cour Saint-Émilion', x: 38, y: 35.5 },
    'bibliotheque-francois-mitterrand': { name: 'Bibliothèque François Mitterrand', x: 36.5, y: 38 },
    olympiades: { name: 'Olympiades', x: 35, y: 40 },
    'hopital-bicetre': { name: 'Hôpital Bicêtre', x: 33.5, y: 45.5 },
    'villejuif-gustave-roussy': { name: 'Villejuif - Gustave Roussy', x: 33.5, y: 48 },
    'l-hay-les-roses': { name: 'L\'Haÿ-les-Roses', x: 33.5, y: 50.5 },
    'chevilly-larue': { name: 'Chevilly-Larue', x: 33.5, y: 53 },
    'thiais-orly': { name: 'Thiais - Orly', x: 33.5, y: 55.5 },
    'aeroport-d-orly': { name: 'Aéroport d\'Orly', x: 33.5, y: 57.5 },
    'porte-de-clignancourt': { name: 'Porte de Clignancourt', x: 30.5, y: 9 },
    simplon: { name: 'Simplon', x: 32, y: 10.5 },
    'marcadet-poissonniers': { name: 'Marcadet - Poissonniers', x: 33.5, y: 12 },
    'chateau-rouge': { name: 'Château Rouge', x: 32, y: 13.5 },
    'barbes-rochechouart': { name: 'Barbès - Rochechouart', x: 33, y: 15 },
    'chateau-d-eau': { name: 'Château d\'Eau', x: 33, y: 18.5 },
    'reaumur-sebastopol': { name: 'Réaumur - Sébastopol', x: 32.5, y: 21.5 },
    'etienne-marcel': { name: 'Étienne Marcel', x: 32.5, y: 23 },
    'les-halles': { name: 'Les Halles', x: 31.5, y: 25 },
    cite: { name: 'Cité', x: 31, y: 28 },
    'saint-michel': { name: 'Saint-Michel', x: 29, y: 28 },
    odeon: { name: 'Odéon', x: 28, y: 29 },
    'saint-germain-des-pres': { name: 'Saint-Germain-des-Prés', x: 27.5, y: 27 },
    'saint-sulpice': { name: 'Saint-Sulpice', x: 26, y: 28.5 },
    'saint-placide': { name: 'Saint-Placide', x: 24.5, y: 30 },
    'montparnasse-bienvenue': { name: 'Montparnasse-Bienvenüe', x: 23, y: 31.5 },
    vavin: { name: 'Vavin', x: 24.5, y: 31.5 },
    raspail: { name: 'Raspail', x: 26.5, y: 33 },
    'denfert-rochereau': { name: 'Denfert-Rochereau', x: 26.5, y: 35 },
    'mouton-duvernet': { name: 'Mouton-Duvernet', x: 26.5, y: 37.5 },
    alesia: { name: 'Alésia', x: 25, y: 39 },
    'porte-d-orleans': { name: 'Porte d\'Orléans', x: 25, y: 41 },
    'mairie-de-montrouge': { name: 'Mairie de Montrouge', x: 23.5, y: 42.5 },
    barbara: { name: 'Barbara', x: 23.5, y: 44.5 },
    'bagneux-lucie-aubrac': { name: 'Bagneux-Lucie Aubrac', x: 23.5, y: 46.5 },
    'boulogne-pont-de-saint-cloud': { name: 'Boulogne - Pont de Saint-Cloud', x: 1.5, y: 31.5 },
    'boulogne-jean-jaures': { name: 'Boulogne - Jean Jaurès', x: 3.5, y: 31.5 },
    'michel-ange-molitor': { name: 'Michel-Ange - Molitor', x: 6, y: 31.5 },
    'chardon-lagache': { name: 'Chardon-Lagache', x: 8, y: 31.5 },
    mirabeau: { name: 'Mirabeau', x: 10, y: 31.5 },
    'javel-andre-citroen': { name: 'Javel - André Citroën', x: 11.5, y: 30.5 },
    'charles-michels': { name: 'Charles Michels', x: 13.5, y: 30.5 },
    'avenue-emile-zola': { name: 'Avenue Émile Zola', x: 16, y: 30.5 },
    segur: { name: 'Ségur', x: 19.5, y: 29 },
    duroc: { name: 'Duroc', x: 21.5, y: 29.5 },
    vaneau: { name: 'Vaneau', x: 23.5, y: 29 },
    'sevres-babylone': { name: 'Sèvres-Babylone', x: 24.5, y: 28 },
    mabillon: { name: 'Mabillon', x: 26.5, y: 27.5 },
    'cluny-la-sorbonne': { name: 'Cluny-La Sorbonne', x: 29.5, y: 29 },
    'maubert-mutualite': { name: 'Maubert - Mutualité', x: 31.5, y: 29 },
    'cardinal-lemoine': { name: 'Cardinal Lemoine', x: 31.5, y: 31 },
    'mairie-d-aubervilliers': { name: 'Mairie d\'Aubervilliers', x: 39, y: 4.5 },
    'aime-cesaire': { name: 'Aimé Césaire', x: 37.5, y: 5.5 },
    'front-populaire': { name: 'Front Populaire', x: 36, y: 7 },
    'porte-de-la-chapelle': { name: 'Porte de la Chapelle', x: 35, y: 8.5 },
    'marx-dormoy': { name: 'Marx Dormoy', x: 35, y: 10.5 },
    'jules-joffrin': { name: 'Jules Joffrin', x: 31.5, y: 12 },
    'lamarck-caulaincourt': { name: 'Lamarck - Caulaincourt', x: 29.5, y: 12 },
    abbesses: { name: 'Abbesses', x: 29.5, y: 14 },
    pigalle: { name: 'Pigalle', x: 29.5, y: 16.5 },
    'saint-georges': { name: 'Saint-Georges', x: 27.5, y: 16.5 },
    'notre-dame-de-lorette': { name: 'Notre-Dame de Lorette', x: 29, y: 18 },
    'trinite-d-estienne-d-orves': { name: 'Trinité d\'Estienne d\'Orves', x: 27, y: 18 },
    'assemblee-nationale': { name: 'Assemblée Nationale', x: 24.5, y: 24.5 },
    solferino: { name: 'Solférino', x: 24, y: 26.5 },
    'rue-du-bac': { name: 'Rue du Bac', x: 26, y: 26 },
    rennes: { name: 'Rennes', x: 26, y: 29.5 },
    'notre-dame-des-champs': { name: 'Notre-Dame des Champs', x: 26, y: 31.5 },
    falguiere: { name: 'Falguière', x: 22, y: 30.5 },
    pasteur: { name: 'Pasteur', x: 22, y: 32.5 },
    volontaires: { name: 'Volontaires', x: 20, y: 32.5 },
    vaugirard: { name: 'Vaugirard', x: 18.5, y: 34 },
    convention: { name: 'Convention', x: 17, y: 35.5 },
    'porte-de-versailles': { name: 'Porte de Versailles', x: 15.5, y: 37 },
    'corentin-celton': { name: 'Corentin Celton', x: 14, y: 38.5 },
    'mairie-d-issy': { name: 'Mairie d\'Issy', x: 12.5, y: 39.5 },
    'pont-de-sevres': { name: 'Pont de Sèvres', x: 0, y: 39 },
    billancourt: { name: 'Billancourt', x: 1.5, y: 38 },
    'marcel-sembat': { name: 'Marcel Sembat', x: 3, y: 36.5 },
    'porte-de-saint-cloud': { name: 'Porte de Saint-Cloud', x: 4.5, y: 35 },
    exelmans: { name: 'Exelmans', x: 6, y: 33.5 },
    'michel-ange-auteuil': { name: 'Michel-Ange - Auteuil', x: 7, y: 30 },
    jasmin: { name: 'Jasmin', x: 8.5, y: 28.5 },
    ranelagh: { name: 'Ranelagh', x: 9.5, y: 27 },
    'la-muette': { name: 'La Muette', x: 11, y: 25.5 },
    'rue-de-la-pompe': { name: 'Rue de la Pompe', x: 12, y: 24 },
    trocadero: { name: 'Trocadéro', x: 14, y: 24 },
    iena: { name: 'Iéna', x: 16, y: 24 },
    'alma-marceau': { name: 'Alma-Marceau', x: 18.5, y: 23.5 },
    'franklin-d-roosevelt': { name: 'Franklin D. Roosevelt', x: 20, y: 22 },
    'saint-philippe-du-roule': { name: 'Saint-Philippe du Roule', x: 21, y: 20.5 },
    miromesnil: { name: 'Miromesnil', x: 23, y: 20 },
    'saint-augustin': { name: 'Saint-Augustin', x: 24.5, y: 19 },
    'havre-caumartin': { name: 'Havre - Caumartin', x: 26, y: 19.5 },
    'saint-ambroise': { name: 'Saint-Ambroise', x: 38.5, y: 24 },
    voltaire: { name: 'Voltaire', x: 39.5, y: 25.5 },
    charonne: { name: 'Charonne', x: 40.5, y: 27 },
    'rue-des-boulets': { name: 'Rue des Boulets', x: 41.5, y: 28.5 },
    nation: { name: 'Nation', x: 43, y: 30 },
    buzenval: { name: 'Buzenval', x: 44.5, y: 28.5 },
    maraichers: { name: 'Maraîchers', x: 46, y: 27 },
    'porte-de-montreuil': { name: 'Porte de Montreuil', x: 48, y: 27 },
    robespierre: { name: 'Robespierre', x: 50, y: 27 },
    'croix-de-chavaux': { name: 'Croix de Chavaux', x: 52.5, y: 27 },
    'mairie-de-montreuil': { name: 'Mairie de Montreuil', x: 53.5, y: 25.5 },
    'chateau-de-vincennes': { name: 'Château de Vincennes', x: 51.5, y: 30 },
    berault: { name: 'Bérault', x: 49.5, y: 30 },
    'saint-mande': { name: 'Saint-Mandé', x: 47.5, y: 30 },
    'porte-de-vincennes': { name: 'Porte de Vincennes', x: 45, y: 30 },
    'saint-paul': { name: 'Saint-Paul', x: 35, y: 27 },
    'hotel-de-ville': { name: 'Hôtel de Ville', x: 34, y: 25.5 },
    'louvre-rivoli': { name: 'Louvre - Rivoli', x: 30, y: 25 },
    tuileries: { name: 'Tuileries', x: 26, y: 24 },
    'champs-elysees-clemenceau': { name: 'Champs-Élysées - Clemenceau', x: 22.5, y: 22 },
    'george-v': { name: 'George V', x: 18, y: 20.5 },
    'charles-de-gaulle-etoile': { name: 'Charles de Gaulle - Étoile', x: 16.5, y: 19 },
    argentine: { name: 'Argentine', x: 14.5, y: 19 },
    'porte-maillot': { name: 'Porte Maillot', x: 13, y: 17.5 },
    'les-sablons': { name: 'Les Sablons', x: 11.5, y: 16 },
    'pont-de-neuilly': { name: 'Pont de Neuilly', x: 10, y: 14.5 },
    'esplanade-de-la-defense': { name: 'Esplanade de La Défense', x: 8.5, y: 13 },
    'la-defense-grande-arche': { name: 'La Défense - Grande Arche', x: 7, y: 12 },
    'pont-de-levallois-becon': { name: 'Pont de Levallois - Bécon', x: 11.5, y: 11 },
    'anatole-france': { name: 'Anatole France', x: 13, y: 12.5 },
    'louise-michel': { name: 'Louise Michel', x: 14.5, y: 14 },
    'porte-de-champerret': { name: 'Porte de Champerret', x: 16, y: 15.5 },
    pereire: { name: 'Pereire', x: 18, y: 15.5 },
    wagram: { name: 'Wagram', x: 20, y: 15.5 },
    malesherbes: { name: 'Malesherbes', x: 22, y: 15.5 },
    villiers: { name: 'Villiers', x: 23.5, y: 17 },
    europe: { name: 'Europe', x: 25, y: 16 },
    'quatre-septembre': { name: 'Quatre Septembre', x: 29.5, y: 22.5 },
    bourse: { name: 'Bourse', x: 31, y: 21 },
    sentier: { name: 'Sentier', x: 31, y: 23 },
    'arts-et-metiers': { name: 'Arts et Métiers', x: 34, y: 23 },
    temple: { name: 'Temple', x: 34, y: 21.5 },
    parmentier: { name: 'Parmentier', x: 38.5, y: 21.5 },
    'rue-saint-maur': { name: 'Rue Saint-Maur', x: 40, y: 22.5 },
    'pere-lachaise': { name: 'Père Lachaise', x: 42.5, y: 22.5 },
    gambetta: { name: 'Gambetta', x: 44.5, y: 22.5 },
    'porte-de-bagnolet': { name: 'Porte de Bagnolet', x: 46.5, y: 22.5 },
    gallieni: { name: 'Gallieni', x: 48.5, y: 22.5 },
    rambuteau: { name: 'Rambuteau', x: 32.5, y: 24.5 },
    goncourt: { name: 'Goncourt', x: 37.5, y: 20 },
    belleville: { name: 'Belleville', x: 39, y: 18.5 },
    pyrenees: { name: 'Pyrénées', x: 41, y: 18.5 },
    jourdain: { name: 'Jourdain', x: 43.5, y: 19 },
    'place-des-fetes': { name: 'Place des Fêtes', x: 45, y: 17.5 },
    telegraphe: { name: 'Télégraphe', x: 47, y: 18 },
    'porte-des-lilas': { name: 'Porte des Lilas', x: 49, y: 18 },
    'mairie-des-lilas': { name: 'Mairie des Lilas', x: 51, y: 17.5 },
    'serge-gainsbourg': { name: 'Serge Gainsbourg', x: 53.5, y: 17.5 },
    'romainville-carnot': { name: 'Romainville - Carnot', x: 55.5, y: 17.5 },
    'montreuil-hopital': { name: 'Montreuil - Hôpital', x: 57.5, y: 17.5 },
    'la-dhuys': { name: 'La Dhuys', x: 60, y: 17.5 },
    'coteaux-beauclair': { name: 'Coteaux Beauclair', x: 62, y: 17.5 },
    'rosny-bois-perrier': { name: 'Rosny - Bois-Perrier', x: 64, y: 17.5 },
    'saint-denis-universite': { name: 'Saint-Denis - Université', x: 33, y: 0 },
    'basilique-de-saint-denis': { name: 'Basilique de Saint-Denis', x: 31.5, y: 1.5 },
    'saint-denis-porte-de-paris': { name: 'Saint-Denis - Porte de Paris', x: 30, y: 3 },
    'carrefour-pleyel': { name: 'Carrefour Pleyel', x: 28.5, y: 5 },
    garibaldi: { name: 'Garibaldi', x: 27, y: 8.5 },
    'porte-de-saint-ouen': { name: 'Porte de Saint-Ouen', x: 26.5, y: 10.5 },
    'guy-moquet': { name: 'Guy Môquet', x: 26.5, y: 12 },
    'la-fourche': { name: 'La Fourche', x: 26.5, y: 14 },
    'place-de-clichy': { name: 'Place de Clichy', x: 26.5, y: 15.5 },
    liege: { name: 'Liège', x: 26.5, y: 17 },
    varenne: { name: 'Varenne', x: 22.5, y: 26 },
    'saint-francois-xavier': { name: 'Saint-François-Xavier', x: 22, y: 27.5 },
    gaite: { name: 'Gaîté', x: 23, y: 33.5 },
    pernety: { name: 'Pernety', x: 23, y: 35.5 },
    plaisance: { name: 'Plaisance', x: 21.5, y: 37 },
    'porte-de-vanves': { name: 'Porte de Vanves', x: 20, y: 38.5 },
    'malakoff-plateau-de-vanves': { name: 'Malakoff - Plateau de Vanves', x: 19, y: 40 },
    'malakoff-rue-etienne-dolet': { name: 'Malakoff - Rue Étienne Dolet', x: 19, y: 42 },
    'chatillon-montrouge': { name: 'Châtillon-Montrouge', x: 19, y: 44 },
    'saint-fargeau': { name: 'Saint-Fargeau', x: 47.5, y: 19.5 },
    pelleport: { name: 'Pelleport', x: 46, y: 21 },
    kleber: { name: 'Kléber', x: 16.5, y: 21 },
    boissiere: { name: 'Boissière', x: 15, y: 22.5 },
    passy: { name: 'Passy', x: 13.5, y: 26 },
    'bir-hakeim': { name: 'Bir-Hakeim', x: 14.5, y: 27.5 },
    dupleix: { name: 'Dupleix', x: 16, y: 29 },
    cambronne: { name: 'Cambronne', x: 19, y: 30.5 },
    'sevres-lecourbe': { name: 'Sèvres-Lecourbe', x: 20.5, y: 31 },
    'edgar-quinet': { name: 'Edgar Quinet', x: 24.5, y: 33 },
    'saint-jacques': { name: 'Saint-Jacques', x: 28, y: 36.5 },
    glaciere: { name: 'Glacière', x: 30, y: 37 },
    corvisart: { name: 'Corvisart', x: 31.5, y: 38 },
    nationale: { name: 'Nationale', x: 35, y: 37 },
    chevaleret: { name: 'Chevaleret', x: 36, y: 35.5 },
    'quai-de-la-gare': { name: 'Quai de la Gare', x: 37.5, y: 34 },
    dugommier: { name: 'Dugommier', x: 40, y: 33 },
    'bel-air': { name: 'Bel-Air', x: 44, y: 33 },
    picpus: { name: 'Picpus', x: 44, y: 31.5 },
    avron: { name: 'Avron', x: 43, y: 28 },
    'alexandre-dumas': { name: 'Alexandre Dumas', x: 43, y: 26 },
    'philippe-auguste': { name: 'Philippe Auguste', x: 42, y: 24.5 },
    menilmontant: { name: 'Ménilmontant', x: 41, y: 21.5 },
    couronnes: { name: 'Couronnes', x: 40, y: 20 },
    'colonel-fabien': { name: 'Colonel Fabien', x: 38, y: 17 },
    'la-chapelle': { name: 'La Chapelle', x: 34.5, y: 13.5 },
    anvers: { name: 'Anvers', x: 31, y: 15 },
    blanche: { name: 'Blanche', x: 28, y: 15 },
    rome: { name: 'Rome', x: 24, y: 15.5 },
    monceau: { name: 'Monceau', x: 21.5, y: 17.5 },
    courcelles: { name: 'Courcelles', x: 19.5, y: 17.5 },
    ternes: { name: 'Ternes', x: 18, y: 17.5 },
    'victor-hugo': { name: 'Victor Hugo', x: 15, y: 20.5 },
    'porte-dauphine': { name: 'Porte Dauphine', x: 13, y: 20.5 },
    bolivar: { name: 'Bolivar', x: 39.5, y: 16.5 },
    'buttes-chaumont': { name: 'Buttes Chaumont', x: 41.5, y: 16.5 },
    botzaris: { name: 'Botzaris', x: 43.5, y: 16.5 },
    'pre-saint-gervais': { name: 'Pré Saint-Gervais', x: 46, y: 16.5 },
    'eglise-d-auteuil': { name: 'Église d\'Auteuil', x: 9, y: 30 },
    'porte-d-auteuil': { name: 'Porte d\'Auteuil', x: 5, y: 30 },
    'villejuif-louis-aragon': { name: 'Villejuif - Louis Aragon', x: 35, y: 51 },
    'villejuif-paul-vaillant-couturier': { name: 'Villejuif - Paul Vaillant-Couturier', x: 34.5, y: 49 },
    'villejuif-leo-lagrange': { name: 'Villejuif - Léo Lagrange', x: 34.5, y: 46.5 },
    'le-kremlin-bicetre': { name: 'Le Kremlin-Bicêtre', x: 34, y: 44.5 },
    brochant: { name: 'Brochant', x: 24.5, y: 13 },
    'mairie-de-clichy': { name: 'Mairie de Clichy', x: 23, y: 9.5 },
    'gabriel-peri': { name: 'Gabriel Péri', x: 21.5, y: 7.5 },
    'les-agnettes': { name: 'Les Agnettes', x: 20, y: 6 },
    'asnieres-gennevilliers-les-courtilles': { name: 'Asnières-Gennevilliers–Les Courtilles', x: 18.5, y: 4.5 },
    danube: { name: 'Danube', x: 45, y: 15 },
  },
};
