// Prague's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'prague',
  name: 'Prague',
  system: 'Metro',
  country: 'Czechia',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'a',
      short: 'A',
      name: 'Metro A',
      colour: '#75ac40',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['nemocnice-motol', 'petriny', 'nadrazi-veleslavin', 'borislavka', 'dejvicka', 'hradcanska', 'malostranska', 'staromestska', 'mustek', 'muzeum', 'namesti-miru', 'jiriho-z-podebrad', 'zelivskeho', 'strasnicka', 'skalka', 'depo-hostivar'],
      ],
    },
    {
      id: 'b',
      short: 'B',
      name: 'Metro B',
      colour: '#f5d30f',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['cerny-most', 'rajska-zahrada', 'hloubetin', 'kolbenova', 'vysocanska', 'ceskomoravska', 'palmovka', 'invalidovna', 'krizikova', 'florenc', 'namesti-republiky', 'mustek', 'narodni-trida', 'karlovo-namesti', 'andel', 'smichovske-nadrazi', 'radlicka', 'jinonice', 'nove-butovice', 'hurka', 'luziny', 'luka', 'stodulky', 'zlicin'],
      ],
    },
    {
      id: 'c',
      short: 'C',
      name: 'Metro C',
      colour: '#e63323',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['letnany', 'prosek', 'strizkov', 'ladvi', 'kobylisy', 'nadrazi-holesovice', 'vltavska', 'florenc', 'hlavni-nadrazi', 'muzeum', 'i-p-pavlova', 'vysehrad', 'prazskeho-povstani', 'pankrac', 'budejovicka', 'kacerov', 'roztyly', 'chodov', 'opatov', 'haje'],
      ],
    },
  ],
  times: {
    'nemocnice-motol petriny': 3,
    'borislavka dejvicka': 5,
    'jiriho-z-podebrad zelivskeho': 4,
    'zelivskeho strasnicka': 3,
    'strasnicka skalka': 3,
    'cerny-most rajska-zahrada': 3,
    'rajska-zahrada hloubetin': 4,
    'hloubetin kolbenova': 3,
    'ceskomoravska palmovka': 3,
    'palmovka invalidovna': 3,
    'mustek narodni-trida': 1,
    'smichovske-nadrazi radlicka': 3,
    'radlicka jinonice': 3,
    'jinonice nove-butovice': 3,
    'stodulky zlicin': 3,
    'letnany prosek': 3,
    'strizkov ladvi': 3,
    'ladvi kobylisy': 3,
    'kobylisy nadrazi-holesovice': 4,
    'hlavni-nadrazi muzeum': 1,
    'i-p-pavlova vysehrad': 3,
    'kacerov roztyly': 3,
    'roztyly chodov': 3,
    'chodov opatov': 3,
    'opatov haje': 3,
  },
  stations: {
    letnany: { name: 'Letňany', x: 29, y: 1.5 },
    prosek: { name: 'Prosek', x: 27, y: 1.5 },
    strizkov: { name: 'Střížkov', x: 25.5, y: 0 },
    ladvi: { name: 'Ládví', x: 23.5, y: 0 },
    kobylisy: { name: 'Kobylisy', x: 22, y: 1.5 },
    'nadrazi-holesovice': { name: 'Nádraží Holešovice', x: 20.5, y: 3 },
    vltavska: { name: 'Vltavská', x: 20.5, y: 5 },
    florenc: { name: 'Florenc', x: 20.5, y: 7 },
    'hlavni-nadrazi': { name: 'Hlavní nádraží', x: 20.5, y: 9 },
    muzeum: { name: 'Muzeum', x: 19, y: 10.5 },
    'i-p-pavlova': { name: 'I. P. Pavlova', x: 19, y: 12.5 },
    vysehrad: { name: 'Vyšehrad', x: 19, y: 14.5 },
    'prazskeho-povstani': { name: 'Pražského povstání', x: 19, y: 16.5 },
    pankrac: { name: 'Pankrác', x: 21, y: 16.5 },
    budejovicka: { name: 'Budějovická', x: 22.5, y: 18 },
    kacerov: { name: 'Kačerov', x: 24.5, y: 18 },
    roztyly: { name: 'Roztyly', x: 26.5, y: 18 },
    chodov: { name: 'Chodov', x: 27.5, y: 19 },
    opatov: { name: 'Opatov', x: 29.5, y: 19 },
    haje: { name: 'Háje', x: 31.5, y: 19 },
    'nemocnice-motol': { name: 'Nemocnice Motol', x: 7, y: 9 },
    petriny: { name: 'Petřiny', x: 7, y: 7 },
    'nadrazi-veleslavin': { name: 'Nádraží Veleslavín', x: 8.5, y: 6 },
    borislavka: { name: 'Bořislavka', x: 10.5, y: 5.5 },
    dejvicka: { name: 'Dejvická', x: 12.5, y: 5.5 },
    hradcanska: { name: 'Hradčanská', x: 14.5, y: 5.5 },
    malostranska: { name: 'Malostranská', x: 14.5, y: 7.5 },
    staromestska: { name: 'Staroměstská', x: 16.5, y: 7.5 },
    mustek: { name: 'Můstek', x: 18, y: 9 },
    'namesti-miru': { name: 'Náměstí Míru', x: 20.5, y: 12 },
    'jiriho-z-podebrad': { name: 'Jiřího z Poděbrad', x: 22, y: 10.5, aka: ['Jiřího z Poděbrad'] },
    zelivskeho: { name: 'Želivského', x: 24, y: 10.5 },
    strasnicka: { name: 'Strašnická', x: 26, y: 10.5 },
    skalka: { name: 'Skalka', x: 27.5, y: 12 },
    'depo-hostivar': { name: 'Depo Hostivař', x: 29, y: 10.5 },
    'cerny-most': { name: 'Černý Most', x: 37, y: 3 },
    'rajska-zahrada': { name: 'Rajská zahrada', x: 35, y: 3 },
    hloubetin: { name: 'Hloubětín', x: 32.5, y: 3 },
    kolbenova: { name: 'Kolbenova', x: 30.5, y: 3 },
    vysocanska: { name: 'Vysočanská', x: 28.5, y: 3 },
    ceskomoravska: { name: 'Českomoravská', x: 27.5, y: 4.5 },
    palmovka: { name: 'Palmovka', x: 25.5, y: 4.5 },
    invalidovna: { name: 'Invalidovna', x: 24, y: 5.5 },
    krizikova: { name: 'Křižíkova', x: 22.5, y: 7 },
    'namesti-republiky': { name: 'Náměstí Republiky', x: 18, y: 7 },
    'narodni-trida': { name: 'Národní třída', x: 16.5, y: 10.5 },
    'karlovo-namesti': { name: 'Karlovo náměstí', x: 16.5, y: 12.5 },
    andel: { name: 'Anděl', x: 14.5, y: 12.5 },
    'smichovske-nadrazi': { name: 'Smíchovské nádraží', x: 15, y: 14.5 },
    radlicka: { name: 'Radlická', x: 13, y: 14.5 },
    jinonice: { name: 'Jinonice', x: 11, y: 14.5 },
    'nove-butovice': { name: 'Nové Butovice', x: 9, y: 14.5 },
    hurka: { name: 'Hůrka', x: 7, y: 14.5 },
    luziny: { name: 'Lužiny', x: 5.5, y: 16 },
    luka: { name: 'Luka', x: 3.5, y: 16 },
    stodulky: { name: 'Stodůlky', x: 1.5, y: 16 },
    zlicin: { name: 'Zličín', x: 0, y: 14.5 },
  },
};
