// Rome's Metropolitana, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'rome',
  name: 'Rome',
  system: 'Metropolitana',
  country: 'Italy',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'a',
      short: 'A',
      name: 'Linea A',
      colour: '#f68b1f',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['battistini', 'cornelia', 'baldo-degli-ubaldi', 'valle-aurelia', 'cipro', 'ottaviano', 'lepanto', 'flaminio', 'spagna', 'barberini', 'repubblica', 'termini', 'vittorio-emanuele', 'manzoni', 'san-giovanni', 're-di-roma', 'ponte-lungo', 'furio-camillo', 'colli-albani', 'arco-di-travertino', 'porta-furba-quadraro', 'numidio-quadrato', 'lucio-sestio', 'giulio-agricola', 'subaugusta', 'cinecitta', 'anagnina'],
      ],
    },
    {
      id: 'b',
      short: 'B',
      name: 'Linea B',
      colour: '#3783c6',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['rebibbia', 'ponte-mammolo', 'santa-maria-del-soccorso', 'pietralata', 'monti-tiburtini', 'quintiliani', 'tiburtina-fs', 'bologna', 'policlinico', 'castro-pretorio', 'termini', 'cavour', 'colosseo', 'circo-massimo', 'piramide', 'garbatella', 'basilica-san-paolo', 'marconi', 'eur-magliana', 'eur-palasport', 'eur-fermi', 'laurentina'],
        ['jonio', 'conca-d-oro', 'libia', 'sant-agnese-annibaliano', 'bologna', 'policlinico', 'castro-pretorio', 'termini', 'cavour', 'colosseo', 'circo-massimo', 'piramide', 'garbatella', 'basilica-san-paolo', 'marconi', 'eur-magliana', 'eur-palasport', 'eur-fermi', 'laurentina'],
      ],
    },
    {
      id: 'c',
      short: 'C',
      name: 'Linea C',
      colour: '#008751',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['monte-compatri-pantano', 'graniti', 'finocchio', 'bolognetta', 'borghesiana', 'due-leoni-fontana-candida', 'grotte-celoni', 'torre-gaia', 'torre-angela', 'torrenova', 'giardinetti', 'torre-maura', 'torre-spaccata', 'alessandrino', 'parco-di-centocelle', 'mirti', 'gardenie', 'teano', 'malatesta', 'pigneto', 'lodi', 'san-giovanni', 'porta-metronia', 'colosseo-fori-imperiali'],
      ],
    },
    {
      id: 'metromare',
      short: 'M',
      name: 'Metromare',
      colour: '#7eb9e6',
      text: '#1a1a1a',
      minutes: 5,
      branches: [
        ['porta-san-paolo', 'basilica-san-paolo', 'eur-magliana', 'tor-di-valle', 'vitinia', 'casal-bernocchi-centro-giano', 'acilia', 'acilia-sud-dragona', 'ostia-antica', 'lido-nord', 'lido-centro', 'stella-polare', 'castel-fusano', 'cristoforo-colombo'],
      ],
    },
  ],
  times: {
    'battistini cornelia': 3,
    'spagna barberini': 1,
    'repubblica termini': 1,
    'vittorio-emanuele manzoni': 1,
    'san-giovanni re-di-roma': 1,
    'ponte-lungo furio-camillo': 1,
    'porta-furba-quadraro numidio-quadrato': 1,
    'numidio-quadrato lucio-sestio': 1,
    'lucio-sestio giulio-agricola': 1,
    'giulio-agricola subaugusta': 1,
    'cinecitta anagnina': 3,
    'santa-maria-del-soccorso pietralata': 1,
    'policlinico castro-pretorio': 1,
    'cavour colosseo': 1,
    'garbatella basilica-san-paolo': 3,
    'marconi eur-magliana': 3,
    'eur-palasport eur-fermi': 1,
    'conca-d-oro libia': 3,
    'sant-agnese-annibaliano bologna': 3,
    'bolognetta borghesiana': 3,
    'torrenova giardinetti': 1,
    'porta-metronia colosseo-fori-imperiali': 3,
    'eur-magliana tor-di-valle': 6,
    'tor-di-valle vitinia': 8,
    'casal-bernocchi-centro-giano acilia': 3,
    'acilia acilia-sud-dragona': 4,
    'acilia-sud-dragona ostia-antica': 8,
    'lido-nord lido-centro': 2,
    'lido-centro stella-polare': 3,
    'stella-polare castel-fusano': 3,
    'castel-fusano cristoforo-colombo': 3,
  },
  stations: {
    rebibbia: { name: 'Rebibbia', x: 43.5, y: 5 },
    'ponte-mammolo': { name: 'Ponte Mammolo', x: 42, y: 6.5 },
    'santa-maria-del-soccorso': { name: 'Santa Maria del Soccorso', x: 42, y: 8.5 },
    pietralata: { name: 'Pietralata', x: 40, y: 8.5 },
    'monti-tiburtini': { name: 'Monti Tiburtini', x: 38.5, y: 7 },
    quintiliani: { name: 'Quintiliani', x: 36.5, y: 7.5 },
    'tiburtina-fs': { name: 'Tiburtina FS', x: 35, y: 9 },
    bologna: { name: 'Bologna', x: 33.5, y: 7.5 },
    policlinico: { name: 'Policlinico', x: 32, y: 9.5 },
    'castro-pretorio': { name: 'Castro Pretorio', x: 30, y: 9.5 },
    termini: { name: 'Termini', x: 28.5, y: 11.5 },
    cavour: { name: 'Cavour', x: 26.5, y: 13.5 },
    colosseo: { name: 'Colosseo', x: 24.5, y: 15.5 },
    'circo-massimo': { name: 'Circo Massimo', x: 23.5, y: 18 },
    piramide: { name: 'Piramide', x: 23, y: 21 },
    garbatella: { name: 'Garbatella', x: 22.5, y: 23.5 },
    'basilica-san-paolo': { name: 'Basilica San Paolo', x: 20, y: 25.5 },
    marconi: { name: 'Marconi', x: 19, y: 27 },
    'eur-magliana': { name: 'EUR Magliana', x: 18, y: 28 },
    'eur-palasport': { name: 'EUR Palasport', x: 19, y: 29.5 },
    'eur-fermi': { name: 'EUR Fermi', x: 20.5, y: 31 },
    laurentina: { name: 'Laurentina', x: 22.5, y: 31 },
    battistini: { name: 'Battistini', x: 13, y: 8 },
    cornelia: { name: 'Cornelia', x: 14.5, y: 9 },
    'baldo-degli-ubaldi': { name: 'Baldo degli Ubaldi', x: 16, y: 10.5 },
    'valle-aurelia': { name: 'Valle Aurelia', x: 17.5, y: 9 },
    cipro: { name: 'Cipro', x: 18.5, y: 7.5 },
    ottaviano: { name: 'Ottaviano', x: 20.5, y: 7.5 },
    lepanto: { name: 'Lepanto', x: 22.5, y: 7.5 },
    flaminio: { name: 'Flaminio', x: 24.5, y: 7.5 },
    spagna: { name: 'Spagna', x: 25.5, y: 9 },
    barberini: { name: 'Barberini', x: 26, y: 11 },
    repubblica: { name: 'Repubblica', x: 27, y: 10 },
    'vittorio-emanuele': { name: 'Vittorio Emanuele', x: 30.5, y: 12.5 },
    manzoni: { name: 'Manzoni', x: 29, y: 13.5 },
    'san-giovanni': { name: 'San Giovanni', x: 31, y: 15 },
    're-di-roma': { name: 'Re di Roma', x: 32.5, y: 16 },
    'ponte-lungo': { name: 'Ponte Lungo', x: 32.5, y: 18 },
    'furio-camillo': { name: 'Furio Camillo', x: 34.5, y: 18 },
    'colli-albani': { name: 'Colli Albani', x: 34.5, y: 19.5 },
    'arco-di-travertino': { name: 'Arco di Travertino', x: 36, y: 21 },
    'porta-furba-quadraro': { name: 'Porta Furba/Quadraro', x: 38, y: 21 },
    'numidio-quadrato': { name: 'Numidio Quadrato', x: 40, y: 21 },
    'lucio-sestio': { name: 'Lucio Sestio', x: 40, y: 22.5 },
    'giulio-agricola': { name: 'Giulio Agricola', x: 42, y: 22.5 },
    subaugusta: { name: 'Subaugusta', x: 43.5, y: 24 },
    cinecitta: { name: 'Cinecittà', x: 45, y: 25.5 },
    anagnina: { name: 'Anagnina', x: 46.5, y: 27 },
    'porta-san-paolo': { name: 'Porta San Paolo', x: 20.5, y: 23.5 },
    'tor-di-valle': { name: 'Tor di Valle', x: 15.5, y: 30.5 },
    vitinia: { name: 'Vitinia', x: 13, y: 32.5 },
    'casal-bernocchi-centro-giano': { name: 'Casal Bernocchi-Centro Giano', x: 10.5, y: 35 },
    acilia: { name: 'Acilia', x: 8.5, y: 37 },
    'acilia-sud-dragona': { name: 'Acilia Sud - Dragona', x: 6, y: 39 },
    'ostia-antica': { name: 'Ostia Antica', x: 4, y: 41 },
    'lido-nord': { name: 'Lido Nord', x: 2, y: 43 },
    'lido-centro': { name: 'Lido Centro', x: 0.5, y: 44.5 },
    'stella-polare': { name: 'Stella Polare', x: 0, y: 47 },
    'castel-fusano': { name: 'Castel Fusano', x: 1, y: 48.5 },
    'cristoforo-colombo': { name: 'Cristoforo Colombo', x: 2.5, y: 50 },
    'monte-compatri-pantano': { name: 'Monte Compatri - Pantano', x: 71, y: 19.5 },
    graniti: { name: 'Graniti', x: 69, y: 19.5 },
    finocchio: { name: 'Finocchio', x: 67, y: 19.5 },
    bolognetta: { name: 'Bolognetta', x: 65, y: 19.5 },
    borghesiana: { name: 'Borghesiana', x: 63, y: 19.5 },
    'due-leoni-fontana-candida': { name: 'Due Leoni - Fontana Candida', x: 61, y: 19.5 },
    'grotte-celoni': { name: 'Grotte Celoni', x: 59, y: 19.5 },
    'torre-gaia': { name: 'Torre Gaia', x: 57, y: 19.5 },
    'torre-angela': { name: 'Torre Angela', x: 55, y: 19.5 },
    torrenova: { name: 'Torrenova', x: 53, y: 19.5 },
    giardinetti: { name: 'Giardinetti', x: 51, y: 19.5 },
    'torre-maura': { name: 'Torre Maura', x: 49, y: 19.5 },
    'torre-spaccata': { name: 'Torre Spaccata', x: 46.5, y: 19.5 },
    alessandrino: { name: 'Alessandrino', x: 45, y: 18 },
    'parco-di-centocelle': { name: 'Parco di Centocelle', x: 43, y: 18 },
    mirti: { name: 'Mirti', x: 43, y: 16 },
    gardenie: { name: 'Gardenie', x: 41.5, y: 14.5 },
    teano: { name: 'Teano', x: 39.5, y: 14.5 },
    malatesta: { name: 'Malatesta', x: 37.5, y: 14.5 },
    pigneto: { name: 'Pigneto', x: 35, y: 14.5 },
    lodi: { name: 'Lodi', x: 33, y: 14.5 },
    'porta-metronia': { name: 'Porta Metronia', x: 29.5, y: 16 },
    'colosseo-fori-imperiali': { name: 'Colosseo – Fori Imperiali', x: 28, y: 15 },
    jonio: { name: 'Jonio', x: 35, y: 0 },
    'conca-d-oro': { name: 'Conca d\'Oro', x: 35, y: 2 },
    libia: { name: 'Libia', x: 34, y: 3.5 },
    'sant-agnese-annibaliano': { name: 'Sant\'Agnese/Annibaliano', x: 33.5, y: 5.5 },
  },
};
