// Rotterdam's Metro, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'rotterdam',
  name: 'Rotterdam',
  system: 'Metro',
  country: 'Netherlands',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'a',
      short: 'A',
      name: 'Metro A',
      colour: '#00aa50',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['binnenhof', 'romeynshof', 'graskruid', 'alexander', 'oosterflank', 'prinsenlaan', 'schenkel', 'capelsebrug', 'kralingse-zoom', 'voorschoterlaan', 'gerdesiaweg', 'oostplein', 'blaak', 'beurs', 'eendrachtsplein', 'dijkzigt', 'coolhaven', 'delfshaven', 'marconiplein', 'schiedam-centrum'],
      ],
    },
    {
      id: 'b',
      short: 'B',
      name: 'Metro B',
      colour: '#ffd301',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['nesselande', 'de-tochten', 'ambachtsland', 'nieuw-verlaat', 'hesseplaats', 'graskruid', 'alexander', 'oosterflank', 'prinsenlaan', 'schenkel', 'capelsebrug', 'kralingse-zoom', 'voorschoterlaan', 'gerdesiaweg', 'oostplein', 'blaak', 'beurs', 'eendrachtsplein', 'dijkzigt', 'coolhaven', 'delfshaven', 'marconiplein', 'schiedam-centrum', 'schiedam-nieuwland', 'vlaardingen-oost', 'vlaardingen-centrum', 'vlaardingen-west', 'maassluis-centrum', 'maassluis-west', 'steendijkpolder', 'hoek-van-holland-haven', 'hoek-van-holland-strand'],
      ],
    },
    {
      id: 'c',
      short: 'C',
      name: 'Metro C',
      colour: '#ef1f1f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['de-akkers', 'heemraadlaan', 'spijkenisse-centrum', 'zalmplaat', 'hoogvliet', 'tussenwater', 'pernis', 'vijfsluizen', 'troelstralaan', 'parkweg', 'schiedam-centrum', 'marconiplein', 'delfshaven', 'coolhaven', 'dijkzigt', 'eendrachtsplein', 'beurs', 'blaak', 'oostplein', 'gerdesiaweg', 'voorschoterlaan', 'kralingse-zoom', 'capelsebrug', 'slotlaan', 'capelle-centrum', 'de-terp'],
      ],
    },
    {
      id: 'd',
      short: 'D',
      name: 'Metro D',
      colour: '#1bc5e9',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['de-akkers', 'heemraadlaan', 'spijkenisse-centrum', 'zalmplaat', 'hoogvliet', 'tussenwater', 'poortugaal', 'rhoon', 'slinge', 'zuidplein', 'maashaven', 'rijnhaven', 'wilhelminaplein', 'leuvehaven', 'beurs', 'stadhuis', 'rotterdam-centraal'],
      ],
    },
    {
      id: 'e',
      short: 'E',
      name: 'Metro E',
      colour: '#1a389a',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['den-haag-centraal', 'den-haag-laan-van-noi', 'voorburg-t-loo', 'leidschendam-voorburg', 'forepark', 'leidschenveen', 'nootdorp', 'pijnacker-centrum', 'pijnacker-zuid', 'berkel-westpolder', 'rodenrijs', 'meijersplein-airport', 'melanchthonweg', 'blijdorp', 'rotterdam-centraal', 'stadhuis', 'beurs', 'leuvehaven', 'wilhelminaplein', 'rijnhaven', 'maashaven', 'zuidplein', 'slinge'],
      ],
    },
  ],
  times: {
    'binnenhof romeynshof': 1,
    'oosterflank prinsenlaan': 1,
    'schenkel capelsebrug': 3,
    'capelsebrug kralingse-zoom': 4,
    'kralingse-zoom voorschoterlaan': 3,
    'voorschoterlaan gerdesiaweg': 1,
    'beurs eendrachtsplein': 1,
    'marconiplein schiedam-centrum': 4,
    'nesselande de-tochten': 3,
    'schiedam-centrum schiedam-nieuwland': 4,
    'schiedam-nieuwland vlaardingen-oost': 4,
    'vlaardingen-oost vlaardingen-centrum': 3,
    'vlaardingen-centrum vlaardingen-west': 4,
    'vlaardingen-west maassluis-centrum': 9,
    'maassluis-centrum maassluis-west': 4,
    'steendijkpolder hoek-van-holland-haven': 16,
    'hoek-van-holland-haven hoek-van-holland-strand': 4,
    'spijkenisse-centrum zalmplaat': 4,
    'tussenwater pernis': 5,
    'pernis vijfsluizen': 6,
    'vijfsluizen troelstralaan': 3,
    'schiedam-centrum marconiplein': 4,
    'eendrachtsplein beurs': 1,
    'gerdesiaweg voorschoterlaan': 1,
    'voorschoterlaan kralingse-zoom': 3,
    'kralingse-zoom capelsebrug': 4,
    'capelsebrug slotlaan': 3,
    'tussenwater poortugaal': 3,
    'poortugaal rhoon': 4,
    'rhoon slinge': 9,
    'slinge zuidplein': 3,
    'zuidplein maashaven': 3,
    'rijnhaven wilhelminaplein': 1,
    'leuvehaven beurs': 1,
    'beurs stadhuis': 1,
    'forepark leidschenveen': 2,
    'leidschenveen nootdorp': 4,
    'nootdorp pijnacker-centrum': 7,
    'pijnacker-centrum pijnacker-zuid': 4,
    'pijnacker-zuid berkel-westpolder': 4,
    'berkel-westpolder rodenrijs': 4,
    'rodenrijs meijersplein-airport': 5,
    'meijersplein-airport melanchthonweg': 2,
    'melanchthonweg blijdorp': 4,
    'blijdorp rotterdam-centraal': 2,
    'rotterdam-centraal stadhuis': 2,
    'stadhuis beurs': 1,
    'beurs leuvehaven': 1,
    'leuvehaven wilhelminaplein': 2,
    'wilhelminaplein rijnhaven': 1,
    'rijnhaven maashaven': 2,
  },
  stations: {
    'den-haag-centraal': { name: 'Den Haag Centraal', x: 14.5, y: 0 },
    'den-haag-laan-van-noi': { name: 'Den Haag Laan van NOI', x: 16.5, y: 0 },
    'voorburg-t-loo': { name: 'Voorburg \'t Loo', x: 19, y: 0 },
    'leidschendam-voorburg': { name: 'Leidschendam-Voorburg', x: 20.5, y: 1.5 },
    forepark: { name: 'Forepark', x: 22, y: 3.5 },
    leidschenveen: { name: 'Leidschenveen', x: 23.5, y: 5 },
    nootdorp: { name: 'Nootdorp', x: 25, y: 6.5 },
    'pijnacker-centrum': { name: 'Pijnacker Centrum', x: 26.5, y: 8.5 },
    'pijnacker-zuid': { name: 'Pijnacker Zuid', x: 26.5, y: 11 },
    'berkel-westpolder': { name: 'Berkel Westpolder', x: 27, y: 13 },
    rodenrijs: { name: 'Rodenrijs', x: 27, y: 15.5 },
    'meijersplein-airport': { name: 'Meijersplein / Airport', x: 27, y: 18 },
    melanchthonweg: { name: 'Melanchthonweg', x: 27.5, y: 20 },
    blijdorp: { name: 'Blijdorp', x: 27.5, y: 22.5 },
    'rotterdam-centraal': { name: 'Rotterdam Centraal', x: 27.5, y: 24.5 },
    stadhuis: { name: 'Stadhuis', x: 29.5, y: 25 },
    beurs: { name: 'Beurs', x: 29.5, y: 27 },
    leuvehaven: { name: 'Leuvehaven', x: 29.5, y: 29.5 },
    wilhelminaplein: { name: 'Wilhelminaplein', x: 31, y: 31 },
    rijnhaven: { name: 'Rijnhaven', x: 30.5, y: 33 },
    maashaven: { name: 'Maashaven', x: 29, y: 34.5 },
    zuidplein: { name: 'Zuidplein', x: 27.5, y: 36 },
    slinge: { name: 'Slinge', x: 25.5, y: 37.5 },
    'de-akkers': { name: 'De Akkers', x: 11.5, y: 45 },
    heemraadlaan: { name: 'Heemraadlaan', x: 13, y: 43.5 },
    'spijkenisse-centrum': { name: 'Spijkenisse Centrum', x: 14.5, y: 42 },
    zalmplaat: { name: 'Zalmplaat', x: 16, y: 40.5 },
    hoogvliet: { name: 'Hoogvliet', x: 17.5, y: 39 },
    tussenwater: { name: 'Tussenwater', x: 19, y: 37.5 },
    poortugaal: { name: 'Poortugaal', x: 21, y: 37.5 },
    rhoon: { name: 'Rhoon', x: 23.5, y: 37.5 },
    nesselande: { name: 'Nesselande', x: 44, y: 16.5 },
    'de-tochten': { name: 'De Tochten', x: 44, y: 18.5 },
    ambachtsland: { name: 'Ambachtsland', x: 43, y: 20 },
    'nieuw-verlaat': { name: 'Nieuw Verlaat', x: 41.5, y: 18.5 },
    hesseplaats: { name: 'Hesseplaats', x: 39.5, y: 18.5 },
    graskruid: { name: 'Graskruid', x: 39, y: 20.5 },
    alexander: { name: 'Alexander', x: 39, y: 22.5 },
    oosterflank: { name: 'Oosterflank', x: 41, y: 22.5 },
    prinsenlaan: { name: 'Prinsenlaan', x: 39.5, y: 24 },
    schenkel: { name: 'Schenkel', x: 41, y: 25.5 },
    capelsebrug: { name: 'Capelsebrug', x: 39.5, y: 27 },
    'kralingse-zoom': { name: 'Kralingse Zoom', x: 37, y: 27 },
    voorschoterlaan: { name: 'Voorschoterlaan', x: 35, y: 27 },
    gerdesiaweg: { name: 'Gerdesiaweg', x: 33.5, y: 25.5 },
    oostplein: { name: 'Oostplein', x: 31.5, y: 27 },
    blaak: { name: 'Blaak', x: 31.5, y: 28.5 },
    eendrachtsplein: { name: 'Eendrachtsplein', x: 27.5, y: 27 },
    dijkzigt: { name: 'Dijkzigt', x: 27.5, y: 29 },
    coolhaven: { name: 'Coolhaven', x: 25.5, y: 29 },
    delfshaven: { name: 'Delfshaven', x: 23.5, y: 29 },
    marconiplein: { name: 'Marconiplein', x: 21, y: 29 },
    'schiedam-centrum': { name: 'Schiedam Centrum', x: 19, y: 29 },
    'schiedam-nieuwland': { name: 'Schiedam Nieuwland', x: 16, y: 29 },
    'vlaardingen-oost': { name: 'Vlaardingen Oost', x: 14, y: 29 },
    'vlaardingen-centrum': { name: 'Vlaardingen Centrum', x: 11.5, y: 29 },
    'vlaardingen-west': { name: 'Vlaardingen West', x: 9, y: 29 },
    'maassluis-centrum': { name: 'Maassluis Centrum', x: 6.5, y: 28.5 },
    'maassluis-west': { name: 'Maassluis West', x: 5, y: 27 },
    steendijkpolder: { name: 'Steendijkpolder', x: 3, y: 25.5 },
    'hoek-van-holland-haven': { name: 'Hoek van Holland Haven', x: 1.5, y: 24 },
    'hoek-van-holland-strand': { name: 'Hoek van Holland Strand', x: 0, y: 22.5 },
    pernis: { name: 'Pernis', x: 18.5, y: 35.5 },
    vijfsluizen: { name: 'Vijfsluizen', x: 18, y: 33.5 },
    troelstralaan: { name: 'Troelstralaan', x: 18, y: 31.5 },
    parkweg: { name: 'Parkweg', x: 17.5, y: 29.5 },
    slotlaan: { name: 'Slotlaan', x: 41.5, y: 27 },
    'capelle-centrum': { name: 'Capelle Centrum', x: 43, y: 25.5 },
    'de-terp': { name: 'De Terp', x: 44.5, y: 24.5 },
    binnenhof: { name: 'Binnenhof', x: 36.5, y: 20.5 },
    romeynshof: { name: 'Romeynshof', x: 38, y: 19.5 },
  },
};
