// Seoul's Subway, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'seoul',
  name: 'Seoul',
  system: 'Subway',
  country: 'South Korea',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Line 1',
      colour: '#004a85',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['yeoncheon', 'jeongok', 'cheongsan', 'soyosan', 'dongducheon', 'bosan', 'dongducheonjungang', 'jihaeng', 'deokjeong-seojeong-college', 'deokgye', 'yangju', 'nogyang', 'ganeung', 'uijeongbu', 'hoeryong', 'mangwolsa-shinhan-university', 'dobongsan', 'dobong', 'banghak-dobong-gu-office', 'chang-dong', 'nokcheon', 'wolgye-induk-university', 'kwangwoon-university', 'seokgye', 'sinimun-korea-national-university-of-arts', 'hankuk-university-of-foreign-studies', 'hoegi', 'cheongnyangni-university-of-seoul', 'jegidong', 'sinseol-dong', 'dongmyo', 'dongdaemun', 'jongno-5-o-ga', 'jongno-3-sam-ga', 'jonggak', 'city-hall', 'seoul', 'namyeong', 'yongsan', 'noryangjin', 'daebang', 'singil', 'yeongdeungpo', 'sindorim', 'guro', 'guil', 'gaebong', 'oryu-dong', 'onsu', 'yeokgok', 'sosa', 'bucheon', 'jung-dong', 'songnae', 'bugae', 'bupyeong', 'baegun', 'dongam', 'ganseok', 'juan', 'dohwa', 'jemulpo', 'dowon', 'dongincheon', 'incheon'],
        ['incheon', 'dongincheon', 'dowon', 'jemulpo', 'dohwa', 'juan', 'ganseok', 'dongam', 'baegun', 'bupyeong', 'bugae', 'songnae', 'jung-dong', 'bucheon', 'sosa', 'yeokgok', 'onsu', 'oryu-dong', 'gaebong', 'guil', 'guro', 'sindorim', 'yeongdeungpo', 'singil', 'daebang', 'noryangjin', 'yongsan', 'namyeong', 'seoul', 'city-hall', 'jonggak', 'jongno-3-sam-ga', 'jongno-5-o-ga', 'dongdaemun', 'dongmyo', 'sinseol-dong', 'jegidong', 'cheongnyangni-university-of-seoul', 'hoegi', 'hankuk-university-of-foreign-studies', 'sinimun-korea-national-university-of-arts', 'seokgye', 'kwangwoon-university', 'wolgye-induk-university', 'nokcheon', 'chang-dong', 'banghak-dobong-gu-office', 'dobong', 'dobongsan', 'mangwolsa-shinhan-university', 'hoeryong', 'uijeongbu', 'ganeung', 'nogyang', 'yangju', 'deokgye', 'deokjeong-seojeong-college', 'jihaeng', 'dongducheonjungang-shinhan-university-campus-2', 'bosan', 'dongducheon', 'soyosan', 'cheongsan', 'jeongok', 'yeoncheon'],
        ['incheon', 'dongincheon', 'dowon', 'jemulpo', 'dohwa', 'juan', 'ganseok', 'dongam', 'baegun', 'bupyeong', 'bugae', 'songnae', 'jung-dong', 'bucheon', 'sosa', 'yeokgok', 'onsu', 'oryu-dong', 'gaebong', 'guil', 'guro', 'sindorim', 'yeongdeungpo', 'singil', 'daebang', 'noryangjin', 'yongsan', 'namyeong', 'seoul', 'city-hall', 'jonggak', 'jongno-3-sam-ga', 'jongno-5-o-ga', 'dongdaemun', 'dongmyo', 'sinseol-dong', 'jegidong', 'cheongnyangni-university-of-seoul', 'hoegi', 'hankuk-university-of-foreign-studies', 'sinimun-korea-national-university-of-arts', 'seokgye', 'kwangwoon-university', 'wolgye-induk-university', 'nokcheon', 'chang-dong', 'banghak-dobong-gu-office', 'dobong', 'dobongsan', 'mangwolsa-shinhan-university', 'hoeryong', 'uijeongbu', 'ganeung', 'nogyang', 'yangju', 'deokgye', 'deokjeong-seojeong-college', 'dongducheonjungang-shinhan-university-campus-2', 'bosan', 'dongducheon'],
        ['kwangwoon-university', 'seokgye', 'sinimun-korea-national-university-of-arts', 'hankuk-university-of-foreign-studies', 'hoegi', 'cheongnyangni-university-of-seoul', 'jegidong', 'sinseol-dong', 'dongmyo', 'dongdaemun', 'jongno-5-o-ga', 'jongno-3-sam-ga', 'jonggak', 'city-hall', 'seoul', 'namyeong', 'yongsan', 'noryangjin', 'daebang', 'singil', 'yeongdeungpo', 'sindorim', 'guro', 'gasan-digital-complex', 'doksan', 'geumcheon-gu-office', 'seoksu', 'gwanak', 'anyang', 'myeonghak', 'geumjeong', 'gunpo', 'dangjeong', 'uiwang', 'sungkyunkwan-univ', 'hwaseo', 'suwon', 'seryu', 'byeongjeom', 'sema', 'osan-college', 'osan', 'jinwi', 'songtan', 'seojeong-ri', 'pyeongtaek-jije', 'pyeongtaek', 'seonghwan', 'jiksan', 'dujeong', 'cheonan', 'bongmyeong', 'ssangyong', 'asan', 'tangjeong', 'baebang', 'onyangoncheon', 'sinchang'],
        ['sinchang', 'onyangoncheon', 'baebang', 'tangjeong', 'asan', 'ssangyong', 'bongmyeong', 'cheonan', 'dujeong', 'jiksan', 'seonghwan', 'pyeongtaek', 'pyeongtaek-jije', 'seojeong-ri', 'songtan', 'jinwi', 'osan', 'osan-college', 'sema', 'byeongjeom', 'seryu', 'suwon', 'hwaseo', 'sungkyunkwan-university', 'uiwang', 'dangjeong', 'gunpo', 'geumjeong', 'myeonghak', 'anyang', 'gwanak', 'seoksu', 'geumcheon-gu-office', 'doksan', 'gasan-digital-complex', 'guro', 'sindorim', 'yeongdeungpo', 'singil', 'daebang', 'noryangjin', 'yongsan', 'namyeong', 'seoul', 'city-hall', 'jonggak', 'jongno-3-sam-ga', 'jongno-5-o-ga', 'dongdaemun', 'dongmyo', 'sinseol-dong', 'jegidong', 'cheongnyangni-university-of-seoul', 'hoegi', 'hankuk-university-of-foreign-studies', 'sinimun-korea-national-university-of-arts', 'seokgye', 'kwangwoon-university'],
        ['dongducheon', 'dongducheonjungang', 'jihaeng', 'deokjeong-seojeong-college', 'yangju', 'uijeongbu', 'hoeryong', 'dobongsan', 'chang-dong', 'kwangwoon-university', 'seokgye', 'sinimun-korea-national-university-of-arts', 'hankuk-university-of-foreign-studies', 'hoegi', 'cheongnyangni-university-of-seoul', 'jegidong', 'sinseol-dong', 'dongmyo', 'dongdaemun', 'jongno-5-o-ga', 'jongno-3-sam-ga', 'jonggak', 'city-hall', 'seoul', 'namyeong', 'yongsan', 'noryangjin', 'daebang', 'singil', 'yeongdeungpo', 'sindorim', 'guro', 'guil', 'gaebong', 'oryu-dong', 'onsu', 'yeokgok', 'sosa', 'bucheon', 'jung-dong', 'songnae', 'bugae', 'bupyeong', 'baegun', 'dongam', 'ganseok', 'juan', 'dohwa', 'jemulpo', 'dowon', 'dongincheon', 'incheon'],
        ['incheon', 'dongincheon', 'dowon', 'jemulpo', 'dohwa', 'juan', 'ganseok', 'dongam', 'baegun', 'bupyeong', 'bugae', 'songnae', 'jung-dong', 'bucheon', 'sosa', 'yeokgok', 'onsu', 'oryu-dong', 'gaebong', 'guil', 'guro', 'sindorim', 'yeongdeungpo', 'singil', 'daebang', 'noryangjin', 'yongsan', 'namyeong', 'seoul', 'city-hall', 'jonggak', 'jongno-3-sam-ga', 'jongno-5-o-ga', 'dongdaemun', 'dongmyo', 'sinseol-dong', 'jegidong', 'cheongnyangni-university-of-seoul', 'hoegi', 'hankuk-university-of-foreign-studies', 'sinimun-korea-national-university-of-arts', 'seokgye', 'kwangwoon-university', 'chang-dong', 'dobongsan', 'hoeryong', 'uijeongbu', 'yangju', 'deokjeong-seojeong-college', 'jihaeng', 'dongducheonjungang-shinhan-university-campus-2', 'dongducheon'],
        ['dongducheon', 'bosan', 'dongducheonjungang', 'jihaeng', 'deokjeong-seojeong-college', 'deokgye', 'yangju', 'nogyang', 'ganeung', 'uijeongbu', 'hoeryong', 'mangwolsa-shinhan-university', 'dobongsan', 'dobong', 'banghak-dobong-gu-office', 'chang-dong', 'nokcheon', 'wolgye-induk-university', 'kwangwoon-university', 'seokgye', 'sinimun-korea-national-university-of-arts', 'hankuk-university-of-foreign-studies', 'hoegi', 'cheongnyangni-university-of-seoul', 'jegidong', 'sinseol-dong', 'dongmyo', 'dongdaemun', 'jongno-5-o-ga', 'jongno-3-sam-ga', 'jonggak', 'city-hall', 'seoul', 'namyeong', 'yongsan', 'noryangjin', 'daebang', 'singil', 'yeongdeungpo', 'sindorim', 'guro', 'gaebong', 'oryu-dong', 'onsu', 'yeokgok', 'sosa', 'bucheon', 'jung-dong', 'songnae', 'bugae', 'bupyeong'],
        ['uijeongbu', 'hoeryong', 'mangwolsa-shinhan-university', 'dobongsan', 'dobong', 'banghak-dobong-gu-office', 'chang-dong', 'nokcheon', 'wolgye-induk-university', 'kwangwoon-university', 'seokgye', 'sinimun-korea-national-university-of-arts', 'hankuk-university-of-foreign-studies', 'hoegi', 'cheongnyangni-university-of-seoul', 'jegidong', 'sinseol-dong', 'dongmyo', 'dongdaemun', 'jongno-5-o-ga', 'jongno-3-sam-ga', 'jonggak', 'city-hall', 'seoul', 'namyeong', 'yongsan', 'noryangjin', 'daebang', 'singil', 'yeongdeungpo', 'sindorim', 'guro', 'gasan-digital-complex', 'doksan', 'geumcheon-gu-office', 'seoksu', 'gwanak', 'anyang', 'myeonghak', 'geumjeong', 'gunpo', 'dangjeong', 'uiwang', 'sungkyunkwan-univ', 'hwaseo', 'suwon', 'seryu', 'byeongjeom', 'seodongtan'],
        ['seodongtan', 'byeongjeom', 'seryu', 'suwon', 'hwaseo', 'sungkyunkwan-university', 'uiwang', 'dangjeong', 'gunpo', 'geumjeong', 'myeonghak', 'anyang', 'gwanak', 'seoksu', 'geumcheon-gu-office', 'doksan', 'gasan-digital-complex', 'guro', 'sindorim', 'yeongdeungpo', 'singil', 'daebang', 'noryangjin', 'yongsan', 'namyeong', 'seoul', 'city-hall', 'jonggak', 'jongno-3-sam-ga', 'jongno-5-o-ga', 'dongdaemun', 'dongmyo', 'sinseol-dong', 'jegidong', 'cheongnyangni-university-of-seoul', 'hoegi', 'hankuk-university-of-foreign-studies', 'sinimun-korea-national-university-of-arts', 'seokgye'],
        ['cheongnyangni-university-of-seoul', 'jegidong', 'sinseol-dong', 'dongmyo', 'dongdaemun', 'jongno-5-o-ga', 'jongno-3-sam-ga', 'jonggak', 'city-hall', 'seoul', 'namyeong', 'yongsan', 'noryangjin', 'daebang', 'singil', 'yeongdeungpo', 'sindorim', 'guro', 'gasan-digital-complex', 'geumcheon-gu-office', 'anyang', 'geumjeong', 'uiwang', 'sungkyunkwan-univ', 'suwon', 'byeongjeom', 'osan', 'seojeong-ri', 'pyeongtaek', 'seonghwan', 'dujeong', 'cheonan', 'bongmyeong', 'ssangyong', 'asan', 'tangjeong', 'baebang', 'onyangoncheon', 'sinchang'],
        ['sinchang', 'onyangoncheon', 'baebang', 'tangjeong', 'asan', 'ssangyong', 'bongmyeong', 'cheonan', 'dujeong', 'seonghwan', 'pyeongtaek', 'seojeong-ri', 'osan', 'byeongjeom', 'suwon', 'sungkyunkwan-university', 'uiwang', 'geumjeong', 'anyang', 'geumcheon-gu-office', 'gasan-digital-complex', 'guro', 'sindorim', 'yeongdeungpo', 'singil', 'daebang', 'noryangjin', 'yongsan', 'namyeong', 'seoul', 'city-hall', 'jonggak', 'jongno-3-sam-ga', 'jongno-5-o-ga', 'dongdaemun', 'dongmyo', 'sinseol-dong', 'jegidong', 'cheongnyangni-university-of-seoul'],
        ['incheon', 'dongincheon', 'dowon', 'jemulpo', 'dohwa', 'juan', 'ganseok', 'dongam', 'baegun', 'bupyeong', 'bugae', 'songnae', 'jung-dong', 'bucheon', 'sosa', 'yeokgok', 'onsu', 'oryu-dong', 'station-397', 'guil', 'guro'],
        ['dongincheon', 'jemulpo', 'station-395', 'dongam', 'bupyeong', 'station-396', 'bucheon', 'yeokgok', 'station-397', 'guro', 'sindorim', 'yeongdeungpo', 'singil', 'station-398', 'noryangjin', 'yongsan'],
        ['yongsan', 'noryangjin', 'daebang', 'singil', 'yeongdeungpo', 'sindorim', 'guro', 'gaebong', 'yeokgok', 'bucheon', 'songnae', 'bupyeong', 'dongam', 'juan', 'jemulpo', 'dongincheon'],
        ['seoul', 'yeongdeungpo', 'geumcheon-gu-office', 'anyang', 'gunpo', 'uiwang', 'sungkyunkwan-univ', 'suwon', 'byeongjeom', 'osan', 'seojeong-ri', 'pyeongtaek', 'seonghwan', 'dujeong', 'cheonan'],
        ['dongducheon', 'bosan', 'dongducheonjungang', 'jihaeng', 'deokjeong-seojeong-college', 'deokgye', 'yangju', 'nogyang', 'uijeongbu', 'hoeryong', 'mangwolsa-shinhan-university', 'dobongsan', 'dobong'],
        ['yongsan', 'noryangjin', 'yeongdeungpo', 'sindorim', 'guro', 'yeokgok', 'bucheon', 'songnae', 'bupyeong', 'juan', 'dongincheon'],
        ['dongincheon', 'station-395', 'bupyeong', 'station-396', 'bucheon', 'yeokgok', 'guro', 'sindorim', 'yeongdeungpo', 'noryangjin', 'yongsan'],
        ['bucheon', 'yeokgok', 'station-397', 'guro', 'sindorim', 'yeongdeungpo', 'station-398', 'noryangjin', 'yongsan'],
        ['gwangmyeong', 'geumcheon-gu-office', 'doksan', 'gasan-digital-complex', 'guro', 'sindorim', 'yeongdeungpo'],
      ],
    },
    {
      id: '2',
      short: '2',
      name: 'Line 2',
      colour: '#00a23f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['city-hall', 'chungjeongno-kyonggi-university', 'ahyeon', 'ewha-womans-university', 'sinchon', 'hongik-university', 'hapjeong', 'dangsan', 'yeongdeungpo-gu-office', 'mullae', 'sindorim', 'daerim-guro-gu-office', 'guro-digital-complex', 'sindaebang', 'sillim', 'bongcheon', 'seoul-nat-l-university-gwanak-gu-office', 'nakseongdae', 'sadang', 'bangbae', 'seocho', 'seoul-nat-l-univ-of-education-court-public-prosecutors-office', 'gangnam', 'yeoksam', 'seolleung', 'samseong-world-trade-center-seoul', 'sports-complex', 'jamsilsaenae', 'jamsil-songpa-gu-office', 'jamsillaru', 'gangbyeon-dongseoul-bus-terminal', 'guui-gwangjin-gu-office', 'konkuk-university', 'seongsu', 'ttukseom', 'hanyang-university', 'wangsimni', 'sangwangsimni', 'sindang', 'dongdaemun-history-culture-park-station-ddp', 'euljiro-4-sa-ga', 'euljiro-3-sam-ga', 'euljiro-1-il-ga-industrial-bank-of-korea', 'city-hall'],
        ['city-hall', 'euljiro-1-il-ga-industrial-bank-of-korea', 'euljiro-3-sam-ga', 'euljiro-4-sa-ga', 'dongdaemun-history-culture-park', 'sindang', 'sangwangsimni', 'wangsimni-seongdong-gu-office', 'hanyang-university', 'ttukseom', 'seongsu', 'konkuk-university', 'guui-gwangjin-gu-office', 'gangbyeon-dongseoul-bus-terminal', 'jamsillaru', 'jamsil-songpa-gu-office', 'jamsilsaenae', 'sports-complex', 'samseong-world-trade-center-seoul', 'seolleung', 'yeoksam', 'gangnam', 'seoul-nat-l-univ-of-education-court-public-prosecutors-office', 'seocho', 'bangbae', 'sadang', 'nakseongdae', 'seoul-nat-l-university-gwanak-gu-office', 'bongcheon', 'sillim', 'sindaebang', 'guro-digital-complex', 'daerim-guro-gu-office', 'sindorim', 'mullae', 'yeongdeungpo-gu-office', 'dangsan', 'hapjeong', 'hongik-university', 'sinchon', 'ewha-womans-university', 'ahyeon', 'chungjeongno-kyonggi-university', 'city-hall'],
        ['sinseol-dong', 'station-224', 'station-225', 'station-226', 'seongsu'],
        ['sindorim', 'dorimcheon', 'yangcheon-gu-office', 'sinjeongnegeori', 'kkachisan'],
      ],
    },
    {
      id: '3',
      short: '3',
      name: 'Line 3',
      colour: '#ed6c00',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['daehwa', 'juyeop', 'jeongbalsan', 'madu', 'baekseok', 'daegok', 'hwajeong', 'wondang', 'wonheung', 'samsong', 'jichuk', 'gupabal', 'yeonsinnae', 'bulgwang', 'nokbeon', 'hongje-seoul-culture-arts-univ', 'muakjae', 'dongnimmun', 'gyeongbokgung-government-complex-seoul', 'anguk', 'jongno-3-sam-ga', 'euljiro-3-sam-ga', 'chungmuro', 'dongguk-univ', 'yaksu', 'geumho', 'oksu', 'apgujeong', 'sinsa', 'jamwon', 'express-bus-terminal', 'seoul-nat-l-univ-of-education-court-public-prosecutors-office', 'nambu-bus-terminal-seoul-arts-center', 'yangjae', 'maebong', 'dogok', 'daechi', 'hangnyeoul', 'daecheong', 'irwon', 'suseo', 'garak-market', 'nat-l-police-hospital', 'ogeum'],
        ['ogeum', 'station-233', 'garak-market', 'suseo', 'irwon', 'station-234', 'station-235', 'station-236', 'dogok', 'station-237', 'yangjae', 'nambu-bus-terminal-seoul-arts-center', 'seoul-nat-l-univ-of-education-court-public-prosecutors-office', 'express-bus-terminal', 'jamwon', 'sinsa', 'station-238', 'oksu', 'station-239', 'station-208', 'station-240', 'station-241', 's-3', 'jongno-3-sam-ga', 'anguk', 'station-243', 'station-244', 'station-245', 'station-246', 'station-247', 'station-189', 'station-248', 'station-249', 'jichuk', 'samsong', 'wonheung', 'wondang', 'hwajeong', 'daegok', 'baekseok', 'madu', 'jeongbalsan', 'juyeop', 'daehwa'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'Line 4',
      colour: '#009bce',
      text: '#ffffff',
      minutes: 3,
      branches: [
        ['buramsan', 'sanggye', 'nowon', 'chang-dong', 'ssangmun', 'suyu-gangbuk-gu-office', 'mia', 'miasageori', 'gireum', 'sungshin-women-s-univ', 'hansung-univ-samseongyo', 'hyehwa', 'dongdaemun', 'dongdaemun-history-culture-park-station-ddp', 'chungmuro', 'myeong-dong', 'hoehyeon-namdaemun-market', 'seoul', 'sookmyung-women-s-univ', 'samgakji', 'sinyongsan', 'ichon', 'dongjak', 'chongsin-univ-isu', 'sadang', 'namtaeryeong', 'seonbawi', 'seoul-racecourse-park', 'seoul-grand-park', 'gwacheon', 'ansan-line', 'indeogwon', 'pyeongchon', 'beomgye', 'geumjeong', 'sanbon', 'surisan', 'daeyami', 'banwol', 'sangnoksu', 'hanyang-university-at-ansan', 'jungang', 'gojan', 'choji', 'ansan', 'singiloncheon', 'jeongwang', 'oido'],
        ['oido', 'jeongwang', 'singiloncheon', 'ansan', 'choji', 'gojan', 'jungang', 'hanyang-university-at-ansan', 'sangnoksu', 'banwol', 'daeyami', 'surisan', 'sanbon', 'geumjeong', 'beomgye', 'pyeongchon', 'indeogwon', 'ansan-line', 'gwacheon', 'seoul-grand-park', 'seoul-racecourse-park', 'seonbawi', 'namtaeryeong', 'sadang', 'chongsin-univ-isu', 'dongjak', 'ichon', 'sinyongsan', 'samgakji', 'sookmyung-women-s-univ', 'seoul', 'hoehyeon-namdaemun-market', 'myeong-dong', 'chungmuro', 'dongdaemun-history-culture-park-station-ddp', 'dongdaemun', 'hyehwa', 'hansung-univ-samseongyo', 'sungshin-women-s-university', 'gireum', 'miasageori', 'mia', 'suyu-gangbuk-gu-office', 'ssangmun', 'changdong', 'nowon', 'sanggye', 'buramsan'],
        ['buramsan', 'sanggye', 'nowon', 'chang-dong', 'ssangmun', 'suyu-gangbuk-gu-office', 'mia', 'miasageori', 'gireum', 'sungshin-women-s-univ', 'hansung-univ-samseongyo', 'hyehwa', 'dongdaemun', 'dongdaemun-history-culture-park-station-ddp', 'chungmuro', 'myeong-dong', 'hoehyeon-namdaemun-market', 'seoul', 'sookmyung-women-s-univ', 'samgakji', 'sinyongsan', 'ichon', 'dongjak', 'chongsin-univ-isu', 'sadang', 'namtaeryeong', 'seonbawi', 'seoul-racecourse-park', 'seoul-grand-park', 'gwacheon', 'ansan-line', 'indeogwon', 'pyeongchon', 'beomgye', 'geumjeong', 'sanbon', 'sangnoksu', 'jungang', 'choji', 'ansan', 'jeongwang', 'oido'],
        ['oido', 'jeongwang', 'ansan', 'choji', 'jungang', 'sangnoksu', 'sanbon', 'geumjeong', 'beomgye', 'pyeongchon', 'indeogwon', 'ansan-line', 'gwacheon', 'seoul-grand-park', 'seoul-racecourse-park', 'seonbawi', 'namtaeryeong', 'sadang', 'chongsin-univ-isu', 'dongjak', 'ichon', 'sinyongsan', 'samgakji', 'sookmyung-women-s-univ', 'seoul', 'hoehyeon-namdaemun-market', 'myeong-dong', 'chungmuro', 'dongdaemun-history-culture-park-station-ddp', 'dongdaemun', 'hyehwa', 'hansung-univ-samseongyo', 'sungshin-women-s-university', 'gireum', 'miasageori', 'mia', 'suyu-gangbuk-gu-office', 'ssangmun', 'changdong', 'nowon', 'sanggye', 'buramsan'],
        ['namtaeryeong', 'sadang', 'chongsin-univ-isu', 'dongjak', 'ichon', 'sinyongsan', 'samgakji', 'sookmyung-women-s-univ', 'seoul', 'hoehyeon-namdaemun-market', 'myeong-dong', 'chungmuro', 'dongdaemun-history-culture-park-station-ddp', 'dongdaemun', 'hyehwa', 'hansung-univ-samseongyo', 'sungshin-women-s-university', 'gireum', 'miasageori', 'mia', 'suyu-gangbuk-gu-office', 'ssangmun', 'changdong', 'nowon', 'sanggye', 'buramsan', 'byeollaebyeolgaram', 'onam', 'jinjeop'],
        ['jinjeop', 'onam', 'byeollaebyeolgaram', 'buramsan', 'sanggye', 'nowon', 'chang-dong', 'ssangmun', 'suyu-gangbuk-gu-office', 'mia', 'miasageori', 'gireum', 'sungshin-women-s-univ', 'hansung-univ-samseongyo', 'hyehwa', 'dongdaemun', 'dongdaemun-history-culture-park-station-ddp', 'chungmuro', 'myeong-dong', 'hoehyeon-namdaemun-market', 'seoul', 'sookmyung-women-s-univ', 'samgakji', 'sinyongsan', 'ichon', 'dongjak', 'chongsin-univ-isu', 'sadang', 'namtaeryeong'],
      ],
    },
    {
      id: '5',
      short: '5',
      name: 'Line 5',
      colour: '#794698',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hanam-geomdansan', 'hanam-city-hall-deokpung-sinjang', 'station-439', 'misa', 'gangil', 'sangil-dong', 'godeok', 'station-260', 'station-261', 'station-262', 'station-257', 'cheonho', 'station-263', 'station-264', 'station-265', 'station-266', 'station-267', 'station-268', 'wangsimni', 'station-269', 'station-270', 'station-209', 'dongdaemun-history-culture-park-station-ddp', 's-4', 'jongno-3-sam-ga', 'gwanghwamun', 'station-273', 'chungjeongno', 'station-275', 'station-202', 'station-276', 'station-277', 'station-144', 'singil', 'station-279', 'station-280', 'yangpyeong', 'omokgyo', 'mok-dong', 'sinjeong', 'kkachisan', 'hwagok', 'ujangsan', 'balsan', 'magok', 'songjeong', 'gimpo-int-l-airport', 'gaehwasan', 'station-291'],
        ['station-291', 'gaehwasan', 'gimpo-int-l-airport', 'songjeong', 'magok', 'balsan', 'ujangsan', 'hwagok', 'kkachisan', 'sinjeong', 'mok-dong', 'omokgyo', 'yangpyeong', 'station-280', 'station-279', 'singil', 'station-144', 'station-277', 'station-276', 'station-202', 'station-275', 'chungjeongno', 'station-273', 'gwanghwamun', 'jongno-3-sam-ga', 's-4', 'dongdaemun-history-culture-park-station-ddp', 'station-209', 'station-270', 'station-269', 'wangsimni', 'station-268', 'station-267', 'station-266', 'station-265', 'station-264', 'station-263', 'cheonho', 'station-257', 'station-262', 'station-261', 'station-260', 'godeok', 'sangil-dong', 'gangil', 'station-442', 'station-439', 'hanam-city-hall-deokpung-sinjang', 'hanam-geomdansan'],
        ['macheon', 'station-253', 'station-254', 'ogeum', 'station-255', 'station-162', 'station-256', 'station-257', 'cheonho', 'station-263', 'station-264', 'station-265', 'station-266', 'station-267', 'station-268', 'wangsimni', 'station-269', 'station-270', 'station-209', 'dongdaemun-history-culture-park-station-ddp', 's-4', 'jongno-3-sam-ga', 'gwanghwamun', 'station-273', 'chungjeongno', 'station-275', 'station-202', 'station-276', 'station-277', 'station-144', 'singil', 'station-279', 'station-280', 'yangpyeong', 'omokgyo', 'mok-dong', 'sinjeong', 'kkachisan', 'hwagok', 'ujangsan', 'balsan', 'magok', 'songjeong', 'gimpo-int-l-airport', 'gaehwasan', 'station-291'],
      ],
    },
    {
      id: '6',
      short: '6',
      name: 'Line 6',
      colour: '#7c4932',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['station-191', 'station-187', 'saejeol', 'station-193', 'station-194', 'station-195', 'station-196', 'station-197', 'station-198', 'station-199', 'station-200', 'station-201', 'station-202', 'station-203', 'samgakji', 'station-204', 'station-205', 'station-206', 'station-207', 'station-208', 'station-209', 'station-210', 'station-211', 'station-212', 'bomun', 'station-214', 'korea-univ', 'station-216', 'station-217', 'station-218', 'station-219', 'station-220', 'station-221', 'bonghwasan', 'sinnae'],
        ['station-187', 'station-188', 'station-189', 'station-190', 'yeonsinnae', 'station-191'],
      ],
    },
    {
      id: '7',
      short: '7',
      name: 'Line 7',
      colour: '#6e7e31',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['jangam', 'dobongsan', 'station-399', 'station-400', 'station-401', 'station-402', 'station-403', 'station-404', 'station-220', 'station-405', 'station-406', 'station-407', 'station-408', 'station-409', 'station-410', 'station-411', 'station-265', 'station-412', 'konkuk-univ', 'jayang', 'station-415', 'gangnam-gu-office', 'station-417', 'station-418', 'station-419', 'express-bus-terminal', 'naebang', 'isu', 'station-422', 'station-423', 'station-424', 'station-425', 'station-426', 'station-427', 'station-428', 'station-429', 'station-430', 'station-431', 'cheolsan', 'station-433', 'station-434', 'onsu', 'station-443', 'station-444', 'station-445', 'station-446', 'station-447', 'station-448', 'station-449', 'station-450', 'bupyeong-gu-office', 'sangok', 'seongnam'],
      ],
    },
    {
      id: '8',
      short: '8',
      name: 'Line 8',
      colour: '#d11d70',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['byeollae', 'dasan', 'donggureung', 'guri', 'jangja-lake-park', 'amsa-history-park', 'amsa', 'cheonho', 'gangdong-gu-office', 'mongchontoseong', 'station-175', 'seokchon', 'songpa', 'garak-market', 'munjeong', 'jangji', 'bokjeong', 'namwirye', 'sanseong', 'namhansanseong', 'dandaeogeori', 'sinheung', 'sujin', 'moran'],
      ],
    },
    {
      id: '9',
      short: '9',
      name: 'Line 9',
      colour: '#a49d87',
      text: '#1a1a1a',
      minutes: 2,
      branches: [
        ['gaehwa', 'gimpo-int-l-airport', 'airport-market', 'sinbanghwa', 'station-135', 'yangcheon-hyanggyo', 'gayang', 'jeungmi', 'deungchon', 'yeomchang', 'sinmokdong', 'seonyudo', 'dangsan', 'national-assembly', 'station-144', 'saetgang', 'noryangjin', 'nodeul', 'heukseok', 'dongjak', 'gubanpo', 'sinbanpo', 'express-bus-terminal', 'sapyeong', 'sinnonhyeon', 'eonju', 'seonjeongneung', 'samseong-jungang', 'bongeunsa', 'sports-complex', 'station-157', 'station-158', 'seokchon', 'station-160', 'station-161', 'station-162', 'station-163', 'vhs-medical-center'],
        ['vhs-medical-center', 'station-162', 'seokchon', 'sports-complex', 'bongeunsa', 'seonjeongneung', 'sinnonhyeon', 'express-bus-terminal', 'dongjak', 'noryangjin', 'station-144', 'national-assembly', 'dangsan', 'yeomchang', 'gayang', 'station-135', 'gimpo-int-l-airport'],
        ['gimpo-int-l-airport', 'station-135', 'gayang', 'yeomchang', 'dangsan', 'station-144', 'saetgang', 'noryangjin', 'dongjak', 'express-bus-terminal', 'sinnonhyeon', 'seonjeongneung', 'bongeunsa', 'sports-complex', 'seokchon', 'station-162', 'vhs-medical-center'],
      ],
    },
    {
      id: '326',
      short: 'S',
      name: 'Shinbundang Line',
      colour: '#b81b30',
      text: '#ffffff',
      minutes: 4,
      branches: [
        ['sinsa', 'nonhyeon', 'sinnonhyeon', 'gangnam', 'yangjae', 'yangjae-citizen-s-forest', 'cheonggyesan', 'pangyo', 'jeongja', 'migeum', 'dongcheon', 'suji-gu-office', 'seongbok', 'sanghyeon', 'gwanggyo-jungang', 'gwanggyo'],
      ],
    },
  ],
  times: {
    'yeoncheon jeongok': 16,
    'jeongok cheongsan': 7,
    'cheongsan soyosan': 11,
    'soyosan dongducheon': 5,
    'dongducheonjungang jihaeng': 2,
    'jihaeng deokjeong-seojeong-college': 11,
    'deokjeong-seojeong-college deokgye': 6,
    'deokgye yangju': 10,
    'yangju nogyang': 4,
    'mangwolsa-shinhan-university dobongsan': 5,
    'chang-dong nokcheon': 2,
    'wolgye-induk-university kwangwoon-university': 2,
    'kwangwoon-university seokgye': 2,
    'sinimun-korea-national-university-of-arts hankuk-university-of-foreign-studies': 2,
    'hankuk-university-of-foreign-studies hoegi': 2,
    'cheongnyangni-university-of-seoul jegidong': 2,
    'jegidong sinseol-dong': 2,
    'sinseol-dong dongmyo': 2,
    'dongmyo dongdaemun': 2,
    'dongdaemun jongno-5-o-ga': 2,
    'jongno-5-o-ga jongno-3-sam-ga': 2,
    'jongno-3-sam-ga jonggak': 2,
    'jonggak city-hall': 2,
    'yongsan noryangjin': 5,
    'daebang singil': 2,
    'singil yeongdeungpo': 2,
    'sindorim guro': 2,
    'guil gaebong': 2,
    'oryu-dong onsu': 4,
    'bucheon jung-dong': 4,
    'jung-dong songnae': 2,
    'songnae bugae': 2,
    'bupyeong baegun': 4,
    'dongam ganseok': 2,
    'juan dohwa': 2,
    'dohwa jemulpo': 2,
    'dowon dongincheon': 2,
    'dongincheon dowon': 2,
    'jemulpo dohwa': 2,
    'dohwa juan': 2,
    'ganseok dongam': 2,
    'baegun bupyeong': 4,
    'bugae songnae': 2,
    'songnae jung-dong': 2,
    'jung-dong bucheon': 4,
    'onsu oryu-dong': 4,
    'gaebong guil': 2,
    'guro sindorim': 2,
    'yeongdeungpo singil': 2,
    'singil daebang': 2,
    'noryangjin yongsan': 5,
    'city-hall jonggak': 2,
    'jonggak jongno-3-sam-ga': 2,
    'jongno-3-sam-ga jongno-5-o-ga': 2,
    'jongno-5-o-ga dongdaemun': 2,
    'dongdaemun dongmyo': 2,
    'dongmyo sinseol-dong': 2,
    'sinseol-dong jegidong': 2,
    'jegidong cheongnyangni-university-of-seoul': 2,
    'hoegi hankuk-university-of-foreign-studies': 2,
    'hankuk-university-of-foreign-studies sinimun-korea-national-university-of-arts': 2,
    'seokgye kwangwoon-university': 2,
    'kwangwoon-university wolgye-induk-university': 2,
    'nokcheon chang-dong': 2,
    'dobongsan mangwolsa-shinhan-university': 5,
    'nogyang yangju': 4,
    'yangju deokgye': 10,
    'deokgye deokjeong-seojeong-college': 6,
    'deokjeong-seojeong-college jihaeng': 11,
    'dongducheon soyosan': 5,
    'soyosan cheongsan': 11,
    'cheongsan jeongok': 7,
    'jeongok yeoncheon': 16,
    'deokjeong-seojeong-college dongducheonjungang-shinhan-university-campus-2': 13,
    'guro gasan-digital-complex': 5,
    'gasan-digital-complex doksan': 4,
    'geumcheon-gu-office seoksu': 5,
    'seoksu gwanak': 4,
    'gwanak anyang': 5,
    'anyang myeonghak': 5,
    'geumjeong gunpo': 4,
    'dangjeong uiwang': 5,
    'uiwang sungkyunkwan-univ': 6,
    'sungkyunkwan-univ hwaseo': 5,
    'hwaseo suwon': 5,
    'suwon seryu': 6,
    'seryu byeongjeom': 9,
    'byeongjeom sema': 5,
    'sema osan-college': 5,
    'osan-college osan': 6,
    'osan jinwi': 8,
    'jinwi songtan': 8,
    'songtan seojeong-ri': 5,
    'seojeong-ri pyeongtaek-jije': 9,
    'pyeongtaek-jije pyeongtaek': 7,
    'pyeongtaek seonghwan': 18,
    'seonghwan jiksan': 10,
    'jiksan dujeong': 8,
    'dujeong cheonan': 5,
    'asan tangjeong': 4,
    'tangjeong baebang': 6,
    'baebang onyangoncheon': 9,
    'onyangoncheon sinchang': 9,
    'sinchang onyangoncheon': 9,
    'onyangoncheon baebang': 9,
    'baebang tangjeong': 6,
    'tangjeong asan': 4,
    'cheonan dujeong': 5,
    'dujeong jiksan': 8,
    'jiksan seonghwan': 10,
    'seonghwan pyeongtaek': 18,
    'pyeongtaek pyeongtaek-jije': 7,
    'pyeongtaek-jije seojeong-ri': 9,
    'seojeong-ri songtan': 5,
    'songtan jinwi': 8,
    'jinwi osan': 8,
    'osan osan-college': 6,
    'osan-college sema': 5,
    'sema byeongjeom': 5,
    'byeongjeom seryu': 9,
    'seryu suwon': 6,
    'suwon hwaseo': 5,
    'hwaseo sungkyunkwan-university': 5,
    'sungkyunkwan-university uiwang': 6,
    'uiwang dangjeong': 5,
    'gunpo geumjeong': 4,
    'myeonghak anyang': 5,
    'anyang gwanak': 5,
    'gwanak seoksu': 4,
    'seoksu geumcheon-gu-office': 5,
    'doksan gasan-digital-complex': 4,
    'gasan-digital-complex guro': 5,
    'dongducheon dongducheonjungang': 6,
    'deokjeong-seojeong-college yangju': 15,
    'yangju uijeongbu': 8,
    'hoeryong dobongsan': 8,
    'dobongsan chang-dong': 8,
    'chang-dong kwangwoon-university': 7,
    'kwangwoon-university chang-dong': 7,
    'chang-dong dobongsan': 8,
    'dobongsan hoeryong': 8,
    'uijeongbu yangju': 8,
    'yangju deokjeong-seojeong-college': 15,
    'dongducheonjungang-shinhan-university-campus-2 dongducheon': 6,
    'guro gaebong': 5,
    'byeongjeom seodongtan': 4,
    'seodongtan byeongjeom': 4,
    'gasan-digital-complex geumcheon-gu-office': 6,
    'geumcheon-gu-office anyang': 13,
    'anyang geumjeong': 7,
    'geumjeong uiwang': 11,
    'sungkyunkwan-univ suwon': 9,
    'suwon byeongjeom': 14,
    'byeongjeom osan': 15,
    'osan seojeong-ri': 19,
    'seojeong-ri pyeongtaek': 15,
    'seonghwan dujeong': 18,
    'dujeong seonghwan': 18,
    'pyeongtaek seojeong-ri': 15,
    'seojeong-ri osan': 19,
    'osan byeongjeom': 15,
    'byeongjeom suwon': 14,
    'suwon sungkyunkwan-university': 9,
    'uiwang geumjeong': 11,
    'geumjeong anyang': 7,
    'anyang geumcheon-gu-office': 13,
    'geumcheon-gu-office gasan-digital-complex': 6,
    'station-397 guil': 2,
    'dongincheon jemulpo': 5,
    'jemulpo station-395': 4,
    'station-395 dongam': 4,
    'dongam bupyeong': 6,
    'bupyeong station-396': 5,
    'station-396 bucheon': 5,
    'bucheon yeokgok': 5,
    'yeokgok station-397': 9,
    'station-397 guro': 5,
    'singil station-398': 2,
    'gaebong yeokgok': 9,
    'yeokgok bucheon': 5,
    'bucheon songnae': 6,
    'songnae bupyeong': 5,
    'bupyeong dongam': 6,
    'dongam juan': 5,
    'juan jemulpo': 4,
    'jemulpo dongincheon': 5,
    'seoul yeongdeungpo': 14,
    'yeongdeungpo geumcheon-gu-office': 13,
    'anyang gunpo': 11,
    'gunpo uiwang': 8,
    'nogyang uijeongbu': 5,
    'noryangjin yeongdeungpo': 6,
    'guro yeokgok': 13,
    'bupyeong juan': 10,
    'juan dongincheon': 8,
    'dongincheon station-395': 9,
    'station-395 bupyeong': 9,
    'yeokgok guro': 13,
    'yeongdeungpo noryangjin': 6,
    'yeongdeungpo station-398': 4,
    'gwangmyeong geumcheon-gu-office': 9,
    'city-hall chungjeongno-kyonggi-university': 3,
    'sinchon hongik-university': 3,
    'hapjeong dangsan': 4,
    'sindorim daerim-guro-gu-office': 4,
    'sindaebang sillim': 3,
    'nakseongdae sadang': 3,
    'sadang bangbae': 3,
    'bangbae seocho': 3,
    'seoul-nat-l-univ-of-education-court-public-prosecutors-office gangnam': 3,
    'yeoksam seolleung': 3,
    'seolleung samseong-world-trade-center-seoul': 3,
    'samseong-world-trade-center-seoul sports-complex': 3,
    'jamsilsaenae jamsil-songpa-gu-office': 3,
    'jamsillaru gangbyeon-dongseoul-bus-terminal': 4,
    'guui-gwangjin-gu-office konkuk-university': 3,
    'konkuk-university seongsu': 3,
    'euljiro-4-sa-ga euljiro-3-sam-ga': 1,
    'euljiro-1-il-ga-industrial-bank-of-korea city-hall': 1,
    'city-hall euljiro-1-il-ga-industrial-bank-of-korea': 1,
    'euljiro-3-sam-ga euljiro-4-sa-ga': 1,
    'seongsu konkuk-university': 3,
    'konkuk-university guui-gwangjin-gu-office': 3,
    'gangbyeon-dongseoul-bus-terminal jamsillaru': 4,
    'jamsil-songpa-gu-office jamsilsaenae': 3,
    'sports-complex samseong-world-trade-center-seoul': 3,
    'samseong-world-trade-center-seoul seolleung': 3,
    'seolleung yeoksam': 3,
    'gangnam seoul-nat-l-univ-of-education-court-public-prosecutors-office': 3,
    'seocho bangbae': 3,
    'bangbae sadang': 3,
    'sadang nakseongdae': 3,
    'sillim sindaebang': 3,
    'daerim-guro-gu-office sindorim': 4,
    'dangsan hapjeong': 4,
    'hongik-university sinchon': 3,
    'chungjeongno-kyonggi-university city-hall': 3,
    'sinseol-dong station-224': 3,
    'station-226 seongsu': 4,
    'dorimcheon yangcheon-gu-office': 3,
    'yangcheon-gu-office sinjeongnegeori': 3,
    'sinjeongnegeori kkachisan': 3,
    'daehwa juyeop': 3,
    'juyeop jeongbalsan': 3,
    'madu baekseok': 3,
    'baekseok daegok': 5,
    'daegok hwajeong': 4,
    'hwajeong wondang': 5,
    'wondang wonheung': 6,
    'wonheung samsong': 4,
    'samsong jichuk': 4,
    'jichuk gupabal': 3,
    'gupabal yeonsinnae': 4,
    'yeonsinnae bulgwang': 3,
    'nokbeon hongje-seoul-culture-arts-univ': 3,
    'dongnimmun gyeongbokgung-government-complex-seoul': 3,
    'gyeongbokgung-government-complex-seoul anguk': 3,
    'jongno-3-sam-ga euljiro-3-sam-ga': 1,
    'oksu apgujeong': 4,
    'apgujeong sinsa': 3,
    'express-bus-terminal seoul-nat-l-univ-of-education-court-public-prosecutors-office': 3,
    'nambu-bus-terminal-seoul-arts-center yangjae': 3,
    'yangjae maebong': 3,
    'daecheong irwon': 3,
    'irwon suseo': 3,
    'suseo garak-market': 3,
    'station-233 garak-market': 1,
    'garak-market suseo': 3,
    'suseo irwon': 3,
    'irwon station-234': 3,
    'station-237 yangjae': 3,
    'yangjae nambu-bus-terminal-seoul-arts-center': 3,
    'seoul-nat-l-univ-of-education-court-public-prosecutors-office express-bus-terminal': 3,
    'sinsa station-238': 3,
    'station-238 oksu': 4,
    'station-240 station-241': 3,
    'station-241 s-3': 1,
    's-3 jongno-3-sam-ga': 1,
    'anguk station-243': 3,
    'station-243 station-244': 3,
    'station-246 station-247': 3,
    'station-247 station-189': 3,
    'station-189 station-248': 3,
    'station-248 station-249': 4,
    'station-249 jichuk': 3,
    'jichuk samsong': 4,
    'samsong wonheung': 4,
    'wonheung wondang': 6,
    'wondang hwajeong': 5,
    'hwajeong daegok': 4,
    'daegok baekseok': 5,
    'baekseok madu': 3,
    'jeongbalsan juyeop': 3,
    'juyeop daehwa': 3,
    'sanggye nowon': 2,
    'sungshin-women-s-univ hansung-univ-samseongyo': 2,
    'hansung-univ-samseongyo hyehwa': 2,
    'dongdaemun dongdaemun-history-culture-park-station-ddp': 2,
    'chungmuro myeong-dong': 2,
    'myeong-dong hoehyeon-namdaemun-market': 2,
    'hoehyeon-namdaemun-market seoul': 2,
    'samgakji sinyongsan': 2,
    'sinyongsan ichon': 2,
    'ichon dongjak': 5,
    'dongjak chongsin-univ-isu': 4,
    'chongsin-univ-isu sadang': 2,
    'namtaeryeong seonbawi': 4,
    'seonbawi seoul-racecourse-park': 2,
    'seoul-racecourse-park seoul-grand-park': 2,
    'seoul-grand-park gwacheon': 2,
    'gwacheon ansan-line': 2,
    'ansan-line indeogwon': 6,
    'beomgye geumjeong': 4,
    'geumjeong sanbon': 4,
    'sanbon surisan': 2,
    'surisan daeyami': 5,
    'daeyami banwol': 4,
    'banwol sangnoksu': 7,
    'choji ansan': 4,
    'ansan singiloncheon': 5,
    'singiloncheon jeongwang': 5,
    'jeongwang singiloncheon': 5,
    'singiloncheon ansan': 5,
    'ansan choji': 4,
    'sangnoksu banwol': 7,
    'banwol daeyami': 4,
    'daeyami surisan': 5,
    'surisan sanbon': 2,
    'sanbon geumjeong': 4,
    'geumjeong beomgye': 4,
    'indeogwon ansan-line': 6,
    'ansan-line gwacheon': 2,
    'gwacheon seoul-grand-park': 2,
    'seoul-grand-park seoul-racecourse-park': 2,
    'seoul-racecourse-park seonbawi': 2,
    'seonbawi namtaeryeong': 4,
    'sadang chongsin-univ-isu': 2,
    'chongsin-univ-isu dongjak': 4,
    'dongjak ichon': 5,
    'ichon sinyongsan': 2,
    'sinyongsan samgakji': 2,
    'seoul hoehyeon-namdaemun-market': 2,
    'hoehyeon-namdaemun-market myeong-dong': 2,
    'myeong-dong chungmuro': 2,
    'dongdaemun-history-culture-park-station-ddp dongdaemun': 2,
    'hyehwa hansung-univ-samseongyo': 2,
    'hansung-univ-samseongyo sungshin-women-s-university': 2,
    'nowon sanggye': 2,
    'sanbon sangnoksu': 17,
    'sangnoksu jungang': 6,
    'jungang choji': 6,
    'ansan jeongwang': 10,
    'jeongwang ansan': 10,
    'choji jungang': 6,
    'jungang sangnoksu': 6,
    'sangnoksu sanbon': 17,
    'buramsan byeollaebyeolgaram': 7,
    'byeollaebyeolgaram onam': 15,
    'onam jinjeop': 4,
    'jinjeop onam': 4,
    'onam byeollaebyeolgaram': 15,
    'byeollaebyeolgaram buramsan': 7,
    'hanam-geomdansan hanam-city-hall-deokpung-sinjang': 3,
    'hanam-city-hall-deokpung-sinjang station-439': 3,
    'station-439 misa': 3,
    'misa gangil': 3,
    'sangil-dong godeok': 3,
    'cheonho station-263': 4,
    'station-263 station-264': 3,
    'station-265 station-266': 3,
    'station-266 station-267': 3,
    'jongno-3-sam-ga gwanghwamun': 3,
    'gwanghwamun station-273': 3,
    'station-275 station-202': 3,
    'station-276 station-277': 4,
    'singil station-279': 3,
    'sinjeong kkachisan': 3,
    'kkachisan hwagok': 3,
    'balsan magok': 3,
    'magok songjeong': 3,
    'gimpo-int-l-airport gaehwasan': 3,
    'gaehwasan gimpo-int-l-airport': 3,
    'songjeong magok': 3,
    'magok balsan': 3,
    'hwagok kkachisan': 3,
    'kkachisan sinjeong': 3,
    'station-279 singil': 3,
    'station-277 station-276': 4,
    'station-202 station-275': 3,
    'station-273 gwanghwamun': 3,
    'gwanghwamun jongno-3-sam-ga': 3,
    'station-267 station-266': 3,
    'station-266 station-265': 3,
    'station-264 station-263': 3,
    'station-263 cheonho': 4,
    'godeok sangil-dong': 3,
    'gangil station-442': 3,
    'station-442 station-439': 3,
    'station-439 hanam-city-hall-deokpung-sinjang': 3,
    'hanam-city-hall-deokpung-sinjang hanam-geomdansan': 3,
    'station-162 station-256': 3,
    'station-191 station-187': 3,
    'station-193 station-194': 3,
    'station-203 samgakji': 3,
    'samgakji station-204': 3,
    'korea-univ station-216': 3,
    'bonghwasan sinnae': 3,
    'jangam dobongsan': 3,
    'dobongsan station-399': 3,
    'station-399 station-400': 3,
    'station-400 station-401': 3,
    'station-402 station-403': 3,
    'station-403 station-404': 3,
    'station-265 station-412': 3,
    'konkuk-univ jayang': 3,
    'jayang station-415': 4,
    'express-bus-terminal naebang': 5,
    'station-422 station-423': 4,
    'station-425 station-426': 3,
    'station-428 station-429': 3,
    'station-429 station-430': 3,
    'station-431 cheolsan': 3,
    'cheolsan station-433': 3,
    'station-433 station-434': 3,
    'station-434 onsu': 3,
    'onsu station-443': 4,
    'station-443 station-444': 3,
    'station-446 station-447': 3,
    'bupyeong-gu-office sangok': 3,
    'sangok seongnam': 5,
    'byeollae dasan': 6,
    'dasan donggureung': 4,
    'guri jangja-lake-park': 4,
    'jangja-lake-park amsa-history-park': 7,
    'amsa-history-park amsa': 3,
    'amsa cheonho': 3,
    'gangdong-gu-office mongchontoseong': 3,
    'bokjeong namwirye': 3,
    'namwirye sanseong': 3,
    'gaehwa gimpo-int-l-airport': 4,
    'station-135 yangcheon-hyanggyo': 3,
    'yangcheon-hyanggyo gayang': 3,
    'sinmokdong seonyudo': 3,
    'dangsan national-assembly': 3,
    'saetgang noryangjin': 3,
    'heukseok dongjak': 3,
    'bongeunsa sports-complex': 3,
    'sports-complex station-157': 3,
    'station-161 station-162': 3,
    'station-163 vhs-medical-center': 3,
    'vhs-medical-center station-162': 4,
    'station-162 seokchon': 5,
    'seokchon sports-complex': 6,
    'sports-complex bongeunsa': 3,
    'bongeunsa seonjeongneung': 3,
    'seonjeongneung sinnonhyeon': 4,
    'sinnonhyeon express-bus-terminal': 4,
    'express-bus-terminal dongjak': 5,
    'dongjak noryangjin': 7,
    'noryangjin station-144': 4,
    'national-assembly dangsan': 3,
    'dangsan yeomchang': 6,
    'yeomchang gayang': 5,
    'gayang station-135': 5,
    'station-135 gimpo-int-l-airport': 5,
    'gimpo-int-l-airport station-135': 5,
    'station-135 gayang': 5,
    'gayang yeomchang': 5,
    'yeomchang dangsan': 6,
    'dangsan station-144': 5,
    'noryangjin dongjak': 7,
    'dongjak express-bus-terminal': 5,
    'express-bus-terminal sinnonhyeon': 4,
    'sinnonhyeon seonjeongneung': 4,
    'seonjeongneung bongeunsa': 3,
    'sports-complex seokchon': 6,
    'seokchon station-162': 5,
    'station-162 vhs-medical-center': 4,
    'sinsa nonhyeon': 2,
    'nonhyeon sinnonhyeon': 2,
    'sinnonhyeon gangnam': 2,
    'gangnam yangjae': 3,
    'yangjae yangjae-citizen-s-forest': 3,
    'yangjae-citizen-s-forest cheonggyesan': 6,
    'cheonggyesan pangyo': 15,
    'pangyo jeongja': 6,
    'migeum dongcheon': 3,
    'suji-gu-office seongbok': 3,
  },
  stations: {
    daehwa: { name: 'Daehwa', x: 12, y: 41, aka: ['대화'] },
    juyeop: { name: 'Juyeop', x: 13.5, y: 42.5, aka: ['주엽'] },
    jeongbalsan: { name: 'Jeongbalsan', x: 15, y: 44, aka: ['정발산'] },
    madu: { name: 'Madu', x: 16.5, y: 45.5, aka: ['마두'] },
    baekseok: { name: 'Baekseok', x: 18, y: 47, aka: ['백석'] },
    daegok: { name: 'Daegok', x: 20, y: 47, aka: ['대곡'] },
    hwajeong: { name: 'Hwajeong', x: 22, y: 47, aka: ['화정'] },
    wondang: { name: 'Wondang', x: 24.5, y: 47, aka: ['원당'] },
    wonheung: { name: 'Wonheung', x: 26.5, y: 47, aka: ['원흥'] },
    samsong: { name: 'Samsong', x: 28.5, y: 47, aka: ['삼송'] },
    jichuk: { name: 'Jichuk', x: 31, y: 47.5, aka: ['지축'] },
    gupabal: { name: 'Gupabal', x: 32, y: 49, aka: ['구파발'] },
    yeonsinnae: { name: 'Yeonsinnae', x: 33.5, y: 50.5, aka: ['연신내'] },
    bulgwang: { name: 'Bulgwang', x: 35, y: 52, aka: ['불광'] },
    nokbeon: { name: 'Nokbeon', x: 35, y: 54.5, aka: ['녹번'] },
    'hongje-seoul-culture-arts-univ': { name: 'Hongje (Seoul Culture Arts Univ.)', x: 35.5, y: 56, aka: ['홍제'] },
    muakjae: { name: 'Muakjae', x: 37.5, y: 56, aka: ['무악재'] },
    dongnimmun: { name: 'Dongnimmun', x: 38, y: 58.5, aka: ['독립문'] },
    'gyeongbokgung-government-complex-seoul': { name: 'Gyeongbokgung (Government Complex Seoul)', x: 40, y: 57, aka: ['경복궁'] },
    anguk: { name: 'Anguk', x: 41.5, y: 58.5, aka: ['안국'] },
    'jongno-3-sam-ga': { name: 'Jongno 3(sam)-ga', x: 41.5, y: 61, aka: ['종로3가'] },
    'euljiro-3-sam-ga': { name: 'Euljiro 3(sam)-ga', x: 41.5, y: 62.5, aka: ['을지로3가'] },
    chungmuro: { name: 'Chungmuro', x: 42.5, y: 64, aka: ['충무로'] },
    'dongguk-univ': { name: 'Dongguk Univ.', x: 45, y: 63.5, aka: ['동대입구'] },
    yaksu: { name: 'Yaksu', x: 46, y: 64.5, aka: ['약수'] },
    geumho: { name: 'Geumho', x: 48, y: 66, aka: ['금호'] },
    oksu: { name: 'Oksu', x: 47, y: 67.5, aka: ['옥수'] },
    apgujeong: { name: 'Apgujeong', x: 46.5, y: 69, aka: ['압구정'] },
    sinsa: { name: 'Sinsa', x: 47, y: 70.5, aka: ['신사'] },
    jamwon: { name: 'Jamwon', x: 45, y: 72, aka: ['잠원'] },
    'express-bus-terminal': { name: 'Express Bus Terminal', x: 44.5, y: 74.5, aka: ['고속터미널'] },
    'seoul-nat-l-univ-of-education-court-public-prosecutors-office': { name: 'Seoul Nat\'l Univ. of Education (Court & Public Prosecutors\' Office)', x: 47, y: 76, aka: ['교대(법원·검찰청)', '교대'] },
    'nambu-bus-terminal-seoul-arts-center': { name: 'Nambu Bus Terminal (Seoul Arts Center)', x: 48.5, y: 77.5, aka: ['남부터미널(예술의전당)'] },
    yangjae: { name: 'Yangjae', x: 50.5, y: 79, aka: ['양재'] },
    maebong: { name: 'Maebong', x: 50.5, y: 77, aka: ['매봉'] },
    dogok: { name: 'Dogok', x: 52, y: 75.5, aka: ['도곡'] },
    daechi: { name: 'Daechi', x: 53, y: 74, aka: ['대치'] },
    hangnyeoul: { name: 'Hangnyeoul', x: 55.5, y: 73.5, aka: ['학여울'] },
    daecheong: { name: 'Daecheong', x: 57, y: 75, aka: ['대청'] },
    irwon: { name: 'Irwon', x: 57, y: 76.5, aka: ['일원'] },
    suseo: { name: 'Suseo', x: 59, y: 76, aka: ['수서'] },
    'garak-market': { name: 'Garak Market', x: 61, y: 76, aka: ['가락시장'] },
    'nat-l-police-hospital': { name: 'Nat\'l Police Hospital', x: 63, y: 75.5, aka: ['경찰병원'] },
    ogeum: { name: 'Ogeum', x: 63, y: 73, aka: ['오금'] },
    'city-hall': { name: 'City Hall', x: 39, y: 66.5, aka: ['시청'] },
    'chungjeongno-kyonggi-university': { name: 'Chungjeongno(Kyonggi University)', x: 38.5, y: 64.5, aka: ['충정로', '충정로(경기대입구)'] },
    ahyeon: { name: 'Ahyeon', x: 37, y: 62.5, aka: ['아현', '아현(추계예술대)'] },
    'ewha-womans-university': { name: 'Ewha Womans University', x: 36, y: 63.5, aka: ['이대'] },
    sinchon: { name: 'Sinchon', x: 34.5, y: 65, aka: ['신촌', '신촌(지하)'] },
    'hongik-university': { name: 'Hongik University', x: 32.5, y: 65, aka: ['홍대입구'] },
    hapjeong: { name: 'Hapjeong', x: 33, y: 67.5, aka: ['합정'] },
    dangsan: { name: 'Dangsan', x: 32, y: 69.5, aka: ['당산'] },
    'yeongdeungpo-gu-office': { name: 'Yeongdeungpo-gu Office', x: 31, y: 70.5, aka: ['영등포구청'] },
    mullae: { name: 'Mullae', x: 31, y: 73.5, aka: ['문래'] },
    sindorim: { name: 'Sindorim', x: 30.5, y: 75.5, aka: ['신도림'] },
    'daerim-guro-gu-office': { name: 'Daerim(Guro-gu Office)', x: 29.5, y: 76.5, aka: ['대림(구로구청)'] },
    'guro-digital-complex': { name: 'Guro Digital Complex', x: 31, y: 78.5, aka: ['구로디지털단지'] },
    sindaebang: { name: 'Sindaebang', x: 32.5, y: 78.5, aka: ['신대방'] },
    sillim: { name: 'Sillim', x: 34.5, y: 78.5, aka: ['신림'] },
    bongcheon: { name: 'Bongcheon', x: 36, y: 78.5, aka: ['봉천'] },
    'seoul-nat-l-university-gwanak-gu-office': { name: 'Seoul Nat\'l University (Gwanak-gu Office)', x: 38, y: 78.5, aka: ['서울대입구', '서울대입구(관악구청)'] },
    nakseongdae: { name: 'Nakseongdae', x: 39.5, y: 79, aka: ['낙성대'] },
    sadang: { name: 'Sadang', x: 41.5, y: 79, aka: ['사당'] },
    bangbae: { name: 'Bangbae', x: 44, y: 79, aka: ['방배', '방배 (백석예술대)'] },
    seocho: { name: 'Seocho', x: 45.5, y: 77.5, aka: ['서초'] },
    gangnam: { name: 'Gangnam', x: 49, y: 76, aka: ['강남'] },
    yeoksam: { name: 'Yeoksam', x: 50.5, y: 74.5, aka: ['역삼'] },
    seolleung: { name: 'Seolleung', x: 52, y: 72.5, aka: ['선릉'] },
    'samseong-world-trade-center-seoul': { name: 'Samseong(World Trade Center Seoul)', x: 54.5, y: 72, aka: ['삼성', '삼성(무역센터)'] },
    'sports-complex': { name: 'Sports Complex', x: 56.5, y: 72, aka: ['종합운동장'] },
    jamsilsaenae: { name: 'Jamsilsaenae', x: 56.5, y: 70, aka: ['잠실새내'] },
    'jamsil-songpa-gu-office': { name: 'Jamsil(Songpa-gu Office)', x: 58, y: 71, aka: ['잠실', '잠실(송파구청)'] },
    jamsillaru: { name: 'Jamsillaru', x: 58, y: 69, aka: ['잠실나루'] },
    'gangbyeon-dongseoul-bus-terminal': { name: 'Gangbyeon(Dongseoul Bus Terminal)', x: 58, y: 66.5, aka: ['강변', '강변(동서울터미널)'] },
    'guui-gwangjin-gu-office': { name: 'Guui(Gwangjin-gu Office)', x: 57, y: 65, aka: ['구의', '구의(광진구청)'] },
    'konkuk-university': { name: 'Konkuk University', x: 54.5, y: 65, aka: ['건대입구'] },
    seongsu: { name: 'Seongsu', x: 52.5, y: 64, aka: ['성수'] },
    ttukseom: { name: 'Ttukseom', x: 51, y: 65.5, aka: ['뚝섬'] },
    'hanyang-university': { name: 'Hanyang University', x: 50.5, y: 63.5, aka: ['한양대'] },
    wangsimni: { name: 'Wangsimni', x: 50.5, y: 62, aka: ['왕십리'] },
    sangwangsimni: { name: 'Sangwangsimni', x: 49, y: 60.5, aka: ['상왕십리'] },
    sindang: { name: 'Sindang', x: 47, y: 62, aka: ['신당'] },
    'dongdaemun-history-culture-park-station-ddp': { name: 'Dongdaemun History & Culture Park Station (DDP)', x: 45, y: 62, aka: ['동대문역사문화공원'] },
    'euljiro-4-sa-ga': { name: 'Euljiro 4(sa)-ga', x: 43, y: 60.5, aka: ['을지로4가'] },
    'euljiro-1-il-ga-industrial-bank-of-korea': { name: 'Euljiro 1(il)-ga (Industrial Bank of Korea)', x: 40, y: 64.5, aka: ['을지로입구'] },
    buramsan: { name: 'Buramsan', x: 59.5, y: 37.5, aka: ['불암산'] },
    sanggye: { name: 'Sanggye', x: 58, y: 38.5, aka: ['상계'] },
    nowon: { name: 'Nowon', x: 55.5, y: 38.5, aka: ['노원'] },
    'chang-dong': { name: 'Chang-Dong', x: 53.5, y: 38.5, aka: ['창동'] },
    ssangmun: { name: 'Ssangmun', x: 52, y: 41, aka: ['쌍문'] },
    'suyu-gangbuk-gu-office': { name: 'Suyu (Gangbuk-gu Office)', x: 50, y: 43.5, aka: ['수유(강북구청)', '수유'] },
    mia: { name: 'Mia', x: 50, y: 46, aka: ['미아'] },
    miasageori: { name: 'Miasageori', x: 49.5, y: 49, aka: ['미아사거리'] },
    gireum: { name: 'Gireum', x: 49, y: 51.5, aka: ['길음'] },
    'sungshin-women-s-univ': { name: 'Sungshin Women\'s Univ.', x: 47.5, y: 52.5, aka: ['성신여대입구'] },
    'hansung-univ-samseongyo': { name: 'Hansung Univ. (Samseongyo)', x: 46, y: 54.5, aka: ['한성대입구(삼선교)', '한성대입구'] },
    hyehwa: { name: 'Hyehwa', x: 44, y: 56.5, aka: ['혜화(서울대학교병원)', '혜화'] },
    dongdaemun: { name: 'Dongdaemun', x: 45, y: 59, aka: ['동대문'] },
    'myeong-dong': { name: 'Myeong-dong', x: 40.5, y: 66, aka: ['명동'] },
    'hoehyeon-namdaemun-market': { name: 'Hoehyeon (Namdaemun Market)', x: 38, y: 68, aka: ['회현(남대문시장)', '회현'] },
    seoul: { name: 'Seoul', x: 37, y: 70, aka: ['서울역'] },
    'sookmyung-women-s-univ': { name: 'Sookmyung Women\'s Univ.', x: 39.5, y: 68, aka: ['숙대입구'] },
    samgakji: { name: 'Samgakji', x: 40.5, y: 69, aka: ['삼각지'] },
    sinyongsan: { name: 'Sinyongsan', x: 39.5, y: 71, aka: ['신용산'] },
    ichon: { name: 'Ichon', x: 41, y: 72, aka: ['이촌'] },
    dongjak: { name: 'Dongjak', x: 41, y: 74, aka: ['동작'] },
    'chongsin-univ-isu': { name: 'Chongsin Univ. (Isu)', x: 41.5, y: 76.5, aka: ['총신대입구 (이수)'] },
    namtaeryeong: { name: 'Namtaeryeong', x: 43, y: 80.5, aka: ['남태령'] },
    seonbawi: { name: 'Seonbawi', x: 44.5, y: 82.5, aka: ['선바위'] },
    'seoul-racecourse-park': { name: 'Seoul Racecourse park', x: 45.5, y: 84, aka: ['경마공원'] },
    'seoul-grand-park': { name: 'Seoul Grand park', x: 45.5, y: 86.5, aka: ['대공원 (서울랜드)', '대공원'] },
    gwacheon: { name: 'Gwacheon', x: 44, y: 88.5, aka: ['과천'] },
    'ansan-line': { name: 'Ansan Line', x: 42.5, y: 90, aka: ['정부과천청사'] },
    indeogwon: { name: 'Indeogwon', x: 41, y: 92, aka: ['인덕원'] },
    pyeongchon: { name: 'Pyeongchon', x: 39.5, y: 94, aka: ['평촌'] },
    beomgye: { name: 'Beomgye', x: 37.5, y: 95.5, aka: ['범계'] },
    geumjeong: { name: 'Geumjeong', x: 36, y: 97.5, aka: ['금정'] },
    sanbon: { name: 'Sanbon', x: 34, y: 99.5, aka: ['산본'] },
    surisan: { name: 'Surisan', x: 36, y: 100, aka: ['수리산'] },
    daeyami: { name: 'Daeyami', x: 34.5, y: 101.5, aka: ['대야미'] },
    banwol: { name: 'Banwol', x: 33.5, y: 102.5, aka: ['반월'] },
    sangnoksu: { name: 'Sangnoksu', x: 31.5, y: 101.5, aka: ['상록수'] },
    'hanyang-university-at-ansan': { name: 'Hanyang University at Ansan', x: 30.5, y: 103, aka: ['한대앞'] },
    jungang: { name: 'Jungang', x: 28.5, y: 102.5, aka: ['중앙'] },
    gojan: { name: 'Gojan', x: 27.5, y: 104, aka: ['고잔'] },
    choji: { name: 'Choji', x: 26, y: 102.5, aka: ['초지 (신안산대학교)', '초지'] },
    ansan: { name: 'Ansan', x: 23.5, y: 102.5, aka: ['안산'] },
    singiloncheon: { name: 'Singiloncheon', x: 22, y: 103, aka: ['신길온천'] },
    jeongwang: { name: 'Jeongwang', x: 22, y: 101, aka: ['정왕'] },
    oido: { name: 'Oido', x: 20.5, y: 99.5, aka: ['오이도'] },
    gaehwa: { name: 'Gaehwa', x: 19, y: 63.5, aka: ['개화'] },
    'gimpo-int-l-airport': { name: 'Gimpo Int\'l Airport', x: 21, y: 63.5, aka: ['김포공항'] },
    'airport-market': { name: 'Airport Market', x: 22.5, y: 64.5, aka: ['공항시장'] },
    sinbanghwa: { name: 'Sinbanghwa', x: 22.5, y: 62.5, aka: ['신방화'] },
    'station-135': { name: '마곡나루', x: 24, y: 64 },
    'yangcheon-hyanggyo': { name: 'Yangcheon Hyanggyo', x: 25.5, y: 64, aka: ['양천향교'] },
    gayang: { name: 'Gayang', x: 26, y: 65.5, aka: ['가양'] },
    jeungmi: { name: 'Jeungmi', x: 28, y: 65.5, aka: ['증미'] },
    deungchon: { name: 'Deungchon', x: 27.5, y: 67.5, aka: ['등촌'] },
    yeomchang: { name: 'Yeomchang', x: 29, y: 67.5, aka: ['염창'] },
    sinmokdong: { name: 'Sinmokdong', x: 30.5, y: 67, aka: ['신목동'] },
    seonyudo: { name: 'Seonyudo', x: 30, y: 69, aka: ['선유도'] },
    'national-assembly': { name: 'National Assembly', x: 33.5, y: 69.5, aka: ['국회의사당'] },
    'station-144': { name: '여의도', x: 34, y: 71.5 },
    saetgang: { name: 'Saetgang', x: 35.5, y: 72, aka: ['샛강'] },
    noryangjin: { name: 'Noryangjin', x: 37, y: 74, aka: ['노량진'] },
    nodeul: { name: 'Nodeul', x: 38, y: 73, aka: ['노들'] },
    heukseok: { name: 'Heukseok', x: 39.5, y: 73, aka: ['흑석'] },
    gubanpo: { name: 'Gubanpo', x: 42.5, y: 74.5, aka: ['구반포'] },
    sinbanpo: { name: 'Sinbanpo', x: 43.5, y: 73, aka: ['신반포'] },
    sapyeong: { name: 'Sapyeong', x: 46, y: 74.5, aka: ['사평'] },
    sinnonhyeon: { name: 'Sinnonhyeon', x: 47.5, y: 74.5, aka: ['신논현'] },
    eonju: { name: 'Eonju', x: 49, y: 73, aka: ['언주'] },
    seonjeongneung: { name: 'Seonjeongneung', x: 50.5, y: 72.5, aka: ['선정릉'] },
    'samseong-jungang': { name: 'Samseong Jungang', x: 52, y: 71, aka: ['삼성중앙'] },
    bongeunsa: { name: 'Bongeunsa', x: 53.5, y: 72.5, aka: ['봉은사'] },
    'station-157': { name: '삼전', x: 57.5, y: 73 },
    'station-158': { name: '석촌고분', x: 59, y: 74.5 },
    seokchon: { name: 'Seokchon', x: 59, y: 72, aka: ['석촌'] },
    'station-160': { name: '송파나루', x: 60.5, y: 71 },
    'station-161': { name: '한성백제', x: 62, y: 69.5 },
    'station-162': { name: '올림픽공원', x: 62, y: 71.5 },
    'station-163': { name: '둔촌오륜', x: 64, y: 72 },
    'vhs-medical-center': { name: 'VHS Medical Center', x: 64, y: 70.5, aka: ['중앙보훈병원'] },
    byeollae: { name: 'Byeollae', x: 63, y: 51.5, aka: ['별내'] },
    dasan: { name: 'Dasan', x: 64.5, y: 53, aka: ['다산'] },
    donggureung: { name: 'Donggureung', x: 64.5, y: 55, aka: ['동구릉'] },
    guri: { name: 'Guri', x: 64.5, y: 57, aka: ['구리'] },
    'jangja-lake-park': { name: 'Jangja Lake Park', x: 64.5, y: 59.5, aka: ['장자호수공원'] },
    'amsa-history-park': { name: 'Amsa History Park', x: 64, y: 61.5, aka: ['암사역사공원'] },
    amsa: { name: 'Amsa', x: 64, y: 63.5, aka: ['암사'] },
    cheonho: { name: 'Cheonho', x: 62.5, y: 65, aka: ['천호'] },
    'gangdong-gu-office': { name: 'Gangdong-gu Office', x: 62.5, y: 67, aka: ['강동구청'] },
    mongchontoseong: { name: 'Mongchontoseong', x: 61, y: 68.5, aka: ['몽촌토성'] },
    'station-175': { name: '잠실', x: 59.5, y: 70 },
    songpa: { name: 'Songpa', x: 60.5, y: 74, aka: ['송파'] },
    munjeong: { name: 'Munjeong', x: 62.5, y: 77, aka: ['문정'] },
    jangji: { name: 'Jangji', x: 64, y: 78.5, aka: ['장지'] },
    bokjeong: { name: 'Bokjeong', x: 63, y: 80, aka: ['복정'] },
    namwirye: { name: 'Namwirye', x: 64.5, y: 81, aka: ['남위례'] },
    sanseong: { name: 'Sanseong', x: 66, y: 82.5, aka: ['산성'] },
    namhansanseong: { name: 'Namhansanseong', x: 68, y: 82.5, aka: ['남한산성입구'] },
    dandaeogeori: { name: 'Dandaeogeori', x: 68, y: 84.5, aka: ['단대오거리'] },
    sinheung: { name: 'Sinheung', x: 66.5, y: 84.5, aka: ['신흥'] },
    sujin: { name: 'Sujin', x: 65, y: 86, aka: ['수진'] },
    moran: { name: 'Moran', x: 63, y: 85.5, aka: ['모란'] },
    'station-187': { name: '응암', x: 32, y: 54 },
    'station-188': { name: '역촌', x: 33.5, y: 53.5 },
    'station-189': { name: '불광', x: 33.5, y: 51.5 },
    'station-190': { name: '독바위', x: 35.5, y: 50 },
    'station-191': { name: '구산', x: 32, y: 52 },
    saejeol: { name: 'Saejeol', x: 33, y: 55.5, aka: ['새절'] },
    'station-193': { name: '증산', x: 32, y: 57 },
    'station-194': { name: '디지털미디어시티', x: 30.5, y: 59 },
    'station-195': { name: '월드컵경기장', x: 29, y: 60.5 },
    'station-196': { name: '마포구청', x: 30, y: 62 },
    'station-197': { name: '망원', x: 31.5, y: 63.5 },
    'station-198': { name: '합정', x: 31.5, y: 66 },
    'station-199': { name: '상수', x: 33.5, y: 66 },
    'station-200': { name: '광흥창', x: 34.5, y: 67.5 },
    'station-201': { name: '대흥', x: 36, y: 66 },
    'station-202': { name: '공덕', x: 37, y: 67.5 },
    'station-203': { name: '효창공원앞', x: 38.5, y: 69.5 },
    'station-204': { name: '녹사평', x: 42.5, y: 69 },
    'station-205': { name: '이태원', x: 44, y: 70 },
    'station-206': { name: '한강진', x: 45, y: 68.5 },
    'station-207': { name: '버티고개', x: 43.5, y: 66.5 },
    'station-208': { name: '약수', x: 44.5, y: 65 },
    'station-209': { name: '청구', x: 46.5, y: 63 },
    'station-210': { name: '신당', x: 46.5, y: 61 },
    'station-211': { name: '동묘앞', x: 47, y: 58.5 },
    'station-212': { name: '창신', x: 45.5, y: 57 },
    bomun: { name: 'Bomun', x: 47.5, y: 57, aka: ['보문'] },
    'station-214': { name: '안암', x: 49, y: 55.5 },
    'korea-univ': { name: 'Korea Univ.', x: 51, y: 56, aka: ['고려대'] },
    'station-216': { name: '월곡', x: 49.5, y: 54 },
    'station-217': { name: '상월곡', x: 51, y: 52.5 },
    'station-218': { name: '돌곶이', x: 52.5, y: 51 },
    'station-219': { name: '석계', x: 53, y: 49 },
    'station-220': { name: '태릉입구', x: 55, y: 49 },
    'station-221': { name: '화랑대', x: 57, y: 49.5 },
    bonghwasan: { name: 'Bonghwasan', x: 58.5, y: 50.5, aka: ['봉화산'] },
    'sinseol-dong': { name: 'Sinseol-dong', x: 48.5, y: 58.5, aka: ['신설동'] },
    'station-224': { name: '용두', x: 50.5, y: 59 },
    'station-225': { name: '신답', x: 53, y: 59 },
    'station-226': { name: '용답', x: 53, y: 61.5 },
    dorimcheon: { name: 'Dorimcheon', x: 29.5, y: 73.5, aka: ['도림천'] },
    'yangcheon-gu-office': { name: 'Yangcheon-gu Office', x: 27, y: 73.5, aka: ['양천구청'] },
    sinjeongnegeori: { name: 'Sinjeongnegeori', x: 25, y: 73, aka: ['신정네거리'] },
    kkachisan: { name: 'Kkachisan', x: 23.5, y: 71.5, aka: ['까치산'] },
    'dongdaemun-history-culture-park': { name: 'Dongdaemun History & Culture Park', x: 45.5, y: 60.5, aka: ['동대문역사문화공원'] },
    'wangsimni-seongdong-gu-office': { name: 'Wangsimni(Seongdong-Gu Office)', x: 49, y: 62, aka: ['왕십리(성동구청)'] },
    'station-233': { name: '경찰병원', x: 62, y: 74.5 },
    'station-234': { name: '대청', x: 55.5, y: 75 },
    'station-235': { name: '학여울', x: 54, y: 74 },
    'station-236': { name: '대치', x: 54, y: 75.5 },
    'station-237': { name: '매봉', x: 52, y: 77.5 },
    'station-238': { name: '압구정', x: 48, y: 69 },
    'station-239': { name: '금호', x: 45.5, y: 66 },
    'station-240': { name: '동대입구', x: 43.5, y: 63.5 },
    'station-241': { name: '충무로', x: 41.5, y: 65 },
    's-3': { name: '을지로3가', x: 41.5, y: 63 },
    'station-243': { name: '경복궁', x: 39.5, y: 58.5 },
    'station-244': { name: '독립문', x: 38.5, y: 57 },
    'station-245': { name: '무악재', x: 36.5, y: 57 },
    'station-246': { name: '홍제', x: 36.5, y: 55 },
    'station-247': { name: '녹번', x: 35, y: 53 },
    'station-248': { name: '연신내', x: 33.5, y: 49 },
    'station-249': { name: '구파발', x: 33, y: 47.5 },
    'sungshin-women-s-university': { name: 'Sungshin Women\'s University', x: 48, y: 54, aka: ['성신여대입구'] },
    changdong: { name: 'Changdong', x: 53.5, y: 40, aka: ['창동'] },
    macheon: { name: 'Macheon', x: 67.5, y: 74.5, aka: ['마천'] },
    'station-253': { name: '거여', x: 66, y: 76 },
    'station-254': { name: '개롱', x: 65, y: 74.5 },
    'station-255': { name: '방이', x: 61, y: 73 },
    'station-256': { name: '둔촌동', x: 64, y: 69 },
    'station-257': { name: '강동', x: 64, y: 67 },
    'sangil-dong': { name: 'Sangil-dong', x: 70.5, y: 62.5, aka: ['상일동'] },
    godeok: { name: 'Godeok', x: 68.5, y: 62.5, aka: ['고덕'] },
    'station-260': { name: '명일', x: 66, y: 63 },
    'station-261': { name: '굽은다리', x: 66, y: 65 },
    'station-262': { name: '길동', x: 66, y: 67 },
    'station-263': { name: '광나루', x: 60.5, y: 65 },
    'station-264': { name: '아차산', x: 59, y: 63.5 },
    'station-265': { name: '군자', x: 57.5, y: 62 },
    'station-266': { name: '장한평', x: 55.5, y: 62 },
    'station-267': { name: '답십리', x: 54, y: 60.5 },
    'station-268': { name: '마장', x: 52, y: 60.5 },
    'station-269': { name: '행당', x: 48.5, y: 63.5 },
    'station-270': { name: '신금호', x: 47, y: 65 },
    's-4': { name: '을지로4가', x: 43, y: 62 },
    gwanghwamun: { name: 'Gwanghwamun', x: 40, y: 60.5, aka: ['광화문'] },
    'station-273': { name: '서대문', x: 38.5, y: 62 },
    chungjeongno: { name: 'Chungjeongno', x: 37.5, y: 64, aka: ['충정로'] },
    'station-275': { name: '애오개', x: 37.5, y: 66 },
    'station-276': { name: '마포', x: 36, y: 69 },
    'station-277': { name: '여의나루', x: 35, y: 70 },
    singil: { name: 'Singil', x: 33.5, y: 73.5, aka: ['신길'] },
    'station-279': { name: '영등포시장', x: 32.5, y: 72 },
    'station-280': { name: '영등포구청', x: 30.5, y: 72 },
    yangpyeong: { name: 'Yangpyeong', x: 29, y: 70.5, aka: ['양평'] },
    omokgyo: { name: 'Omokgyo', x: 28, y: 71.5, aka: ['오목교'] },
    'mok-dong': { name: 'Mok-dong', x: 26.5, y: 70, aka: ['목동'] },
    sinjeong: { name: 'Sinjeong', x: 25.5, y: 71.5, aka: ['신정'] },
    hwagok: { name: 'Hwagok', x: 24, y: 69.5, aka: ['화곡'] },
    ujangsan: { name: 'Ujangsan', x: 23, y: 67.5, aka: ['우장산'] },
    balsan: { name: 'Balsan', x: 24.5, y: 66, aka: ['발산'] },
    magok: { name: 'Magok', x: 22.5, y: 66, aka: ['마곡'] },
    songjeong: { name: 'Songjeong', x: 21, y: 65.5, aka: ['송정'] },
    gaehwasan: { name: 'Gaehwasan', x: 19.5, y: 62, aka: ['개화산'] },
    'station-291': { name: '방화', x: 21, y: 60.5 },
    gwangmyeong: { name: 'Gwangmyeong', x: 33, y: 84, aka: ['광명'] },
    'geumcheon-gu-office': { name: 'Geumcheon-gu Office', x: 34.5, y: 82.5, aka: ['금천구청'] },
    doksan: { name: 'Doksan', x: 33, y: 81, aka: ['독산'] },
    'gasan-digital-complex': { name: 'Gasan Digital Complex', x: 31.5, y: 79.5, aka: ['가산디지털단지'] },
    guro: { name: 'Guro', x: 28, y: 76, aka: ['구로'] },
    yeongdeungpo: { name: 'Yeongdeungpo', x: 34.5, y: 76, aka: ['영등포'] },
    nonhyeon: { name: 'Nonhyeon', x: 47.5, y: 72.5, aka: ['논현'] },
    'yangjae-citizen-s-forest': { name: 'Yangjae Citizen\'s Forest', x: 52.5, y: 81, aka: ['양재시민의숲'] },
    cheonggyesan: { name: 'Cheonggyesan', x: 54, y: 83.5, aka: ['청계산입구'] },
    pangyo: { name: 'Pangyo', x: 56, y: 85.5, aka: ['판교'] },
    jeongja: { name: 'Jeongja', x: 56, y: 88.5, aka: ['정자'] },
    migeum: { name: 'Migeum', x: 56.5, y: 91, aka: ['미금'] },
    dongcheon: { name: 'Dongcheon', x: 56.5, y: 93.5, aka: ['동천'] },
    'suji-gu-office': { name: 'Suji-gu Office', x: 57, y: 96, aka: ['수지구청'] },
    seongbok: { name: 'Seongbok', x: 55.5, y: 98, aka: ['성복'] },
    sanghyeon: { name: 'Sanghyeon', x: 54, y: 99.5, aka: ['상현'] },
    'gwanggyo-jungang': { name: 'Gwanggyo Jungang', x: 52.5, y: 101.5, aka: ['광교중앙'] },
    gwanggyo: { name: 'Gwanggyo', x: 51, y: 101.5, aka: ['광교'] },
    soyosan: { name: 'Soyosan', x: 55, y: 8, aka: ['소요산'] },
    dongducheon: { name: 'Dongducheon', x: 55, y: 11, aka: ['동두천'] },
    bosan: { name: 'Bosan', x: 54, y: 12, aka: ['보산'] },
    dongducheonjungang: { name: 'Dongducheonjungang', x: 55, y: 13, aka: ['동두천중앙'] },
    jihaeng: { name: 'Jihaeng', x: 54.5, y: 15.5, aka: ['지행'] },
    'deokjeong-seojeong-college': { name: 'Deokjeong (Seojeong College)', x: 54.5, y: 18, aka: ['덕정'] },
    deokgye: { name: 'Deokgye', x: 54.5, y: 20, aka: ['덕계'] },
    yangju: { name: 'Yangju', x: 54.5, y: 22, aka: ['양주'] },
    nogyang: { name: 'Nogyang', x: 54, y: 24, aka: ['녹양'] },
    ganeung: { name: 'Ganeung', x: 52.5, y: 25.5, aka: ['가능'] },
    uijeongbu: { name: 'Uijeongbu', x: 54, y: 26, aka: ['의정부'] },
    hoeryong: { name: 'Hoeryong', x: 54, y: 30.5, aka: ['회룡'] },
    'mangwolsa-shinhan-university': { name: 'Mangwolsa (Shinhan University)', x: 54, y: 32.5, aka: ['망월사'] },
    dobongsan: { name: 'Dobongsan', x: 54, y: 35, aka: ['도봉산'] },
    dobong: { name: 'Dobong', x: 52.5, y: 36, aka: ['도봉'] },
    'banghak-dobong-gu-office': { name: 'Banghak (Dobong-gu Office)', x: 52.5, y: 37.5, aka: ['방학'] },
    nokcheon: { name: 'Nokcheon', x: 54.5, y: 41, aka: ['녹천'] },
    'wolgye-induk-university': { name: 'Wolgye (Induk University)', x: 54.5, y: 43, aka: ['월계'] },
    'kwangwoon-university': { name: 'Kwangwoon University', x: 53.5, y: 41.5, aka: ['광운대'] },
    seokgye: { name: 'Seokgye', x: 53.5, y: 45, aka: ['석계'] },
    'sinimun-korea-national-university-of-arts': { name: 'Sinimun (Korea National University of Arts)', x: 54, y: 47.5, aka: ['신이문'] },
    'hankuk-university-of-foreign-studies': { name: 'Hankuk University of Foreign Studies', x: 54, y: 50.5, aka: ['외대앞'] },
    hoegi: { name: 'Hoegi', x: 53, y: 52.5, aka: ['회기'] },
    'cheongnyangni-university-of-seoul': { name: 'Cheongnyangni (University of Seoul)', x: 51.5, y: 54.5, aka: ['청량리'] },
    jegidong: { name: 'Jegidong', x: 50, y: 56.5, aka: ['제기동'] },
    dongmyo: { name: 'Dongmyo', x: 47, y: 60, aka: ['동묘앞'] },
    'jongno-5-o-ga': { name: 'Jongno 5(o)-ga', x: 43, y: 59, aka: ['종로5가'] },
    jonggak: { name: 'Jonggak', x: 39.5, y: 63, aka: ['종각'] },
    namyeong: { name: 'Namyeong', x: 39.5, y: 70, aka: ['남영'] },
    yongsan: { name: 'Yongsan', x: 38, y: 71.5, aka: ['용산'] },
    daebang: { name: 'Daebang', x: 35.5, y: 75, aka: ['대방'] },
    guil: { name: 'Guil', x: 27.5, y: 77.5, aka: ['구일'] },
    gaebong: { name: 'Gaebong', x: 26, y: 76, aka: ['개봉'] },
    'oryu-dong': { name: 'Oryu-dong', x: 24.5, y: 75, aka: ['오류동'] },
    onsu: { name: 'Onsu', x: 22.5, y: 75, aka: ['온수'] },
    yeokgok: { name: 'Yeokgok', x: 24.5, y: 76.5, aka: ['역곡'] },
    sosa: { name: 'Sosa', x: 21.5, y: 76, aka: ['소사'] },
    bucheon: { name: 'Bucheon', x: 19.5, y: 76, aka: ['부천'] },
    'jung-dong': { name: 'Jung-dong', x: 18, y: 75.5, aka: ['중동'] },
    songnae: { name: 'Songnae', x: 16.5, y: 75.5, aka: ['송내'] },
    bugae: { name: 'Bugae', x: 14.5, y: 76, aka: ['부개'] },
    bupyeong: { name: 'Bupyeong', x: 13, y: 76, aka: ['부평'] },
    baegun: { name: 'Baegun', x: 12, y: 75, aka: ['백운'] },
    dongam: { name: 'Dongam', x: 12, y: 77, aka: ['동암'] },
    ganseok: { name: 'Ganseok', x: 10.5, y: 78, aka: ['간석'] },
    juan: { name: 'Juan', x: 10.5, y: 75.5, aka: ['주안'] },
    dohwa: { name: 'Dohwa', x: 9.5, y: 78, aka: ['도화'] },
    jemulpo: { name: 'Jemulpo', x: 9, y: 77, aka: ['제물포'] },
    dowon: { name: 'Dowon', x: 6.5, y: 77, aka: ['도원'] },
    dongincheon: { name: 'Dongincheon', x: 8, y: 75.5, aka: ['동인천'] },
    incheon: { name: 'Incheon', x: 6, y: 75.5, aka: ['인천'] },
    'dongducheonjungang-shinhan-university-campus-2': { name: 'Dongducheonjungang (Shinhan University Campus 2)', x: 54.5, y: 14, aka: ['동두천중앙'] },
    seoksu: { name: 'Seoksu', x: 35, y: 86, aka: ['석수'] },
    gwanak: { name: 'Gwanak', x: 35.5, y: 89, aka: ['관악'] },
    anyang: { name: 'Anyang', x: 36, y: 92.5, aka: ['안양'] },
    myeonghak: { name: 'Myeonghak', x: 36, y: 95, aka: ['명학'] },
    gunpo: { name: 'Gunpo', x: 37.5, y: 97, aka: ['군포'] },
    dangjeong: { name: 'Dangjeong', x: 38, y: 99.5, aka: ['당정'] },
    uiwang: { name: 'Uiwang', x: 38, y: 101, aka: ['의왕'] },
    'sungkyunkwan-univ': { name: 'Sungkyunkwan Univ', x: 41, y: 107.5, aka: ['성균관대'] },
    hwaseo: { name: 'Hwaseo', x: 41.5, y: 109.5, aka: ['화서'] },
    suwon: { name: 'Suwon', x: 42, y: 112, aka: ['수원'] },
    seryu: { name: 'Seryu', x: 43.5, y: 116, aka: ['세류'] },
    byeongjeom: { name: 'Byeongjeom', x: 44, y: 120, aka: ['병점'] },
    sema: { name: 'Sema', x: 45.5, y: 122, aka: ['세마'] },
    'osan-college': { name: 'Osan College', x: 45.5, y: 124.5, aka: ['오산대'] },
    osan: { name: 'Osan', x: 45.5, y: 127.5, aka: ['오산'] },
    jinwi: { name: 'Jinwi', x: 46, y: 130, aka: ['진위'] },
    songtan: { name: 'Songtan', x: 46.5, y: 132.5, aka: ['송탄'] },
    'seojeong-ri': { name: 'Seojeong-ri', x: 47, y: 134.5, aka: ['서정리'] },
    'pyeongtaek-jije': { name: 'Pyeongtaek Jije', x: 47.5, y: 137.5, aka: ['평택지제'] },
    pyeongtaek: { name: 'Pyeongtaek', x: 47.5, y: 139.5, aka: ['평택'] },
    seonghwan: { name: 'Seonghwan', x: 49, y: 147.5, aka: ['성환'] },
    jiksan: { name: 'Jiksan', x: 49.5, y: 149.5, aka: ['직산'] },
    dujeong: { name: 'Dujeong', x: 49.5, y: 151.5, aka: ['두정'] },
    cheonan: { name: 'Cheonan', x: 50.5, y: 158, aka: ['천안'] },
    bongmyeong: { name: 'Bongmyeong', x: 51, y: 162.5, aka: ['봉명'] },
    ssangyong: { name: 'Ssangyong', x: 51.5, y: 167, aka: ['쌍용'] },
    asan: { name: 'Asan', x: 51.5, y: 171, aka: ['아산'] },
    tangjeong: { name: 'Tangjeong', x: 52, y: 174, aka: ['탕정'] },
    baebang: { name: 'Baebang', x: 50.5, y: 176.5, aka: ['배방'] },
    onyangoncheon: { name: 'Onyangoncheon', x: 49, y: 179, aka: ['온양온천'] },
    sinchang: { name: 'Sinchang', x: 47, y: 179, aka: ['신창'] },
    'sungkyunkwan-university': { name: 'Sungkyunkwan University', x: 40, y: 108.5, aka: ['성균관대'] },
    seodongtan: { name: 'Seodongtan', x: 46, y: 120, aka: ['서동탄'] },
    'station-395': { name: '주안', x: 10.5, y: 76.5 },
    'station-396': { name: '송내', x: 17, y: 76.5 },
    'station-397': { name: '개봉', x: 26, y: 77 },
    'station-398': { name: '대방', x: 35, y: 73.5 },
    'station-399': { name: '수락산', x: 54.5, y: 37 },
    'station-400': { name: '마들', x: 55, y: 39.5 },
    'station-401': { name: '노원', x: 55.5, y: 42 },
    'station-402': { name: '중계', x: 55.5, y: 44 },
    'station-403': { name: '하계', x: 55.5, y: 46 },
    'station-404': { name: '공릉', x: 56.5, y: 47.5 },
    'station-405': { name: '먹골', x: 56.5, y: 51 },
    'station-406': { name: '중화', x: 56.5, y: 53 },
    'station-407': { name: '상봉', x: 58.5, y: 53 },
    'station-408': { name: '면목', x: 58.5, y: 55.5 },
    'station-409': { name: '사가정', x: 60, y: 57 },
    'station-410': { name: '용마산', x: 59, y: 58.5 },
    'station-411': { name: '중곡', x: 59, y: 60.5 },
    'station-412': { name: '어린이대공원', x: 56, y: 64 },
    'konkuk-univ': { name: 'Konkuk Univ.', x: 56, y: 66, aka: ['건대입구'] },
    jayang: { name: 'Jayang', x: 54.5, y: 67.5, aka: ['자양'] },
    'station-415': { name: '청담', x: 53, y: 69.5 },
    'gangnam-gu-office': { name: 'Gangnam-gu Office', x: 51.5, y: 69.5, aka: ['강남구청'] },
    'station-417': { name: '학동', x: 50, y: 71 },
    'station-418': { name: '논현', x: 48, y: 71 },
    'station-419': { name: '반포', x: 46, y: 73 },
    naebang: { name: 'Naebang', x: 43.5, y: 76, aka: ['내방'] },
    isu: { name: 'Isu', x: 42.5, y: 77.5, aka: ['이수'] },
    'station-422': { name: '남성', x: 40.5, y: 77.5 },
    'station-423': { name: '숭실대입구', x: 39.5, y: 76.5 },
    'station-424': { name: '상도', x: 38.5, y: 75 },
    'station-425': { name: '장승배기', x: 37, y: 75.5 },
    'station-426': { name: '신대방삼거리', x: 35.5, y: 77 },
    'station-427': { name: '보라매', x: 33.5, y: 77 },
    'station-428': { name: '신풍', x: 32.5, y: 75.5 },
    'station-429': { name: '대림', x: 31, y: 77 },
    'station-430': { name: '남구로', x: 29.5, y: 78 },
    'station-431': { name: '가산디지털단지', x: 28, y: 79.5 },
    cheolsan: { name: 'Cheolsan', x: 26, y: 79, aka: ['철산'] },
    'station-433': { name: '광명사거리', x: 24, y: 79 },
    'station-434': { name: '천왕', x: 22.5, y: 77.5 },
    jangam: { name: 'Jangam', x: 55.5, y: 33.5, aka: ['장암'] },
    sinnae: { name: 'Sinnae', x: 60.5, y: 50.5, aka: ['신내'] },
    'hanam-geomdansan': { name: 'Hanam Geomdansan', x: 78, y: 66, aka: ['하남검단산'] },
    'hanam-city-hall-deokpung-sinjang': { name: 'Hanam City Hall (Deokpung·Sinjang)', x: 76, y: 66, aka: ['하남시청'] },
    'station-439': { name: '하남풍산', x: 76, y: 64 },
    misa: { name: 'Misa', x: 74, y: 64, aka: ['미사'] },
    gangil: { name: 'Gangil', x: 72.5, y: 62.5, aka: ['강일'] },
    'station-442': { name: '미사', x: 74.5, y: 62.5 },
    'station-443': { name: '까치울', x: 21, y: 73.5 },
    'station-444': { name: '부천종합운동장', x: 18.5, y: 73.5 },
    'station-445': { name: '춘의', x: 16.5, y: 73.5 },
    'station-446': { name: '신중동', x: 14.5, y: 73 },
    'station-447': { name: '부천시청', x: 12.5, y: 73 },
    'station-448': { name: '상동', x: 10, y: 73 },
    'station-449': { name: '삼산체육관', x: 8, y: 73 },
    'station-450': { name: '굴포천', x: 6, y: 73 },
    'bupyeong-gu-office': { name: 'Bupyeong-gu Office', x: 4, y: 73, aka: ['부평구청'] },
    sangok: { name: 'Sangok', x: 2, y: 73, aka: ['산곡'] },
    seongnam: { name: 'Seongnam', x: 0, y: 73, aka: ['석남'] },
    byeollaebyeolgaram: { name: 'Byeollaebyeolgaram', x: 62, y: 37.5, aka: ['별내별가람'] },
    onam: { name: 'Onam', x: 63.5, y: 36, aka: ['오남'] },
    jinjeop: { name: 'Jinjeop', x: 65, y: 35, aka: ['진접'] },
    yeoncheon: { name: 'Yeoncheon', x: 55, y: 0, aka: ['연천'] },
    jeongok: { name: 'Jeongok', x: 55, y: 2.5, aka: ['전곡'] },
    cheongsan: { name: 'Cheongsan', x: 55, y: 5, aka: ['청산'] },
  },
};
