// Stockholm's Tunnelbana, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'stockholm',
  name: 'Stockholm',
  system: 'Tunnelbana',
  country: 'Sweden',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '10',
      short: '10',
      name: 'T10',
      colour: '#0065bd',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['kungstradgarden', 't-centralen', 'radhuset', 'fridhemsplan', 'stadshagen', 'vastra-skogen', 'huvudsta', 'solna-strand', 'sundbybergs-centrum', 'duvbo', 'rissne', 'rinkeby', 'tensta', 'hjulsta'],
        ['hjulsta', 'sundbybergs-centrum', 'solna-strand', 'huvudsta', 'vastra-skogen', 'stadshagen', 'fridhemsplan', 'radhuset', 't-centralen', 'kungstradgarden'],
      ],
    },
    {
      id: '11',
      short: '11',
      name: 'T11',
      colour: '#0065bd',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['akalla', 'husby', 'kista', 'nackrosen', 'solna-centrum', 'vastra-skogen', 'stadshagen', 'fridhemsplan', 'radhuset', 't-centralen', 'kungstradgarden'],
      ],
    },
    {
      id: '13',
      short: '13',
      name: 'T13',
      colour: '#e3000f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['norsborg', 'hallunda', 'alby', 'fittja', 'masmo', 'varby-gard', 'varberg', 'skarholmen', 'satra', 'bredang', 'malarhojden', 'axelsberg', 'ornsberg', 'aspudden', 'liljeholmen', 'hornstull', 'zinkensdamm', 'mariatorget', 'slussen', 'gamla-stan', 't-centralen', 'ostermalmstorg', 'karlaplan', 'gardet', 'ropsten'],
      ],
    },
    {
      id: '14',
      short: '14',
      name: '14',
      colour: '#e3000f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['morby-centrum', 'danderyds-sjukhus', 'bergshamra', 'universitetet', 'stadion', 'ostermalmstorg', 't-centralen', 'gamla-stan', 'slussen', 'mariatorget', 'zinkensdamm', 'hornstull', 'liljeholmen', 'midsommarkransen', 'telefonplan', 'hagerstensasen', 'vastertorp', 'fruangen'],
        ['fruangen', 'telefonplan', 'midsommarkransen', 'liljeholmen', 'hornstull', 'zinkensdamm', 'mariatorget', 'slussen', 'gamla-stan', 't-centralen', 'ostermalmstorg', 'universitetet', 'bergshamra', 'danderyds-sjukhus', 'morby-centrum'],
      ],
    },
    {
      id: '17',
      short: '17',
      name: 'T17',
      colour: '#00963f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hasselby-strand', 'hasselby-gard', 'johannelund', 'vallingby', 'racksta', 'blackeberg', 'islandstorget', 'angbyplan', 'akeshov', 'brommaplan', 'abrahamsberg', 'stora-mossen', 'alvik', 'kristineberg', 'thorildsplan', 'fridhemsplan', 'sankt-eriksplan', 'odenplan', 'radmansgatan', 'hotorget', 't-centralen', 'gamla-stan', 'slussen', 'medborgarplatsen', 'skanstull', 'gullmarsplan', 'skarmarbrink', 'hammarbyhojden', 'bjorkhagen', 'karrtorp', 'bagarmossen', 'skarpnack'],
        ['slussen', 'gamla-stan', 't-centralen', 'odenplan', 'fridhemsplan', 'thorildsplan', 'brommaplan', 'hasselby-strand'],
      ],
    },
    {
      id: '18',
      short: '18',
      name: 'T18',
      colour: '#00963f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hasselby-strand', 'hasselby-gard', 'johannelund', 'vallingby', 'racksta', 'blackeberg', 'islandstorget', 'angbyplan', 'akeshov', 'brommaplan', 'abrahamsberg', 'stora-mossen', 'alvik', 'kristineberg', 'thorildsplan', 'fridhemsplan', 'sankt-eriksplan', 'odenplan', 'radmansgatan', 'hotorget', 't-centralen', 'gamla-stan', 'slussen', 'medborgarplatsen', 'skanstull', 'gullmarsplan', 'skarmarbrink', 'blasut', 'sandsborg', 'skogskyrkogarden', 'tallkrogen', 'gubbangen', 'hokarangen', 'farsta', 'farsta-strand'],
      ],
    },
    {
      id: '19',
      short: '19',
      name: 'T19',
      colour: '#00963f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hasselby-strand', 'hasselby-gard', 'johannelund', 'vallingby', 'racksta', 'blackeberg', 'islandstorget', 'angbyplan', 'akeshov', 'brommaplan', 'abrahamsberg', 'stora-mossen', 'alvik', 'kristineberg', 'thorildsplan', 'fridhemsplan', 'sankt-eriksplan', 'odenplan', 'radmansgatan', 'hotorget', 't-centralen', 'gamla-stan', 'slussen', 'medborgarplatsen', 'skanstull', 'gullmarsplan', 'globen', 'enskede-gard', 'sockenplan', 'svedmyra', 'stureby', 'bandhagen', 'hogdalen', 'ragsved', 'hagsatra'],
        ['hagsatra', 'slussen', 'gamla-stan', 't-centralen', 'odenplan', 'fridhemsplan', 'thorildsplan', 'brommaplan', 'hasselby-strand'],
      ],
    },
  ],
  times: {
    'stadshagen vastra-skogen': 3,
    'duvbo rissne': 3,
    'rissne rinkeby': 3,
    'rinkeby tensta': 4,
    'hjulsta sundbybergs-centrum': 12,
    'vastra-skogen stadshagen': 3,
    'akalla husby': 3,
    'kista nackrosen': 9,
    'nackrosen solna-centrum': 3,
    'solna-centrum vastra-skogen': 3,
    'hallunda alby': 3,
    'alby fittja': 3,
    'fittja masmo': 3,
    'masmo varby-gard': 4,
    'varby-gard varberg': 3,
    'skarholmen satra': 3,
    'satra bredang': 3,
    'bredang malarhojden': 3,
    'malarhojden axelsberg': 3,
    'aspudden liljeholmen': 3,
    'slussen gamla-stan': 1,
    'gardet ropsten': 3,
    'danderyds-sjukhus bergshamra': 3,
    'bergshamra universitetet': 4,
    'universitetet stadion': 6,
    'gamla-stan slussen': 1,
    'liljeholmen midsommarkransen': 3,
    'telefonplan hagerstensasen': 3,
    'vastertorp fruangen': 1,
    'fruangen telefonplan': 5,
    'midsommarkransen liljeholmen': 3,
    'ostermalmstorg universitetet': 7,
    'universitetet bergshamra': 4,
    'bergshamra danderyds-sjukhus': 3,
    'vallingby racksta': 3,
    'alvik kristineberg': 3,
    'radmansgatan hotorget': 1,
    'hotorget t-centralen': 1,
    'slussen medborgarplatsen': 1,
    'karrtorp bagarmossen': 3,
    't-centralen odenplan': 3,
    'odenplan fridhemsplan': 3,
    'thorildsplan brommaplan': 8,
    'brommaplan hasselby-strand': 13,
    'skarmarbrink blasut': 1,
    'blasut sandsborg': 1,
    'hokarangen farsta': 4,
    'hogdalen ragsved': 3,
    'ragsved hagsatra': 3,
    'hagsatra slussen': 14,
  },
  stations: {
    hjulsta: { name: 'Hjulsta', x: 12, y: 4 },
    'sundbybergs-centrum': { name: 'Sundbybergs centrum', x: 13.5, y: 5.5 },
    'solna-strand': { name: 'Solna strand', x: 15, y: 7 },
    huvudsta: { name: 'Huvudsta', x: 17, y: 8.5 },
    'vastra-skogen': { name: 'Västra skogen', x: 19, y: 8 },
    stadshagen: { name: 'Stadshagen', x: 20.5, y: 10 },
    fridhemsplan: { name: 'Fridhemsplan', x: 21.5, y: 11.5 },
    radhuset: { name: 'Rådhuset', x: 23.5, y: 13 },
    't-centralen': { name: 'T-Centralen', x: 26, y: 13 },
    kungstradgarden: { name: 'Kungsträdgården', x: 28, y: 13 },
    duvbo: { name: 'Duvbo', x: 15, y: 4.5 },
    rissne: { name: 'Rissne', x: 13.5, y: 3.5 },
    rinkeby: { name: 'Rinkeby', x: 12.5, y: 2 },
    tensta: { name: 'Tensta', x: 10.5, y: 2.5 },
    akalla: { name: 'Akalla', x: 12.5, y: 0 },
    husby: { name: 'Husby', x: 14, y: 1.5 },
    kista: { name: 'Kista', x: 15.5, y: 3 },
    nackrosen: { name: 'Näckrosen', x: 16.5, y: 5 },
    'solna-centrum': { name: 'Solna centrum', x: 18, y: 6.5 },
    norsborg: { name: 'Norsborg', x: 0, y: 33 },
    hallunda: { name: 'Hallunda', x: 2, y: 33 },
    alby: { name: 'Alby', x: 4, y: 33 },
    fittja: { name: 'Fittja', x: 5.5, y: 31.5 },
    masmo: { name: 'Masmo', x: 7, y: 30.5 },
    'varby-gard': { name: 'Vårby gård', x: 7, y: 28 },
    varberg: { name: 'Vårberg', x: 8.5, y: 26.5 },
    skarholmen: { name: 'Skärholmen', x: 10, y: 25 },
    satra: { name: 'Sätra', x: 11.5, y: 23.5 },
    bredang: { name: 'Bredäng', x: 13, y: 22 },
    malarhojden: { name: 'Mälarhöjden', x: 14.5, y: 20.5 },
    axelsberg: { name: 'Axelsberg', x: 16, y: 19 },
    ornsberg: { name: 'Örnsberg', x: 18, y: 19 },
    aspudden: { name: 'Aspudden', x: 20, y: 19 },
    liljeholmen: { name: 'Liljeholmen', x: 22, y: 19 },
    hornstull: { name: 'Hornstull', x: 23, y: 17 },
    zinkensdamm: { name: 'Zinkensdamm', x: 24.5, y: 15.5 },
    mariatorget: { name: 'Mariatorget', x: 26, y: 17 },
    slussen: { name: 'Slussen', x: 26, y: 18.5 },
    'gamla-stan': { name: 'Gamla stan', x: 26, y: 15.5 },
    ostermalmstorg: { name: 'Östermalmstorg', x: 26.5, y: 10.5 },
    karlaplan: { name: 'Karlaplan', x: 28.5, y: 10.5 },
    gardet: { name: 'Gärdet', x: 30, y: 9.5 },
    ropsten: { name: 'Ropsten', x: 30, y: 7.5 },
    fruangen: { name: 'Fruängen', x: 18, y: 23 },
    telefonplan: { name: 'Telefonplan', x: 19, y: 22 },
    midsommarkransen: { name: 'Midsommarkransen', x: 20.5, y: 20.5 },
    universitetet: { name: 'Universitetet', x: 26.5, y: 8.5 },
    bergshamra: { name: 'Bergshamra', x: 26.5, y: 6 },
    'danderyds-sjukhus': { name: 'Danderyds sjukhus', x: 26.5, y: 4 },
    'morby-centrum': { name: 'Mörby centrum', x: 26.5, y: 2 },
    stadion: { name: 'Stadion', x: 28, y: 9.5 },
    hagerstensasen: { name: 'Hägerstensåsen', x: 17, y: 21.5 },
    vastertorp: { name: 'Västertorp', x: 16, y: 23 },
    odenplan: { name: 'Odenplan', x: 24, y: 11.5 },
    thorildsplan: { name: 'Thorildsplan', x: 19, y: 11 },
    brommaplan: { name: 'Brommaplan', x: 15.5, y: 10.5 },
    'hasselby-strand': { name: 'Hässelby strand', x: 13, y: 10 },
    'hasselby-gard': { name: 'Hässelby gård', x: 10.5, y: 8.5 },
    johannelund: { name: 'Johannelund', x: 9, y: 7 },
    vallingby: { name: 'Vällingby', x: 10.5, y: 7 },
    racksta: { name: 'Råcksta', x: 12, y: 8.5 },
    blackeberg: { name: 'Blackeberg', x: 9.5, y: 10 },
    islandstorget: { name: 'Islandstorget', x: 11.5, y: 10 },
    angbyplan: { name: 'Ängbyplan', x: 12.5, y: 11.5 },
    akeshov: { name: 'Åkeshov', x: 14, y: 11 },
    abrahamsberg: { name: 'Abrahamsberg', x: 16.5, y: 12 },
    'stora-mossen': { name: 'Stora mossen', x: 17.5, y: 13 },
    alvik: { name: 'Alvik', x: 19, y: 13 },
    kristineberg: { name: 'Kristineberg', x: 20.5, y: 12.5 },
    'sankt-eriksplan': { name: 'Sankt Eriksplan', x: 23, y: 10 },
    radmansgatan: { name: 'Rådmansgatan', x: 25.5, y: 11.5 },
    hotorget: { name: 'Hötorget', x: 27.5, y: 11.5 },
    medborgarplatsen: { name: 'Medborgarplatsen', x: 28, y: 16.5 },
    skanstull: { name: 'Skanstull', x: 29.5, y: 18 },
    gullmarsplan: { name: 'Gullmarsplan', x: 29.5, y: 20 },
    skarmarbrink: { name: 'Skärmarbrink', x: 31.5, y: 20 },
    hammarbyhojden: { name: 'Hammarbyhöjden', x: 33, y: 21.5 },
    bjorkhagen: { name: 'Björkhagen', x: 34.5, y: 23 },
    karrtorp: { name: 'Kärrtorp', x: 34.5, y: 25 },
    bagarmossen: { name: 'Bagarmossen', x: 36, y: 26.5 },
    skarpnack: { name: 'Skarpnäck', x: 36, y: 28.5 },
    blasut: { name: 'Blåsut', x: 31.5, y: 22 },
    sandsborg: { name: 'Sandsborg', x: 31.5, y: 24 },
    skogskyrkogarden: { name: 'Skogskyrkogården', x: 33, y: 25.5 },
    tallkrogen: { name: 'Tallkrogen', x: 31.5, y: 27 },
    gubbangen: { name: 'Gubbängen', x: 31.5, y: 29 },
    hokarangen: { name: 'Hökarängen', x: 31.5, y: 31 },
    farsta: { name: 'Farsta', x: 33, y: 32.5 },
    'farsta-strand': { name: 'Farsta strand', x: 34.5, y: 34 },
    hagsatra: { name: 'Hagsätra', x: 26, y: 21 },
    globen: { name: 'Globen', x: 30, y: 21.5 },
    'enskede-gard': { name: 'Enskede gård', x: 28, y: 21.5 },
    sockenplan: { name: 'Sockenplan', x: 29.5, y: 23 },
    svedmyra: { name: 'Svedmyra', x: 29.5, y: 24.5 },
    stureby: { name: 'Stureby', x: 27.5, y: 24.5 },
    bandhagen: { name: 'Bandhagen', x: 27.5, y: 26 },
    hogdalen: { name: 'Högdalen', x: 26, y: 25.5 },
    ragsved: { name: 'Rågsved', x: 26, y: 23.5 },
  },
};
