// Stuttgart's Stadtbahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'stuttgart',
  name: 'Stuttgart',
  system: 'Stadtbahn',
  country: 'Germany',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'u1',
      short: 'U1',
      name: 'U1',
      colour: '#c7956c',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['heslach-vogelrain', 'sudheimer-platz', 'bihlplatz', 'erwin-schoettle-platz', 'marienplatz', 'osterreichischer-platz', 'rotebuhlplatz', 'berliner-platz-hohe-strasse', 'berliner-platz-liederhalle', 'borsenplatz', 'hauptbahnhof-arnulf-klett-platz', 'staatsgalerie', 'neckartor', 'stockach', 'metzstrasse', 'mineralbader-naturkundemuseum', 'mercedesstrasse', 'bad-cannstatt-wilhelmsplatz', 'uff-kirchhof', 'augsburger-platz', 'nurnberger-strasse', 'antwerpener-strasse', 'beskidenstrasse', 'hohenstrasse', 'esslinger-strasse', 'schwabenlandhalle', 'fellbach-lutherkirche'],
      ],
    },
    {
      id: 'u2',
      short: 'U2',
      name: 'U2',
      colour: '#f58220',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['botnang', 'eltinger-strasse', 'millockerstrasse', 'beethovenstrasse', 'lindpaintnerstrasse', 'herderplatz', 'vogelsang', 'arndt-spittastrasse', 'schwab-bebelstrasse', 'schloss-johannesstrasse', 'berliner-platz-hohe-strasse', 'rotebuhlplatz', 'rathaus', 'charlottenplatz', 'staatsgalerie', 'neckartor', 'stockach', 'metzstrasse', 'mineralbader-naturkundemuseum', 'mercedesstrasse', 'bad-cannstatt-wilhelmsplatz', 'daimlerplatz', 'kursaal', 'gnesener-strasse', 'obere-ziegelei', 'hauptfriedhof', 'steinhaldenfeld', 'neugereut'],
      ],
    },
    {
      id: 'u3',
      short: 'U3',
      name: 'U3',
      colour: '#935f39',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['plieningen', 'landhaus', 'salzacker', 'plieninger-strasse', 'sigmaringer-strasse', 'mohringen-bahnhof', 'vaihinger-strasse', 'ssb-zentrum', 'ssb-am-wallgraben', 'jurastrasse', 'vaihingen'],
      ],
    },
    {
      id: 'u4',
      short: 'U4',
      name: 'U4',
      colour: '#7a68ae',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['unterturkheim-bf', 'wasenstrasse', 'inselstrasse', 'im-degen', 'brendle-grossmarkt', 'wangener-landhausstrasse', 'gaisburg', 'ostheim-leo-vetter-bad', 'ostendplatz', 'bergfriedhof', 'karl-olga-krankenhaus', 'stockach', 'neckartor', 'staatsgalerie', 'charlottenplatz', 'rathaus', 'rotebuhlplatz', 'berliner-platz-hohe-strasse', 'berliner-platz-liederhalle', 'rosenberg-seidenstrasse', 'russische-kirche', 'holderlinplatz'],
      ],
    },
    {
      id: 'u5',
      short: 'U5',
      name: 'U5',
      colour: '#00baf2',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['killesberg', 'pragfriedhof', 'stadtbibliothek', 'hauptbahnhof-arnulf-klett-platz', 'schlossplatz', 'charlottenplatz', 'olgaeck', 'dobelstrasse', 'bopser', 'weinsteige', 'degerloch', 'degerloch-albstrasse', 'peregrinastrasse', 'sonnenberg', 'riedsee', 'mohringen-bahnhof', 'vaihinger-strasse', 'rohrer-weg', 'mohringen-freibad', 'leinfelden-frank', 'leinf-unteraichen', 'leinfelden-bahnhof', 'leinfelden-neuer-markt-euchner'],
      ],
    },
    {
      id: 'u6',
      short: 'U6',
      name: 'U6',
      colour: '#ec008c',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['gerlingen', 'gerlingen-siedlung', 'breitwiesen', 'giebel', 'salamanderweg', 'bergheimer-hof', 'wolfbusch', 'rastatter-strasse', 'lowen-markt', 'landauer-strasse', 'feuerbach-pfostenwaldle', 'sportpark-feuerbach', 'fohrich', 'wilhelm-geiger-platz', 'feuerbach-bahnhof', 'maybachstrasse', 'pragsattel', 'lowentorbrucke', 'pragfriedhof', 'stadtbibliothek', 'hauptbahnhof-arnulf-klett-platz', 'schlossplatz', 'charlottenplatz', 'olgaeck', 'dobelstrasse', 'bopser', 'weinsteige', 'degerloch', 'degerloch-albstrasse', 'peregrinastrasse', 'sonnenberg', 'riedsee', 'mohringen-bahnhof', 'vaihinger-strasse', 'rohrer-weg', 'mohringen-freibad', 'fasanenhof-bonhoefferkirche', 'europaplatz', 'enbw-city', 'schelmenwasen', 'stadionstrasse', 'messe-west', 'flughafen-messe'],
      ],
    },
    {
      id: 'u7',
      short: 'U7',
      name: 'U7',
      colour: '#0eb48d',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['nellingen-ostfildern', 'nellingen-technische-akademie', 'scharnhauser-park-kreuzbrunnen', 'scharnhauser-park', 'parksiedlung', 'ruit-zinsholz', 'ruit', 'heumaden', 'bockelstrasse', 'schemppstrasse', 'sillenbuch', 'silberwald', 'ruhbank-fernsehturm', 'waldau', 'bopser', 'dobelstrasse', 'olgaeck', 'charlottenplatz', 'schlossplatz', 'hauptbahnhof-arnulf-klett-platz', 'stadtbibliothek', 'pragfriedhof', 'lowentorbrucke', 'pragsattel', 'sieglestrasse', 'borsigstrasse', 'friedrichswahl', 'hohensteinstrasse', 'kelterplatz', 'schozacher-strasse', 'furfelder-strasse', 'tapachstrasse', 'himmelsleiter', 'suttnerstrasse', 'freiberg', 'monchfeld'],
      ],
    },
    {
      id: 'u8',
      short: 'U8',
      name: 'U8',
      colour: '#c3b47d',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['nellingen-ostfildern', 'nellingen-technische-akademie', 'scharnhauser-park-kreuzbrunnen', 'scharnhauser-park', 'parksiedlung', 'ruit-zinsholz', 'ruit', 'heumaden', 'bockelstrasse', 'schemppstrasse', 'sillenbuch', 'silberwald', 'ruhbank-fernsehturm', 'waldau', 'weinsteige', 'degerloch', 'degerloch-albstrasse', 'peregrinastrasse', 'sonnenberg', 'riedsee', 'mohringen-bahnhof', 'vaihinger-strasse', 'ssb-zentrum', 'ssb-am-wallgraben', 'jurastrasse', 'vaihingen'],
      ],
    },
    {
      id: 'u9',
      short: 'U9',
      name: 'U9',
      colour: '#ffd503',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['hedelfingen', 'stadtwerke-stuttgart', 'wangen-marktplatz', 'wasenstrasse', 'inselstrasse', 'im-degen', 'brendle-grossmarkt', 'wangener-landhausstrasse', 'schlachthof', 'raitelsberg', 'bergfriedhof', 'karl-olga-krankenhaus', 'stockach', 'neckartor', 'staatsgalerie', 'hauptbahnhof-arnulf-klett-platz', 'borsenplatz', 'berliner-platz-liederhalle', 'schloss-johannesstrasse', 'schwab-bebelstrasse', 'arndt-spittastrasse', 'vogelsang', 'herderplatz', 'lindpaintnerstrasse', 'beethovenstrasse', 'millockerstrasse', 'eltinger-strasse', 'botnang'],
      ],
    },
    {
      id: 'u11',
      short: 'U11',
      name: 'U11',
      colour: '#cccccc',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['hauptbahnhof-arnulf-klett-platz', 'borsenplatz', 'berliner-platz-liederhalle', 'rotebuhlplatz', 'rathaus', 'charlottenplatz', 'staatsgalerie', 'neckartor', 'stockach', 'metzstrasse', 'mineralbader-naturkundemuseum', 'mercedesstrasse', 'cannstatter-wasen', 'neckarpark-stadion'],
        ['neckarpark-stadion', 'cannstatter-wasen', 'mercedesstrasse', 'mineralbader-naturkundemuseum', 'metzstrasse', 'stockach', 'neckartor', 'staatsgalerie', 'hauptbahnhof-arnulf-klett-platz'],
      ],
    },
    {
      id: 'u12',
      short: 'U12',
      name: 'U12',
      colour: '#93bbe9',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['durrlewang', 'lapp-kabel', 'ssb-am-wallgraben', 'ssb-zentrum', 'vaihinger-strasse', 'mohringen-bahnhof', 'riedsee', 'sonnenberg', 'peregrinastrasse', 'degerloch-albstrasse', 'degerloch', 'weinsteige', 'bopser', 'dobelstrasse', 'olgaeck', 'charlottenplatz', 'schlossplatz', 'hauptbahnhof-arnulf-klett-platz', 'budapester-platz', 'milchhof', 'mittnachtstrasse', 'nordbahnhof', 'lowentor', 'zuricher-strasse', 'riethmullerhaus', 'hallschlag', 'bottroper-strasse', 'wagrainacker', 'max-eyth-see', 'hofen', 'auwiesen', 'muhlhausen', 'aldingen-hornbach', 'aldingen-muhle', 'aldingen-bruckenstrasse', 'remseck-neckargroningen'],
      ],
    },
    {
      id: 'u13',
      short: 'U13',
      name: 'U13',
      colour: '#eda5b4',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['hedelfingen', 'stadtwerke-stuttgart', 'wangen-marktplatz', 'wasenstrasse', 'unterturkheim-bf', 'schlotterbeckstrasse', 'eszet', 'blick', 'kienbachstrasse', 'ebitzweg', 'uff-kirchhof', 'bad-cannstatt-wilhelmsplatz', 'mercedesstrasse', 'wilhelma', 'rosensteinbrucke', 'glockenstrasse-mahle', 'rosensteinpark', 'lowentor', 'pragsattel', 'maybachstrasse', 'feuerbach-bahnhof', 'wilhelm-geiger-platz', 'fohrich', 'sportpark-feuerbach', 'feuerbach-pfostenwaldle'],
      ],
    },
    {
      id: 'u14',
      short: 'U14',
      name: 'U14',
      colour: '#69be51',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['vaihingen', 'vaihingen-schillerplatz', 'fauststrasse', 'vaihingen-viadukt', 'engelboldstrasse', 'kaltental', 'waldeck', 'heslach-vogelrain', 'sudheimer-platz', 'bihlplatz', 'erwin-schoettle-platz', 'marienplatz', 'osterreichischer-platz', 'rathaus', 'charlottenplatz', 'staatsgalerie', 'neckartor', 'stockach', 'metzstrasse', 'mineralbader-naturkundemuseum', 'wilhelma', 'rosensteinbrucke', 'muhlsteg', 'kraftwerk-munster', 'munster-viadukt', 'munster-rathaus', 'freibergstrasse', 'elbestrasse', 'wagrainacker', 'max-eyth-see', 'hofen', 'auwiesen', 'muhlhausen'],
      ],
    },
    {
      id: 'u15',
      short: 'U15',
      name: 'U15',
      colour: '#005aab',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['heumaden', 'bockelstrasse', 'schemppstrasse', 'sillenbuch', 'silberwald', 'ruhbank-fernsehturm', 'stelle', 'geroksruhe', 'payerstrasse', 'bubenbad', 'stafflenbergstrasse', 'heidehofstrasse', 'eugensplatz', 'olgaeck', 'charlottenplatz', 'schlossplatz', 'hauptbahnhof-arnulf-klett-platz', 'stadtbibliothek', 'pragfriedhof', 'lowentorbrucke', 'pragsattel', 'sieglestrasse', 'borsigstrasse', 'friedrichswahl', 'hohensteinstrasse', 'zuffenhausen-rathaus', 'kirchtalstrasse', 'salzwiesenstrasse', 'wimpfener-strasse', 'heutingsheimer-strasse', 'korntaler-strasse', 'stammheim'],
      ],
    },
    {
      id: 'u16',
      short: 'U16',
      name: 'U16',
      colour: '#bac219',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['giebel', 'salamanderweg', 'bergheimer-hof', 'wolfbusch', 'rastatter-strasse', 'lowen-markt', 'landauer-strasse', 'feuerbach-pfostenwaldle', 'sportpark-feuerbach', 'fohrich', 'wilhelm-geiger-platz', 'feuerbach-bahnhof', 'maybachstrasse', 'pragsattel', 'lowentor', 'rosensteinpark', 'glockenstrasse-mahle', 'rosensteinbrucke', 'wilhelma', 'mercedesstrasse', 'bad-cannstatt-wilhelmsplatz', 'uff-kirchhof', 'augsburger-platz', 'nurnberger-strasse', 'antwerpener-strasse', 'beskidenstrasse', 'hohenstrasse', 'esslinger-strasse', 'schwabenlandhalle', 'fellbach-lutherkirche'],
      ],
    },
    {
      id: 'u19',
      short: 'U19',
      name: 'U19',
      colour: '#cccccc',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['neugereut', 'steinhaldenfeld', 'hauptfriedhof', 'obere-ziegelei', 'gnesener-strasse', 'kursaal', 'daimlerplatz', 'bad-cannstatt-wilhelmsplatz', 'cannstatter-wasen', 'neckarpark-stadion'],
      ],
    },
  ],
  times: {
    'sudheimer-platz bihlplatz': 2,
    'bihlplatz erwin-schoettle-platz': 2,
    'erwin-schoettle-platz marienplatz': 2,
    'marienplatz osterreichischer-platz': 2,
    'berliner-platz-liederhalle borsenplatz': 2,
    'metzstrasse mineralbader-naturkundemuseum': 2,
    'bad-cannstatt-wilhelmsplatz uff-kirchhof': 2,
    'antwerpener-strasse beskidenstrasse': 2,
    'beskidenstrasse hohenstrasse': 2,
    'charlottenplatz staatsgalerie': 2,
    'kursaal gnesener-strasse': 2,
    'gnesener-strasse obere-ziegelei': 2,
    'hauptfriedhof steinhaldenfeld': 3,
    'plieningen landhaus': 6,
    'mohringen-bahnhof vaihinger-strasse': 2,
    'vaihinger-strasse ssb-zentrum': 2,
    'ssb-am-wallgraben jurastrasse': 2,
    'unterturkheim-bf wasenstrasse': 2,
    'im-degen brendle-grossmarkt': 2,
    'staatsgalerie charlottenplatz': 2,
    'killesberg pragfriedhof': 2,
    'pragfriedhof stadtbibliothek': 2,
    'stadtbibliothek hauptbahnhof-arnulf-klett-platz': 2,
    'bopser weinsteige': 3,
    'weinsteige degerloch': 2,
    'sonnenberg riedsee': 2,
    'vaihinger-strasse rohrer-weg': 2,
    'rohrer-weg mohringen-freibad': 2,
    'mohringen-freibad leinfelden-frank': 2,
    'leinf-unteraichen leinfelden-bahnhof': 2,
    'gerlingen gerlingen-siedlung': 2,
    'gerlingen-siedlung breitwiesen': 2,
    'salamanderweg bergheimer-hof': 2,
    'lowen-markt landauer-strasse': 2,
    'landauer-strasse feuerbach-pfostenwaldle': 2,
    'fohrich wilhelm-geiger-platz': 2,
    'wilhelm-geiger-platz feuerbach-bahnhof': 2,
    'feuerbach-bahnhof maybachstrasse': 2,
    'pragsattel lowentorbrucke': 2,
    'lowentorbrucke pragfriedhof': 2,
    'mohringen-freibad fasanenhof-bonhoefferkirche': 3,
    'schelmenwasen stadionstrasse': 3,
    'stadionstrasse messe-west': 2,
    'messe-west flughafen-messe': 2,
    'nellingen-technische-akademie scharnhauser-park-kreuzbrunnen': 3,
    'scharnhauser-park-kreuzbrunnen scharnhauser-park': 2,
    'parksiedlung ruit-zinsholz': 2,
    'ruit-zinsholz ruit': 2,
    'ruit heumaden': 4,
    'bockelstrasse schemppstrasse': 2,
    'silberwald ruhbank-fernsehturm': 2,
    'waldau bopser': 4,
    'hauptbahnhof-arnulf-klett-platz stadtbibliothek': 2,
    'stadtbibliothek pragfriedhof': 2,
    'pragfriedhof lowentorbrucke': 2,
    'lowentorbrucke pragsattel': 2,
    'pragsattel sieglestrasse': 2,
    'kelterplatz schozacher-strasse': 2,
    'tapachstrasse himmelsleiter': 2,
    'waldau weinsteige': 3,
    'hedelfingen stadtwerke-stuttgart': 2,
    'wangener-landhausstrasse schlachthof': 2,
    'borsenplatz berliner-platz-liederhalle': 2,
    'mercedesstrasse cannstatter-wasen': 2,
    'cannstatter-wasen mercedesstrasse': 2,
    'mineralbader-naturkundemuseum metzstrasse': 2,
    'lapp-kabel ssb-am-wallgraben': 2,
    'ssb-zentrum vaihinger-strasse': 2,
    'vaihinger-strasse mohringen-bahnhof': 2,
    'riedsee sonnenberg': 2,
    'degerloch weinsteige': 2,
    'weinsteige bopser': 3,
    'hauptbahnhof-arnulf-klett-platz budapester-platz': 2,
    'mittnachtstrasse nordbahnhof': 2,
    'lowentor zuricher-strasse': 2,
    'bottroper-strasse wagrainacker': 2,
    'muhlhausen aldingen-hornbach': 5,
    'aldingen-hornbach aldingen-muhle': 2,
    'aldingen-muhle aldingen-bruckenstrasse': 2,
    'aldingen-bruckenstrasse remseck-neckargroningen': 3,
    'wasenstrasse unterturkheim-bf': 2,
    'eszet blick': 2,
    'blick kienbachstrasse': 2,
    'uff-kirchhof bad-cannstatt-wilhelmsplatz': 2,
    'glockenstrasse-mahle rosensteinpark': 2,
    'maybachstrasse feuerbach-bahnhof': 2,
    'feuerbach-bahnhof wilhelm-geiger-platz': 2,
    'wilhelm-geiger-platz fohrich': 2,
    'vaihingen-viadukt engelboldstrasse': 2,
    'kaltental waldeck': 2,
    'waldeck heslach-vogelrain': 2,
    'mineralbader-naturkundemuseum wilhelma': 2,
    'rosensteinbrucke muhlsteg': 2,
    'munster-viadukt munster-rathaus': 2,
    'freibergstrasse elbestrasse': 2,
    'ruhbank-fernsehturm stelle': 2,
    'kirchtalstrasse salzwiesenstrasse': 2,
    'rosensteinpark glockenstrasse-mahle': 2,
    'steinhaldenfeld hauptfriedhof': 3,
    'obere-ziegelei gnesener-strasse': 2,
    'gnesener-strasse kursaal': 2,
    'bad-cannstatt-wilhelmsplatz cannstatter-wasen': 2,
  },
  stations: {
    plieningen: { name: 'Plieningen', x: 30, y: 61.5 },
    landhaus: { name: 'Landhaus', x: 28.5, y: 60 },
    salzacker: { name: 'Salzäcker', x: 27, y: 58.5 },
    'plieninger-strasse': { name: 'Plieninger Straße', x: 25.5, y: 57 },
    'sigmaringer-strasse': { name: 'Sigmaringer Straße', x: 24, y: 55.5 },
    'mohringen-bahnhof': { name: 'Möhringen Bahnhof', x: 22.5, y: 54.5 },
    'vaihinger-strasse': { name: 'Vaihinger Straße', x: 21, y: 56 },
    'ssb-zentrum': { name: 'SSB-Zentrum', x: 19, y: 56 },
    'ssb-am-wallgraben': { name: 'SSB am Wallgraben', x: 16.5, y: 55.5 },
    jurastrasse: { name: 'Jurastraße', x: 14.5, y: 55.5 },
    vaihingen: { name: 'Vaihingen', x: 13, y: 57 },
    'nellingen-ostfildern': { name: 'Nellingen Ostfildern', x: 59, y: 59.5 },
    'nellingen-technische-akademie': { name: 'Nellingen Technische Akademie', x: 57, y: 59.5 },
    'scharnhauser-park-kreuzbrunnen': { name: 'Scharnhauser Park Kreuzbrunnen', x: 55, y: 59.5 },
    'scharnhauser-park': { name: 'Scharnhauser Park', x: 53.5, y: 58 },
    parksiedlung: { name: 'Parksiedlung', x: 52, y: 56.5 },
    'ruit-zinsholz': { name: 'Ruit Zinsholz', x: 50, y: 55 },
    ruit: { name: 'Ruit', x: 48.5, y: 53.5 },
    heumaden: { name: 'Heumaden', x: 46.5, y: 52 },
    bockelstrasse: { name: 'Bockelstraße', x: 45, y: 50.5 },
    schemppstrasse: { name: 'Schemppstraße', x: 43, y: 49 },
    sillenbuch: { name: 'Sillenbuch', x: 41.5, y: 47.5 },
    silberwald: { name: 'Silberwald', x: 39.5, y: 46 },
    'ruhbank-fernsehturm': { name: 'Ruhbank (Fernsehturm)', x: 37.5, y: 44.5 },
    waldau: { name: 'Waldau', x: 35.5, y: 44 },
    weinsteige: { name: 'Weinsteige', x: 33, y: 44 },
    degerloch: { name: 'Degerloch', x: 31, y: 46 },
    'degerloch-albstrasse': { name: 'Degerloch Albstraße', x: 29.5, y: 47.5 },
    peregrinastrasse: { name: 'Peregrinastraße', x: 27.5, y: 49 },
    sonnenberg: { name: 'Sonnenberg', x: 26, y: 51 },
    riedsee: { name: 'Riedsee', x: 24.5, y: 52.5 },
    'heslach-vogelrain': { name: 'Heslach Vogelrain', x: 22, y: 46.5 },
    'sudheimer-platz': { name: 'Südheimer Platz', x: 23.5, y: 44.5 },
    bihlplatz: { name: 'Bihlplatz', x: 25, y: 43 },
    'erwin-schoettle-platz': { name: 'Erwin-Schoettle-Platz', x: 26.5, y: 41.5 },
    marienplatz: { name: 'Marienplatz', x: 28, y: 40 },
    'osterreichischer-platz': { name: 'Österreichischer Platz', x: 29.5, y: 38 },
    rotebuhlplatz: { name: 'Rotebühlplatz', x: 29.5, y: 36 },
    'berliner-platz-hohe-strasse': { name: 'Berliner Platz (Hohe Straße)', x: 27.5, y: 36 },
    'berliner-platz-liederhalle': { name: 'Berliner Platz (Liederhalle)', x: 28.5, y: 34.5 },
    borsenplatz: { name: 'Börsenplatz', x: 30, y: 33 },
    'hauptbahnhof-arnulf-klett-platz': { name: 'Hauptbahnhof (Arnulf-Klett-Platz)', x: 31.5, y: 31.5 },
    staatsgalerie: { name: 'Staatsgalerie', x: 33, y: 33 },
    neckartor: { name: 'Neckartor', x: 34.5, y: 31.5 },
    stockach: { name: 'Stöckach', x: 36, y: 29.5 },
    metzstrasse: { name: 'Metzstraße', x: 37.5, y: 28 },
    'mineralbader-naturkundemuseum': { name: 'Mineralbäder (Naturkundemuseum)', x: 39, y: 26.5 },
    mercedesstrasse: { name: 'Mercedesstraße', x: 40.5, y: 25.5 },
    'bad-cannstatt-wilhelmsplatz': { name: 'Bad Cannstatt Wilhelmsplatz', x: 42, y: 24.5 },
    'uff-kirchhof': { name: 'Uff-Kirchhof', x: 43.5, y: 23.5 },
    'augsburger-platz': { name: 'Augsburger Platz', x: 45, y: 22 },
    'nurnberger-strasse': { name: 'Nürnberger Straße', x: 47.5, y: 21.5 },
    'antwerpener-strasse': { name: 'Antwerpener Straße', x: 49.5, y: 21.5 },
    beskidenstrasse: { name: 'Beskidenstraße', x: 51.5, y: 21.5 },
    hohenstrasse: { name: 'Höhenstraße', x: 53.5, y: 21.5 },
    'esslinger-strasse': { name: 'Esslinger Straße', x: 55.5, y: 21.5 },
    schwabenlandhalle: { name: 'Schwabenlandhalle', x: 55.5, y: 23.5 },
    'fellbach-lutherkirche': { name: 'Fellbach Lutherkirche', x: 57.5, y: 23.5 },
    hedelfingen: { name: 'Hedelfingen', x: 53, y: 39.5 },
    'stadtwerke-stuttgart': { name: 'Stadtwerke Stuttgart', x: 51.5, y: 38 },
    'wangen-marktplatz': { name: 'Wangen Marktplatz', x: 50, y: 36.5 },
    wasenstrasse: { name: 'Wasenstraße', x: 50, y: 34.5 },
    'unterturkheim-bf': { name: 'Untertürkheim Bf', x: 51.5, y: 33 },
    schlotterbeckstrasse: { name: 'Schlotterbeckstraße', x: 51.5, y: 30.5 },
    eszet: { name: 'Eszet', x: 50, y: 29 },
    blick: { name: 'Blick', x: 48.5, y: 27 },
    kienbachstrasse: { name: 'Kienbachstraße', x: 47, y: 25.5 },
    ebitzweg: { name: 'Ebitzweg', x: 45.5, y: 23.5 },
    wilhelma: { name: 'Wilhelma', x: 39, y: 24.5 },
    rosensteinbrucke: { name: 'Rosensteinbrücke', x: 40.5, y: 22.5 },
    'glockenstrasse-mahle': { name: 'Glockenstraße (Mahle)', x: 38.5, y: 22.5 },
    rosensteinpark: { name: 'Rosensteinpark', x: 36.5, y: 22 },
    lowentor: { name: 'Löwentor', x: 34.5, y: 22 },
    pragsattel: { name: 'Pragsattel', x: 32, y: 22 },
    maybachstrasse: { name: 'Maybachstraße', x: 30.5, y: 20.5 },
    'feuerbach-bahnhof': { name: 'Feuerbach Bahnhof', x: 28, y: 20.5 },
    'wilhelm-geiger-platz': { name: 'Wilhelm-Geiger-Platz', x: 26, y: 20.5 },
    fohrich: { name: 'Föhrich', x: 23.5, y: 20.5 },
    'sportpark-feuerbach': { name: 'Sportpark Feuerbach', x: 21.5, y: 20.5 },
    'feuerbach-pfostenwaldle': { name: 'Feuerbach Pfostenwäldle', x: 19.5, y: 20 },
    bopser: { name: 'Bopser', x: 34, y: 42.5 },
    dobelstrasse: { name: 'Dobelstraße', x: 34, y: 40 },
    olgaeck: { name: 'Olgaeck', x: 34, y: 37.5 },
    charlottenplatz: { name: 'Charlottenplatz', x: 32.5, y: 35.5 },
    schlossplatz: { name: 'Schlossplatz', x: 31.5, y: 33.5 },
    stadtbibliothek: { name: 'Stadtbibliothek', x: 31.5, y: 29 },
    pragfriedhof: { name: 'Pragfriedhof', x: 31.5, y: 26.5 },
    lowentorbrucke: { name: 'Löwentorbrücke', x: 32, y: 24.5 },
    sieglestrasse: { name: 'Sieglestraße', x: 32, y: 20 },
    borsigstrasse: { name: 'Borsigstraße', x: 31, y: 18.5 },
    friedrichswahl: { name: 'Friedrichswahl', x: 29.5, y: 17 },
    hohensteinstrasse: { name: 'Hohensteinstraße', x: 29.5, y: 14.5 },
    kelterplatz: { name: 'Kelterplatz', x: 31, y: 13.5 },
    'schozacher-strasse': { name: 'Schozacher Straße', x: 32.5, y: 12 },
    'furfelder-strasse': { name: 'Fürfelder Straße', x: 34.5, y: 12 },
    tapachstrasse: { name: 'Tapachstraße', x: 36, y: 10.5 },
    himmelsleiter: { name: 'Himmelsleiter', x: 37.5, y: 9 },
    suttnerstrasse: { name: 'Suttnerstraße', x: 38.5, y: 7.5 },
    freiberg: { name: 'Freiberg', x: 40, y: 6 },
    monchfeld: { name: 'Mönchfeld', x: 42, y: 6 },
    killesberg: { name: 'Killesberg', x: 29.5, y: 26.5 },
    'rohrer-weg': { name: 'Rohrer Weg', x: 21, y: 58.5 },
    'mohringen-freibad': { name: 'Möhringen Freibad', x: 22, y: 60 },
    'leinfelden-frank': { name: 'Leinfelden Frank', x: 22, y: 62 },
    'leinf-unteraichen': { name: 'Leinf. Unteraichen', x: 22, y: 64 },
    'leinfelden-bahnhof': { name: 'Leinfelden Bahnhof', x: 22, y: 66 },
    'leinfelden-neuer-markt-euchner': { name: 'Leinfelden Neuer Markt (EUCHNER)', x: 22, y: 68.5 },
    gerlingen: { name: 'Gerlingen', x: 0, y: 24 },
    'gerlingen-siedlung': { name: 'Gerlingen Siedlung', x: 2, y: 24 },
    breitwiesen: { name: 'Breitwiesen', x: 4, y: 24 },
    giebel: { name: 'Giebel', x: 6, y: 24 },
    salamanderweg: { name: 'Salamanderweg', x: 8, y: 24 },
    'bergheimer-hof': { name: 'Bergheimer Hof', x: 10.5, y: 24 },
    wolfbusch: { name: 'Wolfbusch', x: 12, y: 23 },
    'rastatter-strasse': { name: 'Rastatter Straße', x: 13.5, y: 21.5 },
    'lowen-markt': { name: 'Löwen-Markt', x: 15, y: 20 },
    'landauer-strasse': { name: 'Landauer Straße', x: 17, y: 20 },
    'fasanenhof-bonhoefferkirche': { name: 'Fasanenhof (Bonhoefferkirche)', x: 23.5, y: 61.5 },
    europaplatz: { name: 'Europaplatz', x: 25.5, y: 62 },
    'enbw-city': { name: 'EnBW City', x: 27, y: 63.5 },
    schelmenwasen: { name: 'Schelmenwasen', x: 28.5, y: 65 },
    stadionstrasse: { name: 'Stadionstraße', x: 30, y: 66.5 },
    'messe-west': { name: 'Messe West', x: 31.5, y: 68 },
    'flughafen-messe': { name: 'Flughafen/Messe', x: 33.5, y: 68 },
    stelle: { name: 'Stelle', x: 38, y: 42.5 },
    geroksruhe: { name: 'Geroksruhe', x: 38, y: 40.5 },
    payerstrasse: { name: 'Payerstraße', x: 36.5, y: 39.5 },
    bubenbad: { name: 'Bubenbad', x: 36.5, y: 37.5 },
    stafflenbergstrasse: { name: 'Stafflenbergstraße', x: 35, y: 36 },
    heidehofstrasse: { name: 'Heidehofstraße', x: 36.5, y: 35 },
    eugensplatz: { name: 'Eugensplatz', x: 34, y: 35 },
    'zuffenhausen-rathaus': { name: 'Zuffenhausen Rathaus', x: 29.5, y: 12.5 },
    kirchtalstrasse: { name: 'Kirchtalstraße', x: 27.5, y: 12.5 },
    salzwiesenstrasse: { name: 'Salzwiesenstraße', x: 26, y: 11 },
    'wimpfener-strasse': { name: 'Wimpfener Straße', x: 25, y: 9.5 },
    'heutingsheimer-strasse': { name: 'Heutingsheimer Straße', x: 25, y: 7.5 },
    'korntaler-strasse': { name: 'Korntaler Straße', x: 23.5, y: 6 },
    stammheim: { name: 'Stammheim', x: 23.5, y: 4 },
    botnang: { name: 'Botnang', x: 14, y: 34.5 },
    'eltinger-strasse': { name: 'Eltinger Straße', x: 16, y: 34.5 },
    millockerstrasse: { name: 'Millöckerstraße', x: 17.5, y: 33 },
    beethovenstrasse: { name: 'Beethovenstraße', x: 17.5, y: 35 },
    lindpaintnerstrasse: { name: 'Lindpaintnerstraße', x: 17.5, y: 37 },
    herderplatz: { name: 'Herderplatz', x: 19.5, y: 37 },
    vogelsang: { name: 'Vogelsang', x: 21, y: 35.5 },
    'arndt-spittastrasse': { name: 'Arndt-/Spittastraße', x: 23, y: 35.5 },
    'schwab-bebelstrasse': { name: 'Schwab-/Bebelstraße', x: 25, y: 35.5 },
    'schloss-johannesstrasse': { name: 'Schloss-/Johannesstraße', x: 26.5, y: 34.5 },
    rathaus: { name: 'Rathaus', x: 31, y: 37 },
    daimlerplatz: { name: 'Daimlerplatz', x: 42, y: 22.5 },
    kursaal: { name: 'Kursaal', x: 43.5, y: 21 },
    'gnesener-strasse': { name: 'Gnesener Straße', x: 45, y: 19.5 },
    'obere-ziegelei': { name: 'Obere Ziegelei', x: 46.5, y: 18.5 },
    hauptfriedhof: { name: 'Hauptfriedhof', x: 46.5, y: 16.5 },
    steinhaldenfeld: { name: 'Steinhaldenfeld', x: 46.5, y: 14 },
    neugereut: { name: 'Neugereut', x: 46.5, y: 12 },
    inselstrasse: { name: 'Inselstraße', x: 48.5, y: 34.5 },
    'im-degen': { name: 'Im Degen', x: 47, y: 33.5 },
    'brendle-grossmarkt': { name: 'Brendle (Großmarkt)', x: 45.5, y: 32.5 },
    'wangener-landhausstrasse': { name: 'Wangener-/Landhausstraße', x: 44, y: 31 },
    gaisburg: { name: 'Gaisburg', x: 42.5, y: 31.5 },
    'ostheim-leo-vetter-bad': { name: 'Ostheim Leo-Vetter-Bad', x: 41, y: 30 },
    ostendplatz: { name: 'Ostendplatz', x: 39.5, y: 30 },
    bergfriedhof: { name: 'Bergfriedhof', x: 39, y: 28 },
    'karl-olga-krankenhaus': { name: 'Karl-Olga-Krankenhaus', x: 38, y: 29.5 },
    'rosenberg-seidenstrasse': { name: 'Rosenberg-/Seidenstraße', x: 27, y: 33 },
    'russische-kirche': { name: 'Russische Kirche', x: 25.5, y: 31.5 },
    holderlinplatz: { name: 'Hölderlinplatz', x: 24.5, y: 33 },
    schlachthof: { name: 'Schlachthof', x: 42.5, y: 29.5 },
    raitelsberg: { name: 'Raitelsberg', x: 41.5, y: 28.5 },
    'vaihingen-schillerplatz': { name: 'Vaihingen Schillerplatz', x: 13, y: 54.5 },
    fauststrasse: { name: 'Fauststraße', x: 14.5, y: 53 },
    'vaihingen-viadukt': { name: 'Vaihingen Viadukt', x: 16.5, y: 53 },
    engelboldstrasse: { name: 'Engelboldstraße', x: 18, y: 51 },
    kaltental: { name: 'Kaltental', x: 19, y: 49.5 },
    waldeck: { name: 'Waldeck', x: 20.5, y: 48 },
    muhlsteg: { name: 'Mühlsteg', x: 42, y: 21 },
    'kraftwerk-munster': { name: 'Kraftwerk Münster', x: 42, y: 19 },
    'munster-viadukt': { name: 'Münster Viadukt', x: 43, y: 17.5 },
    'munster-rathaus': { name: 'Münster Rathaus', x: 44.5, y: 16 },
    freibergstrasse: { name: 'Freibergstraße', x: 43, y: 14.5 },
    elbestrasse: { name: 'Elbestraße', x: 41, y: 14.5 },
    wagrainacker: { name: 'Wagrainäcker', x: 40.5, y: 12.5 },
    'max-eyth-see': { name: 'Max-Eyth-See', x: 42, y: 11 },
    hofen: { name: 'Hofen', x: 43.5, y: 9.5 },
    auwiesen: { name: 'Auwiesen', x: 45, y: 7.5 },
    muhlhausen: { name: 'Mühlhausen', x: 46.5, y: 6 },
    'neckarpark-stadion': { name: 'NeckarPark (Stadion)', x: 43.5, y: 28 },
    'cannstatter-wasen': { name: 'Cannstatter Wasen', x: 42, y: 27 },
    durrlewang: { name: 'Dürrlewang', x: 14, y: 58.5 },
    'lapp-kabel': { name: 'Lapp Kabel', x: 15.5, y: 57 },
    'budapester-platz': { name: 'Budapester Platz', x: 33, y: 30 },
    milchhof: { name: 'Milchhof', x: 34.5, y: 28.5 },
    mittnachtstrasse: { name: 'Mittnachtstraße', x: 34.5, y: 26.5 },
    nordbahnhof: { name: 'Nordbahnhof', x: 34.5, y: 24 },
    'zuricher-strasse': { name: 'Züricher Straße', x: 36, y: 20.5 },
    riethmullerhaus: { name: 'Riethmüllerhaus', x: 38, y: 19 },
    hallschlag: { name: 'Hallschlag', x: 38, y: 16.5 },
    'bottroper-strasse': { name: 'Bottroper Straße', x: 40, y: 15 },
    'aldingen-hornbach': { name: 'Aldingen Hornbach', x: 48, y: 4.5 },
    'aldingen-muhle': { name: 'Aldingen Mühle', x: 49.5, y: 3 },
    'aldingen-bruckenstrasse': { name: 'Aldingen Brückenstraße', x: 51, y: 1.5 },
    'remseck-neckargroningen': { name: 'Remseck Neckargröningen', x: 52.5, y: 0 },
  },
};
