// The Hague's RandstadRail, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'the-hague',
  name: 'The Hague',
  system: 'RandstadRail',
  country: 'Netherlands',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '3',
      short: '3',
      name: 'Tram 3',
      colour: '#ad1380',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['arnold-spoelplein', 'pisuissestraat', 'mozartlaan', 'heliotrooplaan', 'muurbloemweg', 'hoefbladlaan', 'de-savornin-lohmanplein', 'appelstraat', 'zonnebloemstraat', 'azaleaplein', 'goudenregenstraat', 'fahrenheitstraat', 'valkenbosplein', 'conradkade', 'van-speijkstraat', 'elandstraat-west', 'hmc-westeinde', 'brouwersgracht', 'grote-markt', 'spui', 'centraal-station', 'beatrixkwartier', 'den-haag-laan-van-noi', 'voorburg-t-loo', 'leidschendam-voorburg', 'forepark', 'leidschenveen', 'voorweg-laag', 'centrum-west', 'stadhuis', 'palenstein', 'seghwaert', 'leidsewallen', 'de-leyens', 'buytenwegh', 'voorweg-hoog', 'meerzicht', 'driemanspolder', 'delftsewallen', 'dorp'],
        ['centrum-west', 'dorp', 'delftsewallen', 'driemanspolder', 'meerzicht', 'voorweg-hoog', 'buytenwegh', 'de-leyens', 'leidsewallen', 'seghwaert', 'palenstein', 'stadhuis'],
      ],
    },
    {
      id: '4',
      short: '4',
      name: 'Tram 4',
      colour: '#f18f00',
      text: '#1a1a1a',
      minutes: 1,
      branches: [
        ['lansingerland-zoetermeer', 'van-tuyllpark', 'javalaan', 'oosterheem', 'willem-dreeslaan', 'seghwaert', 'palenstein', 'stadhuis', 'centrum-west', 'voorweg-laag', 'leidschenveen', 'forepark', 'leidschendam-voorburg', 'voorburg-t-loo', 'den-haag-laan-van-noi', 'beatrixkwartier', 'centraal-station', 'spui', 'grote-markt', 'brouwersgracht', 'hmc-westeinde', 'monstersestraat', 'de-la-reyweg', 'dierenselaan', 'tienhovenselaan', 'monnickendamplein', 'leyenburg', 'zuidwoldepad', 'dedemsvaartweg', 'de-rade', 'bouwlustlaan', 'beresteinlaan', 'de-uithof'],
      ],
    },
    {
      id: '34',
      short: '34',
      name: 'Tram 34',
      colour: '#ec608a',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['lansingerland-zoetermeer', 'van-tuyllpark', 'javalaan', 'oosterheem', 'willem-dreeslaan', 'seghwaert', 'palenstein', 'stadhuis', 'centrum-west', 'voorweg-laag', 'leidschenveen', 'forepark', 'leidschendam-voorburg', 'voorburg-t-loo', 'den-haag-laan-van-noi', 'beatrixkwartier', 'centraal-station', 'spui', 'grote-markt', 'brouwersgracht', 'hmc-westeinde', 'elandstraat-west', 'van-speijkstraat', 'conradkade', 'valkenbosplein', 'fahrenheitstraat', 'goudenregenstraat', 'azaleaplein', 'zonnebloemstraat', 'appelstraat', 'de-savornin-lohmanplein'],
      ],
    },
    {
      id: 'e',
      short: 'E',
      name: 'Metro E',
      colour: '#1a389a',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['den-haag-centraal', 'den-haag-laan-van-noi', 'voorburg-t-loo', 'leidschendam-voorburg', 'forepark', 'leidschenveen', 'nootdorp', 'pijnacker-centrum', 'pijnacker-zuid', 'berkel-westpolder', 'rodenrijs', 'meijersplein-airport', 'melanchthonweg', 'blijdorp', 'rotterdam-centraal', 'stadhuis-2', 'beurs', 'leuvehaven', 'wilhelminaplein', 'rijnhaven', 'maashaven', 'zuidplein', 'slinge'],
      ],
    },
  ],
  times: {
    'arnold-spoelplein pisuissestraat': 1,
    'pisuissestraat mozartlaan': 1,
    'mozartlaan heliotrooplaan': 1,
    'heliotrooplaan muurbloemweg': 1,
    'muurbloemweg hoefbladlaan': 1,
    'hoefbladlaan de-savornin-lohmanplein': 1,
    'de-savornin-lohmanplein appelstraat': 1,
    'appelstraat zonnebloemstraat': 1,
    'zonnebloemstraat azaleaplein': 1,
    'azaleaplein goudenregenstraat': 1,
    'goudenregenstraat fahrenheitstraat': 1,
    'fahrenheitstraat valkenbosplein': 1,
    'valkenbosplein conradkade': 1,
    'conradkade van-speijkstraat': 1,
    'van-speijkstraat elandstraat-west': 1,
    'hmc-westeinde brouwersgracht': 1,
    'brouwersgracht grote-markt': 1,
    'grote-markt spui': 1,
    'beatrixkwartier den-haag-laan-van-noi': 1,
    'den-haag-laan-van-noi voorburg-t-loo': 3,
    'voorburg-t-loo leidschendam-voorburg': 3,
    'leidschenveen voorweg-laag': 10,
    'de-leyens buytenwegh': 3,
    'delftsewallen dorp': 1,
    'dorp delftsewallen': 1,
    'buytenwegh de-leyens': 3,
    'lansingerland-zoetermeer van-tuyllpark': 2,
    'van-tuyllpark javalaan': 2,
    'javalaan oosterheem': 2,
    'oosterheem willem-dreeslaan': 2,
    'willem-dreeslaan seghwaert': 3,
    'seghwaert palenstein': 2,
    'palenstein stadhuis': 2,
    'stadhuis centrum-west': 2,
    'centrum-west voorweg-laag': 2,
    'voorweg-laag leidschenveen': 10,
    'leidschenveen forepark': 2,
    'forepark leidschendam-voorburg': 2,
    'leidschendam-voorburg voorburg-t-loo': 3,
    'voorburg-t-loo den-haag-laan-van-noi': 3,
    'beatrixkwartier centraal-station': 2,
    'centraal-station spui': 2,
    'monnickendamplein leyenburg': 2,
    'den-haag-laan-van-noi beatrixkwartier': 1,
    'spui grote-markt': 1,
    'grote-markt brouwersgracht': 1,
    'brouwersgracht hmc-westeinde': 1,
    'elandstraat-west van-speijkstraat': 1,
    'van-speijkstraat conradkade': 1,
    'conradkade valkenbosplein': 1,
    'valkenbosplein fahrenheitstraat': 1,
    'fahrenheitstraat goudenregenstraat': 1,
    'goudenregenstraat azaleaplein': 1,
    'azaleaplein zonnebloemstraat': 1,
    'zonnebloemstraat appelstraat': 1,
    'appelstraat de-savornin-lohmanplein': 1,
    'den-haag-centraal den-haag-laan-van-noi': 3,
    'leidschenveen nootdorp': 4,
    'nootdorp pijnacker-centrum': 7,
    'pijnacker-centrum pijnacker-zuid': 4,
    'pijnacker-zuid berkel-westpolder': 4,
    'berkel-westpolder rodenrijs': 4,
    'rodenrijs meijersplein-airport': 5,
    'melanchthonweg blijdorp': 4,
    'stadhuis-2 beurs': 1,
    'beurs leuvehaven': 1,
    'wilhelminaplein rijnhaven': 1,
    'maashaven zuidplein': 3,
    'zuidplein slinge': 3,
  },
  stations: {
    'arnold-spoelplein': { name: 'Arnold Spoelplein', x: 1.5, y: 9.5 },
    pisuissestraat: { name: 'Pisuissestraat', x: 0, y: 8 },
    mozartlaan: { name: 'Mozartlaan', x: 2, y: 8 },
    heliotrooplaan: { name: 'Heliotrooplaan', x: 0.5, y: 6.5 },
    muurbloemweg: { name: 'Muurbloemweg', x: 2.5, y: 6.5 },
    hoefbladlaan: { name: 'Hoefbladlaan', x: 2.5, y: 4.5 },
    'de-savornin-lohmanplein': { name: 'De Savornin Lohmanplein', x: 5, y: 5 },
    appelstraat: { name: 'Appelstraat', x: 7, y: 5 },
    zonnebloemstraat: { name: 'Zonnebloemstraat', x: 7, y: 3 },
    azaleaplein: { name: 'Azaleaplein', x: 8.5, y: 1.5 },
    goudenregenstraat: { name: 'Goudenregenstraat', x: 10, y: 3 },
    fahrenheitstraat: { name: 'Fahrenheitstraat', x: 10, y: 1 },
    valkenbosplein: { name: 'Valkenbosplein', x: 12, y: 1.5 },
    conradkade: { name: 'Conradkade', x: 13.5, y: 0 },
    'van-speijkstraat': { name: 'Van Speijkstraat', x: 16, y: 0 },
    'elandstraat-west': { name: 'Elandstraat (West)', x: 17.5, y: 1.5 },
    'hmc-westeinde': { name: 'HMC Westeinde', x: 17.5, y: 4 },
    brouwersgracht: { name: 'Brouwersgracht', x: 20, y: 4 },
    'grote-markt': { name: 'Grote Markt', x: 22, y: 3 },
    spui: { name: 'Spui', x: 24.5, y: 3.5 },
    'centraal-station': { name: 'Centraal Station', x: 27.5, y: 4 },
    beatrixkwartier: { name: 'Beatrixkwartier', x: 30, y: 4.5 },
    'den-haag-laan-van-noi': { name: 'Den Haag Laan van NOI', x: 33, y: 4.5 },
    'voorburg-t-loo': { name: 'Voorburg \'t Loo', x: 35.5, y: 5.5 },
    'leidschendam-voorburg': { name: 'Leidschendam-Voorburg', x: 38, y: 7.5 },
    forepark: { name: 'Forepark', x: 40.5, y: 9.5 },
    leidschenveen: { name: 'Leidschenveen', x: 43, y: 11.5 },
    'voorweg-laag': { name: 'Voorweg Laag', x: 45.5, y: 10.5 },
    'centrum-west': { name: 'Centrum-West', x: 48, y: 9.5 },
    stadhuis: { name: 'Stadhuis', x: 51, y: 9 },
    palenstein: { name: 'Palenstein', x: 53, y: 8.5 },
    seghwaert: { name: 'Seghwaert', x: 55.5, y: 8.5 },
    leidsewallen: { name: 'Leidsewallen', x: 54.5, y: 7 },
    'de-leyens': { name: 'De Leyens', x: 52.5, y: 7 },
    buytenwegh: { name: 'Buytenwegh', x: 50.5, y: 7 },
    'voorweg-hoog': { name: 'Voorweg Hoog', x: 49, y: 8.5 },
    meerzicht: { name: 'Meerzicht', x: 49, y: 10.5 },
    driemanspolder: { name: 'Driemanspolder', x: 50, y: 12 },
    delftsewallen: { name: 'Delftsewallen', x: 52, y: 11.5 },
    dorp: { name: 'Dorp', x: 50.5, y: 10 },
    'lansingerland-zoetermeer': { name: 'Lansingerland-Zoetermeer', x: 57, y: 14.5 },
    'van-tuyllpark': { name: 'Van Tuyllpark', x: 58.5, y: 13 },
    javalaan: { name: 'Javalaan', x: 59.5, y: 11.5 },
    oosterheem: { name: 'Oosterheem', x: 59.5, y: 9.5 },
    'willem-dreeslaan': { name: 'Willem Dreeslaan', x: 58, y: 8.5 },
    monstersestraat: { name: 'Monstersestraat', x: 16, y: 2.5 },
    'de-la-reyweg': { name: 'De la Reyweg', x: 14.5, y: 3.5 },
    dierenselaan: { name: 'Dierenselaan', x: 14, y: 5.5 },
    tienhovenselaan: { name: 'Tienhovenselaan', x: 12, y: 5.5 },
    monnickendamplein: { name: 'Monnickendamplein', x: 10.5, y: 7 },
    leyenburg: { name: 'Leyenburg', x: 9, y: 8 },
    zuidwoldepad: { name: 'Zuidwoldepad', x: 10.5, y: 9.5 },
    dedemsvaartweg: { name: 'Dedemsvaartweg', x: 9, y: 11 },
    'de-rade': { name: 'De Rade', x: 7, y: 11 },
    bouwlustlaan: { name: 'Bouwlustlaan', x: 7, y: 13 },
    beresteinlaan: { name: 'Beresteinlaan', x: 5, y: 13 },
    'de-uithof': { name: 'De Uithof', x: 3.5, y: 14 },
    'den-haag-centraal': { name: 'Den Haag Centraal', x: 31.5, y: 3.5 },
    nootdorp: { name: 'Nootdorp', x: 43.5, y: 15 },
    'pijnacker-centrum': { name: 'Pijnacker Centrum', x: 44, y: 18.5 },
    'pijnacker-zuid': { name: 'Pijnacker Zuid', x: 44.5, y: 21.5 },
    'berkel-westpolder': { name: 'Berkel Westpolder', x: 45, y: 25 },
    rodenrijs: { name: 'Rodenrijs', x: 45.5, y: 28.5 },
    'meijersplein-airport': { name: 'Meijersplein / Airport', x: 46, y: 31.5 },
    melanchthonweg: { name: 'Melanchthonweg', x: 46, y: 35 },
    blijdorp: { name: 'Blijdorp', x: 46.5, y: 38 },
    'rotterdam-centraal': { name: 'Rotterdam Centraal', x: 47, y: 41 },
    'stadhuis-2': { name: 'Stadhuis', x: 48.5, y: 43 },
    beurs: { name: 'Beurs', x: 50, y: 45 },
    leuvehaven: { name: 'Leuvehaven', x: 50.5, y: 47.5 },
    wilhelminaplein: { name: 'Wilhelminaplein', x: 52, y: 49.5 },
    rijnhaven: { name: 'Rijnhaven', x: 52, y: 52 },
    maashaven: { name: 'Maashaven', x: 52, y: 54.5 },
    zuidplein: { name: 'Zuidplein', x: 52.5, y: 56.5 },
    slinge: { name: 'Slinge', x: 51, y: 58 },
  },
};
