// Toronto's subway and light rail, run by the TTC: Lines 1, 2, 4, 5 and 6.
//
// Places are squares on a topological grid, not points on the ground. Line 3
// closed in 2023; Line 6 Finch West opened in December 2025 and Line 5 Eglinton
// in February 2026.
export default {
  id: 'toronto',
  name: 'Toronto',
  system: 'TTC Subway',
  country: 'Canada',
  change: 4,
  lines: [
    {
      id: '1',
      short: '1',
      name: 'Line 1 Yonge–University',
      colour: '#F8C300',
      text: '#1a1a1a',
      minutes: 2,
      branches: [[
        'vaughan-metropolitan-centre', 'highway-407', 'pioneer-village', 'york-university', 'finch-west',
        'downsview-park', 'sheppard-west', 'wilson', 'yorkdale', 'lawrence-west', 'glencairn', 'cedarvale',
        'st-clair-west', 'dupont', 'spadina', 'st-george', 'museum', 'queens-park', 'st-patrick', 'osgoode',
        'st-andrew', 'union', 'king', 'queen', 'tmu', 'college', 'wellesley', 'bloor-yonge', 'rosedale',
        'summerhill', 'st-clair', 'davisville', 'eglinton', 'lawrence', 'york-mills', 'sheppard-yonge',
        'north-york-centre', 'finch',
      ]],
    },
    {
      id: '2',
      short: '2',
      name: 'Line 2 Bloor–Danforth',
      colour: '#00923F',
      minutes: 2,
      branches: [[
        'kipling', 'islington', 'royal-york', 'old-mill', 'jane', 'runnymede', 'high-park', 'keele',
        'dundas-west', 'lansdowne', 'dufferin', 'ossington', 'christie', 'bathurst', 'spadina', 'st-george',
        'bay', 'bloor-yonge', 'sherbourne', 'castle-frank', 'broadview', 'chester', 'pape', 'donlands',
        'greenwood', 'coxwell', 'woodbine', 'main-street', 'victoria-park', 'warden', 'kennedy',
      ]],
    },
    {
      id: '4',
      short: '4',
      name: 'Line 4 Sheppard',
      colour: '#A8518A',
      minutes: 2,
      branches: [['sheppard-yonge', 'bayview', 'bessarion', 'leslie', 'don-mills']],
    },
    {
      id: '5',
      short: '5',
      name: 'Line 5 Eglinton',
      colour: '#F37021',
      minutes: 2,
      branches: [[
        'mount-dennis', 'keelesdale', 'caledonia', 'fairbank', 'oakwood', 'cedarvale', 'forest-hill', 'chaplin',
        'avenue', 'eglinton', 'mount-pleasant', 'leaside', 'laird', 'sunnybrook-park', 'don-valley',
        'aga-khan-park-museum', 'wynford', 'sloane', 'oconnor', 'pharmacy', 'hakimi-lebovic', 'golden-mile',
        'birchmount', 'ionview', 'kennedy',
      ]],
    },
    {
      id: '6',
      short: '6',
      name: 'Line 6 Finch West',
      colour: '#959595',
      minutes: 2,
      branches: [[
        'finch-west', 'sentinel', 'tobermory', 'driftwood', 'jane-and-finch', 'norfinch-oakdale', 'signet-arrow',
        'emery', 'milvan-rumike', 'duncanwoods', 'pearldale', 'rowntree-mills', 'mount-olive', 'stevenson', 'albion',
        'martin-grove', 'westmore', 'humber-college',
      ]],
    },
  ],
  times: {
    'vaughan-metropolitan-centre highway-407': 3,
    'highway-407 pioneer-village': 3,
    'york-university finch-west': 3,
    'sheppard-west wilson': 3,
    'york-mills sheppard-yonge': 3,
    'warden kennedy': 3,
    'sheppard-yonge bayview': 3,
    'leslie don-mills': 3,
  },
  stations: {
    'vaughan-metropolitan-centre': { name: 'Vaughan Metropolitan Centre', x: 18, y: -9 },
    'highway-407': { name: 'Highway 407', x: 20, y: -7 },
    'pioneer-village': { name: 'Pioneer Village', x: 22, y: -5 },
    'york-university': { name: 'York University', x: 24, y: -3 },
    'finch-west': { name: 'Finch West', x: 26, y: -1 },
    'downsview-park': { name: 'Downsview Park', x: 28, y: 1 },
    'sheppard-west': { name: 'Sheppard West', x: 28, y: 3 },
    wilson: { name: 'Wilson', x: 28, y: 5 },
    yorkdale: { name: 'Yorkdale', x: 28, y: 7 },
    'lawrence-west': { name: 'Lawrence West', x: 28, y: 9 },
    glencairn: { name: 'Glencairn', x: 28, y: 11 },
    cedarvale: { name: 'Cedarvale', x: 28, y: 13, aka: ['Eglinton West'] },
    'st-clair-west': { name: 'St Clair West', x: 28, y: 15 },
    dupont: { name: 'Dupont', x: 28, y: 17 },
    spadina: { name: 'Spadina', x: 28, y: 20, at: { 1: [28, 19] }, change: 6 },
    'st-george': { name: 'St George', x: 30, y: 20, at: { 1: [30, 19] }, change: 3 },
    museum: { name: 'Museum', x: 30, y: 22 },
    'queens-park': { name: 'Queen’s Park', x: 30, y: 24, aka: ["Queen's Park"] },
    'st-patrick': { name: 'St Patrick', x: 30, y: 26 },
    osgoode: { name: 'Osgoode', x: 30, y: 28 },
    'st-andrew': { name: 'St Andrew', x: 30, y: 30 },
    union: { name: 'Union', x: 32, y: 32 },
    king: { name: 'King', x: 34, y: 30 },
    queen: { name: 'Queen', x: 34, y: 28 },
    tmu: { name: 'TMU', x: 34, y: 26, aka: ['Dundas', 'Toronto Metropolitan University'] },
    college: { name: 'College', x: 34, y: 24 },
    wellesley: { name: 'Wellesley', x: 34, y: 22 },
    'bloor-yonge': { name: 'Bloor–Yonge', x: 34, y: 20 },
    rosedale: { name: 'Rosedale', x: 34, y: 18 },
    summerhill: { name: 'Summerhill', x: 34, y: 16 },
    'st-clair': { name: 'St Clair', x: 34, y: 14 },
    davisville: { name: 'Davisville', x: 34, y: 12 },
    eglinton: { name: 'Eglinton', x: 34, y: 10 },
    lawrence: { name: 'Lawrence', x: 34, y: 8 },
    'york-mills': { name: 'York Mills', x: 34, y: 6 },
    'sheppard-yonge': { name: 'Sheppard–Yonge', x: 34, y: 4 },
    'north-york-centre': { name: 'North York Centre', x: 34, y: 2 },
    finch: { name: 'Finch', x: 34, y: 0 },

    kipling: { name: 'Kipling', x: 0, y: 20 },
    islington: { name: 'Islington', x: 2, y: 20 },
    'royal-york': { name: 'Royal York', x: 4, y: 20 },
    'old-mill': { name: 'Old Mill', x: 6, y: 20 },
    jane: { name: 'Jane', x: 8, y: 20 },
    runnymede: { name: 'Runnymede', x: 10, y: 20 },
    'high-park': { name: 'High Park', x: 12, y: 20 },
    keele: { name: 'Keele', x: 14, y: 20 },
    'dundas-west': { name: 'Dundas West', x: 16, y: 20 },
    lansdowne: { name: 'Lansdowne', x: 18, y: 20 },
    dufferin: { name: 'Dufferin', x: 20, y: 20 },
    ossington: { name: 'Ossington', x: 22, y: 20 },
    christie: { name: 'Christie', x: 24, y: 20 },
    bathurst: { name: 'Bathurst', x: 26, y: 20 },
    bay: { name: 'Bay', x: 32, y: 20 },
    sherbourne: { name: 'Sherbourne', x: 36, y: 20 },
    'castle-frank': { name: 'Castle Frank', x: 38, y: 20 },
    broadview: { name: 'Broadview', x: 40, y: 20 },
    chester: { name: 'Chester', x: 42, y: 20 },
    pape: { name: 'Pape', x: 44, y: 20 },
    donlands: { name: 'Donlands', x: 46, y: 20 },
    greenwood: { name: 'Greenwood', x: 48, y: 20 },
    coxwell: { name: 'Coxwell', x: 50, y: 20 },
    woodbine: { name: 'Woodbine', x: 52, y: 20 },
    'main-street': { name: 'Main Street', x: 54, y: 20 },
    'victoria-park': { name: 'Victoria Park', x: 56, y: 20 },
    warden: { name: 'Warden', x: 58, y: 20 },
    kennedy: { name: 'Kennedy', x: 60, y: 20, at: { 5: [61, 19] } },

    bayview: { name: 'Bayview', x: 37, y: 4 },
    bessarion: { name: 'Bessarion', x: 40, y: 4 },
    leslie: { name: 'Leslie', x: 43, y: 4 },
    'don-mills': { name: 'Don Mills', x: 46, y: 4 },

    'mount-dennis': { name: 'Mount Dennis', x: 18, y: 13 },
    keelesdale: { name: 'Keelesdale', x: 20, y: 13 },
    caledonia: { name: 'Caledonia', x: 22, y: 13 },
    fairbank: { name: 'Fairbank', x: 24, y: 13 },
    oakwood: { name: 'Oakwood', x: 26, y: 13 },
    'forest-hill': { name: 'Forest Hill', x: 30, y: 11 },
    chaplin: { name: 'Chaplin', x: 31, y: 10 },
    avenue: { name: 'Avenue', x: 32.5, y: 10 },
    'mount-pleasant': { name: 'Mount Pleasant', x: 36, y: 10 },
    leaside: { name: 'Leaside', x: 38, y: 10 },
    laird: { name: 'Laird', x: 40, y: 10 },
    'sunnybrook-park': { name: 'Sunnybrook Park', x: 42, y: 10 },
    'don-valley': { name: 'Don Valley', x: 44, y: 10 },
    'aga-khan-park-museum': { name: 'Aga Khan Park & Museum', x: 46, y: 10 },
    wynford: { name: 'Wynford', x: 48, y: 10 },
    sloane: { name: 'Sloane', x: 50, y: 10 },
    oconnor: { name: 'O’Connor', x: 52, y: 10, aka: ["O'Connor"] },
    pharmacy: { name: 'Pharmacy', x: 53.5, y: 11.5 },
    'hakimi-lebovic': { name: 'Hakimi Lebovic', x: 55, y: 13 },
    'golden-mile': { name: 'Golden Mile', x: 56.5, y: 14.5 },
    birchmount: { name: 'Birchmount', x: 58, y: 16 },
    ionview: { name: 'Ionview', x: 59.5, y: 17.5 },

    sentinel: { name: 'Sentinel', x: 24.5, y: -1 },
    tobermory: { name: 'Tobermory', x: 23, y: -1 },
    driftwood: { name: 'Driftwood', x: 21.5, y: -1 },
    'jane-and-finch': { name: 'Jane and Finch', x: 20, y: -1 },
    'norfinch-oakdale': { name: 'Norfinch Oakdale', x: 18.5, y: -1 },
    'signet-arrow': { name: 'Signet Arrow', x: 17, y: -1 },
    emery: { name: 'Emery', x: 15.5, y: -1 },
    'milvan-rumike': { name: 'Milvan Rumike', x: 14, y: -1 },
    duncanwoods: { name: 'Duncanwoods', x: 12.5, y: -1 },
    pearldale: { name: 'Pearldale', x: 11, y: -1 },
    'rowntree-mills': { name: 'Rowntree Mills', x: 9.5, y: -1 },
    'mount-olive': { name: 'Mount Olive', x: 8, y: -1 },
    stevenson: { name: 'Stevenson', x: 6.5, y: -1 },
    albion: { name: 'Albion', x: 5, y: -1 },
    'martin-grove': { name: 'Martin Grove', x: 3.5, y: -1 },
    westmore: { name: 'Westmore', x: 2, y: -1 },
    'humber-college': { name: 'Humber College', x: 0.5, y: -1 },
  },
  features: [
    {
      kind: 'water',
      name: 'Lake Ontario',
      labelAt: [48, 36.6],
      points: [[-6, 34], [8, 34.6], [20, 33.8], [30, 34.8], [40, 34.2], [52, 34.8], [66, 34], [66, 39], [-6, 39]],
    },
    { kind: 'river', width: 0.45, points: [[9.2, -4], [8.8, -1], [7.6, 4], [7, 14], [6.6, 20], [7.4, 27], [6.8, 34.4]] },
    { kind: 'river', width: 0.45, points: [[43.4, 6], [43, 10], [40.4, 14], [39, 20], [38.4, 27], [37, 34.4]] },
    { kind: 'park', points: [[10.4, 21.6], [13.6, 21.6], [14.6, 23.6], [13.4, 25.8], [10.6, 25.8], [9.4, 23.6]] },
  ],
};
