// Utrecht's Tram, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'utrecht',
  name: 'Utrecht',
  system: 'Tram',
  country: 'Netherlands',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: '20',
      short: '20',
      name: 'Tram 20',
      colour: '#ff0010',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['p-r-science-park', 'wkz-pmc', 'umc-utrecht', 'heidelberglaan', 'padualaan', 'de-kromme-rijn', 'stadion-galgenwaard', 'station-vaartsche-rijn', 'cs-centrumzijde', 'cs-jaarbeursplein', 'graadt-van-roggenweg', 's-24-oktoberplein-zuid', 'winkelcentrum-kanaleneiland', 'vasco-da-gamalaan', 'kanaleneiland-zuid', 'p-r-westraven', 'zuilenstein', 'batau-noord', 'wijkersloot', 'nieuwegein-city', 'merwestein', 'fokkesteeg', 'wiersdijk', 'nieuwegein-zuid'],
      ],
    },
    {
      id: '21',
      short: '21',
      name: 'Tram 21',
      colour: '#ff0010',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['ijsselstein-zuid', 'binnenstad', 'achterveld', 'eiteren', 'clinckhoeff', 'hooghe-waerd', 'doorslag', 'sint-antonius-ziekenhuis', 'nieuwegein-city', 'wijkersloot', 'batau-noord', 'zuilenstein', 'p-r-westraven', 'kanaleneiland-zuid', 'vasco-da-gamalaan', 'winkelcentrum-kanaleneiland', 's-24-oktoberplein-zuid', 'graadt-van-roggenweg', 'cs-jaarbeursplein', 'cs-centrumzijde', 'station-vaartsche-rijn', 'stadion-galgenwaard', 'de-kromme-rijn', 'padualaan', 'heidelberglaan', 'umc-utrecht', 'wkz-pmc', 'p-r-science-park'],
        ['p-r-science-park', 'wkz-pmc', 'umc-utrecht', 'heidelberglaan', 'padualaan', 'de-kromme-rijn', 'stadion-galgenwaard', 'station-vaartsche-rijn', 'cs-centrumzijde', 'cs-jaarbeursplein', 'graadt-van-roggenweg', 's-24-oktoberplein-zuid', 'winkelcentrum-kanaleneiland', 'vasco-da-gamalaan', 'kanaleneiland-zuid', 'p-r-westraven', 'zuilenstein', 'wijkersloot', 'nieuwegein-city', 'sint-antonius-ziekenhuis', 'doorslag', 'hooghe-waerd', 'clinckhoeff', 'eiteren', 'achterveld', 'binnenstad', 'ijsselstein-zuid'],
      ],
    },
    {
      id: '22',
      short: '22',
      name: 'Tram 22',
      colour: '#ff0010',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['p-r-science-park', 'wkz-pmc', 'umc-utrecht', 'heidelberglaan', 'padualaan', 'de-kromme-rijn', 'stadion-galgenwaard', 'station-vaartsche-rijn', 'cs-centrumzijde'],
      ],
    },
  ],
  times: {
    'p-r-science-park wkz-pmc': 1,
    'wkz-pmc umc-utrecht': 1,
    'umc-utrecht heidelberglaan': 1,
    'heidelberglaan padualaan': 1,
    'stadion-galgenwaard station-vaartsche-rijn': 4,
    'station-vaartsche-rijn cs-centrumzijde': 3,
    'cs-centrumzijde cs-jaarbeursplein': 1,
    'cs-jaarbeursplein graadt-van-roggenweg': 1,
    'graadt-van-roggenweg s-24-oktoberplein-zuid': 3,
    's-24-oktoberplein-zuid winkelcentrum-kanaleneiland': 1,
    'p-r-westraven zuilenstein': 4,
    'nieuwegein-city merwestein': 1,
    'clinckhoeff hooghe-waerd': 1,
    'hooghe-waerd doorslag': 3,
    'sint-antonius-ziekenhuis nieuwegein-city': 1,
    'zuilenstein p-r-westraven': 4,
    'winkelcentrum-kanaleneiland s-24-oktoberplein-zuid': 1,
    's-24-oktoberplein-zuid graadt-van-roggenweg': 3,
    'graadt-van-roggenweg cs-jaarbeursplein': 1,
    'cs-jaarbeursplein cs-centrumzijde': 1,
    'cs-centrumzijde station-vaartsche-rijn': 3,
    'station-vaartsche-rijn stadion-galgenwaard': 4,
    'padualaan heidelberglaan': 1,
    'heidelberglaan umc-utrecht': 1,
    'umc-utrecht wkz-pmc': 1,
    'wkz-pmc p-r-science-park': 1,
    'zuilenstein wijkersloot': 3,
    'nieuwegein-city sint-antonius-ziekenhuis': 1,
    'doorslag hooghe-waerd': 3,
    'hooghe-waerd clinckhoeff': 1,
    'padualaan de-kromme-rijn': 2,
    'de-kromme-rijn stadion-galgenwaard': 2,
  },
  stations: {
    'p-r-science-park': { name: 'P+R Science Park', x: 25, y: 0.5 },
    'wkz-pmc': { name: 'WKZ/PMC', x: 27, y: 0.5 },
    'umc-utrecht': { name: 'UMC Utrecht', x: 27, y: 2.5 },
    heidelberglaan: { name: 'Heidelberglaan', x: 25, y: 2.5 },
    padualaan: { name: 'Padualaan', x: 23, y: 2.5 },
    'de-kromme-rijn': { name: 'De Kromme Rijn', x: 21, y: 2.5 },
    'stadion-galgenwaard': { name: 'Stadion Galgenwaard', x: 19, y: 2.5 },
    'station-vaartsche-rijn': { name: 'Station Vaartsche Rijn', x: 17, y: 2.5 },
    'cs-centrumzijde': { name: 'CS Centrumzijde', x: 15.5, y: 1.5 },
    'cs-jaarbeursplein': { name: 'CS Jaarbeursplein', x: 14, y: 0 },
    'graadt-van-roggenweg': { name: 'Graadt van Roggenweg', x: 12.5, y: 1.5 },
    's-24-oktoberplein-zuid': { name: '24 Oktoberplein-Zuid', x: 11, y: 3 },
    'winkelcentrum-kanaleneiland': { name: 'Winkelcentrum Kanaleneiland', x: 11, y: 5 },
    'vasco-da-gamalaan': { name: 'Vasco da Gamalaan', x: 12, y: 6.5 },
    'kanaleneiland-zuid': { name: 'Kanaleneiland-Zuid', x: 12, y: 9 },
    'p-r-westraven': { name: 'P+R Westraven', x: 12, y: 11 },
    zuilenstein: { name: 'Zuilenstein', x: 10.5, y: 12.5 },
    wijkersloot: { name: 'Wijkersloot', x: 9, y: 14 },
    'nieuwegein-city': { name: 'Nieuwegein City', x: 8.5, y: 16.5 },
    'sint-antonius-ziekenhuis': { name: 'Sint Antonius Ziekenhuis', x: 8.5, y: 18.5 },
    doorslag: { name: 'Doorslag', x: 7, y: 20 },
    'hooghe-waerd': { name: 'Hooghe Waerd', x: 5, y: 20 },
    clinckhoeff: { name: 'Clinckhoeff', x: 3.5, y: 18.5 },
    eiteren: { name: 'Eiteren', x: 1.5, y: 18.5 },
    achterveld: { name: 'Achterveld', x: 0, y: 20 },
    binnenstad: { name: 'Binnenstad', x: 1.5, y: 21.5 },
    'ijsselstein-zuid': { name: 'IJsselstein-Zuid', x: 1.5, y: 23.5 },
    'batau-noord': { name: 'Batau Noord', x: 8.5, y: 12.5 },
    merwestein: { name: 'Merwestein', x: 10, y: 17.5 },
    fokkesteeg: { name: 'Fokkesteeg', x: 10, y: 19.5 },
    wiersdijk: { name: 'Wiersdijk', x: 10, y: 22 },
    'nieuwegein-zuid': { name: 'Nieuwegein-Zuid', x: 10, y: 24 },
  },
};
