// Metro Vancouver's SkyTrain, run by TransLink: the Expo, Millennium and
// Canada Lines.
//
// Places are squares on a topological grid, not points on the ground. The
// Millennium Line's Broadway extension is left for when it opens.
export default {
  id: 'vancouver',
  name: 'Vancouver',
  system: 'SkyTrain',
  country: 'Canada',
  change: 4,
  lines: [
    {
      id: 'expo',
      name: 'Expo Line',
      colour: '#1A5BAA',
      minutes: 2,
      branches: [
        [
          'waterfront', 'burrard', 'granville', 'stadium-chinatown', 'main-street-science-world',
          'commercial-broadway', 'nanaimo', '29th-avenue', 'joyce-collingwood', 'patterson', 'metrotown',
          'royal-oak', 'edmonds', '22nd-street', 'new-westminster', 'columbia', 'scott-road', 'gateway',
          'surrey-central', 'king-george',
        ],
        [
          'waterfront', 'burrard', 'granville', 'stadium-chinatown', 'main-street-science-world',
          'commercial-broadway', 'nanaimo', '29th-avenue', 'joyce-collingwood', 'patterson', 'metrotown',
          'royal-oak', 'edmonds', '22nd-street', 'new-westminster', 'columbia', 'sapperton', 'braid',
          'lougheed-town-centre', 'production-way-university',
        ],
      ],
    },
    {
      id: 'millennium',
      name: 'Millennium Line',
      colour: '#F2B80C',
      text: '#1a1a1a',
      minutes: 2,
      branches: [[
        'vcc-clark', 'commercial-broadway', 'renfrew', 'rupert', 'gilmore', 'brentwood-town-centre', 'holdom',
        'sperling-burnaby-lake', 'lake-city-way', 'production-way-university', 'lougheed-town-centre',
        'burquitlam', 'moody-centre', 'inlet-centre', 'coquitlam-central', 'lincoln', 'lafarge-lake-douglas',
      ]],
      via: { 'lake-city-way production-way-university': [[45, 4], [48, 7]] },
    },
    {
      id: 'canada',
      name: 'Canada Line',
      colour: '#0098C9',
      minutes: 2,
      branches: [
        [
          'waterfront', 'vancouver-city-centre', 'yaletown-roundhouse', 'olympic-village', 'broadway-city-hall',
          'king-edward', 'oakridge-41st-avenue', 'langara-49th-avenue', 'marine-drive', 'bridgeport', 'capstan',
          'aberdeen', 'lansdowne', 'richmond-brighouse',
        ],
        [
          'waterfront', 'vancouver-city-centre', 'yaletown-roundhouse', 'olympic-village', 'broadway-city-hall',
          'king-edward', 'oakridge-41st-avenue', 'langara-49th-avenue', 'marine-drive', 'bridgeport', 'templeton',
          'sea-island-centre', 'yvr-airport',
        ],
      ],
    },
  ],
  times: {
    'columbia scott-road': 3,
    'production-way-university lougheed-town-centre': 3,
    'lougheed-town-centre burquitlam': 3,
    'burquitlam moody-centre': 3,
    'marine-drive bridgeport': 3,
  },
  stations: {
    waterfront: { name: 'Waterfront', x: 15, y: 0, change: 3 },
    burrard: { name: 'Burrard', x: 11, y: 0 },
    granville: { name: 'Granville', x: 11, y: 3 },
    'stadium-chinatown': { name: 'Stadium–Chinatown', x: 14, y: 6 },
    'main-street-science-world': { name: 'Main Street–Science World', x: 20, y: 6 },
    'commercial-broadway': { name: 'Commercial–Broadway', x: 24, y: 10 },
    nanaimo: { name: 'Nanaimo', x: 26, y: 12 },
    '29th-avenue': { name: '29th Avenue', x: 28, y: 14 },
    'joyce-collingwood': { name: 'Joyce–Collingwood', x: 30, y: 16 },
    patterson: { name: 'Patterson', x: 32, y: 18 },
    metrotown: { name: 'Metrotown', x: 34, y: 20 },
    'royal-oak': { name: 'Royal Oak', x: 37, y: 20 },
    edmonds: { name: 'Edmonds', x: 40, y: 20 },
    '22nd-street': { name: '22nd Street', x: 43, y: 20 },
    'new-westminster': { name: 'New Westminster', x: 46, y: 20 },
    columbia: { name: 'Columbia', x: 49, y: 20 },
    'scott-road': { name: 'Scott Road', x: 51, y: 22 },
    gateway: { name: 'Gateway', x: 51, y: 25 },
    'surrey-central': { name: 'Surrey Central', x: 51, y: 28 },
    'king-george': { name: 'King George', x: 51, y: 31 },
    sapperton: { name: 'Sapperton', x: 51, y: 18 },
    braid: { name: 'Braid', x: 51, y: 15 },
    'lougheed-town-centre': { name: 'Lougheed Town Centre', x: 51, y: 12, at: { expo: [51, 13] } },
    'production-way-university': { name: 'Production Way–University', x: 48, y: 12, at: { expo: [48, 13] } },

    'vcc-clark': { name: 'VCC–Clark', x: 20, y: 10 },
    renfrew: { name: 'Renfrew', x: 26, y: 8 },
    rupert: { name: 'Rupert', x: 28, y: 6 },
    gilmore: { name: 'Gilmore', x: 30, y: 4 },
    'brentwood-town-centre': { name: 'Brentwood Town Centre', x: 33, y: 4 },
    holdom: { name: 'Holdom', x: 36, y: 4 },
    'sperling-burnaby-lake': { name: 'Sperling–Burnaby Lake', x: 39, y: 4 },
    'lake-city-way': { name: 'Lake City Way', x: 42, y: 4 },
    burquitlam: { name: 'Burquitlam', x: 54, y: 9 },
    'moody-centre': { name: 'Moody Centre', x: 57, y: 6 },
    'inlet-centre': { name: 'Inlet Centre', x: 60, y: 6 },
    'coquitlam-central': { name: 'Coquitlam Central', x: 63, y: 6 },
    lincoln: { name: 'Lincoln', x: 65, y: 4 },
    'lafarge-lake-douglas': { name: 'Lafarge Lake–Douglas', x: 67, y: 2 },

    'vancouver-city-centre': { name: 'Vancouver City Centre', x: 17, y: 2 },
    'yaletown-roundhouse': { name: 'Yaletown–Roundhouse', x: 17, y: 4 },
    'olympic-village': { name: 'Olympic Village', x: 17, y: 8 },
    'broadway-city-hall': { name: 'Broadway–City Hall', x: 17, y: 10 },
    'king-edward': { name: 'King Edward', x: 17, y: 12 },
    'oakridge-41st-avenue': { name: 'Oakridge–41st Avenue', x: 17, y: 14 },
    'langara-49th-avenue': { name: 'Langara–49th Avenue', x: 17, y: 16 },
    'marine-drive': { name: 'Marine Drive', x: 17, y: 18 },
    bridgeport: { name: 'Bridgeport', x: 17, y: 22 },
    capstan: { name: 'Capstan', x: 17, y: 24 },
    aberdeen: { name: 'Aberdeen', x: 17, y: 26 },
    lansdowne: { name: 'Lansdowne', x: 17, y: 28 },
    'richmond-brighouse': { name: 'Richmond–Brighouse', x: 17, y: 30 },
    templeton: { name: 'Templeton', x: 15, y: 24 },
    'sea-island-centre': { name: 'Sea Island Centre', x: 13, y: 26 },
    'yvr-airport': { name: 'YVR–Airport', x: 11, y: 28, aka: ['Vancouver Airport'] },
  },
  features: [
    {
      kind: 'water',
      name: 'Burrard Inlet',
      labelAt: [34, -2.4],
      points: [[-4, -5], [70, -5], [70, -1.6], [62, -1.2], [61, 2.6], [58.6, 4.3], [55.6, 3.4], [52, 1.4], [40, 1.6], [28, 1.2], [22, -0.9], [16, -1.2], [8, -1.4], [-4, -1.2]],
    },
    { kind: 'water', points: [[5, 6.8], [19.4, 6.8], [19.6, 7.6], [5, 7.6]] },
    { kind: 'river', name: 'Fraser River', labelAt: [37, 25.6], width: 1.1, points: [[-4, 20], [24, 20], [29, 23.6], [45, 23.8], [49.8, 21.2], [53, 21], [72, 21]] },
    { kind: 'river', width: 0.6, points: [[16.8, 20.2], [16.2, 23], [16.1, 27], [15.2, 32]] },
    { kind: 'park', points: [[4.4, -0.8], [8.6, -1], [9.4, 0.6], [8.2, 2.2], [5.4, 2], [4, 0.6]] },
  ],
};
