// Vienna's U-Bahn, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'vienna',
  name: 'Vienna',
  system: 'U-Bahn',
  country: 'Austria',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'u1',
      short: 'U1',
      name: 'U1 Oberlaa <',
      colour: '#e3000f',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['oberlaa', 'neulaa', 'alaudagasse', 'altes-landgut', 'troststrasse', 'reumannplatz', 'keplerplatz', 'sudtiroler-platz-hauptbahnhof', 'taubstummengasse', 'karlsplatz', 'stephansplatz', 'schwedenplatz', 'nestroyplatz', 'praterstern', 'vorgartenstrasse', 'donauinsel', 'kaisermuhlen-vic', 'alte-donau', 'kagran', 'kagraner-platz', 'rennbahnweg', 'aderklaaer-strasse', 'grossfeldsiedlung', 'leopoldau'],
      ],
    },
    {
      id: 'u2',
      short: 'U2',
      name: 'U2 Seestadt <',
      colour: '#a862a4',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['karlsplatz', 'museumsquartier', 'volkstheater', 'rathaus', 'schottentor', 'schottenring', 'taborstrasse', 'praterstern', 'messe-prater', 'krieau', 'stadion', 'donaumarina', 'donaustadtbrucke', 'stadlau', 'hardeggasse', 'donauspital', 'aspernstrasse', 'lina-loos-platz', 'hausfeldstrasse', 'aspern-nord', 'seestadt'],
      ],
    },
    {
      id: 'u3',
      short: 'U3',
      name: 'U3 Ottakring <',
      colour: '#ef7c00',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['ottakring', 'kendlerstrasse', 'hutteldorfer-strasse', 'johnstrasse', 'schweglerstrasse', 'westbahnhof', 'zieglergasse', 'neubaugasse', 'volkstheater', 'herrengasse', 'stephansplatz', 'stubentor', 'landstrasse', 'rochusgasse', 'kardinal-nagl-platz', 'schlachthausgasse', 'erdberg', 'gasometer', 'zippererstrasse', 'enkplatz', 'simmering'],
      ],
    },
    {
      id: 'u4',
      short: 'U4',
      name: 'U4 Hütteldorf <',
      colour: '#319f49',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['hutteldorf', 'ober-st-veit', 'unter-st-veit', 'braunschweiggasse', 'hietzing', 'schonbrunn', 'meidling-hauptstrasse', 'langenfeldgasse', 'margaretengurtel', 'pilgramgasse', 'kettenbruckengasse', 'karlsplatz', 'stadtpark', 'landstrasse', 'schwedenplatz', 'schottenring', 'rossauer-lande', 'friedensbrucke', 'spittelau', 'heiligenstadt'],
      ],
    },
    {
      id: 'u6',
      short: 'U6',
      name: 'U6 Siebenhirten <',
      colour: '#9d6830',
      text: '#ffffff',
      minutes: 2,
      branches: [
        ['siebenhirten', 'perfektastrasse', 'erlaaer-strasse', 'alterlaa', 'am-schopfwerk', 'tscherttegasse', 'bahnhof-meidling', 'niederhofstrasse', 'langenfeldgasse', 'gumpendorfer-strasse', 'westbahnhof', 'burggasse-stadthalle', 'thaliastrasse', 'josefstadter-strasse', 'alser-strasse', 'michelbeuern-akh', 'wahringer-strasse-volksoper', 'nussdorfer-strasse', 'spittelau', 'jagerstrasse', 'dresdner-strasse', 'handelskai', 'neue-donau', 'floridsdorf'],
      ],
    },
  ],
  times: {
    'oberlaa neulaa': 3,
    'reumannplatz keplerplatz': 1,
    'donauinsel kaisermuhlen-vic': 1,
    'kagran kagraner-platz': 3,
    'museumsquartier volkstheater': 1,
    'donaustadtbrucke stadlau': 3,
    'hausfeldstrasse aspern-nord': 3,
    'kendlerstrasse hutteldorfer-strasse': 1,
    'westbahnhof zieglergasse': 1,
    'zieglergasse neubaugasse': 1,
    'herrengasse stephansplatz': 1,
    'stephansplatz stubentor': 1,
    'stubentor landstrasse': 1,
    'hutteldorf ober-st-veit': 3,
    'meidling-hauptstrasse langenfeldgasse': 1,
    'pilgramgasse kettenbruckengasse': 1,
    'stadtpark landstrasse': 1,
    'spittelau heiligenstadt': 3,
    'alterlaa am-schopfwerk': 3,
    'am-schopfwerk tscherttegasse': 1,
    'niederhofstrasse langenfeldgasse': 1,
    'burggasse-stadthalle thaliastrasse': 1,
    'thaliastrasse josefstadter-strasse': 1,
    'alser-strasse michelbeuern-akh': 1,
    'neue-donau floridsdorf': 3,
  },
  stations: {
    ottakring: { name: 'Ottakring', x: 7.5, y: 19.5 },
    kendlerstrasse: { name: 'Kendlerstraße', x: 7.5, y: 21.5 },
    'hutteldorfer-strasse': { name: 'Hütteldorfer Straße', x: 7.5, y: 23.5 },
    johnstrasse: { name: 'Johnstraße', x: 9.5, y: 23.5 },
    schweglerstrasse: { name: 'Schweglerstraße', x: 11.5, y: 23.5 },
    westbahnhof: { name: 'Westbahnhof', x: 13.5, y: 23.5 },
    zieglergasse: { name: 'Zieglergasse', x: 15.5, y: 23.5 },
    neubaugasse: { name: 'Neubaugasse', x: 17, y: 22 },
    volkstheater: { name: 'Volkstheater', x: 17, y: 20 },
    herrengasse: { name: 'Herrengasse', x: 18.5, y: 18.5 },
    stephansplatz: { name: 'Stephansplatz', x: 20, y: 20 },
    stubentor: { name: 'Stubentor', x: 22, y: 20 },
    landstrasse: { name: 'Landstraße', x: 23.5, y: 20 },
    rochusgasse: { name: 'Rochusgasse', x: 25, y: 21.5 },
    'kardinal-nagl-platz': { name: 'Kardinal-Nagl-Platz', x: 26.5, y: 23 },
    schlachthausgasse: { name: 'Schlachthausgasse', x: 28, y: 24 },
    erdberg: { name: 'Erdberg', x: 29.5, y: 25.5 },
    gasometer: { name: 'Gasometer', x: 29.5, y: 27.5 },
    zippererstrasse: { name: 'Zippererstraße', x: 28, y: 29 },
    enkplatz: { name: 'Enkplatz', x: 28, y: 31 },
    simmering: { name: 'Simmering', x: 29.5, y: 32.5 },
    oberlaa: { name: 'Oberlaa', x: 22.5, y: 39.5 },
    neulaa: { name: 'Neulaa', x: 21, y: 38 },
    alaudagasse: { name: 'Alaudagasse', x: 21, y: 36 },
    'altes-landgut': { name: 'Altes Landgut', x: 21, y: 34 },
    troststrasse: { name: 'Troststraße', x: 21, y: 32 },
    reumannplatz: { name: 'Reumannplatz', x: 20.5, y: 30 },
    keplerplatz: { name: 'Keplerplatz', x: 20.5, y: 28 },
    'sudtiroler-platz-hauptbahnhof': { name: 'Südtiroler Platz-Hauptbahnhof', x: 20.5, y: 26, aka: ['Südtiroler Platz-Hauptbahnhof'] },
    taubstummengasse: { name: 'Taubstummengasse', x: 20.5, y: 24 },
    karlsplatz: { name: 'Karlsplatz', x: 20, y: 21.5 },
    schwedenplatz: { name: 'Schwedenplatz', x: 22, y: 18.5 },
    nestroyplatz: { name: 'Nestroyplatz', x: 23.5, y: 17.5 },
    praterstern: { name: 'Praterstern', x: 25, y: 16.5 },
    vorgartenstrasse: { name: 'Vorgartenstraße', x: 26.5, y: 15 },
    donauinsel: { name: 'Donauinsel', x: 28, y: 13.5 },
    'kaisermuhlen-vic': { name: 'Kaisermühlen-VIC', x: 29.5, y: 12 },
    'alte-donau': { name: 'Alte Donau', x: 31, y: 10.5 },
    kagran: { name: 'Kagran', x: 32.5, y: 9 },
    'kagraner-platz': { name: 'Kagraner Platz', x: 34, y: 7.5 },
    rennbahnweg: { name: 'Rennbahnweg', x: 35, y: 6 },
    'aderklaaer-strasse': { name: 'Aderklaaer Straße', x: 35.5, y: 4 },
    grossfeldsiedlung: { name: 'Großfeldsiedlung', x: 35.5, y: 2 },
    leopoldau: { name: 'Leopoldau', x: 35.5, y: 0 },
    museumsquartier: { name: 'Museumsquartier', x: 18.5, y: 21.5 },
    rathaus: { name: 'Rathaus', x: 17, y: 18 },
    schottentor: { name: 'Schottentor', x: 18.5, y: 17 },
    schottenring: { name: 'Schottenring', x: 20.5, y: 17 },
    taborstrasse: { name: 'Taborstraße', x: 22.5, y: 16.5 },
    'messe-prater': { name: 'Messe-Prater', x: 27, y: 16.5 },
    krieau: { name: 'Krieau', x: 28.5, y: 18 },
    stadion: { name: 'Stadion', x: 30, y: 19.5 },
    donaumarina: { name: 'Donaumarina', x: 32, y: 19.5 },
    donaustadtbrucke: { name: 'Donaustadtbrücke', x: 33.5, y: 18 },
    stadlau: { name: 'Stadlau', x: 35, y: 17 },
    hardeggasse: { name: 'Hardeggasse', x: 36.5, y: 15.5 },
    donauspital: { name: 'Donauspital', x: 39, y: 15.5 },
    aspernstrasse: { name: 'Aspernstraße', x: 40.5, y: 14 },
    'lina-loos-platz': { name: 'Lina-Loos-Platz', x: 41.5, y: 13 },
    hausfeldstrasse: { name: 'Hausfeldstraße', x: 43, y: 11.5 },
    'aspern-nord': { name: 'Aspern Nord', x: 45, y: 11.5 },
    seestadt: { name: 'Seestadt', x: 46.5, y: 13 },
    hutteldorf: { name: 'Hütteldorf', x: 0, y: 25.5 },
    'ober-st-veit': { name: 'Ober St. Veit', x: 1.5, y: 27, aka: ['Ober St. Veit'] },
    'unter-st-veit': { name: 'Unter St. Veit', x: 3.5, y: 27 },
    braunschweiggasse: { name: 'Braunschweiggasse', x: 5.5, y: 27 },
    hietzing: { name: 'Hietzing', x: 7.5, y: 27 },
    schonbrunn: { name: 'Schönbrunn', x: 9.5, y: 27 },
    'meidling-hauptstrasse': { name: 'Meidling Hauptstraße', x: 11.5, y: 27.5 },
    langenfeldgasse: { name: 'Längenfeldgasse', x: 14, y: 27.5 },
    margaretengurtel: { name: 'Margaretengürtel', x: 15.5, y: 26 },
    pilgramgasse: { name: 'Pilgramgasse', x: 17, y: 24.5 },
    kettenbruckengasse: { name: 'Kettenbrückengasse', x: 18.5, y: 23 },
    stadtpark: { name: 'Stadtpark', x: 22.5, y: 21.5 },
    'rossauer-lande': { name: 'Roßauer Lände', x: 19, y: 15 },
    friedensbrucke: { name: 'Friedensbrücke', x: 19, y: 13 },
    spittelau: { name: 'Spittelau', x: 18.5, y: 11 },
    heiligenstadt: { name: 'Heiligenstadt', x: 18.5, y: 9 },
    siebenhirten: { name: 'Siebenhirten', x: 10.5, y: 42.5 },
    perfektastrasse: { name: 'Perfektastraße', x: 10.5, y: 40.5 },
    'erlaaer-strasse': { name: 'Erlaaer Straße', x: 10.5, y: 38.5 },
    alterlaa: { name: 'Alterlaa', x: 10.5, y: 36.5 },
    'am-schopfwerk': { name: 'Am Schöpfwerk', x: 10.5, y: 34.5 },
    tscherttegasse: { name: 'Tscherttegasse', x: 12, y: 33 },
    'bahnhof-meidling': { name: 'Bahnhof Meidling', x: 12, y: 31 },
    niederhofstrasse: { name: 'Niederhofstraße', x: 12.5, y: 29 },
    'gumpendorfer-strasse': { name: 'Gumpendorfer Straße', x: 13.5, y: 25.5 },
    'burggasse-stadthalle': { name: 'Burggasse-Stadthalle', x: 14, y: 21.5 },
    thaliastrasse: { name: 'Thaliastraße', x: 15.5, y: 20.5 },
    'josefstadter-strasse': { name: 'Josefstädter Straße', x: 14, y: 19 },
    'alser-strasse': { name: 'Alser Straße', x: 15.5, y: 17.5 },
    'michelbeuern-akh': { name: 'Michelbeuern-AKH', x: 15.5, y: 15.5 },
    'wahringer-strasse-volksoper': { name: 'Währinger Straße-Volksoper', x: 17, y: 14.5 },
    'nussdorfer-strasse': { name: 'Nußdorfer Straße', x: 17, y: 12.5 },
    jagerstrasse: { name: 'Jägerstraße', x: 20.5, y: 11 },
    'dresdner-strasse': { name: 'Dresdner Straße', x: 22.5, y: 11 },
    handelskai: { name: 'Handelskai', x: 24, y: 9.5 },
    'neue-donau': { name: 'Neue Donau', x: 25.5, y: 8 },
    floridsdorf: { name: 'Floridsdorf', x: 27, y: 7 },
  },
};
