// Zaragoza's Tranvía, from OpenStreetMap (© OpenStreetMap contributors,
// available under the Open Database Licence) on 2026-09-14.
//
// Stations are laid out by scripts/metro-import.mjs from where they really are,
// with the spacing evened out, so the map keeps the city's shape without its
// distances. Travel times are estimated from those distances.
export default {
  id: 'zaragoza',
  name: 'Zaragoza',
  system: 'Tranvía',
  country: 'Spain',
  change: 4,
  credit: '© OpenStreetMap contributors',
  lines: [
    {
      id: 'l1',
      short: 'L1',
      name: 'Tram L1',
      colour: '#e52422',
      text: '#ffffff',
      minutes: 1,
      branches: [
        ['mago-de-oz', 'un-americano-en-paris', 'la-ventana-indiscreta', 'los-olvidados', 'argualas', 'casablanca', 'romareda', 'emperador-carlos-v', 'plaza-de-san-francisco', 'fernando-el-catolico', 'gran-via', 'plaza-aragon', 'plaza-de-espana', 'cesar-augusto', 'plaza-del-pilar-murallas', 'la-chimenea', 'maria-montessori', 'leon-felipe', 'pablo-neruda', 'adolfo-aznar', 'garcia-abril', 'campus-rio-ebro', 'juslibol', 'parque-goya', 'avenida-de-la-academia'],
        ['avenida-de-la-academia', 'parque-goya', 'juslibol', 'campus-rio-ebro', 'margarita-xirgu', 'legaz-lacambra', 'clara-campoamor', 'rosalia-de-castro', 'martinez-soria', 'la-chimenea', 'plaza-del-pilar-murallas', 'cesar-augusto', 'plaza-de-espana', 'plaza-aragon', 'gran-via', 'fernando-el-catolico', 'plaza-de-san-francisco', 'emperador-carlos-v', 'romareda', 'casablanca', 'argualas', 'los-olvidados', 'los-pajaros', 'cantando-bajo-la-lluvia', 'mago-de-oz'],
      ],
    },
  ],
  times: {
    'los-olvidados argualas': 2,
    'argualas casablanca': 2,
    'casablanca romareda': 2,
    'pablo-neruda adolfo-aznar': 2,
    'garcia-abril campus-rio-ebro': 2,
    'parque-goya avenida-de-la-academia': 2,
    'avenida-de-la-academia parque-goya': 2,
    'campus-rio-ebro margarita-xirgu': 2,
    'romareda casablanca': 2,
    'casablanca argualas': 2,
    'argualas los-olvidados': 2,
    'los-pajaros cantando-bajo-la-lluvia': 2,
  },
  stations: {
    'mago-de-oz': { name: 'Mago de Oz', x: 0, y: 28.5 },
    'un-americano-en-paris': { name: 'Un americano en París', x: 1.5, y: 30 },
    'la-ventana-indiscreta': { name: 'La ventana indiscreta', x: 4, y: 30 },
    'los-olvidados': { name: 'Los olvidados', x: 5.5, y: 28.5 },
    argualas: { name: 'Argualas', x: 7, y: 27 },
    casablanca: { name: 'Casablanca', x: 8.5, y: 25.5 },
    romareda: { name: 'Romareda', x: 10, y: 24 },
    'emperador-carlos-v': { name: 'Emperador Carlos V', x: 11.5, y: 22.5 },
    'plaza-de-san-francisco': { name: 'Plaza de San Francisco', x: 13, y: 21.5 },
    'fernando-el-catolico': { name: 'Fernando el Católico', x: 13, y: 19.5 },
    'gran-via': { name: 'Gran Vía', x: 15, y: 19.5 },
    'plaza-aragon': { name: 'Plaza Aragón', x: 16.5, y: 18 },
    'plaza-de-espana': { name: 'Plaza de España', x: 17.5, y: 16.5 },
    'cesar-augusto': { name: 'César Augusto', x: 16.5, y: 15 },
    'plaza-del-pilar-murallas': { name: 'Plaza del Pilar-Murallas', x: 18, y: 13.5 },
    'la-chimenea': { name: 'La Chimenea', x: 18, y: 11.5 },
    'maria-montessori': { name: 'María Montessori', x: 18, y: 9.5 },
    'leon-felipe': { name: 'León Felipe', x: 16.5, y: 8.5 },
    'pablo-neruda': { name: 'Pablo Neruda', x: 15, y: 7 },
    'adolfo-aznar': { name: 'Adolfo Aznar', x: 15, y: 5 },
    'garcia-abril': { name: 'García Abril', x: 15, y: 3.5 },
    'campus-rio-ebro': { name: 'Campus Río Ebro', x: 15, y: 1.5 },
    juslibol: { name: 'Juslibol', x: 16.5, y: 0 },
    'parque-goya': { name: 'Parque Goya', x: 18.5, y: 0 },
    'avenida-de-la-academia': { name: 'Avenida de la Academia', x: 20.5, y: 0 },
    'margarita-xirgu': { name: 'Margarita Xirgu', x: 13.5, y: 3 },
    'legaz-lacambra': { name: 'Legaz Lacambra', x: 13.5, y: 5 },
    'clara-campoamor': { name: 'Clara Campoamor', x: 13.5, y: 7 },
    'rosalia-de-castro': { name: 'Rosalía de Castro', x: 15, y: 8.5 },
    'martinez-soria': { name: 'Martínez Soria', x: 16.5, y: 10 },
    'los-pajaros': { name: 'Los pájaros', x: 3.5, y: 28.5 },
    'cantando-bajo-la-lluvia': { name: 'Cantando bajo la lluvia', x: 2, y: 28.5 },
  },
};
