export default {
  id: "barcode-generator",
  name: "Barcode",
  tagline: "Code 128, EAN and Code 39 barcodes as SVG",
  category: "media",
  glyph: "|||",
  icon: "barcode",
  keywords: ["barcode","code128","ean","ean13","upc","code39","label","sku","retail"],
  tag: "jg-app-barcode-generator",
  window: {"width":820,"height":860},
  i18n: {
    de: { name: 'Barcode', tagline: 'Code 128, EAN und Code 39 als SVG' },
    es: { name: 'Código de barras', tagline: 'Códigos Code 128, EAN y Code 39 en SVG' },
    zh: { name: '条形码', tagline: '输出 SVG 格式的 Code 128、EAN 与 Code 39' },
    fr: { name: 'Code-barres', tagline: 'Codes 128, EAN et Code 39 en SVG' },
    pt: { name: 'Código de barras', tagline: 'Códigos 128, EAN e Code 39 em SVG' },
    ja: { name: 'バーコード', tagline: 'Code 128、EAN、Code 39 を SVG で' },
    ko: { name: '바코드', tagline: 'Code 128, EAN, Code 39을 SVG로' },
  },
  load: () => import('./index.js'),
};
